### ISSUE TITLE
Allow more complex parsing of citations in AOs

### ISSUE THREAD

**Issue by vrajmohan** [fecgov/openFEC#2276]
Find examples of citations that were not identified:

Identify citations even when they are not preceded by telltale markers like "U.S.C.", e,g., 
"18 U.S.C. §§610, 611, 613, 614 and 615". In this case we should identify 611, 613, 614 and 615.

In other cases, citations may be elided as in "18 U.S.C. §§610-615". In this case we should identify 610, 611, 612, 613, 614 and 615.

- [x] !! Figure out why AO's after 2017 aren't showing citations  - missing OCR text. Checking with Salient. https://www.fec.gov/data/legal/advisory-opinions/2017-01/
- [X] Find examples of missed citations: Regulatory and Statutory. Final opinions only.
- [X] Add tests 
- [X] Look for examples of multiples for MURs - I think this is ok, as it uses the database

### Background:
AOs, current MURs, and archived MURs all have different REGEX and data sources for regulations.

- AOs use OCR text in the `aouser.document` table that is currently missing for 23 AOs. AOs cite Statutes, Regulations, and other AOs using [REGEX here](https://github.com/fecgov/openFEC/blob/develop/webservices/legal_docs/advisory_opinions.py#L69-L76)
- Current MURs have a database of citations in `fecmur.violations.regulatory_citation` and uses [REGEX here](https://github.com/fecgov/openFEC/blob/develop/webservices/legal_docs/current_murs.py#L117-L119)
- Archived MURs were OCR'd by FEC and uses [REGEX here](https://github.com/fecgov/openFEC/blob/develop/webservices/legal_docs/load_legal_docs.py#L316-L340)

**Comment by lbeaufort** [comment]
Planning to address this in PI 6
