### ISSUE TITLE
RFAI missing from filings tab of committee profile page

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#2574]
C00332221 RFAI about a F1 at image location 201707060300087813

RFAI not avaiable on the filings tab of the committee profile page
https://www.fec.gov/data/committee/C00332221/?tab=filings#other

RFAI is avaialbe from filings page
https://www.fec.gov/data/filings/?data_type=processed&committee_id=C00332221&form_type=RFAI

The RFAI has duplicate rows in public.ofec_filings_mv. This is wrong. The sub_id should be a unique constraint on the view.  `select * from public.ofec_filings_mv where sub_id = 1070620170035525494;`

The view collects rows from `disclosure.f_rpt_or_form_sub` and `disclosure.nml_form_rfai`. I'm not sure I understand why. All RFAIs exist in `disclosure.f_rpt_or_form_sub`.  If we need additional information about RFAIs from `disclosure.nml_form_rfai` then we should exclude `FRQ`s from the `disclosure.f_rpt_or_form_sub` part of the script. 

select * from public.ofec_filings_mv where sub_id = 1070620170035525494;
returns two rows

select * from DISCLOSURE.NML_FORM_RFAI where sub_id = 1070620170035525494;
returns one row

select * from DISCLOSURE.F_RPT_OR_FORM_SUB where sub_id = 1070620170035525494;
returns one row
form_tp in this table is `FRQ`

**Comment by LindsayYoung** [comment]
This is the call the other documents on the profile pages It dosen't look like it includes RFAIs.
https://api.open.fec.gov/v1/committee/C00332221/filings/?api_key=DEMO_KEY&sort_hide_null=true&sort=-receipt_date&per_page=100&page=1&form_type=F1M&form_type=F8&form_type=F99&form_type=F12&cycle=2018

For the second case, that record is listed twice, once as FRQ and once as an RFAI. Is there a way to determine which record should be shown when it is listed twice?

**Comment by jontours** [comment]
Also to elaborate on why we are pulling data for RFAIs from the `nml_form_rfai`, in a previous iteration the table that we were generating filings from didn't have the RFAIs, can't remember the exact table but it wasn't  `F_RPT_OR_FORM_SUB`.  So that's the history to how this ended up like this, we can remove the code that pulls from `nml_form_rfai`, it would greatly simplify the script that generates the filings table.

**Comment by PaulClark2** [comment]
@LindsayYoung the sub_id is the same for the two rows.  That shouldn't happen. If the source is `F_RPT` then the correct row is `FRQ`.

**Comment by noahmanger** [comment]
@LindsayYoung we do include `RFAI` in the form type query for the very first table for reports. RFAIs typically come up there, as they [do on this page](https://www.fec.gov/data/committee/C00196774/?tab=filings&cycle=2016).

![image](https://user-images.githubusercontent.com/1696495/28883109-30d9ec78-7762-11e7-8196-1f4c926d612c.png)

**Comment by jontours** [comment]
Starting this fix now.  A *strong* note that the form type in the `f_rpt_or_form_sub` table is `FRQ`.  I'm guessing you can call them RFAIs on the front-end, but the filter on the front-end will need to be changed to `FRQ` when referencing RFAIs, or better yet maybe, I can wire that into the API logic.

**Comment by jontours** [comment]
In doing some debugging for this, I did find that the reason that the specific row was missing, or case number 1, is that it was some null columns for sorting, the api call is 

```
https://api.open.fec.gov/v1/committee/C00332221/filings/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=true&sort=-coverage_end_date&sort=report_type_full&sort=-beginning_image_number&per_page=100&page=1&form_type=F3&form_type=F3X&form_type=F3P&form_type=F3L&form_type=F4&form_type=F7&form_type=F13&form_type=RFAI&cycle=2018
```
But if you look at the columns needed for sorting from the database using this query:
```
select coverage_end_date, report_type_full, beginning_image_number from ofec_filings_mv where beginning_image_number ='201707060300087813' and form_type='FRQ';

 coverage_end_date | report_type_full | beginning_image_number 
-------------------+------------------+------------------------
                   |                  |     201707060300087813
```

Therefore this row never shows up in the results.  We could inject a dummy date into these values or maybe for the "other" type filings not apply a sort order?  Is the sort order needed for these filings?  And if it is maybe just apply beginning_image_number, as it's guaranteed to not be null it seems.

**Comment by PaulClark2** [comment]
@jontours thank you for figuring this out.  Some RFAIs, like those send about Form 1s and 2s and a few others, don't have coverage end dates. I'd suggest using the RFAI date (receipt date from `f_rpt_or_form_sub`.

**Comment by jontours** [comment]
Ok, I think that will help.  Also, I believe report_type_full should not be null for these, or at least we should be able to inject it when building the view.

**Comment by jontours** [comment]
My last comment is no longer valid.  Report_type_full is null for these as there is no temporal description to apply to these filings.  However, being that in this case these would be the first filing ever for the entity we may be able to add logic to the api to ignore this sort option in the case of a null report type.

**Comment by AmyKort** [comment]
Where are we with this one?

**Comment by pkfec** [comment]
@PaulClark2 
This issue is fixed here : https://github.com/fecgov/openFEC/issues/3440. 
Can you test and confirm that the RFAI's appear on filings tab of committee profile page in `dev` environment.
The fix will be deployed to `Production`during Release 7.5  on 11/20/1018

**Comment by patphongs** [comment]
This issue has been fixed, closing
