### ISSUE TITLE
Improve performance when automatically loading MURs

### ISSUE THREAD

**Issue by vrajmohan** [fecgov/openFEC#2646]
The code that refreshes MURs works by discovering the oldest document to be reloaded and then reloads every document after that. Unlike AOs, it is not only recent MURs that can be updated. Therefore this code is suboptimal for MURs. 

The code needs to be refactored to only reload the actual documents changed.

This issue has been created by pulling out the remaining work from #2445

 - Consider updating the view
- [ ] As part of this work, make a migration to filter for `case_type=MUR` for `cases_with_parsed_case_serial_numbers`. See https://github.com/18F/openFEC/blob/develop/data/migrations/V0021__fecmur_schema_objects.sql#L97
- [ ] Update team & docs with `load_current_murs` new flag is `-m` -  `./manage.py load_current_murs -m '2804R'`

**Comment by lbeaufort** [comment]
Once this work is done, we could explore having celery worker check for modified AOs and MURs more often - maybe every 5 min

**Comment by AmyKort** [comment]
Merged, so closing
