### ISSUE TITLE
Upgrade Swagger UI to most recent stable version

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#2851]
**What we’re after**:
Upgrade Swagger UI to the most recent stable version (3.x). We want to revisit the decisions made in #2770 and #2789. 

Version 3.x allows for deep linking to tags and operators. For example, a link something like https://api.open.fec.gov/developers/#!/audit would actually take you to the /audit/ section of the  API page. The 3.x user interface is more visually appealing. 

**Current state**:
We are currently using version 2.1.1-M2
- relies on unmaintained js dependencies
- possible security issue

**Completion criteria**:
- [ ] upgrade Swagger UI to the most recent stable version (3.x)

**Related issues or PRs**:
https://github.com/18F/openFEC/issues/2770
https://github.com/18F/openFEC/pull/2789

**Comment by ccostino** [comment]
I've started to dive into this some after a conversation with @patphongs in Slack yesterday, and this may be a rather significant undertaking but not completely insurmountable.  We noted that several dependencies on the Python side need to be upgraded to support the new OpenAPI Spec that Swagger UI is built off of, however the newest version does still support version 2.0 of it so we should be fine as far as our generated API documentation goes.

What may end up happening here to move this forward is a bit of rip the band-aid off situation.  Christine had already done the heavy lifting of bringing Swagger UI directly into the project itself and removing the external dependency we had setup previously, so it should now be possible to do a drop-in replacement with the new version, but that will wipe out any of our customizations.  We'll have to figure out what the best way to accomplish that will be, but once we do we can start determining how much more we want to customize again.

**Comment by patphongs** [comment]
Chunked this down to 2 tickets as it is a big lift. Closing in favor of the tickets below:

https://github.com/fecgov/openFEC/issues/3064

https://github.com/fecgov/openFEC/issues/3065
