### ISSUE TITLE
Create itemized tables (sched_b) and transfer data from fecp to postgresql database in cloud

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#2854]
This is derived from Issue #2686: Golden Gate data loading time.

**Comment by fecjjeng** [comment]
This issue is derived from issue #2686 and is related to issue #2724

**Comment by fecjjeng** [comment]
Currently, coding of the PL/SQL package and Java programs are done. Initial load and daily updates process to the cloud databases of the itemized tables are done. The tables are in separated set of tables in a different schema (disclosure) so not to impact any current APIs accessing the aggregate tables in public schema.

**Comment by LindsayYoung** [comment]
We will want to modify the API code- mostly model references so that it references the new tables. We will want to adjust the tests so that they use the schema  and we will want to add a migration that deletes the old tables.

**Comment by fecjjeng** [comment]
Comparison between table structure of disclosure.fec_fitem_sched_b (new) and public.ofec_sched_b_master (old), following is the result
<img width="1269" alt="sched_b_striucture_comparison" src="https://user-images.githubusercontent.com/24943130/37847042-df55b98a-2ea5-11e8-8527-16dbb6af9724.png">
public.ofec_sched_b_master (old) table has two more columns: timestamp and two_year_transaction_period.  
Data in column timestamp is used in queue tables processing, which will not be needed in the data population process for disclosure.fec_fitem_sched_b tables
Data in column two_year_transaction_period is exactly the same as in column election_cycle in each and every row, so it is not needed

**Comment by hcaofec** [comment]
need to check if column two_year_transaction_period is used by endpoints or materialized views or views before dropping it.
@fecjjeng @ccostino

**Comment by ccostino** [comment]
Yes, we've caught up about this some in Slack but need to have a full discussion around it.  The `two_year_transaction_period` is used by quite a few of the endpoints as it is the column that powers the partitions of the schedule A and B data for now (the `CHECK CONSTRAINT` is based off of it; the endpoints expect it as it's a required field, too.

There is an opportunity to consolidate and cleanup here, so I think we can find a path forward, we'll just have to go over everything and plan accordingly. :-)

**Comment by fecjjeng** [comment]
The FECP-driven tables use election_cycle to power the partitions of schedule A ad B  (the CHECK CONSTRAINT is based on the election_cycle column).  I think there is several possible route we can take.  We will discuss to see what is the best way to proceed.

**Comment by fecjjeng** [comment]
disclosure.fec_fitem_sched_b does not add the extra column two_year_transaction_period since column election_cycle and two_year_transaction_period in public.ofec_sched_b_master tables has exactly the same data.
However, existing API referencing column two_year_transaction_period a lot, it might be less impact to the API to just rename election_cycle to two_year_transaction_period without duplicated data when switching from using public.ofec_sched_b_master tables to disclosure.fec_fitem_sched_b table.  
The program that populate disclosure.fec_fitem_sched_b tables need to be updates and how to sync the DEV/STG/PRD will have to be considered (currently the same program populates all three databases, depending on the parameter passed in).  But might be a possible route.

**Comment by fecjjeng** [comment]
The calculation of value for recipient_name_text in both public.ofec_sched_b and disclosure.fec_fitem_sched_b are slightly incorrect.
It should use clean_recipient_cmte_id instead of recipient_cmte_id.  
Trigger function disclosure.fec_fitem_sched_b_insert() should have the calculation for recipient_name_text should be as followed:
new.recipient_name_text := to_tsvector(concat(new.recipient_nm,' ', new.clean_recipient_cmte_id));
Existing data in tables will need updated
