### ISSUE TITLE
Investigate issue with rename_indexes method in the DB

### ISSUE THREAD

**Issue by ccostino** [fecgov/openFEC#2871]
@hcaofec's and @fecjjeng's work with moving the aggregate tables in PR #2858 uncovered an issue with the `rename_indexes` method we built in the database.  This was built originally for the itemized schedule table construction and so it may not be as generic as we thought.  In any case, we should investigate this to make sure we can leverage it in the future.

We're not immediately able to reproduce this. We'll need to reconsider this the next time we move a table. Moving to icebox.

**Comment by lbeaufort** [comment]
I'll test this on my local db and see if I can get some examples

**Comment by lbeaufort** [comment]
I tested this locally and am unable to reproduce the issue.
