### ISSUE TITLE
Update "create_sample_db" task to run "refresh_materialized" task

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#2872]
Creating a test database from scratch with the task `invoke create_sample_db` doesn't populate materialized views because it doesn't run `refresh_materialized`.

We need to update the `create_sample_db` task to run `refresh_materialized` task and pass concurrently=False after populating the sample data (in other words, at the very end).

**Comment by vrajmohan** [comment]
Will roll this into #3062
