### ISSUE TITLE
Migration timeout fix

### ISSUE THREAD

**Issue by LindsayYoung** [fecgov/openFEC#2879]
This is something to consider for the next time we migrate one of the larger tables. The current automated setup is good for most changes but in the cases were we are changing views or tables that contain a lot of data, we will hit timeout issues. 

- [ ] consider whether we need to change the order, should we log in after the migrations run?
- [ ] expanding circle timeouts (This will help with most but not all migrations)
- [x] creating a java manifest for a migration app (that could create a headless app on demand with a java build pack to run flyway migrations that will take a long time.

**Comment by ccostino** [comment]
This is related to #2834 - the timeout is ultimately because the migration runs and the login token for the deployer account expires by the time it finishes.  We could probably do the migration first and the log the deployer account in to finish up the rest of the deployment.

**Comment by LindsayYoung** [comment]
done:
https://github.com/fecgov/openFEC/blob/develop/data/flyway/manifest_headless_flyway.yml

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by ccostino** [comment]
@AmyKort we're all set!  I may work on a small PR to adjust the continuous integration piece but with the piece we have in place we're at least covered now for accounting for these situations with long-running database migrations. :-)
