### ISSUE TITLE
Update cloud.gov manifest setup in API

### ISSUE THREAD

**Issue by ccostino** [fecgov/openFEC#2884]
[Manifest inheritance](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#minimize-duplication) has been deprecated in Cloud Foundry in favor of another type of setup using something called a YAML anchor.

Instead of inheriting manifest files from each other, you declare a defaults section in your manifest file that other sections then reference.  Unfortunately what this means for us is increased duplication since we have separate manifests for each space (and in the case of the API, separate manifests for each application to boot), but we want to make sure this is accounted for before the manifest inheritance is just shut off completely on us (this change happened about a year ago).

To update the API we'll have to do the following:

* [ ] Copy everything in the base manifest files to their respective application files for each space
* [ ] Make sure each manifest file for each application in each space still works as expected
* [ ] change host -> routes

**Comment by LindsayYoung** [comment]
Good catch! Thank you for making this ticket

**Comment by AmyKort** [comment]
Merged, so closing.
