### ISSUE TITLE
Filings Search timing out issue

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#2900]
THe campaign finance search is timing out on the filings page.  Sometimes it errors and sometimes it just doesn't do the search so the results don't change. 

Go here:
https://www.fec.gov/data/reports/house-senate/   

Choose Raw data and it will have about 16,000 rows

Search for C00657122 and it should return 1 row. Sometimes it does. Sometimes it stays on 16,000 without generating an error. This sounds like the behavior we had in the past when it was a performance issue.

**Comment by LindsayYoung** [comment]
Yes this sounds like a performance issue. We pulled the logs, looked at them with PG Badger and spent time looking at AWS metrics. It would be nice to circle back with everyone that looked at the logs.

**Comment by jwchumley** [comment]
@LindsayYoung  @ccostino  This seems fast now. Is it the result of completing another issue or is it random chance.

**Comment by ccostino** [comment]
I don't think any specific work has taken place since looking at the pgBadger reports, or at least I'm not recalling any, so I'm not sure we can say why this is the case.

**Comment by AmyKort** [comment]
Closing for now. Let's see of this problem resurfaces.
