### ISSUE TITLE
Improve performance for cache calls (#2749) & turn it on 

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#2913]
What we're after:

The work to cache calls was completed but is not performant so we need to figure out why and improve performance and put it into production

Detailed documentation in https://github.com/fecgov/openFEC/issues/2749

- [ ] Research to resolve performance issue

**Comment by pkfec** [comment]
For cached calls, we observed that the requests are being cached before the request is completed. That added a big performance hit on the website. It looks like we no longer can use the after_request decorator. 
Thinking of any alternatives like the celery worker could be feasible. Started some research work on how to use celery worker for caching the calls.

**Comment by pkfec** [comment]
**To do's #**

- Move the Cached_Calls to celery task
- Rewrite the after_request to create a celery task

**Comment by pkfec** [comment]
@LindsayYoung : How do i configure the celery worker/beat to cache the requests in real time?

**Comment by pkfec** [comment]
Save and Retrieve Cache calls PR is merged to develop. 
TODO :# Run the load test (locust) to make sure it doesn't impact the application performance and is working as expected in Dev and or in Stage once this change gets deployed.

**Comment by AmyKort** [comment]
I'm going to close this issue and make a new ticket for the load testing.
