### ISSUE TITLE
Upgrade API to use Elasticsearch 5.6

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#2921]
Cloud.gov now has support for Elasticsearch version 5.6 (wohoo!) [more info here](https://cloud.gov/docs/services/elasticsearch56/), which may improve some of the performance issues we've been having with our current version (2.4). 

Also, cloud.gov may end support for 2.4 in the medium-term future.

- [x] pre-update load testing baseline - dev and local. [Saved here] (https://drive.google.com/drive/folders/1F4lFVVC6gFfN7rwhfNl41WvhUBkksimp?ths=true)
- [x] Redo local testing after loading all AO's and MURs? Restore snapshot for consistency?
- [x] How do we deal with backups and/or reloading archived MURs onto new version? Looks like we can restore a 2.X snapshot to 5.x - https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html
- [x] Test elasticsearch v. 5.6 locally -loading docs, reindexing, load test, check out the front-end, API, etc
- [x] update `requirements.txt` and manual deploy. Update service? https://cloud.gov/docs/services/elasticsearch56/
- [x] manual testing of dev - front-end, API, loading docs, reindexing, etc
- [x] load testing dev - confirm no performance hit and possible improvement
- [x] Update README.md

### Remaining items
- [x] delete 2.4 service instance on `dev` once the PR is merged:  `cf delete-service SERVICE_INSTANCE`
**Before release cut on 5/22:**
- [X] Create 5.6 service instances in `stage`: `cf create-service elasticsearch56 medium-ha fec-api-search56`
- [x] use a headless app to bind to the 5.6 instances 
- [x] restore from snapshot so we will have no downtime
**After release cut on 5/22:**
- [x] Reload legal docs to be sure everything looks good
- [x] delete the 2.4 service instance
**Before deployment on 5/29:**
- [x] Repeat above steps for the `prod` space
**After deployment on 5/29:**
- [x] delete the 2.4 service instance

From cloud.gov: "Elasticsearch version 5.6 is now available. This includes performance improvements and new features. We recommend upgrading from version 2.4 to 5.6, but we don’t have **near-term** plans to end support for 2.4. "

**Comment by lbeaufort** [comment]
@fec-jli requested that we pair on this during the first week of 5.5 before she goes on vacation

**Comment by pkfec** [comment]
Create Elastic Search 5.6 service instances in Production: cf create-service elasticsearch56 medium-ha fec-api-search56 during the release on May 30th

**Comment by lbeaufort** [comment]
No remaining items for this ticket. Thanks for all your hard work! @vrajmohan  @pkfec  @fec-jli

**Comment by lbeaufort** [comment]
@vrajmohan  I confirmed doc counts on `prod` here: https://docs.google.com/spreadsheets/d/1Ksb3mjwsTKcdAwkRkP8n3e6KrNmoZor_WP1ipDQmibo/edit#gid=0

Archived MURs	4445
Current Murs	2160
advisory_opionions	1989
citations 	531
regs	529
statutes	57
	
	
Total All	9711
