### ISSUE TITLE
API user request: add transaction ID and amendment ID to /schedules/schedule_e/ endpoint

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#2925]
So that an API user for a campaign finance research group can analyze independent expenditures properly, we should add amendment ID to the `/schedules/schedule_e/` endpoint. The field `sub_id` appears to be the primary key on `ofec_schedule_e`, but when I asked the user to see if that was what they were looking for, they said the `sub_id` varied so much from record to record. It could be `1, SE.4107,VQZETADMPM8`.

Without the transaction ID and amendment ID, it's very difficult to properly track expenditures.
```
/schedules/schedule_e/
/schedules/schedule_e/by_candidate/
/schedules/schedule_e/efile/
```
- [ ] check if these fields are in the MV/Model
- [ ] add these fields to the schema
- [ ] investigate `sub_id` and how it's generated. Is this supposed to be the transaction ID? Could this be inconsistent between paper and efiled reports?

**Comment by jason-upchurch** [comment]
I reviewed `ofec_sched_e_mv` which has an identifier `tran_id` which might be a good candidate for `transaction_id`.

For the `amendment_id` issue, maybe we can use `amdnt_number`.

**Comment by jason-upchurch** [comment]
in `models/itemized.py` there is the line
transaction_id = db.Column('tran_id', db.Integer)
```
and in the `/schedules/schedule_e/` api, the example value shows `transaction_id` but this field does not appear in the data, only `back_reference_transaction_id` appears in the output

**Comment by jason-upchurch** [comment]
in `ofec_sched_e_mv` the identifier `tran_id` is specified as `character varying` but in `itemized.py` specified as `transaction_id = db.Column('tran_id', db.Integer)`.

Verified `ofec_sched_e_mv` values for `tran_id` are not integers, i.e., examples are alphanumeric with special characters (hyphen, period)

**Comment by jason-upchurch** [comment]
related issue #3750 and PR #3751 to fix datatype for `transaction_id` and `back_reference_transaction_id` to `String` (incorrectly specified as `Integer` in a couple of places)

**Comment by jason-upchurch** [comment]
`schedules/schedule_e/efile/` and `schedules/schedule_e/` will correctly show `transaction_id` with #3751. 

blockers:
* Does this field need to be added to `/schedules/schedule_e/by_candidate/`?
* Is `amendment_number` a sufficient field to have in conjunction with `transaction_id`? Currently `amendment_number` exists in `/schedules/schedule_e/` and `/schedules/schedule_e/efile/`. Is it needed in `/schedules/shedule_e/by_candidate/`

**Comment by jason-upchurch** [comment]
waiting for merge of #3751 to see if that resolves issue.

**Comment by pkfec** [comment]
@jason-upchurch  PR https://github.com/fecgov/openFEC/pull/3751 is merged already. Can you pull the latest changes and test to see if this #3751  resolves your current issue?

**Comment by jason-upchurch** [comment]
Thanks @pkfec! I'll consult @lbeaufort and contact the original user reporting the issue to see if  they can get what they need, or if we still may need to add other fields.

**Comment by jason-upchurch** [comment]
Contacted original reporting user to advise of related bug fix and to ask if they continue to have any problems using this endpoint.

**Comment by dorothyyeager** [comment]
Closing. We can reopen if he contacts us with any new problems.
