### ISSUE TITLE
Investigate and fix 500 errors for unexpected parameters passed to /legal/search/ endpoint

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#2934]
The `/legal/search` endpoint is throwing 500 errors for some unexpected query parameters. We should change this endpoint to handle unexpected parameters without throwing 500 errors. 

**Example of not throwing error:**
https://api.open.fec.gov/v1/candidates/?name=smith&api_key=DEMO_KEY&nonsenseword=nonsenseword

**Example of 500 error:** https://api.open.fec.gov/v1/legal/search/?type=nonsensewords&api_key=DEMO_KEY

- [ ] figure out which parameters/inputs are causing 500 errors (see Kibana logs from 2/16/18 ~8:15am) on the `/legal/` endpoint
- [ ] change the `/legal/` endpoint to handle unexpected parameters without throwing 500 errors.

**Comment by AmyKort** [comment]
cc @LindsayYoung and @ccostino

**Comment by AmyKort** [comment]
Is this ready to close?
