### ISSUE TITLE
Create API endpoint for state election information

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#2938]
Users report wanting "one stop shopping" for information about elections at the state and district level. To meet this need, we've taken steps at https://github.com/fecgov/openFEC/issues/2919 to add state election official contact information to the API. The next step is to create an API endpoint for state election official information.

Completion criteria:
- [x] check out the OpenFEC wiki
- [x] include all fields and all filters
- [x] create endpoint
- [x] tests

**Comment by AmyKort** [comment]
What's the status on this?

**Comment by pkfec** [comment]
created a new **state-election-office** endpoint.

**Comment by AmyKort** [comment]
Merged, so closing.
