### ISSUE TITLE
Mid-PI check-in

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#2944]
At the end of this sprint, we need to meet as a team and reconsider the rest of the work we've planned for the PI. This should be a full team meeting.

Completion criteria:

- [x] schedule meeting
- [x] put together overview of where we're at and what we have planned
- [x] what's our velocity?
- [x] we've made some changes to our processes--is this helping our velocity?
- [x] confidence vote for the rest of the PI

**Comment by AmyKort** [comment]
Thanks everybody!
