### ISSUE TITLE
Figure out if any other API changes or new endpoints are needed for the Election "About" section

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#2948]
**What we're after:** In order to include the required data on the new election summary pages, specifically the `Candidate information` table on the new `About this election` page, we need to determine whether any new API endpoints are needed. 

The below design includes candidate name, political party/affiliation, and principal campaign committee. We need to figure out whether a new endpoint is required. 

**Design:** 
<img width="698" alt="screen shot 2018-02-27 at 1 10 38 pm" src="https://user-images.githubusercontent.com/31663028/36746418-4607c518-1bc0-11e8-909d-5620a230a61c.png">

**Completion criteria:**
- [ ] Research existing API endpoints
- [ ] Determine if existing API endpoints are sufficient
- [ ] Determine modifications to existing endpoints or document new endpoint requirements
- [ ] Create implemention issue

**Comment by AmyKort** [comment]
We need to check endpoints related to PCCs v. affiliated committees.

**Comment by patphongs** [comment]
Closing this issue as finished. This issue has been spread out to 2 separate tickets linked in the comment above.
