### ISSUE TITLE
Transfer openFEC GitHub repo to FEC

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#2950]
- [x] [openFEC](https://github.com/18F/openfec): the first RESTful API for the Federal Election Commission
    - [x] delete fec's current openFEC fork
    - [x] set up circle (there are a lot of env vars for this repo)
    - [x] set up Slack web hooks
    - [x] set up gemnasium alerts
    - [x] confirm code coverage ports over
   - [x] Lindsay makes a copy for 18F's records
   - [X] dev's are informed of how to change the remote origin to `fecgov` org:
```git remote set-url origin git@github.com:fecgov/openFEC.git```

**Comment by LindsayYoung** [comment]
Added a subtask above-we will need to delete the fecgov fork before we make the transfer

**Comment by AmyKort** [comment]
@ccostino and @LindsayYoung

**Comment by lbeaufort** [comment]
All done! 🎉
