### ISSUE TITLE
Research on approach to execute migrations separately from regular build

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#2958]
Some database migration, such as adding indexes to tables with large amount of data, are resource intensive and will take long time to complete.   This will potentially create timeout issue during release time since it compete with resource for user query.  An approach need to be developed to execute migration separately from the build, in a less traffic time frame.

**Comment by fecjjeng** [comment]
Lindsay mentioned possible approach would be
- headless API
- Java manifest
- Modify CircleCI task to run the migration only

**Comment by fecjjeng** [comment]
Vraj had a java based headless API to handle this task.  It is in [PR #2964,(https://github.com/18F/openFEC/pull/2964) which had been merged in DEV.

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by fecjjeng** [comment]
Yes.


On Mar 15, 2018, at 12:51 PM, Amy Kort <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this ready to close?
