### ISSUE TITLE
Investigate why 422 (missing parameters) errors are coming through as 500 (Internal Server) errors

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#2962]
We've designed the API to throw 422 (missing parameters) errors when required parameters are missing. However, it looks like the production environment is throwing 500 (internal server) errors when we're trying to throw 422 errors. This is problematic in that it makes user errors look like API bugs and time-consuming to diagnose.

Locally, this throws a 422 for missing district but throws a 500 on the server: 

500 error:
https://api.open.fec.gov/v1/elections/?API_KEY=DEMO_KEY

422 error:
http://localhost:5000/v1/elections/

```
{
message: {
cycle: [
"Missing data for required field."
],
office: [
"Missing data for required field."
]
},
status: 422
}
```

We should make sure our develop/stage/production environment return the proper server errors.

**Comment by lbeaufort** [comment]
Update: it looks like production servers might be throwing 500 when we're trying to throw 422 errors. Locally, this throws a 422 for missing district but throws a 500 on the server. 

see `check_election_arguments`: https://github.com/18F/openFEC/blob/develop/webservices/utils.py

**Comment by ccostino** [comment]
Furthermore, it appears that `office` is required for this endpoint but it is not showing up as required in the API (Swagger) docs.  Compounding that is the fact that `district` is a conditionally required parameter if `office` is present, so there are a few things that need to be adjusted and double checked to make sure this is wired up correctly.

**Comment by ccostino** [comment]
It seems like there are two things happening here:

* `ApiErrror` exceptions aren't being surfaced properly, which could be impacting the API in a broad manner
* This particular endpoint (`/elections`) is not properly handling its required and conditional arguments

**Comment by lbeaufort** [comment]
@PaulClark2 @jwchumley - This error was reported by an API user - it definitely causes usability problems for data users.

**Comment by lbeaufort** [comment]
@ccostino @LindsayYoung : I think the issue and a workaround are described here, but I don't really follow the technical implementation of workaround. Do you mind taking a look?

Issue: https://github.com/flask-restful/flask-restful/issues/280
Workaround: https://github.com/flask-restful/flask-restful/issues/280#issuecomment-280648790

**Comment by lbeaufort** [comment]
@fec-jli it looks like it's swallowing the 400 error you're expecting here too:
From https://github.com/fecgov/openFEC/pull/3002
-[3] if q with nonsenseword parameter, will get 500 error on prod, after release will catch 400 exception.
https://fec-dev-api.app.cloud.gov/v1/legal/search/?type=regulations&q=+public+%26%26+type+%25SystemRoot%25%5C%5Cwin.ini+%26%26+&hits_returned=20&from_hit=0&api_key=DEMO_KEY

**Comment by lbeaufort** [comment]
@vrajmohan @fec-jli - I confirmed this fix works in the `dev` space for both the /elections/ and /legal/ examples above.
