### ISSUE TITLE
Required API parameters are not marked as required in rest.py

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#2963]
So that users get the data they need from the API, required API parameters should be marked as `required` in Swagger.

 For example, the /elections/ endpoint requires office and will throw a 422 error if it's not provided. Office should be marked `required=true` in `rest.py`. This is further complicated by the fact that we're currently unable to display 422 errors - they're showing as 500 errors. See issue https://github.com/18F/openFEC/issues/2962

- [ ] Make sure required API parameters are marked as required in rest.py
 - cycle and office in /elections/ for example

**Comment by patphongs** [comment]
This has been completed...
