### ISSUE TITLE
Update Docker Buildpack for Circle Builds

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#2972]
Mirroring issue for fec-cms repo here: https://github.com/18F/fec-cms/issues/1824

- [ ] In the circleci config, we need to update the config to use
`- image: circleci/python:3.5.5`

We are using docker images from here: https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/python/images

- [ ] Also we can update runtime.txt to `python-3.5.X` to be consistent with our docker builds. The carrot will make sure that we are to the latest python version within 3.5.

From Circle: 
-----> Installing python 3.5.4
       Download [https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.4-linux-x64-5c7aa3b0.tgz]
       **WARNING** A newer version of python is available in this buildpack. Please adjust your app to use version 3.5.5 instead of version 3.5.4 as soon as possible. Old versions of python are only provided to assist in migrating to newer versions.

**Comment by AmyKort** [comment]
resolved
