### ISSUE TITLE
Add cycle parameter to schedules/schedule_f` endpoint

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/openFEC#2981]
- [x] Add `cycle` parameter to `schedules/schedule_f` endpoint
- [x] Add indexes based off these fields?

Related issue:
Addresses: https://github.com/18F/fec-cms/issues/1821

Related PR:
https://github.com/18F/fec-cms/pull/1830

**Comment by lbeaufort** [comment]
Addressed by fecgov/openFEC #2982
