### ISSUE TITLE
remove extra coalesce function in schedule B query

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#2988]
extra coalesce function was found in schedule B query which cause slow performance.  Need to remove this extra function.

WHERE ofec_sched_b_master.two_year_transaction_period = 2016 AND **(COALESCE (COALESCE (ofec_sched_b_master.disb_dt, CAST ('9999-12-31' AS DATE)), '9999-12-31'::date),** ofec_sched_b_master.sub_id) > ('2016-03-03'::date, 4070720161305573871) ORDER BY COALESCE (ofec_sched_b_master.disb_dt, CAST ('9999-12-31' AS DATE)) ASC, ofec_sched_b_master.sub_id ASC LIMIT 100

#2922

**Comment by AmyKort** [comment]
Merged, so closing.
