### ISSUE TITLE
Create rules for software development version

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#2997]
When we get the time, we need to figure out software development version tag rules. These rules will help us increment our software versions (ex: fec-cms, openfec) to tag major breaking changes vs minor changes / bug fixes. 

Documentation about how to use semantic versioning: https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by fec-jli** [comment]
How to use Semantic Versioning:
[`https://docs.npmjs.com/getting-started/semantic-versioning`](https://docs.npmjs.com/getting-started/semantic-versioning)

**Comment by fec-jli** [comment]
![image](https://user-images.githubusercontent.com/24395751/37166228-89881b18-22cc-11e8-90c5-6df1a1a2798a.png)
