### ISSUE TITLE
Create itemized sched_e related tables and transfer data from fecp to postgresql database in cloud

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3007]
This is derived from Issue #2686: Golden Gate data loading time.

This issue is part of the first step of switching to the FECP driven itemized tables.  It is related to issue #2854 and issue #3006; Since some of the itemized tables has huge amount of data and partitioned tables, there are 3 issues created:
one for sched_a, one for sched_b and one for other smaller sched tables.

Currently, coding of the PL/SQL package and Java programs are done. Initial load and daily updates process to the cloud databases of the itemized tables are done. The tables are in separated set of tables in a different schema (disclosure) so not to impact any current APIs accessing the aggregate tables in public schema.

**Comment by jwchumley** [comment]
@fecjjeng What is left to do on this ticket?

**Comment by fecjjeng** [comment]
There are 3 tickets opened for the first step of switching to the fecp driven itemized tables.

Step 1:
Create tables, transfer data, verify data and structure are compatible to the tables currently being used, added appropriate indexes for these tables.

These tables had been created, data are daily updated for almost a year.
What left to do are verify data and structure are compatible to the tables currently being used, added appropriate indexes for these tables.

Originally we only have 1 ticket for all the itemized tables and really it is a really big task to fit into one ticket so we separated them into schedule_a (and its partitioned tables), shed_b (and its partitioned tables), and other itemized tables.

Step 2:
Switch API and materialized views to use the fecp driven tables.  Again, we plan to separate them into 3 tickets

Step 3:
Drop objects related to the old tables (the tables them self, the queue tables, the triggers in the f-item, shed_a, shed_b tables, procedures utilized by the refreshing process of the old tables, and the test procedures for these tables)

I will suggest to follow one set of tables (shed_b and its partitioned tables, for example) through all three steps then go for another set.



On Mar 16, 2018, at 11:46 AM, Jeff Chumley <notifications@github.com<mailto:notifications@github.com>> wrote:


@fecjjeng<https://github.com/fecjjeng> What is left to do on this ticket?

**Comment by fecjjeng** [comment]
Structure comparisons:
fec_fitem_sched_e vs fec_fitem_sched_e_vw:
![image](https://user-images.githubusercontent.com/24943130/43024025-ddead254-8c3a-11e8-8901-dd846c10077a.png)

**Comment by fecjjeng** [comment]
Data Comparisons:
no difference except pg_date (due to loading time difference)
fec_fitem_sched_e vs fec_fitem_sched_e_vw:
No difference
fec_fitem_f57_vw vs fec_fitem_f57:
No difference
ofec_sched_e_mv vs ofec_sched_e:
No difference except pg_date

**Comment by JonellaCulmer** [comment]
The PR has been merged, so closing this issue.
