### ISSUE TITLE
Once cache calls are in prod adjust manifest

### ISSUE THREAD

**Issue by LindsayYoung** [fecgov/openFEC#3008]
After we deploy the cached-calls to production we will want to take them off of dev and staging.
We can do by setting variables in the manifest, CACHE_ALL_REQUESTS=True should only be set in production once it is tested on dev and stage. 

- this is a small clean up task for the future

**Comment by pkfec** [comment]
CACHE_ALL_REQUESTS=True is set on the PROD manifest files. This is getting deployed to Prod during the 5.2 release on Wednesday 04/04.
