### ISSUE TITLE
auto delete s3 cached requests after 3 days

### ISSUE THREAD

**Issue by LindsayYoung** [fecgov/openFEC#3009]
We can do this when we are creating the files by setting an expiration date.

A little bit of research and probably a one line change.
pass argument via boto

This is a clean up task from #2749

**Comment by pkfec** [comment]
@AmyKort @PaulClark2 @jwchumley 
For how long should we save the data in S3 cached-calls folder? Should we purge the cached-calls folder on S3 every 3 days or even before?

I am working on creating a scheduled task to run every day to clear the cached-call on S3 folder for now. 

cc @ccostino

**Comment by AmyKort** [comment]
I'll defer to @jwchumley and @PaulClark2

**Comment by PaulClark2** [comment]
@pkfec the entire folder and its contents get deleted, correct. The delete process doesn't make decisions to remove individual files based on how old they are. In other words, if we establish a 2-day schedule for deleting the cached-calls folder, a file that was saved in that folder 30 minutes before the delete process starts would get deleted, correct?

**Comment by jwchumley** [comment]
If Paul is correct I'd argue that daily deletes would be best. 4:00 am or there about.

**Comment by ccostino** [comment]
I think we could do this one of two ways:

* The way you describe @PaulClark2, where at a set time each day the entire contents of the folder is just cleared out
* Or, check to see which items in the folder are older than the current date/time of the process running and only remove those items.

Either would work, I think it's just a matter of what makes the most sense.  The cached files are updated upon every successful API request, so within a 2 or 3 day period I'd imagine at least the more popular endpoints would have relatively fresh caches associated with them, while the less popular ones might have at least something stored.

Another thought:  we could also add one more piece of metadata to the API responses the indicate where or not a response is cached (e.g., `is_cached: true/false`).  This wouldn't have to be exposed to the front-end, it'd be just more of something to help double check things if you're looking at an API response directly.  If this sounds like a good idea I can write out a more fleshed out issue with completion criteria for future grooming/planning.

**Comment by pkfec** [comment]
a scheduled task runs every day @1pm and deleted the cached-calls folder from s3. This task is already merged to develop branch and getting deployed to Prod on  Wednesday 04/04 (5.2 release)
