### ISSUE TITLE
drop mv public.ofec_candidate_flag

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3017]
public.ofec_candidate_flag was renamed to public.ofec_candidate_flag_mv in migration script V0059.  But in order to run a time/resource consuming migration script V0060 the night before the code release to avoid time-out issues during high traffic hour, public.ofec_candidate_flag is temporarily added back.  It should be dropped to finish the work.

**Comment by AmyKort** [comment]
Merged, so closing.
