### ISSUE TITLE
Clicking aggregates on IE table should take users to filtered results, not all IEs

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#3043]
**What we're after:** The independent expenditures table on election profile pages include aggregates of the total money spent by a committee in IEs to support or oppose a specific candidate. Upon clicking on that aggregate amount, users should be taken to the list of transactions that contribute to that total. Unfortunately, when clicking on the aggregate amount, users are taken to an unfiltered table that lists all IEs.

This should be corrected so that upon clicking on the aggregate amount, users see a filtered list of only those IEs that contribute to that aggregate IE total. 

**Example:**
_Before:_
https://www.fec.gov/data/elections/senate/AZ/2018/?tab=spending-by-others
<img width="833" alt="screen shot 2018-04-04 at 8 59 57 am" src="https://user-images.githubusercontent.com/31663028/38309041-dec87292-37e6-11e8-9325-c9ba905cf1a3.png">
<img width="965" alt="screen shot 2018-04-04 at 9 00 55 am" src="https://user-images.githubusercontent.com/31663028/38309049-e8dbb816-37e6-11e8-9d18-5dd4212f2862.png">

_After:_
<img width="917" alt="screen shot 2018-04-04 at 9 01 47 am" src="https://user-images.githubusercontent.com/31663028/38309065-f4e1f418-37e6-11e8-9f79-ea88f5d43c0a.png">

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/fec-cms #1902](https://github.com/fecgov/fec-cms/issues/1902) via [**ZenHub**](https://www.zenhub.com/)
