### ISSUE TITLE
Switching API to the fecp-driven sched_b tables

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3045]
This is to deploy the work completed in derived from #2854 

We are switching API to access fecp-driven sched_b tables.

make API code changes to use fecp-driven sched_b tables
modify view definition scripts that utilize these tables
evaluate and create appropriate indexes on the fecp-driven sched_b tables

**Comment by fecjjeng** [comment]
fec_fitem_sched_b tables prior to election cycle 2002 do not have as many data and also are less queried.  Howefer, as suggested by Carlo, for consistency, and also for possible future feature of multiple-cycle queries, indexes still added for election cycle 1976 to 2002

**Comment by patphongs** [comment]
The dependency https://github.com/fecgov/openfec/issues/3098 will be worked on in sprint 5.6. @ccostino @fecjjeng has confirmed that we will be leaving the tables and related processes in place for now as a safety net and still deploying these changes.
