### ISSUE TITLE
Analyze and optimize one slow ScheduleA query

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3050]
Per @PaulClark2: We've made some big improvements on Schedule B performance, but we're still having some issues with Schedule A query timeouts.

Optimize Schedule A: 
- [ ] Identify slow Schedule A queries by following the instructions here: https://github.com/fecgov/openFEC/wiki/Analyzing-slow-queries or by looking at 500 errors in Kibana or talking to @rjayasekera who has been compiling them
- [ ] Analyze slow queries: https://github.com/fecgov/openFEC/wiki/Notes-on-Performance-Optimization
- [ ] Make necessary SQL/SQLalchemy/DB index changes to improve performance

Related issues: 
https://github.com/fecgov/fec-cms/issues/1534
https://github.com/fecgov/openFEC/issues/2373
https://github.com/fecgov/openFEC/issues/2756
https://github.com/fecgov/openFEC/issues/2791

**Comment by lbeaufort** [comment]
@PaulClark2 we could use help scoping this issue.

**Comment by JonellaCulmer** [comment]
We plan to change the scope of this ticket and make it a regular check-in ticket similar to our check logs tickets. @rjayasekera will create the documentation in order for staff to analyze queries themselves and will see how it goes.

- [ ] create documentation
- [ ] create ticket for next sprint (8.5)

**Comment by JonellaCulmer** [comment]
Here's where we document the slow queries in pgbadger: https://drive.google.com/drive/folders/1z57CHj33ib77SfR-oC0lzZcIQZfD0W6h

Here's where we document the slow queries in AWS logs:
https://drive.google.com/drive/folders/1weq69OrC47x_4tmlg099FeEpOH-oQCEN

**Comment by JonellaCulmer** [comment]
Created regular slow query check-in ticket here: https://github.com/fecgov/openFEC/issues/3664

This will be a regular ticket, every sprint, similar to the check snyk vulnerabilities ticket.
