### ISSUE TITLE
Reload legal docs on `stage` and `prod` after their respective deployments (4/11 and 4/18)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3052]
This arises from an Elasticsearch schema change with issue https://github.com/fecgov/openFEC/issues/2803

`cf run-task api  "python manage.py refresh_current_legal_docs_zero_downtime" -m 4G --name refresh-legal-[date]-terminate-after-[date]`

- [x] Reload legal docs on `stage` after release is cut 4/11/18
- [x] Reload legal docs on  `prod` after release is deployed 4/18/18

**Comment by pkfec** [comment]
Load the latest legal docs in prod.This task is completed.
