### ISSUE TITLE
Enable zipcode search for foreign zipcodes 

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3054]
As a follow-up to the changes here https://github.com/fecgov/openFEC/pull/3012/files we should enable zipcode search for foreign zipcodes.

From an API user: 

>We saw that the change was made to the API to support 9 digit zips within the 5 digit zip search - that is really great, and very helpful, thank you for making this happen!

>One thing we did notice is that foreign postal codes no longer seem to be supported, and when we call the API with one of those postal codes (say for London) we get an error. I'm not quite sure on the best way to handle that but just wanted to flag it for you. 

London zipcode format: `SW1A 1AA`
Canada zipcode: `A1A 1A1`

Example : https://api.open.fec.gov/v1/schedules/schedule_a/?sort=contribution_receipt_date&contributor_zip=SW1A%201AA&two_year_transaction_period=2018&api_key=DEMO_KEY&per_page=20

- [x] Enable zipcode search for zipcodes greater than 5 digits
- [x] Match on the first 5 characters
- [x] Test performance of /schedules/schedule_a/

cc: @PaulClark2 @jwchumley

**Comment by vrajmohan** [comment]
This may have been introduced by https://github.com/fecgov/openFEC/issues/2980

**Comment by hcaofec** [comment]
in the process of getting consensus on business rules with PMs.
