### ISSUE TITLE
Research - Leadership PAC sponsor: candidate ID missing

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3056]
**What we’re after**:
To help users identify sponsors of leadership PACs we need to include more helpful information on the data page and in the download file. We need to include more useful data from the Form 1: affiliated candidate name (l_nm and f_nm) and affiliated committee.  We need to include the information the committee submits as  affiliated committee in a way that does not mislead users to think leadership PACs are affiliated with a candidate's PCC.

**Current state**:
The download includes a candidate ID column but it is usually unpopulated. 

**Completion criteria**:
- [ ] develop a strategy to provide better leadership PAC data

**Comment by AmyKort** [comment]
@dorothyyeager might help with H4CC information to help filers too.

**Comment by dorothyyeager** [comment]
Updating my comment above - not sure that reporting example mentioned will actually be all that pertinent. We'll make sure the tip is super-specific.

**Comment by dorothyyeager** [comment]
Just to circle back and let @PaulClark2 @AmyKort @jwchumley know that the Information Division published the requested tip for treasurers on disclosing your leadership PAC-related candidate on Form 1. https://www.fec.gov/updates/leadership-pacs-identify-their-sponsors-fec-form-1/

**Comment by AmyKort** [comment]
Let's close this issue, since the Tip was the planned work associated with the ticket.
