### ISSUE TITLE
Update sample_db SQL to include test data for all MV's 

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3062]
In order to give developers a local database in which they can run tests, etc., we should include sample data in our materialized views. 

https://github.com/fecgov/openFEC/blob/develop/data/sample_db.sql

- [x] We should have a little bit of sample data for every MV in our sample_db file. If it's not feasible to do them all, we could look at the one that are in `update_materialized`
- [x] take care of #2872 - update the create_sample_db task to run refresh_materialized task and pass concurrently=False after populating the sample data (in other words, at the very end).
- [x] take care of #3047 - create MVs WITH DATA.

**Comment by vrajmohan** [comment]
From #2872: 

> Creating a test database from scratch with the task invoke create_sample_db doesn't populate materialized views because it doesn't run refresh_materialized. We need to update the create_sample_db task to run refresh_materialized task and pass concurrently=False after populating the sample data (in other words, at the very end).

**Comment by vrajmohan** [comment]
As part of this we can also take care of #3047 - create MVs `WITH DATA`.

**Comment by vrajmohan** [comment]
This story was identified as a pairing opportunity. I would like to help if i can.

**Comment by wjiangFEC** [comment]
I have a DBA team discussion today about this sample DB request. I will reach out to Vraj and developers to understand more about the requirements for the sample data.

**Comment by wjiangFEC** [comment]
Chat with Vraj today.  Sample_db.sql (https://github.com/18F/openFEC/blob/develop/data/sample_db.sql) creates a set of sample data.  The constraints of the data have been taken into consideration when the data was generated.  Most of the MVs have data in it.  We will look into those MVs that don't have data.

**Comment by wjiangFEC** [comment]
Thank you, Vraj.  We will check these MVs to find out which one does not have data.  We will also list them by order from top level to sub-level, so the MVs can be refreshed top level first, then sub-level.  Those no data MVs can have MV refresh statement added to sample_db.sql to orderly refresh MVs from top level to sub-level.

**Comment by vrajmohan** [comment]
I've already reviewed the MVs above for data and put a checkmark against those that do have data.

**Comment by wjiangFEC** [comment]
Thanks, Vrai.  Below is the output of the record counts from the MVs after running sample_db.sql and MV refresh.
select count(*) from ofec_amendments_mv;
 count 
-------
    17

 select count(*) from ofec_audit_case_category_rel_mv;
 count 
-------
    55
 
 select count(*) from ofec_audit_case_mv;
 count 
-------
   166
 
 select count(*) from ofec_audit_case_sub_category_rel_mv;
 count 
-------
    56
 
 select count(*) from ofec_cand_cmte_linkage_mv;
 count 
-------
    29
 
 select count(*) from ofec_candidate_detail_mv;
 count 
-------
    25
 
 select count(*) from ofec_candidate_election_mv;
 count 
-------
    25
 
 select count(*) from ofec_candidate_flag_mv;
 count 
-------
    25
 
 select count(*) from ofec_candidate_fulltext_audit_mv;
 count 
-------
     0
 select count(*) from ofec_candidate_fulltext_mv;
 count 
-------
    25
 
 select count(*) from ofec_candidate_history_latest_mv;
 count 
-------
    12
 
 select count(*) from ofec_candidate_history_mv;
 count 
-------
    25
 
 select count(*) from ofec_candidate_totals_mv;
 count 
-------
     0
 
 select count(*) from ofec_candidate_totals_with_0s_mv;
 count 
-------
    25
 
 select count(*) from ofec_committee_detail_mv;
 count 
-------
    32
 
 select count(*) from ofec_committee_fulltext_audit_mv;
 count 
-------
     0
 
 select count(*) from ofec_committee_fulltext_mv;
 count 
-------
    32
 
 select count(*) from ofec_committee_history_mv;
 count 
-------
    32
 
 select count(*) from ofec_communication_cost_aggregate_candidate_mv;
 count 
-------
     0
 
 select count(*) from ofec_communication_cost_mv;
 count 
-------
     0
 
 select count(*) from ofec_election_result_mv;
 count 
-------
     0
 
 select count(*) from ofec_electioneering_aggregate_candidate_mv;
 count 
-------
     0
 
 select count(*) from ofec_electioneering_mv;
 count 
-------
     0
 
 select count(*) from ofec_elections_list_mv;
 count 
-------
     0
 
 select count(*) from ofec_entity_chart_mv;
 count 
-------
     0
 
 select count(*) from ofec_filings_all_mv;
 count 
-------
   116
 
 select count(*) from ofec_filings_amendments_all_mv;
 count 
-------
    17
 
 select count(*) from ofec_filings_mv;
 count 
-------
   116
 
 select count(*) from ofec_house_senate_electronic_amendments_mv;
ERROR:  materialized view "ofec_house_senate_electronic_amendments_mv" has not been populated
HINT:  Use the REFRESH MATERIALIZED VIEW command.
 select count(*) from ofec_house_senate_paper_amendments_mv;
 count 
-------
     0
 
 select count(*) from ofec_pac_party_electronic_amendments_mv;
ERROR:  materialized view "ofec_pac_party_electronic_amendments_mv" has not been populated
HINT:  Use the REFRESH MATERIALIZED VIEW command.
 select count(*) from ofec_pac_party_paper_amendments_mv;
 count 
-------
     0
 
 select count(*) from ofec_presidential_electronic_amendments_mv;
ERROR:  materialized view "ofec_presidential_electronic_amendments_mv" has not been populated
HINT:  Use the REFRESH MATERIALIZED VIEW command.
 select count(*) from ofec_presidential_paper_amendments_mv;
 count 
-------
     0
 
 select count(*) from ofec_rad_mv;
 count 
-------
     0
 
 select count(*) from ofec_reports_house_senate_mv;
 count 
-------
    38
 
 select count(*) from ofec_reports_ie_only_mv;
 count 
-------
     2
 
 select count(*) from ofec_reports_pacs_parties_mv;
 count 
-------
    54
 
 select count(*) from ofec_reports_presidential_mv;
 count 
-------
    17
 
 select count(*) from ofec_sched_a_aggregate_size_merged_mv;
 count 
-------
    21
 
 select count(*) from ofec_sched_a_aggregate_state_recipient_totals_mv;
 count 
-------
     0
 
 select count(*) from ofec_sched_c_mv;
 count 
-------
     0
 
 select count(*) from ofec_sched_e_aggregate_candidate_mv;
 count 
-------
     0
 
 select count(*) from ofec_sched_f_mv;
 count 
-------
     0
 
 select count(*) from ofec_totals_candidate_committees_mv;
 count 
-------
     0
 
 select count(*) from ofec_totals_combined_mv;
 count 
-------
    56
 
 select count(*) from ofec_totals_house_senate_mv;
 count 
-------
    14
 
 select count(*) from ofec_totals_ie_only_mv;
 count 
-------
     0
 
 select count(*) from ofec_totals_pacs_mv;
 count 
-------
     0
 
 select count(*) from ofec_totals_pacs_parties_mv;
 count 
-------
     0
 
 select count(*) from ofec_totals_parties_mv;
 count 
-------
     0
 
 select count(*) from ofec_totals_presidential_mv;
 count 
-------
     1

**Comment by wjiangFEC** [comment]
Chat with Vraj, went over the requirements for this ticket.  We decided to open sub-tickets to assign to DBAs, so each DBA can work on 4-5 MVs to include the test data.

There are total 23 MVs that are no data in them.  3 of them do not have data due to the refresh order.  Move the 3 MVs to the end of refresh script should fix the issue.  These 3 MVs are listed below:
ofec_house_senate_electronic_amendments_mv
ofec_pac_party_electronic_amendments_mv
ofec_presidential_electronic_amendments_mv

The order of the MVs is important since there is a dependency of the top level and sub-levels.  DBAs need to work on the tickets orderly.  So I will start top-level MVs first to open separate tickets to assign to different individuals.  The following tickets have been open:

Update sample_db SQL to include test data for ofec_communication_cost_aggregate_candidate_mv

Update sample_db SQL to include test data for ofec_committee_fulltext_audit_mv

Update sample_db SQL to include test data for ofec_candidate_totals_mv

Update sample_db SQL to include test data for ofec_candidate_fulltext_audit_mv

**Comment by vrajmohan** [comment]
Thanks, Wenchun, for creating the following tickets #3109, #3110, #3112, #3113.

**Comment by vrajmohan** [comment]
PR #3114 fixes:
> There are total 23 MVs that are no data in them. 3 of them do not have data due to the refresh order. Move the 3 MVs to the end of refresh script should fix the issue. These 3 MVs are listed below:
ofec_house_senate_electronic_amendments_mv
ofec_pac_party_electronic_amendments_mv
ofec_presidential_electronic_amendments_mv

**Comment by wjiangFEC** [comment]
Thank you, Vraj.

**Comment by wjiangFEC** [comment]
Thanks to Helen and Joseph putting together the following document to summarize the dependency of materialized view.

[ofec_mv.docx](https://github.com/fecgov/openFEC/files/1995438/ofec_mv.docx)

**Comment by vrajmohan** [comment]
Nice, it is fairly trivial to turn this into a picture using https://www.graphviz.org/. Happy to pair with someone on this.

**Comment by hcaofec** [comment]
I am interested in this.  Can we find some time to pair next week? Thanks.
@vrajmohan

**Comment by rjayasekera** [comment]
@wjiangFEC @vrajmohan, over the weekend I created some test data for the missing data found in materialized views.  Below are the latest row counts and we are **half way there now**. (This is a manual and very painful process)

Materialized View Name | Total Records
------------ | -------------
 ofec_amendments_mv                               |      406
 ofec_audit_case_category_rel_mv                  |       55
 ofec_audit_case_mv                               |      166
 ofec_audit_case_sub_category_rel_mv              |       56
 ofec_cand_cmte_linkage_mv                        |      105
 ofec_candidate_detail_mv                         |       26
 ofec_candidate_election_mv                       |       28
 ofec_candidate_flag_mv                           |       26
 ofec_candidate_fulltext_audit_mv                 |        1
 ofec_candidate_fulltext_mv                       |       26
 ofec_candidate_history_latest_mv                 |       15
 ofec_candidate_history_mv                        |       30
 ofec_candidate_totals_mv                         |       29
 ofec_candidate_totals_with_0s_mv                 |       30
 ofec_committee_detail_mv                         |       37
 ofec_committee_fulltext_audit_mv                 |        1
 ofec_committee_fulltext_mv                       |       37
 ofec_committee_history_mv                        |       39
 ofec_communication_cost_aggregate_candidate_mv   |        4
 ofec_communication_cost_mv                       |        5
 ofec_election_result_mv                          |       21
 ofec_electioneering_aggregate_candidate_mv       |        **0**
 ofec_electioneering_mv                           |        **0**
 ofec_elections_list_mv                           |       43
 ofec_entity_chart_mv                             |        6
 ofec_filings_all_mv                              |     1391
 ofec_filings_amendments_all_mv                   |      406
 ofec_filings_mv                                  |     1391
 ofec_house_senate_paper_amendments_mv            |        **0**
 ofec_pac_party_paper_amendments_mv               |        **0**
 ofec_presidential_paper_amendments_mv            |        **0**
 ofec_rad_mv                                      |        5
 ofec_reports_house_senate_mv                     |       38
 ofec_reports_ie_only_mv                          |        2
 ofec_reports_pacs_parties_mv                     |       54
 ofec_reports_presidential_mv                     |       17
 ofec_sched_a_aggregate_size_merged_mv            |       37
 ofec_sched_a_aggregate_state_recipient_totals_mv |        **0**
 ofec_sched_c_mv                                  |        **0**
 ofec_sched_e_aggregate_candidate_mv              |        1
 ofec_sched_f_mv                                  |       10
 ofec_totals_candidate_committees_mv              |       58
 ofec_totals_combined_mv                          |       94
 ofec_totals_house_senate_mv                      |       45
 ofec_totals_ie_only_mv                           |        **0**
 ofec_totals_pacs_mv                              |        **0**
 ofec_totals_parties_mv                           |        **0**
 ofec_totals_presidential_mv                      |        1

**Comment by wjiangFEC** [comment]
@rjayasekera Excellent.  Thank you!

**Comment by wjiangFEC** [comment]
I have opened additional tickets for the rest of the empty MVs and assigned to Rohan, Joseph, and Jean to work on them.  Once all the MVs data have been populated, I will close this main ticket.

**Comment by rjayasekera** [comment]
@wjiangFEC @vrajmohan - Good News!!!! We are getting closer to completing this task.  Now only **two** materialized views with out data.  Thank you @ChingKuan 

@vrajmohan I need you help creating the sample_db.sql file later on.  I am getting the following error(s) during populate data.

```
Loading schema...
WARNING: DB: identifier "ofec_candidate_totals_with_0s_mv_candidate_id_cycle_is_election_idx" will be truncated to "ofec_candidate_totals_with_0s_mv_candidate_id_cycle_is_election" (SQL State: 42622 - Error Code: 0)

psql:data/sample_db.sql:4840: ERROR:  function image_pdf_url(character varying) does not exist
LINE 1: SELECT image_pdf_url(new.image_num)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT image_pdf_url(new.image_num)
CONTEXT:  PL/pgSQL function disclosure.fec_fitem_sched_a_insert() line 3 at assignment
COPY fec_fitem_sched_a, line 1: "C00253047	FRIENDS OF MAJOR OWENS	\N	KIMMEL, MARTIN	MARTIN	\N	KIMMEL	\N	\N	\N	\N	NEW YORK	NY	10022	\N..."
Traceback (most recent call last):
```

Materialized View Name | Total Records
------------------------ | ---------------
 ofec_amendments_mv                               |       17
 ofec_audit_case_category_rel_mv                  |       55
 ofec_audit_case_mv                               |      166
 ofec_audit_case_sub_category_rel_mv              |       56
 ofec_cand_cmte_linkage_mv                        |       31
 ofec_candidate_detail_mv                         |       25
 ofec_candidate_election_mv                       |       25
 ofec_candidate_flag_mv                           |       25
 ofec_candidate_fulltext_audit_mv                 |       14
 ofec_candidate_fulltext_mv                       |       25
 ofec_candidate_history_latest_mv                 |       12
 ofec_candidate_history_mv                        |       25
 ofec_candidate_totals_mv                         |        2
 ofec_candidate_totals_with_0s_mv                 |       25
 ofec_committee_detail_mv                         |      406
 ofec_committee_fulltext_audit_mv                 |       15
 ofec_committee_fulltext_mv                       |       32
 ofec_committee_history_mv                        |      496
 ofec_communication_cost_aggregate_candidate_mv   |       17
 ofec_communication_cost_mv                       |       17
 ofec_electioneering_aggregate_candidate_mv       |        4
 ofec_electioneering_mv                           |       12
 ofec_election_result_mv                          |      104
 ofec_elections_list_mv                           |       43
 **ofec_entity_chart_mv**                            |        **0**
 ofec_filings_all_mv                              |      233
 ofec_filings_amendments_all_mv                   |       17
 ofec_filings_mv                                  |      233
 ofec_house_senate_electronic_amendments_mv       |       11
 ofec_house_senate_paper_amendments_mv            |       21
 ofec_pac_party_electronic_amendments_mv          |       16
 ofec_pac_party_paper_amendments_mv               |      117
 ofec_presidential_electronic_amendments_mv       |        9
 ofec_presidential_paper_amendments_mv            |       24
 ofec_rad_mv                                      |        1
 ofec_reports_house_senate_mv                     |       78
 ofec_reports_ie_only_mv                          |       32
 ofec_reports_pacs_parties_mv                     |       95
 ofec_reports_presidential_mv                     |       57
 ofec_sched_a_aggregate_size_merged_mv            |       21
 **ofec_sched_a_aggregate_state_recipient_totals_mv** |        **0**
 ofec_sched_c_mv                                  |       26
 ofec_sched_e_aggregate_candidate_mv              |        4
 ofec_sched_f_mv                                  |       86
 ofec_totals_candidate_committees_mv              |        4
 ofec_totals_combined_mv                          |       72
 ofec_totals_house_senate_mv                      |       14
 ofec_totals_ie_only_mv                           |        5
 ofec_totals_pacs_mv                              |        4
 ofec_totals_pacs_parties_mv                      |       14
 ofec_totals_parties_mv                           |       10
 ofec_totals_presidential_mv                      |        1
(52 rows)

**Comment by wjiangFEC** [comment]
Thank you, Rohan and Joseph.

**Comment by rjayasekera** [comment]
Thanks to all (@ChingKuan @fecjjeng @hcaofec @wjiangFEC  ) finally we have sample data in all **52** public materialized views. 

Materialized View Name | Total Records
------------------------ | ---------------
 ofec_amendments_mv                               |       76
 ofec_audit_case_category_rel_mv                  |       55
 ofec_audit_case_mv                               |      166
 ofec_audit_case_sub_category_rel_mv              |       56
 ofec_cand_cmte_linkage_mv                        |       36
 ofec_candidate_detail_mv                         |      293
 ofec_candidate_election_mv                       |      346
 ofec_candidate_flag_mv                           |      293
 ofec_candidate_fulltext_audit_mv                 |       14
 ofec_candidate_fulltext_mv                       |      293
 ofec_candidate_history_latest_mv                 |      332
 ofec_candidate_history_mv                        |      371
 ofec_candidate_totals_mv                         |        5
 ofec_candidate_totals_with_0s_mv                 |      373
 ofec_committee_detail_mv                         |      409
 ofec_committee_fulltext_audit_mv                 |       15
 ofec_committee_fulltext_mv                       |      409
 ofec_committee_history_mv                        |      523
 ofec_communication_cost_aggregate_candidate_mv   |       17
 ofec_communication_cost_mv                       |       17
 ofec_election_result_mv                          |      104
 ofec_electioneering_aggregate_candidate_mv       |        4
 ofec_electioneering_mv                           |       12
 ofec_elections_list_mv                           |       43
 ofec_entity_chart_mv                             |        3
 ofec_filings_all_mv                              |     1206
 ofec_filings_amendments_all_mv                   |      238
 ofec_filings_mv                                  |     1206
 ofec_house_senate_electronic_amendments_mv       |      110
 ofec_house_senate_paper_amendments_mv            |       21
 ofec_pac_party_electronic_amendments_mv          |       46
 ofec_pac_party_paper_amendments_mv               |      117
 ofec_presidential_electronic_amendments_mv       |       34
 ofec_presidential_paper_amendments_mv            |       24
 ofec_rad_mv                                      |        1
 ofec_reports_house_senate_mv                     |      388
 ofec_reports_ie_only_mv                          |       32
 ofec_reports_pacs_parties_mv                     |     1532
 ofec_reports_presidential_mv                     |      124
 ofec_sched_a_aggregate_size_merged_mv            |       27
 ofec_sched_a_aggregate_state_recipient_totals_mv |        6
 ofec_sched_c_mv                                  |       26
 ofec_sched_e_aggregate_candidate_mv              |        4
 ofec_sched_f_mv                                  |       86
 ofec_totals_candidate_committees_mv              |        6
 ofec_totals_combined_mv                          |       74
 ofec_totals_house_senate_mv                      |       16
 ofec_totals_ie_only_mv                           |        5
 ofec_totals_pacs_mv                              |        4
 ofec_totals_pacs_parties_mv                      |       14
 ofec_totals_parties_mv                           |       10
 ofec_totals_presidential_mv                      |        1
(52 rows)

**Comment by rjayasekera** [comment]
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File data/sample_db.sql is **78.32 MB**; this is larger than GitHub's recommended maximum file size of **50.00 MB**
To github.com:fecgov/openFEC.git

**Comment by rjayasekera** [comment]
@wjiangFEC @AmyKort - this issue can be closed
