### ISSUE TITLE
Elections 'won' Field Frequently Incorrect

### ISSUE THREAD

**Issue by kevinshurtz** [fecgov/openFEC#3076]
I am using the openFEC API for a data science project for my college coursework, and I've noticed recently that the `/elections/` endpoint often returns a `results` list wherein the `won` field is returned as `false` for the victor of the election.  I have observed this issue for the 2016, 2008, 2000, 1996, 1992, 1988, and 1982 election cycles.

Attached is some example data collected using Powershell from the 2016, 2012, 2008, and 2004 election cycles.  True negatives are circled in yellow, true positives are circled in green, and false negatives are circled in red.  I have encountered no false positives.
![fec api election endpoint error annotated](https://user-images.githubusercontent.com/17734531/39089151-02c1f00e-4586-11e8-9deb-30da5d5266ab.png)

I have additionally tested this issue using `curl` instead of PowerShell's `Invoke-WebRequest` to ensure that the issue was not a result of binding issues, and I further tested the issue using demo functionality of the [openFEC Developers](https://api.open.fec.gov/developers/#!/financial/get_elections) page.  In all cases, the issue persists.

I am unsure if this issue is the result of an issue with the database, or if there is an issue in the [_get_records method](https://github.com/fecgov/openFEC/blob/88593e0bb4f052b61621c2a791bd34ed6598bc9a/webservices/resources/elections.py#L214) for ElectionsView.  I am not an FEC employee, so I may be a bit limited in what I can do in the former case.  Regardless, I am happy to help solve this problem any way I can!

**Comment by lbeaufort** [comment]
@kevinshurtz thank you so much for bringing this to our attention, and for all your work on this so far! I'll take a look at whether it's an underlying data problem and keep you posted. Regardless, the endpoint could definitely use some refactoring. Thanks again!

**Comment by lbeaufort** [comment]
@AmyKort sorry - the linked PR represents a small fraction of the work needed for this ticket.
