### ISSUE TITLE
Cached calls causing connectivity conundrums

### ISSUE THREAD

**Issue by ccostino** [fecgov/openFEC#3078]
## Issue summary

The current implementation of the cached calls is causing the entire API response to also be stored in Redis, which is eating up all of the RAM available to the Redis instance.  Once all of the RAM is taken up, the Redis service stops responding and the API stops functioning correctly.

There is a stopgap fix currently in place where someone on cloud.gov manually increased the RAM available to the Redis service for the time being, but that is not foolproof.

This may require diving into the [Celery Task documentation](http://docs.celeryproject.org/en/latest/userguide/tasks.html) to determine how best to restructure the code and fix this issue.

### Completion criteria

* [ ] Write tests for cached calls if they haven't been written yet
* [ ] Monitor and profile what information is being stored in Redis currently
* [ ] Fix the cached calls implementation to not store the API response in Redis
* [ ] Make sure that tasks and all data associated with them are being cleared out of Redis when they're done

## Technical details 

On the evening of Monday, April 23rd (around 5:15 - 5:30 PM EST/EDT) we began seeing a bunch of New Relic alerts and noticed a large amount of errors in the production API logs related to the Celery worker:

```
redis.exceptions.ResponseError: NOREPLICAS Not enough good slaves to write.
```

At this time, there was a cloud.gov deployment happening with Kubernetes that unfortunately ran into some issues.  This was quickly resolved, however our services weren't recovering, so I initiated a redeployment of the application to rebind everything (it turns out our Celery work applications had crashed).  The redeployment was successful but resulted in another Redis issue:

```
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
```

It turns out this connectivity issue was caused by the API (the Celery worker specifically) consuming all of the Redis service's available memory (512 MB).  The culprit appears to be tracked down to [how we're caching calls](https://github.com/fecgov/openFEC/blob/8bfacf2e37315fa57f1d3890b78c80a87c63f30e/webservices/tasks/cache_request.py#L17-L38).  What is happening here is the `json_str`, which contains the entire cached response, is also going into Redis.  During periods of high traffic and/or when a platform issue impacts the running Redis service, this can cause either a backup in the Celery queue and/or just fill up all of the memory available to Redis.

The immediate fix has been a manual adjustment for increased memory in the production instance of the Redis service the API is connected to, but for long term there are few things we should be looking into:

* Monitoring and profiling just how much data is going into Redis from the cached calls (and downloads too for that matter)
* Make sure that tasks and all data associated with them are being cleared out of Redis when they're done
* See if we can cut down on the amount of data being stored in Redis itself

The cloud.gov team has also stated that they'll look into exposing better error messages to provide more details of what is happening and look into offering high memory plans to account for such use-cases.

**Comment by vrajmohan** [comment]
Used the following `aws-cli` command to determine the total space used on `S3` on `prod` by the cached calls:
` aws s3 ls <<bucket>>/cached-calls --recursive --human-readable --summarize`

The result was:
Total Objects: 91116
   Total Size: 3.7 GiB

I took a random sample of the `cached-calls` directory and was able to reduce the size to 10% (from 13MB to 1.3 MB) by using `gzip`.

We could reduce the size in S3 as well as the size in Celery/Redis by compressing the response _before_ sending it to Celery. This would not be optimal - we would ideally like to have the compression done by the worker, which would mean that this would not improve Celery/Redis memory usage but would reduce S3 storage (which may not be a worthy saving).

**Comment by vrajmohan** [comment]
Examined the actual memory used by Redis using `info memory`. The result:
```
# Memory
used_memory:11944416
used_memory_human:11.39M
used_memory_rss:16224256
used_memory_rss_human:15.47M
used_memory_peak:45395328
used_memory_peak_human:43.29M
total_system_memory:32151523328
total_system_memory_human:29.94G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.36
mem_allocator:jemalloc-4.0.3
```

We don't appear to be taxing Redis very much.

**Comment by vrajmohan** [comment]
Next step is to talk to cloud.gov and figure out if we've missed anything and where we should be looking. Tagging @ccostino.

**Comment by ccostino** [comment]
@vrajmohan, do we still need to reach out to cloud.gov about this?  Would it help to try and setup a meeting with someone, e.g., Josh and/or Steve?

**Comment by vrajmohan** [comment]
Yes, we should.

**Comment by vrajmohan** [comment]
@ccostino and I met with cloud.gov yesterday. We have some followup items:
- [ ] Check how data.gov and Cloudfront caching are working today. We may not need application level request caching at all.
- [ ] If we are continuing with application level request caching, investigate how to lower the priority of this in Redis so that caching requests may be dropped (as this caching is less important than using Redis to serve downloads)

**Comment by vrajmohan** [comment]
Summarized my findings in https://docs.google.com/document/d/1vUDTrnWKpbUDmUv90pEIINV79MSlkg03qoBoXpzl9Wc/edit#. Plan to have a meeting to close this off on Jun 25, 2018 and create new tickets.

**Comment by vrajmohan** [comment]
Closing issue as investigation has been summarized in a document, discussed with team, and follow-on tickets have been created.
