### ISSUE TITLE
[Low risk] Upgrade boto3 to version 1.4.5 or higher 

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3087]
[Low Risk] Snyk alert: https://snyk.io/vuln/SNYK-PYTHON-BOTO3-40617

Vulnerable module: boto3
Introduced through: smart-open@1.5.6 and boto3@1.4.4
Fix: Upgrade boto3 to version 1.4.5 or higher.

**Comment by vrajmohan** [comment]
It looks like the `boto3` version required is 1.5.31 (see https://github.com/boto/boto3/issues/1017#issuecomment-366546445)
