### ISSUE TITLE
Switching API to the fecp-driven sched_a tables 

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3088]
This is to deploy the work completed in derived from #3006

We are switching API to access fecp-driven sched_a tables.

make API code changes to use fecp-driven sched_a tables
modify view definition scripts that utilize these tables
evaluate and create appropriate indexes on the fecp-driven sched_a tables

**Comment by fecjjeng** [comment]
API updated to pointed to use the fecp-driven fec_fitem_sched_a tables.  Migration file to add indexes to these tables ready.  
creating all these indexes during release time will take LONG time and also cause performance problems. 
 Since tables are not being used before switch, indexes had been built during non-peak hour instead (migration file is still submitted to keep track of the integrity of the migration process).

**Comment by fecjjeng** [comment]
More database storage space is required to create all these indexes.  Currently we do no have enough space to complete this issue.   Issue #51 in fec-infrastructure had been created and been working on to get more space in the cloud databases.

**Comment by AmyKort** [comment]
Thanks @fecjjeng !
