### ISSUE TITLE
Restore Paper filings missing from API /reports/ and /filings/

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3103]
At least 591 paper filings available from the bulk downloads seem to be missing from the API's /reports/ endpoint: when we fetch a /reports/ endpoint for a committee, the response does not include any records with these filing ids in the file_number field. 366 of those filings are accessible through the /filings/ endpoint. It seems that the filings which are available through /filings/ but not /reports/ show up on the website, but the summary fields for those are shown as $0 regardless of the filing's actual content.

The filing ids for the 366 filings available through /filings/ but not /reports/ are in the document below:
missing_filings.txt

To resolve this issue, we need to:
- [x] create new view that includes F3X plus F3 submitted by PAC and party committee
- [ ] API work to use the new view
- [ ] test

@hcaofec @pkfec @jwchumley 

Continues work at https://github.com/fecgov/openFEC/issues/3038

**Comment by hcaofec** [comment]
There are two different reasons for causing this issue. 
Besides the reason identified in #3038 , another cause was identified while working on this ticket.  It's from the logic in one of the functions:
 _resolve_committee_type

This function does not have logic for rpt_yr, only for cycle.  When rpt_yr is passed to API, API will use the latest committee type ( type in first row returned order by cycle desc ), then api uses different tables based on committee type.  This logic will not work correctly when committee type changed over different cycles.  Here is an example:


FILE_NUM | CMTE_ID | FORM_TP | RPT_TP | RPT_YR | BEGIN_IMAGE_NUM 
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1884270 | C00258525 | F3 | Q2 | 2013 | 13031090700 
897290 | C00258525 | F3 | Q3 | 2013|13031130211

 Type for C00258525:  
2014    H;  2016  U.
when rpt_yr= 2013, api sets type = U ,  uses pac_party table for F3 and will not return any report;
Instead when cycle=2014, api sets type = H ,  uses house_senate table for F3,  and 1884270 and 897290 will be returned.

So logic to handle rpt_yr will be added to fix this.

@jwchumley @AmyKort
