### ISSUE TITLE
Count estimate for receipts search approximately doubles the amount returned

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3104]
What we are after: 
More accurate estimates or precise counts of transactions.

Why we are after it: 
The current estimates mislead users. They can think their downloaded file is incomplete. 

Competition criteria: 
- [x] Research using `explain analyze=True` but need to figure out if this impacts performance. Use `pgBadger` to analyze. Analyzed number may give a better estimate of the counts. https://github.com/fecgov/openFEC/blob/develop/webservices/common/counts.py#L32
- [ ] Inventory everywhere on the front end where the counts are being pulled in. Each pulls from a different end point and they may be broken.
- [ ] Schedule a meeting to talk about this
- [ ] Investigate reinstating the manifest file with a better design
- [ ] fix the estimate

https://www.fec.gov/data/receipts/?two_year_transaction_period=2018&data_type=processed&committee_id=C00000935&min_date=01%2F01%2F2017&max_date=05%2F01%2F2018&contributor_state=IL

This example returns 18,963 rows but the estimate shows 41,000. [7/2/2018]

This is an annoyance and it makes people think they haven't downloaded all of the rows they want.

**Comment by pkfec** [comment]
@hcaofec did some research on the counts and explained clearly why the counts are not returned correctly here : https://github.com/fecgov/openFEC/pull/3264#issuecomment-406752980

**Comment by lbeaufort** [comment]
@patphongs moving this to 7.2 per @PaulClark2

**Comment by lbeaufort** [comment]
One approach is: 
So we can tell what performance hit might occur if we had better counts, we should test a `count_exact` function with `analyze=False` and see if it fixes our counts.

```
def count_exact(query, session, threshold=None):
    rows = session.execute(explain(query, analyze=False)).fetchall()
    count = extract_analyze_count(rows)
    if threshold is not None and count < threshold:
        return query.count()
    return count  
```

Related to #3104 
and https://github.com/fecgov/fec-cms/issues/2366

- [ ] Check receipts, filings datatables for counts
- [ ] Load test with locust

**Comment by patphongs** [comment]
This issue is temporarily bandaged with this PR: https://github.com/fecgov/fec-cms/pull/2378.

**Comment by patphongs** [comment]
To do, we should schedule a meeting to discuss how we want counts to work and how we will optimize it

**Comment by dorothyyeager** [comment]
Preliminary testing on stage ticket will be made for 7.3.
