### ISSUE TITLE
Research: Investigate possible bug in /schedules/schedule_a/ - compare data to line totals on report

### ISSUE THREAD

**Issue by stephenholzman** [fecgov/openFEC#3105]
Attempting to verify line item contributions pulled using /schedules/schedule_a/ match totals.
(https://github.com/fecgov/openFEC/blob/develop/data/functions/individual.sql) for defining individual contributions.

- [ ] Documentation suggests items where `"is_individual": true` should equal totals, though this is either incomplete, bugging, or both.

Example: Will Hurd's total itemized individual contributions is reported as $566,211.43. After paginating through the [full query](https://api.open.fec.gov/v1/schedules/schedule_a/?committee_id=C00545467&committee_id=C00470351&is_individual=TRUE&api_key=DEMO_KEY&per_page=100) and combining the results, filtering on `is_individual` alone gives a `contributions_receipt_amount` sum of ~$1,396,410. Filtering on `is_individual` and `memo_code` gives a sum of ~$564,211. 

Downloading the [itemized individual contributions manually](https://www.fec.gov/data/receipts/?committee_id=C00545467&two_year_transaction_period=2018&cycle=2018&line_number=F3-11AI&data_type=processed), filtering on `memo_code` alone gives the correct sum. Filtering on both `memo_code` and `is_individual` comes up $2,000 short. The `contribution_id` of the items with potential issues are SA11AI.27345 and SA11AI.28956, both of which seem to involve `entity_type` ORG -> IND without a `memo_code` update.

This is a research ticket to determine what's up with "is_individual": true`

**Comment by AmyKort** [comment]
Thanks for reporting! We'll tackle the dead link in the documentation separately in https://github.com/fecgov/openFEC/issues/3296 , and investigate the other issue here.

**Comment by patphongs** [comment]
We need to figure out the appropriate business logic for this. A business expert needs to take a look to draft the business rule for this before shifting to developers.

**Comment by AmyKort** [comment]
@jwchumley and @llienfec  Can you take a look?

**Comment by llienfec** [comment]
@AmyKort Happy to take a look a little later this week. Do you or @patphongs have any additional info or background before I start researching?

Future me: is this related to https://github.com/fecgov/fec-cms/issues/1656?

**Comment by llienfec** [comment]
Conducted research and compared totals.  Looks like the description for how to get to the committee's line totals needs to be revised.  The instructions conflate finding `individual contributions` with `memo entries` - which are not the same thing.

### The best way to use transaction-level data to determine line totals is to:
1. Get all contributions on a particular line
2. Remove the memo items

As long as the time period is the same, users can expect that:

- On lines that require 100% itemization, this transaction-level total should be the same as the line total on the committee profile page.  
- On lines that have a $200 itemization threshold, this transaction-level total should be less than or equal to the line total on the committee profile page.

Example using the great description from @stephenholzman above:
This is data from Hurd for Congress (C00545467) for 2017-2018, a little longer time period.

Line # | Total from   cmtte profile page | Total from   transaction data
-- | -- | --
11(a)(i) | $734,036.43 | $734,036.43
11(c) | $1,232,262.20 | $1,232,162.20
12 | $976,674.07 | $976,674.07
14 | $2,069.91 | $1,975.00

### To do:
- [ ] Re-write API description for how to find line item totals
- [ ] Look into `is_individual` a little more

**Comment by llienfec** [comment]
Draft re-write of this API description:
🔒 https://docs.google.com/document/d/13o-6EGIpRzXDdIdOe7VLLUF6pfJDr-_KeOiRv8g6FFk/edit?usp=sharing 🔒 

Here's the issue for going through the API descriptions and making similar changes across our endpoint descriptions:
https://github.com/fecgov/fec-cms/issues/2370

Since research is finished, I'm closing the issue. Implementation for this description will happen with the work in https://github.com/fecgov/fec-cms/issues/2370
