### ISSUE TITLE
Verify on API/Webpage for Switching API to the fecp-driven sched_b tables

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3115]
Issue #3045 Switching API to query sched_b from public.ofec_sched_b_xxxx_yyyy tables
to the fecp-driven sched_b tables  (disclosure.fec_fitem_sched_b_xxxx_yyyy).

The only difference between ofec_sched_b tables and fec_fitem_sched_b tables we made was the function/trigger that populate the recipient_name_text field is being changed from 
to_tsvector(recipient_nm) || to_tsvector(coalesce(recipient_cmte_id, '') to
to_tsvector(recipient_nm) || to_tsvector(coalesce(clean_recipient_cmte_id, '')
So this field will only be difference between old and new tables are when recipient_cmte_id=cmte_id (which will make clean_recipient_cmte_id will be null). 
From the following query we can identify some cmte_id/recipient_name we can try and compare between PRD and STG/DEV
select cmte_id, count(*) from disclosure.fec_fitem_sched_b_2017_2018 where recipient_cmte_id=cmte_id group by cmte_id;
One example is C00676494. 
In DEV, when input is (committee_id: C00676494), return 12 rows, when input is (committee_id:C00676494; recipient_name:C00676494), not rows returns.  
In PRD, both condition returns return 12 rows.  The two_year_transaction is 2018.

Couple other example in 2018 are:
'C00673384'
'C00669879'

In addition to check this kind of difference, please record when is the time of tests so Carlo can pull RDS log from AWS and check if the query is point to the fecp-driven tables.

**Comment by ccostino** [comment]
I've just verified that the queries are targeting the correct schedule B tables with these recent changes.  In staging, I created a query that took some extra time to process so I could see it in the `pg_stat_activity` table:  https://fec-stage-proxy.app.cloud.gov/data/disbursements/?two_year_transaction_period=2016&data_type=processed&recipient_name=C00001313&recipient_name=C00002931&recipient_name=C00003376&recipient_name=C00003418&recipient_name=C00027466&recipient_name=C00401224&min_date=01%2F01%2F2015&max_date=12%2F31%2F2016

Sure enough, the query showed up targeting `disclosure.fec_fitem_sched_b`!  We're good to go. :-)

**Comment by jwchumley** [comment]
I compared the prod and stage interfaces are showing the same results from the different sources. There is a difference in the estimated row counts probably due to dropping a date stamp column (this column is an artifact of the Q table process and doesn't have any business logic application) so if anyone compares the two systems you will see that small committees match exactly and once you get up to 20,000 rows or so you start seeing discrepancies but if you export the data you get the same set of transactions.
