### ISSUE TITLE
Speed up build: Investigate whether we still need `pandas` in `requirements-dev.txt`

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3117]
Installing `pandas`  in `requirements-dev.txt` is slowing down our build - it looks like it's only used in some management commands. 

We should investigate if these  management commands are still used or needed, and if not - remove the commands as well as the `import pandas` statements and the `pandas`  in `requirements-dev.txt` Note: I think at some point `build_districts` was getting used to build files for the CMS.

Also, double-check that `pandas` isn't used anywhere else.

**Comment by vrajmohan** [comment]
We should also consider removing `rdbms-subsetter`.

**Comment by jontours** [comment]
I believe I created `load_efile_sheets` if I remember right it was a bit of a one-off.

**Comment by jason-upchurch** [comment]
The following `pandas`-dependent functions only appear in their own definition in the openFEC repo. That is, they do not appear to be used anywhere else outside of the openFEC repo. 

1. load_nicknames()
2. load_pacronyms()
3. build_districts()
4. load_election_dates()
5. load_efile_sheets

As for `rdbms-subsetter`, we currently use `invoke create_sample_db` to build a sample. However, this approach does not create a dataset that spans the api, e.g., no data returned when querying `ofec_rad_analyst_vw`

**Comment by lbeaufort** [comment]
This is addressed in https://github.com/fecgov/openFEC/issues/3782#issuecomment-526243053
