### ISSUE TITLE
Elasticsearch: use asynchronous mode when reindexing all documents

### ISSUE THREAD

**Issue by vrajmohan** [fecgov/openFEC#3118]
We encountered timeouts during reindexing when we tried to upgrade from ES 2.4 to ES 5.6. Although this has been fixed by cloud.gov (by increasing the timeout), we should switch to asynchronous mode when reindexing by setting `wait_for_completion` to False as described in http://elasticsearch-py.readthedocs.io/en/5.5.1/api.html#elasticsearch.Elasticsearch.reindex.

Tagging @lbeaufort, @pkfec.

**Comment by lbeaufort** [comment]
Addressed by PR #3111: Upgrade Elasticsearch to v. 5.6, reindex docs asynchronously

**Comment by AmyKort** [comment]
@vrajmohan and @lbeaufort  Would you say the remainder of this work is a higher or a lower priority for us? I'm not sure I understand the risks.
