### ISSUE TITLE
QA Legal Citations Results for final AOs

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3144]
Users need an at-a-glance way to determine whether a particular AO is relevant to their research or question. One way we meet this need is by providing the legal citations included in each AO. The canonical page displays a legal citations box listing the statutory provisions and regulatory provisions cited in the opinion, any prior AOs cited, and later AOs that cite back to the one being viewed. 

Spot checking the legal citations boxes suggests that these citations are not always populating accurately. In order to solve this problem, which appears to originate from more than one source, we need to get a better overview of the types of errors users encounter. So, we're going to perform a more organized review of the legal citation results.

Completion criteria:

- [ ] Determine sample size and distribution
- [ ] Review sample citation results for accuracy (compared to what is included in the AO)
- [ ] Document results

**Comment by AmyKort** [comment]
We'll want to tackle https://github.com/fecgov/openFEC/issues/2856 before we start this work.

**Comment by lbeaufort** [comment]
@AmyKort  #2856 and #2276 have been addressed, as well as #3465, which will making addressing these false positive and missed citations much easier.
