### ISSUE TITLE
Drop ofec_reports_pacs_parties_mv since it is replaced by another view

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#3145]
Drop ofec_reports_pacs_parties_mv if it's not used by api or other objects( tables, materialized views or views)

This is related to [#3103](https://github.com/fecgov/openFEC/issues/3103)

**Comment by jason-upchurch** [comment]
The only place `ofec_reports_pacs_parties_mv` appears in openFEC is `manage.py`:
```python
'reports_pac_party': ['ofec_reports_pacs_parties_mv']
```
however, ```'reports_pac_party'``` appears in three places:
```python
./webservices/flow.py:37:        'reports_pac_party',  #included as a materialized view list element
./webservices/flow.py:82:        ('filing_amendments_pac_party', 'reports_pac_party'), #graph.edge
./webservices/flow.py:85:        ('filing_amendments_all', 'reports_pac_party'), #graph.edge
```

**Comment by jason-upchurch** [comment]
If we decide to drop this view from db, we can update the api accordingly.

**Comment by dorothyyeager** [comment]
This has been resolved, so we can close.
