### ISSUE TITLE
Add candidate_pcc_name and modify candidate_pcc on /elections/ endpoint

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#3146]
@JonellaCulmer commented on [Fri May 18 2018](https://github.com/fecgov/fec-cms/issues/1996)

**What we're after:** In order to display a candidate's principal campaign committee on the election profile 'about this election' pages, we need to add the committee's name to the endpoint. 

Also, to distinguish between ID and name, we need to update the fields to each say the following: 
`candidate_pcc_name` and `candidate_pcc_id`

**About this election page mock-up:**

<img width="794" alt="screen shot 2018-05-18 at 1 13 06 pm" src="https://user-images.githubusercontent.com/31663028/40248234-41d08c3e-5a9d-11e8-83b4-bdca87d1491c.png">

**Completion criteria:**
- [x] Update 'candidate_pcc' to say 'candidate_pcc_id'
- [x] Add 'candidate_pcc_name'

**Comment by lbeaufort** [comment]
Addressed by https://github.com/fecgov/openFEC/pull/3147
