### ISSUE TITLE
Missing filings part 2: F3 filers that file on F3X

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3154]
Filings are missing from the API's /reports/ endpoint because the endpoint assumes a House/Senate committee will always file on Form 3. They sometimes file incorrectly on form 3X and those filings are missing from the endpoint. Helen has already corrected this problem for form 3x filers that file on form 3. Now we need to do the same for this set. (After that we need to do the same for form 3P)

The filing ids for the 366 filings available through /filings/ but not /reports/ are in the document below:
missing_filings.txt

To resolve this issue, we need to:

  - [ ] create new view that includes F3 plus F3X submitted by House and senate committees
  - [ ] API work to use the new view
  - [ ] test
@hcaofec @pkfec @jwchumley

Continues work at #3038 and #3103

**Comment by hcaofec** [comment]
I ran a query on f_rpt table to get a count of how many F3X were from F3 filers.  There are about 1000+.  Maybe we should consider the option of creating an all_report_mv instead of several committee type based views
@jwchumley

**Comment by PaulClark2** [comment]
An "all reports" view makes sense to me.

**Comment by jwchumley** [comment]
I agree. That is the best long term solution

**Comment by lbeaufort** [comment]
Closed in favor of https://app.zenhub.com/workspace/o/fecgov/openfec/issues/3230
