### ISSUE TITLE
Transfer GSA managed AWS account to FEC

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3158]
What do we want?

We want to transfer our assets from GSA ATO to FEC ATO

Why do we want it?
To complete the FEC ATO process and to own the entire process

- [x] get commercial account number from GSA
- [x] FEC provides commercial account number to our vendor 
- [x] Our vendor initiates the transfer 
- [x] Our vendor moves account under their payer account

In parallel or just prior to the giving our vendor our commercial account number
- [ ] update root email address to an FEC owned address
- [ ] reset password

**Comment by vrajmohan** [comment]
Is there a specific target date for this, either imposed deadline on us or self-imposed? (TTS would like to know so that they can accommodate another program)

**Comment by ccostino** [comment]
@wjiangFEC this will require folks on our infrastructure team at 18F to help coordinate.  I'll let them know that FEC is getting ready for this so that we can all coordinate when folks will be available to help.  I had already given them a heads up that this would be coming relatively soon, so they're aware.

I'll post an update here once I hear back, and/or loop them in directly.  Thanks!

**Comment by wjiangFEC** [comment]
@ccostino Thank you!

**Comment by ccostino** [comment]
@wjiangFEC you're welcome!  Could you please ping @vrajmohan and I once you all have your own account access?  Once that is in place and you're ready for a transfer of resources, I can follow up with our infrastructure team to schedule time with them to move forward on this.  Thanks!

**Comment by wjiangFEC** [comment]
@ccostino @vrajmohan I will.  I got access to FEC's payer account.  Still waiting for link account to be open for the asset transfer.

**Comment by wjiangFEC** [comment]
@vrajmohan @ccostino FEC's AWS account is ready for the asset transfer.  Could you please notify your folks to put into their schedule for the transfer?  Please contact @PaulClark2  or me for the production link account information.  Thanks very much.  @PaulClark2 we discussed this before - we would like to transfer all the assets to the production link account.

**Comment by erik-burgess** [comment]
As I understand things, we're working with two accounts here. A standard AWS account and the paired GovCloud account. I've never transferred a GovCloud account, but I assume that transferring the paired commercial account will automatically transfer the GovCloud account, but you might want to ask your reseller for clarity. I don't remember transferring GovCloud the last time we recompeted the contract, just the commercial accounts. 

I see that email addresses have been requested. We'll only need one for the commercial account. GovCloud accounts do not have their own root account, just IAM users. I'd be happy to update the commercial account root email address and disable MFA. I could then provide you with a temporary password or you could just do a password recovery. Once in, you can update all of the named contacts and accept the transfer request when your reseller initiates it. 

If you have questions or comments, please let me know. Does anyone need the account numbers to get the transfer started, or do you have those already?

**Comment by ccostino** [comment]
A few other questions that come to mind for this:

* Making sure all resources to be transferred are being accounted for:  RDS instances and configuration, CloudWatch configuration, etc. (I can't remember everything off the top of my head but can look if it would be helpful necessary) - will all of that transfer over as is, or will some extra setup be needed?
* Will the connection strings to the RDS instances change?  If so, it might make sense to stagger the transfer of assets if at all possible, to test things out for `dev` first for instance.  If not, then I would plan for some downtime to occur and schedule this off hours.
* Terraform setup:  making sure the Terraform configuration is updated to account for the move of assets and account credentials are updated

If think if anything else I'll add them here!

**Comment by erik-burgess** [comment]
@ccostino Account wise, all items should transfer as is. Everything within the account will remain the same, including connection strings. There should be zero disruption in services. That said, we can do this transfer as quickly or slowly as we want.

**Comment by ccostino** [comment]
Oh that is a huge relief to here, thank you @erik-burgess! :-)

**Comment by wjiangFEC** [comment]
@erik-burgess You mentioned two paired accounts.  One for AWS commercial account, one for GovCloud.  Could you please clarify this?  Is this how current FEC account setup with 18F (two paired accounts)?  We have two accounts setup through our vendor.  I think they are both GovCloud accounts, but I will need to verify with vendor.  @PaulClark2 could you please verify with vendor about the two link accounts -  are they all in GovCloud?

**Comment by wjiangFEC** [comment]
@ccostino @erik-burgess @vrajmohan Please let me or @PaulClark2 know if FEC needs to have two accounts,  one for AWS commercial account, one for GovCloud account.

**Comment by ccostino** [comment]
@wjiangFEC I'm sorry for the confusion, and @erik-burgess will have to weigh in here.  I think on our (18F) side, we only have the one GovCloud account with FEC resources in it and so you should only need one GovCloud account, or at least that's my understanding.  I believe @erik-burgess was referencing your accounts when referring to the commercial AWS account, but I'm not sure.

Either way, it sounds like a good idea if you or @PaulClark2 could let us know what type of accounts you have on your side so we're all on the same page.  Thanks!

**Comment by erik-burgess** [comment]
Just to clarify things here. You cannot have a GovCloud account without a standard commercial account. I don't think the commercial account is actually doing anything, but acting as an anchor for the GovCloud account. Your reseller may have been able to provision you two GovCloud accounts, by just hiding the fact that they are tied to commercial accounts. Given they likely handle your billing, it probably works. In reality you want access to the commercial account, especially when it comes time to recompete the contract and you need to transfer to another reseller. 

That being said, on the 18F side of things, FEC has ONE GovCloud account paired to ONE standard commercial account. 

[This page](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-differences.html) talks a bit about why you need a standard account, especially around billing services. 

_Billing, account activity, and usage reports

An AWS GovCloud (US) account is always associated to a single standard AWS account for billing and payment purposes. All AWS GovCloud (US) billing is billed or invoiced to the associated standard AWS account. You can view the AWS GovCloud (US) account activity and usage reports through the associated AWS standard account only._

**Comment by wjiangFEC** [comment]
@erik-burgess @ccostino Thank you for clarify the pair account setup in GovCloud.  We have a meeting with our Vendor tomorrow afternoon.  We will clarify it with our vendor tomorrow.  Currently, vendor setup a payer account for FEC and two linked accounts associate with the payer account.  One of the linked accounts is for dev/test, one for production.  We will use the linked accounts for the asset transfer.  Since 18F has only one account for FEC.  Should we transfer all the assets to one production account?

@PaulClark2 We will ask vendor about the commercial account behind the Govcloud account and try to get the root account access for the commercial account.

**Comment by wjiangFEC** [comment]
@erik-burgess Our vendor has established a Payer account, a AWS commercial account under the payer account for the website project, as well as GovCloud account goes with the commercial account.  We have the root access.  Does FEC has a Payer account with GSA?  Which account should we pass to you for the asset transfer?

**Comment by PaulClark2** [comment]
@erik-burgess the process you outline makes sense

To summarize:
- [ ] get commercial account number from GSA
- [ ] FEC provides commercial account number to our vendor 
- [ ] Our vendor initiates the transfer 
- [ ] Our vendor moves account under their payer account

In parallel or just prior to the giving Four Points our commercial account number
- [ ] update root email address to an FEC owned address
- [ ] reset password

**Comment by erik-burgess** [comment]
@PaulClark2 Perfect summary. 

While not overly sensitive, I'd rather not publicly post account numbers here. We can exchange via slack/email if that works for your team. I'm also happy to hop on a call if that makes sense.

**Comment by PaulClark2** [comment]
@erik-burgess thanks. Agreed, we should exchange the account numbers over slack or email. I think I'm a member of TTS's Slack organization. We can also add you to our Slack organization.

**Comment by erik-burgess** [comment]
@PaulClark2 Whatever works best for your team. We're here to help this transition go as smooth as possible.

**Comment by wjiangFEC** [comment]
@erik-burgess In addition to Paul's information, our vendor also established a Payer account for FEC only. So FEC has its own payer account.

**Comment by wjiangFEC** [comment]
@erik-burgess Our vendor has sent an account transfer request from FEC's payer account to FEC's account at GSA.

**Comment by wjiangFEC** [comment]
@ccostino @erik-burgess Hi, I was away for a couple of weeks.  Now I am back and would like to follow up with the account transfer request.  Our vendor has sent an account transfer request from FEC's payer account to FEC's account at GSA.  Our vendor also mention to have the account email address change to FEC's email that associates with the transfer account.  I will ask Paul to send you FEC's email address to you.  Thanks.

**Comment by erik-burgess** [comment]
Root account details have been updated and the credentials have been passed to @PaulClark2. Let me know if you require anything further, but I think tat you should have everything that you need.
