### ISSUE TITLE
Sending Election profile pages to press and public records for testing and validation

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3159]
What do we want?
We want Press and Public records to test the work so we can get their (hopefully minimal) feedback. 
Why do we want it?
So we can move the pages into production or implement their feedback requests and send them for testing again.

- [x] Ask Press/Pubrec to test
- [x] collect feedback

**Comment by AmyKort** [comment]
I shared the link with Press. We need to set up a meeting this week to walk staff through the new features.

**Comment by AmyKort** [comment]
Done!
