### ISSUE TITLE
Research - inventory Data Filters

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3160]
What do we want?
Ahead of asking outward facing offices for feedback on our filters, we need to know what filters are available for which search pages and if there are any glaring omissions in our filters' capabilities.

Why do we want it?
We want our users to be able to access the data they need and to have confidence in it's integrity.  
- We want users to easily pick the right page to use to conduct their search
- We want users to have access to the filters they need to find the data they need
- The filters need to be easy to understand, complete, and grouped in ways that make sense to non-experts

### To Do:
- [ ] Inventory all of the CFD pages that have searches
- [ ] Inventory all of the filters for each search page
- [ ] Note any pages where the data is not intuitive
- [ ] Note places where filters may be missing 
- [ ] Note data questions that our filters can't answer

**Comment by llienfec** [comment]
### Filter inventory
Here's the filter inventory with notes :lock: https://docs.google.com/document/d/1C56sLrZQxEYKukhPcQOHGLfwYSziRNLL9ulORtv8QdM/edit?usp=sharing :lock:

### Summary of findings
- To me, data is least intuitive on the Filings and reports pages.  "All filings" has "Pres/House&Senate/PAC&party reports" as subsections.  However, these filters are not subsets of the all filings filters.  We're expecting users to know the difference between reports and filings - which is probably not reasonable.  
- I can't pull data I'd expect to be able to find, like "all form 1s for SSFs."  
- The reports filters are very confusing, functioning like the calendar filters.

### Next steps
- Seek requests/feedback from outward facing offices about filters.  @PaulClark2 
- Maybe set parameters for what you're looking for.  For example, user or caller pain points, data that users go to classic for instead. I'm not sure what the end goal is for the filter work, so keeping the parameters narrow may help with scope creep.

**Comment by llienfec** [comment]
Closing since inventory is complete.
