### ISSUE TITLE
Find and synthesize existing classic map research

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3161]
What do we want:
Considerable effort was put in to researching the effectiveness of the classic maps. We want to synthesize the research.

Why do we want it?
So we can leverage this research to apply to the national election presentation.

- [x] Find Nicky's research
- [ ] Synthesize the research

**Comment by JonellaCulmer** [comment]
Elections research can be found here: https://drive.google.com/drive/folders/0ByABoLSXWk1lVFUwUGNhYTB5MUk
Elections data: research readout:
https://docs.google.com/presentation/d/1otz-6RhaGJF1azldHGoyXnVcTVTveNSEeUjqiqRS68k/edit#slide=id.p

**Comment by JonellaCulmer** [comment]
Consolidated readout of the elections map research, here: 

https://docs.google.com/presentation/d/1aKKRxaSknQ-1fQRus_t1g2-jtMK6f3mnpluZsBC5dX0/edit#slide=id.g23d48f1049_0_202
