### ISSUE TITLE
Add upcoming election data to Map feature

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3168]
There should be drop-down options for the 2019-2020 and 2021 and 2022 cycles through the Election Map. https://www.fec.gov/data/elections/

**Comment by JonellaCulmer** [comment]
@lbeaufort is amazing and she did this already!

**Comment by lbeaufort** [comment]
PR is here: https://github.com/fecgov/fec-cms/pull/2254 🎉
