### ISSUE TITLE
Swagger user testing

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3170]
@llienfec commented on [Thu May 24 2018](https://github.com/fecgov/fec-cms/issues/2003)

API has a bunch of endpoints.  We're dividing and conquering to get this Swagger testing done!

### Testing plan
- [x] ID endpoints to test
- [x] Wenchun will divide and give team members to test, high-level test script. (2 story point to assign)
- [x] Wenchun and @patphongs will run through an example test
- [x] pull down locally and test (1 story point per person).  Connect to dev to test.

### Things to test
- Open endpoint and get a response back.  
- Make sure it executes.  
- Does bad info return a 500? 
- Required fields are still required.  
- Compare to existing site.

---

@patphongs commented on [Tue May 29 2018](https://github.com/fecgov/fec-cms/issues/2003#issuecomment-392877307)

Related to: https://github.com/fecgov/openFEC/issues/3094

---

@wjiangFEC commented on [Thu May 31 2018](https://github.com/fecgov/fec-cms/issues/2003#issuecomment-393720310)

@apburnes Rohan and I did a quick test, it looks good to us except the text box seems not populating the items correctly.  The items are there in the text box but did not display correctly.

---

@apburnes commented on [Fri Jun 01 2018](https://github.com/fecgov/fec-cms/issues/2003#issuecomment-393872935)

@wjiangFEC can you elaborate on which routes and/or data types should be looked at to test the text box functionality?

**Comment by patphongs** [comment]
### Install branch on your local:
1. git pull feature/update-swaggerui
2. delete node_modules folder under openFEC
3. npm install
4. npm run build
5. ./manage.py runserver
6. Connection should be to prod database

### Assignments for endpoint testing
- [ ] candidate (Helen)
- [ ] committee (Wenchun)
- [ ] dates (Wenchun)
- [ ] financial (Helen)
- [ ] search (Rohan)
- [ ] filings (Helen)
- [ ] receipts (Jean)
- [ ] disbursements (Jean)
- [ ] loans (Rohan)
- [ ] debts (Rohan)
- [ ] independent expenditures (Rohan)
- [ ] party-coordinated expenditures (Jean)
- [ ] communication cost (Priya)
- [ ] electioneering (Priya)
- [x] filer resources (Priya has already checked)
- [ ] efiling (Wenchun)
- [ ] audit (Jun)
          - One bug, there is a `Could not render this component, see the console` error on the category_id and category_sub_id parameter

**Comment by rjayasekera** [comment]
During the the testing I have encountered passing parameters to the API.  
Below image form `Search` endpoint
![image](https://user-images.githubusercontent.com/20324717/41233832-8cf445ac-6d58-11e8-9281-4353ac6d417e.png)

**Comment by rjayasekera** [comment]
The above form parameter issue caused by browser cache.  After I delete all browser history and cache I was able pass in form parameters to API end point

**Comment by pkfec** [comment]
/communication-cost/ counts are off ,  just like /electioneering/ endpoint.

**Comment by patphongs** [comment]
This has been completed and PR has been merged. We will do further testing in dev.
