### ISSUE TITLE
Confirm forms 5, 7, 9 and 13 filings are available on reports and filings page

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3179]
Confirm forms 5, 7, 9 and 13 filings are available on reports and filings page

@llienfec could you look at this and flesh it out please?

**Comment by llienfec** [comment]
Sure thing, @jwchumley.  Here's what I remember from our PI planning discussion:

### To do:
- [ ] Research: @PaulClark2 gets more information from users reporting the issue.  Do they have specific committee examples?  Is it every instance of a particular form (example: all Form 5s or just 1 Form 5 is missing)?  Which pages/views are documents missing from?
- [ ] Data QC: @llienfec takes the info above and tests the pages to see if we can find missing information, verify the problem, and look for themes/commonalities.   

Hopefully all filings are present.  If not:
- [ ] Work with devs to come up with a solution for fixing the issue
- [ ] Open a new ticket for fixing the issue.

**Comment by PaulClark2** [comment]
@llienfec  We might need to wait until Monday when Ryan is back. I'm finding filings on these form types from the filing and reports page and from committee profile pages. 

https://www.fec.gov/data/filings/?data_type=processed&form_type=F5
https://www.fec.gov/data/committee/C90014838/?cycle=2016&tab=filings

https://www.fec.gov/data/filings/?data_type=processed&form_type=F7
https://www.fec.gov/data/committee/C70001979/?tab=filings

https://www.fec.gov/data/filings/?data_type=processed&form_type=F9
https://www.fec.gov/data/committee/C30002778/?tab=filings

https://www.fec.gov/data/filings/?data_type=processed&form_type=F13
https://www.fec.gov/data/committee/C00629584/?tab=filings

**Comment by llienfec** [comment]
Awesome, thanks @PaulClark2.  I logged questions for them above that will greatly speed up the research:

- Do they have specific committee examples? 
- Is it every instance of a particular form (example: all Form 5s or just 1 Form 5 is missing)? 
- Which pages/views are documents missing from?

**Comment by PaulClark2** [comment]
I'll email Ryan but, as you know, he's out until Monday.

**Comment by PaulClark2** [comment]
@llienfec I misunderstood this request. 

I spoke with Ryan and Debbie about it. 

Add “Other Filers” Section to Website – This should be for Forms 5, 7, 9, and 13 filers.  Perhaps, and this might be stretching things, we could re-label the “Help for candidates and committees” to “Help for candidates and other filers.”  I am guessing this was a hot topic eons ago, but with the rise in F5 and F9 filings it seems like we should be paying more attention to them on the website.  Also, the current sub-categories under that section don’t even reference other filers.

**Comment by llienfec** [comment]
Closing ticket - research and scoping for new sections is here: https://github.com/fecgov/fec-cms/issues/2131
