### ISSUE TITLE
Ask public facing offices if other pages are missing filters

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3180]
What we want:
To hear from Public records and Press and Info if there are other pages in our data section, in addition to the IE search pages and other searches that have been flagged by internal and external users, that should have more filters options to improve usability.

Why we want it:
Our goal is to make campaign finance data accessible in the way users want to receive it.

-[ ] receive input from PubRec,  Press and Info on pages with missing filters

**Comment by AmyKort** [comment]
Press and public records have reached out with their data needs.
