### ISSUE TITLE
18F training task: Figure out automated testing

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3182]
Prep and give a two-hour workshop on the why and how of writing tests for Django. It'll cover the benefits of testing, how to run the test suite, and how to write tests, with a brief intro to test-driven development. The goal will be to have everyone write and run a simple test in the workshop.

**Comment by annalee** [comment]
Prep and give a two-hour workshop on the why and how of writing tests for Django. It'll cover the benefits of testing, how to run the test suite, and how to write tests, with a brief intro to test-driven development. The goal will be to have everyone write and run a simple test in the workshop.

**Comment by JonellaCulmer** [comment]
@annalee Are you able to put something on the schedule for this sprint? Since you/re departing at the end of the month it would be good to handle as soon as possible and leave room for lingering questions after the fact. 

Let me know if I can help you schedule this.

**Comment by annalee** [comment]
Hey Jonella, does the team have availability next Thursday the 19th? My last day is actually the 20th, so ideally we want a time when @vrajmohan can participate as well so he can take follow-up questions.

**Comment by JonellaCulmer** [comment]
This workshop has been scheduled for July 16 10am-12pm ET.

**Comment by annalee** [comment]
Hey team! The videos are here: https://drive.google.com/open?id=1si64SLoMGZY9sJsfjEeTnHSZbj2wgBdn

**Comment by JonellaCulmer** [comment]
We had a great workshop on automated testing, we can now close this issue in favor of the aforementioned videos in the previous comment.
