### ISSUE TITLE
Make election fixes as necessary based on feedback from Press/Public records

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3183]
This hinges on getting feedback from press and public records. There may be no work or they may not complete review but if they do, this is where the fixes will take place.

Sticky says Pat and Andrew.

**Comment by JonellaCulmer** [comment]
This is the list prioritizing the feedback/recommendations from Press/Public Records: 
https://docs.google.com/document/d/1deFYtnN1RL_fPQIt83-wFQHDpPuuXWaPQ59CrxLvTTY/edit#

These are the issues resulting from that feedback: 
FEC-cms: https://github.com/fecgov/fec-cms/issues/2085
FEC-cms: https://github.com/fecgov/fec-cms/issues/2087
FEC-cms: https://github.com/fecgov/fec-cms/issues/2088
openFEC: https://github.com/fecgov/openFEC/issues/3209

Closing this issue in favor of those listed above.
