### ISSUE TITLE
Log monitoring sprint 6.2  (the robot) week 2

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3187]

**Comment by fec-jli** [comment]
**1---Check 4 repos on SNYK**
1) FEC-CMS: 
a)**[MED]**  Regular Expression Denial of Service (DoS) , Issue: [https://github.com/fecgov/fec-cms/issues/1953](https://github.com/fecgov/fec-cms/issues/1953)

2) FEC-EREGS:  None

3)FEC-PATTERN-LIB:
a) **[HIGH]** Command Injection 
Issue: [https://github.com/fecgov/fec-pattern-library/issues/121](https://github.com/fecgov/fec-pattern-library/issues/121)

b)**[MED]** Regular Expression Denial of Service (ReDoS) 
Issue:[https://github.com/fecgov/fec-pattern-library/issues/116](https://github.com/fecgov/fec-pattern-library/issues/116)
related Issue: [https://github.com/fecgov/fec-pattern-library/pull/119](https://github.com/fecgov/fec-pattern-library/pull/119)

c) Report Four [LOW] risk issues, we only can see 2 issue sections from web page: 
   -Prototype Pollution :  Vulnerable module: lodash
   -Regular Expression Denial of Service (ReDoS) : Vulnerable module: braces
Issue: [https://github.com/fecgov/fec-pattern-library/issues/117](https://github.com/fecgov/fec-pattern-library/issues/117)
related Issue: [https://github.com/fecgov/fec-pattern-library/pull/119](https://github.com/fecgov/fec-pattern-library/pull/119)

4) OPENFEC: None
