### ISSUE TITLE
Ongoing - Document existing database model

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3188]
Ongoing - Document existing database model to strategize future materialized view work.

**Comment by vrajmohan** [comment]
IIRC, @fecjjeng created an update diagram of the materialized view dependencies. Assigning this issue to @fecjjeng to publish the document (perhaps in the Wiki) and provide a link to it in this issue.

**Comment by JonellaCulmer** [comment]
@rjayasekera

**Comment by rjayasekera** [comment]
@lbeaufort please take a look at the wiki link
https://github.com/fecgov/openFEC/wiki/Create-Database-model-diagram

**Comment by AmyKort** [comment]
With https://github.com/fecgov/openfec/issues/3165 closed, this shouldn't be blocked. Can I move it to Ready?

**Comment by wjiangFEC** [comment]
Amy,

In last grooming, I asked to have this ticket closed. Please closed this ticket (3188). Vraj has generated diagrams for current MVs. I don't think we should ask DBA or developers to spend more time to do more database document at this moment. We will need to have a longer time plan to redesign the MVs in the future.

Regards,

Wenchun Jiang

On Jul 6, 2018, at 1:01 PM, Amy Kort <notifications@github.com<mailto:notifications@github.com>> wrote:


With fecgov#3165<https://github.com/fecgov/openFEC/issues/3165> closed, this shouldn't be blocked. Can I move it to Ready?

**Comment by AmyKort** [comment]
Closing while we look into a longer term plan.
