### ISSUE TITLE
Research - Data not showing for host committees

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3197]
https://www.fec.gov/data/committee/C00431593/?cycle=2008&tab=summary
https://www.fec.gov/data/committee/C00572958/?cycle=2018

It looks like we're giving a no data message for host committees.

**Comment by jwchumley** [comment]
I will have to get confirmation that the committee profile pages use the totals/committee_type endpoint but I think they do. 

The problem with that endpoint is that, like some of the other endpoints we've been fixing, it assumes that a committee of a specific type always files on a specific form. In this case the committees are mostly X and Y  with a few N. Those types normally file form 3X but in this case they correctly file Form 4 and that isn't included in the views.

ofec_totals_parties_mv
ofec_totals_pacs_parties_mv

they are built on ofec_totals_combined_mv which seems to have all the data so correcting the other two is probably the best way to go. 

I think the enpoint code is probably fine but the views need to change.
