### ISSUE TITLE
Investigate and expand committee_id limit beyond five values

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#3209]
**What we're after:** For candidates with more than 5 authorized committees, the individual contributions table does not yield results. We need to explore expanding that 5 committee_id limit so that the website does not appear non-function and so we can return accurate results. This, of course, must be balanced with performance. 

**Example:** Select a figure from the individual contributions table on the election profile page to recreate problem. 
Tim Kaine: 
**Election profile page:** https://www.fec.gov/data/elections/senate/VA/2018/?tab=contributions 
**Individual contributions data table:** https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2018&committee_id=C00495358&committee_id=C00572388&committee_id=C00631960&committee_id=C00648071&committee_id=C00648089&committee_id=C00648238&committee_id=C00662114&min_date=01%2F01%2F2017&max_date=06%2F12%2F2018&min_amount=0.00&max_amount=200.00 
**API call:** https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=true&committee_id=C00495358&committee_id=C00572388&committee_id=C00631960&committee_id=C00648071&committee_id=C00648089&committee_id=C00648238&committee_id=C00662114&two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=06%2F12%2F2018&min_amount=0.00&max_amount=200.00&sort=-contribution_receipt_date&per_page=30&is_individual=true 

- [ ] Make sure this addresses https://github.com/fecgov/fec-cms/issues/1656

**Comment by lbeaufort** [comment]
Update - our use case for removing the 5-committee restriction was caused by a bug in the election profile pages - I updated the issue https://github.com/fecgov/fec-cms/issues/1656

Until we have a strong use case for removing the restriction, @PaulClark2 and I agree that we should table this change. We plan to implement a committee type filter in 6.4.
