### ISSUE TITLE
Log monitoring sprint 6.3  (Judy Robinson) week 1

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3212]
Log review needs to be completed for Judy Robinson week 1 per the [Security Event Review Checklist](https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by pkfec** [comment]
- **FEC-CMS**
 1. Regular Expression Denial of Service (DoS) **[MED]** fecgov/fec-cms#1953
 2. Regular Expression Denial of Service (ReDoS) **[HIGH]** https://github.com/fecgov/fec-cms/issues/2163

- **OPENFEC**
  _None_

- **FEC-EREGS**
  _None_

- **FEC-PATTERN-LIB**
1. Command Injection **[HIGH]** fecgov/fec-pattern-library#121
2. Regular Expression Denial of Service (ReDoS) [MED] fecgov/fec-pattern-library#116
3. Two low risk issues(reported on Snyc) [LOW] fecgov/fec-pattern-library#117
   - Prototype Pollution :  Vulnerable module: lodash
   - Regular Expression Denial of Service (ReDoS) : Vulnerable module: braces

-  **Add/Update User Account**
     _None_

- **Deployer Accounts/Service Keys**
   - 10 service keys found on **cloud.gov** under **fec-beta-fec** org

**Comment by pkfec** [comment]
Log review completed on 07/03/18.
