### ISSUE TITLE
Presidential 2017 - 2020 data on adv data table not displaying properly

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3214]
@JonellaCulmer commented on [Wed Apr 25 2018](https://github.com/fecgov/fec-cms/issues/1950)

Relevant issue: #1949 

**What we're after:** The Presidential candidates advanced data table is not displaying data for the two-year periods within the 4-year presidential cycle. When viewing 2017-2020 data, we get a full list of candidates currently raising and spending money for the 2020 election. However, upon filtering to view 2017-2018 data, the tables are empty. We need to display data by both 2017-2020 and by two-year periods.

Completion:
- [ ] Identify desired interaction for buttons

<img width="1197" alt="screen shot 2018-04-25 at 11 53 53 am" src="https://user-images.githubusercontent.com/31663028/39257467-98e5666e-487f-11e8-8349-0b9f7f544ed8.png">
<img width="1113" alt="screen shot 2018-04-25 at 11 55 06 am" src="https://user-images.githubusercontent.com/31663028/39257475-9cfbc55e-487f-11e8-9712-792df4c81758.png">

---

@AmyKort commented on [Fri May 25 2018](https://github.com/fecgov/fec-cms/issues/1950#issuecomment-392093205)

Is this something that will be dependent on https://github.com/fecgov/fec-cms/issues/2007 ?

**Comment by JonellaCulmer** [comment]
There appears to be a similar issue happening with the Senate candidates datatable as well as the Senate table is also pulling from the candidate/totals endpoint. Using inspect and viewing the API call, if I remove the cycle and election-year data populates, beyond that I'm not able to pinpoint the cause. 

Perhaps your fix will also help in some way with this data as well? I'm happy to pair on this for however long. 
https://www.fec.gov/data/candidates/senate/?election_year=2020&cycle=2020&election_full=false

Side note: The Candidates table, which I know, is under the candidates endpoint, shows about 13 individuals registered for the 2020 election and beyond.

**Comment by lbeaufort** [comment]
Thanks for your research, @JonellaCulmer! The fix should address candidate totals for candidates who have declared for future election cycles - house/senate/presidential. I'm still in the process of testing, though.

**Comment by JonellaCulmer** [comment]
@lbeaufort House candidates look to be about the same as Senate and Presidential, excluding the "All years" option, which is not utilized on this table. 

Although, for House candidates, we do have candidates registered for elections up until 2028. I'm not confident we need to list elections out that far in advance.
