### ISSUE TITLE
Missing Total - Discrepancy between two API calls

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3215]
@JenBroad commented on [Fri Jun 15 2018](https://github.com/fecgov/FEC/issues/6313)

We've found two versions of the FEC API for summary totals:
https://api.open.fec.gov/v1/committee/C00402826/reports/?page=1&sort=-coverage_end_date&api_key=DEMO_KEY&per_page=20

https://api.open.fec.gov/v1/efile/reports/pac-party/?page=1&sort=-receipt_date&api_key=DEMO_KEY&committee_id=C00402826&per_page=20

We noticed that on the first version listed about there is a field called "refunded_political_party_committee_contributions_ytd", but there is no corresponding field on the second version - nothing that corresponds with Line 20(c) on the Form 3 or Line 28(c) on the Form 3x. 

When I brought this up to Ken Lally, he had me work with Satheesh Panyala, who asked me to create a ticket.

I can be reached at: broadbent@ispolitical.com if you have any questions.

Thanks so much!

---

@AmyKort commented on [Fri Jun 15 2018](https://github.com/fecgov/FEC/issues/6313#issuecomment-397697670)

Thanks so much for reporting this!

**Comment by PaulClark2** [comment]
The political party refund fields in the /efile/reports/ endpoint have unfortunate names: "political_party_committee_contributions_per_ii" and "political_party_committee_contributions_ytd_ii." If you take a look at filing 1211799 it's a little easier to see. This report has both party contributions and refunds of party contributions. 

API
https://api.open.fec.gov/v1/efile/reports/pac-party/?sort=-receipt_date&page=1&per_page=20&file_number=1211799&api_key=DEMO_KEY

Image
http://docquery.fec.gov/pdf/363/201802289095633363/201802289095633363.pdf

**Comment by JonellaCulmer** [comment]
@JenBroad Please let us know if the above doesn't answer your question. https://github.com/fecgov/openFEC/issues/3215#issuecomment-397728308
