### ISSUE TITLE
Change coverage end date logic for candidate and committee raising/spending pages

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3217]
(Update: a PR for coverage end date has been merged -
3251 (https://github.com/fecgov/openFEC/pull/3251); the remaining work is back-end Python work)

Moved from https://github.com/fecgov/fec-cms/issues/2008

### Committee and Candidate raising/spending page: coverage date box issues

Use aggregate tables with operations log to determine correct coverage end date of transaction level data. Update committee/(ID)/totals `coverage_end_date`

https://api.open.fec.gov/v1/committee/C00053553/totals/?api_key=DEMO_KEY
https://api.open.fec.gov/v1/candidate/S2MA00170/totals/?api_key=DEMO_KEY

`coverage_end_date` should pull from the new view

- Raising examples (individual contributions section), https://www.fec.gov/data/committee/C00053553/?tab=raising
https://www.fec.gov/data/candidate/S2MA00170/?tab=raising

- Spending examples: 
https://www.fec.gov/data/committee/C00053553/?tab=spending
https://www.fec.gov/data/candidate/S2MA00170/?tab=spending

![image](https://user-images.githubusercontent.com/11817734/41546530-e412613c-72eb-11e8-8016-d3ba507ca8ef.png)

Research:

- Endpoints are /committee/(ID)/totals and /candidate/(ID)/totals
- Output field to change is `coverage_end_date`
- Resources are `TotalsCommitteeView` and `CandidateTotalsView`
- Data flow is:
Committee:
`TotalsCommitteeView < ofec_totals_pacs_parties_mv < ofec_totals_combined_mv < ofec_totals_combined_mv < disclosure.v_sum_and_det_sum_report`

Candidate:

To-Do: 
- [x] Make a migration for `public.ofec_agg_coverage_date_vw`. Check with Paul to make sure `cvg_end_date` logic follows the business rules. Consider using full-word column names (team [naming conventions](https://launchbylunch.com/posts/2014/Feb/16/sql-naming-conventions/#naming-conventions))
- [X] In SQLalchemy, update candidate/ID/totals and committee/ID/totals to use `cvg_end_date` from the new MV 
- Note: I changed the candidate totals on the MV side because it's a `1-many` relationship between candidates and committees. `ofec_totals_candidate_committees_mv`. On the committee side, I modified on the SQLAlchemy/Python side because it's a `1-1` relationship and there are 7 possible models:
```    'P': models.CommitteeTotalsPresidential = ofec_totals_presidential_mv
    'H': models.CommitteeTotalsHouseSenate = ofec_totals_house_senate_mv
    'S': models.CommitteeTotalsHouseSenate = ofec_totals_house_senate_mv
    'I': models.CommitteeTotalsIEOnly = ofec_totals_ie_only_mv
    'O': models.CommitteeTotalsPac = ofec_totals_pacs_mv
    'XY': models.CommitteeTotalsParty = ofec_totals_parties_mv
    'default_schemas': models.CommitteeTotalsPacParty = ofec_totals_pacs_parties_mv
```
- [x] Fall back on the coverage end date in the MV if it's too old (there's no entry for 1996 for C00213512, for example)![Screen Shot 2018-07-30 at 10.17.45 AM.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/10f1567f-d7b0-4187-bf9e-98ea993b5ab4)
- [x] Check the front-end behavior for 1st time filers whose reports haven't been processed (maybe consider adding some test data, as this is a moving target) - example as of 7/6 is C00675249
![Screen Shot 2018-07-30 at 10.27.24 AM.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/ea7c80c9-4d8d-4ecd-a346-c90f0f8d1ab6)
- [x] Fix an issue with `ofec_agg_coverage_date_mv` returning incorrect dates for committees with amendments (Paul is working with DBA team - example is C00000935 shows 3/31 when it should show 5/31 as of 7/30)
- [x] Fix failing tests - try making the join on the model level, not the query level - see proposed schedule A PR
- [x] Test the front-end ending coverage date for candidate and committee profile pages
- [x] Add automated tests 
- [ ] Remove temporary MV's in `dev` after merge

Note: I moved the "aggregates by states" issue to https://github.com/fecgov/openFEC/issues/3246

**Comment by PaulClark2** [comment]
From Slack: What do you except coverage date to be for this C00235309 ? 06-17-2018?

The coverage dates for C00235309  for the 2017-18 two-year period should be 1/1/17 to 5/31/2018. This committee's 2018 M6 report is completely processed. 

`select 
cand_cmte_id, rpt_yr, O.BEGINNING_COVERAGE_DT, O.ENDING_COVERAGE_DT, rpt_tp, receipt_dt, O.PASS_3_ENTRY_DONE_DT
from STAGING.OPERATIONS_LOG o where cand_cmte_id = 'C00235309' and rpt_yr in (2017, 2018) and form_tp like 'F3X%' 
order by O.ENDING_COVERAGE_DT, receipt_dt;`

**Comment by ChingKuan** [comment]
created materialized view public.ofec_agg_coverage_date_mv - it'll take the max(ENDING_COVERAGE_DT) from operations_log when pass_3_entry_done_dt is not null.

**Comment by ChingKuan** [comment]
just use mv. 
To get coverage end date, example -
(select cvg_end_date from public.ofec_agg_coverage_date_vw 
 where  cand_cmte_id = 'C00003418' and  fec_election_yr  = 2018)
In Python - Add another variable to hold this cvg_end_date and display it on that pages - 
![image](https://user-images.githubusercontent.com/24719816/41998214-36d25f24-7a28-11e8-977f-6b6bab38d1c3.png)

**Comment by lbeaufort** [comment]
@ChingKuan thanks - is there a migration for that materialized view? Sorry if I missed it.

**Comment by lbeaufort** [comment]
In order to get the MV into production, we need to have a migration file here: https://github.com/fecgov/openFEC/tree/develop/data/migrations

**Comment by ChingKuan** [comment]
I'll try to create one.  Do you know who will work this on Python?

**Comment by lbeaufort** [comment]
I'm not sure, no.

**Comment by ChingKuan** [comment]
A PR for coverage end date  is created -
[3251](https://github.com/fecgov/openFEC/pull/3251)

**Comment by lbeaufort** [comment]
Thanks, @ChingKuan! The remaining work is back-end python work, slated for 6.4.

**Comment by PaulClark2** [comment]
@lbeaufort I agree we should create a new field for the transactions processed date. The issue we are trying to fix is to correctly display the coverage end date when the summary coverage end date and the transaction processed coverage end date are not the same.

**Comment by lbeaufort** [comment]
Update: WIP PR's for prototyping here: 

https://github.com/fecgov/openFEC/pull/3310
https://github.com/fecgov/fec-cms/pull/2223

![Screen Shot 2018-07-26 at 4.58.34 PM.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/0ab72422-cd0f-4039-bf32-9af6d7d316ca)
