### ISSUE TITLE
Candidate not showing in CO 7

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3218]
@fec-issues-bot commented on [Mon Jun 18 2018](https://github.com/fecgov/FEC/issues/6384)

## What were you trying to do and how can we improve it?
 Trying to find a candidate's reports. The incumbent, who has shown up here in the past, is missing from the Colorado CD 7 search results. 

## Tell us about yourself
 A reporter interested in doing my job. 

## Details
* URL: https://www.fec.gov/data/elections/house/CO/07/2018/ 
* User Agent: Amazon CloudFront

---

@AmyKort commented on [Mon Jun 18 2018](https://github.com/fecgov/FEC/issues/6384#issuecomment-398136013)

Thank you for reporting this!

**Comment by AmyKort** [comment]
Perlmutter shows in the 2015-2016 view, but is not showing for 2017-2018.

**Comment by lbeaufort** [comment]
@AmyKort The issue appears to be with the `ofec_candidate_history_mv` materialized view. It has marked the incumbent (H6CO07023) as inactive. The /elections/ endpoint filters for active candidates.

```
SELECT *
FROM ofec_candidate_history_mv 
WHERE ofec_candidate_history_mv.two_year_period <= 2018 
    AND ofec_candidate_history_mv.two_year_period > 2016 
    AND ofec_candidate_history_mv.candidate_election_year + ofec_candidate_history_mv.candidate_election_year % 2 = 2018 
    AND ofec_candidate_history_mv.office = 'H' 
    AND ofec_candidate_history_mv.state = 'CO' 
    AND ofec_candidate_history_mv.district = '07' 
    --AND ofec_candidate_history_mv.candidate_inactive = false
    AND ofec_candidate_history_mv.candidate_id='H6CO07023'
```

**Comment by AmyKort** [comment]
Thanks for looking into the root of this problem, @lbeaufort ! cc @PaulClark2

**Comment by lbeaufort** [comment]
@PaulClark2 @jwchumley it looks like the incumbent has an entry in `disclosure.cand_inactive` - does that seem right to you? https://ballotpedia.org/Ed_Perlmutter

```
select * from disclosure.cand_inactive where cand_id='H6CO07023'
```

**Comment by PaulClark2** [comment]
Looks like he's back in the CO-07 House race. I'll update the table and the ICIs for all the other candidates in that CD.

**Comment by PaulClark2** [comment]
Updates complete.  We should see the changes tomorrow morning.

**Comment by lbeaufort** [comment]
@AmyKort I confirmed that the incumbent appears

**Comment by lbeaufort** [comment]
![image](https://user-images.githubusercontent.com/31420082/41594796-a326797c-7392-11e8-9acc-5c61e722122b.png)
