### ISSUE TITLE
Elections endpoint is including joint fundraisers and inflating candidate receipts and disbursements

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3221]
https://www.fec.gov/data/elections/senate/VA/2018/

There are several issues with the SQL in the elections endpoint:

1. it is including joint fundraisers so any candidate that has one or more joint fundraiser has inflated figures (because the joint fundraising committee transfers money to the candidate committee so the money is already there)
  
- [x] add AND ofec_cand_cmte_linkage_mv.cmte_dsgn in ('A','P') to the anon_4 where clause

2. There are two tables that we use to make sure candidates are not on the list:
   disclosure.cand_inactive (for candidates that withdraw from an election) which is already included in one of the underlying views and:
   disclosure.unverified_cand_cmte (for candidates or committees that have been removed for administrative reasons) which is not accounted for

- [ ] Add unverified candidate statement to the where clause of the **anon_4** sub select:  
AND ofec_cand_cmte_linkage_mv.cand_id not in (select cand_cmte_id from disclosure.unverified_cand_cmte)

**Comment by fec-jli** [comment]
This(elections) endpoint is created based on ** ofec_totals_house_senate_mv**
then leftjoin a couple of queries using SQLAlchemy orm function.
Here is the final query, Could you look at it? Thanks:
`SELECT DISTINCT anon_1.candidate_id AS anon_1_candidate_id, anon_1.candidate_election_year AS anon_1_candidate_election_year, 
anon_1.candidate_name AS anon_1_candidate_name, 
anon_1.party_full AS anon_1_party_full, 
anon_1.incumbent_challenge_full AS anon_1_incumbent_challenge_full, 
anon_1.office AS anon_1_office, 
anon_1.total_receipts AS anon_1_total_receipts, 
anon_1.total_disbursements AS anon_1_total_disbursements, 
anon_1.cash_on_hand_end_period AS anon_1_cash_on_hand_end_period, anon_1.committee_ids AS anon_1_committee_ids, 
anon_1.coverage_end_date AS anon_1_coverage_end_date, 
anon_1.candidate_pcc_id AS anon_1_candidate_pcc_id, 
anon_2.candidate_id AS anon_2_candidate_id, 
anon_2.cash_on_hand_end_period AS anon_2_cash_on_hand_end_period, 
CASE WHEN (anon_3.cand_id IS NOT NULL) THEN :param_1 ELSE :param_2 END AS won, ofec_committee_detail_mv.name AS candidate_pcc_name 
FROM (SELECT anon_4.candidate_id AS candidate_id, anon_4.candidate_election_year AS candidate_election_year, max(anon_4.name) AS candidate_name, max(anon_4.party_full) AS party_full, max(anon_4.incumbent_challenge_full) AS incumbent_challenge_full, max(anon_4.office) AS office, sum(coalesce(anon_4.receipts, :param_3)) AS total_receipts, sum(coalesce(anon_4.disbursements, :param_4)) AS total_disbursements, sum(coalesce(anon_4.cash_on_hand_end_period, :param_5)) AS cash_on_hand_end_period, array_agg(DISTINCT anon_4.cmte_id) AS committee_ids, max(anon_4.coverage_end_date) AS coverage_end_date, max(anon_4.candidate_pcc_id) AS candidate_pcc_id 
FROM (SELECT DISTINCT ofec_candidate_history_mv.candidate_id AS candidate_id, ofec_candidate_history_mv.name AS name, 
ofec_candidate_history_mv.party_full AS party_full, ofec_candidate_history_mv.incumbent_challenge_full AS incumbent_challenge_full, ofec_candidate_history_mv.office AS office, 
ofec_candidate_history_mv.two_year_period AS two_year_period, ofec_candidate_history_mv.candidate_election_year AS candidate_election_year, ofec_cand_cmte_linkage_mv.cmte_id AS cmte_id, 
ofec_totals_house_senate_mv.receipts AS receipts, 
ofec_totals_house_senate_mv.disbursements AS disbursements, ofec_totals_house_senate_mv.last_cash_on_hand_end_period AS cash_on_hand_end_period, ofec_totals_house_senate_mv.coverage_end_date AS coverage_end_date, 
CASE WHEN (ofec_cand_cmte_linkage_mv.cmte_dsgn = :cmte_dsgn_1) THEN ofec_cand_cmte_linkage_mv.cmte_id END AS candidate_pcc_id 
FROM ofec_candidate_history_mv 
LEFT OUTER JOIN ofec_cand_cmte_linkage_mv ON ofec_candidate_history_mv.candidate_id = ofec_cand_cmte_linkage_mv.cand_id AND ofec_candidate_history_mv.two_year_period = ofec_cand_cmte_linkage_mv.fec_election_yr 
LEFT OUTER JOIN ofec_totals_house_senate_mv ON ofec_cand_cmte_linkage_mv.cmte_id = ofec_totals_house_senate_mv.committee_id AND ofec_cand_cmte_linkage_mv.fec_election_yr = ofec_totals_house_senate_mv.cycle 
WHERE ofec_candidate_history_mv.two_year_period <= :two_year_period_1 AND ofec_candidate_history_mv.two_year_period > :two_year_period_2 AND ofec_candidate_history_mv.candidate_election_year + ofec_candidate_history_mv.candidate_election_year % :candidate_election_year_1 = :param_6 AND ofec_candidate_history_mv.office = :office_1 AND ofec_candidate_history_mv.state = :state_1 AND ofec_candidate_history_mv.candidate_inactive = 0) AS anon_4 
GROUP BY anon_4.candidate_id, anon_4.candidate_election_year) AS anon_1 

LEFT OUTER JOIN (SELECT anon_5.candidate_id AS candidate_id, sum(coalesce(anon_5.cash_on_hand_end_period, :param_7)) AS cash_on_hand_end_period 
FROM (SELECT DISTINCT anon_4.cash_on_hand_end_period AS cash_on_hand_end_period, anon_4.candidate_id AS candidate_id, anon_4.cmte_id AS cmte_id, anon_4.two_year_period AS two_year_period 
FROM (SELECT DISTINCT ofec_candidate_history_mv.candidate_id AS candidate_id, ofec_candidate_history_mv.name AS name, 
ofec_candidate_history_mv.party_full AS party_full, ofec_candidate_history_mv.incumbent_challenge_full AS incumbent_challenge_full, ofec_candidate_history_mv.office AS office, 
ofec_candidate_history_mv.two_year_period AS two_year_period, ofec_candidate_history_mv.candidate_election_year AS candidate_election_year, ofec_cand_cmte_linkage_mv.cmte_id AS cmte_id, 
ofec_totals_house_senate_mv.receipts AS receipts, 
ofec_totals_house_senate_mv.disbursements AS disbursements, ofec_totals_house_senate_mv.last_cash_on_hand_end_period AS cash_on_hand_end_period, ofec_totals_house_senate_mv.coverage_end_date AS coverage_end_date, CASE WHEN (ofec_cand_cmte_linkage_mv.cmte_dsgn = :cmte_dsgn_1) THEN ofec_cand_cmte_linkage_mv.cmte_id END AS candidate_pcc_id 
FROM ofec_candidate_history_mv 
LEFT OUTER JOIN ofec_cand_cmte_linkage_mv ON ofec_candidate_history_mv.candidate_id = ofec_cand_cmte_linkage_mv.cand_id AND ofec_candidate_history_mv.two_year_period = ofec_cand_cmte_linkage_mv.fec_election_yr 
LEFT OUTER JOIN ofec_totals_house_senate_mv ON ofec_cand_cmte_linkage_mv.cmte_id = ofec_totals_house_senate_mv.committee_id AND ofec_cand_cmte_linkage_mv.fec_election_yr = ofec_totals_house_senate_mv.cycle 
WHERE ofec_candidate_history_mv.two_year_period <= :two_year_period_1 AND ofec_candidate_history_mv.two_year_period > :two_year_period_2 AND ofec_candidate_history_mv.candidate_election_year + ofec_candidate_history_mv.candidate_election_year % :candidate_election_year_1 = :param_6 AND ofec_candidate_history_mv.office = :office_1 AND ofec_candidate_history_mv.state = :state_1 AND ofec_candidate_history_mv.candidate_inactive = 0) AS anon_4 
ORDER BY anon_4.candidate_id, anon_4.cmte_id, anon_4.two_year_period DESC) AS anon_5 

GROUP BY anon_5.candidate_id) AS anon_2 ON anon_1.candidate_id = anon_2.candidate_id LEFT OUTER JOIN (SELECT ofec_election_result_mv.cand_id AS cand_id 
FROM ofec_election_result_mv 
WHERE ofec_election_result_mv.election_yr = :election_yr_1 AND ofec_election_result_mv.cand_office = :cand_office_1 AND ofec_election_result_mv.cand_office_st = :cand_office_st_1 AND ofec_election_result_mv.cand_office_district = :cand_office_district_1) AS anon_3 
ON anon_1.candidate_id = anon_3.cand_id 
LEFT OUTER JOIN ofec_committee_detail_mv 
ON anon_1.candidate_pcc_id = ofec_committee_detail_mv.committee_id
`

**Comment by jwchumley** [comment]
Here is the corrected SQL. IT handles all the issues except committees filing on the wrong form which we need to correct globally rather than for each endpoint.

SELECT DISTINCT
       anon_1.candidate_id,
       anon_1.candidate_election_year,
       anon_1.candidate_name,
       anon_1.party_full,
       anon_1.incumbent_challenge_full,
       anon_1.office,
       anon_1.total_receipts,
       anon_1.total_disbursements,
       anon_1.cash_on_hand_end_period,
       anon_1.committee_ids,
       anon_1.coverage_end_date,
       anon_1.candidate_pcc_id,
       anon_2.candidate_id,
       anon_2.cash_on_hand_end_period,
       CASE WHEN (anon_3.cand_id IS NOT NULL) THEN TRUE ELSE FALSE END AS won,
       ofec_committee_detail_mv.name AS candidate_pcc_name
  FROM (SELECT anon_4.candidate_id AS candidate_id,
               anon_4.candidate_election_year AS candidate_election_year,
               MAX (anon_4.name) AS candidate_name,
               MAX (anon_4.party_full) AS party_full,
               MAX (anon_4.incumbent_challenge_full)
                  AS incumbent_challenge_full,
               MAX (anon_4.office) AS office,
               SUM (COALESCE (anon_4.receipts, 0.0)) AS total_receipts,
               SUM (COALESCE (anon_4.disbursements, 0.0))
                  AS total_disbursements,
               SUM (COALESCE (anon_4.cash_on_hand_end_period, 0.0))
                  AS cash_on_hand_end_period,
               array_agg (DISTINCT anon_4.cmte_id) AS committee_ids,
               MAX (anon_4.coverage_end_date) AS coverage_end_date,
               MAX (anon_4.candidate_pcc_id) AS candidate_pcc_id
          FROM (SELECT DISTINCT
                       ofec_candidate_history_mv.candidate_id AS candidate_id,
                       ofec_candidate_history_mv.name AS name,
                       ofec_candidate_history_mv.party_full AS party_full,
                       ofec_candidate_history_mv.incumbent_challenge_full  AS incumbent_challenge_full,
                       ofec_candidate_history_mv.office AS office,
                       ofec_candidate_history_mv.two_year_period   AS two_year_period,
                       ofec_candidate_history_mv.candidate_election_year   AS candidate_election_year,
                       ofec_cand_cmte_linkage_mv.cmte_id AS cmte_id,
                       ofec_totals_house_senate_mv.receipts AS receipts,
                       ofec_totals_house_senate_mv.disbursements  AS disbursements,
                       ofec_totals_house_senate_mv.last_cash_on_hand_end_period  AS cash_on_hand_end_period,
                       ofec_totals_house_senate_mv.coverage_end_date   AS coverage_end_date,
                       CASE
                          WHEN (ofec_cand_cmte_linkage_mv.cmte_dsgn = 'P')
                          THEN
                             ofec_cand_cmte_linkage_mv.cmte_id
                       END  AS candidate_pcc_id
                  FROM ofec_candidate_history_mv
                       LEFT OUTER JOIN ofec_cand_cmte_linkage_mv
                          ON     ofec_candidate_history_mv.candidate_id =   ofec_cand_cmte_linkage_mv.cand_id
                             AND ofec_candidate_history_mv.two_year_period =   ofec_cand_cmte_linkage_mv.fec_election_yr
                             AND ofec_cand_cmte_linkage_mv.cmte_dsgn in ('A','P') -- added by Jeff  to remove joint fundraisers from the output
                       LEFT OUTER JOIN ofec_totals_house_senate_mv
                          ON     ofec_cand_cmte_linkage_mv.cmte_id =  ofec_totals_house_senate_mv.committee_id
                             AND ofec_cand_cmte_linkage_mv.fec_election_yr =   ofec_totals_house_senate_mv.cycle
                 WHERE     ofec_candidate_history_mv.two_year_period <= 2018
                       AND ofec_candidate_history_mv.two_year_period > 2016
                       AND ofec_candidate_history_mv.candidate_id not in (select cand_cmte_id from disclosure.unverified_cand_cmte) -- added by Jeff to remove unverified candidates from the output
                       AND ofec_candidate_history_mv.candidate_election_year + mod(ofec_candidate_history_mv.candidate_election_year, 2) = 2018 
                       AND ofec_candidate_history_mv.office = 'S' 
                       AND ofec_candidate_history_mv.state = 'CA' 
                       AND ofec_candidate_history_mv.district = '00' 
                       AND ofec_candidate_history_mv.candidate_inactive = false) AS anon_4 
                       GROUP BY anon_4.candidate_id, anon_4.candidate_election_year) AS anon_1 
                       LEFT OUTER JOIN (SELECT anon_5.candidate_id AS candidate_id, 
			sum(coalesce(anon_5.cash_on_hand_end_period, 0.0)) AS cash_on_hand_end_period
FROM (SELECT DISTINCT ON (anon_4.candidate_id, anon_4.cmte_id) anon_4.cash_on_hand_end_period AS cash_on_hand_end_period, anon_4.candidate_id AS candidate_id
FROM (SELECT DISTINCT ofec_candidate_history_mv.candidate_id AS candidate_id, ofec_candidate_history_mv.name AS name, ofec_candidate_history_mv.party_full AS party_full, ofec_candidate_history_mv.incumbent_challenge_full AS incumbent_challenge_full, ofec_candidate_history_mv.office AS office, ofec_candidate_history_mv.two_year_period AS two_year_period, ofec_candidate_history_mv.candidate_election_year AS candidate_election_year, ofec_cand_cmte_linkage_mv.cmte_id AS cmte_id, ofec_totals_house_senate_mv.receipts AS receipts, ofec_totals_house_senate_mv.disbursements AS disbursements, ofec_totals_house_senate_mv.last_cash_on_hand_end_period AS cash_on_hand_end_period, ofec_totals_house_senate_mv.coverage_end_date AS coverage_end_date, CASE WHEN (ofec_cand_cmte_linkage_mv.cmte_dsgn = 'P') THEN ofec_cand_cmte_linkage_mv.cmte_id END AS candidate_pcc_id
FROM ofec_candidate_history_mv LEFT OUTER JOIN ofec_cand_cmte_linkage_mv ON ofec_candidate_history_mv.candidate_id = ofec_cand_cmte_linkage_mv.cand_id AND ofec_candidate_history_mv.two_year_period = ofec_cand_cmte_linkage_mv.fec_election_yr LEFT OUTER JOIN ofec_totals_house_senate_mv ON ofec_cand_cmte_linkage_mv.cmte_id = ofec_totals_house_senate_mv.committee_id AND ofec_cand_cmte_linkage_mv.fec_election_yr = ofec_totals_house_senate_mv.cycle
WHERE ofec_candidate_history_mv.two_year_period <= 2018 AND ofec_candidate_history_mv.two_year_period > 2016 AND ofec_candidate_history_mv.candidate_election_year + mod(ofec_candidate_history_mv.candidate_election_year,2) = 2018 
AND ofec_candidate_history_mv.office = 'S' 
AND ofec_candidate_history_mv.state = 'CA' 
AND ofec_candidate_history_mv.district = '00' 
AND ofec_candidate_history_mv.candidate_inactive = false) AS anon_4 ORDER BY anon_4.candidate_id, anon_4.cmte_id, anon_4.two_year_period DESC) AS anon_5 GROUP BY anon_5.candidate_id) AS anon_2 ON anon_1.candidate_id = anon_2.candidate_id LEFT OUTER JOIN (SELECT ofec_election_result_mv.cand_id AS cand_id
FROM ofec_election_result_mv
WHERE ofec_election_result_mv.election_yr = 2018 
AND ofec_election_result_mv.cand_office = 'S' 
AND ofec_election_result_mv.cand_office_st = 'CA' 
AND ofec_election_result_mv.cand_office_district = '00'
) AS anon_3 ON anon_1.candidate_id = anon_3.cand_id LEFT OUTER JOIN ofec_committee_detail_mv ON anon_1.candidate_pcc_id = ofec_committee_detail_mv.committee_id

**Comment by fec-jli** [comment]
after removing joint fundraisers from the query, for (VA, 2018, senate), the datatable page likes this, Can you verify the data is correct or not? Thanks @jwchumley  
<img width="622" alt="screen shot 2018-06-27 at 12 12 37 am" src="https://user-images.githubusercontent.com/24395751/41953079-8adaacac-79a1-11e8-9a5f-bf6850cbc477.png">


the wrong one likes this:
<img width="726" alt="screen shot 2018-06-27 at 12 13 07 am" src="https://user-images.githubusercontent.com/24395751/41953108-c2f03a9e-79a1-11e8-90ad-8bbb0436fe75.png">

**Comment by jwchumley** [comment]
The data are correct.

**Comment by PaulClark2** [comment]
Item 1 is complete

Item 2 is now in issue https://github.com/fecgov/openFEC/issues/3260
