### ISSUE TITLE
Research / Create ofec_all_report_mv

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3230]
Problem: There are multiple endpoints that assume a committee will file the correct form type. i.e. a candidate committee will file form 3. When a committee files on the wrong form type these endpoints miss that report.

Solution:
Rather than fix each endpoint we want to create a single view based on the v_sum table that has all form types so it can be used in all the relevant end points.

Things to consider:

Only the columns currently in v_sum handle paper amendments that may be missing values in some or all summary columns (not required by the regs to give us anything that has not changed). So adding more columns from the report tables is risky.

The endpoint used by the candidate and committee profile pages returns different columns depending on committee type. We need to make sure the new view supports all of the committee profile presentations.

For more detail: #3154

- [x] Have a meeting - Jeff, Helen, Paul, Laura, DBAs
- [x] Figure out columns

**Comment by hcaofec** [comment]
we decide to create a new materialized view using current fec_v_sum...vw to include all reports.  At phase one, this mv will include F3, F3P and F3X.  But we are aware of the possibility of need for adding more forms to this mv.

**Comment by hcaofec** [comment]
After consulting with DBA team,  we will create view instead of materialized view if performance is good.  View does not need to be refreshed manually.

**Comment by hcaofec** [comment]
A view was created initially but the time to load the view is getting longer with more columns added to it. So a materialized view with same structure will be created. 

New issue is here: [#3373](https://github.com/fecgov/openFEC/issues/3373)
