### ISSUE TITLE
Research: De-dupe 24 and 48-hour reports of Independent Expenditures

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3233]
Issue: 24 and 48 hour IE notices are reported in the days leading up to an election.  These notices serve the purpose of giving vital spending information to voters that would not normally be reported until after the election. When the next regularly scheduled report is filed those same IEs are reported because they happened during the coverage date range of the report. So we have them twice and it is difficult to dedupe them. 

In one of the presentations on the Classic site hosted by Salient, logic was incorporated to display the notices until that committee filed a report covering that time frame and then drop the notices from the display. This works because regular filers will file their next report and the duplicates go away but it also works for the first time filers who may never file a regular report so their notices do not go away. It isn't perfect but we should look at using it on the new site.

This issue exists on both FEC.gov here:  https://www.fec.gov/data/independent-expenditures/?data_type=processed&is_notice=true

and on classic.fec.gov here: https://classic.fec.gov/data/IndependentExpenditure.do.

Further complication. On discussion with Paul, it turns out that though everything written above is correct, the Press office really cares more about a different but related issue. Forgetting the regularly scheduled reports for a moment, the 24 and 48  hours are a much bigger mess and here is why:

1. 48 or 24 hour notices are filed every day or every other day by many filers during the time leading up to an election. They can be New or they can be amended. Though the efiling rules say an amendment must be a complete replacement for the report being amended the actual practice is all over the map. An amendment can be partial or full and there is no good indicator of which it is. So there are a lot of duplicates but there is no good programatic way to dedupe them. Also the forms themselves don't require coverage dates so that's another complication. The V_sum table tries to include only the most recent version of each notice but since that may be a complete or a partial report that is of little help. We've tried to deal with this several ways over the years and have not come up with a reliable automated approach.

- [ ] get logic from salient (Mahi)
- [ ] figure out if the logic can be applied to a current endpoint or if a new endpoint is needed

**Comment by adamConnerSax** [comment]
I think I am running into this issue when trying to look at independent expenditures over time.  I'm querying the /schedules/schedule_e endpoint by candidate_id and cycle.  I'm seeing lots of what look like duplicates.  At the single entry level, can I safely dedupe by ignoring any entry which has the identical office_total_ytd as the previous for that committee?  That seems like a pretty clear indicator, but maybe I'm missing something?
