### ISSUE TITLE
Fix archived MURs with wrong names, only partial PDFs

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3234]
A handful of archived MURs came in with the wrong MUR no - they shouldn't have the `_A`. We confirmed these on classic.

Because of the wrong numbers, they're not coming up in results because a user searching "1252" (the correct number) won't find "1252_A" (what we've named it).

9 Examples:
1252_A
1503_A
1704_A
253_A
2583_A
2667_A
2804_A
2892_A
3485_A

After discussing this with Jason, I realize the issue is more complex than we previously thought - Currently, the “_A” PDF’s are only part “_A” of the MUR - the canonical page should link to all PDF’s. So in the “2892” example, there are 5 PDF’s we need to associate with that number, and currently we’re only associating one “_A” PDF with that MUR. Just renaming these won’t be enough.

It looks like our system for archived MURs is set up on a `1-1` relationship between MURs and their PDFs, but this is actually a `1-many` relationship for these 9 MURs that have multiple parts. We’ll need to re-think our work to fix this issue.

- [x] Check for duplicates - are there current MURs with these numbers? 
- [x] Make a snapshot of the Archived MUR index in elasticsearch
- ~[ ] Fix the schema to handle `one-many` archived MURs - PDFs~ no schema change needed - shared w/current MURs
- [x] Modify reload to handle nested documents
- [X] Implement front end (PR https://github.com/fecgov/fec-cms/pull/2185)
- [X] test `dev` - merge front end PR
- [X] reload one multi and one multiple archived MUR with a headless app, (2583 and 2584), make sure nothing breaks. 
- [x] Merge PR
[Reload progress here](https://docs.google.com/spreadsheets/d/12h_lI8_Lsau31WbRntdr1sx0DvovRc_Dd2QeaFlBft8/edit#gid=0)
- [x] Dev - Load these 9 MURs with with `load_archived_murs`  and delete old `_A` archived murs*, Make a snapshot after
Release branch is cut
- [x] Stage - Load these 9 MURs with with `load_archived_murs` and delete old `_A` archived murs*, Make a snapshot after
7/31 Release is deployed to prod
- [x] Prod - Load these 9 MURs with with `load_archived_murs` and delete old `_A` archived murs*, Make a snapshot after
- [ ] Update documentation on loading archived MURs

*
```
cf ssh api
--!! DELETE by query

curl -X POST "<URI>/archived_murs/murs/_delete_by_query" -H 'Content-Type: application/json' -d'
{
    "query": {
        "wildcard" : { "no" : "*_A" }
    }
}
'
```

Better not to do this by hand - less error-prone, more exposure

**Comment by vrajmohan** [comment]
The front-end for archived MURs is designed to show a link for a single document.



Discussed with @JonellaCulmer, @lbeaufort and @fec-jli - we will use a table similar to that for current MURs. For most archived MURs, this table will have a single entry. The archived MURs with multiple PDFs will have multiple entries. The entry will comprise a name with a link and a file size. We will either use the existing names (e.g. 1252_A) or use a slightly better name like '1252 Part 1'.

**Comment by rjayasekera** [comment]
Loading archive MURs with a suffix other than `_A` for some reason does not work.  
If finds the *.pdf file from the URL given, but after the regex parser record length becomes `0`
running following with pdb debug break points:
./manage.py load_archived_murs -s 1704_B
(Pdb++) print (len(rows))
4446
elif specific_mur_no is not None:
-> lambda x: re.search('/disclosure_data/mur/([0-9_A-Z]+)\.pdf', x, re.M).group(1) == specific_mur_no, rows))
(Pdb++) l
442  	    if from_mur_no is not None:
443  	        rows = list(itertools.dropwhile(
444  	            lambda x: re.search('/disclosure_data/mur/([0-9_A-Z]+)\.pdf', x, re.M).group(1) != from_mur_no, rows))
445  	    elif specific_mur_no is not None:
446  	        rows = list(filter(
447  ->	            lambda x: re.search('/disclosure_data/mur/([0-9_A-Z]+)\.pdf', x, re.M).group(1) == specific_mur_no, rows))
448  	    murs = zip(range(len(rows)), [len(rows)] * len(rows), rows)
449  	    processes = int(num_processes)
450  	    maxtasksperchild = int(tasks_per_child) if tasks_per_child else None
451  	    with Pool(processes=processes, maxtasksperchild=maxtasksperchild) as pool:
452  	        pool.map(process_mur, murs, chunksize=1)
(Pdb++) s
--Call--
(Pdb++) print (pattern)
/disclosure_data/mur/([0-9_A-Z]+)\.pdf
(Pdb++) print (string)

      <td class="linkColumn"><span style="font-weight:bold; color:#454545">4842</span><br><a href="/disclosure_data/mur/4842.pdf" target="_blank">4842.pdf</a><span style="padding-left:2px; font-size:9px;">[2M]</span></td>
(Pdb++) print (len(rows))
`0`
(Pdb++) c
INFO:manager:0 archived MURs loaded

Will work with @vrajmohan this morning to figure this out.

**Comment by rjayasekera** [comment]
I haven't made much progress on this for the past two days.  According to @vrajmohan what's need to happen is that we need to modify/create a Elastic Search schema to account for multiple PDFs associate with a single archive MUR.  
Currently @vrajmohan and @lbeaufort helping me to understand how Elastic Search works and how archive MURs get parsed.  Reading some ES documentation and similar code in Current MURs. 
But still unable to make any progress.  
Just wanted to flag this here, since I don't want work on this ticket to spill over to the next sprint.
cc @PaulClark2 @AmyKort

**Comment by rjayasekera** [comment]
This structure should be able to handle multiple PDFs for single archive MUR
{
  "_index": "archived_murs_index",
  "_type": "murs",
  "_id": "mur_1252",
  "_version": 29,
  "found": true,
  "_source": {
  
      "documents": [
      {
        "document_id": 1,
        "category": "Complaint, Responses, Designation of Counsel and Extensions of Time",
        "description": "Grant of Extension of Time to National Republican Senatorial Committee",
        "length": 31468,
        "url": "/files/legal/murs/1.pdf",
        "text": "\nFEDERAL ELECTION COMMISSION WASHINGTON. D.C. 20463 
      }
      {
        "document_id": 2,
        "category": "Complaint, Responses, Designation of Counsel and Extensions of Time",
        "description": "Grant of Extension of Time to National Republican Senatorial Committee",
        "length": 31468,
        "pdf_size": 127466280,
        "pdf_pages": 1516,
        "url": "/files/legal/murs/2.pdf",
        "text": "\nFEDERAL ELECTION COMMISSION WASHINGTON. D.C. 20463 
      }
    ],

    "name": "REAGAN FOR PRESIDENT COMMITTEE",
    "mur_type": "archived",
    "open_date": "1980-07-03T00:00:00",
    "close_date": "1983-05-24T00:00:00",
    "complainants": [
      "Carter-Mondale Reelection Committee",
      "Common Cause",
      "Democratic National Committee"
    ],
    "respondents": [
      "Americans For An Effective Presidency",
      "Americans For Change",
      "Fund For A Conservative Majority",
      "National Congressional Club",
      "National Conservative Political Action Committee",
      "Reagan For President Committee",
      "Reagan, Ronald",
      "Reagan/Bush Committee",
      "Republican National Committee"
    ],
    "subject": [
      {
        "text": "Contributions",
        "children": [
          {
            "text": "Acceptance"
          },
            ]
          },
      }
    ],
    "citations": {
      "us_code": [
        {
          "text": "52 U.S.C. 30101(17)",
          "url": "http://api.fdsys.gov/link?collection=uscode&link-type=html&title=52&year=mostrecent&section=30101"
        },

      ],
      "regulations": [
        {
          "text": "11 C.F.R. 109.1",
          "url": "/regulations/109-1/CURRENT"
        }
      ]
    },
    "url": "/files/legal/murs/1252_E.pdf"
  }
}

**Comment by rjayasekera** [comment]
Following is the proposed ES structure for loading Archive MURs
```
{
  "_index": "archived_murs_index",
  "_type": "murs",
  "_id": "mur_1252",
  "_version": 29,
  "found": true,
  "_source": {
  
    "no": "1252",
    "url": "/legal/matter-under-review/1252/",
    "name": "REAGAN FOR PRESIDENT COMMITTEE",
    "mur_type": "archived",
    "open_date": "1980-07-03T00:00:00",
    "close_date": "1983-05-24T00:00:00",
    "complainants": [
    "List of complainants"
    ],
    "respondents": [
      "List of respondents"
    ],
    "citations": {
      "us_code": [
        {
          "text": "52 U.S.C. 30101(17)",
          "url": "http://api.fdsys.gov/link?collection=uscode&linktype=html&title=52&year=mostrecent&section=30101"
        },

      ],
      "regulations": [
        {
          "text": "11 C.F.R. 109.1",
          "url": "/regulations/109-1/CURRENT"
        }
      ]
    },
    "documents": [
      {
        "document_id": 1,
        "length": 10M,
        "url": "/files/legal/murs/1252/1252_A.pdf",
        "text": "\nFEDERAL ELECTION COMMISSION WASHINGTON. D.C. 20463 
      }
      {
        "document_id": 2,
        "length": 20M,
        "url": "/files/legal/murs/1252/1252_B.pdf",
        "text": "\nFEDERAL ELECTION COMMISSION WASHINGTON. D.C. 20463 
      }
    ],
  }
}```

**Comment by rjayasekera** [comment]
Work needs to be done

Modify load_legal_docs.py program to reload the archived MURs with multiple PDF files 
(9 of them identified) according to the modified ES schema (which is similar to current MURs schema)

The above will create inconstancies the way that we store archive MURs in ES index. 

Previously load of archived MURs has only one PDF file associated with a MUR number

	doc_id	"mur_1252"
	no	"1252"
	name	"REAGAN FOR PRESIDENT COMMITTEE"
	text	"FEDERAL ELECTION COMMISS…n\n'U,.\n\n'S\n\n\u000c"
	mur_type	"archived"
	pdf_size	127466280
	pdf_pages	1516
	open_date	"1980-07-03T00:00:00"
	close_date	"1983-05-24T00:00:00"
	complainants	[…]
	respondents	[…]
	subject	[…]
	citations	{…}
	url	"/files/legal/murs/1252.pdf"
	
Newer load of archived MURs with multiple PDF files associated with a MUR number

	doc_id	"mur_1252"
	no	"1252"
	name	"REAGAN FOR PRESIDENT COMMITTEE"
	text	"FEDERAL ELECTION COMMISS…n\n'U,.\n\n'S\n\n\u000c"
	mur_type	"archived"
	open_date	"1980-07-03T00:00:00"
	close_date	"1983-05-24T00:00:00"
	complainants	[…]
	respondents	[…]
	subject	[…]
	citations	{…}
	url	"/legal/matter-under-review/1252/"
	"documents": [
      {
        "document_id": 1,
        "length": 10M,
        "url": "/files/legal/murs/1252/1252_A.pdf",
        "text": "\nFEDERAL ELECTION COMMISSION WASHINGTON. D.C. 20463 
      }
      {
        "document_id": 2,
        "length": 20M,
        "url": "/files/legal/murs/1252/1252_B.pdf",
        "text": "\nFEDERAL ELECTION COMMISSION WASHINGTON. D.C. 20463 
      }
	
- Therefor after the load of 9 identified archived MURs with multiple PDFs we will write a
utility program to move the previously loaded archived MURs from old structure to new structure.

-  This will create a "document" list of one entry with it characteristics when there is one PDF file and its document_id will be 1.

- When there are multiple PDF files associated with the MUR there will be a "document" list of multiple 
entries with it characteristics and document_id will be a sequence number (document_id: 1, document_id:2, etc) 

- Until we move all the archived MURs to the new structure we need to modify the front end to
identify whether "documents" list element exists in the json or not and display the MUR accordingly.

cc: @lbeaufort @vrajmohan

**Comment by lbeaufort** [comment]
```
cf run-task api "python manage.py load_archived_murs -s 1252" -m 4G --name reload_1252
cf run-task api "python manage.py load_archived_murs -s 1503" -m 4G --name reload_1503
cf run-task api "python manage.py load_archived_murs -s 1704 -m 4G --name reload_1704
cf run-task api "python manage.py load_archived_murs -s 253 -m 4G --name reload_253
cf run-task api "python manage.py load_archived_murs -s 2583 -m 4G --name reload_2583
cf run-task api "python manage.py load_archived_murs -s 2667 -m 4G --name reload_2667
cf run-task api "python manage.py load_archived_murs -s 2804 -m 4G --name reload_2804
cf run-task api "python manage.py load_archived_murs -s 2892 -m 4G --name reload_2892
cf run-task api "python manage.py load_archived_murs -s 3485 -m 4G --name reload_3485
```

**Comment by JonellaCulmer** [comment]
PR is merged, so closing this issue.

**Comment by lbeaufort** [comment]
@JonellaCulmer this isn't complete yet - the checklist has the remaining items
