### ISSUE TITLE
Remove S3 caching

### ISSUE THREAD

**Issue by vrajmohan** [fecgov/openFEC#3235]
The current implementation of S3 allows the use of the application only if the following conditions are met:
App server is up but for some reason, DB/Elasticsearch connections are down
The request is being repeated with the same params since the cache was cleared at 2am UTC.

_Note:_ 

1. _This cache has failed us when we failed to do the Elasticsearch upgrade in prod._
2. _The S3 caching of responses was the reason that NewRelic was not alerting on dev when we removed an underlying table_

In addition, the logging done by this code is incorrect and does not indicate when the cache is actually being used.

**Completion criteria:** 
- [ ] Flip the feature flag to disable S3 caching
- [ ] Deploy as hotfix to lessen logging records
- [ ] Delete caching code

**Comment by pkfec** [comment]
I would like to work on disabling the cache requests and remove the celery task that uploads the cached requests to S3 bucket in this sprint.

I need an extra day to test the changes throughly, but i can wrap up the work before this sprint ends.
