### ISSUE TITLE
Set up CloudFront for the stage space as well

### ISSUE THREAD

**Issue by vrajmohan** [fecgov/openFEC#3236]
CloudFront CDN is only implemented in `prod` and not in `stage`. This is a cloud.gov service. Check cloudl.gov documentation. Service is included with cloud.gov. Instructions for implementation are included in the documentation.

- [x] read the cloud.gov docs on cloudfront (https://cloud.gov/docs/services/cdn-route/)
- [ ] implement in `stage` as it is implemented in `prod`

**Comment by rjayasekera** [comment]
Start to look in to this, and reading the documentation  (https://cloud.gov/docs/services/cdn-route/)

**Comment by rjayasekera** [comment]
I contacted cloud.gov support regarding whether we need to create a broker/agent in staging before enabling CloudFront cache in Stage space.
Below is the answer I got from cloud.gov support:

> Hi Rohan,
> The cloud.gov team runs the broker, so you don't need to follow those instructions. You can follow the instructions in https://cloud.gov/docs/services/cdn-route/ instead.
> Josh

**Comment by rjayasekera** [comment]
Currently we are accessing application running in Stage space is thru the following URL:
https://fec-stage-proxy.app.cloud.gov/

According to instructions in https://fec-stage-proxy.app.cloud.gov/ document
1. Create a private domain in your organization (replace <org> with your org name, and replace my.example.gov with your domain):

> Creating domain fec-stage-proxy.app.cloud.gov for org fec-beta-fec as rjayasekera@fec.gov...
> FAILED
> Server error, status code: 400, error code: 130001, message: The domain is invalid: name route_conflict
> 

2. Since the above command failed. Create a new domain

> cf create-domain fec-beta-fec fec-stage-proxy2.app.cloud.gov
> Creating domain fec-stage-proxy2.app.cloud.gov for org fec-beta-fec as rjayasekera@fec.gov...
> OK

3. Then, to create a cdn-route service instance, run the following command 

> cf create-service cdn-route cdn-route fec-stg-cdn-route -c '{"domain": "fec-stage-proxy2.app.cloud.gov"}'
> Creating service instance fec-stg-cdn-route in org fec-beta-fec / space stage as rjayasekera@fec.gov...
> OK
> 
> Create in progress. Use 'cf services' or 'cf service fec-stg-cdn-route' to check operation status.
> 

4. According to the document the above process should take about an hour.  But even after 24 hrs the status show as "creating in progress"

> cf service fec-cdn-route
> Showing info of service fec-cdn-route in org fec-beta-fec / space stage as rjayasekera@fec.gov...
> 
> name:            fec-cdn-route
> service:         cdn-route
> bound apps:      
> tags:            
> plan:            cdn-route
> description:     Custom domains, CDN caching, and TLS certificates with automatic renewal
> documentation:   
> dashboard:       
> 
> Showing status of last operation from service fec-cdn-route...
> 
> status:    create in progress
> message:   Provisioning in progress [fec-stage-proxy2.app.cloud.gov => cdn-broker-origin.fr.cloud.gov]; CNAME or ALIAS domain fec-stage-proxy2.app.cloud.gov
>            to d3xxxxxxxxxxxxx7.cloudfront.net or create TXT record(s): 
> name: _acme-challenge.fec-stage-proxy2.app.cloud.gov., value:
>            sw8lxxxxxxxxxxxxxxxxxxxxxxeA, ttl: 120
> started:   2018-07-26T16:51:52Z
> updated:   2018-07-27T15:30:17Z

**Comment by rjayasekera** [comment]
Contacted cloud.gov via email regarding the above issue  and waiting to hear back.

In the mean time added our the new domain as a second route to our proxy app in staging.  Modified the   fec-proxy/manifest_stage.yml file

> routes:
>   -route: fec-stage-proxy.app.cloud.gov
>   -route: fec-stage-proxy2.app.cloud.gov

**Comment by rjayasekera** [comment]
After two days has passed my new cdn-route creation is still in `create in progress` status.  After looking at Kibana logs I see the following error message:

> 404 GET /.well-known/acme-challenge/xxxxxxxxxxx-yyyyyyyyyyyyyy (93.834 ms)
> xx.xx.xx.xx, 127.0.0.1 - - - [30/Jul/2018:09:43:19 +0000] "GET /.well-known/acme-challenge/xxxxxxxxxx-yyyyyyyyyyyyy HTTP/1.1" 404 6042
> 
> Not Found: /.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxx-yyyyyyyyyyyyyyyyy

The above error has something to do with `Let's Encrypt` and according to the documentation cdn-route create broker should create this.  I think this is the reason my cdn-route creation is still in progress.

> Create the TXT record(s) as instructed by the broker. The existence of these records will be validated by Let’s Encrypt when issuing your certificate and will not affect your site.
> 
> After the records have been created wait up to 1 hour for the certificate to be provisioned. Your certificate has been provisioned when the cf service my-cdn-route command reports the status as create succeeded.

After 3 days still no answer from cloud.gov support. Updated cloud.gov support with above findings.

**Comment by rjayasekera** [comment]
cloud.gov replied this morning. cc @vrajmohan @patphongs 

> The CDN service is used to provision HTTPS certificates for custom domains and to associate those domains with cloud.gov applications. The custom domain should be a domain controlled by the user, since you'll need to set up DNS for your domain in order to finish provisioning the service instance: https://cloud.gov/docs/services/cdn-route/#how-to-set-up-dns. It looks like your service instance is using a domain that's managed by cloud.gov rather than FEC: fec-stage-proxy2.app.cloud.gov. This isn't a custom domain, since it's managed by cloud.gov, and because you presumably don't have access to the app.cloud.gov DNS configuration, you won't be able to follow the DNS configuration instructions to complete provisioning.
> 
> If you want to set up a CDN service instance for our application, you can create a new instance using a domain that you control, presumably part of *.fec.gov. Then, check the DNS instructions on your new instance and create DNS records as described there.

**Comment by rjayasekera** [comment]
Unable to delete the cdn-route service created earlier, since it is still being created

> cf delete-service fec-stg-cdn-route
> 
> Really delete the service fec-stg-cdn-route?> yes
> Deleting service fec-stg-cdn-route in org fec-beta-fec / space stage as rjayasekera@fec.gov...
> FAILED
> Server error, status code: 409, error code: 60016, message: An operation for service instance fec-stg-cdn-route is in progress.
> 

Contacted cloud.gov support and they temporarily change the stated from `create in progress` to `created` in order for me to delete the servie

> Instances of the CDN service remain in a pending state until the service broker finds the DNS records that it instructs the user to create. That's why the instance has been in that state for a while. I just manually changed the status of the instance--you should be able to delete it now.

> cf delete-service fec-stg-cdn-route
> 
> Really delete the service fec-stg-cdn-route?> yes
> Deleting service fec-stg-cdn-route in org fec-beta-fec / space stage as rjayasekera@fec.gov...
> OK
> 
> Delete in progress. Use 'cf services' or 'cf service fec-stg-cdn-route' to check operation status.

Service got deleted successfully.

**Comment by rjayasekera** [comment]
Closing this issues in favor of issue [3320](https://github.com/fecgov/openFEC/issues/3320)
