### ISSUE TITLE
Set caching headers in the API

### ISSUE THREAD

**Issue by vrajmohan** [fecgov/openFEC#3237]
Do a single endpoint this sprint as a test.

We removed the caching headers set by the API entirely when trying to ensure that refreshed legal documents show up promptly. Consequently, we are not leveraging any caching by api.data.gov, and API users do not benefit from any caching. As discussed in https://docs.google.com/document/d/1vUDTrnWKpbUDmUv90pEIINV79MSlkg03qoBoXpzl9Wc/edit?usp=sharing, we should reinstate caching - the cache duration may be different for legal (no cache?), efiling (10m?) and the rest (1h?). 

In addition, we should also fix https://github.com/fecgov/openFEC/blob/develop/webservices/rest.py#L157 as it gives the false impression that we are caching.

- [x] Reinstate caching - the cache duration may be different for legal (no cache?), efiling (10m?) and the rest (1h?). 
- [x] Remove `if app.config['MAX_CACHE_AGE'] is not None:`[here](https://github.com/fecgov/openFEC/blob/develop/webservices/rest.py#L157)

**Cache duration**
efiling: none
legal: 5 minutes
calendar: 5 minutes per @AmyKort 
other: 1 hour

**Comment by PaulClark2** [comment]
No changes to the API umbrella. 

Set headers correctly

**Comment by lbeaufort** [comment]
Caching is a double-edged sword - it reduces server load and response time, but serves up content that hasn’t been refreshed since the cache duration. Most endpoints aren’t updated except once a day anyway, but there’s an expectation that some data (like published AO’s and efilings) to be available immediately.

Any ideas on where to start with these values? 
1) Is there a list of endpoints that are refreshed/updated more often than once a day? 
2) I’m proposing 1 hour cache on all endpoints except legal (no cache?) and efiling (10 minutes).

cc: @PaulClark2 @AmyKort @vrajmohan

**Comment by PaulClark2** [comment]
Things to consider: 

1. Can the calendar related endpoints be updated more than once a day? If yes, we probably want no cache. 
2. For years we've told data users that efiling data will be available nearly immediately after we receive it. We may want the cache to be 5 minutes or less or no cache.

**Comment by lbeaufort** [comment]
@PaulClark2 yes, calendar entries pull straight from the database. Would 1 hour be too long of a cache for calendar dates? We would probably want at least some cache because I think that endpoint gets hit pretty hard.

**Comment by PaulClark2** [comment]
One hour for the calendar seems reasonable to me. @AmyKort do you have any concerns about a one-hour cache on the calendar?

**Comment by lbeaufort** [comment]
@PaulClark2 @AmyKort after giving it some thought, we might want to have a small (5 minute?) cache on the legal side to improve performance. 

**Cache duration**
legal: 5 minutes
efiling: none
other: 1 hour
calendar: ? TBD - Amy is researching this

Thoughts?

**Comment by PaulClark2** [comment]
@lbeaufort those caching times make sense to me. Thanks!
