### ISSUE TITLE
Refine "Print full query" function

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3238]
To make it easier to access the query used by the API, the print full query function needs to be refined to make it a simple statement that even Jeff and Paul can run.

- [ ] Update `print_literal_query_string` in webservices/utils.py to print the query with parameters:
```
from sqlalchemy.dialects import postgresql

print(str(query.statement.compile(
    dialect=postgresql.dialect(),
    compile_kwargs={"literal_binds": True})))
```
- [ ] consider renaming it to something easier for the PM's to use, like `print_full_query`
- [ ] test this on an endpoint
- [ ] train Paul and Jeff on using it

**Comment by lbeaufort** [comment]
This is more complex than I realized for 2 reasons:
1) Not all endpoints have a `query = ` assignment - this shouldn't be too bad to work with but it increases the difficulty
2) It looks like this won't work as-is for dates: Testing with http://localhost:5000/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=true&data_type=processed&two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=07%2F20%2F2018&contributor_zip=2016&sort=-contribution_receipt_date&per_page=30 results in the error:
```
INFO in rest [/Users/lbeaufort/dev/API/openFEC/webservices/rest.py:246]:
An API error occurred with the status code of 500 (Don't know how to literal-quote value datetime.date(2017, 1, 1)).
```

**Comment by lbeaufort** [comment]
Closing due to complications and resource constraints
