### ISSUE TITLE
Candidate PCC not displaying on election profile page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#3244]
**What we're after:** This may be a symptom of the work that needs to take place with the /elections endpoint, but a 2016 Presidential candidate is currently showing there is no connected PCC. In the API the candidate_pcc_id and _name are showing up as `null`. Unfortunately, the candidate's presidential committee is still active. 

**Example:**
Marco Rubio
https://www.fec.gov/data/elections/president/2016/?tab=about-election

**Comment by PaulClark2** [comment]
This looks like a data problem. C00458844 is Rubio's presidential PCC but currently has a committee designation of other authorized. I'll update the committee's designation.

**Comment by PaulClark2** [comment]
This was a linkage problem. I updated the link between Rubio's presidential ID and his presidential PCC. This should be resolved now. https://www.fec.gov/data/elections/president/2016/?tab=about-election
