### ISSUE TITLE
Show non-US states in Schedule A by state aggregates

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3246]
/schedules/schedule_a/by_state/ - aggregations by state should also display total contributions received from non-us states. Have a list of acceptable non-US state values, then have a non-clickable "other" aggregate.

Example: https://api.open.fec.gov/v1/schedules/schedule_a/by_state/by_candidate/?api_key=DEMO_KEY&cycle=2018&candidate_id=H4AL01123&per_page=99

Front-end page:
https://www.fec.gov/data/committee/C00053553/?tab=raising
<img width="542" alt="screen shot 2018-06-18 at 12 21 07 pm" src="https://user-images.githubusercontent.com/11650355/41548877-27c51630-72f2-11e8-8e02-fc3a0304ad22.png">

<img width="1320" alt="screen shot 2018-07-19 at 2 11 24 pm" src="https://user-images.githubusercontent.com/31663028/42961730-aca1c208-8b5d-11e8-86d3-880b69089516.png">

Add the ability to click through:
https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=true&committee_id=C00053553&two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=06%2F28%2F2018&contributor_state=TX&sort=-contribution_receipt_date&per_page=30&is_individual=true

- [x] Work with content team to confirm appropriate language (@llienfec)
- [x] Show non-US states in Schedule A by state aggregates (/schedules/schedule_a/by_state/ endpoint) - aggregations by state should also display total contributions received from non-us states. Where it's not a US state or territory, display Unknown, Non-US State or Other or something better. 
- [ ] Add the ability to filter /schedules/schedule_a/ transaction data by non-US states. We'll need to click through to a transaction search for transactions from non-US states. We could either build a parameter (non-us state = true) or manually exclude every state/territory value. This is a change to the SA endpoint.
- [x] Test the front end pages with these changes

**Comment by PaulClark2** [comment]
@lbeaufort "ZZ" is our code for foreign countries. If the committee uses that in the state field, we display it. What we are missing are "state" codes that are not in the state reference table (staging.ref_st). For example, if the person's address is Montreal, Quebec and the committee puts "QC" in the state field. We need to aggregate these transactions too.

**Comment by PaulClark2** [comment]
Where it's not a US state or territory, display `Unknown`, `Non-US State` or `Other` or something better.

**Comment by llienfec** [comment]
Content team votes using "Other" as the label for non-US state data.  Thanks!

**Comment by fec-jli** [comment]
question: [https://www.fec.gov/data/committee/C00370007/?tab=raising](https://www.fec.gov/data/committee/C00370007/?tab=raising)

Do we need aggregate those `Other` to one row? some of them are negative values.
<img width="874" alt="screen shot 2018-07-26 at 10 54 58 pm" src="https://user-images.githubusercontent.com/24395751/43299258-88d1d0fa-9127-11e8-9682-566c9babcae6.png">

**Comment by lbeaufort** [comment]
@fec-jli yes, they should be all aggregated together, like the US states do as well.

**Comment by lbeaufort** [comment]
The last item has been moved to a new issue - https://github.com/fecgov/openFEC/issues/3326

PR is merged: https://github.com/fecgov/openFEC/pull/3321
