### ISSUE TITLE
Refactor elections (ElectionView) endpoint to extend ApiResource

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#3254]
this issue related with Issue https://github.com/fecgov/fec-cms/issues/2010
to enable the export link in election summery page.

**Comment by PaulClark2** [comment]
Is this a refactor or are we adding export functionality?

**Comment by fec-jli** [comment]
in order to make export work, we need refactor this endpoint first.

**Comment by fec-jli** [comment]
yes, #3253 only takes care of the download for candidate financial totals.
the reason I am working on this, because the code to fix this https://github.com/fecgov/openFEC/issues/3221 are mixed in same python file.
we better to do together.  for other tow export individual contributions links, we can leave this for the future.

**Comment by PaulClark2** [comment]
related to https://github.com/fecgov/fec-cms/issues/2153

**Comment by JonellaCulmer** [comment]
Work has been merged, so closing this issue.
