### ISSUE TITLE
Load missing archived MUR 3620

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3256]
On the new site, we have 4,445 archived MURs, but on classic we have 4,446 archived MURs.  We should identify the discrepancy and load the missing MUR if necessary.

fec.gov: 4445
https://docs.google.com/spreadsheets/d/1Ksb3mjwsTKcdAwkRkP8n3e6KrNmoZor_WP1ipDQmibo/edit#gid=0

classic.fec.gov: 4446
https://classic.fec.gov/MUR/

**Comment by vrajmohan** [comment]
The missing archived MUR is https://classic.fec.gov/disclosure_data/mur/3620.pdf. I suggest that we try and load it in with #3234.

**Comment by vrajmohan** [comment]
Tagging @rjayasekera

**Comment by lbeaufort** [comment]
@vrajmohan oddly, 3620 it looks like a current MUR: https://www.fec.gov/data/legal/matter-under-review/3620/

**Comment by lbeaufort** [comment]
I confirmed that 3620 is a duplicate - it appears on both the archived and current MUR searches on classic. We're going to stick with the current version, as it has better data.
