### ISSUE TITLE
Exclude inactive and unverified candidates from /elections/

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3260]
Committees that have terminated or are unverified candidates we need to take the last final step to ensure that only those verified candidates are shown. 

There are two tables that we use to make sure candidates are not on the list:
disclosure.cand_inactive (for candidates that withdraw from an election) which is already included in one of the underlying views and:
disclosure.unverified_cand_cmte (for candidates or committees that have been removed for administrative reasons) which is not accounted for

- [ ] Add unverified candidate statement to the where clause of the anon_4 sub select:
AND ofec_cand_cmte_linkage_mv.cand_id not in (select cand_cmte_id from disclosure.unverified_cand_cmte)
- [ ] Find an example of where this is occurring, or if there are locations that already do the thing

Related to https://github.com/fecgov/openFEC/issues/3221

@AmyKort Will explore/groom this further.

**Comment by fec-jli** [comment]
@ChingKuan @hcaofec 
we need remove unverified_cand_cmte from `ofec_candidate_history_mv`.
Can we create a view base on `ofec_candidate_history_mv` to remove unverified_cand_cmte?
not sure this is right way? Thanks

**Comment by hcaofec** [comment]
How hard will it be if modifying ofec_candidate_history_mv by adding this exclusion condition, because of the dependency among all the materialized views?  
Even though we create a view as @fec-jli suggested, we still need to replace wherever **ofec_candidate_history_mv** being used now with the new view. That requires lots changes on materialized views too which is complicated too because of dependency.

@fec-jli @ChingKuan @fecjjeng

**Comment by jwchumley** [comment]
You have to be careful with unverified candidates and committees. Yes, we want to exclude them from any appearance on the website EXCEPT we need to display them in an Unverified Candidates and Committees presentation so the data must be available for that.


You could either make sure there is an unverified flag in the ofec candidate history mv so the API can return unverifieds or not or you could remove them from the MV and make another MV just for unverifieds.


Jeff Chumley

Electronic Filing, Web and Disclosure Branch Manager

Federal Election Commission



________________________________

**Comment by PaulClark2** [comment]
closing in favor of https://github.com/fecgov/openFEC/issues/3564
