### ISSUE TITLE
Fix incumbent flags 

### ISSUE THREAD

**Issue by llienfec** [fecgov/openFEC#3262]
We need to fix a few incumbent flags coming from the /elections/ endpoint.  We have the House candidates that need fixed.  We still need to quality check the Senate data.

State | District | Incumbent should be
-- | -- | --
GA | 06 | Karen Handel
PA | 18 | Conor Lamb
TX | 27 | Micheal Cloud
UT | 03 | John Curtis

### Prior issues
Original research - https://github.com/fecgov/fec-cms/issues/2015
Senate research will be at #3261 once 2020/2022 data is added to the endpoint #3243

**Comment by PaulClark2** [comment]
I've updated the ICI of the members listed above.  We should confirm the change tomorrow.

SUB_ID	|	CAND_ID	|	ELECTION_YR	|	NEW_ICI	|	CANDIDATE
----	|	----	|	----	|	----	|	----
1070320180036861270	|	H8GA06286	|	2018	|	I	|	Karen Handel
1070320180036861272	|	H8UT03238	|	2018	|	I	|	John Curtis
1070320180036861271	|	H8PA18181	|	2018	|	I	|	Conor Lamb
1070320180036861273	|	H8TX27049	|	2018	|	I	|	Micheal Cloud

**Comment by AmyKort** [comment]
These are displaying correctly. Is our next step to quality check Senate data?

cc @patphongs
