### ISSUE TITLE
Statutory citation filter broken

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3271]
When performing a filter for statutory citations, the API returns a 500 error.  Citation filters were just added back into the AO search here: https://fec-dev-proxy.app.cloud.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=F

Here's an example of the API error when attempting to filter by statutory citation: https://fec-dev-api.app.cloud.gov/v1/legal/search/?type=advisory_opinions&ao_category=F&ao_statutory_citation=52+U.S.C.+%C2%A730101

**Comment by vrajmohan** [comment]
This is an easy fix. @AmyKort, should we expedite the fix so that it makes the release slated for Sep 11?

**Comment by vrajmohan** [comment]
Done. Thanks, @lbeaufort, for retargeting my PR.
