### ISSUE TITLE
Add `spender_committee_type` filter to schedules/schedule_b/ endpoint

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3274]
**WHAT WE'RE AFTER:** We want to see the type of the committee making the expenditure so that we can enable filters: https://github.com/fecgov/fec-cms/issues/2128

- [x] Add the filter to `args.py`
- [x] Refactor the endpoint to include the committee_type
- [x] Add indexes as needed

**Comment by patphongs** [comment]
This ticket is now dependent on #3357. Adding this column will make this a lot simpler and remove hardcoded data.
