### ISSUE TITLE
Test multiple AO citations parsing

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3277]
Testing ticket for https://github.com/fecgov/openFEC/issues/2276
PR is https://github.com/fecgov/openFEC/pull/3269

I only changed the logic for statutes (USC) and regulations (CFR)

~Wait until it's merged - listed as a blocker.~ >> ok - merged

~Noting here that `dev` and `stage` are out of date with AO data - we could point to the `prod` db and load the docs into elasticsearch.~ >> Rohan updated these, yay! `dev` has multiples logic and `stage` has the old logic

**Comment by lbeaufort** [comment]
@AmyKort this issue is ready for testing in dev. Here's an example of a regulation that was caught by the new logic: 

Before: only 11 CFR §100.73 
https://fec-dev-proxy.app.cloud.gov/data/legal/advisory-opinions/2016-01/

After: 11 CFR §100.73
and 
11 CFR §100.132
https://fec-dev-proxy.app.cloud.gov/data/legal/advisory-opinions/2016-01/

Examples we found of multiples: https://docs.google.com/spreadsheets/d/1-nf-oAPtw3LisZInuDHcQ7JdpyEQXRISZ4kY1ONrFcE/edit#gid=0

**Comment by AmyKort** [comment]
@lbeaufort  We're testing the AO citations in a couple of phases, but I thought I'd share our results as we get them. The first sheet (evens) is the work we've completed so far sampling AOs for even numbered years. The second sheet (selected AOs) shows testing results for AOs listed on your multiple citations list. Only AOs with missing data are listed here. The third sheet should be coming next week and will show sampling of AOs from odd numbered years.

https://docs.google.com/spreadsheets/d/161cnTtYzXzXW2iNxZPIX9rYhko2ZV2deHYFNDP-R49o/edit#gid=162198133

**Comment by AmyKort** [comment]
It looks like we've got enough testing data, so closing.
