### ISSUE TITLE
Test new operations_log endpoint

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#3282]
Testing issue for new operations-log endpoint. There have been additions and changes since the PR was reviewed.

Originating issue: https://github.com/fecgov/fec-cms/issues/2008
PR: https://github.com/fecgov/openFEC/issues/3203

This endpoint will fetch the reports of candidate or committee with status  in verified or completed status .

**Comment by jwchumley** [comment]
I've tested the endpoint. Data returns as expected.

**Comment by JonellaCulmer** [comment]
Testing is complete and no additional work is needed, so closing this testing issue.
