### ISSUE TITLE
Reports missing on Committee > Filings page in IE

### ISSUE THREAD

**Issue by llienfec** [fecgov/openFEC#3286]
In Internet Explorer, reports aren't showing up under the committee's filings page.  Was working this morning.

Example: C000155522 - this committee definitely has reports and the reports are showing up under the All Filings search.  Doesn't show up here: https://www.fec.gov/data/committee/C00015552/?tab=filings

![image](https://user-images.githubusercontent.com/22914750/42837929-7914f702-89cd-11e8-8841-08df05c6804c.png)

**Comment by jwchumley** [comment]
@lbeaufort RAD analysts say it was working this morning then stopped working. Could be related to the release?

**Comment by jwchumley** [comment]
Nevermind @lbeaufort. Pat's on it. I should have tagged her not you.
