### ISSUE TITLE
Procurement for website project

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3288]
- [ ] ~~New Relic~~
   - [ ] ~~APM and Synthetics~~
    - [ ] ~~12 applications running~~
- [x] Invision
- [ ] Slack (Move to procurement vehicle.  It’s costing too much to do on a credit card nowadays)
- [ ] Google organizational account
- [x] GitHub private repository
- [x] Mural (muraly)

**Comment by patphongs** [comment]
@PaulClark2 I know this is a never ending ticket for you, going to move forward to 7.2 in blocked until you hear back from procurement

**Comment by dorothyyeager** [comment]
Moving forward to 7.3 since procurement office is unlikely to move forward this sprint.

**Comment by lbeaufort** [comment]
@PaulClark2 is this ticket useful to you for tracking purposes, or should we close it?

**Comment by patphongs** [comment]
We'll remove the milestone from this issue. @PaulClark2 is working to procure these items and it is a long process. We'll keep this ticket open for tracking purposes.
