### ISSUE TITLE
Form 6 missing from Committee page 24/48 hr report section

### ISSUE THREAD

**Issue by llienfec** [fecgov/openFEC#3289]
Form 6s are missing from the Committee pages in the 24 and 48 hour reports section.  

https://www.fec.gov/data/committee/C00606939/?tab=filings#notices

For testing: examples of committees that have Form 6s filed this cycle
PA) Lou Barletta for Senate – C00445122
(TX) Dan Crenshaw for Congress – C00660795
(SC) William Timmons for Congress – C00668491

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/fec-cms #2194](https://github.com/fecgov/fec-cms/issues/2194) via [**ZenHub**](https://www.zenhub.com/)
