### ISSUE TITLE
By Aug 1: Update the DNS entry for api.open.fec.gov

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3293]
Update: PR in, thanks to @GUI! Pending 18F review. https://github.com/18F/dns/pull/273

- [x] Jeff is asking Gashaw for feedback
- [x] Have a meeting to understand how to handle 
- [ ] Understand the implications of changing the CNAME value in the DNS entry for api.open.fec.gov
- [ ] Update the DNS entry for api.open.fec.gov to a new CNAME value of api-open-fec-gov.domains.api.data.gov before August 1

from cloud.gov:

>We're performing some infrastructure updates with the api.data.gov service and we need your help updating the DNS for api.open.fec.gov. Can you update the DNS entry for api.open.fec.gov to a new CNAME value of: api-open-fec-gov.domains.api.data.gov.
 
>(This differs from the current CNAME value of api-open-fec-2086140464.us-east-1.elb.amazonaws.com.)
 
>There will be no changes in how you use the api.data.gov service with this DNS update, and it will not result in any downtime. This DNS update will just allow us to complete some upgrades to the underlying api.data.gov infrastructure on our end.
 
>If this DNS change could be made before August 1, that would be greatly appreciated.

**Comment by lbeaufort** [comment]
You can see the `CNAME` by running `host -a api.open.fec.gov`

**Comment by patphongs** [comment]
@LindsayYoung @jmcarp Hello, we received this email notification from Nick who helps to run the API umbrella. It sounds like they need us to change our API CNAME from api-open-fec-2086140464.us-east-1.elb.amazonaws.com to api-open-fec-gov.domains.api.data.gov. Here's our questions:

1) What are the implications of what will happen if we modify our CNAME to what the API umbrella needs?

2) How do we do this? We know that transition.fec.gov and www.fec.gov was done through 18F's DNS terraform given the below PRs, however, api.open.fec.gov seems to be set up differently and references `us-east-1` ELB.

- Transition.fec.gov DNS modification PR: https://github.com/18F/dns/pull/82
- www.fec.gov DNS modification PR: 
https://github.com/18F/dns/pull/108
https://github.com/18F/dns/pull/114

**Comment by GUI** [comment]
@patphongs: Ah, I hadn't realized this DNS was managed by 18F, but in that case, I think I've found things and submitted a pull request which should hopefully take care of this DNS change: https://github.com/18F/dns/pull/273 (I haven't gone through this process with the 18F/dns repo before, so someone else might chime in if we need to something different, but hopefully this will get the ball rolling in the right direction). Thanks for tackling all this!

**Comment by LindsayYoung** [comment]
The PR looks good. 

Sorry I didn't see this before, in the future feel free to email me or ping me on slack @patphongs if you have questions.

**Comment by patphongs** [comment]
PR has been merged so we should be good to go: https://github.com/18F/dns/pull/273. Closing this issue
