### ISSUE TITLE
Individual contributor table loading slowly

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#3294]
@fec-issues-bot commented on [Thu Jul 19 2018](https://github.com/fecgov/FEC/issues/7285)

## What were you trying to do and how can we improve it?
 It is taking forever to download a single file. Also, if I want to download all individual contributor data from a single state, then I should not be forced to manually type in every single zip code for that state.  

## General feedback?
 This website is garbage.  

## Details
* URL: https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2016&min_date=01%2F01%2F2015&max_date=12%2F31%2F2016&contributor_state=NY&contributor_zip=11358 
* User Agent: Amazon CloudFront

**Comment by AmyKort** [comment]
This started working again around 3:30 today. Maybe just a hiccup? Let's keep an eye on this for a while before we decide to take any action.

**Comment by AmyKort** [comment]
This appears to have been a short term problem, so closing.
