### ISSUE TITLE
Research: Coverage end date logic for /elections/ endpoint 

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3295]
**What we're after:**
On the election profile page, coverage_end_date is displayed within the `Source reports` column. We need to verify that the coverage end date is accurate, or if we should change the logic to match candidate/committe totals like we did [here with #3217)(https://github.com/fecgov/openFEC/issues/3217). If not, we need to fix it to be accurate.

Example:
Alabama District 1 2018 profile page: https://www.fec.gov/data/elections/house/AL/01/2018/

![screen shot 2018-07-19 at 2 47 52 pm](https://user-images.githubusercontent.com/12799132/42963641-cd3b2e14-8b62-11e8-9c91-20c677ccad2d.png)

**API Call:**

https://api.open.fec.gov/v1/elections/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&cycle=2012&office=house&state=AL&stateFull=Alabama&district=01&per_page=0&sort_hide_null=true

**Comment by PaulClark2** [comment]
@patphongs I'm not sure I understand this issue. 

That coverage end date we display in the data table above should be the same as the one from the financial summary page or the most recent filing. The summary data is from Pass 1 and doesn't rely on transactions being processed.

**Comment by lbeaufort** [comment]
@PaulClark2 then we don't need to change the coverage end date to match https://github.com/fecgov/openFEC/issues/3217. I'll close this issue.
