### ISSUE TITLE
Research: Setup New Relic alert for celery-worker jobs

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3299]
Related issue: https://github.com/fecgov/openFEC/issues/3331

Currently we are not getting notified when celery-worker jobs are failing.  

There needs to be a celery-worker and redis connection to be present in order for schedule jobs such as Materialized view refresh, AO/MUR data refresh and download/export campaign finance data from www.fec.gov to work.

- [ ] Research how to setup an alert mechanism
- [ ] Create a new ticket to implement such a system

**Comment by PaulClark2** [comment]
@rjayasekera are you working on this? Is this still something that needs to happen?

**Comment by patphongs** [comment]
@rjayasekera Please update this ticket with the work you have done so far

**Comment by lbeaufort** [comment]
We moved to Pingdom to track uptime/downtime, and @rjayasekera and @fec-jli added a download test that has been catching celery-worker issues
