### ISSUE TITLE
Fix materialized view refresh error message

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3308]
We found an error message during materialized views refreshing time. 
![image](https://user-images.githubusercontent.com/24943130/43219000-1be9feae-9014-11e8-9fc4-3742d6e1b17a.png)

**Comment by fecjjeng** [comment]
Comparison of all existing materialized views in the database and the message from Kabana log shows all existing materialized views in the database are refreshed. 
Further investigation reveals error message coming from a missing node in the flow.py file.

**Comment by JonellaCulmer** [comment]
PR is merged, so closing.
