### ISSUE TITLE
Update ofec_agg_coverage_date_mv logic

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3313]
**What we are after**: 
Update ofec_agg_coverage_date_mv logic to correctly handle a scenario in which a new is processed but an amendment is not processed.  

**Why we are after it**:
We need to display the correct coverage end date of transactions included in the aggregates. 

**Completion criteria**: 
- [ ] update ofec_agg_coverage_date_mv logic to handle amendments.

Example:
The most recently processed report is the M6 with a coverage end date of 5/31/18. `ofec_agg_coverage_date_mv` currently produces 3/31/18 as the most recently processed report. 

operations_log 

CAND_CMTE_ID	|	RPT_YR	|	RPT_TP	|	AMNDT_IND	|	PASS_3_ENTRY_DONE_DT	|	ENDING_COVERAGE_DT
----	|	----	|	----	|	----	|	----	|	----
C00000935	|	2018	|	M2	|	N	|	2/28/2018	|	1/31/2018
C00000935	|	2018	|	M3	|	N	|	3/23/2018	|	2/28/2018
C00000935	|	2018	|	M4	|	N	|	5/11/2018	|	3/31/2018
C00000935	|	2018	|	M4	|	A	|	6/27/2018	|	3/31/2018
C00000935	|	2018	|	M5	|	N	|	5/25/2018	|	4/30/2018
C00000935	|	2018	|	M5	|	A	|		|	4/30/2018
C00000935	|	2018	|	M6	|	N	|	6/27/2018	|	5/31/2018
C00000935	|	2018	|	M6	|	A	|		|	5/31/2018
C00000935	|	2018	|	M6	|	A	|		|	5/31/2018

ofec_agg_coverage_date_mv

CAND_CMTE_ID	|	FEC_ELECTION_YR	|	COVERAGE_END_DATE
----	|	----	|	----
C00000935	|	2018	|	20180331

**Comment by JonellaCulmer** [comment]
PR is merged, so closing this issue.
