### ISSUE TITLE
Check logs sprint 6.6 (Dr. Smith) week 1

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3318]
Log review needs to be completed for Dr. Smith (Sprint 6.6) week 1 per the [Security Event Review Checklist](https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by lbeaufort** [comment]
**FEC-CMS: 2** 
- package.json - 1 Medium
     -  [Med] Snyk: Cross-site Scripting (XSS) (due 10/8) https://github.com/fecgov/fec-cms/issues/2262

- requirements.txt -  1 Medium 
    - [Med] Open Redirect  (due 10/8)  https://github.com/fecgov/fec-cms/issues/2263


**OPENFEC: 1** 
 - package.json
   -  None
 - requirements.txt: 1 
   -  [Med per Jay] Arbitrary Code Execution (due 9/10) - https://github.com/fecgov/openFec/issues/3280
 - flyway
   - None

**FEC-EREGS: #0**
  - package.json
    - None
 -  requirements.txt
    - None

**FEC-PATTERN-LIB: #3**
 - package.json
    - [MED] ua-parser-js module - Regular Expression Denial of Service (ReDoS) - fecgov/fec-pattern-library#116
    - [MED] chownr - Time of Check Time of Use (TOCTOU) - https://github.com/fecgov/fec-pattern-library/issues/127
    - [LOW] Two low risk modues : **lodash** and **braces** - fecgov/fec-pattern-library#117

**Add/Update User Account : **
WIP

**Deployer Accounts/Service Keys :**
 - Previously **10** service keys found on cloud.gov under **fec-beta-fec** org
