### ISSUE TITLE
Create FEC owned DNS entry for staging space

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3320]
According to cloud.gov support we need to have our own domain in order for us to enable CloudFront cache in Staging space.

Related issue: https://github.com/fecgov/openFEC/issues/3236

> The CDN service is used to provision HTTPS certificates for custom domains and to associate those domains with cloud.gov applications. The custom domain should be a domain controlled by the user, since you'll need to set up DNS for your domain in order to finish provisioning the service instance: https://cloud.gov/docs/services/cdn-route/#how-to-set-up-dns. It looks like your service instance is using a domain that's managed by cloud.gov rather than FEC: fec-stage-proxy2.app.cloud.gov. This isn't a custom domain, since it's managed by cloud.gov, and because you presumably don't have access to the app.cloud.gov DNS configuration, you won't be able to follow the DNS configuration instructions to complete provisioning.
> 
> If you want to set up a CDN service instance for our application, you can create a new instance using a domain that you control, presumably part of *.fec.gov. Then, check the DNS instructions on your new instance and create DNS records as described there.

**Completion criteria:**
- [ ] Figure out what the domain will be for our API staging environment (FEC stage proxy)
- [ ] Email CenturyLink and Gashaw that we need a new DNS name
- [ ] Have CenturyLink delegate the new domain to 18F's DNS

**Comment by rjayasekera** [comment]
Created a related issue:https://github.com/18F/dns/issues/279

**Comment by patphongs** [comment]
This will be stalled until we get our AWS transfer through. That way we can do this configuration ourselves.

**Comment by PaulClark2** [comment]
We've transferred the account but need to setup roles and IAM accounts. I moved this to 7.2 but we can discuss if it needs to happen sooner.

**Comment by lbeaufort** [comment]
@rjayasekera thanks for all your work on this issue! Could you update this issue with your progress, or close it if it's complete?

**Comment by rjayasekera** [comment]
- Created stage.fec.gov domain at AWS commercial account. 
- Got the name servers for the above DNS and registered the domain with Century Link
- Created a Cloud Front collection from origin https://fec-stage-proxy.app.cloud.gov/
- Make an alias to the above collection from stage.fec.gov domain
- Got a certificate for https://stage.fec.gov domain
- Made a CNAME to the above certificate verification link from stage.fec.gov domain
- Set the default Cloud Front cache limit to 600s (10 min)

Now we can access our application (fec-cms / openFEC) in staging environment as follows: https://stage.fec.gov/  (with cache enabled)
To verify caching run: curl -I "https://stage.fec.gov/"
https://fec-stage-proxy.app.cloud.gov/ (without cache enabled)
