### ISSUE TITLE
Add data from H4 to API

### ISSUE THREAD

**Issue by llienfec** [fecgov/openFEC#3341]
We’ve received several requests to expose the data that comes in on Schedule H4.  Users have asked that we expose it at least in the API if not on the site itself.  

Looks like data is in `fec_fitem_sched_h4_vw` and we could possibly use Sch F as a model b/c it gives similar type of data and isn’t manipulated very much.

**Filters:** Users want to filter H4 for a particular committee ID and a particular time frame.

**Fields** needed for H4:
filer_cmte_id                
filer_cmte_nm
pye_nm - If this is only for payees that are orgs, we'll also need payee_l_nm and payee_f_nm
pye_st1                      
pye_city pye_zip                      
evt_purpose_nm               
evt_purpose_desc             
ttl_amt_disb                 
evt_purpose_category_tp_desc      Is this “Allocated activity or event” checkboxes from schedule?
fed_share                    
nonfed_share                 
evt_amt_ytd                  
memo_cd
memo_text                                          
tran_id
rpt_tp
rpt_yr                      
election_cycle

Someone with more technical knowledge, please feel free to groom more completely!

**Comment by bmathesonFEC** [comment]
Received a comment from Party/Non-Party analyst in RAD that it would be useful for this data to be accessible in the data section of the site.

**Comment by jason-upchurch** [comment]
closing in favor of #4112 / #4123
