### ISSUE TITLE
Schedule_e/by_candidate bug

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3343]
For this particular committee http://localhost:8000/data/committee/C90017617/?tab=summary that is an IE, it shows an amount for Independent Expenditures on the financial summary page but then on the spending page, there is no data. 

We found that this appears to be an API bug based on the API call returning 0: https://fec-dev-api.app.cloud.gov/v1/committee/C90017617/schedules/schedule_e/by_candidate/?api_key=NICAR16&sort_hide_null=true&sort=-total&per_page=30&page=1&cycle=2018

And this call has 2 expenditures: https://fec-dev-api.app.cloud.gov/v1/schedules/schedule_e/?sort=-expenditure_date&per_page=20&api_key=DEMO_KEY&committee_id=C90017617

![screen shot 2018-08-21 at 4 07 01 pm](https://user-images.githubusercontent.com/12799132/44426340-61bab380-a55c-11e8-8c70-bc74ea639483.png)

![screen shot 2018-08-21 at 4 08 59 pm](https://user-images.githubusercontent.com/12799132/44426412-93cc1580-a55c-11e8-8075-93e145c3f80d.png)

This issue was found after reviewing this CMS hotfix: https://github.com/fecgov/fec-cms/pull/2296

**Comment by lbeaufort** [comment]
This issue can't be replicated - the IE now appears: https://www.fec.gov/data/committee/C90017617/?tab=spending
