### ISSUE TITLE
[High] Synk - Improper Input Validation (due 09/21/18)

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#3344]
**Improper Input Validation**
Vulnerable module: flask
Introduced through: flask-apispec@0.6.0.post0 and flask@0.12

**Detailed paths**
Introduced through: project@0.0.0 › flask-apispec@0.6.0.post0 › flask@0.12
Introduced through: project@0.0.0 › flask@0.12

**Remediation path**

**Plan A:**
This is desired because it's tech debt that we can pay off while Vraj can still help us.

@vrajmohan has suggested we upgrade to latest version 1.0.2. Flask restful has dependencies of with other small libraries: Flask==0.12
Flask-Cors==3.0.2
Flask-Script==2.0.5
Flask-RESTful==0.3.5
Flask-SQLAlchemy==2.1

Need to investigate all of this in order to upgrade the major version.

**Plan B:** 
Current openFEC version is 0.12. We need to upgrade to 0.12.3 or higher.

**Comment by qqss88** [comment]
some quick links for reference:

https://pypi.org/project/Flask/1.0.2/
https://pypi.org/project/Flask/#history

**Comment by qqss88** [comment]
Things to do:
1. library dependency and compatibility check:

Tool in mind - pipenv (will dig a little more on this)

2. local testing, dev testing and expanded smoke testing

**Comment by qqss88** [comment]
may need some helps from other team members on testing.

**Comment by qqss88** [comment]
Current versions of related libriaries:
Flask-Cors==3.0.6
Flask-Script==2.0.6
Flask-RESTful==0.3.6
Flask-SQLAlchemy==2.3

will suggest and test that all those libraries updated to the newest.
