### ISSUE TITLE
Show Committee ID on Committees CFD page

### ISSUE THREAD

**Issue by llienfec** [fecgov/openFEC#3354]
User was trying to tell the difference between committees with similar names.  Can we make `Committee ID` visible on the search results screen for the `Committees` search in Campaign Finance Data?

Example: https://www.fec.gov/data/committees/?treasurer_name=SYLVAN+MACKANESS

![image](https://user-images.githubusercontent.com/22914750/45038034-64bea500-b02e-11e8-8bde-8e9eb21e4b64.png)

**Comment by lbeaufort** [comment]
@llienfec I agree this would be a great change! I confirmed it's [available in the API](https://api.open.fec.gov/v1/committees/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=true&treasurer_name=SYLVAN+MACKANESS&sort=-first_file_date&per_page=30&page=1) so I'm moving this to the fec-cms repo.

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/fec-cms #2361](https://github.com/fecgov/fec-cms/issues/2361) via [**ZenHub**](https://www.zenhub.com/)
