### ISSUE TITLE
Research: Add committee type column for schedule_a and schedule_b

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3357]
**What we're after:**
In order to enhance performance for searching by Committee type filter, we need to discuss the below solution of adding a committee type column to the schedule_a and schedule_b tables.

Possible solution:
Add column of committee type, but this needs to be updated nightly by script. Committee types change often? Takes 1 hour per cycle for the first time to insert column. 

**Completion criteria:**
- [x] Have a meeting with the following team members: Jean, Helen, Rohan, Vraj, Laura, Joseph
- [x] Create a follow-up implementation issue

**Comment by patphongs** [comment]
Meeting scheduled for 9/11

**Comment by fecjjeng** [comment]
Using the current query that use a join table to get the cmte_tp from the ofec_committee_history_mv to do the filtering, some cycle/cmte_tp combination is slower than acceptable (such as sched_b 2016/E or 2018/E) when sorting AND limit had been included in the query, while other cmte_tp such as H, S, P are ok.  We had tried add index on cmte_tp in ofec_committee_history_mv but not help much.  The explain plan indicated a "Materialize" step is added for these cmte_tp that return very few amount of rows such as cmte_tp E (<100 rows).  I had tried turn session work_mem up and no improvement.  Setting session enable_material to off seems help to improve the performance, but not enough to satisfy the needs.  So adding the cmte_tp to the base table itself maybe the only solution.

**Comment by fecjjeng** [comment]
@ChingKuan had come up with a design to add/maintain the cmte_tp to the sched_a/sched_b tables.  We were trying to flush out the details and testing the feasibility of this approach.

**Comment by fecjjeng** [comment]
After adding cmte_tp column on a test table, which is a complete replica (with all data and indexes) of fec_fitem_sched_b_2017_2018 and adding index to the new cmte_tp.   "Materialize" step is not used according to the explain plan.  The same query (2018/E) running time decrease from 5 minutes to 72 msec.  So adding cmte_tp to the huge schedule tables indeed improve the performance.
The initial update time to fill in the newly added column takes about 5 to 6 hours in our local database on as130 which is faster than the cloud database and increased table size from 67G to 97G.  A separate ticket will be opened to deal with the adding of the new column, the initial update to fill the newly added column for the existing rows, and the daily maintenance of this new column.

**Comment by patphongs** [comment]
Closing this issue after research and meeting have been completed
