### ISSUE TITLE
Add ADR and AF to API

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3359]
From @vrajmohan:

ADRs and AFs are similar to MURs in may respects:
- they have a similar but simpler data structure
- they are available in the same Postgres DB

This task is to:

- [x] retrieve ADRs and AFs from Postgres
- [x] load any attached documents into S3
- [x] index the ADRs and AFs in Elasticsearch

Most of the design and code for MURs can be reused here.

**Developer testing**
- [x] Take a backup of `dev`
- [x] Take a baseline load test of `dev`
- [x] Add ADR/AF locust tests
- [x] Reload legal docs: `cf run-task api  "python manage.py initialize_current_legal_docs" -m 4G --name reinit-legal-docs`
- [x] Re-load test `dev` with a manual deploy
- [x] Test front-end legal search on `dev` with manual deploy
- [ ] Make a follow-up ticket for:
   - backing up `dev` after merge/reload
   - and backing up, reloading legal docs, and backing up again on `stage` and `prod`

**Comment by qqss88** [comment]
steps:
1. define how the ADR and AF docs look like: which fields need to be included
2. define doc type mapping file and add them to ./webservices/legal_docs/index_management.py
3. query database, build ADR and AF doc, index it, refer to:
./webservices/legal_docs/current_murs.py

it is 'one doc build, one doc injected' indexing approach.

**Comment by lbeaufort** [comment]
Tracking fields here: https://docs.google.com/spreadsheets/d/1i8GeWHEeTzt3jdN3RZg3wKA_dSq2J-6CR5JGtq6G2nQ/edit#gid=0

### MUR fields - classic
<img width="733" alt="screen shot 2018-09-07 at 11 16 26 am" src="https://user-images.githubusercontent.com/31420082/45227975-d2b5d700-b28f-11e8-9492-d8e01abd3979.png">

### ADR fields - classic
<img width="680" alt="screen shot 2018-09-07 at 11 14 53 am" src="https://user-images.githubusercontent.com/31420082/45227983-d9dce500-b28f-11e8-9c32-723c2ccfd663.png">

### Admin Fine fields - classic
<img width="727" alt="screen shot 2018-09-07 at 11 14 38 am" src="https://user-images.githubusercontent.com/31420082/45227991-e06b5c80-b28f-11e8-9418-2306223e50ed.png">

**Comment by qqss88** [comment]
those are the fields from the af_case table: 
 {
        "case_id": "46000000003307",
        "af_number_rad": "3307",
        "case_number": "3307",
        "committee_id": "C00612861",
        "report_year": "2016",
        "report_type": "YE",
        "rtb_action_date": "2017-04-03 00:00:00",
        "rtb_fine_amount": "3751",
        "chal_receipt_date": "",
        "chal_outcome_code_desc": "",
        "fd_date": "2017-07-13 00:00:00",
        "fd_final_fine_amount": "0",
        "check_amount": "3751",
        "treasury_date": "",
        "treasury_amount": "",
        "petition_court_filing_date": "",
        "petition_court_decision_date": "",
        "action_date": "",
        "af_category": "",
        "title": "",
        "meeting_type": "",
        "action": "",
        "vote_result": "",
        "commissioner_1": "",
        "commissioner_1_vote": "",
        "commissioner_2": "",
        "commissioner_2_vote": "",
        "commissioner_3": "",
        "commissioner_3_vote": "",
        "commissioner_4": "",
        "commissioner_4_vote": "",
        "commissioner_5": "",
        "commissioner_5_vote": "",
        "commissioner_6": "",
        "commissioner_6_vote": "",
        "pg_date": "2017-08-16 08:45:27.770891"
    }

**Comment by lbeaufort** [comment]
Thanks, @qqss88! My WIP PR is here: https://github.com/fecgov/openFEC/pull/3365
