### ISSUE TITLE
Research: Slow queries performance tuning

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3360]
**What we're after:**
To make our website more efficient, we need to debug and performance tune by identifying slow queries narrow down what needs to be optimized

**Completion criteria:**
- [x] Check the AWS logs for slow queries. Ask FEC AWS owners to pull the logs so that we can analyze. 
- [x] Run pgBadger to identify slowest queries: Wiki documentation is here: https://github.com/fecgov/openFEC/wiki/Analyzing-slow-queries
- [x] Meet to discuss the slowest queries together as a team
- [x] Create a plan of action for when slow queries need to be identified and optimized
- [x] Create new implementation ticket(s) on making the slow queries faster

**Comment by pkfec** [comment]
- @rjayasekera  downloaded AWS logs yesterday
- i ran pgbadger against the logs 
- analyzed the output.html with @fecjjeng @hcaofec 

Following are our findings:
1. We didn't find any slow queries against schedule tables.
2. The slowest queries (26m28s) most of them involve real_efile.sa7

**Comment by patphongs** [comment]
Analyze top 10 slowest queries and base the results against how many times those queries are called. This should lead us on our decisions on which queries to work on first.

**Comment by pkfec** [comment]
Tracking the Top 10 Slow queries here:
https://docs.google.com/spreadsheets/d/1U0EIRbFSuNWJC5uvcb54Sv6KTRnokSSb87Zd_4ZhjrY/edit#gid=0

**Comment by patphongs** [comment]
@pkfec I created a new issue for 7.2 that is connected to this issue: https://github.com/fecgov/openFEC/issues/3378

**Comment by pkfec** [comment]
Closing this issue in favor of #3378
