### ISSUE TITLE
Research: Unable to get a complete pull of schedules/schedule_a/

### ISSUE THREAD

**Issue by hobbes3** [fecgov/openFEC#3369]
I'm trying to pull

https://api.open.fec.gov/v1/schedules/schedule_a/?sort=contribution_receipt_amount&per_page=100&api_key=DEMO_KEY&committee_id=C00673004&cycle=2018

It says there are 56 pages, so when I try to pull the 2nd result set by passing back `last_index` and `last_contribution_receipt_amount`, I get no results:

https://api.open.fec.gov/v1/schedules/schedule_a/?sort=contribution_receipt_amount&last_index=4081720181584744993&committee_id=C00673004&last_contribution_receipt_amount=10500.0&per_page=100&api_key=DEMO_KEY&cycle=2018

I tried using both `sort=contribution_receipt_amount` and the default `sort= contribution_receipt_date `. I _did_ notice that if I omit `last_contribution_receipt_amount` then I can get to the next set, but that's against the documentation.

https://api.open.fec.gov/v1/schedules/schedule_a/?sort=contribution_receipt_amount&last_index=4081720181584744993&committee_id=C00673004&per_page=100&api_key=DEMO_KEY&cycle=2018 (notice this doesn't have `last_contribution_receipt_amount`)

Please advise.

By the way, how many `committee_id` can I pass in at once (for both `schedule_a` and `schedule_e`)? Could I pass hundreds of them? Because I plan on pulling all schedule_a and _e for every committee associated to every Florida House and Senate candidates this cycle, which is 136 people.

**Comment by hcaofec** [comment]
The bug here is caused by the inaccurate counts given by endpoint.  For C00673004, 2018,  there are only 27 rows of sched_a in database. As per_page = 100, there is no result when turning to 2nd page.  But the estimated counts is 5663 which misled the user.

**Comment by hcaofec** [comment]
> I tried using both `sort=contribution_receipt_amount` and the default `sort= contribution_receipt_date`. I _did_ notice that if I omit `last_contribution_receipt_amount` then I can get to the next set, but that's against the documentation.
> 
> https://api.open.fec.gov/v1/schedules/schedule_a/?sort=contribution_receipt_amount&last_index=4081720181584744993&committee_id=C00673004&per_page=100&api_key=DEMO_KEY&cycle=2018 (notice this doesn't have `last_contribution_receipt_amount`)
> 
--- Run same endpoint by omitting `last_contribution_receipt_amount` does not return the 2nd page actually. What returns is a subset of the 27 rows by this filter: 
`sub_id >4081720181584744993`
`order by contribution_receipt_amount`

**Comment by pkfec** [comment]
For a given endpoint you can only search upto 5 committee id. That's the MAX limit set on the API..

**Comment by hcaofec** [comment]
Here is the code part for setting up maximum 5

[views.py](https://github.com/fecgov/openFEC/blob/feature/fix-missing-inaugural-committees/webservices/common/views.py#L67)

**Comment by patphongs** [comment]
We need to fix counts, there is a separate issue open to do this.
