### ISSUE TITLE
Add `candidate_office_sought` to schedules/schedule_e

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3370]
`candidate_office_sought` wasn't included in the fields in this issue: https://github.com/fecgov/openfec/issues/3276 but should be added per @PaulClark2.

Related PR: https://github.com/fecgov/openFEC/pull/3348

**Comment by pkfec** [comment]
There is an existing issue for SE filter. `cand_office` filter can be included in the existing issue # 3276 
closing this issue in favor of https://github.com/fecgov/openFEC/issues/3276

**Comment by lbeaufort** [comment]
Thanks @pkfec!
