### ISSUE TITLE
Create ofec_all_report_mv

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#3373]
continue from [#3230](https://github.com/fecgov/openFEC/issues/3230)

**What we're after:**
This ticket is to track the implementation of creating the materialized view.  Right now each type of reports has its own table, and which table to be used for searching is depended on the type of reports.   Sometimes committee may file wrong reports to FEC.  For example, a house/senate committee files a F3X instead of F3.  If searching for reports by that committee from this page,  the F3X will not show up for the committee.
https://www.fec.gov/data/advanced/?tab=filings

To repair this, a materialized view that includes F3, F3x and F3p will be created and used for reports searching

**Completion criteria:**
- [x] create materialized view
- [ ] make sure the mv is refreshed every night
- [ ] Make sure to test:
   - [ ] Test the totals to make sure that they are still correct. 
   - [ ] Find some examples of committees who have filed more than one Form 3. 
   - [ ] Look at all the references from the old MV to the new MV. 
   - [ ] Make sure amendments versions will still show up ok.
- [ ] Create a new testing ticket after this is merged to make sure things check out. Make testing ticket based on completion criteria.

**Comment by patphongs** [comment]
@jwchumley Can you please flesh out the user story here more. I think we're missing the point about why this issue needs to be done in the first place? cc @AmyKort @PaulClark2

**Comment by hcaofec** [comment]
@patphongs edit the issue to include the reason for this fix based on my knowledge.

**Comment by hcaofec** [comment]
Materialized view is created directly in DEV database.  Because of the complicated mapping of columns from three forms, validation on columns and data itself needs to be done in very careful way.

**Comment by dorothyyeager** [comment]
We will close this ticket as the work has been completed. A new ticket will be put in for the next steps.

**Comment by dorothyyeager** [comment]
Re-opening for use in making that new ticket.
