### ISSUE TITLE
Backup & reload legal docs in stage & prod

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3376]
This is a follow-up task from ADR and Admin fines API work.

**`dev` space**
- [x] Reload legal docs: 
 `cf run-task api "python manage.py refresh_current_legal_docs_zero_downtime" -m 4G --name reload-legal-docs`
- [x] make an elasticsearch backup 

**`stage` space** after 9/18/2018
- [x] Make an elasticsearch backup
- [x] Reload legal docs:
 `cf run-task api "python manage.py refresh_current_legal_docs_zero_downtime" -m 4G --name reload-legal-docs`
- [x] make an elasticsearch backup again

**`prod` space** after 9/25/2018
- [x] Make an elasticsearch backup
- [x] Reload legal docs:
 `cf run-task api "python manage.py refresh_current_legal_docs_zero_downtime" -m 4G --name reload-legal-docs`
- [x] make an elasticsearch backup again

**Comment by patphongs** [comment]
@lbeaufort @qqss88 The deploy of 7.1 has been completed. You can now move forward with the reset of the implementation for this ticket. Thanks!

**Comment by lbeaufort** [comment]
Reloaded and backed up using https://github.com/fecgov/openFEC/wiki/Elasticsearch-backup-instructions off-hours
