### ISSUE TITLE
Add column cmte_tp to fec_fitem_sched_a and fec_fitem_sched_b tables

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3379]
This PR is from issue #3357.  The conclusion of issue #3357 is to add cmte_tp to fec_fitem_sched_a and fec_fitem_sched_b tables to solve the performance issue discovered during attempt to add cmte_tp filter to  sched_a and sched_b tables.

Tasks required:
- [x] adding cmte_tp to fec_fitem_sched_a and fec_fitem_sched_b tables
- [x] the initial update to fill the newly added column for the existing rows
- [x] add index on the new column to the 40+ subtables
- [x] design and implement the daily maintenance of this new column.

**Comment by AmyKort** [comment]
moving to 7.3

**Comment by fecjjeng** [comment]
The following tasked had been complicated for this issue:
- adding cmte_tp to fec_fitem_sched_a and fec_fitem_sched_b tables
- design and implement the daily maintenance of this new column.  
This including the updates of the existing Oracle packages and tables in intermediate database and updates of java program that currently used to do daily data transfer from Oracle to postgresql databases for the new/updated fitem rows.  And also added new Oracle procedures/shell scripts to handle the case when committees have cmte_tp changes that are not part of the daily new/updates.
- the initial update to fill the newly added column for the existing rows.  This involves big data changes and time/resource consuming.  It is designed to be executed in a way that have minimum impact to the database, even it still cause the replica database to slow down due to the amount of activities involved.
- add indexes on the new column to the 40+ subtables after all existing rows of involved tables had been updated to include the new data.
- migration file is still submitted even all tasked had been done in the background to keep the version control clean.  The migration file is written in a way that it will not cause error when merge into cloud databases where the changed had been made.  But it will be executed when creating local DB and to keep it in sync with the cloud databases.

**Comment by hcaofec** [comment]
PR is merged.
