### ISSUE TITLE
Research: Investigate how to best optimize slow queries

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3380]
Have a meeting to discuss with @vrajmohan his past experience with analyzing and optimizing slow queries. This is the time for devs to ask questions and get good strategies on how to tackle this in the future.

**Completion criteria:**
- [x] Take notes on meeting with Vraj to better formulate a strategy

**Comment by pkfec** [comment]
To analyze the queries :

- Grab the the detailed slow query from pgbadger
- Run the query with EXPLAIN ANALYZE against Prod or Dev DB in pgadmin
- Look for join conditions or committee id's that seem to take a long time to execute
  Ex:  avoid using this committee id : C00401224 (ActBlue)
 - See if there is a possibility to add indexes  on any of the columns just like we did to improve SB 
   performance.
