### ISSUE TITLE
Counts - when to use exact and when to use estimates

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3389]
**What we are after:** Better counts

**Why we are after it**: Our counts are inaccurate, and they confuse and frustrate our users. 

**Completion criteria**: 
- [x] Make a plan about counts and estimates

**Comment by vrajmohan** [comment]
For reference, the commit that removed the manifest - https://github.com/fecgov/openFEC/commit/028361c1b4b348d105c81dde6c9cba80b7e8b43e.

**Comment by AmyKort** [comment]
This is probably not going to be a one solution fix. As a first step, we will try to restore accurate counts for results returned at 500,000 or less, and estimate the number of results returned above that.
