### ISSUE TITLE
Missing links to transaction level data: Candidate and committee profile pages

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3391]
This example is of a Senate candidate and committee. 

**What we are after**: Provide users access to transaction level data. 
**Why we are after it**: As part of our disclosure mission, we should provide access to campaign finance data to the public.
**Current state**: We have coded data from the committee but the line item links on the financial summary are not active. Users cannot click through to explore the schedule data.

**Examples**: 
https://www.fec.gov/data/candidate/S6MT00162/?cycle=2006&election_full=true
https://www.fec.gov/data/candidate/S6MT00162/?cycle=2006&election_full=true

**Screen shots**: 
![image](https://user-images.githubusercontent.com/11817734/45774583-5621e180-bc1b-11e8-8687-f8515ff62aed.png)

![image](https://user-images.githubusercontent.com/11817734/45774608-6934b180-bc1b-11e8-946e-555081982617.png)

**Completion criteria**:
- [x] Investigate why line item links are not active
- [ ] Make line item links active

**Comment by lbeaufort** [comment]
@PaulClark2 it looks like this has been hard-coded to only link after 2006 since the beginning of the repo - https://github.com/fecgov/fec-cms/commit/fbd7e7f37254b0766a6803a6d5867eb3d81a3b12#diff-4817fd82110ba07bc1ccf075000feccdR27

Looks like that was one of the original requirements: https://github.com/18F/openFEC-web-app/issues/2125

**Comment by PaulClark2** [comment]
@lbeaufort thanks for looking into this. 

@AmyKort @jwchumley it seems to me if we have the coded data we should let folks click through to it. We will need to explain to folks that the scope of the data is less than that of more recent filings.

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/fec-cms #2401](https://github.com/fecgov/fec-cms/issues/2401) via [**ZenHub**](https://www.zenhub.com/)
