### ISSUE TITLE
Need to remove AO citation from AO 2011-12 canonical page

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3393]
We've picked up a date, rather than an AO number, when parsing AOs cited within an AO https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_no=2011-12&ao_category=F . We need to remove AO 2017-03 from the list of later opinions that cite AO 2011-12.

![image](https://user-images.githubusercontent.com/13237823/45891582-f13dc700-bd93-11e8-80b3-9337cca9bad9.png)

It appears we've grabbed that reference out of the following sentence in AO 2017-03: "For example, three of the AUA’s six most recent presidents (serving in 2010-11, 2011-12, and 2015-16) had previously been president of AACU."

**Comment by lbeaufort** [comment]
This might be the right time to implement https://github.com/fecgov/openFEC/issues/3302 and make a change to both exclude a list of false positives and include a list of missed citations.

**Comment by lbeaufort** [comment]
@AmyKort as discussed in sprint planning, we're going to address this issue as part of https://github.com/fecgov/openFEC/issues/3302
