### ISSUE TITLE
Upgrade smart_open to 1.6.0 or higher

### ISSUE THREAD

**Issue by vrajmohan** [fecgov/openFEC#3398]
The latest release is 1.7.1. Version 1.6.0 includes support for `boto3`. This will allow us to drop `boto` altogether.

This will also solve this Issue [https://github.com/fecgov/openFEC/issues/3527](https://github.com/fecgov/openFEC/issues/3527)--clean `requests module` in webservices/tasks/utils.py

**Comment by lbeaufort** [comment]
PR is merged: https://github.com/fecgov/openFEC/pull/3534
