### ISSUE TITLE
Update Flask-SQLAlchemy to the newest version

### ISSUE THREAD

**Issue by qqss88** [fecgov/openFEC#3404]
This is derived from issue 3371. Flask-SQLAlchemy update to 2.2 and 2.3 both broke the unit tests. More time and efforts will be added on this for a near-future update.

(update to 2.2 has been fixed for unit testing, will prepare a separate PR for this.)

**Comment by AmyKort** [comment]
Where are we with this?

**Comment by lbeaufort** [comment]
@AmyKort the PR is ready for review: https://github.com/fecgov/openFEC/pull/3753
