### ISSUE TITLE
Research visualization framework options

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3406]
**What we are after**: We need a framework that will support visualizations. 

**Why we are after it**: We need to provide users and internal stakeholders with data visualizations, yes maps and other visualizations.

**Completion criteria**: 
- [x] Meet to discuss potential uses for data visualizations on .gov with @JonellaCulmer 
- [x] Review potential options based on research with @JonellaCulmer 
- [x] Present options to product managers and product owner
- [x] Present options to team 

cc: @wluoFEC

**Comment by qqss88** [comment]
some options from my mind:
- d3.js
- echarts(from chinese company baidu)

some python solutions: interactive and can be pushed to front end
plotly
bokeh

another option(less frontend dev efforts): ElK stack(kibana for visualizaiton).

will add more based on my research.

**Comment by qqss88** [comment]
this seems like a good starting point for map-based visuals:
https://github.com/markmarkoh/datamaps

**Comment by qqss88** [comment]
a collection of git hub list on data visualization:
https://github.com/fasouto/awesome-dataviz

**Comment by qqss88** [comment]
more on python tools:

https://blog.modeanalytics.com/python-interactive-plot-libraries/

**Comment by dorothyyeager** [comment]
We're going to timebox this for this sprint.

**Comment by qqss88** [comment]
currently working on the summary and demo for this ticket. Will wrap up before demo next Monday

quick summary:
1. best front end framework option: d3
2. best python framework: plotly
3. ELK stack as a backup option, may also used for internal reporting.

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by qqss88** [comment]
ppt uploaded to google drive and here is the link:

https://drive.google.com/open?id=1zrxtequ8H52M4jBVA48mVul5_lr7BaTd

**Comment by dorothyyeager** [comment]
Work is completed, so closing.
