### ISSUE TITLE
Flask upgrade testing - a followup on #3403

### ISSUE THREAD

**Issue by qqss88** [fecgov/openFEC#3409]
intensive testing on dev server to make sure everything is ok after Flask and Flask-related packages upgrade(see #3403 fro upgrade details.)

**Comment by qqss88** [comment]
we may need to have a after-deployment automatic or semi-automatic api testing solutions. Add some quick links here for quick reference:

https://medium.com/@alicealdaine/top-10-api-testing-tools-rest-soap-services-5395cb03cfa9

https://github.com/taverntesting/tavern/blob/master/example/simple/test_server.tavern.yaml

**Comment by lbeaufort** [comment]
@vrajmohan suggested we add every endpoint to locust for testing situations like these. Reference: https://docs.google.com/document/d/1ru6Qg0ErTQLD7a86qxW7kbaKbzkayt_X9PmGjZdC_nY/edit

**Comment by qqss88** [comment]
Sure. I'll take a look and give it a quick test. Thx.

**Comment by qqss88** [comment]
current locust endpoint testing coverage is still low: totally 19 testing tasks with redundancy.

according to rest.py, we have 72 endpoints defined.

**Comment by qqss88** [comment]
another python REST api testing tool to consider:

https://github.com/taverntesting/tavern

**Comment by qqss88** [comment]
run locust tests on staging:

have some issues:
1. one failed request on 'load_schedule_a_large'
2. all failed on 'load_schedule_a_problematic'.

see attached csv output for [details.
[requests_1538576601.084537.txt](https://github.com/fecgov/openFEC/files/2442425/requests_1538576601.084537.txt)

**Comment by qqss88** [comment]
locust tests on production:

similar results back: all 'load_schedule_a_problematic' failed. 50% 'load_schedule_a_large' failed.

requests_1538578513.1127412.txt

**Comment by patphongs** [comment]
@qqss88 @lbeaufort It appears that the flask upgrade is effecting the loading of candidate and committee profile pages. The majority of those calls are using the api_caller.py and so on load of the page, it gives us 500 errors when trying to call to the API. Calls that are datatable calls to the API function ok.

**Comment by qqss88** [comment]
the candidate and committee profile page loading issue has been resolved. the corresponding PR is here:

https://github.com/fecgov/openFEC/pull/3419

**Comment by qqss88** [comment]
created new pull request:

https://github.com/fecgov/openFEC/pull/3426

**Comment by qqss88** [comment]
Here is a quick summary on the testing:
1. went through version release history for all 4 packages involved in this upgrade
2. use pipenv for package version conflict checking and potential vulnerability checking
3. PR and peer PR review
4. endpoints testing: locust testing, all_endpoints scripting/testing, endpoints consumer testing(CMS)

major issue identified: trailing back slack issue, recorded in this PR:
https://github.com/fecgov/openFEC/pull/3419

special thanks to Pat, Laura and other team members' help on this issue.

**Comment by dorothyyeager** [comment]
Work is completed, so closing.
