### ISSUE TITLE
Offboard Vraj Mohan

### ISSUE THREAD

**Issue by vrajmohan** [fecgov/openFEC#3410]
Remove @vrajmohan from:
[] GitHub repo membership
[] Slack (only retain #alumni)
[] NewRelic
[] AWS 
[] CircleCI
[] cloud.gov

Tagging @apburnes for creating a similar ticket

**Comment by apburnes** [comment]
Also cloud.gov?

**Comment by lbeaufort** [comment]
😭 Thanks, @vrajmohan! These tickets go in our accounts repo - I'll move it now.

**Comment by lbeaufort** [comment]
Closing in favor of https://github.com/18F/fec-accounts/issues/146
