### ISSUE TITLE
Senate committees don't display the Raw electronic filings box

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3413]
What we need: 
The public needs to be able to see the latest Senate efilings that have come in since the previous evening process  kicked off. 
Why: 
So users don't have to wait 24 hours for the next overnight process.

THese examples are only good for Oct 1, 2018:

This House committee filed this morning. Note the Raw Eelectronic Filings box that includes this mornings filing:
https://www.fec.gov/data/committee/C00470393/?tab=filings
![image](https://user-images.githubusercontent.com/12615919/46295182-729c1300-c565-11e8-9f9c-37750f3c8530.png)

This Senate committee filed this morning. Note NO Raw electronic filings box:
https://www.fec.gov/data/committee/C00471557/?tab=filings
![image](https://user-images.githubusercontent.com/12615919/46295282-a5460b80-c565-11e8-9dcf-9ea7d68fdaa3.png)

I suspect in the display code there is a "don't display if Senate Committee" statement.

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/fec-cms #2417](https://github.com/fecgov/fec-cms/issues/2417) via [**ZenHub**](https://www.zenhub.com/)
