### ISSUE TITLE
Mis-mapped fields at /committee/{committee_id}/reports/ for Senate/paper reports

### ISSUE THREAD

**Issue by esonderegger** [fecgov/openFEC#3434]
It appears as though some (but not all) fields in the results returned by the `/committee/{committee_id}/reports/` endpoint are mis-mapped.

An example report is: https://api.open.fec.gov/v1/committee/C00501197/reports/?api_key=DEMO_KEY&year=2018&report_type=Q2 compared to http://docquery.fec.gov/cgi-bin/paper_forms/C00501197/1250782/

Some fields I've noticed are giving different results are:

- total_disbursements_ytd
- other_disbursements_ytd
- transfers_to_other_authorized_committee_ytd
- other_receipts_ytd

This is my first time reporting an issue to the OpenFEC repository - please let me know if there's anything else I can do to be helpful.

**Comment by AmyKort** [comment]
Thanks for reporting this!

**Comment by JonellaCulmer** [comment]
You can track the work on this issue here: https://github.com/fecgov/openFEC/issues/3435
