### ISSUE TITLE
/filings/ count incorrectly counting RFAI's twice

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3440]
Example: https://fec-dev-api.app.cloud.gov/v1/filings/?api_key=DEMO_KEY&sort_hide_null=true&data_type=processed&committee_id=C00151845&sort=-receipt_date&per_page=30&page=1

Returns 16 results but count is 21. 

- [ ] Fix the count
- [ ] Make sure this doesn't impact the front-end filing data tables and candidate/committee profile pages - was this done on purpose for a front-end need?

**Comment by pkfec** [comment]
`ofec_filings_all_mv` was originally composed data from 
-   disclosure.f_rpt_or_form_sub
-   disclosure.nml_form_rfai
However, disclosure.f_rpt_or_form_sub already has all the RFAI filing information, under FORM_TP = 'FRQ'
So the union all from disclosure.nml_form_rfai is redundant.

`ofec_filings_all_mv` is therefore refactored to return `RFAI data` from `disclosure.f_rpt_or_form_sub`,
which has the required data.

**Comment by fecjjeng** [comment]
Comparing of the RFAI data in disclosure.f_rpt_or_form_sub and disclosure.nml_form_rfai, only 3 rows were missing in disclosure.f_rpt_or_form_sub and after reported to Informatica administrator, these 3 rows had been added to disclosure.f_rpt_or_form_sub so the RFAI data is complete.

The following columns with data derived from rows in disclosure.f_rpt_or_form_sub but not in nml_form_RFAI table:
pages
fec_url
is_amended

The following columns with data derived from rows in disclosure.nml_form_RFAI table but is null in  disclosure.f_rpt_or_form_sub:
previous_file_number (had been hard-coded to 0 in previous ofec_filing_all_mv definition, kept)
election_yr (not meaningful for RFAI, disclosure.f_rpt_or_form_sub is correct not to include it)
amndt_ind  (some rows in nml_form_RFAI has value, but not meaningful for RFAI,, disclosure.f_rpt_or_form_sub is correct not to include it)

**Comment by fecjjeng** [comment]
The original API code already handled the case when user searches for form_type RFAI, search for RFAI and FRQ.  Therefore no need to update the API after ofec_filings_all_mv refactoring.

**Comment by pkfec** [comment]
PR is merged. This issue is resolved.

**Comment by AmyKort** [comment]
Thanks @pkfec !
