### ISSUE TITLE
invoke-restmethod : Cannot send a content-body with this verb-type

### ISSUE THREAD

**Issue by danSpotter** [fecgov/openFEC#3447]
How do you pass a query via powershell?

$tb = @{
cycle = 2016
candidate_id = "P80001571"
}|convertto-json

$t = "https://api.open.fec.gov/v1/schedules/schedule_a/by_size/by_candidate/?api_key=$apikey"
$rest = invoke-restmethod -uri $t -body $tb -method GET

**Comment by lbeaufort** [comment]
Hi @danSpotter, thanks for your question. 

It works for me if I remove the `|convertto-json` - can you give that a shot? If that doesn't work, can you give me some more information about your operating system, version of powershell, etc?

```
$tb = @{
cycle = 2016
candidate_id = "P80001571"
}
$t = "https://api.open.fec.gov/v1/schedules/schedule_a/by_size/by_candidate/?api_key=$apikey"
$rest = invoke-restmethod -uri $t -body $tb -method GET
```

**Comment by danSpotter** [comment]
Now why didn't I try that? :-) Most of the api's I've dealt with so far, require the conversion.

**Comment by lbeaufort** [comment]
@danSpotter I'm not as familiar with Powershell - I found [this answer](https://stackoverflow.com/a/32443537) to be helpful. Happy querying!
