### ISSUE TITLE
Add prev_file_num and amndt_ind to /schedules/schedule_e/ endpoint

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3448]
Users need to have the amendment indicator and previous file_num when they export independent expenditure data in order to make sense of the data. In order for that to happen it needs to be added to the `/schedules/schedule_e/ ` endpoint.

The /schedules/Schedule_e endpoint does not include these two columns but now there is a materialized view in Dev, the public.ofec_schedule_e_temp_mv that is a copy of the ofec_schedule_e_mv with `prev_file_num` and `amndt_ind` added. It should be used for developing and testing the API.

Completion Criteria:
- [ ]  Add amndt_ind and prev_file_num to endpoint
- [ ]  test ie export to make sure the columns are added to the export.  https://www.fec.gov/data/independent-expenditures/?data_type=processed&committee_id=C00680926&is_notice=true

**Comment by PaulClark2** [comment]
Add language to the data page and the API documentation explaining there are duplicate transactions in this data. https://www.fec.gov/data/independent-expenditures/?data_type=processed&is_notice=true and 
https://api.open.fec.gov/developers/#/independent_expenditures

**Comment by pkfec** [comment]
I have updated `itemized.py` model file to include the two new columns. Quickly tested the API and EXPORT functions  on my local feature branch. The two columns appear on the API and the Export function. Here are the screenshots:
![screen shot 2018-10-18 at 4 26 50 pm](https://user-images.githubusercontent.com/11650355/47182655-fb4fd880-d2f3-11e8-8285-2cd1971881af.png)
![screen shot 2018-10-18 at 4 35 31 pm](https://user-images.githubusercontent.com/11650355/47182664-0276e680-d2f4-11e8-8a99-08442d3e7535.png)
![screen shot 2018-10-18 at 4 31 11 pm](https://user-images.githubusercontent.com/11650355/47182682-0c004e80-d2f4-11e8-9bce-4c619f1bf144.png)

**Comment by pkfec** [comment]
This change requires to create a new database migration file to include the two new columns. I will work with @fecjjeng on this.

**Comment by pkfec** [comment]
@jwchumley @PaulClark2 Please confirm that we are not alerting the language on IE API documentation.
And also no changes on the CMS data pages, since we are showing the exact counts.

**Comment by PaulClark2** [comment]
The language changes should not block releasing the API change. The language changes can catch-up.  We have a release on 10/23. So, the language changes will just be a few days behind the API change.

**Comment by jwchumley** [comment]
@Priyanka Kasireddy<mailto:PKasireddy@fec.gov>


are you talking about this language:

[cid:f3c0f4cf-1394-4e42-850a-93d8995ccbbb]


Jeff Chumley

Electronic Filing, Web and Disclosure Branch Manager

Federal Election Commission



________________________________

**Comment by pkfec** [comment]
that's correct.

Thanks,
Priya Kasireddy



________________________________________

**Comment by pkfec** [comment]
@jwchumley @PaulClark2 
The backend changes( API and DB ) will be deployed as a  hotfix sometime today.
