### ISSUE TITLE
efile/filings broken?

### ISSUE THREAD

**Issue by lbvienna** [fecgov/openFEC#3453]
Hi there,

I'm currently trying to parse efilings and the `efile/filings` endpoint (`https://api.open.fec.gov/v1/efile/filings/\?per_page\=100\&sort\=-receipt_date\&api_key\={API_KEY}\&min_receipt_date\=20181020\&max_receipt_date\=20181024`) and the last filing I can see is by One Nation United from around 4am eastern time. 

When I compare it to the RSS feed (`http://efilingapps.fec.gov/rss/generate\?preDefinedFilingType\=ALL`) it looks like the endpoint is either stuck or broken because the RSS feed shows newer filings. I was wondering whether this is related to the humungous ActBlue filing that came in on Saturday, since that is the next filing according to the RSS feed?

In any case thank you very much.

**Comment by lbeaufort** [comment]
Hi @lbvienna, thanks for reporting this issue. It looks like it's been resolved, but I will investigate to see what may have caused the delay. Do you remember during what times you noticed they were out of sync?

Also, do you mind taking another look to confirm they're no longer out of sync?

**Comment by lbvienna** [comment]
@lbeaufort, thanks for your reply! I noticed that they were out of sync at 10am and I realized that the problem resolved itself around 3pm. But I'm pretty sure the problem started at 4am. My theory is that processing the ActBlue filing just took a while.

And yeah, can confirm that they are back in sync.

Thanks again!
