### ISSUE TITLE
No count for /schedule_a/by_size/by_candidate/

### ISSUE THREAD

**Issue by hobbes3** [fecgov/openFEC#3456]
The JSON response is missing the `count` key for each size, which makes this endpoint less than useful :-).

I expect to see a `count` key, but I don't:

    {
      "cycle": 2018,
      "total": 6826504.4800000004,
      "candidate_id": "S8FL00166",
      "size": 0
    }

For example: https://api.open.fec.gov/v1/schedules/schedule_a/by_size/by_candidate/?per_page=20&page=1&api_key=DEMO_KEY&election_full=false&sort_null_only=false&cycle=2018&sort_hide_null=false&candidate_id=S8FL00166

This is an example of what the count will look like within this `/schedule_a/by_size` call.
https://api.open.fec.gov/v1/schedules/schedule_a/by_size/?page=1&sort_hide_null=false&sort_null_only=false&api_key=DEMO_KEY&per_page=20

- [ ] Add to `schedule_a/by_size/by_candidate` resource `ScheduleABySizeCandidateView`. Has label_columns variable, add it there.
- [ ] Add count to the schema file
- [ ] Explore inheriting from the `CandidateAggregateResource` class
- [x] Make sure that it's in the table

**Comment by JonellaCulmer** [comment]
We have a model of the existing endpoints with the count. We can look at the other schedule_a aggregate resources. [ Fill this out more during technical grooming.]
