### ISSUE TITLE
Drop old dsc_sched_b_aggregate_xxxxx tables after complete switch to new tables with update business logic

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3459]
The following 3 tables are in the process of being replaced by
dsc_sched_b_aggregate_purpose
dsc_sched_b_aggregate_recipient
dsc_sched_b_aggregate_recipient_id

are in the process of being replaced by the following tables with updated business logic and new and renamed columns
dsc_sched_b_aggregate_purpose_new
dsc_sched_b_aggregate_recipient_new
dsc_sched_b_aggregate_recipient_id_new

These tables will be, and only will be dropped after API using these tables had been completely switched.

Related issued:
#3431 
#3390 

- [x] Tables dropped from postgresql databases
- [x] Oracle tables/procedures related to the calculation of these tables will be dropped
- [x] Nightly transfer procedure for these tables will be removed
- [x] Update sample_db

**Comment by fecjjeng** [comment]
Oracle tables/procedures related to the calculation of these tables had been dropped
Nightly transfer procedure for these tables had been removed
Updated sample_db to reference the new set of dsc_sched_b_aggregate tables
Original dsc_sched_b_aggregate tables dropped from postgresql databases

**Comment by hcaofec** [comment]
PR has been merged.
