### ISSUE TITLE
AOs: Short-term fix for AO missed/false positive citations

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3461]
What we're after:
So that we can quickly update AO citations that are missed or accidentally included by the AO loading process, we should have a list-like thing with "extra" citations that aren't picked up by the REGEX due to bad OCR text or unusual formats.

- [x] Design python data structure(s) `lookup` to hold this info - maybe AO #, citation, date added, added by, exclude/include ....anything else relevant. (Separate include/exclude lookup?)
- [x] Modify the AO reload management task to also check this `lookup` for citations missed excluded ( 1 - remove false positives 2 - add missed)

See https://github.com/fecgov/openFEC/issues/3393 as an example

See also, past research on false positives: 
https://docs.google.com/spreadsheets/d/1-nf-oAPtw3LisZInuDHcQ7JdpyEQXRISZ4kY1ONrFcE/edit?usp=drive_web&ouid=114351900669501389307

https://docs.google.com/spreadsheets/d/161cnTtYzXzXW2iNxZPIX9rYhko2ZV2deHYFNDP-R49o/edit#gid=0

For a more elegant long-term solution, see #3302

**Comment by patphongs** [comment]
@lbeaufort This looks like a really big issue. Can we split it up? Should we split up the python data structure design and the modification of the AO reload management? 

Is this something that we want to take out of next sprint 7.5? Seems like a lot, maybe we want to save this for the innovation sprint? @AmyKort

**Comment by lbeaufort** [comment]
This is now a small task, sorry if I made it sound complicated!
