### ISSUE TITLE
Raw house/senate efilings throwing 500 error

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3476]
The following endpoint is giving `Internal Server Error` 
https://api.open.fec.gov/v1/efile/reports/house-senate/?sort=-receipt_date&sort_null_only=false&api_key=DEMO_KEY&per_page=20&page=1&sort_hide_null=false which causes no results to show for raw house/senate filings: https://www.fec.gov/data/reports/house-senate/?data_type=efiling

It looks like this is being caused by some bad data with `C00660126`.

Exception:
`2018-11-06T08:00:07.27-0500 [APP/PROC/WEB/3] OUT ERROR:flask.app:An API error occurred with the status code of 500 ('>' not supported between instances of 'NoneType' and 'NoneType').`

`cash = max(line_list.get('coh_cop_i'), line_list.get('coh_cop_ii'))`

C00660126 doesn't have COH for this report - fix MV? http://docquery.fec.gov/pdf/852/201811059133590852/201811059133590852.pdf

**Comment by pkfec** [comment]
Hot fix is deployed to production. Closing the issue.
