### ISSUE TITLE
[Med] Snyk: Information Exposure requests module(same as cms issue) [due 01/06/19]

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#3478]
Issue description: [https://app.snyk.io/vuln/SNYK-PYTHON-REQUESTS-72435](https://app.snyk.io/vuln/SNYK-PYTHON-REQUESTS-72435)

**Remediation**
Upgrade request to version 2.20 or higher.

Same issue as cms: [https://github.com/fecgov/fec-cms/issues/2456](https://github.com/fecgov/fec-cms/issues/2456)

**Comment by qqss88** [comment]
current version: 2.18.4
newest version: 2.10.1

quick link to release history: 
http://docs.python-requests.org/en/latest/community/updates/#software-updates

**Comment by qqss88** [comment]
al affected modules:

./webservices/tasks/utils.py
./webservices/legal_docs/load_legal_docs.py
./webservices/utils.py

**Comment by qqss88** [comment]
things to do:
1. review requests release history for any potential issues.
2. make sure all unit tests ok
3. make sure all api endpoints ok
4. make sure all affected modules working ok.

**Comment by fec-jli** [comment]
The newest version should be 2.20.1 , right?

**Comment by qqss88** [comment]
yes, typo:-( thx for keeping an eye on this.

**Comment by qqss88** [comment]
'requests' module removed from ./webservices/tasks/utils.py:
it is imported but NEVER used.
.

**Comment by qqss88** [comment]
in ./webservices/utils.py:
'requests' was used to post to slack

    response = requests.post(
        env.get_credential('SLACK_HOOK'),
        data=json.dumps({
            'text': message, 'channel': channel, 'link_names': 1,
            'username': 'Ms. Robot', 'icon_emoji': ':robot_face:',
        }),
        headers={'Content-Type': 'application/json'},
    )
    if response.status_code != 200:
        logger.error('SLACK ERROR- Message failed to send:{0}'.format(message))

**Comment by qqss88** [comment]
'requests' was heavily used in legal_doc ES indexing in load_legal_docs.py.

in unit tests, those functions are mocked.

**Comment by qqss88** [comment]
So we need to pay attention and test slack messaging and legal_doc indexing after the update. None of them are covered by unit tests.

**Comment by qqss88** [comment]
pytest unit tests passed.

**Comment by qqss88** [comment]
python manage.py index_statutes passed.
