### ISSUE TITLE
Update Bastion Host tunnel variables

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#3492]
1) 11/27 cut release branch, update FEC_MIGRATOR_SQLA_CONN_STAGE on circleci.

2) 12/4 release, update FEC_MIGRATOR_SQLA_CONN_PROD on circleci.

Related PR: https://github.com/fecgov/openFEC/pull/3488
Related Issues:
![Screen Shot 2018-11-15 at 11.48.40 AM.png](https://images.zenhubusercontent.com/595e524361b4ca3b0a736e43/9eb2a588-e4f3-411b-8161-9239f9d4f793)
![Screen Shot 2018-11-15 at 11.49.12 AM.png](https://images.zenhubusercontent.com/595e524361b4ca3b0a736e43/7abf9767-b8c7-4f70-8ea1-463eacfc67f9)

**Comment by pkfec** [comment]
@fec-jli Add the Bastion Host environement variable on **Stage** environement.

**Comment by rjayasekera** [comment]
Production CircleCI variables modified. Closing this issue
