### ISSUE TITLE
Swagger has incorrect field format for the load_date field of candidates endpoint?

### ISSUE THREAD

**Issue by adamConnerSax** [fecgov/openFEC#3496]
I'm trying to use the provided swagger file to create a client.  I can successfully query data but the decoding (transformation from json into a data type) is failing on the the "load_date" field at the "candidates" endpoint.  I think this is because in the swagger "load_date" has format "date" but the data is like a "date-time".  
I can work around this, but it makes auto-generation of strongly-typed clients (in my case, haskell) fail.
It's also possible that I'm misunderstanding the types here.  I'm new to swagger and this client-library generator.

**Comment by fec-jli** [comment]
This is done. we changed load_date field from date to DateTime.

**Comment by adamConnerSax** [comment]
Thanks!
