### ISSUE TITLE
Typo in committe name in docquery file

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3500]
@fec-issue-bot commented on [Tue Dec 12 2017](https://github.com/fecgov/FEC/issues/4805)

## What were you trying to do and how can we improve it?
 When you click on the National Association for Gun Rights Inc PAC's Amendment 5 Statement of Organization (current version) it brings you to this page, http://docquery.fec.gov/cgi-bin/forms/C00481200/1192340/. On that page it incorrectly lists the name of the connected organization as "hts Inc PAC National Association for Gun Rights, I". As the PDF version of the filing indicates, it should be "National Association for Gun Rights, Inc.", which is a completely separate organization and does not include the word "PAC". Please correct this issue. Thank you! 

## Details
* URL: https://www.fec.gov/data/committee/C00481200/?tab=filings 
* User Agent: Amazon CloudFront

---

@jwchumley commented on [Wed Dec 13 2017](https://github.com/fecgov/FEC/issues/4805#issuecomment-351404528)

Thanks for the feedback. We're looking into it. 

---

@AmyKort commented on [Wed May 30 2018](https://github.com/fecgov/FEC/issues/4805#issuecomment-393208042)

@jwchumley  This doesn't seem to be resolved.

**Comment by lbeaufort** [comment]
@jwchumley is this a salient issue? It looks like the raw .fec file is correct.

**Comment by jwchumley** [comment]
@AmyKort 

Would you confirm for me that it is correct now. It looks correct to me but I just want to make sure.

**Comment by AmyKort** [comment]
Looks good to me @jwchumley !
