### ISSUE TITLE
Senate candidate showing up in wrong Senate class

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3501]
@fec-issue-bot commented on [Mon Dec 18 2017](https://github.com/fecgov/FEC/issues/4820)

## What were you trying to do and how can we improve it?
 Received a call that Tammy Duckworth is showing up in 2018 Election Cycle candidates for Senate.  However she isn't up for election until 2022. 

## Tell us about yourself
 Public Records Staff on behalf of a caller 

## Details
* URL: https://www.fec.gov/data/candidate/S6IL00292/?tab=about-candidate 
* User Agent: Amazon CloudFront

---

@AmyKort commented on [Wed May 30 2018](https://github.com/fecgov/FEC/issues/4820#issuecomment-393202813)

cc @PaulClark2

**Comment by jwchumley** [comment]
I just made some changes in the database. There was an erroneous form 2z set for 2018 that caused some mahem. I think I just cleaned everything up but will have to let it process tonight to make sure.

**Comment by AmyKort** [comment]
Looks good to me https://www.fec.gov/data/elections/senate/IL/2018/
