### ISSUE TITLE
48-hour notices not showing up in /reports/house-senate/

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3507]
@fec-issues-bot commented on [Sun May 06 2018](https://github.com/fecgov/FEC/issues/5758)

## What were you trying to do and how can we improve it?
 48 notices don't appear to show up on this page: https://www.fec.gov/data/reports/house-senate/?data_type=processed&committee_id=C00646745&report_type=48 
Even if you go all the way down to report type and choose 48 hour notification. I know there is a delay in posting (the old site vs. the new site) but it has been 24 hours since I filed a 48-hour notice. 

## Details
* URL: https://www.fec.gov/data/reports/house-senate/?data_type=processed&committee_id=C00646745&report_type=48 
* User Agent: Amazon CloudFront

---

@lbeaufort commented on [Mon Nov 26 2018](https://github.com/fecgov/FEC/issues/5758#issuecomment-441808635)

Thanks for reporting this issue - we're going to move this issue to our openFEC repo to address it.

**Comment by lbeaufort** [comment]
API call is https://api.open.fec.gov/v1/reports/house-senate/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&data_type=processed&committee_id=C00639591&report_type=48&sort=-receipt_date&per_page=30&page=1

Looks like there are no results for `report_type` 24/48. 

https://api.open.fec.gov/v1/reports/house-senate/?page=1&sort_null_only=false&api_key=DEMO_KEY&per_page=20&report_type=48&sort_hide_null=false&sort_nulls_last=false&sort=-coverage_end_date

We should: 
- [ ] Confirm there are no results for `report_type` 24/48
- [ ] Remove that from the `report_type` options
- [ ] Remove that from the front-end options

**Comment by hcaofec** [comment]
The MV behind the endpoint does not have 24/48.  For House/Senate committees, MV only includes Form 3.

**Comment by hcaofec** [comment]
<img width="906" alt="screen shot 2018-11-29 at 11 11 22 am" src="https://user-images.githubusercontent.com/24396726/49235288-c42b1780-f3c7-11e8-82d2-37c6c109fc60.png">

**Comment by hcaofec** [comment]
PR is merged so close this ticket.
A ticket for CMS change is created: [#2561](https://github.com/fecgov/fec-cms/issues/2561)
