### ISSUE TITLE
Add 'form_type' filter to /efile/filings/ endpoint

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3523]
User story: As a member of the press, I want to be able to see raw Form 2 filings. (See https://github.com/fecgov/FEC/issues/8748)

**Completion criteria:**
- [ ] Add 'form_type' filter to /efile/filings/ endpoint

**Comment by lbeaufort** [comment]
Note: This is more involved, because it's missing from the underlying `real_efile` tables. We should reconsider this work as part of our larger strategy to improving raw data.

**Comment by cnlucas** [comment]
Closing in favor of https://github.com/fecgov/openFEC/issues/5497
