### ISSUE TITLE
clean `requests module` in webservices/tasks/utils.py

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#3527]
'requests module' is not used in openFEC/webservices/tasks/utils.py
we can remove it.

**Comment by fec-jli** [comment]
This will be solved in Issue [https://github.com/fecgov/openFEC/issues/3398](https://github.com/fecgov/openFEC/issues/3398). This can be closed.

**Comment by lbeaufort** [comment]
Thanks @fec-jli!
