### ISSUE TITLE
[Med] Snyk: Cross-site Scripting (XSS) due 2/4/19 

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3528]
Cross-site Scripting (XSS)
Vulnerable module: react-dom
Introduced through: react-dom@16.3.2

Remediation
Upgrade react-dom to versions 16.0.1, 16.1.2, 16.2.1, 16.3.3, 16.4.2 or higher.

https://app.snyk.io/org/fecgov/project/d0baf872-87d8-4d68-80a5-cb52a6d0f57b

**Comment by fec-jli** [comment]
Fixed in PR [https://github.com/fecgov/openFEC/pull/3556](https://github.com/fecgov/openFEC/pull/3556)
