### ISSUE TITLE
[Med] Regular Expression Denial of Service due 2/4/19 

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3529]
Regular Expression Denial of Service (ReDoS)
Vulnerable module: ua-parser-js
Introduced through: react-dom@16.3.2, react@16.3.2 and others

Remediation: Your dependencies are out of date, otherwise you would be using a newer ua-parser-js than ua-parser-js@0.7.17. Try reinstalling your dependencies. 

https://app.snyk.io/vuln/npm:ua-parser-js:20180227

**Comment by fec-jli** [comment]
Fixed in PR [https://github.com/fecgov/openFEC/pull/3556](https://github.com/fecgov/openFEC/pull/3556)
