### ISSUE TITLE
Check logs Sprint 7.7 Week 3

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3537]
Log review needs to be completed for Sprint 7.7 (week 3) per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by pkfec** [comment]
**Vulnerabilities::**

1) FEC-CMS: 1 Medium issue found in requirements.txt
Cross-site Scripting (XSS)) https://github.com/fecgov/fec-cms/issues/2573

2) OPENFEC : 2 Medium issue found in package.json.
Cross-site Scripting (XSS) https://github.com/fecgov/openFEC/issues/3528
Regular Expression Denial of Service (ReDoS) https://github.com/fecgov/openFEC/issues/3529

3) FEC-EREGS: None
4) FEC-PATTERN-LIBRARY: None

**Search logs::**

1) `bmatheson` user was  added/given access to CMS on December 7th 2018
2) `rfultz ` user was added/given access to CMS on December 13th 2018
3) `kcarothers` was added/given access to CMS on December 11th 2018

**Cloud.gov Dashboard:**

Two new users were given access to cloud.gov this week.
1. qsun.ctr@fec.gov
2. bmatheson@fec.gov

**Comment by pkfec** [comment]
Log review completed for Sprint 7.7 Week 3. Closing this issue.
