### ISSUE TITLE
Check logs Sprint 8.0 (week 1)

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3538]
Log review needs to be completed for Sprint 8.0 (week 1) per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by lbeaufort** [comment]
**Vulnerabilities::**

1) FEC-CMS: 1 existing Medium issue found in requirements.txt (due 2/4 - needs milestone)
Cross-site Scripting (XSS)) https://github.com/fecgov/fec-cms/issues/2573

2) OPENFEC : 2 existing Medium issue found in package.json (due 2/4 - needs milestone)
Cross-site Scripting (XSS) https://github.com/fecgov/openFEC/issues/3528
Regular Expression Denial of Service (ReDoS) https://github.com/fecgov/openFEC/issues/3529

3) FEC-EREGS: None
4) FEC-PATTERN-LIBRARY: None

**Search logs::**

1) `bmatheson` user was  added/given access to CMS on December 7th 2018
2) `rfultz ` user was added/given access to CMS on December 13th 2018
3) `kcarothers` was added/given access to CMS on December 11th 2018
4) `rfultz ` user was given Editor/Moderator status on Dec 13. Confirming this was approved.

**Cloud.gov Dashboard:**

No new users
