### ISSUE TITLE
Check logs Sprint 8.0 (week 2)

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3539]
Log review needs to be completed for Sprint 8.0 (week 2) per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by fec-jli** [comment]
**Vulnerabilities:**

1) FEC-CMS: 1 existing Medium issue found in requirements.txt (due 2/4 - needs milestone)
Cross-site Scripting (XSS)) https://github.com/fecgov/fec-cms/issues/2573

2) OPENFEC : 2 existing Medium issue found in package.json (due 2/4 - needs milestone)
Cross-site Scripting (XSS) https://github.com/fecgov/openFEC/issues/3528
Regular Expression Denial of Service (ReDoS) https://github.com/fecgov/openFEC/issues/3529

3) FEC-EREGS: None
4) FEC-PATTERN-LIBRARY: None


**Search logs:**
no new users are added into fec-accounts


**Cloud.gov Dashboard:**
9 deployers accounts
