### ISSUE TITLE
Increase database performance

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3543]
So that we users can click through on the full election totals on the nationwide raising/spending maps and see the underlying transactions, we should increase database performance to facilitate making a 6-year restriction (rather than 2-year restriction)

iOPs only utilizes around 60% on the database side. It's possible that increasing the application server memory per instance will provide greater performance and stability.

**Completion criteria:**
- [x] Ask @wjiangFEC and @PaulClark2 about funds to increase RDS performance
- [x] Decide amount of additional resources needed to purchase
- [x] Decide what environments we will be applying these additional resources for
- [x] Talk about switching RDS replicas from dev to stage. Or spin up temporary replicas in order to test performance

**Comment by rjayasekera** [comment]
created stage-replica-1 in AWS RDS instance using Terraform.  Setup of this replica is identical to dev-replica-1

**Comment by rjayasekera** [comment]
Change DB instance class of stage-replica-1 from db.r3.2xlarge to db.r3.4xlarge
[https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html)
Now stage-replica-1 has twice as much horsepower than other replicas.  

Instance Class | vCPU1 | ECU2 | Memory3 (GiB) | VPC Only4 | EBS Optimized5 | Max. Bandwidth6 (Mbps) | Network Performance7 | MariaDB | Microsoft SQL Server8 | MySQL | Oracle9 | PostgreSQL10
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
db.r3.4xlarge | 16 | 52 | 122 | No | Yes | 2,000 | High | Yes | Yes8 | Yes | Yes9 | Yes
db.r3.2xlarge | 8 | 26 | 61 | No | Yes | 1,000 | High | Yes | Yes8 | Yes | Yes9 | Yes

- [ ] Next steps are to run most time consuming queries against stage-replica-1 and the same queries against dev-replica-1 and compare the performance measurements.

**Comment by rjayasekera** [comment]
One of the biggest culprit of Individual contributor search query slowness is trying to get a exact count.

Program first try to get an estimated count using:

EXPLAIN SELECT *
FROM disclosure.fec_fitem_sched_a
WHERE disclosure.fec_fitem_sched_a.is_individual = true
AND disclosure.fec_fitem_sched_a.two_year_transaction_period = 2018
AND disclosure.fec_fitem_sched_a.cmte_id IN (‘C00401224’)
AND disclosure.fec_fitem_sched_a.contb_receipt_dt >= date(‘2017-01-01’)
AND disclosure.fec_fitem_sched_a.contb_receipt_dt <= date(‘2018-12-31’)
AND disclosure.fec_fitem_sched_a.contb_receipt_amt >= ‘2000.00’;

```
QUERY PLAN

-------------------------------------------------------------------------------------------------------------------------
 Append  (cost=0.00..1143233.89 rows=316177 width=1437)
   ->  Seq Scan on fec_fitem_sched_a  (cost=0.00..0.00 rows=1 width=5691)
         Filter: (is_individual AND (contb_receipt_dt >= '2017-01-01'::date) AND (contb_receipt_dt <= '2018-12-31'::date)
 AND (contb_receipt_amt >= 2000.00) AND (two_year_transaction_period = '2018'::numeric) AND ((cmte_id)::text = 'C00401224
'::text))
   ->  Index Scan using idx_sched_a_2017_2018_two_year_period_amt_sub_id on fec_fitem_sched_a_2017_2018  (cost=0.57..1143
233.89 rows=316176 width=1437)
         Index Cond: ((two_year_transaction_period = '2018'::numeric) AND (contb_receipt_amt >= 2000.00))
         Filter: (is_individual AND (contb_receipt_dt >= '2017-01-01'::date) AND (contb_receipt_dt <= '2018-12-31'::date)
 AND ((cmte_id)::text = 'C00401224'::text))
(6 rows)

Time: 90.976 ms```

If the above query returns less than 500,000 estimated rows then program will do a exact count


SELECT count(*) AS count_1
FROM (SELECT *
FROM disclosure.fec_fitem_sched_a
WHERE disclosure.fec_fitem_sched_a.is_individual = true
AND disclosure.fec_fitem_sched_a.two_year_transaction_period = 2018
AND disclosure.fec_fitem_sched_a.cmte_id IN ('C00401224')
AND disclosure.fec_fitem_sched_a.contb_receipt_dt >= date('2017-01-01')
AND disclosure.fec_fitem_sched_a.contb_receipt_dt <= date('2018-12-31')
AND disclosure.fec_fitem_sched_a.contb_receipt_amt >= '2000.00') AS anon_1;
count_1
---------
     82
(1 row)

Time: 197151.716 ms  (3.28 min)

Exact result count query takes 3-5 minutes.  So this is the reason it takes 3-5 minutes to display the results.
Before yesterday gunicon server timeout was set at default, which is 30 seconds.  Now  @pat has increased timeout  to 300 seconds (5 min).  So now we get the results without erred  out but takes longer for the first run of the query.  (Not a good/acceptable user experience)
cc @paul

**Comment by rjayasekera** [comment]
Staging database upgraded to more powerful server. Now we should be able to continue with code changes and test performance of multi election cycle contributor search.
https://stage.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=12%2F31%2F2018

**Comment by rjayasekera** [comment]
Temporarily changed application timeout settings in nginx.conf 
  keepalive_timeout 300;
  proxy_connect_timeout 300;
  proxy_read_timeout 300;
[https://github.com/fecgov/fec-proxy/pull/114](https://github.com/fecgov/fec-proxy/pull/114)

**Comment by patphongs** [comment]
Closing in favor of https://github.com/fecgov/openFEC/issues/3580
