### ISSUE TITLE
Remove Schedule A year restriction

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3544]
So that we can provide full election transactions, we should change to greater than 2-year restriction. First choice is to lift the restriction entirely. Plan b is to explore acceptable performance for levels for lifting restrictions.

**Completion criteria:**
- [ ] Take inventory of which endpoints need the changes - we need /schedules/schedule_a/ do any others depend on it though?
**Database changes, if needed**
- [ ] Performance testing - take a baseline. We have some data on schedule_a slow queries.
- [X] What about partitions? Query should work anyway
**Python**
- [ ] Python changes, including additional automated tests. Remove 2-year period as a required field.
- [ ] Data verification step
- [ ] Performance testing - compare to baseline

**Comment by qqss88** [comment]
current api 'ScheduleAByStateRecipientTotals' is based on this material view: ofec_sched_a_aggregate_state_recipient_totals_mv

here is the quick list of fields:
   total = db.Column(db.Numeric(30, 2), index=True, doc='The calculated total.')
    count = db.Column(db.Integer, index=True, doc='Number of records making up the total.')
    cycle = db.Column(db.Integer, index=True, doc=docs.CYCLE)
    state = db.Column(db.String, index=True, doc=docs.STATE_GENERIC)
    state_full = db.Column(db.String, index=True, doc=docs.STATE_GENERIC)
    committee_type = db.Column(db.String, index=True, doc=docs.COMMITTEE_TYPE)
    committee_type_full = db.Column(db.String, index=True, doc=docs.COMMITTEE_TYPE)

**Comment by rjayasekera** [comment]
@qqss88 Staging database upgraded to more powerful server.  You should be able to continue with your code changes and test performance.
[https://stage.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=12%2F31%2F2018](https://stage.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=12%2F31%2F2018)
