### ISSUE TITLE
Extend base cache for API beyond 1 hour

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3545]
Our basic cache for the API is 1 hour - we should consider extending this for performance because the materialized views are only refreshed nightly.

See issue #3237 for the original cache implementation.

**Completion criteria:**
- [x] Test caching headers on `dev` with a manual deploy before and after 5pm ET
- [x] Consider whether we should only do the `within_extra_caching_hours` calculation if we've gotten to that `elif` statement, for performance improvement
- [x] Do a baseline performance test of `stage` with `locust` and browser tools to see load time for a specific query (testing first load)
- [x] Push up caching changes and run another performance test of `stage` and browser tools to see load time for a specific query (testing first load)
- [ ] Test clearing the cache with a redeploy and/or changing the 'Override response headers' setting in the API umbrella

**Comment by lbeaufort** [comment]
After discussing with @fecjjeng and @rjayasekera and confirming the API is [properly caching `GET` requests](https://github.com/fecgov/openFEC/issues/3601), we could make the application longer to improve peformance. 

After the nightly updates run, all the endpoints (except legal/efile/calendar-dates) remain the same all day. We really could extend the cache much longer to improve performance.

We should test the performance of checking when the nightly updates are done, and going off calendar time (the updates finish around 7) and weigh that against accuracy and flexibility.

**Ideas**
- [ ] Test a 16 hour cache starting at 7am ET, then go back to an hour
- [ ] Test checking the database to see when the updates are done (@rjayasekera mentioned a flag for this) and add 16 hours to that, then go back to an hour
- [ ] Test checking celery logs to see when the nightly process finished, and add a 16 hour cache to that, then go back to an hour

**Comment by lbeaufort** [comment]
Update: After thinking about this, we realized that the longest cache we want is 5 hours, because we can't tell the cache when to expire, just how many hours it should be. Illustration: 
![image](https://user-images.githubusercontent.com/31420082/53991312-4bd79f00-40f8-11e9-9be4-82ec6da82d94.png)

**Comment by lbeaufort** [comment]
Massively cooler visualization by @JonellaCulmer:

![image](https://user-images.githubusercontent.com/31420082/54048270-4e450200-41a7-11e9-9fce-dad9acaa1d18.png)

**Comment by lbeaufort** [comment]
After further reflection and reading the docs, we can use a longer cache duration with an Expires header.

**Comment by lbeaufort** [comment]
Thanks for the reminder @rjayasekera I want to test overriding the cache with a "Override response header" setting in the API umbrella

**Comment by JonellaCulmer** [comment]
This is merged, so closing.
