### ISSUE TITLE
Make new /candidates/totals/by_party/by_office endpoint

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3549]
**What we're after:** In order to support the party aggregate totals work, we need to make new 
/candidates/totals/by_party/by_office endpoint. 

**Completion criteria:**
- [x] Identify table that houses the data for receipts and disbursements
- [x] Create endpoint that can provide both receipts and disbursement information
- [x] Determine what data points need to be filterable
- [x] Include additional filter for is_active_candidate
- [x] Compare and make sure the other totals match up

Design work happening here: https://github.com/fecgov/fec-cms/issues/2620

**Comment by fecjjeng** [comment]
A new API named /candidates/totals/by_office/by_party had been created.

**Comment by fecjjeng** [comment]
A new pytest test_candidate_totals_by_office_by_party had been added.
The new endpoint /candidates/totals/by_office/by_party/ had been added to endpoints_walk.

**Comment by fecjjeng** [comment]
Run this new endpoint without specify the party and compared the summary of the result with 
/candidates/totals/by_office/ wth several election_year/office.  The result matched.
