### ISSUE TITLE
Investigate increasing application server memory

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3560]
We need to first increase the memory on our API application instances. Then measure if performance for slow time out calls improve. See previous pg_badger and locust testing spreadsheet for examples of slow queries.

**Completion criteria:**
- [x] Investigate what the memory cap is for our API
- [x] Research cost with cloud.gov for increasing memory for instances
- [x] There are cloudfoundry tools for memory usage over time, consider using this in research
- [x] Take a new baseline before application memory increase
- [x] Record any improvements after memory increase

**Comment by lbeaufort** [comment]
Cloud.gov has some helpful resources on quotas. 

https://cloud.gov/overview/pricing/quotas/

Cloud Foundry also has some plugins for measuring memory usage over time.
https://cloud.gov/docs/apps/limits/#tracking-quota-usage

**Comment by rjayasekera** [comment]
As of now there is no noticeable performance improvement by increasing application memory from 1G to 4G.  (SqlAlchemy return query results by no of display records specified in each page.)
Currently we are using 40G of total memory in our cloud.gov org, fec-beta-fec and our quota is 50G.
