### ISSUE TITLE
Add filter to include only active candidates for /candidates/totals

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3572]
**What we're after:**
To be able to display only active candidates on the raising and spending breakdown charts, we need an active candidate filter on this endpoint: https://api.open.fec.gov/v1/candidates/totals/

**Basic logic:** To decide whether a candidate is active or inactive, we need to look at the candidate election year. And if the candidate inactive table says that the candidate is inactive, it should be filtered out.

**Example API call:** https://api.open.fec.gov/v1/candidates/totals?sort_hide_null=True&cycle=2018&election_full=False&office=P&sort=-receipts&per_page=10&api_key=DEMO_KEY

- [ ] `ofec_candidate_history_MV` has candidate_inactive column added to it. We need to use `candidate_inactive` boolean flag. `false` is active and `true` is inactive. By using the candidate_inactive column combined with the candidate `election_year` will filter out the inactive candidates based on election year.
- [ ] Add the filter option to filter by out inactive candidates. `is_active=true` (this will filter out inactive candidates)
- [ ] Add automated test
- [ ] Spot check the data for active candidates

https://www.fec.gov/data/raising-bythenumbers/

![screen shot 2019-02-21 at 10 49 49 am](https://user-images.githubusercontent.com/12799132/53181914-7d178180-35c6-11e9-8709-02f366da934f.png)

https://www.fec.gov/data/spending-bythenumbers/

![screen shot 2019-02-21 at 10 50 27 am](https://user-images.githubusercontent.com/12799132/53181955-899bda00-35c6-11e9-881b-22675647051d.png)

**Comment by JonellaCulmer** [comment]
This work is complete, so closing.
