### ISSUE TITLE
Data design research for lifting year restriction on transactions

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3574]
What we're after:

In order to lift the year restriction on transactions, we may want to change the dataset we're working with to a smaller set for implementation first. Then work our way up to larger datasets.

**Completion criteria:**
- [ ] Investigate why the query is taking so long. Even with an upgrade to x-large database instance, the improvement is only 2-3 times improvement.
- [ ] There are too many indexes, can we remove any to improve insert time?
- [ ] What are smaller datasets we can target to lift the restriction first
- [ ] Investigate classic site to see how many transactions are within their individual contributions search. And what types of transactions these are. 
- [ ] Investigate possible postgres configuration issues that may be causing slowness (example for ideas: https://severalnines.com/blog/why-postgresql-running-slow-tips-tricks-get-source)

For reference on some possible action items, check this old ticket: https://github.com/fecgov/openfec/issues/3544

**Comment by JonellaCulmer** [comment]
Closing this issue in favor of: https://github.com/fecgov/openFEC/issues/3595
