### ISSUE TITLE
Create state level aggregates

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3575]
**What we are after**: 
State-level aggregates

**Why we are after it**: 
We want to show users top-line summary numbers by state. These aggregates could be used as a entry point to explore data in more detail.

**Completion criteria**:

**Comment by lbeaufort** [comment]
@PaulClark2 can this issue be closed? We have [/schedules/schedule_a/by_state/](https://api.open.fec.gov/developers/#/receipts/get_schedules_schedule_a_by_state_) in the API and the "Where contributions come from" map is live: https://fec.gov/data/raising-bythenumbers/

**Comment by PaulClark2** [comment]
Yes, I think so.
