### ISSUE TITLE
Upgrade RDS instance size

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3580]
In order to increase query performance, we need to upgrade to an XL RDS instance size. @PaulClark2 You have received quotes on the cost of the upgrade, will we be able to implement this increase?

**Comment by lbeaufort** [comment]
After discussing with @LindsayYoung, FEC developer emeritus, we may want to do a performance/cost comparison of increasing our instance sizes vs. adding another read replica. cc: @PaulClark2

**Comment by rjayasekera** [comment]
Upgrade both prod-replica-1 and prod-replica-2 from `db.r3.2xlarge` to `db.r4.8xlarge`
Increase iops from 14,000 to 20,000

**Comment by rjayasekera** [comment]
![image](https://user-images.githubusercontent.com/20324717/54568349-3b071300-49ad-11e9-8b22-c7554de79301.png)

![image](https://user-images.githubusercontent.com/20324717/54568401-638f0d00-49ad-11e9-9472-53b65d960ae4.png)

**Comment by rjayasekera** [comment]
**Before:**
Instance Class
db.r3.2xlarge
Storage Type
Provisioned IOPS (SSD)
IOPS
14000
Storage
2200 GiB

**After:**
Instance Class
db.r4.8xlarge
Storage Type
Provisioned IOPS (SSD)
IOPS
20000
Storage
2200 GiB
