### ISSUE TITLE
PAC "Total Federal Disbursements" returning "null"

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3581]
The API is incorrectly returning `null` for the "Total Federal Disbursements" field in this PAC example (we recently fixed "Operating Expenditures" with [this PR](https://github.com/fecgov/openFEC/pull/3583). 

**Example page:** 
https://www.fec.gov/data/committee/C00344234/?cycle=2018

**API Call:** https://api.open.fec.gov/v1/committee/C00344234/totals/?sort_nulls_last=false&page=1&sort_null_only=false&api_key=DEMO_KEY&sort_hide_null=false&per_page=20&sort=-cycle

<img width="669" alt="screen shot 2019-03-01 at 1 25 20 pm" src="https://user-images.githubusercontent.com/31420082/53657991-a454fb00-3c25-11e9-9dc9-d04c35a27f2e.png">

**Comment by PaulClark2** [comment]
@patphongs I'll look at this more closely but a null financial value returned from the API **should** display as `NONE` on the front-end.

**Comment by PaulClark2** [comment]
Looks like there's something else going on here. @jwchumley  is investigating.

**Comment by lbeaufort** [comment]
@PaulClark2 @jwchumley  I think this might be an API bug - here's an example of a PAC that I think should have a value for  "Total Federal Disbursements". Do you mind taking a look?

https://www.fec.gov/data/committee/C00344234/?cycle=2018

https://api.open.fec.gov/v1/committee/C00344234/totals/?sort_nulls_last=false&page=1&sort_null_only=false&api_key=DEMO_KEY&sort_hide_null=false&per_page=20&sort=-cycle

**Comment by PaulClark2** [comment]
@lbeaufort yes, this committee should have a value for total disbursements and total operating expenditures. 
![image](https://user-images.githubusercontent.com/11817734/53650584-e0cb2b80-3c12-11e9-8799-a3bcb0420f77.png)

This is probably a similar problem as the operating expenditure problem in #3582

**Comment by fecjjeng** [comment]
In the parent MV ofec_totals_combined_mv, the source for fed_disbursements is fed_funds_per column in disclosure.v_sum_and_det_sum_report.
     sum(vsd.fed_funds_per) AS fed_disbursements
@PaulClark2 @jwchumley Is there another column we should use instead of fed_funds_per for F3X filer?
