### ISSUE TITLE
Operating expenditures wrong on committee profile page

### ISSUE THREAD

**Issue by jwchumley** [fecgov/openFEC#3582]
https://www.fec.gov/data/committee/C00011262/

The value for operating expenditures is incorrect here and also on other form 3X filing committees I've looked at.  The ofec_totals_combined_mv is using only the op_exp_per column which works for form 3 and 3p but form 3x needs to use the ttl_op_exp_per column. I believe this change will solve the problem:

in ofec_totals_combined_mv, change this line:

sum(vsd.op_exp_per)

to this line (or it's functional equivalent)ncase when vsd.form_tp_cd = 'F3X' then sum(vsd.ttl_op_exp_per) else sum(vsd.op_exp_per) end  operating_expenditures,

@rjayasekera

**Comment by patphongs** [comment]
Closing, this has been fixed in PR https://github.com/fecgov/openFEC/pull/3583
