### ISSUE TITLE
[Split into multiple issues] Make endpoints to calculate "other spending" (IE/EC/CC) totals

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3587]
While investigating [this bug](https://github.com/fecgov/fec-cms/pull/2702
), I discovered that we calculate "other spending" totals on the front-end side, using JavaScript.  We should make endpoints to calculate these totals rather than calculating them on the front-end, for consistency and performance improvement.

Example: https://www.fec.gov/data/candidate/P80001571/?tab=other-spending

![Screen Shot 2019-09-19 at 11 22 21 AM](https://user-images.githubusercontent.com/12799132/65257723-a7cfa700-dacf-11e9-9ff2-9b5947795205.png)

- [ ] Research data needs for IE/EC/CC totals
- [ ] Make endpoints for these totals - Independent Expenditures, Electioneering Communications, Communication Costs
- [ ] Add automated tests
- [ ] Make front-end ticket to use these endpoints

**Comment by PaulClark2** [comment]
closing in favor of 
https://github.com/fecgov/openFEC/issues/4061
https://github.com/fecgov/openFEC/issues/4062
https://github.com/fecgov/openFEC/issues/4063
