### ISSUE TITLE
Problem with candidate profile page party affiliation

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3592]
Julian Castro shows has filed as "Democratic Party" on both his 2018 and 2019 form 2 filings. However, when selecting the 2017-2018 cycle to view, his party affiliation says `None`. But when switching to his 2019-2020 cycle, it displays as Democratic party. And when showing full cycle, it shows as democratic party. We need to investigate why these are inconsistent.

https://www.fec.gov/data/candidate/P00009092/

### API calls:

- **Display 2020 full cycle:** https://api.open.fec.gov/v1/candidate/P00009092/history/2020?per_page=1&election_full=True&api_key=NICAR16
- **Display 2017-2018 two year period:** https://api.open.fec.gov/v1/candidate/P00009092/history/2018?per_page=1&election_full=False&api_key=NICAR16
- **Display 2019-2020 two year period:** https://api.open.fec.gov/v1/candidate/P00009092/history/2020?per_page=1&election_full=False&api_key=NICAR16

**Comment by lbeaufort** [comment]
I confirmed this issue is fixed. Thanks @jwchumley and @patphongs !
