### ISSUE TITLE
Remove the two-year restriction from the API and test performance

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#3595]
**User story:** As an API user, I need to be able to pull data across more than one two year time period so that I can better understand the full picture of money raised and spent by committees and other filers.

**What we're after:** In order to move forward with our need to remove the 2-year restriction, we are going to attempt to remove the restriction from the API and test the performance. The staging replicas are currently running on xl instance size. 

**What does success look like?**
We need to define what success looks like, what's the performance threshold to remove 2 year restriction? We don't want to negatively impact database performance with having

**Completion criteria:**
- [ ] We are concentrating on these transactional schedules: 
   - [x] `/schedules/schedule_a/`
   - [x] `/schedules/schedule_b/`
   - ~~[ ] `/schedules/schedule_e/`~~
- [ ] Perform and document a locust baseline test of each schedule listed above on stage with 2 year restriction applied (no code change)
- [ ] Perform and document a locust test with the restriction removed of each schedule listed above from the API (change API code to remove restriction for this test)
- [ ] If successful, create a new ticket to remove the restriction from the CMS

api testing summary uploaded here:
https://drive.google.com/drive/u/0/folders/1nv1qJZ7T8WXYqb5MrfYtLldjNYkPrseZ

Quick conclusions from the testings:
- We only need to consider removing 2-year restriction on schedule_a and scheule_b, ~~schedule_e~~ loading performance is decent and we do not have 2-year restriction on it
- If the api call can take advantage of both partitioning and indexing-scan, the data loading speed is decent.
- Cross-partitions Range only query(min_date, max_date, min_amount, max_amount etc) could be very slow(could be 20-30 minutes, sometime got internal errors)
- Range query + indexing_scan filtering(committee_id, or contributor_state etc) could speed up things a lot.
- Query on old transaction data is usually slow: data table vacuum issue?

Recommendations:
- For CMS api calls, I think it is safe to remove 2-year restriction on committee_single.js, candidate_single.js calls, removing restriction on Datatable-receipts.js api calls(range_query + sorting) will load two much data and the performance is not there yet(and it does not make lot of sense)

- we probably still want to put on a restriction on cycles(3 is good for a full election cycle) for each api call. Some api calls are still very slow and relaxing too much may introduce more performance issues related to schedule_a and schedule_b query.

- considering the data amount we have for schedule_a and schedule_b, I also suggest to split schedule_a and schedule_b api into smaller APIs with careful design so that we have better control/restrictions and minimize the amount of slow queries.

Some factors for sql query performance :
1. partitioning vs non-partitioning query
2. index scan vs datatable sequential scan
3. query caching and query execution plan caching(buffer read vs buffer hit) 
4. Small query vs large query: query result row number count
5. Range query is usually slow.

Here is a quick list of related API calls from CMS:
CMS schedule_a api calls:

1.
committee_single.js:
            query: {
              committee_id: committeeId,
              two_year_transaction_period: cycle,
              is_individual: true
            },

2.
candidate_single.js:
query: {
      committee_id: opts.committee_id,
      two_year_transaction_period: opts.cycle
    },

3. 
Datatable-receipts.js:
Query:{
 Max_date: XXXX
Min_date: XXXX
Two_year_transaction_period: cycle
}

other discoveries / issues:
1. A locustfile.py bug fixed:
schedule_a problematic data date format is wrong - that explains why those api call always fail.

2. I also found that receipt date does not go hand with hand with transaction year:

http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2018&is_individual=true&two_year_transaction_period=2016&sort_null_only=false&min_amount=500&contributor_state=NY&contributor_state=CA

receipt date: 1/1/2018 - 12/31/2018
2-year trsaction period: 2016
count: 1

http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2018&is_individual=true&two_year_transaction_period=2020&sort_null_only=false&min_amount=500&contributor_state=NY&contributor_state=CA

receipt date: 1/1/2018 - 12/31/2018
2-year trsaction period: 2020
count: 126

based on discussion with Paul, this could be some raw filing errors. I'll dig a little more on this issue when I got time.

**Comment by qqss88** [comment]
need to connect new issue 
https://github.com/fecgov/FEC/issues/8813
to this one.

**Comment by qqss88** [comment]
basic measurements on prod:

curltime 'https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=NICAR16'
time_namelookup:  0.134462
       time_connect:  0.148478
    time_appconnect:  0.214146
   time_pretransfer:  0.214172
      time_redirect:  0.000000
 time_starttransfer:  0.471504
                    ----------
         time_total:  0.509203
curltime 'https://api.open.fec.gov/v1/schedules/schedule_b/?api_key=NICAR16'
time_namelookup:  0.004132
       time_connect:  0.031999
    time_appconnect:  0.108311
   time_pretransfer:  0.108400
      time_redirect:  0.000000
 time_starttransfer:  0.280808
                    ----------
         time_total:  0.318908

curltime 'https://api.open.fec.gov/v1/schedules/schedule_c/?api_key=NICAR16'
time_namelookup:  0.065445
       time_connect:  0.085122
    time_appconnect:  0.168770
   time_pretransfer:  0.168882
      time_redirect:  0.000000
 time_starttransfer:  0.345204
                    ----------
         time_total:  0.378358

curltime 'https://api.open.fec.gov/v1/schedules/schedule_d/?api_key=NICAR16'
time_namelookup:  0.005079
       time_connect:  0.029009
    time_appconnect:  0.114042
   time_pretransfer:  0.114132
      time_redirect:  0.000000
 time_starttransfer:  2.497074
                    ----------
         time_total:  2.533253

curltime 'https://api.open.fec.gov/v1/schedules/schedule_e/?api_key=NICAR16'
time_namelookup:  0.005121
       time_connect:  0.032020
    time_appconnect:  0.106041
   time_pretransfer:  0.106133
      time_redirect:  0.000000
 time_starttransfer:  10.295011
                    ----------
         time_total:  10.346377

**Comment by qqss88** [comment]
this request takes 1885615 ms to come back:

http://127.0.0.1:5000/v1/schedules/schedule_a/?max_amount=500&sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2016&sort=contribution_receipt_date&is_individual=true&sort_null_only=false

**Comment by qqss88** [comment]
this one takes 2896423 ms:
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2016&sort=contribution_receipt_date&is_individual=true&sort_null_only=false&min_amount=500

**Comment by qqss88** [comment]
577387 ms for this schedule_b  one:
http://127.0.0.1:5000/v1/schedules/schedule_b/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2016&is_individual=true&sort_null_only=false&min_amount=500

**Comment by qqss88** [comment]
9045ms for this one:
http://127.0.0.1:5000/v1/schedules/schedule_b/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2010&is_individual=true&sort_null_only=false&min_amount=500

**Comment by qqss88** [comment]
1406948 ms
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2002&is_individual=true&sort_null_only=false&min_amount=500

**Comment by qqss88** [comment]
368664ms:
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2018&is_individual=true&sort_null_only=false&min_amount=500

**Comment by qqss88** [comment]
612 ms:
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2018&is_individual=true&two_year_transaction_period=2018&sort_null_only=false&min_amount=500

**Comment by qqss88** [comment]
595 ms:
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2018&is_individual=true&two_year_transaction_period=2018&sort_null_only=false&min_amount=500

16836 ms
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2018&is_individual=true&two_year_transaction_period=2018&sort_null_only=false&min_amount=500&two_year_transaction_period=2016

15162 ms:
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2018&is_individual=true&two_year_transaction_period=2018&sort_null_only=false&min_amount=500&two_year_transaction_period=2016&two_year_transaction_period=2014

**Comment by qqss88** [comment]
time: 1942 ms
count: 503857
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2014&is_individual=true&two_year_transaction_period=2018&sort_null_only=false&min_amount=1000&two_year_transaction_period=2016&two_year_transaction_period=2014&contributor_state=CA

time: 621
count: 804669
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2014&is_individual=true&two_year_transaction_period=2018&sort_null_only=false&min_amount=500&two_year_transaction_period=2016&two_year_transaction_period=2014&contributor_state=CA

time: 727 ms
count: 840344
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2014&is_individual=true&two_year_transaction_period=2018&sort_null_only=false&min_amount=400&two_year_transaction_period=2016&two_year_transaction_period=2014&contributor_state=CA

count: 420758
time: 159183
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F30%2F2014&is_individual=true&two_year_transaction_period=2018&sort_null_only=false&min_amount=300&two_year_transaction_period=2016&two_year_transaction_period=2014&contributor_state=NY

time: 10761
Count: 381315
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=2%2F20%2F2014&is_individual=true&two_year_transaction_period=2018&sort_null_only=false&min_amount=400&two_year_transaction_period=2016&two_year_transaction_period=2014&contributor_state=NY

**Comment by qqss88** [comment]
time: 120997
count: 190518
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2010&api_key=DEMO_KEY&min_date=2%2F20%2F2008&is_individual=true&two_year_transaction_period=2008&sort_null_only=false&min_amount=400&two_year_transaction_period=2010&contributor_state=NY

count: 210083
time: 14167
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2010&api_key=DEMO_KEY&min_date=2%2F20%2F2008&is_individual=true&two_year_transaction_period=2008&sort_null_only=false&min_amount=300&two_year_transaction_period=2010&contributor_state=NY

time: 85040 ms
count: 655809
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2010&api_key=DEMO_KEY&min_date=2%2F20%2F2008&is_individual=true&sort_null_only=false&min_amount=300&contributor_state=NY&contributor_state=CA

**Comment by qqss88** [comment]
without partitioning:
time: 184378
count: 1189997
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=10%2F31%2F2018&api_key=DEMO_KEY&min_date=2%2F20%2F2014&is_individual=true&two_year_transaction_period=2018&sort_null_only=false&min_amount=500&two_year_transaction_period=2016&two_year_transaction_period=2014&contributor_state=NY&contributor_state=CA

with partitioning:
time: 16707
count: 1185808
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=2%2F28%2F2014&is_individual=true&two_year_transaction_period=2018&sort_null_only=false&min_amount=500&two_year_transaction_period=2016&two_year_transaction_period=2014&contributor_state=NY&contributor_state=CA
