### ISSUE TITLE
Research/test pinning kombu version

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3608]
Celery 4.1.1 depends on `kombu >=4.2.0,<5.0`. Kombu's breaking changes in minor upgrades have bitten us hard, twice. (See https://github.com/fecgov/openFEC/issues/3607 and  https://github.com/fecgov/openFEC/pull/3151/commits/f83ae22c133b9c6983aa375e0d54eac3946f6d97)

Kombu [doesn't seem to follow semantic versioning](https://github.com/celery/kombu/issues/1016#issuecomment-469412793). From another `celery` user: 

>“It would seem that you want people to pin specific versions of kombu when using celery. That’s something that I will be doing in the future as kombu changes have included breaking changes outside of major version releases.”

We should research/test pinning `kombu` versions in our requirements file to see if that will force celery to use that version. 

**Completion criteria**
- [x] Try pinning `kombu==4.3.0` in requirements.txt
- [x] Do a fresh `pip install -r requirements.txt`
- [x] Do a `pip freeze` to see what version of `kombu` in in your environment - `celery 4.1.1` would normally grab `kombu` 4.4.0 but we want to ensure that pinning at `4.3.0` actually works.
- [x] If this works, add a comment to the `celery` line in requirements.txt that if we update `celery` we should check which version(s) of `kombu` will work, and pin the right version.

**Comment by jason-upchurch** [comment]
- [x] Try pinning `kombu==4.3.0` in requirements.txt
```
Installing collected packages: kombu
  Found existing installation: kombu 4.5.0
    Uninstalling kombu-4.5.0:
      Successfully uninstalled kombu-4.5.0
Successfully installed kombu-4.3.0
```

**Comment by jason-upchurch** [comment]
updated requirements.txt with comment on celery to check kombu version compatibility.

**Comment by pkfec** [comment]
@jason-upchurch Could you submit a pull request and have someone review your changes?
