### ISSUE TITLE
Totals for John Delaney incorrect on election profile page(/elections/)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3611]
Checking: P00006213, DELANEY, JOHN K.

datatable_url
https://api.open.fec.gov/v1/candidates/totals/?candidate_id=P00006213&election_year=2020&full_election=true&api_key=3WFCX5yqR4ZQmRKkQemdZVKEebxwWHQ6MPVc40l9&sort=-receipts

candidate_profile_url
https://api.open.fec.gov/v1/candidate/P00006213/totals/?cycle=2020&full_election=true&api_key=3WFCX5yqR4ZQmRKkQemdZVKEebxwWHQ6MPVc40l9

election_profile_url
https://api.open.fec.gov/v1/elections/?candidate_id=P00006213&cycle=2020&election_full=true&api_key=3WFCX5yqR4ZQmRKkQemdZVKEebxwWHQ6MPVc40l9&office=president&sort_nulls_last=true&sort=-total_receipts&per_page=100

!!! ERROR - results don't match!!!
Candidate datatable: 6145779.44
Candidate profile page: 6145779.44
**Election profile page: 5874365.79**

!!! ERROR - results don't match!!!
Candidate datatable: 5899574.2
Candidate profile page: 5899574.2
**Election profile page: 5660142.67**

***May become a bigger problem as more people start to/continue to report going into 2020. Affects candidates (likely high profile candidates) who convert their committees.***

**Completion criteria:**
- [x] Look at how the totals are calculated for the /totals/ endpoint
- [x] For Presidential candidates, make sure totals are including information from form 3 and 3P

**Comment by PaulClark2** [comment]
**Correct**: 
Includes both F3 and F3P financial data (candidate converted his House committee to his presidential committee)
datatable_url
https://api.open.fec.gov/v1/candidates/totals/?candidate_id=P00006213&election_year=2020&full_election=true&api_key=3WFCX5yqR4ZQmRKkQemdZVKEebxwWHQ6MPVc40l9&sort=-receipts

candidate_profile_url
https://api.open.fec.gov/v1/candidate/P00006213/totals/?cycle=2020&full_election=true&api_key=3WFCX5yqR4ZQmRKkQemdZVKEebxwWHQ6MPVc40l9

Candidate profile page: https://www.fec.gov/data/candidate/P00006213/
total receipts $6,145,779.44; total disbursements $5,899,574.20


**Incorrect**: 
seems to only include F3P financial data

election_profile_url
https://api.open.fec.gov/v1/elections/?candidate_id=P00006213&cycle=2020&election_full=true&api_key=3WFCX5yqR4ZQmRKkQemdZVKEebxwWHQ6MPVc40l9&office=president&sort_nulls_last=true&sort=-total_receipts&per_page=100

Election profile page: https://www.fec.gov/data/elections/president/2020/
total receipts $5,874,365.79; total disbursements $5,660,142.67

FORM_TP_CD	|	RPT_YR	|	RPT_TP	|	TTL_RECEIPTS	|	TTL_DISB	|
----	|	----	|	----	|	----	|	----	|
F3	|	C00508416	|	Q1	|	$83,825.05	|	$40,469.30	|
F3	|	C00508416	|	Q2	|	$187,588.60	|	$198,962.23	|
F3P	|	C00508416	|	Q3	|	$577,085.53	|	$318,036.53	|
F3P	|	C00508416	|	YE	|	$647,299.54	|	$580,931.31	|
F3P	|	C00508416	|	Q1	|	$2,173,151.75	|	$1,722,890.44	|
F3P	|	C00508416	|	Q2	|	$240,167.48	|	$915,614.48	|
F3P	|	C00508416	|	Q3	|	$1,088,448.44	|	$1,164,848.39	|
F3P	|	C00508416	|	YE	|	$1,148,213.05	|	$957,821.52	|


.	|	TTL_RECEIPTS	|	TTL_DISB	|
----	|	----	|	----	|
Total	|	$6,145,779.44	|	$5,899,574.20	|
F3 only	|	$271,413.65	|	$239,431.53	|
F3P only 	|	$5,874,365.79	|	$5,660,142.67	|


It looks like the election profile endpoint/page is excluding F3 data that it shouldn't. @lbeaufort would @hcaofec 's F3/F3P/F3X table help here? @hcaofec what's the status of that combined table?

**Comment by lbeaufort** [comment]
@PaulClark2 I also found that the candidate data table has the wrong COH for Delaney. I'm thinking this should be a separate issue because it's a different endpoint that appears to be correct.

!!! ERROR - COH results don't match!!!
Candidate datatable: 	$536,496.16
Candidate profile page:  $268,248.08
Election profile page: 	$268,248.08

**Comment by JonellaCulmer** [comment]
^^ The above work was moved to a separate ticket here: https://github.com/fecgov/openFEC/issues/3635

**Comment by hcaofec** [comment]
Here is another example because F3 was filed.  FULLER, REV VERONICA RONNIE, P00006684

receipts:
Candidate datatable: 749
Candidate profile page: 749
Election profile page: 0

disbursements:
!!! ERROR - results don't match!!!
Candidate datatable: 549
Candidate profile page: 549
Election profile page: 0

**Comment by hcaofec** [comment]
Another example: S0KS00190 , ADAMS, ELLIOTT, cand_election_year = 2020

**Comment by hcaofec** [comment]
Totals is also wrong on Delaney's committee profile page:
https://www.fec.gov/data/committee/C00508416/

https://api.open.fec.gov/v1/totals/presidential/?api_key=DEMO_KEY&per_page=20&sort_hide_null=false&committee_id=C00508416&sort_nulls_last=false&sort=-cycle&sort_null_only=false&page=1

https://api.open.fec.gov/v1/committee/C00508416/totals/?api_key=DEMO_KEY&per_page=20&sort_hide_null=false&sort_nulls_last=false&sort=-cycle&sort_null_only=false&page=1

The above three have:
"receipts": 5874365.79,
"disbursements": 5660142.6699999999,
"last_cash_on_hand_end_period": 268248.08,

@lbeaufort  @PaulClark2
