### ISSUE TITLE
Replace pathlib with pathlib2

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#3612]
`pathlib` library is no longer maintained. Replace it with `pathlib2`.

**Problem:** 
`pathlib` is a dependency library of `openapi-spec-validator` or `OSV`. The recent update on OSV library indicates that pathlib is replaced with pathlib2. This breaking change impacted our Python tests(**pytest**)  in both circleci and in local development environments. pytest are failing with INTERNAL ERROR as shown in the stack trace below. 

More info on pathlib here : https://pypi.org/project/pathlib/ 

**Fix/Resolution:**
Install the newer version of pathlib2. Make sure the python tests run OK

**pytest error stack trace**: 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/_pytest/main.py", line 174, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/_pytest/config/__init__.py", line 593, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/pluggy/hooks.py", line 311, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/_pytest/cacheprovider.py", line 292, in pytest_configure
INTERNALERROR>     config.cache = Cache.for_config(config)
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/_pytest/cacheprovider.py", line 40, in for_config
INTERNALERROR>     cachedir = cls.cache_dir_from_config(config)
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/_pytest/cacheprovider.py", line 48, in cache_dir_from_config
INTERNALERROR>     return paths.resolve_from_str(config.getini("cache_dir"), config.rootdir)
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/_pytest/paths.py", line 7, in resolve_from_str
INTERNALERROR>     root = Path(root)
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/pathlib.py", line 936, in __new__
INTERNALERROR>     self = cls._from_parts(args, init=False)
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/pathlib.py", line 613, in _from_parts
INTERNALERROR>     drv, root, parts = self._parse_args(args)
INTERNALERROR>   File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/heljen/lib/python3.6/site-packages/pathlib.py", line 605, in _parse_args
INTERNALERROR>     % type(a))
INTERNALERROR> TypeError: argument should be a path or str object, not <class 'py._path.local.LocalPath'>

**Completion criteria**
- [x] Unpack package and run tests.
- [x] Add Swagger tests back.

**Comment by dorothyyeager** [comment]
Waiting on 3rd party package to get updated.

**Comment by pkfec** [comment]
PR #3851  is ready to be merged. Thanks @fec-jli for reviewing this PR.
