### ISSUE TITLE
Raw efiling data improvements

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#3627]
**What we're after:** We need to develop an overall strategy. 

**Completion criteria:**
- [ ] Determine overall strategy for work we can tackle in PI 9.

Raw vs. processed filters documentation: https://docs.google.com/document/d/16DWIquTYpbdtCCDrXYLXXRrHQXS51sX_8cLY75spLA0/edit

**Comment by PaulClark2** [comment]
I've asked the contracting office to cancel the New Relic request for quotes. We have decided to use Pingdom. Pingdom is a Solarwinds product.

**Comment by PaulClark2** [comment]
Closing in favor of IE de-duping work prioritized for PI 9
