### ISSUE TITLE
ofec_candidate_history_with_future_election_mv need to be refreshed before ofec_candidate_totals_mv

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3632]
Sequence of materialized views refresh are not correct for the following two MVs:
ofec_candidate_history_with_future_election_mv
ofec_candidate_totals_mv

ofec_candidate_totals_mv depends on ofec_candidate_history_with_future_election_mv.  Therefore ofec_candidate_history_with_future_election_mv needs to be refreshed first.

[] update flow.py to put the sequence into correct order.

**Comment by fecjjeng** [comment]
During an effort to drop/recreate the ofec MVs in our local server, I noticed the sequence of MV creation is out of order for the above two MVs.  Since my drop/recreate script is based on the refresh sequence, I went back to double check the manage.py and flow.py files, which controls the sequence of MVs and realized the refresh sequence is incorrect for these two MVs.

**Comment by PaulClark2** [comment]
Thanks @fecjjeng
