### ISSUE TITLE
Query against processed sched tables should use two_year_transaction_period instead of re-calculated in the query

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3634]
The fec_fitem_sched_tables already have two_year_transaction_period column, which is the partition key of the huge fec_fitem_sched_a and fec_fitem_sched_b tables.  It is calculated based on rpt_yr + rpt_yr % 2.  The current code re-calculate the it again in the query, which slowed down the query.

**Comment by lbeaufort** [comment]
Thank you @fecjjeng ! Here's what I found:

### With % calculated join
```
explain analyze (SELECT *
FROM disclosure.fec_fitem_sched_a 
LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_1 
    ON disclosure.fec_fitem_sched_a.clean_contbr_id = ofec_committee_history_mv_1.committee_id 
    AND disclosure.fec_fitem_sched_a.rpt_yr + disclosure.fec_fitem_sched_a.rpt_yr % 2 = ofec_committee_history_mv_1.cycle 
LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_2 ON disclosure.fec_fitem_sched_a.cmte_id = ofec_committee_history_mv_2.committee_id AND disclosure.fec_fitem_sched_a.rpt_yr + disclosure.fec_fitem_sched_a.rpt_yr % 2 = ofec_committee_history_mv_2.cycle 
WHERE disclosure.fec_fitem_sched_a.two_year_transaction_period = 2000 AND disclosure.fec_fitem_sched_a.contb_receipt_amt >= 2.10
)
```
rows=1679507
Planning time: 690.704 ms                                                          
Execution time: 13282.618 ms   

### With two-year transaction period
```
 explain analyze (SELECT *
FROM disclosure.fec_fitem_sched_a 
LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_1 
    ON disclosure.fec_fitem_sched_a.clean_contbr_id = ofec_committee_history_mv_1.committee_id 
    AND disclosure.fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_1.cycle 
LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_2 ON disclosure.fec_fitem_sched_a.cmte_id = ofec_committee_history_mv_2.committee_id AND disclosure.fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_2.cycle 
WHERE disclosure.fec_fitem_sched_a.two_year_transaction_period = 2000 AND disclosure.fec_fitem_sched_a.contb_receipt_amt >= 2.10
)
```
rows=1679507
Planning time: 5.594 ms                                                     
Execution time: 5863.703 ms

**Comment by fecjjeng** [comment]
Yes, I thought we already changed it while doing the CMTE_TP work.  But apparently missed it.  Will update the code accordingly.

**Comment by fecjjeng** [comment]
There are two join to the ofec_committee_history_mv tables.  The existing code are using different methods to make the join.  One of them inherited from the base itemized model and the other use regular db.relationship.  I need to override the inherited one in the sched_a and sched_b model by either modify the call the utils function, or changed it to use the db.relationship.  I choose to use the db.relationship to make them more consistent.

**Comment by JonellaCulmer** [comment]
This is merged, so closing.
