### ISSUE TITLE
Research: Reduce the number of our celery workers

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3637]
The celery-worker app is only being used in the `/download/` endpoint. We would like to decrease the number of celery-worker apps in order spread out the impact on the database. If celery-worker apps are decreased, this will cause a larger queue in Redis. At this point, we are unsure how much additional load Redis can take. If Redis goes down, that can impact our data performance as well.

**Completion criteria:**
- [x] Investigate why we increased the number of celery-workers in production (Look at past post-mortems and github issues)

I checked all related issues but did not get a defined answer on why we set up 6 worker instances in production. Based on previous discussion from 18f developers, it seems like the download efficiency is not very good(around 3 minutes for 500k schedule_a data) due to mashmallow serialization. More worker instances will help ensure download efficiency.

- [x] Update the staging environment with the same number of celery-workers as production. Locust test and log results

download api locust test added to locust file. Because celery is a async pipeline, locust tests itself does not reflect how efficient celery is working. I am adding some logs data from the worker logs. It'll be much easier if we have a flower monitoring session in place and we can collect much better data on this.

- [x] Start reducing the number of celery-workers one by one in staging. Locust test and log results. 

will upload the spread sheet of locust test results on different worker instances on STG.

Other works done:
1. other parameters we can use to restrain celery and slow down the pipeline:
- time limit
- rate limit
- prefetch limit
Pls refer the uploaded demo slides for more details:
https://drive.google.com/file/d/1BA3HSK9QHJ0qPAUNP0fPfF65E2v1Y7JP/view?usp=sharing

swarming test quick summary:
1. the download task is relative minor, usually takes <3min to process
2. more workers, faster task queueing time and processing speed
3. based on current swarming test config, no big differences observed after >=3 worker instances.
4. strongly suggest to install flower for better celery monitoring.

Here is the link for swarming test result:
https://drive.google.com/file/d/1bSRsj8BrtawMmpbqivpzrxfjT1g63NSn/view?usp=sharing

**Comment by qqss88** [comment]
check into those links and resources:

https://stackoverflow.com/questions/31898311/celery-difference-between-concurrency-workers-and-autoscaling

https://medium.com/@taylorhughes/three-quick-tips-from-two-years-with-celery-c05ff9d7f9eb

https://theblog.workey.co/my-experiences-with-a-long-running-celery-based-microprocess-b2cc30da94f5

**Comment by qqss88** [comment]
celery worker config on different tiers:

DEV(openFEC/manifests/manifest_celery_worker_dev.yml)
applications:
  - name: celery-worker
    instances: 2
    memory: 1G
    no-route: true
    health-check-type: process
    command: celery worker --app webservices.tasks --loglevel ${LOGLEVEL:=INFO} --concurrency 2

STG(openFEC/manifests/manifest_celery_worker_stage.yml):
  - name: celery-worker
    instances: 1
    memory: 1G
    no-route: true
    health-check-type: process
    command: celery worker --app webservices.tasks --loglevel ${LOGLEVEL:=INFO} --concurrency 2

PRD(openFEC/manifests/manifest_celery_worker_prod.yml):
  - name: celery-worker
    instances: 6
    memory: 1G
    disk_quota: 2G
    no-route: true
    health-check-type: process
    command: celery worker --app webservices.tasks --loglevel ${LOGLEVEL:=INFO} --concurrency 3

Summary:
dev: worker instance 2, concurrency 2
stg: worker instance 1, concurrency 2
prd: worker instance 6, concurrency 3

other factors can be used to restrain celery:
connection_pool_limit
task_time_out(soft, hard)
task_rate_limit(how many tasks processed/min)

**Comment by qqss88** [comment]
See this link for some general recommendations on worker number and concurrency number setup:
- one worker per machine
- concurrency = cores of the CPU

**Comment by qqss88** [comment]
curl 'https://api.open.fec.gov/v1/download/schedules/schedule_a/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=false&sort_nulls_last=false&two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=01%2F01%2F2017&sort=-contribution_receipt_date&is_individual=true' -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Origin: https://www.fec.gov' -H 'Referer: https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=01%2F01%2F2017' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36' -H 'Access-Control-Request-Headers: content-type' --compressed

**Comment by qqss88** [comment]
need to make a locust file test with json data passed in - filename for download api. refer to this link for some examples:

https://github.com/locustio/locust/issues/157

**Comment by qqss88** [comment]
curl -d "filename=test.csv" -X POST http://127.0.0.1:5000/v1/download/schedules/schedule_a?sort_hide_null=False&sort_nulls_last=False&two_year_transaction_period=2018&min_date=01%2F01%2F%2F2017&max_date=01%2F02%2F%2F2017&sort=-contribution_receipt_date&is_individual=True

**Comment by pkfec** [comment]
@qqss88 are you running locust tests against `stage` api with one instance of celery worker? Which other env are you running the tests against to compare the results with `stage`? Could you add your findings in a spreadsheet or create a table here and upload the results?

**Comment by qqss88** [comment]
@pkfec I am changing the worker instance number and doing some locus swarming tests collect some data from cf logs. I'll put up an excel file. If we have a flower session(https://flower.readthedocs.io/en/latest/) in pace, it'll be much easier to monitor celery and collect more meaningful/quality data. we can open a ticket on this.
