### ISSUE TITLE
Identify slow queries and performance tuning

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3641]
On daily basis we will monitor Kibana logs to identify user queries that are taking longer to run.  From that list we will pick  a query that users are running often, try to find the cause for the slowness and find a solution for it.  

This issue ticket is ongoing and we will deal with one query at at time.

**Comment by rjayasekera** [comment]
Query from Kibana log - 20190319
/v1/schedules/schedule_a/?sort_hide_null=false&sort_nulls_last=false&contributor_name=Vandemoer&contributor_name=Vavic&two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=12%2F31%2F2018&sort=-contribution_receipt_date&per_page=30&is_individual=true 

https://api-stage.open.fec.gov/v1/schedules/schedule_a/?sort_hide_null=false&sort_nulls_last=false&contributor_name=Vandemoer&contributor_name=Vavic&two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=12%2F31%2F2018&sort=-contribution_receipt_date&per_page=30&is_individual=true&api_key=DEMO_KEY

select * 
FROM disclosure.fec_fitem_sched_a LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_1 ON disclosure.fec_fitem_sched_a.clean_contbr_id = ofec_committee_history_mv_1.committee_id AND disclosure.fec_fitem_sched_a.rpt_yr + disclosure.fec_fitem_sched_a.rpt_yr %% %(rpt_yr_1)s = ofec_committee_history_mv_1.cycle LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_2 ON disclosure.fec_fitem_sched_a.cmte_id = ofec_committee_history_mv_2.committee_id AND disclosure.fec_fitem_sched_a.rpt_yr + disclosure.fec_fitem_sched_a.rpt_yr %% %(rpt_yr_2)s = ofec_committee_history_mv_2.cycle 
WHERE disclosure.fec_fitem_sched_a.is_individual = true AND disclosure.fec_fitem_sched_a.contb_receipt_dt >= %(contb_receipt_dt_1)s AND disclosure.fec_fitem_sched_a.contb_receipt_dt <= %(contb_receipt_dt_2)s AND (disclosure.fec_fitem_sched_a.contributor_name_text @@ to_tsquery(%(contributor_name_text_1)s) OR disclosure.fec_fitem_sched_a.contributor_name_text @@ to_tsquery(%(contributor_name_text_2)s)) AND disclosure.fec_fitem_sched_a.two_year_transaction_period = %(two_year_transaction_period_1)s

**Comment by JonellaCulmer** [comment]
Closing this ticket in favor of regular slow query check-in ticket, here: https://github.com/fecgov/openFEC/issues/3664
