### ISSUE TITLE
[Med] Snyk: Race Condition (due 5/20/19)

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3642]
**Vulnerable module:** webargs
Introduced through: webargs@0.18.0 and flask-apispec@0.7.0

**Detailed paths:**
Introduced through: project@0.0.0 › webargs@0.18.0
Introduced through: project@0.0.0 › flask-apispec@0.7.0 › webargs@0.18.0

**Remediation:**
Upgrade webargs to version 5.1.3 or higher.

**Comment by jason-upchurch** [comment]
# Race Condition #
Vulnerable module: webargs
- Introduced through: webargs@0.18.0 and flask-apispec@0.7.0

**Detailed paths**
- Introduced through: project@0.0.0 › webargs@0.18.0
- Introduced through: project@0.0.0 › flask-apispec@0.7.0 › webargs@0.18.0
## Overview ##
`webargs` is a python library for parsing and validating HTTP request objects, with built-in support for popular web frameworks, including Flask, Django, Bottle, Tornado, Pyramid, webapp2, Falcon, and aiohttp.

Affected versions of this package are vulnerable to Race Condition. Json parsing uses a short-lived cache to store the parsed Json body. This cache is not thread-safe, meaning that incorrect Json payloads could have been parsed for concurrent requests.

## Remediation ##
Upgrade `webargs` to version 5.1.3 or higher.

**Comment by jason-upchurch** [comment]
added `webargs==5.3.1` to `requirements.txt`

**Comment by jason-upchurch** [comment]
Require `webargs@5.3.1`, `pytest` breaks at `webargs@2.0.0`

**Comment by jason-upchurch** [comment]
`webargs` changelog: https://webargs.readthedocs.io/en/latest/changelog.html

**Comment by jason-upchurch** [comment]
# 2.x
```python
@parser.error_handler
def handle_error(error):
raise CustomError(error.messages)
```
# 3.x
```python
@parser.error_handler
def handle_error(error, req):
raise CustomError(error.messages)
```

**Comment by jason-upchurch** [comment]
## 5.0.0 ##
Backwards-incompatible: webargs.ValidationError is removed. Use marshmallow.ValidationError instead.

**Comment by jason-upchurch** [comment]
updated `args.py` to reflect updated `webargs@5.3.1` interface specification an update `requirements.txt` for dependencies. Pushed [WIP]
