### ISSUE TITLE
DEMO_KEY rate limit inconsistent with messaging

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3648]
Currently our "Over rate limit" message says: 

```
You have exceeded your rate limit of 1000 calls an hour for the DEMO_KEY...
```

However, the DEMO_KEY may have changed its restrictions over time and is only set to 40 requests per hour per IP now. This is a key that is used across multiple APIs under api.data.gov. We can't change those key's restrictions, so we should create another FEC demo key if we want to up the limits on the demo key. 

**Completion criteria:**
- [x] Decide if current restrictions of 40 requests per hour per IP is sufficient for DEMO_KEY. 
**Laura says** No - we've been promising 1000/hour and 40/hour is a fraction of that.
- [x] If current restrictions are not sufficient, ask api.data.gov if we can create another custom demo key only for use by the FEC. Ex: `FEC_DEMO` or `FEC_DEMO_KEY` or something easier to type like `FEC` or `DEMO-KEY` or `FEC-DEMO`. Get input from the team.
- [ ] Change our messaging and API documentation to be consistent with actual settings

**Comment by lbeaufort** [comment]
Update: We've had complaints from API users, so I went ahead and emailed the API umbrella folks: 

Hi Team!


We've been operating under the assumption that the DEMO_KEY api key had a 1000 hits per hour per IP rate limit, but it looks like it's set up to 40 hits/hour/IP.  I figure that DEMO_KEY is used by other agencies - I'm not sure if we've been operating under the incorrect assumption, or the limits changed.

Would it be possible to create a named "FEC_DEMO" key for our use? I'm not sure if it's possible to create a named key with the admin interface.

Thanks for your help!
Laura

**Comment by lbeaufort** [comment]
After hearing back from the API umbrella folks, DEMO_KEY has always been 40/IP/hour so that regular users will sign up for a personal key. Our "over rate limit" message was confusing - I propose that we update the language to say 

```
You have exceeded your rate limit. Rate limits are 40 calls per hour for the DEMO_KEY, 1,000 calls per hour for a personal key, or 120 calls per minute for an upgraded key. Sign up for a personal key at <a href="https://api.data.gov/signup/">https://api.data.gov/signup/</a>, or email apiinfo@fec.gov to upgrade your existing key.
```

**Comment by lbeaufort** [comment]
Here is the new and improved version, courtesy of @dorothyyeager :

```
You have exceeded your rate limit of 40 calls per hour for the DEMO_KEY, 1000 calls per hour for a personal key, or 120 calls per minute for an upgraded key. <br> <br>
You can either try again later, <a href="https://api.data.gov/signup/">sign up for a personal key</a>, or email <a href="mailto:apiinfo@fec.gov">apiinfo@fec.gov</a> to upgrade your key.
```

**Comment by lbeaufort** [comment]
Looks like the API umbrella doesn't render HTML, so we switched to plain text. This is live on `stage` and `prod`: 
```
You have exceeded your rate limit of 40 calls per hour for the DEMO_KEY, 1000 calls per hour for a personal key, or 120 calls per minute for an upgraded key. You can either try again later, sign up for a personal key at https://api.data.gov/signup/, or email apiinfo@fec.gov to upgrade your key.
```

Test with more than one request per minute to https://api.open.fec.gov/v1/candidate/P80001571/totals/?api_key=8Bhfz2eaOM0KVmfulpzCUgLnTeYn60oJQDZp4tzy

Thank you @dorothyyeager and @JonellaCulmer for your help!
