### ISSUE TITLE
Check logs Sprint 8.5 week 1

### ISSUE THREAD

**Issue by qqss88** [fecgov/openFEC#3652]
Log review needs to be completed for Sprint 8.5 (week 1) per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by fec-jli** [comment]
duplicate one, please look at this [https://github.com/fecgov/openFEC/issues/3655#event-2247356808](https://github.com/fecgov/openFEC/issues/3655#event-2247356808)
