### ISSUE TITLE
[High] fecgov/openFEC:data/flyway/build.gradle - need a fix by Apr. 28, 2019

### ISSUE THREAD

**Issue by qqss88** [fecgov/openFEC#3654]
**Overview**: 
org.postgresql:postgresql is a Java JDBC 4.2 (JRE 8+) driver for PostgreSQL database.

Affected versions of this package are vulnerable to Man-in-the-Middle (MitM). It was possible to provide an SSL Factory and not check the host name if a host name verifier was not provided to the driver.
Man-in-the-Middle (MitM)
https://app.snyk.io/org/fecgov/project/e6c155e9-f0ac-4a49-98fa-83c24f5b74b3/

**Vulnerable module**: org.postgresql:postgresql

**Introduced through**: org.flywaydb:flyway-commandline@5.1.3

**Detailed paths** : 
Introduced through: project@0.0.0 › org.flywaydb:flyway-commandline@5.1.3 › org.postgresql:postgresql@42.2.2.jre6

**Remediation** :  `Upgrade org.postgresql:postgresql to version 42.2.5 or higher.`

- [x] Install version 5.2.4 of Flyway
- [x] Update Flyway version to 5.2.4 [here](https://github.com/fecgov/openFEC/blob/develop/.circleci/config.yml#L36-L42)
- [x] Update Flyway version to 5.2.4 [here](https://github.com/fecgov/openFEC/blob/develop/data/flyway/build.gradle#L9)
-  [x] Update README with new version instructions
- [x] Update team google doc instructions
- [x] Test with manual deploy - make sure flyway checks to see if there are any new migrations
- [x] ~Test migration with headless app (look for `flyway-independent-migration`)~ As a team we decided we could skip this step since we tested it with the last upgrade. We find manual deploy to be sufficient.
- [x] Give devs instructions on updating local

**Comment by lbeaufort** [comment]
It looks like Currently Flyway version 5.1.3 downloads 
flyway-5.1.3/drivers/postgresql-42.2.2.jre6.jar

I'm thinking we might need to upgrade Flyway version, but we need to figure out if that will automatically update the postgresql driver.

**Comment by pkfec** [comment]
@lbeaufort I have installed the latest version of flyway 5.2.4 and ran the migrations against my local test db. This latest version of flyway comes with an upgraded **postgressql-42.2.5.jre6.jar**.  Didnt run into any issues on my local. 

<img width="1150" alt="Screen Shot 2019-04-04 at 12 01 57 PM" src="https://user-images.githubusercontent.com/11650355/55570962-8f5f0200-56d2-11e9-9ddc-902fbc2a85ba.png">

**Comment by lbeaufort** [comment]
That is great, thank you so much @pkfec!

**Comment by jason-upchurch** [comment]
Sent instructions on #dev channel
