### ISSUE TITLE
incorrect totals for C00508416 (FRIENDS OF JOHN DELANEY)  on committee profile page

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#3656]
Checking: C00508416, FRIENDS OF JOHN DELANEY

On committee profile page for C00508416, the totals do not match what's on the candidate profile page.  The gap is caused by not including the totals from the F3 filed by this committee.

**committee profile:**
total receipts:  5,874,365.79
total disbursements: 5,660,142.67

https://www.fec.gov/data/committee/C00508416/?cycle=2018

**candidate profile:**
total receipts: 6,145,779.44
total disbursements: 5,899,574.20
https://www.fec.gov/data/candidate/P00006213/?cycle=2020&election_full=true

A similar issue can be found here: [#3611](https://github.com/fecgov/openFEC/issues/3611)

**Completion criteria:**
- [ ] Look at how the totals are calculated for the /totals/ endpoint
- [ ] For Presidential candidates, make sure totals are including information from form 3 and 3P

**Comment by hcaofec** [comment]
After switching to ofec_totals_combined_mv, the query needs to be rewritten as well to include the data from F3.  Delaney's committee has two rows in this mv for 2018 cycle, and aggregate functions needs to be added to query to calculate running totals and summary totals.

**Comment by hcaofec** [comment]
A view is created to capture financial summary data per committee, per fec cycle

**Comment by patphongs** [comment]
Fix has been merged
