### ISSUE TITLE
Expand two year restriction to allow users to search up to 6 year periods: schedule_a api update/re-implementation

### ISSUE THREAD

**Issue by qqss88** [fecgov/openFEC#3659]
related issues:
#3595 

other related issues:
#3544 
#2684
#2630 

Basic filter logic for removing 2 year restriction:
- Default display shows the currently two-year time period. 
- User can search MORE THAN 2 year time period only if a secondary criteria is required. What does a user see if/when they select more than 1 two-year time period?
          - If no secondary criteria is supplied, search only see ONE 2 year time period at a time

Current implementation in 3595:
1. two_year_transaction_period: required --> not required
2. multiple cycles can be entered

based on the discussion from the engineering sync, we need to discuss further to have a well-defined implementation plan.

**Comment by qqss88** [comment]
Need to discuss this during the engineering sync. Major questions to clarify:

1. the 6 years should be 6 consecutive years.
2. the years restriction should be implemented with 'two_year_transaction_period' filtering.

**Comment by pkfec** [comment]
We decided to remove the 2 year restriction on the API entirely. The changes are implemented in this ticket : https://github.com/fecgov/openFEC/issues/3595. Hence closing this ticket.
