### ISSUE TITLE
Research - Create FEC owned DNS entries 

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3667]
Currently all our DNS entries are managed by cloud.gov. We need transfer them to our own fecgov repo and take ownership of them.
Related issue: https://github.com/fecgov/openFEC/issues/3320

18F repo
https://github.com/18F/dns
FEC repo
https://github.com/fecgov/fec-dns

Current 18F host DNS entries that need to be transferred to FEC
- beta.fec.gov
- open.fec.gov
- transition.fec.gov

** Research Completion criteria:**
- [x] Figure out how to create DNS entries on our own AWS commercial account using terraform 
- [ ] Create a circleci user for deployer account
- [ ] Create a S3 bucket to store the terraform.state file
- [ ] Create a our own fec-dns repo in github
- [ ] Attach circleci configuration to fec-dns repo
- [ ] Make sure all members has access to fec-dns repo and they can push changes

Depending on what we decide on CDN caching entries, we need to have a follow up meeting with cloud.gov.  If we are going to create CDN entries then create a separate ticket for it.

**Comment by fec-jli** [comment]
We just figure out how to create DNS using terraform and play on awstest account.
I am writing the notes about this now.

**Comment by fec-jli** [comment]
1)We already created a our own fec-dns repo in github and all members has access to fec-dns repo and they can push changes
2)We already figure out how to do the following:
**Create a S3 bucket to store the terraform.state file(using aws console or terraform)
**Create a circleci user for deployer account (using aws console or terraform)
Attach circleci configuration to fec-dns repo
**Create DNS entries on our own AWS commercial account using terraform 
3) We know we don't need create new cdn-route entries, we can use existing cdn-route of cloudfront.

so, we close this ticket. We will create new ticket for real work on creating DNS on stage space later.
