### ISSUE TITLE
Check logs sprint 8.6 week 1

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3691]
Log review needs to be completed for Sprint 8.5 (week 1) per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by fecjjeng** [comment]
Vulnerabilities found this week:

OPENFEC: Total 2

package.json: 0

requirements.txt: 1 MEDIUM
1. Race Condition : #3642

flyway:1 HIGH
1. Man-in-the-Middle (MitM) : #3654

FEC-EREGS: Total 2

package.json: 1 MEDIUM
1. Prototype Pollution :fecgov/fec-eregs#439

requirements.txt: 1 MEDIUM
1. Race Condition: fecgov/fec-eregs#435

FEC-PATTERN-LIBRARY: Total 1

package.json: 1 MEDIUM
1. Prototype Pollution fecgov/fec-pattern-library#135
FEC-CMS: Total 3

package.json: 1 HIGH, 2 MEDIUM
1. Arbitrary File Overwrite : HIGH fecgov/fec-cms#2821
2. Denial of Service (DoS) : MEDIUM fecgov/fec-cms#2792
3. Prototype Pollution: MEDIUM fecgov/fec-cms#2823

requirements.txt: Total 1
1. Sandbox Escape: fecgov/fec-cms#2822

Account approvals: NONE this week.

Search logs: No new users added/removed

Cloud.gov Dashboard: 9 deployer accounts, same as last week.

**Comment by fecjjeng** [comment]
complete and close the ticket.
