### ISSUE TITLE
Check logs sprint 8.6 week 2

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3692]
Log review needs to be completed for Sprint 8.5 (week 2) per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by jason-upchurch** [comment]
Vulnerabilities found this week:

**FEC-CMS**: Total 5
package.json: 1 HIGH, 2 MEDIUM
1. Arbitrary File Overwrite : HIGH fecgov/fec-cms#2821
2. Denial of Service (DoS) : MEDIUM fecgov/fec-cms#2792
3. Prototype Pollution: MEDIUM fecgov/fec-cms#2823

requirements.txt: 1 HIGH, 1 MEDIUM
1. CRLF Injection: HIGH https://github.com/fecgov/fec-cms/issues/2862
2. Sandbox Escape: MEDIUM fecgov/fec-cms#2822

**OPENFEC**: Total 3
package.json: 0

requirements.txt: 1 HIGH, 1 MEDIUM
1. CRLF Injection: HIGH https://github.com/fecgov/openFEC/issues/3722
2. Race Condition : MEDIUM #3642

flyway:2 HIGH
1. Man-in-the-Middle (MitM) : 1 HIGH: Snyk is recommending upgrade to `org.postgresql:postgresql@42.2.5` driver, which we currently have, therefore Laura has marked it as a false positive.
2. Integer Overflow: #3706 

**FEC-EREGS**: Total 3

package.json: 1 MEDIUM
1. Prototype Pollution : MEDIUM fecgov/fec-eregs#439

requirements.txt: 1 HIGH, 1 MEDIUM
1. CRLF injection: HIGH https://github.com/fecgov/fec-eregs/issues/442
2. Race Condition: MEDIUM fecgov/fec-eregs#435

**FEC-PATTERN-LIBRARY**: Total 1

package.json: 1 MEDIUM
1. Prototype Pollution fecgov/fec-pattern-library#135

Account approvals: One issue added: https://github.com/fecgov/fec-accounts/issues/174

Search logs: No new users added/removed

Cloud.gov Dashboard: 9 deployer accounts, same as last week.

Offboarding: Ticket https://github.com/fecgov/fec-accounts/issues/173 needs to be assigned
