### ISSUE TITLE
Loans:/schedules/schedule_c/{sub_id} is not working

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#3696]
When attempting to get a response request from /schedules/schedule_c/{sub_id}, there is a 500 error.

Sample request URL: https://api.open.fec.gov/v1/schedules/schedule_c/1021220180036303017/?api_key=DEMO_KEY&per_page=20&page=1

How to reproduce:
Go to https://api.open.fec.gov/developers/#/loans/get_schedules_schedule_c__sub_id__
Click the Try it out button
Enter any sub_id for schedule_c or use one from this sample list of sample sub_ids: 1010320180036112499,
1010320180036112570,
1010420130011352007,
1010520170033146002, 
4123120181623413597,
4123120151260394245
Click the Execute button. You will see a 500 Internal Server Error response.

**Completion criteria:**
- [x] Fix the endpoint
- [x] Check with endpoint_walk.py
- [x] Add a test for this endpoint

**Comment by patphongs** [comment]
Similar to this PR: https://github.com/fecgov/openFEC/pull/3682. Check for implementation details

**Comment by fec-jli** [comment]
This issue will be fixed in openFEC PR: 
[https://github.com/fecgov/openFEC/pull/3714](https://github.com/fecgov/openFEC/pull/3714)
