### ISSUE TITLE
Research making totals-level data available for filings after 7:30 pm

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3701]
**User story:** As a citizen interested in which presidential candidates have raised the most money, I want to check the FEC website the morning after a filing deadline and see up-to-date and accurate data.

**Problem:** Currently, summary data for committees that file after 7:30pm won't appear in the totals data (examples) until over 24 hours later. This make charts like https://www.fec.gov/data/raising-bythenumbers/ confusing to the user, who might be looking to compare recent filings.

In order to reach parity with the classic presidential map, and to show up-to-date top-level numbers on the home page, we should research how to process summary-level data we receive up until midnight on the filing deadline. 

**Example**
On 4/16/19, the day after the filing deadline, [media outlets reported](https://www.nytimes.com/interactive/2019/04/16/us/politics/campaign-finance-2020-fundraising.html) that Beto O'Rourke had raised $9.4 million in individual contributions, but the "Raising by the numbers" page didn't show that candidate:
<img width="937" alt="Screen Shot 2019-04-16 at 10 55 14 AM" src="https://user-images.githubusercontent.com/31420082/56220884-362e9100-6037-11e9-9a6c-5fb305d05f47.png">
This is because the [committee filed around 10pm on the filing deadline](https://www.fec.gov/data/committee/C00699090/?tab=filings), 2 hours before the deadline but after the 7:30pm cutoff for making summary data available.

**Ideas**
- One idea is to run the `b_nightly` process again after midnight - the RAD modues will be updated much later, but the data wouldn't be any more stale than it is currently. 
- Another idea is to modify the presidential informatica process so it runs all summary-level data so the 2am delivery would do all form-level data. We'll need to research to make sure this doesn't interfere with our normal delivery process (we wouldn't want to deliver the same data twice)
- Another idea is to bring in summary data from the raw filings.

Completion Criteria:
- [x] Coordinate with Informatica team
- [ ] Develop plan we can implement to remediate this problem

**Comment by jwchumley** [comment]
Another thought - take the summary data for electronic filings from the real_efile schema or check the real_efile schema for filings that were too late for the load and union them into the result.

**Comment by fecjjeng** [comment]
I had discussed with the Informatica team, according to Jerry, we currently load separated form 3p, schedule A and schedule B data files for presidential tables at 5:30 am.   Users can use the presidential map in the classic.fec.gov to see all the updated presidential candidate's financial data.

**Comment by fecjjeng** [comment]
These are a special set of tables just to handle this situation and the data is not coded and only used for the display of presidential data quickly. The data will go through the regular route and go in the regular tables later.

**Comment by dorothyyeager** [comment]
Next steps: Talk offline about them.

**Comment by fecjjeng** [comment]
We plan to have a meeting to discuss this issue after grooming meeting Thursday afternoon.

**Comment by fecjjeng** [comment]
Possible solution would be:
1.  Users can tag alone and use the presidential map in the classic.fec.gov to see all the updated presidential candidate's financial data.  A pointer from the new web site to the classic site will be needed.
2. Include the special set of tables in the transfer process and new web site will use these data to create new display.
PRES_F3P_TOTALS_CA_CM_LINK_16 =DISCLOSURE.PRES_F3P_TOTALS_CA_CM_LINK_16
PRES_CA_CM_SCHED_A_JOIN_16 =DISCLOSURE.PRES_CA_CM_SCHED_A_JOIN_16
PRES_CA_CM_SCHED_LINK_SUM_16 =DISCLOSURE.PRES_CA_CM_SCHED_LINK_SUM_16
PRES_CA_CM_SCHED_STATE_16 =DISCLOSURE.PRES_CA_CM_SCHED_STATE_16
PRES_NML_FORM_3P_16 =DISCLOSURE.PRES_NML_FORM_3P_16
PRES_NML_SCHED_A_16 =DISCLOSURE.PRES_NML_SCHED_A_16
PRES_NML_CA_CM_LINK_16 =DISCLOSURE.PRES_NML_CA_CM_LINK_16
PRES_NML_SCHED_B_16 =DISCLOSURE.PRES_NML_SCHED_B_16
3. Get data from real_efile, a separate MV based on the real_efile data only for presidential form level data might be a possible solution.  I would not recommend to blend into the the regular MV.  Separate API endpoint will be needed if we take this approach.

**Comment by fecjjeng** [comment]
We had discussed different possibility to address this problem.  
Solution #1 will depend on the existence of classic site, which we plan to shutdown in the near future, if not sooner.
Solution #2 will only address the presidential candidates, but not the house/senate candidates.
Solution #3 on regular financial reports (F3, F3P, and F3X) would be a possible solution.  But will requires major lifting, involved changes on fundamental process that we currently relying on.  Also, it is still depending on the time required for data feed from committees and Salient, our contractor company who process data from committees.

**Comment by fecjjeng** [comment]
A separate ticket opened (#3800) to re-consider Solution #3 after 2020 election.
A CMS ticket opened (https://github.com/fecgov/fec-cms/issues/2924) to add description to let the users know that data filed after 7:30pm previous night will not be included.
