### ISSUE TITLE
Investigate python buildpack depreciation warning

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3703]
From Circle:
```
Downloading python_buildpack...
Downloaded python_buildpack
...
Downloading app package...
Downloaded app package (51.1M)
-----> Python Buildpack version 1.6.29
       **WARNING** [DEPRECATION WARNING]:
       **WARNING** Please use AppDynamics extension buildpack for Python Application instrumentation
       **WARNING** for more details: https://docs.pivotal.io/partners/appdynamics/multibuildpack.html
```
https://circleci.com/gh/fecgov/openFEC/1400

**Comment by qqss88** [comment]
Here is quick reference:
https://docs.pivotal.io/partners/appdynamics/multibuildpack.html

need to follow the guide and do some testings.

**Comment by qqss88** [comment]
python buildpack from AppDynamics:
https://docs.cloudfoundry.org/buildpacks/python/index.html

**Comment by qqss88** [comment]
appdynamics github examples:
https://github.com/Appdynamics/cloudfoundry-apps/tree/master/cf-python

note: there is contradictory info from readme and menifest.yml file.

**Comment by qqss88** [comment]
appdynamics python-buildpack:
https://github.com/Appdynamics/python-buildpack

**Comment by qqss88** [comment]
quick summary:
1. based on the AppDynamics extension buildtrack documentation:
https://docs.pivotal.io/partners/appdynamics/multibuildpack.html

we need to add the appdbuildpack on the server side and modify the manfest file as guided(they do have sample manifest.yml file). two issues encountered:
- we do not have capability to add a buildpack on our own
- current 'cf push' does not support multiple-buildpack approach.

2. after discuss with Bret from cloud.gov, he suggested using remote buildpack without any changes on the server side. I tried 2 remote python buildpacks:

- https://github.com/appdynamics/python-buildpack.git

>>Current Version: 1.6.13
>>command:
cf push api -b https://github.com/appdynamics/python-buildpack.git

>>result: 
I got build error from this one and finally failed:
Staging app and tracing logs...
   Cell b701ee4f-885a-4c07-80c1-036e3d494e0a creating container for instance 60f2497a-fa07-49a2-87f5-68cef4bb7b21
   Cell b701ee4f-885a-4c07-80c1-036e3d494e0a successfully created container for instance 60f2497a-fa07-49a2-87f5-68cef4bb7b21
   Downloading app package...
   Downloading build artifacts cache...
   Downloaded build artifacts cache (79.6M)
   Downloaded app package (35.5M)
   -----> Download go 1.9.1
   -----> Running go build supply
   -----> Python Buildpack version 1.6.13
          **ERROR** Stack not supported by buildpack: required stack cflinuxfs3 was not found
   Failed to compile droplet: Failed to run all supply scripts: exit status 11
   Exit status 223
   Cell b701ee4f-885a-4c07-80c1-036e3d494e0a stopping instance 60f2497a-fa07-49a2-87f5-68cef4bb7b21
   Cell b701ee4f-885a-4c07-80c1-036e3d494e0a destroying container for instance 60f2497a-fa07-49a2-87f5-68cef4bb7b21
Error staging application: App staging failed in the buildpack compile phase
FAILED

- https://github.com/cloudfoundry/python-buildpack.git
>>version: 1.6.33(our python buildpack version is 1.6.29)
>>command:
cf push api -b https://github.com/cloudfoundry/python-buildpack.git
>>result:
this one pass, but we still have the same warning.

3. based on discussion with Bret again, he suggested that we just leave it the way it is if we never used AppDynamics buildpack before.

leftover and discussion:
we still not sure why we get this deprecation warning. we may need to discuss with cloud.gov people on how to add appdynamics service on the server side(we need to make sure they support it at this moment) before we try this appdynamics multi-buildpack approach.

**Comment by qqss88** [comment]
Bret confirmed that this is cf python buildpack bug:
https://www.pivotaltracker.com/n/projects/1042066/stories/164703749

I think we can skip this warning and close this ticket. But we can keep an eye on the development of this multi-buildpack approach provided by appDynamics..
