### ISSUE TITLE
Create FEC owned DNS for stage.fec.gov

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3704]
We have done research about this here: https://github.com/fecgov/openFEC/issues/3667

For a start we will create our own https://stage.fec.gov domain name using terraform.
We will be using Cloud.gov CDN service.

**Comment by pkfec** [comment]
@rjayasekera @fec-jli Do you have any updates on this issue?

**Comment by rjayasekera** [comment]
This issues completed and https://stage.fec.gov works now using FEC-DNS and Cloud.gov-CDN service.
