### ISSUE TITLE
missing end tag for "default value" on api.open.fec.gov

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3705]
**Problem**
start tag for italics on "Default value" has no corresponding end tag.

**Example**
https://api.open.fec.gov/developers/#/filer%20resources/get_rad_analyst_
```html
<p>&lt;i&gt;Default value : null</p>
```

This bug appears before clicking the "Try it out" button.

**Comment by patphongs** [comment]
Thanks @jason-upchruch! I wonder if it’s suppose to be just an <i></i> tag instead of encoded chars

**Comment by lbeaufort** [comment]
@patphongs @jason-upchurch let's maybe first look at our specs and make sure they validate.

**Comment by jason-upchurch** [comment]
background/relevant issues and/or details:
- https://github.com/fecgov/openFEC/pull/3068/commits
- https://github.com/fecgov/openFEC/commit/ca3dca040013af20029e43d99439bb45ff921a9c
- https://github.com/fecgov/openFEC/blob/8886afca02b6fdada2b33fb4b54f57d9f9ee2f6a/webpack.production.config.js#L14

**Comment by jason-upchurch** [comment]
Compare latest `swagger-ui.js.map` in the `swagger-ui` project at https://raw.githubusercontent.com/swagger-api/swagger-ui/master/dist/swagger-ui.js.map to the `swagger-ui.js.map` in openFEC `node_modules`. 

- source={"<i>Default value</i> : " + paramDefaultValue}
- source={\"<i>Default value</i> : \" + paramDefaultValue}

current version (openFEC) uses quote escapes.

to do:
- [ ] compare using each version on local api

**Comment by jason-upchurch** [comment]
currently on hold in favor of higher priority items, but next check can be to see if replacing line to exclude the escape characters resolves the issue. If so, this `swagger-ui.js.map` is available with upgrade of swaggerui version.

**Comment by jason-upchurch** [comment]
@patphongs @PaulClark2 @johnnyporkchops closing this issue as the problem was resolved under https://github.com/fecgov/openFEC/pull/4262
