### ISSUE TITLE
Add most_recent logic to /schedules/schedule_e/efile/

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3708]
**User story:** As a reporter, I would like to calculate a clean outside spending total of 24/48 (Form 5 and Form 24) IE notices for a particular candidate and/or election.

For small races, it's easy to dedupe this data but for larger races like presidential it's very difficult to determine the "as amended" set of data.

Like we show `current_version` for form-level data, we should add `current_version` to transaction-level IE data because we dedupe other transactions for our users but not IEs because there is so much ambiguity on amendments, etc. The default API behavior should remain the same, but there an optional flag to filter by `most_recent` yes, no, and unknown. In the future, we'll add these filters to the front end datatables and default to show `most_recent` yes and unknown.

**Completion criteria:**

- [ ] Like we show `current_version` for form-level data, we should add `current_version` to transaction-level IE data because we dedupe other transactions for our users but not IEs because there is so much ambiguity on amendments, etc. The default API behavior should remain the same, but there an optional flag to filter by `most_recent` true, including unknown and false.

- [ ] Change most recent filter behavior for other endpoints to include nulls with the trues.

**Comment by lbeaufort** [comment]
Note: the paper filing part of this work is blocked by https://github.com/fecgov/openFEC/issues/3455. Per @PaulClark2 we could work on the raw data first (/schedules/schedule_e/efile) before working on the paper filing "most recent" logic.

**Comment by hcaofec** [comment]
There is a view: public.real_efile_se_f57 which is the same as real_efile_se_f57_vw, but not being used.  real_efile_se_f57 can be dropped if it's not being used.

**Comment by hcaofec** [comment]
most_recent column will be added to the view, and the related filter will be implemented in [#3813](https://github.com/fecgov/openFEC/issues/3813)
