### ISSUE TITLE
Candidate totals incorrect for one candidate

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3709]
*********Checking: H6PR00082, GONZALEZ COLON, JENNIFFER************

Candidate totals datatable url: https://api.open.fec.gov/v1/candidates/totals/?candidate_id=H6PR00082&election_year=2020&election_full=true&api_key=DEMO_KEY&sort=-receipts

Candidate profile page totals url: https://api.open.fec.gov/v1/candidate/H6PR00082/totals/?cycle=2020&api_key=DEMO_KEY&full_election=False

 Election profile page totals url: https://api.open.fec.gov/v1/elections/?candidate_id=H6PR00082&cycle=2020&election_full=true&api_key=DEMO_KEY&office=house&sort_nulls_last=true&sort=-total_receipts&per_page=100&state=PR&election_full=True&district=00&election_full=False

!!! ERROR - contribution results don't match!!!

| Data source | Total |
|--|--|
| Candidate datatable 		|	$420,879.39|
| Candidate profile page 	|	$19,200.00|
| Election profile page 	|	$19,200.00|

!!! ERROR - disbursement results don't match!!! 

| Data source | Total |
|--|--|
| Candidate datatable 		|	$135,776.83 |
| Candidate profile page 	|	$12,117.10 |
| Election profile page 	|	$12,117.10 |

**Comment by lbeaufort** [comment]
From @PaulClark2: "Puerto Rico's resident commissioner has a 4-year election cycle. Even though the commissioner serves in the house."

**Comment by dorothyyeager** [comment]
Background issue on Puerto Rico election cycle in case it helps: https://github.com/fecgov/fec-cms/issues/1722

**Comment by lbeaufort** [comment]
@fecjjeng thank you so much for addressing this issue at the same time as #3768! Per our discussion, I will add to the integrated candidate tests to cover this data scenario.

**Comment by PaulClark2** [comment]
Is this front-end work related? https://github.com/fecgov/fec-cms/issues/1722

**Comment by lbeaufort** [comment]
Definitely stems from the same data complexity, but the technical problems/solutions aren’t related.


On Jun 11, 2019, at 4:02 PM, Paul Clark <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this front-end work related? fecgov/fec-cms#1722<https://github.com/fecgov/fec-cms/issues/1722>

**Comment by lbeaufort** [comment]
!!! ERROR - receipts results don't match!!!


| Data source | Total receipts | Notes
|--|--|
| datatable page        |   $420,879.39| Correct
| candidate page        |   $401,679.39| Missing 2020 data
| election page         |   $19,200.00 | Missing 2018 data

!!! ERROR - disbursements results don't match!!!

| Data source | Total disbursements |
|--|--|
| datatable page        |   $135,776.83|
| candidate page        |   $123,659.73|
| election page         |   $12,117.10|

!!! ERROR - cash_on_hand_end_period results don't match!!!

| Data source | Total cash_on_hand_end_period |
|--|--|
| datatable page        |   $308,640.33|
| candidate page        |   $301,557.43|
| election page         |   $308,640.33|



### Candidates/totals


--http://localhost:5000/v1/candidates/totals/?candidate_id=H6PR00082&election_year=2020&election_full=true&sort=-receipts&api_key=DEMO_KEY

```
SELECT *
FROM ofec_candidate_history_with_future_election_mv JOIN ofec_candidate_totals_mv ON ofec_candidate_history_with_future_election_mv.candidate_id = ofec_candidate_totals_mv.candidate_id AND ofec_candidate_history_with_future_election_mv.two_year_period = ofec_candidate_totals_mv.cycle JOIN ofec_candidate_detail_mv ON ofec_candidate_history_with_future_election_mv.candidate_id = ofec_candidate_detail_mv.candidate_id
WHERE ofec_candidate_history_with_future_election_mv.candidate_id IN ('H6PR00082') AND ofec_candidate_totals_mv.election_year IN (2020) AND ofec_candidate_totals_mv.is_election = true
```

### Candidate profile page (candidate/id/totals)

--http://localhost:5000/v1/candidate/H6PR00082/totals/?cycle=2020&api_key=DEMO_KEY&full_election=True

--Resource: CandidateTotalsView
--Model: CandidateCommitteeTotalsHouseSenate
--MV: ofec_totals_candidate_committees_mv
--Fix options:
--1) group `election_totals` subquery by `totals.election_year` in ofec_totals_candidate_committees_mv, needs migration)
--2) update `ofec_candidate_election_mv` to use `candidate_election_duration` function

-- Testing MV: ofec_totals_candidate_committees_mv_lb_tmp

``
SELECT *
FROM ofec_totals_candidate_committees_mv
WHERE ofec_totals_candidate_committees_mv.cycle IN (2020) AND ofec_totals_candidate_committees_mv.candidate_id = 'H6PR00082' AND ofec_totals_candidate_committees_mv.full_election = true
``


### Election profile page (/elections/)

--http://localhost:5000/v1/elections/?candidate_id=H6PR00082&cycle=2020&election_full=true&office=house&sort_nulls_last=true&sort=-total_receipts&per_page=100&api_key=DEMO_KEY&state=PR&district=00&election_full=True

--Resource: ElectionView
--Models: various
--Fix: handle duration for PR in the python
```
    if kwargs.get('election_full'):
        if kwargs.get('state').upper() == 'PR':
            # PR house commissioners have 4-year cycles
            duration = 4
        else:
            duration = election_durations.get(kwargs['office'], 2)
    else:
        duration = 2
```

--TODO: Look into ElectionSummary, '/elections/summary/' and see if we can use `filter_candidate_totals_with_alternative_cand_election_yr` and get rid of 
`filter_candidate_totals` and `filter_candidates`


```
(SQL is a nightmare)
```
