### ISSUE TITLE
Add validation for missing or multiple 2-year periods

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3717]
Missing or multiple 2-year periods need a secondary criteria with an index. Can we use the index_validator? would that be over-engineered? We could start with a hard-coded list of fields. 
See front-end issue: https://github.com/fecgov/fec-cms/issues/2857

**Comment by pkfec** [comment]
Deployed Hotfix on April 26th. Technical details are in  PR fecgov/openFEC#3725.
Hence closing this issue.
