### ISSUE TITLE
Investigate setting db timeout for 'fec_api' to match application timeout

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3724]
www.fec.gov timeout/cache limits diaram:
[https://docs.google.com/drawings/d/1TH1BPoG1TYMs4HSE5_jxnJw1EXxq0mTpz4zWu5o7p_k/edit](https://docs.google.com/drawings/d/1TH1BPoG1TYMs4HSE5_jxnJw1EXxq0mTpz4zWu5o7p_k/edit)

![fec gov timeout _cache charz](https://user-images.githubusercontent.com/24395751/57641836-fe5a3100-7583-11e9-89cd-686290d5a912.jpg)

So big queries don't clog up the database, we need to investigate setting db timeout for `fec_api` role to match application timeout. Can we do this with a migration? 

**API timeout is 5 minutes?**
`ALTER ROLE fec_api SET statement_timeout=300000;`

Seems to persist when logging in and out

**Comment by lbeaufort** [comment]
From @fec-jli Jun Li [10:55 AM]
>can we think about set timeout in SQLAlchemy level (DAO level) , like `create_engine(db_url, connect_args={'connection_timeout': 10})`

I read that it’s not advisable to set the timeout globally, but I think SQLalchemy would only use `fec_read` anyway…? We should definitely investigate/test.

**Comment by lbeaufort** [comment]
Looks like we need to set `statement_timeout` rather than `connection_timeout` in the `create_engine`'s `connect_args`

**Comment by rjayasekera** [comment]
In my past experiences this type of terminate connections should be done as a last resort.  Most of the time even though you terminate a connection from the client side, background query still running to its completion.  After the DB process (query) completes SQL engine tries to send the results back to the client and that time it finds out that the client connection who made the request does not exists and prints an error message "client lost connection" 
That is why most of the time when you kill a long running query from the client side, we need to login to the database server find the PID and kill that PID from the server side where SQL engine resides.  

In postgres we use:
SELECT pg_cancel_backend(pid);
SELECT pg_terminate_backend(pid);
 
Just my thoughts.  We may need to do further research on this.

**Comment by fec-jli** [comment]
1)for fec.gov, data accesses are all read-only, so we don't have `row level concurrency access` issue, that is good.
2)it looks like we don't use sqlalchemy pooling to manage connection? (maybe I am wrong), not sure how we do db transaction management. (use mybatis framework in java)
3)by using sqlalchemy pooling , we can setup init connection number, timeout and transaction management.

For answer Rohan's questions, 1)when a connection takes long time, sqlalchemy will run rollback() to db and release that connection. 2)when db dis-connect happen, sqlalchemy will refresh connection pool automaticity.

Just first thought here, still need do more research. Thanks

**Comment by rjayasekera** [comment]
Thanks, @fec-jli This explains why we see lot of rollbacks on DB side.  So the connections are taking too long SqlAlchemy will abandon query and rollback any work.

**Comment by fec-jli** [comment]
on database level, there are two parameters we can think about to modify
idle_in_transaction_session_timeout
statement_timeout(x)


1)mostly don’t suggest to modify the `statement_timeout`, this is a session based, need restart session.

2)test `idle_in_transaction_session_timeout = 1 minute` on dev.

check the `state` in table pg_stat_activity:
(1)state = idle
mean that this connection is available for next request to use.

(2)state = idle_in_transaction 
mean the query is running, if time is greater then 1 minute, this connection will timeout and will kill this connection put back to the connection pool.

(3)state = active
query is running

(4)check the `query` column
when the transaction finished, 	query = rollback.
mean that all connection resource will be unlocked. and available for next request to use.


(5)now, our database performance is powerful enough to handle our query requests. normally, there are only 4 to 5 `state = idle_in_transaction`, after a couple seconds, state change to `idle`. 

Conclusion:
We don’t need set idle_in_transaction_session_timeout for now.
 

3)We also test some connection pool settings for SqlAlchemy. 
current setting:
pool timeout=120, pool size=50, overflow=50
(init allocated 50 db connection and keep alive. dynamically can overflow=50, so max connection = 100. timeout means that wait before giving up on getting a connection from the pool)

From AWS log, we know average connections for replica1 and replica 2 = 60~70
So we are good now.

**Comment by fec-jli** [comment]
This is done, closed.

**Comment by lbeaufort** [comment]
Really great work, @fec-jli! After demo, let's discuss setting the `idle_in_transaction_session_timeout` before closing this issue.

**Comment by fec-jli** [comment]
@lbeaufort sure , I reopened this issue. Thanks

**Comment by AmyKort** [comment]
Do we want to move this to 9.1 for now?

**Comment by fec-jli** [comment]
@PaulClark2  @lbeaufort I move this to S9.1.
We can talk about this later after @rjayasekera talk with 4 points to see if any suggestion.
Thanks

**Comment by fec-jli** [comment]
We have talked about modify `idle_in_transaction_session_timeout` parameter issue.
for now user `fec_api` is shared by different app, so it is not good to modify this parameter.
We will create a new issue to create new database user=fec_web who will be used for fec api, read-only, then we can try to setup timeout for user=fec_web. close this issue. Thanks

**Comment by cnlucas** [comment]
Statement_timeout should cancel the [statement](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-STATEMENT-TIMEOUT) from the server side cleaner than our current method
Sqlalchemy_pool_timeout [does not limit how long the query](https://docs.sqlalchemy.org/en/13/core/engines.html#sqlalchemy.create_engine.params.pool_timeout) can run in PG, just how long a connection can be waiting for a response from the pool. This is why we are seeing very long successful query times. 

We can and should reconsider implementing session timeouts via role, but until another role is created I think it's fine to do it at engine creation for the read only.

Setting statement_timeout at the session or role is not the same as a global setting via postgresql.conf.
