### ISSUE TITLE
Notify /schedules/schedule_a/ API users of default behavior change

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3729]
We should look at the API umbrella admin page and email the folks who have used /schedules/schedule_a/ in the past 6 months.

In order to allow users to search across more than one two-year period, the decision was made to not default to a 2-year period.

There are definitely trade-offs, but having a “secret” parameter applied isn’t very friendly, and we’d have to make them choose all 2-year periods to search all data, which also isn’t very friendly. I entered an issue to make the swagger default value (so, a client-side default rather than a server-side default) but I don’t know how we’d make that swagger default. setting `missing=2020` forces the 2020 value.

https://github.com/fecgov/openFEC/issues/3728

Right now if we have a default value in args.py then the API will add that parameter even if it&#39;s not specified. To improve performance, we should see if we can get the swagger developer docs t...
Right now all our default values in `args.py` are server-side defaults. I’d like to add swagger/client-side defaults but I don’t think we can currently do that.
a query to search all data would have to say: 
```
&two_year_transaction_period=1980&two_year_transaction_period=1982&two_year_transaction_period=1984&two_year_transaction_period=1986&two_year_transaction_period=1988&two_year_transaction_period=1990&two_year_transaction_period=1992&two_year_transaction_period=1994&two_year_transaction_period=1996&two_year_transaction_period=1998&two_year_transaction_period=2000&two_year_transaction_period=2002&two_year_transaction_period=2004....
``` 
...and you can see it’s very tedious.

**Completion criteria**
- [ ] Draft language 
- [ ] Identify the folks who have used /schedules/schedule_a/ in the past 6 months.
- [ ] Email them

**Comment by AmyKort** [comment]
Closing as stale.
