### ISSUE TITLE
removing line_number from secondary parameter list from schedule_a api

### ISSUE THREAD

**Issue by qqss88** [fecgov/openFEC#3733]
As data distribution of line_number in schedule_a is skewed toward '11AI', and when multiple cycles and secondary parameter 'line_number=11AI' is not loadable under current db performance, we'll remove line_number from secondary list when multiple cycle data is queried from schedule_a api.

acceptance criteria:
1. remove line_number from secondary parameter list code-wise.
2. make sure all related unit tests are still ok.

**Comment by pkfec** [comment]
Technical implementation can be tracked this PR https://github.com/fecgov/openFEC/pull/3735. This PR is merged. Hence closing this issue
