### ISSUE TITLE
change committee total api argument 'full_election' to 'election_full' to be aligned with all other APIs

### ISSUE THREAD

**Issue by qqss88** [fecgov/openFEC#3734]
All other APIs are using 'election_full':
./webservices/resources/committees.py:               
./webservices/resources/candidate_aggregates.py:        
./webservices/resources/aggregates.py:        
./webservices/resources/elections.py:        
./webservices/resources/candidates.py:  

Acceptance criteria:
1. change 'full_election' to 'election_full' for the corresponding API
2. make sure all related unit tests are not broken.

**Comment by lbeaufort** [comment]
@qqss88 @pkfec this would be a breaking change - the best we can do it add an additional `election_full` to the existing endpoints.

**Comment by qqss88** [comment]
@lbeaufort thx for the reminder - it is a minor issue and let us do not change it at all. @pkfec let us go ahead and close this ticket.
