### ISSUE TITLE
Fix cand_election_yr in ofec_candidate_history_mv

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3736]
This is continuation from cand_election_yr problem we discovered in issue #3700.   ofec_candidate_history_mv, this is one of the driver for the candidate profile,  and has the same problem and need to be fixed.

**Comment by fecjjeng** [comment]
Following is a screenshot of Hillary's entries in ofec_candidate_history_mv currently.
<img width="647" alt="Screen Shot 2019-04-24 at 11 33 41 AM" src="https://user-images.githubusercontent.com/24943130/56978182-f7273200-6b44-11e9-9b8f-1fc7c612d6ee.png">

**Comment by fecjjeng** [comment]
Confirm with @PaulClark2 that we would like to make the candidate_election_year null when there is actually no elections associate with that particular two_year_period.  Just like what we have in the ofec_candidate_history_mv
![image (5)](https://user-images.githubusercontent.com/24943130/56978873-808b3400-6b46-11e9-9b2b-33cf16a8ff63.png)

**Comment by pkfec** [comment]
@fecjjeng are you still working on this issue? Do you have any updates?

**Comment by fecjjeng** [comment]
the calculation here for the election_year is similar to the election_yr_to_be_included column in ofec_cand_cmte_linkage table, but not exactly the same.
The purpose of election_yr_to_be_included is to calculated the election_cycle the cycle financial data belongs to and an odd year will be rounded up and folded into its even year cycle.
Here the election_year is for the election year, an odd election year need to be preserved, separated from its even year cycle.

The calculation is based on the fec_election_yr, the cand_election_yr, the cycle length (6, 4, 2), the next_election
Simple and straight foward rules first, followed by more complicated rules.
cycles, election_years, election_districts, active_through
are still based on the original cand_election_yr from disclosure.cand_valid_fec_yr so the interface will not be impacted. Only candidate_election_year information is updated

**Comment by fecjjeng** [comment]
The migration file had been created and tested locally and tmp version of MVs were tested in DEV.  Would like this PR to get in the next Sprint to more throughly tests.
