### ISSUE TITLE
Check slow queries

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3739]
**What we're after:** This is a regular ticket to check slow database query performance. 

- [ ] Identify and document slow queries and add logs to the following two locations:
PGbadger: https://drive.google.com/drive/folders/1z57CHj33ib77SfR-oC0lzZcIQZfD0W6h
AWS_rds_logs: https://drive.google.com/drive/folders/1weq69OrC47x_4tmlg099FeEpOH-oQCEN
Stats in LOCAL server: http://db-status.fec.gov/
- [ ] Open up a new ticket if any issues are identified from this log review
- [ ] Open new ticket for next sprint

**Comment by AmyKort** [comment]
Is this for this week?

**Comment by PaulClark2** [comment]
@rjayasekera should this be closed and a new one created for S9.1 or are you still working on this?

**Comment by dorothyyeager** [comment]
Need to determine next steps.

**Comment by PaulClark2** [comment]
@rjayasekera are we waiting for more information from 4Points and/or AWS for this ticket? Or, is it blocked for some other reason?

**Comment by dorothyyeager** [comment]
Closing since we are just regularly collecting slow queries. We will follow up with ticket when we are ready to make a change to address them.
