### ISSUE TITLE
Exclude SL from ofec_totals_combined_mv

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#3740]
ofec_totals_combined_mv is a table that has cycle totals for each committee, per cycle, per form_type.  Currently there are 500+ rows that does not have coverage_end_date. Most of them are party committees who filed SL besides F3x. As it can be seen from the screenshot, postgresql  chose SL row while calculating the latest totals for 2014 in the logic.  Then the sub_id (4012920151237500491) is used to get cvg_end_dt later by LEFT JOIN to ofec_filings_mv.  Because ofec_filings_mv excluds SL, so the coverage_end_date is null in ofec_totals_combined_mv for these party committees.  And for 'last_cash_on_hand_end_period, last_debts_owed_by_committee, last_debts_owed_to_committee, last_net_operating_expenditures, last_net_contributions', values are all from SL row which are 0s for this committee, even though F3x row does have values. 

SLs should not be included in cycle totals.

**Comment by pkfec** [comment]
PR is merged #3749. Closing this issue.
