### ISSUE TITLE
Move two TRUSTED_PROXIES IP addresses into env variables

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#3757]
Currently, we put api umbrella backend IP in rest.py.
TRUSTED_PROXIES = ('54.208.160.112', '54.208.160.151')
In order to secure our app, decide to move to `api env variables`.

**Comment by pkfec** [comment]
Added `trusted_proxy_ips` as an API env variable on `stage` space. PR #3783 is ready for review.

**Comment by pkfec** [comment]
Added `trusted_proxy_ips` API environment variable on `prod` space.

**Comment by lbeaufort** [comment]
@PaulClark2 can we discuss this issue when you're back in the office tomorrow?

**Comment by lbeaufort** [comment]
Update: after speaking with @PaulClark2 we should:

1) Split the IP's into a list
2) Put splitting the `env vars` into a list functionality into a function and add testing coverage
