### ISSUE TITLE
research inconsistency between snyk cli and web interface

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3760]
**Problem**
running snyk command line interface to test resolution of dependency vulnerability yields "all clear" while web interface still shows vulnerability

**Example**
pre-fix report from CLI:
>Medium severity vulnerability found in mysql:mysql-connector-java
>Description: Privilege Escalation
>Info: https://snyk.io/vuln/SNYK-JAVA-MYSQL-174574
>Introduced through: org.flywaydb:flyway-commandline@5.2.4
>From: org.flywaydb:flyway-commandline@5.2.4 > mysql:mysql-connector-java@8.0.12

after adding `exclude group: 'mysql', module: 'mysql-connector-java'` to `build.gradle` and retesting on CLI, vulnerability is resolved.

However, Snyk web interface still shows dependency after merge

**Suggested avenues for investigation**
- run targeted test over ssh
- see if we can run test over github repo specifying the `gradle.build` (right now we can test at top level using the project url, but need to specify correct manifest)
- open issue with Snyk

**Comment by jason-upchurch** [comment]
related issue https://github.com/snyk/snyk/issues/129

**Comment by lbeaufort** [comment]
@jason-upchurch another possibility might be to use GitHub vulnerability tracking. We would want to make sure it doesn't also have false-positive  issues. https://help.github.com/en/articles/about-security-alerts-for-vulnerable-dependencies

**Comment by jason-upchurch** [comment]
Per snyk issue: snyk/snyk#129
>We've discovered the cause of this. Our online tool reads package manifest files and determines which dependencies would be installed if it were run, whereas our CLI tool has access to the actual environment and can determine the actual packages used by the codebase.
