### ISSUE TITLE
Check logs PI planning week

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3766]
Log review needs to be completed for PI planning week per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by jason-upchurch** [comment]
# Vulnerabilities found this week # 

## FEC-CMS: Total 3 ##
**package.json: 1 HIGH, 2 MEDIUM**
- Arbitrary File Overwrite: HIGH fecgov/fec-cms#2901
- Denial of Service (DoS) : MEDIUM fecgov/fec-cms#2792
- Prototype Pollution: MEDIUM fecgov/fec-cms#2823

**requirements.txt: 1 MEDIUM**
- Sandbox Escape: MEDIUM fecgov/fec-cms#2822

## OPENFEC: Total 3 ##
**package.json: 0**

**requirements.txt: 1 MEDIUM**
- Race Condition : MEDIUM #3642

**data/flyway/build.gradle: 0**

## FEC-EREGS: Total 2 ##
**package.json: 1 MEDIUM**
- Prototype Pollution : MEDIUM fecgov/fec-eregs#439

**requirements.txt: 1 MEDIUM**
- Race Condition: MEDIUM fecgov/fec-eregs#435

## FEC-PATTERN-LIBRARY: Total 1 ##
**package.json: 1 MEDIUM**
Prototype Pollution: MEDIUM fecgov/fec-pattern-library#135

# Account approvals: # 
## No new issues ##
## 1 existing issue: ecgov/fec-accounts#174 ##

# Search logs: No new users added/removed #

# Cloud.gov Dashboard: 9 deployer accounts, same as last week. #
