### ISSUE TITLE
Update apispec, stop using forked copy

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3776]
## Summary ##
We should update apispec, stop using forked copy. Some issues with our specs: https://github.com/fecgov/openFEC/pull/3422. We should also add back swagger validation tests.

Related issue #3782 

### Completion criteria
- [ ] Upgrade by adding apispec ~@2.0.x~ back into requirements so that it pulls from original source
- [ ] Make sure to reinstall requirements and make sure apispec is functioning as expected. It should pass all pytests and snyk tests
- [ ] Add more thorough tests to PR
- [ ] pass thorough testing, i.e., complete testing steps explicitly defined in PR

**Comment by jason-upchurch** [comment]
Full changelog available here: https://apispec.readthedocs.io/en/stable/changelog.html

**Comment by jason-upchurch** [comment]
`apispec` versions to work through:

| version | `pytest` passed |
| ---        | ---                     |
|1.0.0b1| `True` |
|1.0.0b2|
|1.0.0b3|
|1.0.0b4|
|1.0.0b5|
|1.0.0b6|
|1.0.0rc1|
|1.0.0|
|1.1.0|
|1.1.1|
|1.1.2|
|1.2.0|
|1.3.0|
|1.3.1|
|1.3.2|
|1.3.3|
|2.0.0|
|2.0.1|
|2.0.2|
|3.0.0 |

**Comment by jason-upchurch** [comment]
backlog comment (to be deleted as worked):


|     | `False` | `ModuleNotFoundError: No module named 'marshmallow.compat'` in `apispec.ext.marshmallow/openapi.py` | `True` | [upgrade to `apispec@3.0.0`](https://github.com/marshmallow-code/apispec/pull/445) |
|3.0.0 | `False` | `ValueError: 'missing' must not be set for required fields` in `utils.py` line 48 | `True` | [specify `required=False`](https://github.com/marshmallow-code/marshmallow/issues/1040) |
| | `False` | `ModuleNotFoundError: No module named 'marshmallow.compat'` in `args.py` line 3 | `True` | replace `isinstance(value, text_type)` with `isinstance(value, str)` |
| | `False` | `TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given` in `args.py` | `False` | upgrade to `webargs@5.5.1` |
| | `False` | `TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given` in `args.py` 206 | `True` | rem `IStr` from `'case_respondents'` |
| | `False` | `TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given` in `args.py` 208 | `True` | rem `IStr` from `'case_election_cycles'` |
| | `False` | `TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given` in `args.py` 216 | `True` | rem `IStr` from `'af_committee_id'` |
| | `False` | `TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given` in `args.py` 217 | `True` | rem `IStr` from `'af_report_year'` |
| | `False` | `TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given` in `args.py` 220 | `True` | rem `IStr` from `'af_rtb_fine_amount'` |
| | `False` | `TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given` in `args.py` 225 | `True` | rem `IStr` from `'af_fd_fine_amount'` |
| | `False` | `TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given` in `args.py` 690 | `True` | add `description` kw to `'description'` | 
| | `False` | `TypeError: __init__() got an unexpected keyword argument 'ordered'` (marshmallow-pagination) | `True` | downgraded to `marshmallow@2.20.5` | 
| | `False` | `apispec.exceptions.DuplicateParameterError: Duplicate parameter with name calendar_category_id and location query` | `True` | downgrade to `apispec@1.3.3` | 
|1.3.3| `False` | `tests/test_swagger.py ..F` (`openapi_spec_validator.exceptions.OpenAPIValidationError`) | `False` | inspect `localhost` |
|1.3.3| `False` | `api_key` field does not render | n/a | restore `required=True` to `API_KEY_ARG` 
|2.0.0|
|2.0.1|
|2.0.2|

**Comment by jason-upchurch** [comment]
as of 9/27/2019 the changes in the completed table with the additional toying around with `basePath` argument modification in `spec.py` allows the local api to be run. In incognito mode the rendering does not look correct, but unsure if this is a function of any spec changes (non-incognito mode seems to render fine). 

Current approach with
