### ISSUE TITLE
Only keep four months of raw filings data in PG

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3789]
**What we're after**: We need to develop an overall strategy to improve raw filing performance

Ideas:

1) Reduce volume of data: We only need to keep a certain amount of raw filing data beyond a certain point. We need to get a clarification on what that time period is exactly. Once we determine how far back we need to go, we should clear out unneeded raw filing data.
2) Add indexes

Raw vs. processed filters documentation: 🔒 https://docs.google.com/document/d/16DWIquTYpbdtCCDrXYLXXRrHQXS51sX_8cLY75spLA0/ 🔒 

**Related issues**:
https://github.com/fecgov/openfec/issues/3627
https://github.com/fecgov/openfec/issues/3636

Things to consider: 
- [x] How much raw filings data should we keep in API
- [ ] Make a new ticket to check if the database performance for efiling improve after removing legacy data. Include a list of datatables that display raw data.

**Comment by AmyKort** [comment]
@PaulClark2 and I met to discuss. Paul will reach out to the Press Office and Public Records to confirm we aren't aware of situations where users would look at raw filings that are more than one year old.

**Comment by PaulClark2** [comment]
We only need to keep three months of raw electronic data. 

To do: 
- [ ] ask Salient to modify their upload process to include deleting data older than three months
- [ ] will this cause short-term problems for the read-replicas

**Comment by PaulClark2** [comment]
Discussed this with the Press Office. They are good with keeping as little as 3 months of electronic filing data.

**Comment by lbeaufort** [comment]
Thanks @paul! Re: read-replica issues, we could possibly do this off-hours to minimize performance impact.

**Comment by lbeaufort** [comment]
From @rjayasekera 

>Today I talked with Mahi about deleting eFile/pFile records prior to 5/1/2019 from AWS-DEV instance.  He is currently busy with processing large amount of ActBlue amendments (about 25 mil records). He can get to this task after that, probably 1st or 2nd week of August.

**Comment by PaulClark2** [comment]
Salient will start working this Tuesday, 9/3

**Comment by PaulClark2** [comment]
Salient is working on this.

**Comment by PaulClark2** [comment]
Mahi and Rohan will start testing the delete process on DEV. We'll delete 5,000 reports per day during this test.

**Comment by patphongs** [comment]
Still troubleshooting deletion process for all raw filings greater than 4 months. Moving to 10.2 to be completed then.

**Comment by patphongs** [comment]
Right now we have 9 months of data for raw filing. We would like to delete and only keep 4 months of data.

**Comment by PaulClark2** [comment]
Closing in favor of https://github.com/fecgov/openFEC/issues/4004
