### ISSUE TITLE
Add test coverage for CandidateTotalsView

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3806]
## Summary ##
Related to #3768 add test coverage for the `/candidates/totals/` view. PR #3803 actually tests the `/candidates/` endpoint.

**Comment by lbeaufort** [comment]
@jason-upchurch if it's ok with you I'd like to work on this and also add test coverage for the PR 4-year cycle totals in https://github.com/fecgov/openFEC/issues/3709
