### ISSUE TITLE
Research: Add connected org to committee history

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3807]
Per @PaulClark2, "Connected organization" should be included with the information on the "about this committee tab" of all SSFs. These committees have connected organizations: C00053553, C00002089, C00096156, C00029447, C00007922.

Example API call: https://api.open.fec.gov/v1/committee/C00053553/history/?per_page=1&api_key=DEMO_KEY

Resource: `CommitteeHistoryView`

**Completion criteria**
- [x] Add `connected_organization` to `/committee/<ID>/history/`
- [x] Open up a front-end ticket to add "Connected organization" to "About this Committee" page for SSFs fecgov/fec-cms#3024

**Comment by PaulClark2** [comment]
Might want to consider this issues while considering or working on this issue

- Investigate leadership PAC sponsor inconsistencies on forms 1 and 1S
- https://github.com/fecgov/openFEC/issues/3433

- Add org type, designation to Schedule A datatables (use F1 Line 6 information to determine nonconnected and membership)
- https://github.com/fecgov/openFEC/issues/3787

**Comment by lbeaufort** [comment]
Resource: `committees.CommitteeHistoryView`
Model: `models.CommitteeHistory` inherits from `BaseCommittee`
MV: `ofec_committee_history_mv`

I think we need to bring `fec_vsum_f1_vw.affiliated_cmte_nm` into `ofec_committee_history_mv`
