### ISSUE TITLE
candidate_inactive column in ofec_candidate_detail_mv does not include historical data

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3810]
Candidate_inactive column in ofec_candidate_detail_mv does not include historical data.  
That is, this MV takes the latest information per candidate.  However, candidate_inactive should be based on a specific election_year.  An example is a candidate ('S6AZ00019') who is active at 2016 cycle, but his/her latest information is from 2022, which he/she is inactive.  So when search from the candidates on 2016, it is considered inactive, while in candidate_totals it is marked active for 2016 cycle.

@hcaofec has an excellent idea to add a column that is an array which has all the inactive year for that candidate.  This will require a MV change and API change on how this will be used.  A follow up ticket will be created after all work done to drop the original column to avoid confusion.

**Completion criteria**
- [ ] add new column that holds a list of its inactive years for each candidate 
- [ ] change endpoints to compare with the new column when checking if the candidate is inactive for a particular election year 
- [ ] may need to add/change testing case

**Comment by hcaofec** [comment]
The endpoint and website behaves slight differently. S6AZ00019 is not shown on this result set:
https://api.open.fec.gov/v1/candidates/?sort_hide_null=false&sort_nulls_last=false&api_key=DEMO_KEY&office=S&page=1&state=AZ&sort=name&sort_null_only=false&per_page=20&election_year=2016&party=REP&is_active_candidate=true

But can be seen here.  Looks like website does not pass "is_active_candidate" to api, so it gets all candidates.
https://www.fec.gov/data/candidates/?election_year=2016&office=S&party=REP&state=AZ

**Comment by hcaofec** [comment]
Things to note here:
There is no connection between historical cycle and candidate_inactive.  When other than current FEC cycles ( 2018, 2016, 2014...etc) are passed to endpoint, there is no way for endpoint to check the candidate_active status for that particular cycle in ofec_candidate_detail_mv.   candidate_inactive is associated with election_year directly.  Maybe remove cycle filter from endpoint?
