### ISSUE TITLE
Add filters to /schedules/schedule_e/efile

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3813]
(/schedules/schedule_e/efile/)

So that we can implement fec-cms/#2899 we need to add filters to the API

Filter options should include
- [x] Spender name
- [x] Candidate name or ID
- [x] Support/Oppose
- [x] Candidate office state
- [x] Candidate office district
- [x] Candidate party
- [x] Candidate office
- [x] Filing date (F24 or F5 filing date)
- [x] Expenditure date
- [x] (maybe) Dissemination date
- [x] Most recent (match filings filter)

**Completion Criteria**
- [x] Figure out how difficult these filters are to add - are some easier than others?
- [x] Add the filters
- [x] Add tests for each one of the filter

**Comment by pkfec** [comment]
Had a brief discussion about the new efile filters with @hcaofec yesterday. @hcaofec is making changes to  a `real_efile_se_f57_vw` to add `candidate_party` and `most_recent`filter since these two do not exist in the current view.
Need to determine which which filters we want to be multi vs single.  I will check with @paulClark2 on this today.

**Comment by PaulClark2** [comment]
@pkfec I had a chance to look at candidate ID/candidate name data of electronically filed 24- and 48-hour reports of independent expenditures. 

- Looking at report year 2018, Form 3X (Form 24/Schedule E) filers submitted 29,019 SE transactions on  24- and 48-hour reports of IEs. Approximately 14% do not have candidate IDs.
- Looking at report year 2018, Form 5 (Form 5/Form 57) filers submitted 10,864 F57 transactions on  24- and 48-hour reports of IEs. Approximately 17% do not have candidate IDs.

What would be the best way to allow users to search for both candidate IDs and candidate name? Is is possible to pass both? In other words, if I search for Pelosi can we send to the API cand_id = "H8CA05035" or  cand_name like 'PELOSI'?

`select S.SO_CANID, S.SO_CAN_NAME , S.SO_CAN_OFF , S.SO_CAN_STATE , S.SO_CAN_DIST
from REAL_EFILE.REPS r, REAL_EFILE.SE s
where r.repid = s.repid
and r.form like 'F24%'
and R.FILED_DATE between '01-JAN-2018' and '31-DEC-2018'
and S.SO_CANID is null;`

`4,052`

`select S.SO_CANID, S.SO_CAN_NAME , S.SO_CAN_OFF , S.SO_CAN_STATE , S.SO_CAN_DIST
from REAL_EFILE.REPS r, REAL_EFILE.SE s
where r.repid = s.repid
and r.form like 'F24%'
and R.FILED_DATE between '01-JAN-2018' and '31-DEC-2018';`

`29,019`

`select S.SO_CANID, S.SO_CAN_NAME , S.SO_CAN_OFF , S.SO_CAN_STATE , S.SO_CAN_DIST 
from REAL_EFILE.F5 f, REAL_EFILE.F57 s
where f.repid = s.repid
and f.rptcode is null 
and f.h_code in ('24', '48')
and ((sign_date between '01-JAN-2018' and '31-DEC-2018') or (through_date between '01-JAN-2018' and '31-DEC-2018'))
and S.SO_CANID is null;`

`1,887`

`select S.SO_CANID, S.SO_CAN_NAME , S.SO_CAN_OFF , S.SO_CAN_STATE , S.SO_CAN_DIST 
from REAL_EFILE.F5 f, REAL_EFILE.F57 s
where f.repid = s.repid
and f.rptcode is null 
and f.h_code in ('24', '48')
and ((sign_date between '01-JAN-2018' and '31-DEC-2018') or (through_date between '01-JAN-2018' and '31-DEC-2018'));`

`10,864`

**Comment by patphongs** [comment]
Check with @PaulClark2 about when we can expect the efiling database table to be trimmed down. This may help to improve this endpoint, needs more investigation.

**Comment by PaulClark2** [comment]
@patphongs @pkfec I think we can start working on removing data from the efiling endpoints at the end of the first week of August or beginning of the second week of August. We need to process all the mid-year data. 

Our plan is to keep just three months of data in the efiling tables.

@pkfec did my comment about name and ID search make sense? `What would be the best way to allow users to search for both candidate IDs and candidate name? Is is possible to pass both? In other words, if I search for Pelosi can we send to the API cand_id = "H8CA05035" or cand_name like 'PELOSI'?`

**Comment by pkfec** [comment]
@PaulClark2 Yes, we can search by both candidate name or id. Everytime we search by either one, only ID is passed to the API.  CMS is handling this on the front-end. We can apply the same logic to the candidate name/ID filter on the CMS side. please check the spender name section of IE's. Hope this helps.

For example, In production, if we search for a spender/committee with a name`Laborers`, a list of spender id's along the names pop up. But on the API call, we only see the committee_id being passed and NOT the name. Please check the screenshot attached below. 

cc @patphongs 

api call : https://api.open.fec.gov/v1/schedules/schedule_e/?api_key=oXyFx4md0kTkxxq9JNfIRlrOPorXc60dqOVEs4GE&sort_hide_null=false&sort_nulls_last=true&data_type=processed&committee_id=C00007922&is_notice=false&sort=-expenditure_date&per_page=30

CMS screenshot:
<img width="1435" alt="Screen Shot 2019-07-26 at 6 52 44 AM" src="https://user-images.githubusercontent.com/11650355/61947152-796f9880-af72-11e9-939f-99e434d378cc.png">

**Comment by pkfec** [comment]
Filters | PG DB | API 
------------ | ------------- | -------------
None | 14.07 mins | 22.8 sec
spender name  | 6.90 sec | 7.44 sec
suppose/oppose | 7.21 mins | 14.5 sec
candidate office state  |  | 21.3 sec
candidate id  | 6.90 sec | 7.44 sec
spender name  | 6.90 sec | 7.44 sec
spender name  | 6.90 sec | 7.44 sec
spender name  | 6.90 sec | 7.44 sec
spender name  | 6.90 sec | 7.44 sec
spender name  | 6.90 sec | 7.44 sec
spender name  | 6.90 sec | 7.44 sec
spender name  | 6.90 sec | 7.44 sec
spender name  | 6.90 sec | 7.44 sec

**Comment by PaulClark2** [comment]
@pkfec thank you for the explanation. Because candidate ID is often null in transactions of 24- and 48-hour reports , can we pass both the ID and the name, text string, the user types in? Or the ID and the last name of the candidate as a text string?  I know we’d be passing in information to two filters instead of one.  Is that even possible?

**Comment by pkfec** [comment]
Yes, technically we can do it.  After talking to @fecjjeng and @hcaofec it appears that we have to add a new tsvector column to the view `real_efile_se_f57_vw`. A new tsvector column would be a combination of Candidate ID and Candidate Name (first, last etc...). However on the flip side, we have to see how this new tsvector column would impact the performance, since the view is already slow as of now.

**Comment by PaulClark2** [comment]
Thanks @pkfec that’s good news.  So, the tsvector column would allow the user to retrieve transactions if there was a match on candidate ID, candidate name or partial candidate name?

**Comment by pkfec** [comment]
@PaulClark2 Do you want me to go ahead and implement this tsvector column on `real_efile_se_f57_vw` view in 9.6 Sprint?

**Comment by PaulClark2** [comment]
@pkfec yes, please do.

**Comment by pkfec** [comment]
@PaulClark2 thank you. I will seek @fecjjeng and @hcaofec help and implement the changes.

**Comment by pkfec** [comment]
Yesterday (07/30/2019) worked with @hcaofec and created a new TSVECTOR column on the a tmp view `real_efile_se_f57_vw_tmp_pk` in dev db. 

Today, mapped this new TSVECTOR column in the python itemized SE efile model, resource, args and schema files. 

candidate name # API 13.7 sec | DB 
candidate id # API
