### ISSUE TITLE
Update env variable FEC_EMAIL_RECIPIENTS and FEC_EMAIL_SENDER

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#3815]
Currently, when `cf env api` , These two variables are still 18f email. 
we need update these email addresses.
"FEC_EMAIL_RECIPIENTS": "xxxxxxxx@gsa.gov,xxxxxxxx@gsa.gov",
"FEC_EMAIL_SENDER": "fec-update-bot@18f.gov",

**Comment by lbeaufort** [comment]
Nice catch, @fec-jli! Also if they’re not being used, we could delete them.

**Comment by pkfec** [comment]
18f created these environment variables to notify team about the nightly job statuses. We upgraded to slack alerts so therefore we no longer require above environment variables.

**Comment by pkfec** [comment]
Came across MANDRILL_API_KEY env variable which is not used in cms, api, eregs apps. 
- `Mandrill is an email infrastructure service designed to help applications or websites that need to send transactional email like password resets, order confirmations, and welcome messages.`
- We use slack for as your application alerts monitoring service.` 

I have removed this env from `dev` space and rerun the latest `develop` circle build which gets deployed to `dev` space. I will continue to test the `dev` website and API to see if there are any issues in the logs after removing `MANDRILL_API_KEY` env variable.

**Comment by JonellaCulmer** [comment]
Closing in favor of #4238
