### ISSUE TITLE
Itemized contributions being double-counted for two candidates in "by size" breakdown

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3816]
Derived from https://github.com/fecgov/openFEC/issues/3777, which has a script that adds these aggregates together for totals. 

It looks like these candidates have filed pre-special election reports, and their unitemized totals are being counted twice.

** Checking: H0PA12181, KELLER, FRED in prod. Election year is 2020. **

By size: https://api.open.fec.gov/v1/schedules/schedule_a/by_size/by_candidate/?candidate_id=H0PA12181&cycle=2020&election_full=False&per_page=20&api_key=DEMO_KEY

By state: https://api.open.fec.gov/v1/schedules/schedule_a/by_state/by_candidate/?per_page=150&page=1&candidate_id=H0PA12181&cycle=2020&election_full=False&api_key=DEMO_KEY

Candidate ID totals: https://api.open.fec.gov/v1/candidate/H0PA12181/totals?cycle=2020&full_election=False&api_key=DEMO_KEY

unitemized total: $29,658.69
raw by_size_total: $517,059.18
adjusted by_size_total: $487,400.49
by_state_total: $457,741.80
...
difference: $-29,658.69

** Checking: H8NC09123, MCCREADY, DANIEL in prod. Election year is 2020. **

By size: https://api.open.fec.gov/v1/schedules/schedule_a/by_size/by_candidate/?candidate_id=H8NC09123&cycle=2020&election_full=False&per_page=20&api_key=DEMO_KEY

By state: https://api.open.fec.gov/v1/schedules/schedule_a/by_state/by_candidate/?per_page=150&page=1&candidate_id=H8NC09123&cycle=2020&election_full=False&api_key=DEMO_KEY

Candidate ID totals: https://api.open.fec.gov/v1/candidate/H8NC09123/totals?cycle=2020&full_election=False&api_key=DEMO_KEY

unitemized total: $707,665.35
raw by_size_total: $3,676,182.10
adjusted by_size_total: $2,968,516.75
by_state_total: $2,260,851.40
...
difference: $-707,665.35

**Comment by lbeaufort** [comment]
I split the remaining work into a follow-up ticket: https://github.com/fecgov/openFEC/issues/3816

**Comment by hcaofec** [comment]
After comparing endpoint with aggregate tables,  and reviewing the endpoint logic, it looks like both endpoints /schedules/schedule_a/by_state/by_candidate/,  /schedules/schedule_a/by_size/by_candidate/ are returning doubled totals for these two candidates.  Both candidates have special election in 2019, there two rows for each of them in cand_cmte_linkage_mv in same fec_election_year.  When aggregated tables join cand_cmte_linkage_mv on candidate_id and fec_cycle,  the result will have duplicated rows. 

**Cand_cmte_linkage_mv**
<img width="824" alt="Screen Shot 2019-07-17 at 4 22 18 PM" src="https://user-images.githubusercontent.com/24396726/61408927-2d0bc500-a8af-11e9-8699-13445defce9e.png">

**by_size total from table:**
<img width="641" alt="Screen Shot 2019-07-17 at 4 32 48 PM" src="https://user-images.githubusercontent.com/24396726/61409708-d0a9a500-a8b0-11e9-924e-bfebf4693668.png">

**by_size from endpoint**
<img width="373" alt="Screen Shot 2019-07-17 at 4 43 23 PM" src="https://user-images.githubusercontent.com/24396726/61410363-1b77ec80-a8b2-11e9-9072-f49f32dcf430.png">

**Comment by hcaofec** [comment]
**by_size total from table:**
<img width="586" alt="Screen Shot 2019-07-17 at 4 57 42 PM" src="https://user-images.githubusercontent.com/24396726/61411285-08661c00-a8b4-11e9-9e5d-3965c0e884c7.png">

**by_size from endpoint**
<img width="394" alt="Screen Shot 2019-07-17 at 4 58 40 PM" src="https://user-images.githubusercontent.com/24396726/61411356-34819d00-a8b4-11e9-966f-19cc279b346a.png">

**Comment by hcaofec** [comment]
Here is the latest comparison result:

**H0PA12181, KELLER, FRED in prod. Election year is 2020**
Candidate ID totals: https://api.open.fec.gov/v1/candidate/H0PA12181/totals?cycle=2020&full_election=False&api_key=DEMO_KEY

- "individual_itemized_contributions":      362043.0,
-  "individual_unitemized_contributions": 75417.77


endpoint | sum(totals) | remove_double
------------ | ------------- | ----------
by_size (item+unitem) | 851287.58 | 425643.79
by_state(item only)| 700452.04| 350226.02

**425643.79 - 350226.02 = 75417.77** . ---- matches Candidate ID totals

**After removing the doubles**
unitemized total: $75417.77
raw by_size_total: $425643.79
adjusted by_size_total: $350226.02
by_state_total: $350226.02

**Comment by hcaofec** [comment]
PR is merged.
