### ISSUE TITLE
Add filters and output fields to /schedules/schedule_e/ (Processed data)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3817]
(/schedules/schedule_e/)

Filter options should include
- [x] Filing date (F24 or F5 filing date) (min/max) **Also needs output field like efile endpoint**
- [x] Dissemination date (min/max)
- [ ] ~Most recent (match filings filter) **Also needs output field like efile endpoint**~ 
most recent filter work is moved to next sprint 10.5. 
API  work will be tracked in the new issue  https://github.com/fecgov/openFEC/issues/4058
DB work will tracked in issue #4056 

**Previous work**
#3813 

**Completion criteria**
- [x] Add the missing fields to output
- [x] Add filters
- [x] Update automated tests

**Comment by pkfec** [comment]
`ofec_sched_e_mv` should be updated to include the `most_recent` and `filing_date` columns. I will reach out to @hcaofec or @fecjjeng for help to update the MV .

**Comment by fecjjeng** [comment]
In summary, for F3X and F5 REGULAR REPORT, what is in ofec_sched_e_mv are most recent.  For F24 and F5 notice, we can not be sure what is most recent or not so we treat every one as an independent one.  Not sure if a most_recent column will help.

**Comment by fecjjeng** [comment]
The fiing_date (receipt_dt) in form and schedule tables are not always the same.  After discussed with @PaulClark2, it is the receipt_dt from the form we would like to show.
