### ISSUE TITLE
Add totals endpoint for /schedules/schedule_a/by_state/by_candidate 

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3819]
So that we can show totals for the "Where contributions come from" map, we should add an endpoint that shows totals for /schedules/schedule_a/by_state/by_candidate endpoint

(FYI)
/schedule_a/by_state/ does not include itemized
/schedule_a/by_size/ includes unitemized

**Completion criteria:**
- [x] Name it `/schedules/schedule_a/by_state/by_candidate/totals`
- [x] Endpoint should only show itemized totals
- [x] Needs to support `election_full`. Example call for subtotals: https://api.open.fec.gov/v1/schedules/schedule_a/by_state/by_candidate/?api_key=DEMO_KEY&candidate_id=P80001571&cycle=2020&per_page=99&election_full=true&sort=-total

**Comment by jason-upchurch** [comment]
refs:
- technical reference for creating endpoint: https://github.com/fecgov/openFEC/wiki/Create-an-endpoint
- recent implementation of endpoint https://github.com/fecgov/openFEC/pull/3593

**Comment by jason-upchurch** [comment]
high-level components:
- model
- args
- schema
- resource 
- url
- test

**Comment by jason-upchurch** [comment]
duplicating `/schedules/schedule_a/by_state/by_candidate/` endpoint with new name as a starting point

**Comment by jason-upchurch** [comment]
remaining task is modifying `candidate_aggregates.py` with correct grouping query.

**Comment by jason-upchurch** [comment]
query that produces the desired result:
```sql
select cand_id, cycle, sum(total) as total, sum(count) as count 
from (SELECT ofec_cand_cmte_linkage_mv.cand_id, ofec_cand_cmte_linkage_mv.fec_election_yr 
AS cycle, ofec_sched_a_agg_state_vw.state, sum(ofec_sched_a_agg_state_vw.total) 
AS total, max(ofec_sched_a_agg_state_vw.state_full) 
AS state_full, ofec_sched_a_agg_state_vw.count 
FROM ofec_cand_cmte_linkage_mv 
JOIN ofec_sched_a_agg_state_vw 
ON ofec_cand_cmte_linkage_mv.cmte_id = ofec_sched_a_agg_state_vw.cmte_id 
AND ofec_cand_cmte_linkage_mv.fec_election_yr = ofec_sched_a_agg_state_vw.cycle 
WHERE ofec_cand_cmte_linkage_mv.fec_election_yr IN (2020) 
AND ofec_cand_cmte_linkage_mv.cand_id IN ('P80001571') 
AND ofec_cand_cmte_linkage_mv.cmte_dsgn IN ('P', 'A') 
GROUP BY ofec_cand_cmte_linkage_mv.cand_id, ofec_cand_cmte_linkage_mv.fec_election_yr, ofec_sched_a_agg_state_vw.state, ofec_sched_a_agg_state_vw.count) 
as tmp group by cand_id, cycle;
```

**Comment by jason-upchurch** [comment]
Completed `sqlalchemy` work. Working on test cases for endpoint.

**Comment by jason-upchurch** [comment]
Completed test case and submitting for review for merge.
