### ISSUE TITLE
Add Line 25 to disbursement details filter

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3826]
### Summary

Users are not able to filter for party coordinated expenditures using the disbursement details filter group (Made by PACs or party committees) on https://www.fec.gov/data/disbursements/

### Expected Behavior

Users should be able to filter by Line 25 (Made by PACs or party committees)

### How to Reproduce
- navigate to https://www.fec.gov/data/disbursements/
- expand disbursement details filter group
- expand drop down of Made by PACs or party committees

### Screenshots

_Screenshots would help us correctly identify the issue._
![image](https://user-images.githubusercontent.com/11817734/59782712-94bcf900-928c-11e9-9498-848084788827.png)

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/fec-cms #3001](https://github.com/fecgov/fec-cms/issues/3001) via [**ZenHub**](https://www.zenhub.com/)
