### ISSUE TITLE
non-schedule_a and non-schedule_b tables: Update .*_text columns for tables with new tsvector

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3836]
## Summary ##
Throughout the db, former `TSVECTOR` columns that were generated upon insert to a `VARCHAR` column used the default `to_tsvector(<argument>)`, however, to make searching more predictable, the function was updated with an inner function argument to split on and strip nonword characters as:

```sql
to_tsvector(regexp_replace(<argument>, '[^a-zA-Z0-9]', ' ', 'g'))
```

The above was added to migration files under PR https://github.com/fecgov/openFEC/pull/3811 to handle future inserts. 

The historical db data also needs to be updated/refreshed to use the new `to_tsvector` definition.

The tables are:

| affected table |  column |  is_fixed | commit |
| ---                    | ---         | ---       | --- |
| `fec_fitem_sched_b` | `recipient_name_text` | `T` | b5e14b528018c7a5f1a634e02b68c611d1ebbc64 |
| `fec_fitem_sched_b` | `disbursement_description_text` | `T` | 7761a2c43382d99e517ace92d2e9237469629213 |
| `fec_fitem_sched_f` | `payee_name_text` | `T` | 7506c4e1d6b0e85ce4181a175145af2ff76896a9 |
| `fec_fitem_sched_a` | `contributor_name_text` | `T` | c6791504b743ae5708e26d21ae45331e56d96ce4 |
| `fec_fitem_sched_a` | `contributor_employer_text` | `T` | c6791504b743ae5708e26d21ae45331e56d96ce4 |
| `fec_fitem_sched_a` | `contributor_occupation_text` | `T` | c6791504b743ae5708e26d21ae45331e56d96ce4 |
| `fec_fitem_sched_c` | `loan_source_name_text` | `T` | a277d8d28827699efbca48384de4ae7737000d99 |
| `fec_fitem_sched_c` | `candidate_name_text` | `T` | a277d8d28827699efbca48384de4ae7737000d99 |
| `fec_fitem_sched_d` | `creditor_debtor_name_text` | `T` | 0363e407b15dc10421e4a620df7411fcb7f4a039 |

The migration file handling this update is `V0142__update_to_tsvector_function_over_all_columns.sql`

**Comment by fecjjeng** [comment]
tsvector columns in fec_fitem_sched_a and fec_fitem_sched_b tables had been updated according to the new definition in issue #3787
tsvector columns in fec_fitem_sched_c, fec_fitem_sched_d, and fec_fitem_sched_f have been updated in all cloud environments (DEV/STG/PRD).  @jason-upchurch It is ready for you to check if the desired changes is in place.

**Comment by jason-upchurch** [comment]
@fecjjeng thank you so much for making this change! It looks great! 🎉

**Comment by fecjjeng** [comment]
Database work done.  No PR needed.  Closed ticket.
