### ISSUE TITLE
Check logs sprint 9.4 week 2

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#3839]
Log review needs to be completed for sprint 9.4 week 2 per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by fec-jli** [comment]
**Vulnerabilities found this week**
**FEC-CMS: Total 2**
package.json: 2 HIGH
Prototype Pollution: https://github.com/fecgov/fec-cms/issues/3021
Prototype Pollution: https://github.com/fecgov/fec-cms/issues/3022

requirements.txt: 1 MED, 1 LOW
 Man-in-the-Middle (MitM) https://github.com/fecgov/fec-cms/issues/3023
Cross-site Scripting (XSS)(django) : LOW fecgov/fec-cms#2944

**OPENFEC: 0**
package.json: 0
requirements.txt: 0
data/flyway/build.gradle: 0

**FEC-EREGS: 0**
package.json: 0
requirements.txt: 0

**FEC-PATTERN-LIBRARY: 0**
package.json: 0

Users changed this week or last:  
Search logs: No new users added/removed
Cloud.gov Dashboard: 9 deployer accounts, same as last week.

**Comment by fec-jli** [comment]
This is done. closed.
