### ISSUE TITLE
Check logs sprint 9.5 week 2

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#3855]
Log review needs to be completed for sprint 9.5 week 2 per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by pkfec** [comment]
**Vulnerabilities found on 07/25/2019**

**FEC-CMS: Total 4**

- package.json: 2 HIGH
- Prototype Pollution: https://github.com/fecgov/fec-cms/issues/3021
- Prototype Pollution: https://github.com/fecgov/fec-cms/issues/3022

requirements.txt: 1 HIGH, 1 LOW

-  Man-in-the-Middle (MitM) (HIGH): https://github.com/fecgov/fec-cms/issues/3023
- Cross-site Scripting (XSS)(django) (LOW)): https://github.com/fecgov/fec-cms/issues/2944

**OPENFEC: Total 0**

- package.json: 0
- requirements.txt: 0
- data/flyway/build.gradle: 0

**FEC-EREGS:  Total 0**

- package.json: 0
- requirements.txt: 0

**FEC-PATTERN-LIBRARY:  Total 0**

- package.json: 0

**Users changed this week or last**:  Search kibana logs: No new users added/removed
**Cloud.gov Dashboard**: 9 deployer accounts, same as last week.

**Comment by pkfec** [comment]
Completed week2 log review on 07/25/2019.
