### ISSUE TITLE
investigate election_full flag for schedules/schedule_a/by_state/by_candidate/

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3865]
## Summary ##
querying same endpoint with `election_full=True` yields smaller number than `election_full=False`. This is counterintuitive because the `election_full` logic should aggregate two cycles together.

## Steps to reproduce ##
- "https://api.open.fec.gov/v1/schedules/schedule_a/by_state/by_candidate/?api_key=DEMO_KEY&candidate_id=P00003392&cycle=2014&per_page=200&election_full=true&sort=-total"
yields 0
- "https://api.open.fec.gov/v1/schedules/schedule_a/by_state/by_candidate/?api_key=DEMO_KEY&candidate_id=P00003392&cycle=2014&per_page=200&election_full=false&sort=-total"
yields 3450.0

**Comment by patphongs** [comment]
This is not an issue, `election_full=true` on a non-election year should yield 0 counts, meaning no results.
