### ISSUE TITLE
Clean some unused views and MVs for F3,F3P,F3X

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#3866]
After done with PR [https://github.com/fecgov/openFEC/issues/3844](https://github.com/fecgov/openFEC/issues/3844), there are some views and MVs we don't need. We should double check them and clean them.
Here are the list:

- [x] public.ofec_report_pac_party_all_vw
- [x] public.ofec_report_pac_party_all_mv
- [x] ofec_reports_pacs_parties_mv
- [x] ofec_reports_pacs_parties_vw
- [x] Remove these objects from nightly refresh job if there is any

These three views will not be deleted:
public.fec_vsum_f3_vw
public.fec_vsum_f3p_vw
public.fec_vsum_f3x_vw

**Comment by fecjjeng** [comment]
The fec_vsum_xxx_vw views are a whole set of views that originally created for internal users to do a quick check and/or a template for queries used in MVs and other views.  We would like to keep the three fec_vsum_fxx_vw mentioned in this ticket.  The usefulness of the whole sets of fec_vsum_xxx_vw will be evaluated as a set.

**Comment by hcaofec** [comment]
PR is merged, so closing.
