### ISSUE TITLE
Only strip out login-related Flyway error messages

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3869]
Follow up to #3827, we stripped out postgres error messages but this has made troubleshooting failed builds more difficult. In [remove credentials](https://github.com/fecgov/openFEC/blob/develop/jdbc_utils.py#L26) we should only strip out the messages for login-specific error codes and output the whole error message for other codes.

**Comment by jason-upchurch** [comment]
List of `postgres@9.6` errors: https://www.postgresql.org/docs/9.6/errcodes-appendix.html
