### ISSUE TITLE
[Merge to release 9.4] Fix ofec_reports_xxxxxxx_mvs refresh flow

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#3871]
Below three reporting MVs use **ofec_filings_amendments_all_mv**
ofec_reports_house_senate_mv
ofec_reports_presidential_mv
ofec_reports_pac_party_mv 

we need adjust the refresh order of them.

**Comment by lbeaufort** [comment]
PR has been merged to the release, thanks! https://github.com/fecgov/openFEC/pull/3873
