### ISSUE TITLE
Two entries per state from schedule_a/by_state/by_candidate when election_full=true

### ISSUE THREAD

**Issue by rfultz** [fecgov/openFEC#3874]
When I call `schedule_a/by_state/by_candidate` and `schedule_a/by_size/by_candidate` with `election_full=true`, I get two entires for each state but with different values. I'm guessing it's for the first two years of a presidential cycle and then for the second two years.

Examples: 
- by size: https://api.open.fec.gov/v1/schedules/schedule_a/by_size/by_candidate/?api_key=DEMO_KEY&sort_hide_null=false&election_full=true&sort_nulls_last=false&per_page=20&candidate_id=P00003392&page=1&sort_null_only=false&cycle=2016
- by state: https://api.open.fec.gov/v1/schedules/schedule_a/by_state/by_candidate/?api_key=DEMO_KEY&sort_hide_null=false&election_full=true&sort_nulls_last=false&per_page=20&candidate_id=P80001571&page=1&sort_null_only=false&cycle=2020&per_page=200

**Comment by hcaofec** [comment]
A PR https://github.com/fecgov/openFEC/pull/3879 was submitted for this issue.

**Comment by hcaofec** [comment]
PR is merged, so this ticket is closed.
