### ISSUE TITLE
determine if dsc_sched_a_aggregate_employer aggregates as intended

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3885]
## Summary ##
The aggregate endpoint below does not appear to correctly match the sum of the individual components:
* CASE 1:
https://api.open.fec.gov/v1/schedules/schedule_a/by_employer/?page=1&cycle=2020&employer=amazon.com&sort_null_only=false&sort_hide_null=false&sort_nulls_last=false&per_page=20

```json
{
  "api_version": "1.0",
  "results": [
    {
      "cycle": 2020,
      "employer": "AMAZON COM",
      "count": 2,
      "committee_id": "C00003418",
      "total": 3.75
    }
  ],
  "pagination": {
    "per_page": 20,
    "page": 1,
    "pages": 1,
    "count": 1
  }
}
```

CASE 2:
```sql
select * from disclosure.fec_fitem_sched_a 
where contributor_employer_text @@ to_tsquery('amazon:* & com:*') 
AND two_year_transaction_period = 2020AND cmte_id = 'C00003418';
```
returns

| `cmte_id` | `two_year_transaction_period` | `contbr_employer` | `contb_receipt_amt` |
| ---  | ---  | --- | --- |
| C00003418 |  2020 | AMAZON COM | 1.25 |
| C00003418 |  2020 | AMAZON COM | 2.50 |
| C00003418 |  2020 | AMAZON.COM | 25.00 |

Note the last row contains the "." in the `contbr_employer` field. It appears that `dsc_sched_a_aggregate_employer` might aggregate by identical `contbr_employer` values. Users searching for "employer" may in the case of `/schedules/schedule_a/` need to use `contributer_employer` which makes use of the `TSVECTOR` field, while in the case of `/schedules/schedule_a/by_employer/` need to use `employer` which is a `VARCHAR` field.

from `V0015__disclosure_schema_objects.sql`:
```sql
CREATE TABLE dsc_sched_a_aggregate_employer (
    cmte_id character varying(9),
    cycle numeric,
    employer character varying(38),
    total numeric,
    count bigint,
    idx integer DEFAULT nextval('public.ofec_sched_a_aggregate_employer_idx_seq1'::regclass) NOT NULL
);
```

from `aggregates.py`
```python
class ScheduleAByEmployer(BaseAggregate):
    __table_args__ = {'schema': 'disclosure'}
    __tablename__ = 'dsc_sched_a_aggregate_employer'
    employer = db.Column(db.String, primary_key=True, doc=docs.EMPLOYER)
```

## Problem ##

In the specific case documented above, the user searched for `AMAZON.COM` and the aggregates returned were `AMAZON COM`, while the particular entry omitted from the aggregate was the searched element, i.e., `AMAZON.COM`.

### Completion Criteria
Need to determine:
- [ ] is the identified "problem" acceptable as is, or should the returned element at least contain the searched term
- [ ] open specific issue as needed to address problem
- [ ] audit other endpoints to determine similar behavior

**Comment by fec-jli** [comment]
blocked by [https://github.com/fecgov/openFEC/issues/5739](https://github.com/fecgov/openFEC/issues/5739)
