### ISSUE TITLE
[Snyk: High] urllib3 vulnerability [due 9/5/2019]

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3893]
## Summary ##
https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174323:
```
High severity vulnerability found in urllib3
  Description: CRLF injection
  Info: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174323
  Introduced through: elasticsearch@5.5.1, requests@2.21.0, elasticsearch-dsl@5.4.0, prance@0.15.0, smart-open@1.7.1
```

https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174464:
```
High severity vulnerability found in urllib3
  Description: Improper Certificate Validation
  Info: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174464
  Introduced through: elasticsearch@5.5.1, requests@2.21.0, elasticsearch-dsl@5.4.0, prance@0.15.0, smart-open@1.7.1
```

**Comment by pkfec** [comment]
urllib3 CRLF injection vulnerability has been fixed in 1.24 series and released as 1.24.3.
see more:urllib3/urllib3#1553

Our development environment is already running on the latest release of urllib3 v1.24.3 package.
No need to make any changes. Closing this issue.
