### ISSUE TITLE
Limit query variables for certain fields

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3902]
Set up 10 filter limit for filters with performance issues.

**Completion criteria**
**Schedule A endpoint (schedules/schedule_a/):** 
- [ ] Limit 10 for:
- Name - `contributor_name`
- Zip - `contributor_zip`
- City - `contributor_city`
- Occupation - `contributor_employer`
- Employer - `contributor_occupation`

**Schedule B endpoint (schedules/schedule_b/):** 
- [ ] Limit 10 for:
- Recipient name or ID - `recipient_name` (takes ID or name)
- City  - `recipient_city`

**Schedule E endpoint (schedules/schedule_e/):** 
- [ ] Limit 10 for:
- Candidate name or ID (`candidate_id`)

We only seeing this many names and zip codes passed into a single query on 8/8 and 8/9/2019.  (during the media ask public to go to fec.gov and query contributors by name or zip code).  **Database performance is not an issue if this type of queries happening occasionally.**

Following are the sample queries:

**Names Query**
select * 
FROM disclosure.fec_fitem_sched_a 
	WHERE disclosure.fec_fitem_sched_a.is_individual = true AND disclosure.fec_fitem_sched_a.contb_receipt_dt <= '2020-12-31'::date AND (disclosure.fec_fitem_sched_a.contributor_name_text @@ to_tsquery('Ware:* & Adams:*') OR disclosure.fec_fitem_sched_a.contributor_name_text @@ to_tsquery('Scott:* & Allen:*') OR disclosure.fec_fitem_sched_a.contributor_name_text @@ to_tsquery('Mark:* & Alderman:*') OR disclosure.fec_fitem_sched_a.contributor_name_text @@ to_tsquery('John:* & Aldock:*') OR disclosure.fec_fitem_sched_a.contributor_name_text @@ to_tsquery('Adrienne:* & Arsht:* & Elizabeth:* & Bagley:* & Jean:* & Bailey:* & Barbara:* & Bainum:* & Bruce:* & Bainum:* & Stewart:* & Bainum:* & Tomi:* & Bannister:* & Maurice:* & Bellan:* & Georgia:* & Berner:* & Megan:* & Beyer:* & Elizabeth:* & Birch:* & Tim:* & Broas:* & Anthony:* & Brown:* & Kathy:* & Brown:* & David:* & Burd:* & Dwight:* & amp:* & Toni:* & Bush:* & Wilfried:* & Busse:* & Roel:* & Campos:* & Stephen:* & and:* & Molly:* & Cashin:* & Hester:* & Clark:* & David:* & and:* & Rhonda:* & Cohen:* & Belinda:* & Coleman:* & Steve:* & and:* & Sandy:* & Cozen:* & Kelly:* & Craighead:* & Jehan:* & Christopher:* & De:* & La:* & Haye:* & Saint:* & Hilaire:* & Ted:* & Dintersmith:* & John:* & Duff:* & Jay:* & Dunn:* & David:* & Ferleger:* & Josh:* & and:* & Genine:* & Fidler:* & Joseph:* & amp:* & Marie:* & Field:* & Morton:* & amp:* & Norma:* & Lee:* & Funger:* & Matthew:* & amp:* & Marie:* & Garfield:* & Glenn:* & Gerstell:* & Carol:* & amp:* & Hank:* & Goldberg:* & Stuart:* & and:* & Suzanne:* & Grant:* & Ernest:* & Green:* & Keith:* & Harper:* & Scott:* & Harris:* & David:* & Hill:* & Jeffrey:* & Hoffman:* & Richard:* & Horowitz:* & Emmanuel:* & amp:* & Ogay:* & Irono:* & Frank:* & Islam:* & Kenneth:* & Jarin:* & Joseph:* & Kaempfer:* & Carolyn:* & Kaplan:* & Warren:* & Kaplan:* & Dan:* & and:* & Sunita:* & Leeds:* & Jeff:* & and:* & Cal:* & Leonard:* & Bel:* & Leong:* & Hong:* & Cliff:* & Levine:* & Rob:* & Liberatore:* & Terry:* & Terence:* & McAuliffe:* & Gerry:* & McGowan:* & David:* & McKean:* & Thomas:* & McLarty:* & Tom:* & McMillen:* & Lamell:* & McMorris:* & Nathan:* & Milikowsky:* & Judith:* & Miller:* & Constance:* & Milstein:* & Brenda:* & and:* & Mark:* & Moore:* & Thomas:* & and:* & Joyce:* & Moorehead:* & Faith:* & Morningstar:* & Jim:* & and:* & Bruce:* & Murray:* & Shekar:* & Narasimhan:* & Susan:* & Ness:* & Mark:* & Nichols:* & Peter:* & O:* & Keefe:* & Gov:* & Martin:* & O:* & Malley:* & Jo:* & Ousterhout:* & Spencer:* & Overton:* & Lazar:* & Palnick:* & Hilda:* & Pang:* & Fu:* & Shaunda:* & Patterson:* & Strachan:* & Carol:* & Pensky:* & John:* & Phillips:* & John:* & and:* & Mary:* & Register:* & John:* & Rezk:* & Adam:* & Riggs:* & Alfreda:* & Robinson:* & Cynthia:* & Ryan:* & Gabrielle:* & amp:* & Sunil:* & Sabharwal:* & Cynthia:* & Shapira:* & Rose:* & and:* & Cleveland:* & Slade:* & Sonjia:* & Smith:* & Earl:* & amp:* & Amanda:* & Stafford:* & George:* & Stevens:* & Ritchie:* & Tabachnick:* & Beth:* & Tomasello:* & Christy:* & amp:* & Scott:* & Wallace:* & Nancy:* & amp:* & Milton:* & Washington:* & John:* & Welch:* & Tom:* & Wheeler:* & Frank:* & White:* & Jr:* & Michael:* & Zeldin:*'));

**Zip codes query**

select * 
	FROM disclosure.fec_fitem_sched_a LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_1 ON disclosure.fec_fitem_sched_a.cmte_id = ofec_committee_history_mv_1.committee_id AND disclosure.fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_1.cycle LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_2 ON disclosure.fec_fitem_sched_a.clean_contbr_id = ofec_committee_history_mv_2.committee_id AND disclosure.fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_2.cycle 
	WHERE disclosure.fec_fitem_sched_a.contb_receipt_dt >= '2018-01-01'::date AND disclosure.fec_fitem_sched_a.contb_receipt_dt <= '2020-12-31'::date AND ((disclosure.fec_fitem_sched_a.contbr_zip LIKE '95589' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95573' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95571' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95570' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95569' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95565' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95564' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95562' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95560' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95559' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95558' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95556' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95555' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95554' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95553' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95551' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95550' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95549' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95547' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95546' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95545' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95542' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95540' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95537' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95536' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95534' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95528' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95526' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95525' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95524' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95521' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95519' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95518' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95514' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95511' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95503' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95502' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95501' || '%')) ORDER BY disclosure.fec_fitem_sched_a.contb_receipt_amt DESC, disclosure.fec_fitem_sched_a.sub_id DESC LIMIT 100;

### Completion Criteria
- [ ] add validation to schedules endpoints for 10 names/zips

**Comment by lbeaufort** [comment]
We'll need to talk to @PaulClark2 and @JonellaCulmer about what a reasonable number of names and/or zip codes to search at once looks like.

**Comment by lbeaufort** [comment]
This also caused IOPS alerts on 9/26:

```
duration: 4358.783 ms statement: COPY (SELECT disclosure.fec_fitem_sched_a.cmte_id AS committee_id, ofec_committee_history_mv.name AS committee_name, disclosure.fec_fitem_sched_a.rpt_yr AS report_year, disclosure.fec_fitem_sched_a.rpt_tp AS report_type, disclosure.fec_fitem_sched_a.image_num AS image_number, disclosure.fec_fitem_sched_a.line_num AS line_number, disclosure.fec_fitem_sched_a.tran_id AS transaction_id, disclosure.fec_fitem_sched_a.file_num AS file_number, disclosure.fec_fitem_sched_a.cmte_nm AS committee_name, disclosure.fec_fitem_sched_a.entity_tp AS entity_type, disclosure.fec_fitem_sched_a.entity_tp_desc AS entity_type_desc, disclosure.fec_fitem_sched_a.contbr_id AS unused_contbr_id, disclosure.fec_fitem_sched_a.contbr_prefix AS contributor_prefix, disclosure.fec_fitem_sched_a.contbr_nm AS contributor_name, disclosure.fec_fitem_sched_a.cmte_tp AS recipient_committee_type, disclosure.fec_fitem_sched_a.org_tp AS recipient_committee_org_type, disclosure.fec_fitem_sched_a.cmte_dsgn AS recipient_committee_designation, disclosure.fec_fitem_sched_a.contbr_nm_first AS contributor_first_name, disclosure.fec_fitem_sched_a.contbr_m_nm AS contributor_middle_name, disclosure.fec_fitem_sched_a.contbr_nm_last AS contributor_last_name, disclosure.fec_fitem_sched_a.contbr_suffix AS contributor_suffix, disclosure.fec_fitem_sched_a.contbr_st1 AS contributor_street_1, disclosure.fec_fitem_sched_a.contbr_st2 AS contributor_street_2, disclosure.fec_fitem_sched_a.contbr_city AS contributor_city, disclosure.fec_fitem_sched_a.contbr_st AS contributor_state, disclosure.fec_fitem_sched_a.contbr_zip AS contributor_zip, disclosure.fec_fitem_sched_a.contbr_employer AS contributor_employer, disclosure.fec_fitem_sched_a.contbr_occupation AS contributor_occupation, disclosure.fec_fitem_sched_a.clean_contbr_id AS contributor_id, disclosure.fec_fitem_sched_a.receipt_tp AS receipt_type, disclosure.fec_fitem_sched_a.receipt_tp_desc AS receipt_type_desc, disclosure.fec_fitem_sched_a.receipt_desc AS receipt_type_full, disclosure.fec_fitem_sched_a.memo_cd AS memo_code, disclosure.fec_fitem_sched_a.memo_cd_desc AS memo_code_full, disclosure.fec_fitem_sched_a.contb_receipt_dt AS contribution_receipt_date, disclosure.fec_fitem_sched_a.contb_receipt_amt AS contribution_receipt_amount, disclosure.fec_fitem_sched_a.contb_aggregate_ytd AS contributor_aggregate_ytd, disclosure.fec_fitem_sched_a.cand_id AS candidate_id, disclosure.fec_fitem_sched_a.cand_nm AS candidate_name, disclosure.fec_fitem_sched_a.cand_nm_first AS candidate_first_name, disclosure.fec_fitem_sched_a.cand_nm_last AS candidate_last_name, disclosure.fec_fitem_sched_a.cand_m_nm AS candidate_middle_name, disclosure.fec_fitem_sched_a.cand_prefix AS candidate_prefix, disclosure.fec_fitem_sched_a.cand_suffix AS candidate_suffix, disclosure.fec_fitem_sched_a.cand_office AS candidate_office, disclosure.fec_fitem_sched_a.cand_office_desc AS candidate_office_full, disclosure.fec_fitem_sched_a.cand_office_st AS candidate_office_state, disclosure.fec_fitem_sched_a.cand_office_st_desc AS candidate_office_state_full, disclosure.fec_fitem_sched_a.cand_office_district AS candidate_office_district, disclosure.fec_fitem_sched_a.conduit_cmte_id AS conduit_committee_id, disclosure.fec_fitem_sched_a.conduit_cmte_nm AS conduit_committee_name, disclosure.fec_fitem_sched_a.conduit_cmte_st1 AS conduit_committee_street1, disclosure.fec_fitem_sched_a.conduit_cmte_st2 AS conduit_committee_street2, disclosure.fec_fitem_sched_a.conduit_cmte_city AS conduit_committee_city, disclosure.fec_fitem_sched_a.conduit_cmte_st AS conduit_committee_state, disclosure.fec_fitem_sched_a.conduit_cmte_zip AS conduit_committee_zip, disclosure.fec_fitem_sched_a.donor_cmte_nm AS donor_committee_name, disclosure.fec_fitem_sched_a.national_cmte_nonfed_acct AS national_committee_nonfederal_account, disclosure.fec_fitem_sched_a.election_tp AS election_type, disclosure.fec_fitem_sched_a.election_tp_desc AS election_type_full, disclosure.fec_fitem_sched_a.fec_election_tp_desc AS fec_election_type_desc, disclosure.fec_fitem_sched_a.fec_election_yr AS fec_election_year, disclosure.fec_fitem_sched_a.action_cd AS amendment_indicator, disclosure.fec_fitem_sched_a.action_cd_desc AS amendment_indicator_desc, disclosure.fec_fitem_sched_a.schedule_type_desc AS schedule_type_full, disclosure.fec_fitem_sched_a.pg_date AS load_date, disclosure.fec_fitem_sched_a.orig_sub_id AS original_sub_id, disclosure.fec_fitem_sched_a.back_ref_tran_id AS back_reference_transaction_id, disclosure.fec_fitem_sched_a.back_ref_sched_nm AS back_reference_schedule_name, disclosure.fec_fitem_sched_a.filing_form AS filing_form, disclosure.fec_fitem_sched_a.link_id AS link_id, disclosure.fec_fitem_sched_a.is_individual AS is_individual, disclosure.fec_fitem_sched_a.memo_text AS memo_text, disclosure.fec_fitem_sched_a.two_year_transaction_period AS two_year_transaction_period, disclosure.fec_fitem_sched_a.schedule_type AS schedule_type, disclosure.fec_fitem_sched_a.increased_limit AS increased_limit, disclosure.fec_fitem_sched_a.sub_id AS sub_id, disclosure.fec_fitem_sched_a.pdf_url AS pdf_url, disclosure.fec_fitem_sched_a.line_number_label AS line_number_label
FROM disclosure.fec_fitem_sched_a JOIN ofec_committee_history_mv ON disclosure.fec_fitem_sched_a.cmte_id = ofec_committee_history_mv.committee_id AND disclosure.fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv.cycle
WHERE disclosure.fec_fitem_sched_a.is_individual = true AND disclosure.fec_fitem_sched_a.cmte_id IN ('C00636738') AND disclosure.fec_fitem_sched_a.contbr_st IN ('VA') AND disclosure.fec_fitem_sched_a.two_year_transaction_period IN (2018) AND ((disclosure.fec_fitem_sched_a.contbr_zip LIKE '22728' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22712' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22663' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22655' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22645' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22637' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22630' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22625' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22620' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22611' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22603' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22602' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22601' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '22556' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '20198' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '20187' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '20186' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '20184' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '20175' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '20144' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '20135' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '20119' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '20117' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '20115' || '%'))) TO STDOUT (FORMAT 'csv', HEADER TRUE)
```

**Comment by lbeaufort** [comment]
PR merged to release branch
