### ISSUE TITLE
Add restriction on cand_cmte_linkage related code (database and API) to exclude leadership PAC (cmte_dsgn=D)

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3907]
A new linkage type (leadership PAC) will be added to the cand_cmte_linkage table.  Add restriction on current code which use cand_cmte_linkage  (database and API) to exclude leadership PAC (cmte_dsgn=D).

[X] Add restriction on cand_cmte_linkage related code (database and API) to exclude leadership PAC (cmte_dsgn=D)
[X] Review SQLAlchemy code to make sure leadership PACs are not included in calculating candidate totals.

**Comment by fecjjeng** [comment]
A new linkage type (leadership PAC and and their sponsor candidates) had been added to the cand_cmte_linkage table. 
A federal office holder can sponsor a leadership PAC. But, that doesn't mean the person has to be running for re-election, so they might not be a candidate.
A candidate who is not an officeholder can also sponsor a leadership PAC.

We want to make sure that we do not include any of the financial activity of the leadership PAC in the financial summary of the candidate's campaign committees.
Therefore restriction is added to ofec_cand_cmte_linkage_mv  
to make sure leadership PAC (cmte_dsgn=D) is excluded in the calculation of candidate totals.

Since this mv is also used in addition to finacial activity, these D rows are included.  
However, the overall calculation on election_yr_to_be_included had excluded these rows 
  and election_yr_to_be_included column of these rows will be empty as well.

In addition, in the children MVs that involved in candidate financial summary calculation, only cmte_dsgn in ('P', 'A') rows are included, 
  further ensure these rows will not be included in the calculation of candidate financial summary.

**Comment by hcaofec** [comment]
PR has been merged, so closing.
