### ISSUE TITLE
Fix ofec_agg_coverage_date_mv to remove double entries from committee_id/fec_election_yr at the turn of 2002/2003

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#3915]
V0098 update ofec_agg_coverage_date_mv logic to take amendment situation into consideration
don’t look at operations log before 2003 (no consistent data)  

However, there are 172 committee_id/fec_election_yr that are doubled which happened at the turn of 2002/2003 since those are 2002 data submitted after 20030101

 [] Fix ofec_agg_coverage_date_mv to remove double entries from committee_id/fec_election_yr at the turn of 2002/2003

**Comment by JonellaCulmer** [comment]
PR has been merged. So closing.
