### ISSUE TITLE
[Snyk: Med] Cross-site scripting in eslint-plugin-no-unsanitized (Due: 10/20/2019)

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3921]
## Summary ##
Medium severity vulnerability found in eslint-plugin-no-unsanitized
Description: Cross-site Scripting (XSS)
Info: https://snyk.io/vuln/SNYK-JS-ESLINTPLUGINNOUNSANITIZED-173734
Introduced through: eslint-plugin-no-unsanitized@3.0.2
From: eslint-plugin-no-unsanitized@3.0.2

## Overview ##
`eslint-plugin-no-unsanitized` defines rules to disallow unsafe coding practices that may result into security vulnerabilities.

Affected versions of this package are vulnerable to Cross-site Scripting (XSS) due to allowing use of the dynamic `import()` function which accepts expressions.

## Remediation (as of August 21, 2019) ##
A fix was pushed into the master branch but not yet published.

## Steps to reproduce ##
in `openFEC` run `snyk test --file=package.json --dev`

**Comment by patphongs** [comment]
Let's run the test specified above, if no flags, let's close out this issue as it would be fixed.

**Comment by jason-upchurch** [comment]
@patphongs this is still an issue as of today:
```
✗ Medium severity vulnerability found in eslint-plugin-no-unsanitized
  Description: Cross-site Scripting (XSS)
  Info: https://snyk.io/vuln/SNYK-JS-ESLINTPLUGINNOUNSANITIZED-173734
  Introduced through: eslint-plugin-no-unsanitized@3.0.2
  From: eslint-plugin-no-unsanitized@3.0.2
```

**Comment by lbeaufort** [comment]
It looks like the fix for this was merged in February and they haven’t had a release in a year. We should deterimine if this vulnerability impacts us, and if so, make alternate plans.

**Comment by jason-upchurch** [comment]
We have an issue open in accounts that may be tangentially related, or perhaps even resolve this issue. The purpose of this package is described here: 

https://github.com/mozilla/eslint-plugin-no-unsanitized#disallow-unsanitized-code-no-unsanitized

Part of the determination would be to identify if this package is directly used to sanitize inputs cc @patphongs @rfultz @johnnyporkchops
