### ISSUE TITLE
Update apispec in requirements.txt and modify codebase for breaking changes

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3923]
## Summary ##
Currently `flask-apispec==0.7.0` (up to date) uses a forked/modified version of `apispec` (required: >=0.17.0, installed: 1.0.0b1). However, version `apispec@2.0.2` is available (and version `@3.0.0` is forthcoming) and has several breaking changes from the forked/modified version. These breaking changes include the addition of `openapi_version` to `init` as well as exception handling. Full changelog available here: https://apispec.readthedocs.io/en/stable/changelog.html

**Comment by lbeaufort** [comment]
@jason-upchurch is this a duplicate of https://github.com/fecgov/openFEC/issues/3776?

**Comment by jason-upchurch** [comment]
@lbeaufort indeed it is! Thank you for catching it!
