### ISSUE TITLE
Clean-up ofec_totals_candidate_committees_mv

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#3928]
Now that #3919 is merged. It is replaced by ofec_candidate_totals_detail_mv.
We don't need ofec_totals_candidate_committees_mv and ofec_totals_candidate_committees_vw
- [ ] remove ofec_totals_candidate_committees_mv and ofec_totals_candidate_committees_vw
- [ ] clean flow.py
- [ ] clean manage.py

**Comment by JonellaCulmer** [comment]
PR has been merged, so closing.
