### ISSUE TITLE
research load balancing and server configuration

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3938]
## Summary ##
We discussed in PI10 planning the need to research and understand the default configuration, e.g., server configuration and load balancing, for our servers.

**Comment by fec-jli** [comment]
Currently, we are using the round robin routing algorithm. 

AWS ELB works:
[How Elastic Load Balancing Works](https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/how-elastic-load-balancing-works.html)
