### ISSUE TITLE
Fix API links in Statutes, reload legal docs

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3942]
**What we're after:**
Following up on the work to [update that message](https://github.com/fecgov/fec-cms/issues/3112) on the Statutes search, we now need to update the links to make sure that when a user clicks on the link to a specific statute that it actually goes to the appropriate page. 

### Related issues
- [x]  https://github.com/fecgov/fec-cms/issues/3112

### Example
Go to https://www.fec.gov/data/legal/search/statutes/?search=contribution and click on a statute link

### Completion criteria

- [x] Update the links to the API so they point to the govinfo API, not http://api.fdsys.gov/ for each provision (which GPO has moved on from using). 
For Title 26: See https://www.govinfo.gov/link/uscode/26/9002
For Title 52: See https://www.govinfo.gov/link/uscode/52/30116
**dev**
- [x] Reload current legal docs `cf run-task api "python manage.py refresh_current_legal_docs_zero_downtime" -m 4G --name reload-current-legal-docs`
- [ ] (in progress) Reload archived MURs with a [headless app](https://cloud.gov/docs/getting-started/one-off-tasks/#deploy-an-app-that-performs-a-task) ~Modify them in elasticsearch? Reach out to GPO about redirects?~
Reloading current AOs and MURs is easy, but reloading all archived MURs takes days to do. I looked into just updating the statute links in elasticsearch, but that would be lots of work (See https://www.govinfo.gov/about#fdsys-transition). Redirects are no longer working.
**stage**
- [x] Reload current legal docs
- [ ] (in progress) Reload archived MURs (restore from Prod?)
**prod (after 12/31 deployment)**
- [x] Reload current legal docs
- [ ] (in progress - app is `load-archived-murs-prod-kill-1-15-19`) Reload archived MURs 
- [x] Test links in front end
- [ ] Check logs for errors in prod before closing

### Future work

Open up followup tickets to consider how to improve the Statutes search. 

---

@lbeaufort commented on [Thu Sep 05 2019](https://github.com/fecgov/fec-cms/issues/3145#issuecomment-528568919)

This is an API issue, so moving to the openFEC repo. Check out the `index_statutes` function in the API.

Example query: https://fec-dev-api.app.cloud.gov/v1/legal/search?hits_returned=20&type=statutes&from_hit=0&q=contribution

**Comment by dorothyyeager** [comment]
When you are ready to work on this, Jim Jones has forwarded me the name of someone in GPO who may be able to help on their end. Just let me know.

**Comment by lbeaufort** [comment]
@PaulClark2 @dorothyyeager we currently link directly to the PDF. Would it be more user-friendly to take them to the landing page, as linked above? 

Example: 
Landing page: https://www.govinfo.gov/app/details/USCODE-2017-title26/USCODE-2017-title26-subtitleH
PDF link: https://www.govinfo.gov/content/pkg/USCODE-2017-title26/pdf/USCODE-2017-title26-subtitleH.pdf

**Comment by dorothyyeager** [comment]
@lbeaufort @PaulClark2 That was a judgment call made by the initial website team, I'm guessing. After looking at both pages, it depends on what the user wants to do. For someone like a lawyer or an Information Division specialist, the PDF link is the most useful. For someone who wants to download the statutes in whatever format, the landing page is more useful. The lawyers and specialists would have to figure out they need to click "text" or "PDF" on the left to get what they need. I'd prefer to keep as is for my selfish purposes as a specialist, but let's see what @AmyKort thinks...

**Comment by lbeaufort** [comment]
@dorothyyeager thanks - we probably shouldn't make changes to the behavior if folks haven't complained about it. Flagging for @JonellaCulmer in case you're interested when you're back in the office.

**Comment by dorothyyeager** [comment]
Just a note that GPO has implemented a redirect for their RSS feed, and our links are now redirecting properly as a result. We will still want to figure out a way to get the most recent URL into our pages to keep it cleaner and make it faster to load.

**Comment by lbeaufort** [comment]
@PaulClark2 @jason-upchurch I removed the milestone for this issue since the links are no longer broken. I tagged it `Technical debt` since we'll want to put in the non-redirect links eventually.

**Comment by lbeaufort** [comment]
@dorothyyeager pointed out that the redirects are no longer working, so I tagged this as a bug again. 


<img width="673" alt="Screen Shot 2019-12-26 at 10 26 51 AM" src="https://user-images.githubusercontent.com/31420082/71481037-43a53900-27ca-11ea-82b4-e3dcccbf55cc.png">

**Comment by dorothyyeager** [comment]
Links for 2018 version uploaded recently by GovInfo:
Title 26: https://www.govinfo.gov/app/collection/uscode/2018/title26/subtitleH
Title 52: https://www.govinfo.gov/app/collection/uscode/2018/title52

**Comment by lbeaufort** [comment]
@dorothyyeager it looks like the 2017 links are broken now - I think our best bet would be to use this format: https://www.govinfo.gov/link/uscode/52/30116

Docs: https://www.govinfo.gov/link-docs/

**Comment by lbeaufort** [comment]
It looks like the GPO redirects are working again and most archived MURs are reloaded in production. In addition, since the classic site is down the reload won't be possible until we implement https://github.com/fecgov/openFEC/issues/4129 so per @PaulClark2 I'm going to de-prioritize the remaining reloads until we work on https://github.com/fecgov/openFEC/issues/4129

**Comment by lbeaufort** [comment]
Closing this in favor of #4129
