### ISSUE TITLE
Create materialized view to get current_version for each filing

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#3946]
This is a following up ticket of #[3455](https://github.com/fecgov/openFEC/issues/3455). 

Try a different approach to calculate most_recent_file_number and use this data to get the version of each filing:

We can add image_number to window function to handle the scenario where more than one amendment are received on the same day.

CREATE MATERIALIZED VIEW public.ofec_filings_current_version_mv_tmp_hc AS
SELECT f_rpt_or_form_sub.cand_cmte_id,
f_rpt_or_form_sub.rpt_yr,
f_rpt_or_form_sub.rpt_tp,
f_rpt_or_form_sub.file_num,
f_rpt_or_form_sub.receipt_dt,
first_value(f_rpt_or_form_sub.file_num) OVER (PARTITION BY f_rpt_or_form_sub.cand_cmte_id, f_rpt_or_form_sub.rpt_yr, f_rpt_or_form_sub.rpt_tp ORDER BY f_rpt_or_form_sub.receipt_dt DESC NULLS LAST) AS most_recent_file_num
FROM disclosure.f_rpt_or_form_sub
WHERE f_rpt_or_form_sub.file_num IS NOT NULL AND f_rpt_or_form_sub.rpt_yr >= 1979::numeric AND f_rpt_or_form_sub.form_tp::text <> 'SL'::text
WITH DATA;

## Completion criteria ##
- [ ] complete reference implementation
- [ ] decide if approach should be adopted (chat with other devs)
- [ ] if accepted, use reference implementation, i.e., put in PR for this issue.

**Comment by hcaofec** [comment]
A filing's version is decided by "most_recent" from endpoint: /filings/.  Instead of calling the function to calculate it,  another way is to left join to v_sum table.  If this filling exists in v_sum, then it is the most recent filing.  This applies to F3/3X/3P and all other form types that are pulled into v_sum.  The similar logic can be seen in fec_vsum_f3_vw.  The logic in ofec_processed_non_financial_amendment_chain_vw will be used for F1 and F2 with some modification.  The partition will be order by receipt_date. 

Calculation of amendment_chain seems complicated because of the nature of the data in f_rpt table, and could be fixed in a separate ticket.

**Comment by patphongs** [comment]
Moving this to 10.2, since it looks like more work needs to be done

**Comment by lbeaufort** [comment]
PR has been merged
