### ISSUE TITLE
Incorporate API key signup elements from related API key work

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3947]
### Summary ###

Related issue #4323 is to include vanilla api signup key to `swagger-ui.html`. This issue should follow that work and also #4305 to incorporate validation elements required for our signup process.

### Related issues ###
- [x] https://github.com/fecgov/fec-accounts/issues/254 (validation)
- [x] https://github.com/fecgov/openFEC/issues/4305 (aup)
- [x] https://github.com/fecgov/openFEC/issues/4323 (vanilla signup)

**Comment by lbeaufort** [comment]
Another advantage is we could make purpose of use and reading/acknowledging the acceptable use criteria required.

**Comment by lbeaufort** [comment]
We could also make a separate signup page rather than imbedding it in the docs

**Comment by JonellaCulmer** [comment]
Closing in favor of https://github.com/fecgov/fec-cms/issues/3867
