### ISSUE TITLE
develop prioritization plan for updating python libraries

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3953]
## Summary
The following libraries have breaking changes (but perhaps not for our application. Need to prioritize these in terms of ordering. May also want to reference #3782 and work related libraries together even if they do not have breaking changes, e.g., everything to do with `marshmallow` might be a single issue to be worked together or broken up but worked together before other packages (a candidate path forward). 

|     package     |      location       |    current | newest | has_bkwrd_incompatible |
|  ---  |  ---  |  ---  |  ---  | --- |
| [`marshmallow`](https://marshmallow.readthedocs.io/en/stable/changelog.html) | `requirements.txt` | 2.16.3 | 3.0.0 | true |
| [`apispec`](https://apispec.readthedocs.io/en/stable/changelog.html) | `requirements.txt` | 0.39 | 2.0.2 |  true | |
| [`invoke`](http://www.pyinvoke.org/changelog.html) | `requirements.txt` |  0.15.0 | 1.3.0 | true |

non-breaking change libraries:

|     package     |      location       |    current | newest | GitHub issue to upgrade |
|  ---  |  ---  |  ---  |  ---  | --- |
| [`cfenv`](https://pypi.org/project/cfenv/0.5.3/)  |  `requirements.txt`  | 0.5.2 | 0.5.3 |
| [`psycopg2-binary`](https://pypi.org/project/psycopg2/#history) | `requirements.txt` | 2.7.4 | 2.8.3 |
| [`Flask`](https://pypi.org/project/Flask/#history) | `requirements.txt` | 1.0.2 | 1.1.1 | #4026
|[`Flask-Cors`](https://pypi.org/project/Flask-Cors/#history) | `requirements.txt` | 3.0.6 | 3.0.8 |
| [`Flask-RESTful`](https://flask-restful.readthedocs.io/en/latest/) | `requirementst.txt` | 0.3.6 | 0.3.7 |
| [`python-dateutil`](https://dateutil.readthedocs.io/en/stable/changelog.html) | `requirements.txt` | 2.4.2 | 2.8.0 |
| [`sqlalchemy-postgres-copy`](https://github.com/jmcarp/sqlalchemy-postgres-copy/blob/master/CHANGELOG.rst) | `requirements.txt` | 0.3.0 | 0.5.0 |
| [`networkx`](https://networkx.github.io/documentation/stable/news.html) | `requirements.txt` | 1.11 | 2.3
| [`SQLAlchemy`](https://docs.sqlalchemy.org/en/13/changelog/changelog_13.html#change-1.3.6) | `requirements.txt` | 1.3.1 | 1.3.7 |
| [`gevent`](https://pypi.org/project/gevent/#history) | `requirements.txt` | 1.2.2 | 1.4.0 | #3961 
| [`icalendar`](https://docs.sqlalchemy.org/en/13/changelog/changelog_13.html#change-1.3.6) | `requirements.txt` | 3.9.1 | 4.0.3 |
| [`GitPython`](https://gitpython.readthedocs.io/en/stable/changes.html) | `requirements.txt` | 1.0.1 | 2.1.12 |
| [`gunicorn`](http://docs.gunicorn.org/en/stable/news.html) | `requirements.txt` | 19.7.1 | 19.9.0 | #3961 |
| [`webargs`](https://webargs.readthedocs.io/en/latest/changelog.html) | `requirements.txt` | 5.3.1 | 5.4.0 |
| [`ujson`](https://pypi.org/project/ujson/#history) | `requirements.txt` | 1.33 | 1.35
| [`requests`](https://pypi.org/project/requests/2.7.0/#history) | `requirements.txt` | 2.21.0 | 2.22.0
| [`elasticsearch`](https://elasticsearch-py.readthedocs.io/en/master/Changelog.html) | `requirements.txt` | 5.5.1 | ~6.3.0~ 5.5.3 | #4065 
| [`elasticsearch-dsl`](https://elasticsearch-dsl.readthedocs.io/en/latest/Changelog.html) | `requirements.txt` | 5.4.0 | 7.0.0
| [`marshmallow-sqlalchemy`](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/changelog.html#changelog) | `requirements.txt` | 0.15.0 | 0.17.0 |
| [`smart_open`](https://pypi.org/project/smart-open/1.8.4/#history) | `requirements.txt` | 1.7.1 | 1.8.3 |
| [`redis`](https://pypi.org/project/redis/3.3.8/#history) | `requirements.txt` | 3.2.0 | 3.3.8 |
| [`pytest`](https://docs.pytest.org/en/latest/changelog.html) | `requirements-dev.txt` | 3.7.4 | 5.1.1 |
| [`pytest-cov`](https://github.com/pytest-dev/pytest-cov/blob/master/CHANGELOG.rst) | `requirements-dev.txt` | 2.5.1 | 2.7.1 |
| [`factory_boy`](https://factoryboy.readthedocs.io/en/latest/changelog.html) | `requirements-dev.txt` | 2.8.1 | 2.12.0 |
| [`nplusone`](https://github.com/jmcarp/nplusone/blob/master/HISTORY.rst) | `requirements-dev.txt` | 0.8.0 | 1.0.0 |
| [`webtest`](https://github.com/Pylons/webtest/blob/master/CHANGELOG.rst) | `requirements-dev.txt` | 2.0.27 | 2.0.34 |
| [`click`](https://click.palletsprojects.com/en/7.x/changelog/) | `requirementst-dev.txt` | 6.7 | 7.1 |
| [`codecov`](https://github.com/codecov/codecov-python/blob/master/CHANGELOG.md) | `requirements-ci.txt` | 2.0.9 | 2.0.15 |

## Completion criteria
- [x] Developer make recommendation based on trying upgrades. Confer with development team about approach for packages with breaking changes
- [x] Open related issues as necessary

**Comment by JonellaCulmer** [comment]
A meeting is scheduled this week to update this ticket and identify next steps.

**Comment by jason-upchurch** [comment]
Call scheduled for 11/8 at 10:15 with @lbeaufort @pkfec @fec-jli

**Comment by jason-upchurch** [comment]
@jason-upchurch to run `pipdeptree` to discover logical groupings for packages where possible and get team consensus on ordering/issue creation.

**Comment by jason-upchurch** [comment]
`pipdeptree` result:

```
celery-once==3.0.0
  - celery [required: Any, installed: 4.3.0]
    - billiard [required: >=3.6.0,<4.0, installed: 3.6.1.0]
    - kombu [required: >=4.4.0,<5.0, installed: 4.6.3]
      - amqp [required: >=2.5.0,<3.0, installed: 2.5.2]
        - vine [required: >=1.1.3,<5.0.0a1, installed: 1.3.0]
    - pytz [required: >dev, installed: 2019.3]
    - vine [required: >=1.3.0, installed: 1.3.0]
  - redis [required: >=2.10.2, installed: 3.2.0]
cfenv==0.5.2
  - furl [required: >=0.4.8, installed: 2.1.0]
    - orderedmultidict [required: >=1.0.1, installed: 1.0.1]
      - six [required: >=1.8.0, installed: 1.13.0]
    - six [required: >=1.8.0, installed: 1.13.0]
elasticsearch-dsl==5.4.0
  - elasticsearch [required: >=5.0.0,<6.0.0, installed: 5.5.3]
    - urllib3 [required: >=1.21.1, installed: 1.24.3]
  - python-dateutil [required: Any, installed: 2.4.2]
    - six [required: >=1.5, installed: 1.13.0]
  - six [required: Any, installed: 1.13.0]
factory-boy==2.8.1
  - Faker [required: >=0.7.0, installed: 2.0.3]
    - python-dateutil [required: >=2.4, installed: 2.4.2]
      - six [required: >=1.5, installed: 1.13.0]
    - six [required: >=1.10, installed: 1.13.0]
    - text-unidecode [required: ==1.3, installed: 1.3]
flask-apispec==0.7.0
  - apispec [required: >=0.17.0, installed: 0.39.0]
    - PyYAML [required: >=3.10, installed: 5.1.2]
  - flask [required: >=0.10.1, installed: 1.1.1]
    - click [required: >=5.1, installed: 6.7]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.10.3]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 0.16.0]
  - marshmallow [required: >=2.0.0, installed: 2.16.3]
  - six [required: >=1.9.0, installed: 1.13.0]
  - webargs [required: >=0.18.0, installed: 5.3.1]
    - marshmallow [required: >=2.15.2, installed: 2.16.3]
Flask-Cors==3.0.6
  - Flask [required: >=0.9, installed: 1.1.1]
    - click [required: >=5.1, installed: 6.7]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.10.3]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 0.16.0]
  - Six [required: Any, installed: 1.13.0]
Flask-RESTful==0.3.6
  - aniso8601 [required: >=0.82, installed: 8.0.0]
  - Flask [required: >=0.8, installed: 1.1.1]
    - click [required: >=5.1, installed: 6.7]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.10.3]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 0.16.0]
  - pytz [required: Any, installed: 2019.3]
  - six [required: >=1.3.0, installed: 1.13.0]
Flask-Script==2.0.6
  - Flask [required: Any, installed: 1.1.1]
    - click [required: >=5.1, installed: 6.7]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.10.3]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 0.16.0]
Flask-SQLAlchemy==2.4.0
  - Flask [required: >=0.10, installed: 1.1.1]
    - click [required: >=5.1, installed: 6.7]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.10.3]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 0.16.0]
  - SQLAlchemy [required: >=0.8.0, installed: 1.3.1]
gevent==1.4.0
  - greenlet [required: >=0.4.14, installed: 0.4.15]
GitPython==1.0.1
  - gitdb [required: >=0.6.4, installed: 0.6.4]
    - smmap [required: >=0.8.5, installed: 0.9.0]
gunicorn==19.9.0
icalendar==3.9.1
  - python-dateutil [required: Any, installed: 2.4.2]
    - six [required: >=1.5, installed: 1.13.0]
  - pytz [required: Any, installed: 2019.3]
  - setuptools [required: Any, installed: 40.8.0]
invoke==0.15.0
marshmallow-pagination==0.1.2
  - marshmallow [required: >=2.0.0b1, installed: 2.16.3]
  - marshmallow-sqlalchemy [required: >=0.4.1, installed: 0.15.0]
    - marshmallow [required: >=2.0.0, installed: 2.16.3]
    - SQLAlchemy [required: >=0.9.7, installed: 1.3.1]
networkx==1.11
  - decorator [required: >=3.4.0, installed: 4.4.1]
nplusone==0.8.0
  - blinker [required: >=1.3, installed: 1.4]
  - six [required: >=1.9.0, installed: 1.13.0]
openapi-spec-validator==0.2.8
  - jsonschema [required: Any, installed: 3.1.1]
    - attrs [required: >=17.4.0, installed: 19.3.0]
    - importlib-metadata [required: Any, installed: 0.23]
      - zipp [required: >=0.5, installed: 0.6.0]
        - more-itertools [required: Any, installed: 7.2.0]
    - pyrsistent [required: >=0.14.0, installed: 0.15.5]
      - six [required: Any, installed: 1.13.0]
    - setuptools [required: Any, installed: 40.8.0]
    - six [required: >=1.11.0, installed: 1.13.0]
  - PyYAML [required: >=5.1, installed: 5.1.2]
  - six [required: Any, installed: 1.13.0]
pdbpp==0.9.1
  - fancycompleter [required: >=0.2, installed: 0.8]
  - pygments [required: Any, installed: 2.4.2]
  - wmctrl [required: Any, installed: 0.3]
pip-tools==4.2.0
  - click [required: >=6, installed: 6.7]
  - six [required: Any, installed: 1.13.0]
pipdeptree==0.13.2
  - pip [required: >=6.0.0, installed: 19.0.3]
prance==0.16.1
  - chardet [required: ~=3.0, installed: 3.0.4]
  - PyYAML [required: ~=5.1, installed: 5.1.2]
  - requests [required: ~=2.21, installed: 2.21.0]
    - certifi [required: >=2017.4.17, installed: 2019.9.11]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.9, installed: 2.8]
    - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.3]
  - semver [required: ~=2.8, installed: 2.9.0]
  - six [required: ~=1.12, installed: 1.13.0]
psycopg2-binary==2.7.4
pytest-cov==2.5.1
  - coverage [required: >=3.7.1, installed: 4.5.4]
  - pytest [required: >=2.6.0, installed: 3.7.4]
    - atomicwrites [required: >=1.0, installed: 1.3.0]
    - attrs [required: >=17.4.0, installed: 19.3.0]
    - more-itertools [required: >=4.0.0, installed: 7.2.0]
    - pluggy [required: >=0.7, installed: 0.13.0]
      - importlib-metadata [required: >=0.12, installed: 0.23]
        - zipp [required: >=0.5, installed: 0.6.0]
          - more-itertools [required: Any, installed: 7.2.0]
    - py [required: >=1.5.0, installed: 1.8.0]
    - setuptools [required: Any, installed: 40.8.0]
    - six [required: >=1.10.0, installed: 1.13.0]
rdbms-subsetter==0.2.6.2
  - blinker [required: Any, installed: 1.4]
  - sqlalchemy [required: Any, installed: 1.3.1]
slate==0.5.2
  - pdfminer3k [required: Any, installed: 1.3.1]
    - ply [required: >=3.4, installed: 3.11]
    - pytest [required: >=2.0, installed: 3.7.4]
      - atomicwrites [required: >=1.0, installed: 1.3.0]
      - attrs [required: >=17.4.0, installed: 19.3.0]
      - more-itertools [required: >=4.0.0, installed: 7.2.0]
      - pluggy [required: >=0.7, installed: 0.13.0]
        - importlib-metadata [required: >=0.12, installed: 0.23]
          - zipp [required: >=0.5, installed: 0.6.0]
            - more-itertools [required: Any, installed: 7.2.0]
      - py [required: >=1.5.0, installed: 1.8.0]
      - setuptools [required: Any, installed: 40.8.0]
      - six [required: >=1.10.0, installed: 1.13.0]
  - setuptools [required: Any, installed: 40.8.0]
smart-open==1.7.1
  - boto [required: >=2.32, installed: 2.49.0]
  - boto3 [required: Any, installed: 1.10.13]
    - botocore [required: >=1.13.13,<1.14.0, installed: 1.13.13]
      - docutils [required: >=0.10,<0.16, installed: 0.15.2]
      - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
      - python-dateutil [required: >=2.1,<2.8.1, installed: 2.4.2]
        - six [required: >=1.5, installed: 1.13.0]
      - urllib3 [required: >=1.20,<1.26, installed: 1.24.3]
    - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
    - s3transfer [required: >=0.2.0,<0.3.0, installed: 0.2.1]
      - botocore [required: >=1.12.36,<2.0.0, installed: 1.13.13]
        - docutils [required: >=0.10,<0.16, installed: 0.15.2]
        - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
        - python-dateutil [required: >=2.1,<2.8.1, installed: 2.4.2]
          - six [required: >=1.5, installed: 1.13.0]
        - urllib3 [required: >=1.20,<1.26, installed: 1.24.3]
  - bz2file [required: Any, installed: 0.98]
  - requests [required: Any, installed: 2.21.0]
    - certifi [required: >=2017.4.17, installed: 2019.9.11]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.9, installed: 2.8]
    - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.3]
sqlalchemy-postgres-copy==0.3.0
  - psycopg2 [required: Any, installed: 2.8.4]
  - six [required: Any, installed: 1.13.0]
  - sqlalchemy [required: Any, installed: 1.3.1]
ujson==1.33
WebTest==2.0.27
  - beautifulsoup4 [required: Any, installed: 4.8.1]
    - soupsieve [required: >=1.2, installed: 1.9.5]
  - six [required: Any, installed: 1.13.0]
  - waitress [required: >=0.8.5, installed: 1.3.1]
  - WebOb [required: >=1.2, installed: 1.8.5]
```

**Comment by jason-upchurch** [comment]
had call and made following recommendation:
Top-level, no sub/top interaction--these can likely all be worked in a single issue with unique commits for each package:
• cfenv
• psychopg2-binary
• networkx
• Gitpython
• Webtest
• codecov
For each bullet point below, I'd suggest we have an issue and work the related packages for that bullet point as a whole:
Top-level/dependency interaction
• Flask (dependency of flask-apispec, flask-cors, flask-restful, flask-script, flask-sqlalechmy) nplusone
• Sqlalchemy (sqlalchemy-postgres-copy)
• Elasticsearch-dsl (elasticsearch, python-dateutil, factory_boy)
• Smart-open Icalendar, Python-dateutil(maximum version <2.8.1 (smart-open))
• Redis (may be able to remove as a top level) (celery-once)
• Click (may be able  to  remove since it is a dependency of many already-installed tools (mostly flask stuff)) but also as devdependeny bc of pip-tools
• pytest / pytest-cov (edited)
