### ISSUE TITLE
remove unused libraries

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3955]
## Summary
Related issue #3940 and #3782. Need to remove unused python libraries (but need to double check each is not in use before removing them from requirements). `pandas` will require removal of unused functions that reference the package.

|     package     |      location       |    current | newest | has_bkwrd_incompatible |
|  ---  |  ---  |  ---  |  ---  | --- |
| [unused] [`prompt-toolkit`](https://python-prompt-toolkit.readthedocs.io/en/master/pages/upgrading/3.0.html) | `requirements.txt` | 2.0.6 | 3.0.0 | true |
| [unused] `ipython` | `requirements-dev.txt` | 7.5.0 | 
| [unused] [`faker`](https://github.com/joke2k/faker/blob/master/CHANGELOG.rst) | `requirements-dev.txt` | 0.7.18 | 2.0.1 | true |
| [unused] `pdbpp` | `requirements-dev.txt` | 0.9.1 |
| [unused] `pygments` | `requirements-dev.txt` | 2.2.0 |
| [unused] [`pandas`](https://pandas.pydata.org/pandas-docs/stable/whatsnew/index.html) |  `requirements-dev.txt` | 0.16.2 |  0.25.0 | true |
| [unused] `xlrd` | `requirements-dev.txt` | 0.9.4 |

## Completion Criteria ##
- [ ] Remove packages
- [ ] Test the removal.

**Comment by pkfec** [comment]
|     unused package   name  |      location       |    used for  |
|  ---  |  ---  |  ---  |  
| `prompt-toolkit`| `requirements.txt` | 2.0.6 |  |
| `ipython` | `requirements-dev.txt` | 7.5.0 | 
| `faker` | `requirements-dev.txt` | to create dummy data | 
| `pdbpp` | `requirements-dev.txt` | python debugger with  |
| `pygments` | `requirements-dev.txt` | 2.2.0 |
| `pandas` |  `requirements-dev.txt` | 0.16.2 |  
| `xlrd` | `requirements-dev.txt` | 0.9.4 |

**Comment by pkfec** [comment]
PR https://github.com/fecgov/openFEC/pull/4013 ready for review
