### ISSUE TITLE
Full organization type (organization_type_full) is blank for H's and I's

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3967]
The `expand_organization_type` function is not handling H's and I's, making `organization_type_full` `NULL` for organization types H and I (H: Convention - need exact definition, I: Inaugural - need exact label)

Symptom: Weird looking commmitee profile pages
![Screen Shot 2019-09-23 at 9 13 05 AM](https://user-images.githubusercontent.com/31420082/65429084-90e8c780-dde3-11e9-82e7-ed56d270d318.png)

**Completion criteria**
- [ ] Update `expand_organization_type` function to handle H's and I's
- [ ] Update `ORGANIZATION_TYPE` docs to include H's and I's

**Comment by lbeaufort** [comment]
```
select organization_type, organization_type_full, count(*), min(committee_id), max(committee_id) from ofec_committee_history_mv where organization_type not in ('W','C','L','V','M'
     ,'T') group by organization_type, organization_type_full
```

**Comment by PaulClark2** [comment]
My understanding is we used `org_tp` `H` and `I' to distinguish host/convention and inaugural committees from other party committees. We should not display an organization type for types `H` and `I`. 

If we need descriptions for `H` and `I`, I suggest: 
H = Convention or host
I = Inaugural

**Comment by lbeaufort** [comment]
After discussing this with @PaulClark2 and finding this ticket https://github.com/fecgov/openFEC/issues/3441, it looks like these org_types are a workaround and aren't "truly" organization types. We can move the implementation to the front end - I'll work with @patphongs on this.
