### ISSUE TITLE
test python upgrade on api stage (Due 9/30/2019 before release deploy)

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3969]
## Summary
Related: #3961 and #3951. PR #3961 was merged for the 10.1 release on 10/1/2019. This is a ticket to test this work on stage.

## Completion criteria
- [ ] on stage, go to swagger ui and verify endpoints return as expected
- [ ] try some downloads to verify that downloads work

**Comment by patphongs** [comment]
Test API endpoints through Swagger and tested download functionality on staging CMS. Everything worked as expected!

- [x] Download functionality worked
- [x] API swagger testing:
   - [x] /candidate/{candidate_id}/
   - [x] /candidate​/{candidate_id}​/history​/
   - [x] /candidate/{candidate_id}/history/{cycle}/
   - [x] /candidate/{candidate_id}/totals/
   - [x] /candidates/
   - [x] /candidates​/search​/
   - [x] /candidates/totals/
   - [x] /candidates​/totals​/by_office​/
   - [x] /candidates/totals/by_office/by_party/
   - [x] /committee/{committee_id}/candidates/
   - [x] /committee/{committee_id}/candidates/history/
   - [x] /committee/{committee_id}/candidates/history/{cycle}/
   - [x] /candidate/{candidate_id}/committees/
   - [x] /candidate/{candidate_id}/committees/history/
   - [x] /candidate/{candidate_id}/committees/history/{cycle}/
   - [x] /committee/{committee_id}/
   - [x] /committee​/{committee_id}​/history​/
   - [x] /committee/{committee_id}/history/{cycle}/
   - [x] /committees​/
   - [x] /calendar-dates/
   - [x] /calendar-dates/export/
   - [x] /election-dates/
   - [x] /reporting-dates/
   - [x] /committee/{committee_id}/reports/
   - [x] /committee/{committee_id}/totals/
   - [x] /elections/
   - [x] /elections/search/
   - [x] /elections/summary/
   - [x] /reports/{committee_type}/
   - [x] /totals/by_entity/
   - [x] /totals/{committee_type}/
   - [x] /names/candidates/
   - [x] /names/committees/
   - [x] /candidate/{candidate_id}/filings/
   - [x] /committee/{committee_id}/filings/
   - [x] /filings​/
   - [x] /operations-log/
   - [x] /committee/{committee_id}/schedules/schedule_a/by_employer/
   - [x] /committee/{committee_id}/schedules/schedule_a/by_occupation/
   - [x] /committee​/{committee_id}​/schedules​/schedule_a​/by_size​/
   - [x] /committee/{committee_id}/schedules/schedule_a/by_state/
   - [x] /committee/{committee_id}/schedules/schedule_a/by_zip/
   - [x] /schedules/schedule_a/
   - [x] /schedules/schedule_a/by_employer/
   - [x] /schedules/schedule_a/by_occupation/
   - [x] /schedules​/schedule_a​/by_size​/
   - [x] /schedules/schedule_a/by_size/by_candidate/
   - [x] /schedules/schedule_a/by_state/
   - [x] /schedules/schedule_a/by_state/by_candidate/
   - [x] /schedules/schedule_a/by_state/by_candidate/totals/
   - [x] /schedules/schedule_a/by_state/totals/
   - [x] /schedules/schedule_a/by_zip/
   - [x] /schedules/schedule_a/efile/
   - [x] /schedules/schedule_a/{sub_id}/
   - [x] /committee/{committee_id}/schedules/schedule_b/by_purpose/
   - [x] /committee/{committee_id}/schedules/schedule_b/by_recipient/
   - [x] /committee/{committee_id}/schedules/schedule_b/by_recipient_id/
   - [x] /schedules/schedule_b/
   - [x] /schedules​/schedule_b​/by_purpose​/
   - [x] /schedules/schedule_b/by_recipient/
   - [x] /schedules/schedule_b/by_recipient_id/
   - [x] /schedules/schedule_b/efile/
   - [x] /schedules​/schedule_b​/{sub_id}​/
   - [x] /schedules​/schedule_c​/
   - [x] /schedules/schedule_c/{sub_id}/
   - [x] /schedules/schedule_d/
   - [x] /schedules/schedule_d/{sub_id}/
   - [x] /committee/{committee_id}/schedules/schedule_e/by_candidate/
   - [x] /schedules/schedule_e/
   - [x] /schedules/schedule_e/by_candidate/
   - [x] /schedules/schedule_e/efile/
   - [x] /schedules/schedule_f/
   - [x] /schedules/schedule_f/{sub_id}/
   - [x] /committee/{committee_id}/communication_costs/by_candidate/
   - [x] /communication-costs/
   - [x] /communication_costs/by_candidate/
   - [x] /committee/{committee_id}/electioneering/by_candidate/
   - [x] /electioneering/
   - [x] /electioneering/by_candidate/
   - [x] /rad-analyst/
   - [x] /state-election-office/
   - [x] /efile/filings/
   - [x] /efile/reports/house-senate/
   - [x] /efile/reports/pac-party/
   - [x] /efile/reports/presidential/
   - [x] /audit-case/
   - [x] /audit-category​/
   - [x] /audit-primary-category/
   - [x] /names/audit_candidates/
   - [x] /names/audit_committees/
   - [x] /legal/search/
