### ISSUE TITLE
Research why /schedules/schedule_a/by_state/by_candidate is slow

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3970]
**What we're after:**
We have noticed that when loading the candidate totals by state for the Where contributions come from feature, that it would take roughly 10s to load in the staging environment. This can happen even after a query for a particular candidate has already been performed. Would be good to see if there's a way to optimize these endpoints or make sure the cache consistently performs?

This is the link to the Where contributions come from feature in the stage environment: https://fec-stage-proxy.app.cloud.gov/data/raising-bythenumbers/#contributions-by-state

- /schedules/schedule_a/by_state/by_candidate/: 10 seconds
- /schedules/schedule_a/by_state/by_candidate/totals/: 20 seconds

Sample API AJAX call:

https://api-stage.open.fec.gov/v1/schedules/schedule_a/by_state/by_candidate/?api_key=NICAR16&cycle=2016&election_full=true&office=P&page=1&per_page=200&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false&candidate_id=P00003392

https://api-stage.open.fec.gov/v1/schedules/schedule_a/by_state/by_candidate/totals/?api_key=NICAR16&cycle=2016&election_full=true&office=P&page=1&per_page=200&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false&candidate_id=P00003392

This query is being built by sqlalchemy

**Comment by fecjjeng** [comment]
Thanks @lbeaufort for providing the query output from sqlalchemy: 
SELECT anon_1.candidate_id, 
anon_1.election_yr_to_be_included AS cycle, 
ofec_sched_a_agg_state_vw.state, 
sum(ofec_sched_a_agg_state_vw.total) AS total, 
max(ofec_sched_a_agg_state_vw.state_full) AS state_full, 
sum(ofec_sched_a_agg_state_vw.count) AS count
FROM (SELECT DISTINCT ofec_cand_cmte_linkage_mv.cand_id AS candidate_id, ofec_cand_cmte_linkage_mv.cmte_id AS committee_id, ofec_cand_cmte_linkage_mv.fec_election_yr AS fec_election_year, ofec_cand_cmte_linkage_mv.election_yr_to_be_included AS election_yr_to_be_included 
    FROM ofec_cand_cmte_linkage_mv 
    WHERE ofec_cand_cmte_linkage_mv.election_yr_to_be_included IN (2016) 
    AND ofec_cand_cmte_linkage_mv.cand_id IN ('P00003392') 
    AND ofec_cand_cmte_linkage_mv.cmte_dsgn IN ('P', 'A')) AS anon_1 
JOIN ofec_sched_a_agg_state_vw 
ON anon_1.committee_id = ofec_sched_a_agg_state_vw.cmte_id 
AND anon_1.fec_election_year = ofec_sched_a_agg_state_vw.cycle 
GROUP BY anon_1.candidate_id, anon_1.election_yr_to_be_included, ofec_sched_a_agg_state_vw.state;

-- takes 6.8 seconds to return
-- explain analyze reveals index from the base table of ofec_sched_a_agg_state_vw was not used somehow (a view does not have indexes but should take advantage from the indexes of its base tables.

**Comment by fecjjeng** [comment]
-- -----------------------
-- analyze the base tables, 
-- not help
-- -----------------------
vacuum analyze disclosure.dsc_sched_a_aggregate_state;
vacuum analyze staging.ref_st;

**Comment by fecjjeng** [comment]
-- ---------------------------------
-- create a materialized view instead of view
-- ---------------------------------
-- -----------------------------
-- before index created on MV, performance already better.(return in 241 msec)
-- -----------------------------
-- -----------------------------
-- create index
-- index used.  query return in 101 msec
-- -----------------------------

**Comment by fecjjeng** [comment]
-- ---------------------------------------
-- try some other way to improve performance
-- Just test the theory, use view with hard coded cmte_id and cycle (without subquery of cand_cmte_linkage_mv)
-- index in base table of ofec_sched_a_agg_state_vw is used (as expected). query return in 101 msec
-- ---------------------------------------
explain analyze
SELECT 
ofec_sched_a_agg_state_vw.state, 
sum(ofec_sched_a_agg_state_vw.total) AS total, 
max(ofec_sched_a_agg_state_vw.state_full) AS state_full, 
sum(ofec_sched_a_agg_state_vw.count) AS count
FROM 
ofec_sched_a_agg_state_vw
where cycle = 2016
and cmte_id in ('C00431569','C00575795')
GROUP BY ofec_sched_a_agg_state_vw.state

**Comment by fecjjeng** [comment]
-- ----------------------------
-- Use subquery, but use the base tables with the condition used to create the view (without going through views)
-- index used.  query return in 101 msec
-- ----------------------------

explain analyze
with anon_1 as
(
	SELECT DISTINCT ofec_cand_cmte_linkage_mv.cand_id AS candidate_id, ofec_cand_cmte_linkage_mv.cmte_id AS committee_id, ofec_cand_cmte_linkage_mv.fec_election_yr AS fec_election_year, ofec_cand_cmte_linkage_mv.election_yr_to_be_included AS election_yr_to_be_included 
	FROM ofec_cand_cmte_linkage_mv 
	WHERE ofec_cand_cmte_linkage_mv.election_yr_to_be_included IN (2016) 
	AND ofec_cand_cmte_linkage_mv.cand_id IN ('P00003392') 
	AND ofec_cand_cmte_linkage_mv.cmte_dsgn IN ('P', 'A')
)
SELECT anon_1.candidate_id, 
anon_1.election_yr_to_be_included AS cycle, 
COALESCE(st.st, 'OT'::character varying) AS state,
sum(sa.total) AS total,
max(COALESCE(sa.state_full, 'Other'::text)) AS state_full,
sum(sa.count) AS count
FROM disclosure.dsc_sched_a_aggregate_state sa
LEFT JOIN staging.ref_st st ON sa.state::text = st.st::text
JOIN anon_1 ON anon_1.committee_id = sa.cmte_id AND anon_1.fec_election_year = sa.cycle 
GROUP BY anon_1.candidate_id, anon_1.election_yr_to_be_included, COALESCE(st.st, 'OT'::character varying)

**Comment by fecjjeng** [comment]
In summary, 
a view does not have indexes but will take advantage from the indexes of its base tables.  The original query use a subquery and a view.  The database optimizer decided not to use the view's base tables' indexes.  We can either 1) create a MV instead of the view or 2) change the query to directly query from base tables.

**Comment by PaulClark2** [comment]
@fecjjeng thank you for all your work on this. So you and @hcaofec think the MV approach is the better option, right.

**Comment by lbeaufort** [comment]
@fecjjeng @hcaofec thanks for working on this issue! 

If we use the base tables, we'll need to calculate the max/sum values on the fly each time, right? So it seems like another advantage to the MV would be to calculate those values one time per day.

**Comment by hcaofec** [comment]
The other endpoint that shares the same function is /schedules/schedule_a/by_size/by_candidate/
and the performance seems fine.

**Comment by fecjjeng** [comment]
> @fecjjeng @hcaofec thanks for working on this issue!
> 
> If we use the base tables, we'll need to calculate the max/sum values "on the fly" - each time, right? So it seems like another advantage to the MV would be to calculate those values one time per day.

Yes, in general, that is one big advantage of the MV.  In this case, the query actually sum up the sum from the view (or the new MV we proposed) on the candidate level.  The alternative version of the query list above actually combined the two layers of sum in one step so does not add extra sum up step.  
Having said that, it will take much more work to re-write the query from SQLAlchemy, especially when the same function touches another endpoint.  Also, the readability of a MV is also better in this case.
