### ISSUE TITLE
Candidate profile pages 404ing

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3977]
Might be related to https://github.com/fecgov/fec-cms/issues/3163 and/or https://github.com/fecgov/openFEC/pull/3958

Reported in feedback repo: https://github.com/fecgov/FEC/issues/9175, https://github.com/fecgov/FEC/issues/9176 and https://github.com/fecgov/FEC/issues/9177

**What we are after**
Display candidates registered for future elections. 

**Why we are after it**
Provide data to the public

**Additional details**
Many 2024 Senate candidate profile pages are 404ing. 

Default and 2018 candidate profile page links

Candidate name|Candidate ID|Default Candidate profile page (CPP)|Load?|2018 CPP|Load?
----|----|----|----|----|----
DUCKWORTH, L TAMMY|S6IL00292|https://www.fec.gov/data/candidate/S6IL00292/|No|https://www.fec.gov/data/candidate/S6IL00292/?cycle=2018&election_full=true|Yes
STRANGE, LUTHER J III|S8AL00308|https://www.fec.gov/data/candidate/S8AL00308/|No|https://www.fec.gov/data/candidate/S8AL00308/?cycle=2018&election_full=true|Yes
FEINSTEIN, DIANNE|S0CA00199|https://www.fec.gov/data/candidate/S0CA00199/|No|https://www.fec.gov/data/candidate/S0CA00199/?cycle=2018&election_full=true|Yes
GILLIBRAND, KIRSTEN ELIZABETH|S0NY00410|https://www.fec.gov/data/candidate/S0NY00410/|No|https://www.fec.gov/data/candidate/S0NY00410/?cycle=2018&election_full=true|Yes
MANCHIN III, JOE|S0WV00090|https://www.fec.gov/data/candidate/S0WV00090/|No|https://www.fec.gov/data/candidate/S0WV00090/?cycle=2018&election_full=true|Yes
MURPHY, CHRISTOPHER S MR|S2CT00132|https://www.fec.gov/data/candidate/S2CT00132/|No|https://www.fec.gov/data/candidate/S2CT00132/?cycle=2018&election_full=true|Yes
HIRONO, MAZIE K|S2HI00106|https://www.fec.gov/data/candidate/S2HI00106/|No|https://www.fec.gov/data/candidate/S2HI00106/?cycle=2018&election_full=true|Yes
WARREN, ELIZABETH|S2MA00170|https://www.fec.gov/data/candidate/S2MA00170/|No|https://www.fec.gov/data/candidate/S2MA00170/?cycle=2018&election_full=true|Yes
KING, ANGUS STANLEY JR|S2ME00109|https://www.fec.gov/data/candidate/S2ME00109/|No|https://www.fec.gov/data/candidate/S2ME00109/?cycle=2018&election_full=true|Yes
FISCHER, DEBRA S|S2NE00094|https://www.fec.gov/data/candidate/S2NE00094/|No|https://www.fec.gov/data/candidate/S2NE00094/?cycle=2018&election_full=true|Yes
HEINRICH, MARTIN TREVOR|S2NM00088|https://www.fec.gov/data/candidate/S2NM00088/|No|https://www.fec.gov/data/candidate/S2NM00088/?cycle=2018&election_full=true|Yes
CRUZ, RAFAEL EDWARD  TED|S2TX00312|https://www.fec.gov/data/candidate/S2TX00312/|No|https://www.fec.gov/data/candidate/S2TX00312/?cycle=2018&election_full=true|Yes
KAINE, TIMOTHY MICHAEL|S2VA00142|https://www.fec.gov/data/candidate/S2VA00142/|No|https://www.fec.gov/data/candidate/S2VA00142/?cycle=2018&election_full=true|Yes
BALDWIN, TAMMY|S2WI00219|https://www.fec.gov/data/candidate/S2WI00219/|No|https://www.fec.gov/data/candidate/S2WI00219/?cycle=2018&election_full=true|Yes
SANDERS, BERNARD|S4VT00033|https://www.fec.gov/data/candidate/S4VT00033/|No|https://www.fec.gov/data/candidate/S4VT00033/?cycle=2018&election_full=true|Yes
CARDIN, BENJAMIN L|S6MD03177|https://www.fec.gov/data/candidate/S6MD03177/|No|https://www.fec.gov/data/candidate/S6MD03177/?cycle=2018&election_full=true|Yes
KLOBUCHAR, AMY|S6MN00267|https://www.fec.gov/data/candidate/S6MN00267/|No|https://www.fec.gov/data/candidate/S6MN00267/?cycle=2018&election_full=true|Yes
TESTER, JON|S6MT00162|https://www.fec.gov/data/candidate/S6MT00162/|No|https://www.fec.gov/data/candidate/S6MT00162/?cycle=2018&election_full=true|Yes
MENENDEZ, ROBERT|S6NJ00289|https://www.fec.gov/data/candidate/S6NJ00289/|No|https://www.fec.gov/data/candidate/S6NJ00289/?cycle=2018&election_full=true|Yes
BROWN, SHERROD|S6OH00163|https://www.fec.gov/data/candidate/S6OH00163/|No|https://www.fec.gov/data/candidate/S6OH00163/?cycle=2018&election_full=true|Yes
CASEY, ROBERT P JR|S6PA00217|https://www.fec.gov/data/candidate/S6PA00217/|No|https://www.fec.gov/data/candidate/S6PA00217/?cycle=2018&election_full=true|Yes
WHITEHOUSE, SHELDON II|S6RI00221|https://www.fec.gov/data/candidate/S6RI00221/|No|https://www.fec.gov/data/candidate/S6RI00221/?cycle=2018&election_full=true|Yes
BARRASSO, JOHN A|S6WY00068|https://www.fec.gov/data/candidate/S6WY00068/|No|https://www.fec.gov/data/candidate/S6WY00068/?cycle=2018&election_full=true|Yes
CARPER, THOMAS R|S8DE00079|https://www.fec.gov/data/candidate/S8DE00079/|No|https://www.fec.gov/data/candidate/S8DE00079/?cycle=2018&election_full=true|Yes
STABENOW, DEBBIE|S8MI00281|https://www.fec.gov/data/candidate/S8MI00281/|No|https://www.fec.gov/data/candidate/S8MI00281/?cycle=2018&election_full=true|Yes
WICKER, ROGER F|S8MS00196|https://www.fec.gov/data/candidate/S8MS00196/|No|https://www.fec.gov/data/candidate/S8MS00196/?cycle=2018&election_full=true|Yes
CANTWELL, MARIA|S8WA00194|https://www.fec.gov/data/candidate/S8WA00194/|No|https://www.fec.gov/data/candidate/S8WA00194/?cycle=2018&election_full=true|Yes

2024 candidate profile page links

Candidate name|Candidate ID|Registered for 2024|2024 CPP|Load?
---|---|---|---|---
DUCKWORTH, L TAMMY|S6IL00292|No|n/a|n/a
STRANGE, LUTHER J III|S8AL00308|No|n/a|n/a
FEINSTEIN, DIANNE|S0CA00199|Yes|https://www.fec.gov/data/candidate/S0CA00199/?cycle=2024&election_full=true|No
GILLIBRAND, KIRSTEN ELIZABETH|S0NY00410|Yes|https://www.fec.gov/data/candidate/S0NY00410/?cycle=2024&election_full=true|No
MANCHIN III, JOE|S0WV00090|Yes|https://www.fec.gov/data/candidate/S0WV00090/?cycle=2024&election_full=true|No
MURPHY, CHRISTOPHER S MR|S2CT00132|Yes|https://www.fec.gov/data/candidate/S2CT00132/?cycle=2024&election_full=true|No
HIRONO, MAZIE K|S2HI00106|Yes|https://www.fec.gov/data/candidate/S2HI00106/?cycle=2024&election_full=true|No
WARREN, ELIZABETH|S2MA00170|Yes|https://www.fec.gov/data/candidate/S2MA00170/?cycle=2024&election_full=true|No
KING, ANGUS STANLEY JR|S2ME00109|Yes|https://www.fec.gov/data/candidate/S2ME00109/?cycle=2024&election_full=true|No
FISCHER, DEBRA S|S2NE00094|Yes|https://www.fec.gov/data/candidate/S2NE00094/?cycle=2024&election_full=true|No
HEINRICH, MARTIN TREVOR|S2NM00088|Yes|https://www.fec.gov/data/candidate/S2NM00088/?cycle=2024&election_full=true|No
CRUZ, RAFAEL EDWARD  TED|S2TX00312|Yes|https://www.fec.gov/data/candidate/S2TX00312/?cycle=2024&election_full=true|No
KAINE, TIMOTHY MICHAEL|S2VA00142|Yes|https://www.fec.gov/data/candidate/S2VA00142/?cycle=2024&election_full=true|No
BALDWIN, TAMMY|S2WI00219|Yes|https://www.fec.gov/data/candidate/S2WI00219/?cycle=2024&election_full=true|No
SANDERS, BERNARD|S4VT00033|Yes|https://www.fec.gov/data/candidate/S4VT00033/?cycle=2024&election_full=true|No
CARDIN, BENJAMIN L|S6MD03177|Yes|https://www.fec.gov/data/candidate/S6MD03177/?cycle=2024&election_full=true|No
KLOBUCHAR, AMY|S6MN00267|Yes|https://www.fec.gov/data/candidate/S6MN00267/?cycle=2024&election_full=true|No
TESTER, JON|S6MT00162|Yes|https://www.fec.gov/data/candidate/S6MT00162/?cycle=2024&election_full=true|No
MENENDEZ, ROBERT|S6NJ00289|Yes|https://www.fec.gov/data/candidate/S6NJ00289/?cycle=2024&election_full=true|No
BROWN, SHERROD|S6OH00163|Yes|https://www.fec.gov/data/candidate/S6OH00163/?cycle=2024&election_full=true|No
CASEY, ROBERT P JR|S6PA00217|Yes|https://www.fec.gov/data/candidate/S6PA00217/?cycle=2024&election_full=true|No
WHITEHOUSE, SHELDON II|S6RI00221|Yes|https://www.fec.gov/data/candidate/S6RI00221/?cycle=2024&election_full=true|No
BARRASSO, JOHN A|S6WY00068|Yes|https://www.fec.gov/data/candidate/S6WY00068/?cycle=2024&election_full=true|No
CARPER, THOMAS R|S8DE00079|Yes|https://www.fec.gov/data/candidate/S8DE00079/?cycle=2024&election_full=true|No
STABENOW, DEBBIE|S8MI00281|Yes|https://www.fec.gov/data/candidate/S8MI00281/?cycle=2024&election_full=true|No
WICKER, ROGER F|S8MS00196|Yes|https://www.fec.gov/data/candidate/S8MS00196/?cycle=2024&election_full=true|No
CANTWELL, MARIA|S8WA00194|Yes|https://www.fec.gov/data/candidate/S8WA00194/?cycle=2024&election_full=true|No

**Completion criteria**
- [ ] Users can see candidates in future elections.

**Comment by lbeaufort** [comment]
An older version of the `master` branch was pushed to production 4 days ago, resulting in the hotfix to address this issue being overwritten. I rebuilt the latest version of `master` which resolved  the majority of these 404s. 

https://circleci.com/gh/fecgov/openFEC/tree/master

Some 404s remain that need to be investigated further:
https://www.fec.gov/data/candidate/S6OH00163/
https://www.fec.gov/data/candidate/S0CA00199/

**Comment by lbeaufort** [comment]
These now load for me - I'm thinking Chrome was aggressively caching. Closing this issue
