### ISSUE TITLE
More than five campaigns returns no results, but also no error message

### ISSUE THREAD

**Issue by rfultz** [fecgov/openFEC#3988]
When a candidate has more than five committees, their [profile page's individual contributions](https://www.fec.gov/data/candidate/P00000489/?tab=raising#individual-contribution-transactions) table shows no entries, but also doesn't tell the user what's going on or how to fix it.

Clicking "Filter this data" (or otherwise going to [/receipts/individual-contributions](https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=1996&&committee_id=C00213850&committee_id=C00317743&committee_id=C00216838&committee_id=C00234427&committee_id=C00300608&committee_id=C00301077) for the candidate) also displays no data and no message.

We may need a front-end ticket to handle the messaging.

For my examples here, I'm using Bob Dole's presidential campaign in '96.

**Comment by lbeaufort** [comment]
We should be able to just remove the restriction on the API side. Example call: https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&committee_id=C00213850&committee_id=C00317743&committee_id=C00216838&committee_id=C00234427&committee_id=C00300608&committee_id=C00301077&two_year_transaction_period=1996&sort=-contribution_receipt_date&per_page=30&is_individual=true

**Comment by lbeaufort** [comment]
Here's the fec-cms issue: https://github.com/fecgov/fec-cms/issues/3272
