### ISSUE TITLE
Check logs PI 10.3 week 1

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3989]
Log review needs to be completed for PI 10.3 week 1 per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Create check logs tickets for the next sprint

**Comment by fecjjeng** [comment]
FEC-CMS: Total 0
package.json: 0
requirements.txt: 0

OPENFEC: Total 0
package.json: 0
requirements.txt: 0
data/flyway/build.gradle: 0 High, 0 medium
   There are 1 High and 1 medium vulnerability shown on Synk. 
   However, both High and Medium vulnerability are on mysql:mysql-connector-java
   **Vulnerable module: mysql:mysql-connector-java**
   we do not use mysql:mysql-connector-java, in data/flyway/build.gradle file, it is specified in the "**exclude group**"

FEC-EREGS: Total 0
package.json: 0
requirements.txt: 0

FEC-PATTERN-LIBRARY: Total 0
package.json: 0

Users changed this week or last:
Search kibana logs
last week:
No users created or deleted.
this week:
No users created or deleted.

Cloud.gov Dashboard: 9 deployer accounts, same as last week.
