### ISSUE TITLE
Check logs PI 10.3 week 2

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3990]
Log review needs to be completed for PI 10.3 week 2 per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Create check logs tickets for the next sprint

**Comment by hcaofec** [comment]
FEC-CMS: Total 0
package.json: 0
requirements.txt: 0

OPENFEC: Total 0
package.json: 0
requirements.txt: 0
data/flyway/build.gradle: 0 High, 0 medium

FEC-EREGS: Total 0
package.json: 0
requirements.txt: 0

FEC-PATTERN-LIBRARY: Total 0
package.json: 0

Users changed this week or last:
Add Jason Upchurch to fecgov ( ticket created and closed )

Search kibana logs
last week:
No users created or deleted.
this week:
No users created or deleted.

Cloud.gov Dashboard: 9 deployer accounts, same as last week.
