### ISSUE TITLE
Increase committee ID limit for schedule A to 10

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3996]
https://api-stage.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&committee_id=C00223743&committee_id=C00223446&committee_id=C00223735&committee_id=C00222778&committee_id=C00222612&committee_id=C00224048&committee_id=C00222273&committee_id=C00222760&committee_id=C00223925&committee_id=C00213850&two_year_transaction_period=1996&two_year_transaction_period=1994&contributor_state=CA&sort=-contribution_receipt_date&per_page=30&is_individual=true

Front end use case: Bob Dole's authorized committees

**Completion criteria**
- [x] Increase the limit to 10
- [x] Test performance
- [x] Add a follow-up ticket to the front end to prevent users from adding more than 10 committee IDs and throw validation if more than 10 are passed https://github.com/fecgov/fec-cms/issues/3272

**Comment by PaulClark2** [comment]
There were some coding issues with a few of Dole's delegate committees. I've corrected those. 

This candidate P60000452 1996 (1993-1996) has 10 authorized committees.
