### ISSUE TITLE
Load test legal

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3999]
With #3985 we should do some load testing on Locust and compare it to previous results. Increasing the timeout is a temporary solution - query results shouldn't be taking over 10 seconds to load. We've seen issues on the cloud.gov side before, so we should do some research to see if there are performance issues.

**Comment by lbeaufort** [comment]
In our monthly checkin, cloud.gov mentioned some changes they're making to their managed services around October 21 that may result in performance improvements. They also asked us if we could avoid load testing until then.

**Comment by JonellaCulmer** [comment]
@lbeaufort Is this still an issue?

**Comment by lbeaufort** [comment]
Yes, but it can wait.

**Comment by lbeaufort** [comment]
Stale, so closing.
