### ISSUE TITLE
Add candidate_id filter back to schedules/schedule_e/efile

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4005]
To be consistent with other endpoints (especially `schedules/schedule_e/`) and because it was a breaking change to remove it, we should add `candidate_id` back to `schedules/schedule_e/efile`

### Completion Criteria
- [ ] Candidate ID is added a filter in the end point
- [ ] Once change is implemented, test the front end to evaluate if more work is needed.

**Comment by jason-upchurch** [comment]
associated PR ready for review #4041
