### ISSUE TITLE
Add name to nicknames

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#4015]
**What we are after:
We would like users to find candidates by their commonly know name.

**Task
Add Mark Sanford as a nickname of Marshall Sanford

**Completion criteria
- [x] Add Mark Sanford as a nickname of Marshall Sanford

**Comment by pkfec** [comment]
Below two new rows are inserted into`ofec_nicknames` table  in `dev`, `stage` and `prod` DB. `ofec_candidate_fulltext_mv` is  manually refreshed in `dev` space only.  On `stage` and `prod` spaces after the scheduled daily MV refresh, the candidate `SANFORD, MARSHALL C. HON` will be searchable by his nick name `mark sanford`

1. H4SC01073 mark sanford 
2. P00013649 mark sanford

**Comment by pkfec** [comment]
After today's daily MV refresh the candidate `SANFORD, MARSHALL C. HON` is now searched by his nick name `Mark Sanford` in `stage` and `prod` spaces .

Hence closing this issue.
