### ISSUE TITLE
Notify the Deprecated endpoints users: /committee/<committee_ID>/schedules/schedule_x/by_xx/

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4023]
Ref Issue: [https://github.com/fecgov/openFEC/issues/3995](https://github.com/fecgov/openFEC/issues/3995)
 Ref PR: [https://github.com/fecgov/openFEC/pull/4022](https://github.com/fecgov/openFEC/pull/4022)

These 9 endpoints are deprecated:
/committee/<committee_ID>/schedules/schedule_a/by_employer/
/committee/<committee_ID>/schedules/schedule_a/by_occupation/
/committee/<committee_ID>/schedules/schedule_a/by_size/
/committee/<committee_ID>/schedules/schedule_a/by_state/
/committee/<committee_ID>/schedules/schedule_a/by_zip/
/committee/<committee_ID>/schedules/schedule_b/by_purpose/
/committee/<committee_ID>/schedules/schedule_b/by_recipient/
/committee/<committee_ID>/schedules/schedule_b/by_recipient_id/
/committee/<committee_ID>/schedules/schedule_e/by_candidate/

### Completion Criteria
- [x] Send email to api users.
Solution for api users:
Please use /schedules/schedule_x/by_xxxxxx/?committee_id=<committee_ID>

**Comment by PaulClark2** [comment]
I've updated the API receipts documentation I've been working on. I've added `[Deprecated]` to the descriptions of five endpoints listed below.

/committee/<committee_ID>/schedules/schedule_a/by_employer/
/committee/<committee_ID>/schedules/schedule_a/by_occupation/
/committee/<committee_ID>/schedules/schedule_a/by_size/
/committee/<committee_ID>/schedules/schedule_a/by_state/
/committee/<committee_ID>/schedules/schedule_a/by_zip/

**Comment by PaulClark2** [comment]
Email sent 10/21.
