### ISSUE TITLE
Update labels for deprecated endpoints

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4025]
How to deprecate the endpoint: 
- [x] Add [DEPRECATED] to the endpoint descriptions https://github.com/fecgov/openFEC/pull/4022 (merged)

**Related issues**
-  Switch the front end to use the alternate endpoint https://github.com/fecgov/fec-cms/issues/3285
-  Notify API users that have called the deprecate endpoints in the past 3 months, telling them to use alternate endpoints https://github.com/fecgov/openFEC/issues/4023
-  Remove the deprecated endpoints code: https://github.com/fecgov/openFEC/issues/4024
-  Update Pingdom alerts: https://github.com/fecgov/openFEC/issues/4024

Ref Issue: [https://github.com/fecgov/openFEC/issues/3995](https://github.com/fecgov/openFEC/issues/3995)

**Comment by PaulClark2** [comment]
Deprecation policy published 10/21, https://github.com/fecgov/openFEC/wiki#api

**Comment by lbeaufort** [comment]
Remaining work has been split into new issues.
