### ISSUE TITLE
Update Flask to latest version

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4026]
As a test for updating python packages, this will be a test case for making a change with out breaking.

Current: 1.0.2
Updated: 1.1.1

**Previous issues**
#3954 

### Completion Criteria
- [x] Update Flask, test for breaking changes

**Comment by jason-upchurch** [comment]
@lbeaufort @PaulClark2 I installed Flask 1.1.1 and ran pytest which passes. In issue #4026 the "breaking changes" refers to packages that have any breaking changes, rather than breaking in the way we use it.
