### ISSUE TITLE
Add test coverage for committee financial summary

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4027]
## Summary
We need to expand test coverage to catch issues related to #4016 
>A presidential candidate has two committees. The PCC is filing on Form 3P, but the other authorized committee is filing on Form 3. Both committees are committee type "P."  The PCC's profile page is ok, https://www.fec.gov/data/committee/C00699090/?cycle=2020. The other authorized committee profile page incorrectly says we don't have data for the committee, https://www.fec.gov/data/committee/C00501197/?cycle=2020.

## First pass at completion criteria
- [ ] test fails for pre-bug fix above
- [ ] test passes for correct implementation of bug fix

**Comment by hcaofec** [comment]
PR is merged, so close.
