### ISSUE TITLE
More Python package updates

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4033]
- [ ] Pick a few
- [ ] Enter a follow-up issue for more

**Comment by jason-upchurch** [comment]
See also issue https://github.com/fecgov/openFEC/issues/3953

**Comment by JonellaCulmer** [comment]
Closing this ticket. There will be a meeting to discuss how we will move forward with future python package updates - if tickets need to happen in a particular order, what the priorities are, and how we may want to space this work out over time.
