### ISSUE TITLE
Issue on the website with an Advisory Opinion summary in AO 2016-25

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4035]
Hi, all,
 
I don’t know if the problem is with the AO system interpreting an apostrophe, or the website interpreting the apostrophe, but instead of an apostrophe showing up, there are weird symbols showing on the website. Entry into AODES is not the issue.  Therefore, I am sending it to all of you. Thanks in advance
 
“The first is AO 2016-25 (Mike Pence for Indiana). The issue description (which you can see here https://www.fec.gov/data/legal/advisory-opinions/2016-25/) has a weird A with an upside down question mark instead of an apostrophe. I tried to go into AODES-NG to fix it but it looks good there. Any idea how to make sure it has the right apostrophe displayed?”

**Comment by jason-upchurch** [comment]
The db entry for this "summary" can be obtained as

```sql
select * from aouser.aos_with_parsed_numbers where ao_id = 4310;
```
and contains the apostrophe.

Also may want to investigate output from `legal_docs/advisory_opinions.py` to see if apostrophe is preserved.

**Comment by lbeaufort** [comment]
Looks like AOs were reloaded after the data was changed, but the issue is still in elasticsearch. 

API query: https://api.open.fec.gov/v1/legal/docs/advisory_opinions/2016-25?api_key=DEMO_KEY
ES query (after SSHing): `curl -X GET -u "${es_username}:${es_password}"  "localhost:9200/docs_index/advisory_opinions/2016-25"`
````
...
"summary": "Issue: Use of nonfederal funds to pay for certain activities by federal candidateÂ¿s state campaign committee."
```

Just to be sure, I’m reloading AOs in production
`cf run-task api "python manage.py load_advisory_opinions -f AO 2016-25" -m 4G --name reload-aos`

**Comment by lbeaufort** [comment]
After a reload, the issue seems to be fixed. I'll spend a little time trying to figure out why the automatic reload didn't pick this up.

**Comment by lbeaufort** [comment]
After further research, the reload was most likely affected by the elasticsearch outage on 10/22. The update date on this AO is ` 2019-10-22 19:22:19 `. 

https://www.fec.gov/data/legal/advisory-opinions/2016-25/
