### ISSUE TITLE
Update API documentation to indicate raw data(/efile/ endpoints) is limited to 4 months

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4045]
**What we're after:** 
Now that we've removed raw filings beyond 4 months for raw data(/efile/ endpoints), we need to make it clear on the API that the limitation exists. 

**Completion criteria:**
- [x] Draft language alongside the content team
- [x] Implement language wherever appropriate in API documentation

**Comment by JonellaCulmer** [comment]
Draft content: 

https://github.com/fecgov/fec-cms/issues/3319#issuecomment-552947911

**Comment by jason-upchurch** [comment]
floating this suggestion around:

>These endpoints are perfect for watching filings roll in when you want to know the latest information. Efiling endpoints only contain the most recent ~two years~ [insert: four months] worth of data and don't contain the processed and coded data that you can find on the other endpoints. Those endpoints are better for in-depth analysis.
