### ISSUE TITLE
Remove unneeded package installation from config.yml

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4047]
### Summary
`requirements-dev.txt` is a set of python libraries intended to provide developers tools for testing the application before deploying. Currently in `config.yml` these libraries are installed along with our application. 

These libraries should not be installed to production, and if any libraries in `requirements-dev.txt` are needed for production, they should be added to `requirements.txt` instead.

```
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt -r requirements-dev.txt -r requirements-ci.txt
```
### Additional option:
add `requirements-local.txt` to `.gitignore` so that devs can also maintain any local packages that help them develop in addition to `requirements-dev.txt`. For example, some packages a developer may want to use may not be in `requirements-dev.txt`, e.g., `pandas`, but others may want to use it. We don't want every developer to be required to install it with `requirements-dev.txt`. 

Adding `requirements-local.txt` to `.gitignore` does not require any developer to have or maintain a different local package set.

### Completion criteria
- [ ] identify which packages in `requirements-dev.txt` are actually used for a build
- [ ] move all required packages to `requirements.txt`
- [ ] move `locust` to `requirements-dev.txt`
- [ ] update `config.yml` to remove references to `requirements-dev.txt`
- [ ] submit PR with comprehensive test steps

**Comment by jason-upchurch** [comment]
@lbeaufort thank you. What do you think about moving pytest to requirements.txt since it is a requirement to build?

**Comment by lbeaufort** [comment]
@jason-upchurch while I think it makes sense to keep the packages to run the app separate from the packages to test the app, I don't think it matters too much except for what helps the team. 

In `requirements-dev`, I think most of the packages in there are for testing and are needed by Circle, but not all. I don't have a preference for how we organize things as long as it works for the team. 

If we put all the things Circle needs in `requirements.txt`, we could make a testing section and group them together. If we keep `requirements-dev` to just internal tools, it might make sense to put locust in there.

**Comment by jason-upchurch** [comment]
@lbeaufort I really like this idea
>If we put all the things Circle needs in requirements.txt, we could make a testing section and group them together. If we keep requirements-dev to just internal tools, it might make sense to put locust in there.

and can run it by the team when we discuss the issue. Thank you for identifying the locust as another one to clean up! 

I'm thinking of a couple of benefits of not having dev dependencies installed in production while still allowing or not blocking any team members from using whatever tools they need. We could also `.gitignore` something like `requirements-local.txt` and any developer could then install absolutely any tool they want independently in addition to whatever is in `requirements-dev.txt`. I'll add this idea for team discussion. Thanks!
