### ISSUE TITLE
Filings API: Incorrect fec_url and pdf_url values

### ISSUE THREAD

**Issue by rfultz** [fecgov/openFEC#4053]
### Description

Images prior to 2000 are not being displayed on FEC.gov, even if a PDF exists. The URL is not being generated, so the front-end doesn't have anything to pass to docquery. We need to correct this so that users are able to access are more "historical" images, regardless of when they were made. 

Example:

- https://www.fec.gov/data/committee/C00213512/?tab=filings&cycle=1998
- expand the panel for RFAI: POST-GENERAL 1998

The data returned includes
- null value for `pdf_url`. The pdf exists.
- semi-legit value for `fec_url`, except there's no filename—only a path and file extension. (The string.format is being given a null?)

### Desired behavior

Proper values should be returned for `pdf_url` and `fec_url`

**Completion criteria:**
- [ ] If the FEC link exists, the PDF should show. It's currently appearing as expected on classic.fec.gov

**Comment by rfultz** [comment]
This work is related to fec-cms #3276 and #3309 .

**Comment by rfultz** [comment]
Tagging @PaulClark2 for priority and because we were examining the data.

I'm interested in helping/pairing on it—seems like it shouldn't be _too_ complicated...?

**Comment by pkfec** [comment]
API is returning `pdf_url`, `fec_url` for `committee_id= C00213512` :  https://api.open.fec.gov/v1/committee/C00213512/filings/?page=1&sort_null_only=false&api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&sort=-receipt_date&per_page=20

**Comment by fec-jli** [comment]
additional think: how to handle some pdf files which not exist on docquery.fec.gov hold by contractor.
ex: https://docquery.fec.gov/pdf/100/96016044100/96016044100.pdf
currently, we got `page not found` page without stylesheet. 

<img width="400" alt="Screen Shot 2021-04-13 at 3 34 30 PM" src="https://user-images.githubusercontent.com/24395751/114610387-d42cb480-9c6d-11eb-96da-619e2e1b82c8.png">
