### ISSUE TITLE
Add most_recent column to ofec_sched_e_mv to support added filters on most_recent in /schedules/schedule_e

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#4056]
Issue #3817 requested to add filters and output fields to /schedules/schedule_e/
Dissemination_date field is already in the the backend MV ofec_sched_e_mv
Filing_date needed to be added to ofec_sched_e_mv to support this functionality (added in issue #4054 
Most_recent need more research to be complete and will be added in separate ticket.

This ticket address to add the most_recent to ofec_sched_e_mv

**Comment by fecjjeng** [comment]
ofec_sched_e_mv has 4 sources:
-form5 regular filing (regular report): data from fec_fitem tables. So it is most_recent)
-form5 notice (notice)
-form3X sched e (regular report): data from fec_fitem tables. So it is most_recent)
-form24 sched_e (notice)

**Comment by fecjjeng** [comment]
In summary, for F3X and F5 REGULAR REPORT, what is in ofec_sched_e_mv are most recent. For F24 and F5 notice, we can not be sure what is most recent or not so we treat every one as an independent one. Not sure if a most_recent column will help.

**Comment by fecjjeng** [comment]
For regularly filed reports (such as Q1, YE, etc), 
v_sum/f_item table has the most recent filing.  
Therefore the most_recent flag for rows from fec_fitem tables are set to "true"

For notices, we need to base on the amendment chain (file_num/prev_file_num).
However, for quite some pfiled reports, the file_num < 0 and this amendment chain mothod is not reliable.
And since they don't have a fixed file time, the receipt_dt/image_num based method can not be used neither.

**Comment by fecjjeng** [comment]
Currently, we have several amendment chain related mv/vw.  
ofec_processed_financial_amendment_chain_vw, which only consist reports with file_num > 0 and is more reliable.
Fortunately, for sched_e notices, majority of the reports has file_num > 0.
Therefore this vw is choosen to be the source to determin the most_recent flag for the notices.  
If a report's file_num can not be find in ofec_processed_financial_amendment_chain_vw, 
then we can not determin if it is most recent or not, the most_recent is set to null

If its file_num is the same as the mst_rct_file_num, then most_recent = 'true'
If its file_num is the different from the mst_rct_file_num, then most_recent = 'false'

**Comment by fecjjeng** [comment]
After discussed the situation with @PaulClark2. He agreed the above rules are acceptable for the most_recent flag in sched_e.

**Comment by fecjjeng** [comment]
There is no added/removed dependency to other MV.  Therefore no manage.py/flow.py change.
(ofec_processed_financial_amendment_chain_vw is a pure view, not the front interface to a MV)

**Comment by fecjjeng** [comment]
-- Checked the rows with most_recent null in the updated MV:
select cmte_id, link_id, filing_form, rpt_yr, rpt_tp, count(*)
from ofec_sched_e_mv_tmp_jj 
where most_recent is null
group by cmte_id, link_id, filing_form, rpt_yr, rpt_tp
order by cmte_id, link_id, filing_form, rpt_yr, rpt_tp
/*
-- 813 reports found
majority are F24.

only 1 row with sub_id 4xxxxxx, all others are 1xxxxxxx

"C00003418";4051620171404175240;"F24";2017;"48";1
*/

select * from disclosure.f_rpt_or_form_sub where sub_id = 4051620171404175240
-- 1162434;1162427
-- In Oralce: there is no rows with file_num 1162427 in f_rpt, nml_form_24, nml_form_3X, in real_efile.reps, real_pfile.ppreps.
--	amendment chain of this record can not calculated even file_num > 0 since there is no base to connect to
-- In Oracle, real_efile.reps, the rptnum of repid 1162434 is 0 and previd is null.


select cmte_id, rpt_yr, rpt_tp, file_num, prev_file_num
from ofec_sched_e_mv_tmp_jj 
where link_id = 4051620171404175240
-- "C00003418";2017;"48";1162434;1162427

select * from ofec_processed_financial_amendment_chain_vw where file_num = 1162434
-- no row selected

It seems that particular record has error.  Otherwise the most_recent flag for all efiled records has value.

**Comment by JonellaCulmer** [comment]
Work has been merged, so closing.
