### ISSUE TITLE
Make an endpoint calculate total electioneering communications

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#4062]
Make an endpoint calculate total electioneering communications for  "other spending"

While investigating  [this bug](https://github.com/fecgov/fec-cms/pull/2702
), @lbeaufort discovered that we calculate "other spending" totals on the front-end side, using JavaScript. We should make endpoints to calculate these totals rather than calculating them on the front-end, for consistency and performance improvement.

Example: https://www.fec.gov/data/candidate/P80001571/?tab=other-spending

- [x] Research data needs for EC totals
- [x] Make endpoint for EC totals
- [ ] Add automated tests
- [ ]  Make front-end ticket to use these endpoints

**Comment by hcaofec** [comment]
To calculate total electioneering communications, the new endpoint will utilize ofec_electioneering_aggregate_candidate_mv that's already exists as data source.

**Comment by JonellaCulmer** [comment]
PR has been merged, so closing.
