### ISSUE TITLE
review config.yml and decide if necessary to upgrade npm/node

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4070]
### Summary

`npm` and `node` build / deploy versions appear to be older than perhaps those local versions in use by the team. We may want to upgrade.

```
      - run:
          name: Install node dependencies
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
            echo ". ~/.nvm/nvm.sh" >> $BASH_ENV
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            nvm install 8.9.1
            nvm use 8.9.1
            nvm alias default 8.9.1
            npm install -g npm swagger-tools
            npm install
            npm run build
```

### Completion criteria
- [x] review `config.ym`
- [x] decide on modifying with other versions of npm (5.5.1) / node (8.9.1)

**Comment by pkfec** [comment]
activate python virtual environment
list all the available node version that are already installed in your machine : nvm ls
If you already have v10.16.0, Alias new version to default : nvm alias default v10.16.0

if node version is not installed : Install LTS version of node:  nvm install v10.16.0
Alias new version to default:  nvm alias default v10.16.0
Use new version:  nvm use default
Upgrade npm:  npm install -g npm
Check node version: node -v
check npm version : npm -v 
At this point your node and npm should be : v10.16.0 & v6.13.7
Remove node_modules/ from openFEC repo
Install node modules: npm install
Install all the python pkgs  : npm run build
Install swagger-tools:  npm install -g swagger-tools
install requirement.txt and requirement-dev.txt
./manage.py runserver
test endpoints
