### ISSUE TITLE
Create prototype for schedule_h4 endpoint

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4112]
### Summary

In preparation for our H schedule Data Design Studio the back-end team suggested that a prototype for H schedule data may be useful to help analysts and other interested users to understand the endpoint functionality. Considering schedule H4 data is most similar to a schedule B data, it was suggested that the Schedule B endpoint would a good template for creating this prototype.

THIS SHOULD NOT BECOME A BLOCKER FOR THE DATA DESIGN STUDIO.

**Previous tickets:** #3341 (H4 data request -- ~currently in icebox~ closed)

What's needed
- duplicate functionality for schedule b endpoint for a prototype of `fec_fitem_sched_h4`
- this will be a starting point to determine additional filters (or potentially removal of filters)
- Users may be interested in being able to cross reference `fec_fitem_sched_b`

### completion criteria
- [x] prototype is available for use in the data design studio.
- [x] notify @JonellaCulmer that the prototype is ready for use.
- [x] write basic test cases (may need to revise these based on "Future work" below

### Future work
- Create a data table of H schedule data (PI 12)

**Comment by bmathesonFEC** [comment]
@jason-upchurch Thank you for picking this up!  I'll get you set up with a RAD manager or analyst to give you -- and whoever else from the backend team wants to join --  an overview of Schedule H. We'll talk offline.

**Comment by jason-upchurch** [comment]
```
conduit_cmte_id
conduit_cmte_nm
conduit_cmte_st1
conduit_cmte_st2
conduit_cmte_city
conduit_cmte_st
conduit_cmte_zip
admin_acty_ind
gen_voter_drive_acty_ind
catg_cd
catg_cd_desc
disb_tp
disb_tp_desc
pub_comm_ref_pty_chk
memo_cd
memo_cd_desc
memo_text
action_cd
action_cd_desc
tran_id
back_ref_tran_id
back_ref_sched_id
schedule_type 
schedule_type_desc
line_num
image_num
file_num
link_id
orig_sub_id
sub_id
filing_form
rpt_tp
rpt_yr
election_cycle
pg_date
```

**Comment by bmathesonFEC** [comment]
@jason-upchurch Still trying to lock down a H schedule overview for you, will be Friday at the earliest. 

The one thing that jumps out at me is that the first few fields are titled "conduit".  Since the payee's on Schedule H are not conduits, I'm surprised to see that as the naming convention for the primary fields of the transaction (id, name, address, etc.).

Unfortunately I don't have read access tot the database anymore because it prevents my access to another RAD specific program. Might have to do a side-by-side or a screen share on this.

**Comment by bmathesonFEC** [comment]
Looking at this more thoroughly, think there are a few missing fields in additional to the conduit note in the previous comment. I included a screenshot of the H4 so you can see what pieces of information are available to report so you can compare that to the database:

- purpose of disbursement
- date
- activity or event identifier
- federal share (numeric)
- non-federal share (numeric)
- total amount (numeric)

![image](https://user-images.githubusercontent.com/33758291/71377989-2dae3300-2594-11ea-8ece-cdb961beb00a.png)

**Comment by bmathesonFEC** [comment]
I just emailed some transaction data from a report, may be helpful in navigating the database to find the right fields.

**Comment by jason-upchurch** [comment]
Hi @bmathesonFEC, thanks for all of this! Just to clarify, the things in my last comment were ALL of the fields that exist in the `fec_fitem_sched_h4` table, so I think the fields we will need will (probably) be available. For example, the name `conduit` is just a name (unless there is some glaring error), so it probably means something that actually makes sense in the right context (at least I hope so!)
