### ISSUE TITLE
Check logs 11.1 week 1

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4119]
- [ ] Log review needs to be completed for sprint 11.1 week 1 per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by jason-upchurch** [comment]
@patphongs per @PaulClark2 the due date for this work is 12/26/2019 (Thursday).

**Comment by patphongs** [comment]
FEC-CMS: Total 3
package.json: 0
requirements.txt: 
fecgov/fec-cms#3396 
https://github.com/fecgov/fec-cms/issues/3422 
https://github.com/fecgov/fec-cms/issues/3423

OPENFEC: Total 0
package.json: 0
requirements.txt: 0
data/flyway/build.gradle: 0 High, 0 medium

FEC-EREGS: Total 0
package.json: 0
requirements.txt: 0

FEC-PATTERN-LIBRARY: Total 0
package.json: 0

Search kibana logs
last week: No users created or deleted
This week: No users created or deleted

Cloud.gov Dashboard: 9 deployer accounts, same as last week.
