### ISSUE TITLE
Check logs 11.1 week 2

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4120]
- [x] Log review needs to be completed for sprint 11.1 week 2 per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

- [ ] Create check logs tickets for the next sprint

**Comment by jason-upchurch** [comment]
@pkfec per @PaulClark2 the due date for this is 1/2/2020 (Thursday)

**Comment by pkfec** [comment]
FEC-CMS: Total 3
package.json: 0
requirements.txt:
fecgov/fec-cms#3396
fecgov/fec-cms#3422
fecgov/fec-cms#3423

OPENFEC: Total 0
package.json: 0
requirements.txt: 0
data/flyway/build.gradle: 0 High, 0 medium

FEC-EREGS: Total 0
package.json: 0
requirements.txt: 0

FEC-PATTERN-LIBRARY: Total 0
package.json: 0

Search kibana logs
last week: No users created or deleted
This week: No users created or deleted

Cloud.gov Dashboard: 9 deployer accounts, same as last week.

**Comment by pkfec** [comment]
Completed log review on 01/02/2020. Hence closing the ticket.
