### ISSUE TITLE
Fix cycles_has_activity return NULL in ofec_committee_history_mv

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4126]
Ref PR: [https://github.com/fecgov/fec-cms/pull/3427](https://github.com/fecgov/fec-cms/pull/3427)

wrong query example: select * from ofec_committee_history_mv where committee_id='C00140590'
cycles_has_activity=[1982, 1984, 1986, 1988, 1990, 1992, 1994, 1996, 1998, 2000, 2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018, 2020, NULL]

the correct query: select * from ofec_committee_history_mv where committee_id='C00105668'
cycles_has_activity=[1978, 1980, 1982, 1984, 1986, 1988, 1990, 1992, 1994, 1996, 1998, 2000, 2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018, 2020]

- [x] find out the reason and fix MV
- [x] add test coverage to test this MV

**Comment by hcaofec** [comment]
PR was merged, so closing.
