### ISSUE TITLE
Preserve archived MUR data in Postgres or archived MUR XML

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4129]
**What we're after:**
Currently, archived MUR data is loaded using the [classic website](https://classic.fec.gov/MUR/MURData.do). We need to update the ability to re-load archived MURs without the classic site.

### Root cause
After the shutdown of classic, we need to find a way to continue loading archived MUR data when there is an update.

### Planning
We may want to use the same archived MUR xml file to pull in archive MUR data into ElasticSearch. Find a new home for archived MUR xml file.

**Completion criteria**
- [ ] ElasticSearch is able to pull data from the archived MUR xml file
- [ ] Be able to continue reloading archived MURs into ElasticSearch

### Additional information
Occasionally, we need to re-load archived MURs from scratch again to fix issues like legal citations, see #3942 as reference. We don't want to depend on the classic site for loading this data anymore.

### Future work
Load archived MUR data into postgres https://github.com/fecgov/openFEC/issues/4151

**Comment by lbeaufort** [comment]
@fec-jli will upload the archived MUR XML files to S3

**Comment by fec-jli** [comment]
** Upload all classic arc-mur **data_files** to prod api s3 bucket(cg-519axxxxxxxxxxxxxx1f74)
There are two folders: 1032 and xml under **data_files**
https://cg-519axxxxxxxxxxxxxxxxxxxxxx1f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/index2.html?prefix=bulk-downloads/arc-mur/data-files

1)under xml folder ( 4 files):
https://cg-519axxxxxxxxxxxxxxxxxxxxxx1f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/index2.html?prefix=bulk-downloads/arc-mur/data-files/xml/
dateTime.xsl
mur.xsl
murArchive.xml
pagination.xsl

2)under 1032 folder (12 files)
https://cg-519axxxxxxxxxxxxxxxxxxxxxx1f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/index2.html?prefix=bulk-downloads/arc-mur/data-files/1032/
CITE.DMO	
MURCIT.DMD
MURCIT.DMO
MURCIT.TXT
MURCOMPRESP.TXT
MURDATES.TXT
MURSUB.DMD
MURSUB.DMO	
MURSUB.TXT	
SUBJCT.DMD
SUBJCT.DMO

3)upload all arc-mur pdf files (4461 filers)
https://cg-519axxxxxxxxxxxxxxxxxxx1f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/index2.html?prefix=bulk-downloads/arc-mur/

**Comment by fec-jli** [comment]
Two options to upload archived MURs to Elasticsearch (don't  depend on the classic site), we can add into innovation sprint:

1)From PostgresSQL database to Elasticsearch
Currently, all archived MURs data(11 tables and 1 procedure) is stored in oracle db, schema: **mur_arch**, we can transfer those to PostgresSQL (aws). convert procedure to MV.

a)11 tables:
cite
murao
murcit
murcom
murflm
murmst
murmst_bad
murrel
mursub
subjct
subjct_from_file

b) 1 procedure: proc_get_mur_subject (to generate **subject** column for display)

=========mur_arch.proc_get_mur_subject script============
CREATE OR REPLACE PROCEDURE MUR_ARCH.proc_get_mur_subject(p_mur in number,p_clob out clob) IS
/******************************************************************************
 NAME: MUR_ARCH.proc_get_mur_subject_xml
   PURPOSE:
   REVISIONS:
   Ver        Date        Author           Demur scription
   ---------  ----------  ---------------  ------------------------------------
   1.0        11/9/2012   mbasupalli       1. Created this procedure.
******************************************************************************/
v_clob  clob;
cursor cur_main is
SELECT   to_number(level_1) level_1,to_number(level_2) as level_2 ,to_number(level_3) as level_3,
(case when to_number(level_2)=0 then subject else
(case when to_number(level_3)=0 then '<li>'||subject||'</li>' else '<li>'||subject||'</li>'end)
end) subject,
2 as src
          FROM  MUR_ARCH.SUBJCT_FROM_FILE sb
          WHERE  mur=p_mur
union all
select to_number(level_1),to_number(level_2),0.1 as level_3, '<ul class=''nomargin''>'as subject,1 as src  from MUR_ARCH.SUBJCT_FROM_FILE where
mur=p_mur
group by level_1,level_2
having count(*)>1
union all
select to_number(level_1),to_number(level_2),9999 as level_3, '</ul>'as subject,3 as src from MUR_ARCH.SUBJCT_FROM_FILE where
mur=p_mur
group by level_1,level_2
having count(*)>1
union all
select to_number(level_1),0.1 as level_2,0.1 as level_3, '<ul class=''nomargin''>'as subject,1 as src  from MUR_ARCH.SUBJCT_FROM_FILE where
mur=p_mur
group by level_1
having count(*)>1
union all
select to_number(level_1),9999 as level_2,9999 as level_3, '</ul>'as subject,3 as src from MUR_ARCH.SUBJCT_FROM_FILE where
mur=p_mur
group by level_1
having count(*)>1
order by 1,2,3,src;

BEGIN
p_clob:=' ';
  for r1 in cur_main loop
       p_clob:=p_clob||'  '||r1.subject;
  end loop;
   -- dbms_output.put_line(p_clob);
END proc_get_mur_subject;
/


2)From arc-mur (s3 bucket) to Elasticsearch

**Comment by dorothyyeager** [comment]
@lbeaufort see above

**Comment by lbeaufort** [comment]
This is enough work to preserve the archived MUR data for now - because GPO put in redirects and most of the archived MURs were successfully reloaded with the new format (see https://github.com/fecgov/openFEC/issues/3942#issuecomment-578876555) per @PaulClark2 I'm going to de-prioritize this issue for now. 

Thanks for your work on this @fec-jli!

**Comment by pkfec** [comment]
> Two options to upload archived MURs to Elasticsearch (don't depend on the classic site), we can add into innovation sprint:
> 
> 1)From PostgresSQL database to Elasticsearch
> Currently, all archived MURs data(11 tables and 1 procedure) is stored in oracle db, schema: **mur_arch**, we can transfer those to PostgresSQL (aws). convert procedure to MV.
> 
> a)11 tables:
> cite
> murao
> murcit
> murcom
> murflm
> murmst
> murmst_bad
> murrel
> mursub
> subjct
> subjct_from_file
> 
> b) 1 procedure: proc_get_mur_subject (to generate **subject** column for display)
> 
> =========start mur_arch.proc_get_mur_subject script============
> CREATE OR REPLACE PROCEDURE MUR_ARCH.proc_get_mur_subject(p_mur in number,p_clob out clob) IS
> /******************************************************************************
> NAME: MUR_ARCH.proc_get_mur_subject_xml
> PURPOSE:
> REVISIONS:
> Ver Date Author Demur scription
> 1.0 11/9/2012 mbasupalli 1. Created this procedure.
> **************************************************************************____/ v_clob clob; cursor cur_main is SELECT to_number(level_1) level_1,to_number(level_2) as level_2 ,to_number(level_3) as level_3, (case when to_number(level_2)=0 then subject else (case when to_number(level_3)=0 then '____
> 
> * ___'||subject||'___
> ___' else '* '||subject||''end) end) subject, 2 as src FROM MUR_ARCH.SUBJCT_FROM_FILE sb WHERE mur=p_mur union all select to_number(level_1),to_number(level_2),0.1 as level_3, '<ul class=''nomargin''>'as subject,1 as src from MUR_ARCH.SUBJCT_FROM_FILE where mur=p_mur group by level_1,level_2 having count(_)>1 union all select to_number(level_1),to_number(level_2),9999 as level_3, ''as subject,3 as src from MUR_ARCH.SUBJCT_FROM_FILE where mur=p_mur group by level_1,level_2 having count(_)>1 union all select to_number(level_1),0.1 as level_2,0.1 as level_3, '<ul class=''nomargin''>'as subject,1 as src from MUR_ARCH.SUBJCT_FROM_FILE where mur=p_mur group by level_1 having count(_)>1
> union all
> select to_number(level_1),9999 as level_2,9999 as level_3, ''as subject,3 as src from MUR_ARCH.SUBJCT_FROM_FILE where
> mur=p_mur
> group by level_1
> having count()>1
> order by 1,2,3,src;
> BEGIN
> p_clob:=' ';
> for r1 in cur_main loop
> p_clob:=p_clob||' '||r1.subject;
> end loop;
> -- dbms_output.put_line(p_clob);
> END proc_get_mur_subject;
> /
> =========end mur_arch.proc_get_mur_subject script============
> 
> 2)From arc-mur (s3 bucket) to Elasticsearch

@fec-jli i think you have captured all the required archived mur info. Thanks for documenting all the info.

**Comment by fec-jli** [comment]
see issue [https://github.com/fecgov/openFEC/issues/4465](https://github.com/fecgov/openFEC/issues/4465)
