### ISSUE TITLE
Add filing_form and is_notice params as filterable field within /schedules/schedule_e/efile/

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4140]
## Summary

**What we're after:**
Within the Independent Expenditures datatable, in order to be able to implement filtering for 24- and 48- hour reports and regularly scheduled reports (Form 5 and Form 3X), we need to be able to filter by `filing_form` and `is_notice`. This parameter is only available under the `/schedules/schedule_e/` endpoint and not the efile endpoint.

We should modify the model file to include `filing_form` and `is_notice`. This may need a database change so that we have a cleaner format.

https://api.open.fec.gov/v1/schedules/schedule_e/efile/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&data_type=efiling&is_notice=true&filing_form=F3X&sort=-expenditure_date&per_page=30&page=1

**Completion criteria**
- [ ] make `filing_form` filterable
- [ ] make `is_notice` filterable

**Comment by PaulClark2** [comment]
/schedules/schedule_e/efile/ has  `form_type`. This field should have the some information as `filing_form`.

**Comment by fec-jli** [comment]
1)real_efile.f57 and real_efile.se have no form_type, need join real_efile.reps on repid to get form_tp as filing_form.
2)real_efile.se and real_efile.f57 are Form 3X, Form 24, and Form 5. we need clean form type.

> CASE 
            WHEN rep.form like 'F3X%' THEN 'F3X'::text
            WHEN rep.form like 'F5%' THEN 'F5'::text
            WHEN rep.form like 'F24%' THEN 'F24'::text
            ELSE rep.form
        END AS filing_form,
