### ISSUE TITLE
Confirm search parameters are being upper-cased when needed

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4141]
See original issues: #4137 and #4111 

We should look at the fields in `args.py` that are type `fields.Str` and make sure they're being upper-cased where that field in the database is upper-cased.

**Background**
In `args.py`, it looks like the `IStr` class capitalizes parameter values and `fields.Str` does not.
https://github.com/fecgov/openFEC/blob/45d8324a901dcfc85c000a8cde8808289a3f340b/webservices/args.py#L39-L42
`filter_fulltext` uses `to_tsquery()` which doesn’t appear to be case-sensitive (example - `contributor_name`). However, `filter_multi` uses `IN` which appears to be case sensitive (example -`contributor_city`).
If we’re using class `field.Str` (doesn’t `upper()` the input value) in `args.py` for non-TSVECTOR fields, if we aren’t doing the manual upper()  in the resource, I don’t think it will work as expected.

This is a difficult thing to test because there are so many moving parts.

1. How the field is defined in args
2. How it’s being filtered (built-in - filter_fulltext, filter_multi, etc or hand-rolled)
3. What the data looks like 

In the hand-rolled query for `filing_form` in Schedule A for example, the upper() is needed because the arg type is `Str` and not `IStr`

**Ideas**
- [ ] ~We could test out only using `IStr` and see if things still work~ not all the data is upper-cased.

**Comment by lbeaufort** [comment]
Related issue: #4355

**Comment by cnlucas** [comment]
I tested all [/schedules/schedule_a/](https://api.open.fec.gov/developers/#/receipts/get_schedules_schedule_a_) parameters and found the casing to work as expected.
