### ISSUE TITLE
[presidential map] create tables with migration file

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4168]
### Summary
Need:
* PostgreSQL tables to support presidential map:
![image (1)](https://user-images.githubusercontent.com/49287206/73552914-1413cd00-4417-11ea-8932-c79541e91af0.png)
* migration files

### Completion criteria
- [x] all base tables necessary to support presidential map exist
- [x] any migration files needed to migrate tables exist
- [x] initial data load of the base tables

**Comment by fecjjeng** [comment]
Base tables had been created in all databases.
Joseph, Yung, and Rohan had done initial load of these base tables.   
Database team will work on strategy to refresh data on demand (separate issue)
