### ISSUE TITLE
[presidential map] recreate sql logic used for classic

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4169]
### Summary
Need to recreate / use the SQL logic @fec-jli implemented when creating the presidential maps for the classic site.

### Completion criteria
- [ ] SQL logic created

**Comment by lbeaufort** [comment]
From @fec-jli : https://github.com/fecgov/openFEC/issues/4170#issuecomment-580795643

**Comment by patphongs** [comment]
Closing since this is rolled into endpoint work

**Comment by lbeaufort** [comment]
Endpoint tickets:
https://github.com/fecgov/openFEC/issues/4170 #1 Make endpoint for candidate list (presidential/contributions/by_candidate)
https://github.com/fecgov/openFEC/issues/4178 #2 and #5 Make endpoint for coverage dates and summaries (financial_summary, coverage_date) 
https://github.com/fecgov/openFEC/issues/4177  #3 and #4 Make endpoints for aggregates (by_state, by_size)
