### ISSUE TITLE
Upgrade apispec from 0.39 to 1.0.0

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4173]
### Update
This vulnerability was already addressed by @lbeaufort under #4236. Closing as a vulnerability, keeping open as a general upgrade.

This issue has become a high-security vulnerability:
```
  ✗ Arbitrary Code Execution [High Severity][https://snyk.io/vuln/SNYK-PYTHON-PYYAML-559098] in PyYAML@5.3.1
    introduced by apispec@0.39.0 > PyYAML@5.3.1 and 2 other path(s)
  No upgrade or patch available
```

### Summary
several breaking changes exist between apispec 0.39 and 1.0.0. Existing PR from issue #4150 provides a portion of the upgrade (see branch `feature/4079-apispec-upgrade`), however some of the cosmetic appearance of the swagger ui changes because the `basePath` is no longer stripped from paths in `apispec`. 

This issue is to do the actual upgrade (suggest using the work from #4079 up to this point. Original issue to research upgrading was #4079)

### Completion criteria
- [ ] apispec upgraded to 1.0.0

### Technical considerations
- [ ] `flask-apispec` also is upgraded (to 0.8.0)
- [ ] cosmetic differences in swagger ui may be ok in the short term given a long-term upgrade to openapi version 3.0.0 may be in store at some point, and the `basePath` is removed from that version

**Comment by cnlucas** [comment]
This was closed during the Flask upgrade we are now on 4.0.0
