### ISSUE TITLE
Candidate totals for H6MD08549 is inconsistent in /candidates/totals/ and /candidate/{candidate_id}/totals/

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#4214]
This is a follow up ticket of of #4256 and #4182 
After migration file V0179 successfully find cand_election_yr 2018 for H6MD08549 in ofec_candidate_history_mv, a separate issue surfaced related to H6MD08549.
ofec_candidate_totals_mv, which is based on ofec_cand_cmte_linkage_mv to find the association of cand to their the financial cmte,  has two different cand cmte with cmte_dsgn P/A for H6MD08549 in fec_cycle 2018.
One of them should be included in cand_election_yr 2018, one of them is not. Currently there is only one case of this situation exists.  
/candidates/totals/ is now reflect the correct candidate totals for H6MD08549/2018
/candidate/{candidate_id}/totals/, which is feed by another MV.  The data source needs to be updated too to keep the candidate totals in sync for these two endpoints.

/candidate/{candidate_id}/totals/: data source public.ofec_candidate_totals_detail_mv
/candidates/totals/: data source public.ofec_candidate_totals_mv

**Comment by pkfec** [comment]
@fecjjeng Could you please update this ticket?

**Comment by fecjjeng** [comment]
select election_yr_to_be_included, cand_election_yr, fec_election_yr, cmte_id, cmte_tp, * from public.ofec_cand_cmte_linkage_mv  
where cand_id = 'H6MD08549' 
order by fec_election_yr, election_yr_to_be_included

2016	2016	2016	C00607952	H
		2016	2018	C00607952	H
2018	2018	2018	C00653196	H
2020	2020	2020	C00653196	H


select * from disclosure.cand_valid_fec_yr  
where cand_id = 'H6MD08549' 
order by fec_election_yr

338113	H6MD08549	2016	2016
360501	H6MD08549	2018	2016
390058	H6MD08549	2020	2020



select * from ofec_candidate_history_mv
where candidate_id = 'H6MD08549' 
order by two_year_period


select * from ofec_candidate_totals_mv
where candidate_id = 'H6MD08549' 
order by cycle



WITH linkage AS (
        SELECT DISTINCT ofec_cand_cmte_linkage_vw.cand_id,
            ofec_cand_cmte_linkage_vw.fec_election_yr,
            ofec_cand_cmte_linkage_vw.cmte_id,
            ofec_cand_cmte_linkage_vw.cmte_dsgn,           
            ofec_cand_cmte_linkage_vw.election_yr_to_be_included
        FROM ofec_cand_cmte_linkage_vw
        WHERE ofec_cand_cmte_linkage_vw.cmte_dsgn IN ('P', 'A')
        AND ofec_cand_cmte_linkage_vw.fec_election_yr >= 1979
    )
        SELECT ccl.cand_id,
            ccl.fec_election_yr,
           ccl.election_yr_to_be_included
        FROM linkage ccl
            JOIN ofec_committee_totals_per_cycle_vw ct ON ccl.cmte_id = ct.committee_id AND ccl.fec_election_yr = ct.cycle
            LEFT JOIN ofec_agg_coverage_date_vw trans_date ON ccl.cmte_id = trans_date.committee_id AND ccl.fec_election_yr = trans_date.fec_election_yr
        --where ccl.cand_id = 'H6MD08549'
        where ccl.cand_id = 'H0OR02010'

WITH linkage AS (
        SELECT DISTINCT ofec_cand_cmte_linkage_vw.cand_id,
            ofec_cand_cmte_linkage_vw.fec_election_yr,
            ofec_cand_cmte_linkage_vw.cmte_id,
            ofec_cand_cmte_linkage_vw.cmte_dsgn,           
            ofec_cand_cmte_linkage_vw.election_yr_to_be_included
        FROM ofec_cand_cmte_linkage_vw
        WHERE ofec_cand_cmte_linkage_vw.cmte_dsgn IN ('P', 'A')
        AND ofec_cand_cmte_linkage_vw.fec_election_yr >= 1979
    )
        SELECT ccl.cand_id,
            ccl.fec_election_yr,
            count(coalesce (ccl.election_yr_to_be_included, 1))
         FROM linkage ccl
            JOIN ofec_committee_totals_per_cycle_vw ct ON ccl.cmte_id = ct.committee_id AND ccl.fec_election_yr = ct.cycle
            LEFT JOIN ofec_agg_coverage_date_vw trans_date ON ccl.cmte_id = trans_date.committee_id AND ccl.fec_election_yr = trans_date.fec_election_yr
        where ccl.cand_id = 'H6MD08549'
        GROUP BY ccl.cand_id,
            ccl.fec_election_yr

WITH linkage AS (
        SELECT DISTINCT ofec_cand_cmte_linkage_vw.cand_id,
            ofec_cand_cmte_linkage_vw.fec_election_yr,
            ofec_cand_cmte_linkage_vw.cmte_id,
            ofec_cand_cmte_linkage_vw.cmte_dsgn,           
            ofec_cand_cmte_linkage_vw.election_yr_to_be_included
        FROM ofec_cand_cmte_linkage_vw
        WHERE ofec_cand_cmte_linkage_vw.cmte_dsgn IN ('P', 'A')
        AND ofec_cand_cmte_linkage_vw.fec_election_yr >= 1979
    )
        SELECT ccl.cand_id,
            ccl.fec_election_yr,            --coalesce (ccl.election_yr_to_be_included, 1)
            count(distinct ccl.election_yr_to_be_included)
         FROM linkage ccl
            JOIN ofec_committee_totals_per_cycle_vw ct ON ccl.cmte_id = ct.committee_id AND ccl.fec_election_yr = ct.cycle
            LEFT JOIN ofec_agg_coverage_date_vw trans_date ON ccl.cmte_id = trans_date.committee_id AND ccl.fec_election_yr = trans_date.fec_election_yr        --where ccl.cand_id = 'H0OR02010'
        GROUP BY ccl.cand_id,
            ccl.fec_election_yr
            having count(distinct ccl.election_yr_to_be_included)>1
-- 0 rows

WITH linkage AS (
        SELECT DISTINCT ofec_cand_cmte_linkage_vw.cand_id,
            ofec_cand_cmte_linkage_vw.fec_election_yr,
            ofec_cand_cmte_linkage_vw.cmte_id,
            ofec_cand_cmte_linkage_vw.cmte_dsgn,           
            ofec_cand_cmte_linkage_vw.election_yr_to_be_included
        FROM ofec_cand_cmte_linkage_vw
        WHERE ofec_cand_cmte_linkage_vw.cmte_dsgn IN ('P', 'A')
        AND ofec_cand_cmte_linkage_vw.fec_election_yr >= 1979
    )
        SELECT ccl.cand_id,
            ccl.fec_election_yr,
            count(distinct coalesce (ccl.election_yr_to_be_included, 1))
         FROM linkage ccl
            JOIN ofec_committee_totals_per_cycle_vw ct ON ccl.cmte_id = ct.committee_id AND ccl.fec_election_yr = ct.cycle
            LEFT JOIN ofec_agg_coverage_date_vw trans_date ON ccl.cmte_id = trans_date.committee_id AND ccl.fec_election_yr = trans_date.fec_election_yr
        --where ccl.cand_id = 'H6MD08549'
        GROUP BY ccl.cand_id,
            ccl.fec_election_yr
            having count(distinct coalesce (ccl.election_yr_to_be_included, 1))>1
-- 11 rows
/*
H0OR02010	1982	2
H4FL13069	2006	2
H6MD08549	2018	2
H6OH06038	2000	2
H6OH06038	2002	2
P00000489	1988	2
P20001434	1992	2
P80003122	2006	2
S4FL00223	2004	2
S6NE00095	2004	2
S6OR00037	1986	2
*/

select election_yr_to_be_included, cand_election_yr, fec_election_yr, cmte_id, cmte_tp, * from public.ofec_cand_cmte_linkage_mv  
where cand_id = 'S6NE00095'  
and fec_election_yr = 2004
order by fec_election_yr, election_yr_to_be_included

2006	2006	2004	C00306712	S
		2006	2004	C00368209	C




WITH linkage AS (
        SELECT DISTINCT ofec_cand_cmte_linkage_vw.cand_id,
            ofec_cand_cmte_linkage_vw.fec_election_yr,
            ofec_cand_cmte_linkage_vw.cmte_id,
            ofec_cand_cmte_linkage_vw.cmte_dsgn,           
            ofec_cand_cmte_linkage_vw.election_yr_to_be_included
        FROM ofec_cand_cmte_linkage_vw
        WHERE ofec_cand_cmte_linkage_vw.cmte_dsgn IN ('P', 'A')
        --
        and cmte_tp in ('H','P','S')
        --
        AND ofec_cand_cmte_linkage_vw.fec_election_yr >= 1979
    )
        SELECT ccl.cand_id,
            ccl.fec_election_yr,
            count(distinct coalesce (ccl.election_yr_to_be_included, 1))
         FROM linkage ccl
            JOIN ofec_committee_totals_per_cycle_vw ct ON ccl.cmte_id = ct.committee_id AND ccl.fec_election_yr = ct.cycle
            LEFT JOIN ofec_agg_coverage_date_vw trans_date ON ccl.cmte_id = trans_date.committee_id AND ccl.fec_election_yr = trans_date.fec_election_yr
        GROUP BY ccl.cand_id,
            ccl.fec_election_yr
            having count(distinct coalesce (ccl.election_yr_to_be_included, 1))>1

-- 1 row
-- H6MD08549	2018	2

**Comment by pkfec** [comment]
PR #4247 merged. Closing this issue.
