### ISSUE TITLE
[Snyk: HIGH]Arbitrary Code Execution (Due: 04/4/2020)

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4236]
[https://app.snyk.io/vuln/SNYK-PYTHON-PYYAML-559098](https://app.snyk.io/vuln/SNYK-PYTHON-PYYAML-559098)

There is no fixed version for pyyaml.

[https://app.snyk.io/org/fecgov/project/a95ea997-b012-4b3b-a026-2fdbe6ac0398](https://app.snyk.io/org/fecgov/project/a95ea997-b012-4b3b-a026-2fdbe6ac0398)

**Comment by lbeaufort** [comment]
Because we are not processing untrusted YAML files in our usage of `apispec`, `prance`, or ` flask-apispec`, this pyyaml vulnerability isn't applicable to our project. We have other plans to update `apispec` (#3978), so It's ok to close this issue.

**Comment by jason-upchurch** [comment]
@lbeaufort thanks for the head's up on this. I was not aware of this closed issue.
