### ISSUE TITLE
AO 2019-13 and AO 2018-06 missing citations

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/openFEC#4237]
AO 2019-13 included several citations:

- 52 USC 30114(a)(1), 30114(b)
- 11 CFR 113.1(g)(1)(i) and (ii)
-  AO 2018-06 and AO 1995-42

but no citations appear on its page: https://www.fec.gov/data/legal/advisory-opinions/2019-13/
![image](https://user-images.githubusercontent.com/24437369/75919342-5ae84e80-5e2b-11ea-8092-db91eb8fb521.png)

Likewise, the two AOs it cited do not list AO 2019-13 under "This opinion is cited by these later opinions" 
https://www.fec.gov/data/legal/advisory-opinions/2018-06/
https://www.fec.gov/data/legal/advisory-opinions/1995-42/

See similar ticket for another AO at https://github.com/fecgov/openFEC/issues/3669

**Comment by lbeaufort** [comment]
```
SELECT ao_no, max(char_length(ocrtext)) 
 FROM aouser.document 
 INNER JOIN aouser.ao USING (ao_id) 
 WHERE category = 'Final Opinion' 
 group by ao_no 
 having max(char_length(ocrtext)) < 100 
 order by ao_no desc                                                                                                      
+---------+-------+
| ao_no   | max   |
|---------+-------|
| 2019-14 | 1     |
| 2019-13 | 1     |
| 2019-11 | 1     |
| 2019-10 | 1     |
| 2019-06 | 1     |
| 2018-15 | 1     |
+---------+-------+
```


https://www.fec.gov/data/legal/advisory-opinions/2019-14/
https://www.fec.gov/data/legal/advisory-opinions/2019-13/
https://www.fec.gov/data/legal/advisory-opinions/2019-11/
https://www.fec.gov/data/legal/advisory-opinions/2019-10/
https://www.fec.gov/data/legal/advisory-opinions/2019-06/
https://www.fec.gov/data/legal/advisory-opinions/2018-15/

**Comment by lbeaufort** [comment]
I emailed Salient and will update this issue after I hear back. AOs will need to be reloaded from the beginning once these OCR fields are populated.

`cf run-task api "python manage.py refresh_current_legal_docs_zero_downtime" -m 4G --name refresh-legal-<today>`

**Comment by lbeaufort** [comment]
@dorothyyeager thanks for reporting this issue. The AOs below have been updated, if you'd like to take another look. 

https://www.fec.gov/data/legal/advisory-opinions/2019-14/
https://www.fec.gov/data/legal/advisory-opinions/2019-13/
https://www.fec.gov/data/legal/advisory-opinions/2019-11/
https://www.fec.gov/data/legal/advisory-opinions/2019-10/
https://www.fec.gov/data/legal/advisory-opinions/2019-06/
https://www.fec.gov/data/legal/advisory-opinions/2018-15/

**Comment by dorothyyeager** [comment]
Hi @lbeaufort and thanks! Here's what I caught for each AO. 

**AO 2019-14** - Missing some regulations: 
11 CFR 102.1
11 CFR 102.6
11 CFR 104.1
11 CFR 300.10

**AO 2019-13** - Perfect, got it all.

**AO 2019-11** - One missing regulation to add: 11 CFR 110.11.

Also in this AO, there's a cite to ALL of the statutes at the beginning of AO and I think that got done on here as 52 U.S.C. §301. I would just delete that.  I noticed it referenced a 2019 AO, so I checked and this AO did get cited on the older AOs page, so that's good.

**AO 2019-10** - Missing statute cite:
 52 U.S.C. 30106 and 30107 (This is an AOR that didn't become an AO so not sure we need this.)

AO 2019-06 - Missing statute cites 52 U.S.C. 30106 and 30107
(This is an AOR that didn't become an AO so not sure we need this.)

**AO 2018-15** - Cite to 52 U.S.C. 30101 can be deleted for same reason as AO 2019-11. Missing regulations:
 11 CFR 112.1
11 CFR 112.5
11 CFR 113.1
11 CFR 113.2

**Comment by lbeaufort** [comment]
@dorothyyeager thanks for catching those! They'll need to be addressed separately - for reference here's the work to manually add citations https://github.com/fecgov/openFEC/issues/3461

**Comment by lbeaufort** [comment]
@dorothyyeager one thing I notice about these PDFs is they're not text highlightable - do you know how the PDFs get uploaded? Is that a 508 compliance issue?

**Comment by JonellaCulmer** [comment]
Closing in favor of followup ticket #4333
