### ISSUE TITLE
replace cf environment variable values for FEC_EMAIL_RECIPIENTS

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4238]
### Summary
for `cf env api` the `"FEC_EMAIL_RECIPIENTS"` environment variable values are obsolete. These need to be updated with current employees.

Resolves issue https://github.com/fecgov/openFEC/issues/3815

**Completion criteria:**
- [x] Need to check that we're still referencing this
- [x] If not being used, we need to remove. Refer to https://github.com/fecgov/fec-cms/issues/1812

**Comment by pkfec** [comment]
Found an OLD issue to remove the FEC_EMAIL_RECIPIENTS env variable not used in prod environment https://github.com/fecgov/fec-cms/issues/1812

**Comment by pkfec** [comment]
In the past, FEC_EMAIL_RECIPIENTS  env variable was used  to notify only few team members about the nightly jobs status. However this variable is no longer in use in production after enabling the slack alerts. see # https://github.com/fecgov/openFEC/pull/2955/files#diff-04c6e90faac2675aa89e2176d2eec7d8L524

**Comment by pkfec** [comment]
Came across MANDRILL_API_KEY env variable in `dev`, `stage` and `prod` environments which is not used in cms, api, eregs apps. 
- `Mandrill is an email infrastructure service designed to help applications or websites that need to send transactional email like password resets, order confirmations, and welcome messages.`
- We use slack for as your application alerts monitoring service.` 

I have removed this env from `dev` space and rerun the latest `develop` circle build which gets deployed to `dev` space. I will continue to test the `dev` website and API to see if there are any issues in the logs after removing `MANDRILL_API_KEY` env variable.

**Comment by pkfec** [comment]
Removed FEC_EMAIL_RECIPIENTS & FEC_EMAIL_SENDER from Prod space. Redeployed the API app via circleci. Due to the ongoing Aurora migration, the Writes to postgres db were disable in prod and the recent master build failed for the same reason. 
Circle API master build:
https://app.circleci.com/pipelines/github/fecgov/openFEC/125/workflows/6644ab91-7443-4e33-ada6-a5e104fe47d7/jobs/2456

I will redeploy the API app on Monday (05/04/2020), after the Aurora migration.

**Comment by pkfec** [comment]
API app was deployed to Prod Saturday (05/02/2020) after the DB migration. Here is the circleci build:
https://app.circleci.com/pipelines/github/fecgov/openFEC/125/workflows/b827fcb2-1a8f-40f5-a665-cb232d5460dc/jobs/2458

No further action is required. Closing this issue.
