### ISSUE TITLE
Remove two endpoints: /committee/{committee_id}/electioneering/by_candidate/ and /committee/{committee_id}/communication_costs/by_candidate/ 

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4248]
**What we're after:**
These two endpoints are not currently functioning. Based on that, and that we have few users of this endpoint we're opting for a truncated deprecation and will forego some of the normal steps to completion, including the waiting period before removal.

We have created the below two endpoints with correct filters(commttee_id, cycle..) and has been used by front-end.
/communication_costs/aggregates/?committee_id={committee_id}
/electioneering/aggregates/?committee_id={committee_id

In PR: [https://github.com/fecgov/openFEC/pull/4098](https://github.com/fecgov/openFEC/pull/4098)
[https://github.com/fecgov/openFEC/pull/4246](https://github.com/fecgov/openFEC/pull/4246)

So we should think of remove or deprecate these two 'not work' endpoints:
/committee/{committee_id}/communication_costs/by_candidate/
/committee/{committee_id}/electioneering/by_candidate/

Action items:
- [x] notify api users that it's going away - don't wait 30 days before proceeding with deprecation
- [x] make sure front-end isn't using the broken endpoints
- [x] remove two endpoints

Completion criteria:
- [x] Endpoints are removed

**Comment by lbeaufort** [comment]
API users for `/committee/{committee_id}/communication_costs/by_candidate/`: [none](https://api.data.gov/admin/#/stats/logs?query=%7B%22condition%22%3A%22AND%22%2C%22rules%22%3A%5B%7B%22id%22%3A%22gatekeeper_denied_code%22%2C%22field%22%3A%22gatekeeper_denied_code%22%2C%22type%22%3A%22string%22%2C%22input%22%3A%22select%22%2C%22operator%22%3A%22is_null%22%2C%22value%22%3Anull%7D%2C%7B%22id%22%3A%22request_path%22%2C%22field%22%3A%22request_path%22%2C%22type%22%3A%22string%22%2C%22input%22%3A%22text%22%2C%22operator%22%3A%22contains%22%2C%22value%22%3A%22communication_costs%2Fby_candidate%22%7D%2C%7B%22id%22%3A%22request_path%22%2C%22field%22%3A%22request_path%22%2C%22type%22%3A%22string%22%2C%22input%22%3A%22text%22%2C%22operator%22%3A%22contains%22%2C%22value%22%3A%22committee%22%7D%2C%7B%22id%22%3A%22user_email%22%2C%22field%22%3A%22user_email%22%2C%22type%22%3A%22string%22%2C%22input%22%3A%22text%22%2C%22operator%22%3A%22not_contains%22%2C%22value%22%3A%22webapp%22%7D%5D%2C%22valid%22%3Atrue%7D)

API users for `/committee/{committee_id}/electioneering/by_candidate/`: [none](https://api.data.gov/admin/#/stats/logs?query=%7B%22condition%22%3A%22AND%22%2C%22rules%22%3A%5B%7B%22id%22%3A%22gatekeeper_denied_code%22%2C%22field%22%3A%22gatekeeper_denied_code%22%2C%22type%22%3A%22string%22%2C%22input%22%3A%22select%22%2C%22operator%22%3A%22is_null%22%2C%22value%22%3Anull%7D%2C%7B%22id%22%3A%22request_path%22%2C%22field%22%3A%22request_path%22%2C%22type%22%3A%22string%22%2C%22input%22%3A%22text%22%2C%22operator%22%3A%22contains%22%2C%22value%22%3A%22electioneering%2Fby_candidate%22%7D%2C%7B%22id%22%3A%22request_path%22%2C%22field%22%3A%22request_path%22%2C%22type%22%3A%22string%22%2C%22input%22%3A%22text%22%2C%22operator%22%3A%22contains%22%2C%22value%22%3A%22committee%22%7D%2C%7B%22id%22%3A%22user_email%22%2C%22field%22%3A%22user_email%22%2C%22type%22%3A%22string%22%2C%22input%22%3A%22text%22%2C%22operator%22%3A%22not_contains%22%2C%22value%22%3A%22webapp%22%7D%5D%2C%22valid%22%3Atrue%7D)
