### ISSUE TITLE
[Snyk: Medium] Prototype Pollution (Due: 05/19/2020)

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4253]
[Snyk: Medium] Prototype Pollution  (Due: 05/19/2020)

[https://app.snyk.io/org/fecgov/project/d0baf872-87d8-4d68-80a5-cb52a6d0f57b](https://app.snyk.io/org/fecgov/project/d0baf872-87d8-4d68-80a5-cb52a6d0f57b)

- [ ] Remediation: Upgrade minimist to version 0.2.1, 1.2.3 or higher.

**Comment by patphongs** [comment]
@fec-jli This no longer appears to show up as a vulnerability in openFEC, was it remediated?

**Comment by lbeaufort** [comment]
Closing because it's no longer being flagged by Snyk
