### ISSUE TITLE
Add active/terminated status to /names/committees/

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4270]
**What we're after:**
As part of our work to include a status indicator  for all committees, we want to also add status to the global search, so users can see the status at a quick glance. When using the autosuggest for committee lookup, users want to quickly get results and be able to distinguish between active and terminated committees.

Here speed matters most, more than having api-user friendly data. /names/candidates/ is designed for the auto-suggest and doesn't provide any other data currently, so it's ok to make the abstraction from filing frequency to `is_active` true/false in the name of performance.

### Related issues
- https://github.com/fecgov/fec-cms/issues/3325 Design solution for active vs terminated committee status
- https://github.com/fecgov/fec-cms/issues/3642 Implement committee status on committee profile pages

### Completion criteria
- [ ] Add `is_active` to /names/committees/ endpoint

Helpful chart:

is_active	|	filing_frequency	|	filing frequency description
----	|	----	|	----
True	|	Q	|	Quarterly filer
True	|	M	|	Monthly filer
False	|	T	|	Terminated
False	|	A	|	Administratively terminated
 
- [ ] Double-check that this doesn't slow down the search performance

### Tech steps or considerations (optional)

This comment from the design issue: https://github.com/fecgov/fec-cms/issues/3325#issuecomment-603393785

Update `ofec_committee_fulltext_mv` to have `is_active` based on `filing_frequency` and bring those changes forward to the model/endpoint.

### Design
<img width="308" alt="Screen Shot 2020-03-11 at 9 36 43 AM" src="https://user-images.githubusercontent.com/31663028/76427223-6afbb300-6382-11ea-9696-e4f1f474c88e.png">

**Comment by hcaofec** [comment]
PR is merged, so closing.
