### ISSUE TITLE
Hook up testing data loading with CircleCI

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4288]
### Summary

After initial setup of the new Aurora database, applications that currently used to load the postgresql database need to be tested to make sure data loading/synchronization between source databases and the new Aurora database will still functioning.  This ticket involved setting up Bastion host and hook up to the new Aurora host.  

### Related issues
- #4286  
- #4287  
- #4289 
- #4290 
- #4291 

### Completion criteria

- [x] update CircleCI environment variables that related to bastion host to connect to the new Aurora database instance
- [x] Execute CircleCI build pointing to the new Aurora database instance successfully

### Future work
- #4288 
- #4289 
- #4290 
- #4291

**Comment by fecjjeng** [comment]
The circleCI going through Bastion host to connect to database to run the migration files for security reason.  We initially thought we need to modification our Bastion host environment to point to the new dev-aurora database.  After carefully review the code by Rohan, who had originally setup the Bastion host with Jun.  We realized that there is no need to modify our Bastion host.  But need to update several circleCI environmental variables to make the Bastion host to point to the new dev-aurora database.

**Comment by fecjjeng** [comment]
- After update the circleCI environment variables, we had run rebuild in circleCI of the last successful build in DEV, which had up to migration file V0192.  It went through without connection error and verify the database is up-to-date, no need for flyway migration.  
- We later merged in another PR with migration file V0193, to the dev-aurora database.  It finished successfully and the updates to the database appears in the dev-aurora database.
