### ISSUE TITLE
Perform data query test (API, data export, PGBadger)

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4289]
### Summary
After initial setup of the new Aurora database, and applications that currently used to load the postgresql database had been tested(modification made if needed) to be able tio loading/synchronization between source databases and the new Aurora database, data query test need to be performed to test if any API functionality are still functioning.

### Related issues
#4286
#4287 
#4288 
#4290
#4291
#4298

### Completion criteria
- [x] Swagger API Test on developer's local server
- [x] Data Export
- [x] AWS RDS DAILY LOG download and PGBadger run 

### Future work
#4290
#4291
#4298

**Comment by fecjjeng** [comment]
Swagger API Test on developer's local server
 Swagger API Test by hooking up to STAGE API
 Data Export
 AWS RDS DAILY LOG download and PGBadger run
