### ISSUE TITLE
Perform locust load testing

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4290]
### Summary

Locust load testing will be perform against the current stage-replica postgresql database (as a baseline) and the new Aurora database readers.  Comparison will be made to test the capability of the Aurora database to handle load conditiob.

### Related issues

#4287
#4288
#4289
#4290
#4291

### Completion criteria

Using the same API (stage), but point to the current stage replica and the new Aurora readers, respectively, perform the same locust stress test.

- [x] Using stage API, point to the current stage replica database perform locust stress test.
- [x] Using stageAPI, point to the new Aurora readers, respectively, perform locust stress test.
- [x] Compare results

**Comment by dzhang-fec** [comment]
waiting reviews. The locust test result is here for your and Laura review. https://docs.google.com/spreadsheets/d/1bRW9y1C7XOYPInLu2p_dez6cKdlMsfA3TzZEkQF497Y

**Comment by JonellaCulmer** [comment]
@lbeaufort Can you take a look at the results? ^^

**Comment by lbeaufort** [comment]
@dzhang-fec and @rjayasekera these are excellent results! Thanks for presenting them clearly and summarizing results. I don't see any reason not to move forward.

**Comment by dzhang-fec** [comment]
This is a team work. Thanks a lot for the teams, esp., @rjayasekera @fec-jli  @fecjjeng @hcaofec appreciate it.
