### ISSUE TITLE
Initial performance tuning

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4291]
try out different tuning parameters other than the default parameter group)

### Summary

**What we're after:**
_Briefly describe the goal or user story for this issue. Be sure to include any dependencies._

### Related issues
#4287
#4288
#4289
#4290
#4291

### Tech steps or considerations (optional)

_List any considerations the tech team should know. Additionally, any specific tech steps can be included here._

- [x] Create a separate parameter group to experiment on different parameter without affect the default parameter group
- [x]  Modify and try out different parameter for initial tuning.

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by dzhang-fec** [comment]
![image](https://user-images.githubusercontent.com/62447258/79480208-d1a46a00-7fdb-11ea-9663-09f7ac3636cb.png)

**Comment by dzhang-fec** [comment]
There are two parameters.
Please see the change above on the parameters, mainly to use more memory based on Aurora architecture. It has been tested in master and replicas by loading test.
Thee is no change on the cluster parameter.
