### ISSUE TITLE
Candidate profile page doesn't show financial summary (Easy implementation)

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#4292]
After this candidate changed his primary committee to PAC ( committee type changes from P to N ),  his candidate profile page doesn't show financial summary any more.  The candidate profile page is designed to include committees with type 'P' and  'A' only.
https://www.fec.gov/data/candidate/P00010298/

The other way to obtain the financial summary is to go to PAC profile page.
https://www.fec.gov/data/committee/C00697441/

**Technical considerations:**
Easy: Fix Pete and high-level 2020 candidates on candidate profile pages and determine what that means, open followup ticket for usability testing
Medium: programmatically identify all candidates where this issue exists, add the mid-cycle conversion logic to the API
Large: Make our data more granular to account for these kinds of changes across all candidates/committees

**Completion criteria:**
- [x] Implement easy solution documented above 
- [x] As necessary, create followup tickets

**Comment by PaulClark2** [comment]
@hcaofec thanks. Is there a way we can show the financial activity on the candidate profile page.  The message, "We don't have BUTTIGIEG, PETE for 2019–2020." is incorrect. Buttigieg raised $99 million and spent $89 million as a candidate.

**Comment by hcaofec** [comment]
A couple possible workarounds:
1)  Put text there to state the primary committee has been changed to PAC, and provide a link to committee profile page which has financial summary.

2)  Have a separate table to keep log of the candidates ,  and add this table to the mv that provides financial summary on candidate profile page.   The drawback is the separate table will be manually maintained.  

any other thoughts?  
@lbeaufort @fecjjeng @fec-jli

**Comment by PaulClark2** [comment]
Thanks @hcaofec .  Do @lbeaufort @fec-jli or @fecjjeng  having any suggestions?

**Comment by lbeaufort** [comment]
This is a fundamental design issue - Buttigieg is also missing from the election profile pages and raising by the numbers pages.

I think one of the issues with candidate-driven data is that this candidate is no longer a candidate in the way we've typically categorized them in that there is no active P/A candidate committee.

**Comment by lbeaufort** [comment]
I think this a complete inventory of where the candidate is missing financials:

- Candidate profile page - no financial data https://www.fec.gov/data/candidate/P00010298/
- Candidate totals - 0's  https://www.fec.gov/data/candidates/president/?q=P00010298&election_year=2020&cycle=2020&election_full=true
- Where contributions come from - missing data https://www.fec.gov/data/raising-bythenumbers/
- Raising barchart - 0's (same data source as candidate totals) https://www.fec.gov/data/raising-bythenumbers/
- Election profile page - missing https://www.fec.gov/data/elections/president/2020/ (page through or use API call https://api.open.fec.gov/v1/elections/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&sort=-total_receipts&per_page=800&page=1&cycle=2020&election_full=true&duration=4&office=president)

**Comment by lbeaufort** [comment]
Noting here but it might be unrelated - there's a 2017-2018 button that 404's on the candidate profile page

https://www.fec.gov/data/candidate/P00010298/?tab=summary
http://fec.gov/data/candidate/P00010298/?tab=summary&cycle=2018&election_full=false (404)

**Comment by lbeaufort** [comment]
Research from Jaime in RAD: 

** Examples of candidates converting mid-cycle **
- Julian Castro's presidential candidate committee (ID C00693044) also already converted to a PAC. 
- Here's some examples of other House candidate committees that converted to a PAC this cycle: C00634212, C00652594, C00691790.  historical candidates that converted their PCC or authorized committees to PACs after the cycle was over?

**Examples of candidates converting post-cycle**
-Rand Paul's presidential committee (C00575449) converted to a PAC in 2017 after he ran in the 2016 cycle. 
- Scott Brown's PCC (C00560003) converted to a PAC in 2015 after he last ran in the 2014 cycle.

The committees that converted after the election cycle show the affiliated candidate when you choose the two-year period where they were affiliated. 

Complications on calculating totals for mid-cycle conversion - our linkage and cycle totals are done on a two-year timeframe. After conversion, PAC totals shouldn't show on the corresponding candidate profile pages. We'd need to re-thing some fundamental assumptions about totals and linkage to make this work.

I think the ideal behavior would be to have a cutoff date for the candidate profile pages:
PAC (former candidate committee): show full-cycle totals
Candidate profile page: show totals for reports filed through the cutoff date

**Comment by lbeaufort** [comment]
Ideally we could identify these issues programmatically, but if we can't or that takes a lot of effort, one workaround could be the CMS having a hard-coded list of candidate ID's that show explanatory text on their candidate profile pages.
cc: @JonellaCulmer @AmyKort @patphongs

**Comment by PaulClark2** [comment]
Related https://github.com/fecgov/FEC/issues/9709

**Comment by JonellaCulmer** [comment]
In looking at the other data visualizations we're not showing Pete Buttigieg and his figures are no longer accounted for, particularly in the party totals visualization. 

He's on the presidential map, but not on the charts in Raising: by the numbers.
https://www.fec.gov/data/raising-bythenumbers/

**Comment by patphongs** [comment]
The easy implementation has been completed. A new ticket has been opened for the more automated API approach: https://github.com/fecgov/openFEC/issues/4419
