### ISSUE TITLE
(openFEC db migration) Add is_active column into ofec_committee_fulltext_mv

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4296]
**What we're after:**
To ensure that committee status is added to the front-end we need to add it to the materialized view first. Specifically, the is_active column to the ofec_committee_fulltext_mv.

### Completion criteria

- [x] is_active column added to the ofec_committee_detail_mv
- [x] is_active column added to the ofec_committee_fulltext_mv
- [x]  Spotcheck against the four different filing frequencies.

**Comment by hcaofec** [comment]
Becaue ofec_committee_fulltext_mv is built on ofec_committee_detail_mv, is_active column will be added to ofec_committee_detail_mv as well.

**Comment by hcaofec** [comment]
PR is merged, so closing.
