### ISSUE TITLE
Develop team to use the aurora database as the dev database to fully test API/database

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4298]
### Summary

After initial tests had been successfully performed by database team on the data loading (#4287), this work will serve dual purposes: help testing API and also make sure all data loading process works without issues.  
After initial tests had been successfully performed by database team on the API (#4289), the DEV environment will point to the dev-aurora database to do a more through tests on the API/database interaction before the final switch from the current 9.6 postgres database to the verison 10.7 aurora database.

### Related issues

_List any relevant related issue(s)_

#4289
#4297

### Completion criteria
- [x] Ensure the data refresh jobs running without issues
- [x] point DEV API to use the dev-aurora database
- [x] Celery worker jobs regarding databases such as MV refresh, ao refresh executed successfully
- [x] No unusual pingdom alerts on DEV space
- [x] No unusual database related problem on API development work on dev-aurora database

**Comment by fecjjeng** [comment]
Update DEV API to use the dev-aurora database for on 4/17 for developers to use it as the DEV database
Data refresh jobs (Java, GG, Salient's legal and real file) running without issues
Celery worker jobs regarding databases such as MV refresh, successfully
No unusual pingdom alerts on DEV space
No unusual database related problem on API development work on dev-aurora database

**Comment by fecjjeng** [comment]
Migration to aurora on all three environment performed successfully (#4297)
practice dev-aurora database and its replica droped.
