### ISSUE TITLE
define acceptable use policy for API keys

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4305]
### Summary
We need to define and acceptable use policy that explicitly states the terms of use for FEC API keys.

### Completion criteria
- [x] use postmortem discussion from document as a starting point
- [x] hold meeting to discuss ideas/pros/cons for elements of AUP
- [x] document AUP internally/externally
- [ ] open any issues needed for implementing/enforcing AUP

**Comment by PaulClark2** [comment]
Some examples (we should try to find others)

Government AUPs

https://developer.vic.gov.au/acceptable-use
https://developer.nhs.uk/apis/dos-api/acceptable_usage_policy.html
https://digital.nhs.uk/services/directory-of-services-dos/api-acceptable-use-policy

Private sector AUPs

https://docs.developer.amazonservices.com/en_US/dev_guide/DG_AcceptableUsePolicy.html
https://developers.google.com/photos/library/guides/acceptable-use
https://gsuite.google.com/terms/use_policy.html

**Comment by jason-upchurch** [comment]
Government "Terms of Service"
https://www.eia.gov/opendata/register.php#terms_of_service
https://www.census.gov/data/developers/about/terms-of-service.html
https://www.weather.gov/disclaimer
https://regulationsgov.github.io/developers/ (one key per organization)

**Comment by PaulClark2** [comment]
From my research, terms of service tend to be more general and acceptable use policies are more specific lists of acceptable and unacceptable ways to use a service. 

:lock: [draft terms of service](https://docs.google.com/document/d/1c9MlVSFtTWzCQuoRPam8XXHEOz44AJh8MSI6kPPY_Vo/edit#heading=h.ktx5tu5kq5y3) :lock:

:lock: [draft acceptable use policy](https://docs.google.com/document/d/1eYQ45aJhw3RoHgBb_wQUZGcXeI63MrhBUd1QoItH-Lc/edit#heading=h.qdlymdqjqhvz) :lock:

cc: @AmyKort @patphongs @lbeaufort

**Comment by patphongs** [comment]
Thank you @PaulClark2, these policies are looking really good! I've reviewed and added a few comments

**Comment by PaulClark2** [comment]
OGC has reviewed the terms of service agreement. I'm waiting for them to complete their review of the AUP. We'll publish the TOS and AUP at the same time.

**Comment by PaulClark2** [comment]
OGC didn't have any edits to the AUP. We are ready to publish.

**Comment by JonellaCulmer** [comment]
Followup work here: fec-cms #3867
