### ISSUE TITLE
Make API Key signup page (vanilla prototype)

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4323]
### Summary
From https://github.com/fecgov/fec-accounts/issues/254, we would like to make our own API key signup page. This ticket is to create a bare bones (vanilla) prototype for a simple signup. Additional functional requirements can be met with additional tickets in iterative fashion.

### Completion criteria
- [x] a working API key signup page linked through the swagger-ui

**Comment by jason-upchurch** [comment]
>https://api.data.gov/docs/agency-manual/#embedding-the-api-key-signup-form-on-your-own-documentation-site

**Comment by jason-upchurch** [comment]
working on storing apiKey var as an envar and accessing through `swagger-ui.html`

**Comment by JonellaCulmer** [comment]
@jason-upchurch @johnnyporkchops Please let me know if there's anything I need to look at as part of this work.

**Comment by jason-upchurch** [comment]
@JonellaCulmer there will  definitely be a layout component we'd like your input on. Right now, the emphasis is on correct behavior, but we'll definitely ask for your help (either in reviewing this  vanilla  version or the full-fledged one  to  eventually follow). In the meantime, we're kind of going for something along the lines of  the types  of pages  implemented here:  https://api.data.gov/ if you want to look at those and get a sense of anything you  think  we could/should do differently?
cc @johnnyporkchops

**Comment by JonellaCulmer** [comment]
@jason-upchurch Am I correct in that the API key signup at the top of the page you referenced is for all of the APIs listed below it? If so, are you aware of which government APIs use their own sign up page? At this point are you planning to replicate the form they're using here at https://api.data.gov/signup/? 

<img width="1038" alt="Screen Shot 2020-05-13 at 10 06 20 AM" src="https://user-images.githubusercontent.com/31663028/81822778-88bfd280-9501-11ea-842d-9b1f578a9b77.png">

**Comment by jason-upchurch** [comment]
@JonellaCulmer yes, if you click those links in the actual boxes I believe you should see a variety of signup pages, some of which are embedded in the agency sites as we are working on. These may be good references for you to see how others are doing it. You'll know it's from that agency because the agency name will be in the URL. NASA is  one that immediately comes to mind. EOP is another, I think.

**Comment by JonellaCulmer** [comment]
Thanks for those examples @jason-upchurch Some of those forms are difficult to find. Something to keep in mind.

https://petitions.whitehouse.gov/developers/apply
https://api.data.gov/signup/
https://api.nasa.gov/

**Comment by johnnyporkchops** [comment]
@jason-upchurch , Some in the list use Swagger for their docs, but I have yet to find one that has an open source GH repo for them, like we do.

**Comment by patphongs** [comment]
The prototype has been developed and completed. Closing this issue and we'll move on to this issue for the next iteration: https://github.com/fecgov/openFEC/issues/4363
