### ISSUE TITLE
Update system diagram with CDN

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4326]
@patphongs and I have some questions about how CDN and routing currently work. 

**Completion criteria:**
- [x] Double-check with cloud.gov (confirmed data flow is CDN > ALB > cloud.gov router. More docs: 
> Feel free to review the network diagrams for the platform at the bottom of this page: https://cloud.gov/docs/compliance/diagrams/
>The CF Docs on general Cloud Foundry routing.  From the cloud.gov standpoint just follow along the HTTP traffic flow as we don't offer TCP Routing services:
https://docs.cloudfoundry.org/concepts/cf-routing-architecture.html
- [x] Update the system diagram in the wiki 🔒 https://docs.google.com/drawings/d/13LtMZMlOyZlBurFLQZL8s2IyCN66kgu59c6FnC3Igto/edit 🔒 
- [x] We should document how the CDN routing currently works

**Comment by patphongs** [comment]
Initial [diagram](https://app.diagrams.net/#G1TVaQjCjPeKZIziYB5npM9OdDOaXyvsYo) 🔒 on DNS routing and CDN

**Comment by patphongs** [comment]
@lbeaufort I've updated the diagram with how I think the CDN fits into the system architecture: [diagram](https://docs.google.com/drawings/d/1CqPKBuH2rpZ1-EIvXoe_GEkWHir_VtCIaxMaDpYYLZM/edit) 🔒

**Comment by lbeaufort** [comment]
@pat thank you! We should update the system diagram (https://github.com/fecgov/FEC/wiki/2.-FEC-system-diagram) with the non-ATO border image.

**Comment by lbeaufort** [comment]
Here's the [doc without ATO border](https://docs.google.com/drawings/d/13LtMZMlOyZlBurFLQZL8s2IyCN66kgu59c6FnC3Igto/edit), but I had some questions about ALB and cloud.gov router. I believe the cloud.gov router routes traffic to an app, ALB balances that traffic between instances. We're going to check with cloud.gov in our next checkin, June 1.

![Screen Shot 2020-05-20 at 3.50.24 PM.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/2556a899-23a5-4a16-9809-44d63bca7e6c)

**Comment by lbeaufort** [comment]
Paired with @JonellaCulmer, now updated here: https://github.com/fecgov/FEC/wiki/2.-FEC-system-diagram
