### ISSUE TITLE
Keep one postgresql database (prod) in sync in parallel then drop all the old postgres databases

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4328]
This is a Tear down ticket after the migration. 

This work is dependent on how the migration goes in 12.2. This ticket may be closed depending on how the migration shakes out.

**Completion criteria:**
- [x] Keep one postgresql database live in case we need to roll back after the Aurora migration in 12.2. #4297 
- [x] Remove all data input tasks (also need to inform Salient) point to the posgresql databases prior to drop the master postgresql databases.
- [x] Drop master DEV/STG/PRD postgres databases two Sprints after migration to Aurora database without problem observed.

**Comment by fecjjeng** [comment]
The backend databases had been migrate to Aurora (#4297).  STG/PRD postgres master databases will be dropped one Sprint after migration to Aurora database without problem observed.  We will keep DEV postgres database to support the DR work until it is done.

**Comment by fecjjeng** [comment]
DR work will not apply to the old postgres database anymore.  Therefore the DEV postgres database will be dropped along with STG and PRD.

**Comment by fecjjeng** [comment]
- Data input task had been continued to feed to production postgres database for 2 Sprints.  Aurora databases had been operated with no issue for 2 Sprints.  The old postgres databases are not required and ready to be deleted.

**Comment by fecjjeng** [comment]
- Salient had been informed to stop real_file and legal data input
- Java transfer and Golden Gate input tasks to feed posgresql databases had been stopped.

**Comment by fecjjeng** [comment]
DEV/STG/PRD postgres databases had been dropped through Infrastructure PR 
https://github.com/fecgov/fec-infrastructure/pull/114
https://github.com/fecgov/fec-infrastructure/pull/115

**Comment by fecjjeng** [comment]
All tasks completed.
Closed this ticket.
