### ISSUE TITLE
Document and hold training on how to identify slowest queries in realtime (and historical) in Aurora

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4330]
**User Story:**
As a production monitor, it makes it easier for me to identify performance issues if I can see the slowest running queries in the database in realtime.

We can see historical (previous day and before) slow queries in the database using PGBadger, but in Aurora we're not sure how to see the slowest running queries in realtime. 

Database team will conduct a training to show interested parties on how to do this.

I think @rjayasekera has a support ticket in for this. This is a topic was takeaway from the metrics meeting.

**Completion criteria:**
- [ ]  Document how to do this realtime investigation into slow queries
- [ ] Hold training with team on how to do historical and realtime analysis. Share documentation with team.

**Comment by dzhang-fec** [comment]
[HowToFindSlowSqlInAurora.pptx](https://github.com/fecgov/openFEC/files/4717802/HowToFindSlowSqlInAurora.pptx)

Please review the attached Presentation with demo and samples.

**Comment by dzhang-fec** [comment]
Please review the attached Presentation with demo and samples.
[image](https://user-images.githubusercontent.com/62447258/83656416-834c2a00-a58d-11ea-94ce-e7c11e0c812b.png)

[HowToFindSlowSqlInAurora.pptx](https://github.com/fecgov/openFEC/files/4724409/HowToFindSlowSqlInAurora.pptx)

**Comment by dzhang-fec** [comment]
I have created PPT ^ and  ready to show demo per @Jonella yesterday. Whenever is good to the teams. Thanks

**Comment by dzhang-fec** [comment]
done yesterday and did followup per request at the #dev. close. thanks for @JonellaCulmer 's help.
