### ISSUE TITLE
Update README, team postgres version to 10.7

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4332]
**What we're after:**
When we moved to aurora our documentation became out of date. We should get the documentation and get updated versions for the team. 

Related tickets: 
- https://github.com/fecgov/fec-cms/issues/3757
- https://github.com/fecgov/fec-eregs/issues/499

**Completion criteria:**
- [x] Update README, team postgres version to 10.7
- [x] Double check the drivers
- [x] Remind the team to update their versions
- [ ] Open any followup tickets as necessary

**Comment by hcaofec** [comment]
1) The description in README has been updated
2) Current PG drivers works fine
3) PG 10.13 has been installed on local computer, and works fine.  Here are the steps:
` brew services stop postgresql@9.6 `
` brew uninstall postgresql@9.6. `
` brew install postgresql@10`
    ---(update PATH in .bash_profile)---
 `brew services start postgresql@10`
4) It is recommend to create a new virtual environment
5) To test new database
    re-create cfdm_test, and run `invoke create_sample_db`
    run `pytest`
    psql cfdm_test

To check PG version:
    which postgres 
    psql --version (show: 10.13)

**Comment by hcaofec** [comment]
This [/.circleci/config.yml](https://github.com/fecgov/openFEC/blob/develop/.circleci/config.yml#L11) still has old version of Python and PG.  
Follow-up ticket is created for further action if necessary.
[#4425](https://github.com/fecgov/openFEC/issues/4425)
