### ISSUE TITLE
Manually add missing citations to five AOs

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4333]
**What we're after:** We need to manually add missing citations: (Here's how: #3461)

**Related work:**
- https://github.com/fecgov/openFEC/issues/4237 AO 2019-13 and AO 2018-06 missing citations

### AO's missing citations that need to be manually added:

**AO 2019-14** - Missing some regulations: 
11 CFR 102.1
11 CFR 102.6
11 CFR 104.1
11 CFR 300.10

**AO 2019-11** - One missing regulation to add: 11 CFR 110.11.

Also in this AO, there's a cite to ALL of the statutes at the beginning of AO and I think that got done on here as 52 U.S.C. §301. I would just delete that.  I noticed it referenced a 2019 AO, so I checked and this AO did get cited on the older AOs page, so that's good.

**AO 2019-10** - Missing statute cite:
 52 U.S.C. 30106 and 30107 (This is an AOR that didn't become an AO so not sure we need this.)

AO 2019-06 - Missing statute cites 52 U.S.C. 30106 and 30107
(This is an AOR that didn't become an AO so not sure we need this.)

**AO 2018-15** - Cite to 52 U.S.C. 30101 can be deleted for same reason as AO 2019-11. Missing regulations:
 11 CFR 112.1
11 CFR 112.5
11 CFR 113.1
11 CFR 113.2

**Completion criteria:** 
- [ ] All missing citations or regulations are added to the applicable AOs

**Comment by pkfec** [comment]
On my local env, i have updated AO 2019-14, AO 2019-11, AO 2018-15 with missing regulations :
I have set up elastic search service, connect to Dev DB  grab the latest Dev API  S3 creds  , update the AO python code and include the missing regulations, and  finally ran the task  that loads the AO's. 

**In Dev environment screen shot for AO 2019-14 with missing regs:**

<img width="1126" alt="Screen Shot 2020-05-08 at 4 34 22 PM" src="https://user-images.githubusercontent.com/11650355/81447028-e04cef80-9149-11ea-9908-199a3602d17d.png">

**In Local screen shot after regs are added to AO 2019-14:**
<img width="1130" alt="Screen Shot 2020-05-08 at 4 34 34 PM" src="https://user-images.githubusercontent.com/11650355/81447040-e3e07680-9149-11ea-8cfa-8b405e749af9.png">

**Comment by pkfec** [comment]
Confirmed with @dorothyyeager and @AmyKort we don't need to add missing cites for AOR's. 

- AO 2019-06
- AO 2019-10

**Comment by pkfec** [comment]
Updated the python code to include/exclude cites in feature branch `feature/4333-fix-missing-ao-cites`. Deployed this feature branch to `dev` space and ran a cf task to reload AO (cf run-task api  "python manage.py load_advisory_opinions -f 2018-15").

@dorothyyeager verified in `dev` that the AO are now showing up with the cites mentioned below.
AO 2018-15 
Added regulations:
- 11 CFR 112.1
- 11 CFR 112.5
- 11 CFR 113.1
- 11 CFR 113.2

AO 2019-11 
- Added regulation: 11 CFR 110.11
- Remove Statutes: 52 U.S.C. §301.

AO 2019-14 
Added regulations:
- 11 CFR 102.1
- 11 CFR 102.6
- 11 CFR 104.1
- 11 CFR 300.10
