### ISSUE TITLE
Improve slowest queries by adding a new index composited real_efile_sa7_comid_date_con_idx

### ISSUE THREAD

**Issue by dzhang-fec** [fecgov/openFEC#4345]
**Completion criteria:**

- [ ] create migration file

#3408  
Case 1: #3408
Summary:
===Before tune sql run 12sec
==-==After tune sql run 0.3sec with better execution plan, with same return result
About 40 times faster
By adding a combination index.
Problem: slow: 12 sec to xx mins.
What change?
create combination index
CREATE INDEX real_efile_sa7_comid_date_con_idx
ON real_efile.sa7 USING btree
(comid ASC NULLS LAST, date_con ASC NULLS LAST)
TABLESPACE pg_default;

Why?
Better execution plan on this 44,153,744 rows large table
select count(*) from real_efile.sa7
---44,153,744 rows

-===Before run 12sec
SELECT real_efile.sa7.line_num AS real_efile_sa7_line_num,
real_efile.sa7.tran_id AS real_efile_sa7_tran_id,
real_efile.sa7.imageno AS real_efile_sa7_imageno,
real_efile.sa7.entity AS real_efile_sa7_entity,
real_efile.sa7.amend AS real_efile_sa7_amend,
real_efile.sa7.br_tran_id AS real_efile_sa7_br_tran_id,
real_efile.sa7.br_sname AS real_efile_sa7_br_sname,
real_efile.sa7.create_dt AS real_efile_sa7_create_dt,
real_efile.sa7.repid AS real_efile_sa7_repid,
real_efile.sa7.rel_lineno AS real_efile_sa7_rel_lineno,
real_efile.sa7.comid AS real_efile_sa7_comid,
real_efile.sa7.prefix AS real_efile_sa7_prefix,
real_efile.sa7.fname AS real_efile_sa7_fname,
real_efile.sa7.mname AS real_efile_sa7_mname,
real_efile.sa7.name AS real_efile_sa7_name,
real_efile.sa7.suffix AS real_efile_sa7_suffix,
real_efile.sa7.city AS real_efile_sa7_city,
real_efile.sa7.state AS real_efile_sa7_state,
real_efile.sa7.zip AS real_efile_sa7_zip,
real_efile.sa7.indemp AS real_efile_sa7_indemp,
real_efile.sa7.indocc AS real_efile_sa7_indocc,
real_efile.sa7.ytd AS real_efile_sa7_ytd,
real_efile.sa7.amount AS real_efile_sa7_amount,
real_efile.sa7.date_con AS real_efile_sa7_date_con,
real_efile.sa7.other_comid AS real_efile_sa7_other_comid,
real_efile.sa7.donor_comname AS real_efile_sa7_donor_comname,
real_efile.sa7.other_str1 AS real_efile_sa7_other_str1,
real_efile.sa7.other_str2 AS real_efile_sa7_other_str2,
real_efile.sa7.other_city AS real_efile_sa7_other_city,
real_efile.sa7.other_state AS real_efile_sa7_other_state,
real_efile.sa7.other_zip AS real_efile_sa7_other_zip,
real_efile.sa7.memo_code AS real_efile_sa7_memo_code,
real_efile.sa7.memo_text AS real_efile_sa7_memo_text,
real_efile.sa7.contributor_name_text AS real_efile_sa7_contributor_name_text,
real_efile.sa7.contributor_employer_text AS real_efile_sa7_contributor_employer_text,
real_efile.sa7.contributor_occupation_text AS real_efile_sa7_contributor_occupation_text,
real_efile.sa7.pgo AS real_efile_sa7_pgo,
ofec_committee_history_mv_1.idx AS ofec_committee_history_mv_1_idx,
ofec_committee_history_mv_1.name AS ofec_committee_history_mv_1_name,
ofec_committee_history_mv_1.committee_id AS ofec_committee_history_mv_1_committee_id,
ofec_committee_history_mv_1.cycles AS ofec_committee_history_mv_1_cycles,
ofec_committee_history_mv_1.treasurer_name AS ofec_committee_history_mv_1_treasurer_name,
ofec_committee_history_mv_1.treasurer_text AS ofec_committee_history_mv_1_treasurer_text,
ofec_committee_history_mv_1.committee_type AS ofec_committee_history_mv_1_committee_type,
ofec_committee_history_mv_1.committee_type_full AS ofec_committee_history_mv_1_committee_type_full,
ofec_committee_history_mv_1.filing_frequency AS ofec_committee_history_mv_1_filing_frequency,
ofec_committee_history_mv_1.designation AS ofec_committee_history_mv_1_designation,
ofec_committee_history_mv_1.designation_full AS ofec_committee_history_mv_1_designation_full,
ofec_committee_history_mv_1.organization_type AS ofec_committee_history_mv_1_organization_type,
ofec_committee_history_mv_1.organization_type_full AS ofec_committee_history_mv_1_organization_type_full,
ofec_committee_history_mv_1.party AS ofec_committee_history_mv_1_party,
ofec_committee_history_mv_1.party_full AS ofec_committee_history_mv_1_party_full,
ofec_committee_history_mv_1.state AS ofec_committee_history_mv_1_state,
ofec_committee_history_mv_1.street_1 AS ofec_committee_history_mv_1_street_1,
ofec_committee_history_mv_1.street_2 AS ofec_committee_history_mv_1_street_2,
ofec_committee_history_mv_1.city AS ofec_committee_history_mv_1_city,
ofec_committee_history_mv_1.state_full AS ofec_committee_history_mv_1_state_full,
ofec_committee_history_mv_1.zip AS ofec_committee_history_mv_1_zip,
ofec_committee_history_mv_1.candidate_ids AS ofec_committee_history_mv_1_candidate_ids,
ofec_committee_history_mv_1.CYCLE AS ofec_committee_history_mv_1_cycle,
reps_1.repid AS reps_1_repid,
reps_1.FORM AS reps_1_form,
reps_1.comid AS reps_1_comid,
reps_1.com_name AS reps_1_com_name,
reps_1.timestamp AS reps_1_timestamp,
reps_1.create_dt AS reps_1_create_dt,
reps_1.from_date AS reps_1_from_date,
reps_1.through_date AS reps_1_through_date,
reps_1.starting AS reps_1_starting,
reps_1.ending AS reps_1_ending,
reps_1.rptcode AS reps_1_rptcode,
reps_1.previd AS reps_1_previd,
reps_1.rptnum AS reps_1_rptnum,
efiling_amendment_chain_vw_1.repid AS efiling_amendment_chain_vw_1_repid,
efiling_amendment_chain_vw_1.previd AS efiling_amendment_chain_vw_1_previd,
efiling_amendment_chain_vw_1.amendment_chain AS efiling_amendment_chain_vw_1_amendment_chain,
efiling_amendment_chain_vw_1.longest_chain AS efiling_amendment_chain_vw_1_longest_chain,
efiling_amendment_chain_vw_1.most_recent_filing AS efiling_amendment_chain_vw_1_most_recent_filing,
efiling_amendment_chain_vw_1.depth AS efiling_amendment_chain_vw_1_depth,
efiling_amendment_chain_vw_1.last AS efiling_amendment_chain_vw_1_last,
reps_1.superceded AS reps_1_superceded
FROM real_efile.sa7
left outer join ofec_committee_history_mv AS ofec_committee_history_mv_1
ON real_efile.sa7.comid = ofec_committee_history_mv_1.committee_id
AND Extract (year FROM real_efile.sa7.create_dt) + Cast (Extract (year FROM real_efile.sa7.create_dt) AS INTEGER) % 2 = ofec_committee_history_mv_1.CYCLE
left outer join real_efile.reps AS reps_1
ON real_efile.sa7.repid = reps_1.repid
left outer join efiling_amendment_chain_vw AS efiling_amendment_chain_vw_1
ON efiling_amendment_chain_vw_1.repid = reps_1.repid
WHERE real_efile.sa7.comid IN ('C00135475')
AND real_efile.sa7.date_con IS NOT NULL
ORDER BY real_efile.sa7.date_con DESC limit 30 offset 0;

-===Before
"Limit (cost=242314.67..282545.39 rows=30 width=1054) (actual time=11221.599..11221.599 rows=0 loops=1)"
" -> Nested Loop Left Join (cost=242314.67..96270359.37 rows=71608 width=1054) (actual time=11221.599..11221.599 rows=0 loops=1)"
" Join Filter: (efiling_amendment_chain_vw_1.repid = reps_1.repid)"
" -> Nested Loop Left Join (cost=1001.30..4114046.64 rows=5359 width=906) (actual time=11221.598..11221.598 rows=0 loops=1)"
" Join Filter: (((sa7.comid)::text = (ofec_committee_history_mv_1.committee_id)::text) AND ((date_part('year'::text, sa7.create_dt) + (((date_part('year'::text, sa7.create_dt))::integer % 2))::double precision) = (ofec_committee_history_mv_1.cycle)::double precision))"
" -> Gather Merge (cost=1000.88..4112906.71 rows=5359 width=585) (actual time=11221.597..11224.527 rows=0 loops=1)"
" Workers Planned: 2"
" Workers Launched: 2"
" -> Nested Loop Left Join (cost=0.85..4111288.13 rows=2233 width=585) (actual time=11217.126..11217.126 rows=0 loops=3)"
" -> Parallel Index Scan Backward using real_efile_sa7_date_con_idx on sa7 (cost=0.56..4109737.28 rows=2233 width=463) (actual time=11217.125..11217.125 rows=0 loops=3)"
" Index Cond: (date_con IS NOT NULL)"
" Filter: ((comid)::text = 'C00135475'::text)"
" Rows Removed by Filter: 14717877"
" -> Index Scan using real_efile_reps_pkey on reps reps_1 (cost=0.29..0.69 rows=1 width=122) (never executed)"
" Index Cond: (sa7.repid = repid)"
" -> Materialize (cost=0.42..14.55 rows=6 width=321) (never executed)"
" -> Index Scan using idx_ofec_committee_history_mv_committee_id on ofec_committee_history_mv ofec_committee_history_mv_1 (cost=0.42..14.52 rows=6 width=321) (never executed)"
" Index Cond: ((committee_id)::text = 'C00135475'::text)"
" -> Materialize (cost=241313.37..281956.21 rows=469936 width=148) (never executed)"
" -> Subquery Scan on efiling_amendment_chain_vw_1 (cost=241313.37..269509.53 rows=469936 width=148) (never executed)"
" -> WindowAgg (cost=241313.37..264810.17 rows=469936 width=184) (never executed)"
" CTE oldest_filing"
" -> Recursive Union (cost=0.00..169284.23 rows=469936 width=75) (never executed)"
" -> Seq Scan on reps (cost=0.00..1279.69 rows=30016 width=65) (never executed)"
" Filter: (previd IS NULL)"
" -> Hash Join (cost=1344.10..15860.58 rows=43992 width=75) (never executed)"
" Hash Cond: (oldest.repid = se.previd)"
" -> WorkTable Scan on oldest_filing oldest (cost=0.00..6003.20 rows=300160 width=52) (never executed)"
" -> Hash (cost=1279.69..1279.69 rows=5153 width=23) (never executed)"
" -> Seq Scan on reps se (cost=0.00..1279.69 rows=5153 width=23) (never executed)"
" Filter: (previd IS NOT NULL)"
" -> Sort (cost=72029.14..73203.98 rows=469936 width=100) (never executed)"
" Sort Key: oldest_filing.last, oldest_filing.depth"
" -> CTE Scan on oldest_filing (cost=0.00..9398.72 rows=469936 width=100) (never executed)"
"Planning time: 1.018 ms"
"Execution time: 11228.675 ms"

---After---------------run 603 ms.

"Limit (cost=241314.65..279828.50 rows=30 width=1054) (actual time=0.027..0.027 rows=0 loops=1)"
" -> Nested Loop Left Join (cost=241314.65..92960860.21 rows=72223 width=1054) (actual time=0.027..0.027 rows=0 loops=1)"
" Join Filter: (efiling_amendment_chain_vw_1.repid = reps_1.repid)"
" -> Nested Loop Left Join (cost=1.27..15829.64 rows=5405 width=906) (actual time=0.027..0.027 rows=0 loops=1)"
" -> Nested Loop Left Join (cost=0.98..12093.61 rows=5405 width=784) (actual time=0.027..0.027 rows=0 loops=1)"
" Join Filter: (((sa7.comid)::text = (ofec_committee_history_mv_1.committee_id)::text) AND ((date_part('year'::text, sa7.create_dt) + (((date_part('year'::text, sa7.create_dt))::integer % 2))::double precision) = (ofec_committee_history_mv_1.cycle)::double precision))"
" -> Index Scan Backward using real_efile_sa7_comid_idx2 on sa7 (cost=0.56..10944.02 rows=5405 width=463) (actual time=0.026..0.026 rows=0 loops=1)"
" Index Cond: (((comid)::text = 'C00135475'::text) AND (date_con IS NOT NULL))"
" -> Materialize (cost=0.42..14.55 rows=6 width=321) (never executed)"
" -> Index Scan using idx_ofec_committee_history_mv_committee_id on ofec_committee_history_mv ofec_committee_history_mv_1 (cost=0.42..14.52 rows=6 width=321) (never executed)"
" Index Cond: ((committee_id)::text = 'C00135475'::text)"
" -> Index Scan using real_efile_reps_pkey on reps reps_1 (cost=0.29..0.69 rows=1 width=122) (never executed)"
" Index Cond: (sa7.repid = repid)"
" -> Materialize (cost=241313.37..281956.21 rows=469936 width=148) (never executed)"
" -> Subquery Scan on efiling_amendment_chain_vw_1 (cost=241313.37..269509.53 rows=469936 width=148) (never executed)"
" -> WindowAgg (cost=241313.37..264810.17 rows=469936 width=184) (never executed)"
" CTE oldest_filing"
" -> Recursive Union (cost=0.00..169284.23 rows=469936 width=75) (never executed)"
" -> Seq Scan on reps (cost=0.00..1279.69 rows=30016 width=65) (never executed)"
" Filter: (previd IS NULL)"
" -> Hash Join (cost=1344.10..15860.58 rows=43992 width=75) (never executed)"
" Hash Cond: (oldest.repid = se.previd)"
" -> WorkTable Scan on oldest_filing oldest (cost=0.00..6003.20 rows=300160 width=52) (never executed)"
" -> Hash (cost=1279.69..1279.69 rows=5153 width=23) (never executed)"
" -> Seq Scan on reps se (cost=0.00..1279.69 rows=5153 width=23) (never executed)"
" Filter: (previd IS NOT NULL)"
" -> Sort (cost=72029.14..73203.98 rows=469936 width=100) (never executed)"
" Sort Key: oldest_filing.last, oldest_filing.depth"
" -> CTE Scan on oldest_filing (cost=0.00..9398.72 rows=469936 width=100) (never executed)"
"Planning time: 0.883 ms"
"Execution time: 3.002 ms"

**Comment by hcaofec** [comment]
PR is merged, so closing.
