### ISSUE TITLE
EC and CC endpoints not filtering by committee ID

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4357]
**What we're after:**
These endpoints aren't filtering by committee ID: 

aggregates.CommunicationCostByCandidateView:
 - https://api.open.fec.gov/v1/committee/C70001318/communication_costs/by_candidate/?candidate_id=H8IL03102&api_key=DEMO_KEY

aggregates.ElectioneeringByCandidateView:
 -  https://api.open.fec.gov/v1/committee/C30002976/electioneering/by_candidate/?candidate_id=P80001571&api_key=DEMO_KEY

**Action items:**
- [x] **Determine if this is still broken**
- [x] If we don't need this, close it
- [x] If we do need the work, convert this ticket to do the work

**Completion criteria:**
- [x] Filter results by committee ID, case insensitive

**Comment by fec-jli** [comment]
These two broken endpoints don't exist anymore, replaced by the other endpoints.

1)https://api.open.fec.gov/v1/committee/C70001318/communication_costs/by_candidate/?candidate_id=H8IL03102&api_key=DEMO_KEY

replaced by this endpoint:
https://api.open.fec.gov/v1/communication_costs/?page=1&sort_nulls_last=false&sort_null_only=false&sort_hide_null=false&committee_id=C70001318&candidate_id=H8IL03102&per_page=20&api_key=DEMO_KEY


2)https://api.open.fec.gov/v1/committee/C30002976/electioneering/by_candidate/?candidate_id=P80001571&api_key=DEMO_KEY

replaced by this endpoint:
https://api.open.fec.gov/v1/electioneering/?page=1&sort_nulls_last=false&sort_null_only=false&sort_hide_null=false&committee_id=C30002976&candidate_id=P80001571&per_page=20&api_key=DEMO_KEY
