### ISSUE TITLE
Research why MURs are missing documents after reload

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4361]
**What we're after:**
We're experiencing an issue on MUR pages when no documents are present. If no documents are present the page fails to load. To catch missing MUR documents in the future, we should research why this is happening.

Example: https://stage.fec.gov/data/legal/matter-under-review/7620/

Research from prod:

MURs have an earlier `pg_date` than documents.

+-----------+----------------+-------------+----------------------------+-----------------+
| case_no   | case_id        | case_type   | pg_date                    | published_flg   |
|-----------+----------------+-------------+----------------------------+-----------------|
| 7620      | 60000002975456 | MUR         | 2020-05-16 20:23:34.477607 | True            |
+-----------+----------------+-------------+----------------------------+-----------------+

```
SELECT case_no, case_id, case_type, pg_date, published_flg, * 
     FROM fecmur.cases_with_parsed_case_serial_numbers_vw 
     WHERE pg_date >= NOW() - '50 hour'::INTERVAL and case_no='7620' 
     ORDER BY case_serial limit 100                                               
```

```
    SELECT
        doc.document_id,
        mur.case_no,
        mur.case_type,
        doc.filename,
        doc.category,
        doc.description,
        doc.ocrtext,
        doc.fileimage,
        length(fileimage) AS length,
        doc.doc_order_id,
        doc.document_date, doc.*
    FROM fecmur.document doc
    INNER JOIN fecmur.cases_with_parsed_case_serial_numbers_vw mur
        ON mur.case_id = doc.case_id
    WHERE doc.case_id = 60000002975456
    ORDER BY doc.doc_order_id, doc.document_date desc, doc.document_id DESC
  ```

```
pg_date      
2020-05-17 01:17:43.30203
```

**Statements:**
- At the time MURs were reloaded, documents couldn't be found. This has happened before (February)
- It doesn't appear possible to tell whether modified MURs are inserts or updates. Just pg_date.

**Questions:**
- What was changed for the MURs? Salient handles these inserts?
- Can we tell whether on '2020-05-16 20:23:34.477607' (pg_date for the MUR) that there was data in fecmur.document table?
- What happens when AOs are missing documents? Do we need to handle this too?
- Do all MURs have documents? Do we have a way to handle this? Do we need a way?

**Technical requirements:**
- [ ] Figure out why documents aren't being loaded 
- [ ] Add better logging for missing docs
- [ ] Add a slack alert if this happens (MUR without documents - do all MURs have documents?)
- [ ] Better error handling on front end when MUR is missing documents
- [ ] Pair with design/content on missing doc messages

**Completion criteria:**
- [ ] ~Front-end should not error when there are no recent MURs present. The page will still load and show a message for users explaining why there aren't any documents.~ https://github.com/fecgov/openFEC/issues/4364
- [ ] Notify Salient that we should know before a reload so we can keep an eye out for errors/issues and query for missing documents

**Related work:**
https://github.com/fecgov/openFEC/issues/4364

**Comment by fec-jli** [comment]
After talking with Silent, they agree to adjust the sequence of table when reloading data.
1)**aouser** 
always reload data into **ao** table the last.

2) **fecmur**, 
always reoad data into **case** table the last.

They will reload the whole data to **aouser** and **fecmur** on stage for testing soon.

**Comment by fec-jli** [comment]
Thanks Silent finished reloading aouser and fecmur data to stage db this morning (05/22/2020) using new sequence.(load data into **"ao"** and **"case"** tables the last)

The MUR 's documents show on stage site now, fix missing issue.
ex: https://stage.fec.gov/data/legal/matter-under-review/7260/

We also estimate the down time during reload all ao and mur data: about 12 hours(include test)
1)1:33am—5:41am, Silent reload data to postgres db (aouser and fecmur)
2)check fecmur data timestamp: 
```
fecmur.document.pg_date: 2020-05-22 09:41:47 (**5:41:47am EST**)
fecmur.case.pg_date: 2020-05-22 09:46:47(**5:46:47am EST**)
```
3)16:53:17(**12:53:17pm EST**), Elastic Search load done
4) Show on website at 12:53pm (EST)

**Comment by fec-jli** [comment]
This is done. close.
