### ISSUE TITLE
Incorporate design/UX and feature flag for API key sign up

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4363]
**What we're after:**
The vanilla sign up key page prototype has been completed. There is outstanding feedback that needs to be addressed prior to merging the code.

**Completion criteria:**
- [x] The sign up key page is under a feature flag
- [x] The design/UX feedback is incorporated per https://github.com/fecgov/openFEC/pull/4359#issuecomment-630270654 (per @JonellaCulmer)
    - [x] We include help text that says to include information where "* Required", but none of the fields include an asterisk. Can you include one where appropriate? Or add more "(optional)" text everywhere else.
    - [x] We need to reduce the size of the header for the sign-up text. Currently, it's the same size and prominence as the page title. Can we reduct the text "Sign up for an API key" to 24px?
    - [x] Can we add a second sentence that explains that users can still use the demo key lower on the page? Not sure how to phrase it. Example: Signing up here does not prevent you from trying out the API below using a DEMO_KEY. For those interested in doing XXX, please sign up for an API key.
- [x] Incorporate finalized language for API key sign up page
- ~[ ] Incorporate finalized language for API key sign up email, also include api.open.fec.gov in the example within the email~moved to issue #4445 by @JonellaCulmer 
- [x] Remove `Get an [API key here](https://api.data.gov/signup/)` when the feature flag is turned on https://github.com/fecgov/openFEC/pull/4359#issuecomment-636054696
- [x] Clean up JS per @johnnyporkchops https://github.com/fecgov/openFEC/pull/4359#pullrequestreview-421086744 and
- [x] Clean up comments per @johnnyporkchops https://github.com/fecgov/openFEC/pull/4359#pullrequestreview-421087807
- [x] Add API_UMBRELLA_SIGNUP_KEY for each environment

**Comment by jason-upchurch** [comment]
Working on the feature flag component today.

**Comment by jason-upchurch** [comment]
This ticket is on hold while (unrelated) ticket for loading eregs is being worked:
https://github.com/fecgov/fec-eregs/issues/502

**Comment by jason-upchurch** [comment]
successfully generated welcome email to include the user's `api_key` by escaping variable as `{{ '{{ api_key }}' }}`

**Comment by jason-upchurch** [comment]
@JonellaCulmer cc @PaulClark2 @AmyKort @patphongs this issue will likely be completed in innovation sprint due to the prioritization of loading the 2020 eregs.

**Comment by jason-upchurch** [comment]
@JonellaCulmer how does this welcome email look to you?

<img width="616" alt="Screen Shot 2020-07-01 at 3 01 47 PM" src="https://user-images.githubusercontent.com/49287206/86281632-dbd20f80-bbab-11ea-84df-4c1fa94386ce.png">

**Comment by JonellaCulmer** [comment]
@jason-upchurch Looks great. I think any API user would know what you mean when you say "pass your key in the URL" so I'll leave that alone, unless we think that "paste" might be better than "pass". But I defer to you on that terminology.

In the last sentence, "When contacting us, please tell us what API you're accessing..." Don't we have just the one API? Or are you looking for something more specific like the endpoint? 

-----------------
Not part of this work/possible future task that we don't need to do anything with at this time:
Wondering if incorporating a feedback box on the swagger page is possible. I know we get responses via email but this could be another avenue in the future.

**Comment by jason-upchurch** [comment]
@JonellaCulmer thanks for the feedback. I'm glad it looks good! That text gets passed (like a parameter gets "passed") from api.data.gov, so I'm not sure what we readily have control over. I'll contact them about altering the text at the bottom and document my research in this issue.

Would you please open an issue for your suggestion? It seems like a reasonable thing to consider.

**Comment by JonellaCulmer** [comment]
@jason-upchurch Oh, you're saying we don't have control over the email where it mentions "When contacting us..."?

**Comment by jason-upchurch** [comment]
@JonellaCulmer That text gets passed from api.data.gov, so I'm not sure what we readily have control over. I'll contact them about altering the text at the bottom and document my research in this issue!

**Comment by jason-upchurch** [comment]
per @JonellaCulmer 
>@Jason Upchurch The new research you mentioned (to address my comment about the ‘one API’), doesn’t need to be a blocker to implementing the API key signup page. I’m satisfied with the language as it’s currently showing in the example email (comment: https://github.com/fecgov/openFEC/issues/4363#issuecomment-652593839) and think we should move forward without any other changes to the email text. If we’re able to make future improvements to the language it can happen under the new ticket, #4445. (edited)
