### ISSUE TITLE
Error handling and alerting for MURs that are missing documents

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4364]
**What we're after:**
To catch missing MUR documents in the future, we need to incorporate better error handling and alerting when an error occurs in production. We currently get emails to the database team, but adding slack would put more eyes on this high-impact issue.

**For more details:** 
This is related to https://github.com/fecgov/openFEC/issues/4361

**Completion criteria:**
- [x]  When reloading MURs, API should show a warning message when there are missing documents.
- [x]  Celery should send a Slack alert once a day when there are missing documents in production.

**Comment by patphongs** [comment]
Moving this for now so we can do the Slack alerting later

**Comment by patphongs** [comment]
Moved to 15.6 due to resource constraints

**Comment by lbeaufort** [comment]
Partially addressed by https://github.com/fecgov/openFEC/pull/4957 - we need to have a larger conversation about the best technical approach to these alerts. After checking with @fec-jli and @patphongs I'm going to put this back in "new issues" and re-prioritize this work if it the issue re-occurs.

**Comment by pkfec** [comment]
Case document refresh window has been updated in this PR https://github.com/fecgov/openFEC/pull/5241

Slack alerts have been setup on `legal-source and `bots` channel when legal documents are updated.
