### ISSUE TITLE
Investigate speeding up query counts by not specifying columns

### ISSUE THREAD

**Issue by dzhang-fec** [fecgov/openFEC#4368]
### Summary
Improve slowest queries by python code change: investigate speeding up query counts by not specifying columns. "81" column data to "1" column data (2 to 3 times faster and 3000 times less cost of DB memory). This is to speed the sql as more efficient and faster way by only scan the data on cluster primary key (not other unnecessary 81 columns's 42 indexes...) and improve the Database stability (no crash) and improve end user experience (get what they want instead of nothing return after 5mins)   

### Problem:
SQL is top 1 slow sql at 5/21 outage, 9+mins, contributed the 5/21 outage

The list of top sqls:
2020-05-21 14:25:30 UTC:ec2-52-222-122-97.us-gov-west-1.compute.amazonaws.com(28318):fec_api@fec:[53429]:LOG:  00000: duration: 531906.619 ms

2020-05-21 14:21:52 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(56620):fec_api@fec:[53506]:LOG:  00000: duration: 37107.614 ms
2020-05-21 14:21:55 UTC:ec2-52-222-122-97.us-gov-west-1.compute.amazonaws.com(2230):fec_api@fec:[53849]:LOG:  00000: duration: 39283.466 ms
2020-05-21 14:21:52 UTC:ec2-52-222-122-97.us-gov-west-1.compute.amazonaws.com(7143):fec_api@fec:[54470]:LOG:  00000: duration: 39545.578 ms
2020-05-21 14:38:40 UTC:ec2-52-222-122-97.us-gov-west-1.compute.amazonaws.com(46657):fec_api@fec:[61012]:LOG:  00000: duration: 40826.120 ms
2020-05-21 14:35:55 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(18930):fec_api@fec:[61197]:LOG:  00000: duration: 43630.518 ms
2020-05-21 14:25:25 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(64542):fec_api@fec:[61145]:LOG:  00000: duration: 45558.757 ms
2020-05-21 14:24:02 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(57054):fec_api@fec:[53423]:LOG:  00000: duration: 46149.068 ms
2020-05-21 14:31:45 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(18930):fec_api@fec:[61197]:LOG:  00000: duration: 50994.219 ms
2020-05-21 14:43:10 UTC:ec2-52-222-122-97.us-gov-west-1.compute.amazonaws.com(46657):fec_api@fec:[61012]:LOG:  00000: duration: 56423.646 ms
2020-05-21 14:31:04 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(63880):fec_api@fec:[61048]:LOG:  00000: duration: 64510.690 ms
2020-05-21 14:32:05 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(27637):fec_api@fec:[60986]:LOG:  00000: duration: 69577.844 ms
2020-05-21 14:31:51 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(34300):fec_api@fec:[61289]:LOG:  00000: duration: 81256.544 ms
2020-05-21 14:43:53 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(34300):fec_api@fec:[61289]:LOG:  00000: duration: 86668.024 ms
2020-05-21 14:41:47 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(63880):fec_api@fec:[61048]:LOG:  00000: duration: 91261.847 ms
2020-05-21 14:32:48 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(6916):fec_api@fec:[61047]:LOG:  00000: duration: 97674.200 ms
2020-05-21 14:27:24 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(43561):fec_api@fec:[61046]:LOG:  00000: duration: 114913.742 ms
2020-05-21 14:27:34 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(6916):fec_api@fec:[61047]:LOG:  00000: duration: 122762.167 ms
2020-05-21 14:37:01 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(63880):fec_api@fec:[61048]:LOG:  00000: duration: 136971.194 ms
2020-05-21 14:23:01 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(25218):fec_api@fec:[53430]:LOG:  00000: duration: 180431.541 ms
2020-05-21 14:23:01 UTC:ec2-52-222-122-97.us-gov-west-1.compute.amazonaws.com(41769):fec_api@fec:[54495]:LOG:  00000: duration: 185413.376 ms
2020-05-21 14:23:01 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(7702):fec_api@fec:[53456]:LOG:  00000: duration: 187030.738 ms
2020-05-21 14:42:36 UTC:ec2-52-222-122-97.us-gov-west-1.compute.amazonaws.com(24883):fec_api@fec:[60969]:LOG:  00000: duration: 500951.166 ms
2020-05-21 14:25:30 UTC:ec2-52-222-122-97.us-gov-west-1.compute.amazonaws.com(26845):fec_api@fec:[53867]:LOG:  00000: duration: 526333.794 ms
2020-05-21 14:25:30 UTC:ec2-52-222-122-97.us-gov-west-1.compute.amazonaws.com(28318):fec_api@fec:[53429]:LOG:  00000: duration: 531906.619 ms

Here is the top 1 slowest sql:
2020-05-21 14:25:30 UTC:ec2-52-222-122-97.us-gov-west-1.compute.amazonaws.com(28318):fec_api@fec:[53429]:LOG:  00000: duration: 531906.619 ms

SELECT count(*) AS count_1
FROM
  (SELECT disclosure.fec_fitem_sched_a.cmte_id AS disclosure_fec_fitem_sched_a_cmte_id,
          disclosure.fec_fitem_sched_a.rpt_yr AS disclosure_fec_fitem_sched_a_rpt_yr,
          disclosure.fec_fitem_sched_a.rpt_tp AS disclosure_fec_fitem_sched_a_rpt_tp,
          disclosure.fec_fitem_sched_a.image_num AS disclosure_fec_fitem_sched_a_image_num,
          disclosure.fec_fitem_sched_a.line_num AS disclosure_fec_fitem_sched_a_line_num,
          disclosure.fec_fitem_sched_a.tran_id AS disclosure_fec_fitem_sched_a_tran_id,
          disclosure.fec_fitem_sched_a.file_num AS disclosure_fec_fitem_sched_a_file_num,
          disclosure.fec_fitem_sched_a.cmte_nm AS disclosure_fec_fitem_sched_a_cmte_nm,
          disclosure.fec_fitem_sched_a.entity_tp AS disclosure_fec_fitem_sched_a_entity_tp,
          disclosure.fec_fitem_sched_a.entity_tp_desc AS disclosure_fec_fitem_sched_a_entity_tp_desc,
          disclosure.fec_fitem_sched_a.contbr_id AS disclosure_fec_fitem_sched_a_contbr_id,
          disclosure.fec_fitem_sched_a.contbr_prefix AS disclosure_fec_fitem_sched_a_contbr_prefix,
          disclosure.fec_fitem_sched_a.contbr_nm AS disclosure_fec_fitem_sched_a_contbr_nm,
          disclosure.fec_fitem_sched_a.cmte_tp AS disclosure_fec_fitem_sched_a_cmte_tp,
          disclosure.fec_fitem_sched_a.org_tp AS disclosure_fec_fitem_sched_a_org_tp,
          disclosure.fec_fitem_sched_a.cmte_dsgn AS disclosure_fec_fitem_sched_a_cmte_dsgn,
          disclosure.fec_fitem_sched_a.contbr_nm_first AS disclosure_fec_fitem_sched_a_contbr_nm_first,
          disclosure.fec_fitem_sched_a.contbr_m_nm AS disclosure_fec_fitem_sched_a_contbr_m_nm,
          disclosure.fec_fitem_sched_a.contbr_nm_last AS disclosure_fec_fitem_sched_a_contbr_nm_last,
          disclosure.fec_fitem_sched_a.contbr_suffix AS disclosure_fec_fitem_sched_a_contbr_suffix,
          disclosure.fec_fitem_sched_a.contbr_st1 AS disclosure_fec_fitem_sched_a_contbr_st1,
          disclosure.fec_fitem_sched_a.contbr_st2 AS disclosure_fec_fitem_sched_a_contbr_st2,
          disclosure.fec_fitem_sched_a.contbr_city AS disclosure_fec_fitem_sched_a_contbr_city,
          disclosure.fec_fitem_sched_a.contbr_st AS disclosure_fec_fitem_sched_a_contbr_st,
          disclosure.fec_fitem_sched_a.contbr_zip AS disclosure_fec_fitem_sched_a_contbr_zip,
          disclosure.fec_fitem_sched_a.contbr_employer AS disclosure_fec_fitem_sched_a_contbr_employer,
          disclosure.fec_fitem_sched_a.contbr_occupation AS disclosure_fec_fitem_sched_a_contbr_occupation,
          disclosure.fec_fitem_sched_a.clean_contbr_id AS disclosure_fec_fitem_sched_a_clean_contbr_id,
          disclosure.fec_fitem_sched_a.receipt_tp AS disclosure_fec_fitem_sched_a_receipt_tp,
          disclosure.fec_fitem_sched_a.receipt_tp_desc AS disclosure_fec_fitem_sched_a_receipt_tp_desc,
          disclosure.fec_fitem_sched_a.receipt_desc AS disclosure_fec_fitem_sched_a_receipt_desc,
          disclosure.fec_fitem_sched_a.memo_cd AS disclosure_fec_fitem_sched_a_memo_cd,
          disclosure.fec_fitem_sched_a.memo_cd_desc AS disclosure_fec_fitem_sched_a_memo_cd_desc,
          disclosure.fec_fitem_sched_a.contb_receipt_dt AS disclosure_fec_fitem_sched_a_contb_receipt_dt,
          disclosure.fec_fitem_sched_a.contb_receipt_amt AS disclosure_fec_fitem_sched_a_contb_receipt_amt,
          disclosure.fec_fitem_sched_a.contb_aggregate_ytd AS disclosure_fec_fitem_sched_a_contb_aggregate_ytd,
          disclosure.fec_fitem_sched_a.cand_id AS disclosure_fec_fitem_sched_a_cand_id,
          disclosure.fec_fitem_sched_a.cand_nm AS disclosure_fec_fitem_sched_a_cand_nm,
          disclosure.fec_fitem_sched_a.cand_nm_first AS disclosure_fec_fitem_sched_a_cand_nm_first,
          disclosure.fec_fitem_sched_a.cand_nm_last AS disclosure_fec_fitem_sched_a_cand_nm_last,
          disclosure.fec_fitem_sched_a.cand_m_nm AS disclosure_fec_fitem_sched_a_cand_m_nm,
          disclosure.fec_fitem_sched_a.cand_prefix AS disclosure_fec_fitem_sched_a_cand_prefix,
          disclosure.fec_fitem_sched_a.cand_suffix AS disclosure_fec_fitem_sched_a_cand_suffix,
          disclosure.fec_fitem_sched_a.cand_office AS disclosure_fec_fitem_sched_a_cand_office,
          disclosure.fec_fitem_sched_a.cand_office_desc AS disclosure_fec_fitem_sched_a_cand_office_desc,
          disclosure.fec_fitem_sched_a.cand_office_st AS disclosure_fec_fitem_sched_a_cand_office_st,
          disclosure.fec_fitem_sched_a.cand_office_st_desc AS disclosure_fec_fitem_sched_a_cand_office_st_desc,
          disclosure.fec_fitem_sched_a.cand_office_district AS disclosure_fec_fitem_sched_a_cand_office_district,
          disclosure.fec_fitem_sched_a.conduit_cmte_id AS disclosure_fec_fitem_sched_a_conduit_cmte_id,
          disclosure.fec_fitem_sched_a.conduit_cmte_nm AS disclosure_fec_fitem_sched_a_conduit_cmte_nm,
          disclosure.fec_fitem_sched_a.conduit_cmte_st1 AS disclosure_fec_fitem_sched_a_conduit_cmte_st1,
          disclosure.fec_fitem_sched_a.conduit_cmte_st2 AS disclosure_fec_fitem_sched_a_conduit_cmte_st2,
          disclosure.fec_fitem_sched_a.conduit_cmte_city AS disclosure_fec_fitem_sched_a_conduit_cmte_city,
          disclosure.fec_fitem_sched_a.conduit_cmte_st AS disclosure_fec_fitem_sched_a_conduit_cmte_st,
          disclosure.fec_fitem_sched_a.conduit_cmte_zip AS disclosure_fec_fitem_sched_a_conduit_cmte_zip,
          disclosure.fec_fitem_sched_a.donor_cmte_nm AS disclosure_fec_fitem_sched_a_donor_cmte_nm,
          disclosure.fec_fitem_sched_a.national_cmte_nonfed_acct AS disclosure_fec_fitem_sched_a_national_cmte_nonfed_acct,
          disclosure.fec_fitem_sched_a.election_tp AS disclosure_fec_fitem_sched_a_election_tp,
          disclosure.fec_fitem_sched_a.election_tp_desc AS disclosure_fec_fitem_sched_a_election_tp_desc,
          disclosure.fec_fitem_sched_a.fec_election_tp_desc AS disclosure_fec_fitem_sched_a_fec_election_tp_desc,
          disclosure.fec_fitem_sched_a.fec_election_yr AS disclosure_fec_fitem_sched_a_fec_election_yr,
          disclosure.fec_fitem_sched_a.action_cd AS disclosure_fec_fitem_sched_a_action_cd,
          disclosure.fec_fitem_sched_a.action_cd_desc AS disclosure_fec_fitem_sched_a_action_cd_desc,
          disclosure.fec_fitem_sched_a.schedule_type_desc AS disclosure_fec_fitem_sched_a_schedule_type_desc,
          disclosure.fec_fitem_sched_a.pg_date AS disclosure_fec_fitem_sched_a_pg_date,
          disclosure.fec_fitem_sched_a.orig_sub_id AS disclosure_fec_fitem_sched_a_orig_sub_id,
          disclosure.fec_fitem_sched_a.back_ref_tran_id AS disclosure_fec_fitem_sched_a_back_ref_tran_id,
          disclosure.fec_fitem_sched_a.back_ref_sched_nm AS disclosure_fec_fitem_sched_a_back_ref_sched_nm,
          disclosure.fec_fitem_sched_a.filing_form AS disclosure_fec_fitem_sched_a_filing_form,
          disclosure.fec_fitem_sched_a.link_id AS disclosure_fec_fitem_sched_a_link_id,
          disclosure.fec_fitem_sched_a.contributor_name_text AS disclosure_fec_fitem_sched_a_contributor_name_text,
          disclosure.fec_fitem_sched_a.contributor_employer_text AS disclosure_fec_fitem_sched_a_contributor_employer_text,
          disclosure.fec_fitem_sched_a.contributor_occupation_text AS disclosure_fec_fitem_sched_a_contributor_occupation_text,
          disclosure.fec_fitem_sched_a.is_individual AS disclosure_fec_fitem_sched_a_is_individual,
          disclosure.fec_fitem_sched_a.memo_text AS disclosure_fec_fitem_sched_a_memo_text,
          disclosure.fec_fitem_sched_a.two_year_transaction_period AS disclosure_fec_fitem_sched_a_two_year_transaction_period,
          disclosure.fec_fitem_sched_a.schedule_type AS disclosure_fec_fitem_sched_a_schedule_type,
          disclosure.fec_fitem_sched_a.increased_limit AS disclosure_fec_fitem_sched_a_increased_limit,
          disclosure.fec_fitem_sched_a.sub_id AS disclosure_fec_fitem_sched_a_sub_id,
          disclosure.fec_fitem_sched_a.pdf_url AS disclosure_fec_fitem_sched_a_pdf_url,
          disclosure.fec_fitem_sched_a.line_number_label AS disclosure_fec_fitem_sched_a_line_number_label
   FROM disclosure.fec_fitem_sched_a
   WHERE disclosure.fec_fitem_sched_a.is_individual = TRUE
     AND disclosure.fec_fitem_sched_a.contbr_city IN ('LUCAS',
                                                      'DALLAS')
     AND disclosure.fec_fitem_sched_a.two_year_transaction_period IN (2020)
     AND disclosure.fec_fitem_sched_a.contb_receipt_dt >= '2019-01-01'::date
     AND disclosure.fec_fitem_sched_a.contb_receipt_dt <= '2020-12-31'::date) AS anon_1

### Analysis and suggestion 

Currently this sql takes super  database memory by 383,259 rows with "81" columns of whole schedule_a table, which is not necessary to get the equal query result . We may get same count(*) from the following simpler query by 1 column of primary key.
Suggestion: change code to
	 SELECT count(disclosure.fec_fitem_sched_a.cmte_id) AS count_1 
   FROM disclosure.fec_fitem_sched_a
   WHERE disclosure.fec_fitem_sched_a.is_individual = TRUE
     AND disclosure.fec_fitem_sched_a.contbr_city IN ('LUCAS',
                                                      'DALLAS')
     AND disclosure.fec_fitem_sched_a.two_year_transaction_period IN (2020)
     AND disclosure.fec_fitem_sched_a.contb_receipt_dt >= '2019-01-01'::date
     AND disclosure.fec_fitem_sched_a.contb_receipt_dt <= '2020-12-31'::date 

or
disclosure.fec_fitem_sched_a.cmte_id 

SELECT count(*) AS count_1
FROM
  (SELECT disclosure.fec_fitem_sched_a.cmte_id AS disclosure_fec_fitem_sched_a_cmte_id
   FROM disclosure.fec_fitem_sched_a
   WHERE disclosure.fec_fitem_sched_a.is_individual = TRUE
     AND disclosure.fec_fitem_sched_a.contbr_city IN ('LUCAS',
                                                      'DALLAS')
     AND disclosure.fec_fitem_sched_a.two_year_transaction_period IN (2020)
     AND disclosure.fec_fitem_sched_a.contb_receipt_dt >= '2019-01-01'::date
     AND disclosure.fec_fitem_sched_a.contb_receipt_dt <= '2020-12-31'::date) AS anon_1

It will be 3 to 10 times faster

**Completion criteria**
- [ ] Research getting query count without passing columns, start with one endpoint, measure whether this is better
- [ ] Document takeaways
- [ ] Open followup tickets as necessary (possibly other endpoints). Not all tables have primary keys. Maybe this only needs to be implemented for itemized resources.

**Comment by lbeaufort** [comment]
Tracking results here -so far a bit inconclusive so I need to test more: https://docs.google.com/spreadsheets/d/1VKjqaPdnf8GAU6znXHTwbMVQKBzIbbjFk2MKVXSUWy4/edit#gid=0

**Comment by lbeaufort** [comment]
@dzhang-fec I put in this follow-up issue in case we want to implement this change for other endpoints: https://github.com/fecgov/openFEC/issues/4429
