### ISSUE TITLE
Add index for `pg_date` on fec_fitem_sched_a tables

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4379]
This [community-submitted PR](https://github.com/fecgov/openFEC/pull/4367) is ready, but
`load_date` (`pg_date` in database) currently does not have index in the Schedule A table  (`fec_fitem_sched_a`).  If we need to filter on it, with large quantity of data, we need to add index to this column.

Related technical debt issue: https://github.com/fecgov/openFEC/issues/4378: Research adding API logic to require filter fields for certain endpoints to have an index

**Steps to reproduce queries**
- Check out this branch: https://github.com/fecgov/openFEC/pull/4367
```
git remote add pg_date_remote git@github.com:arcegkaz/openFEC.git
git fetch pg_date_remote
git checkout --track pg_date_remote/sched_a-load_date-filter
```
- Run these queries: 

http://localhost:5000/v1/schedules/schedule_a/?max_load_date=5-26-2010&two_year_transaction_period=2010

http://localhost:5000/v1/schedules/schedule_a/?min_load_date=5-26-2020&two_year_transaction_period=2020

**Completion criteria:**
- [ ] Add an index on `pg_date` in `fec_fitem_sched_a` table based on queries (sort by contribution date)

**Comment by fecjjeng** [comment]
3 indexes had been considered to facilitate the query for filtering on pg_date:
CREATE INDEX idx_sched_a_2019_2020_pg_dt ON disclosure.fec_fitem_sched_a_2019_2020 USING btree (pg_date desc);

CREATE INDEX idx_sched_a_2019_2020_pg_dt_dt_sub_id_desc ON disclosure.fec_fitem_sched_a_2019_2020 USING btree (pg_date desc, contb_receipt_dt DESC, sub_id desc);

CREATE INDEX idx_sched_a_2019_2020_pg_dt_amt_sub_id_desc ON disclosure.fec_fitem_sched_a_2019_2020 USING btree (pg_date desc, contb_receipt_amt DESC, sub_id desc);


explain analyze 
select pg_date, contb_receipt_dt, sub_id
from disclosure.fec_fitem_sched_a_2019_2020 ffsa 
where pg_date < '2020-01-21'::date
order by contb_receipt_dt desc, sub_id desc

-- with no index
/*
-- 23288228 rows
        ->  Parallel Seq Scan on fec_fitem_sched_a_2019_2020 ffsa  (cost=0.00..8520736.00 rows=9688452 width=28) (actual time=0.006..92941.730 rows=7762743 loops=3)
              Filter: (pg_date < '2020-01-21'::date)
              Rows Removed by Filter: 25266558
Planning time: 0.209 ms
Execution time: 130,364.625 ms

GPlanning time: 0.203 ms
Execution time: 127,975.323 ms
*/

### 
CREATE INDEX idx_sched_a_2019_2020_pg_dt ON disclosure.fec_fitem_sched_a_2019_2020 USING btree (pg_date desc);

analyze disclosure.fec_fitem_sched_a_2019_2020

explain analyze 
select pg_date, contb_receipt_dt, sub_id
from disclosure.fec_fitem_sched_a_2019_2020 ffsa 
where pg_date < '2020-01-21'::date
order by contb_receipt_dt desc, sub_id desc

/*
        ->  Parallel Index Scan using idx_sched_a_2019_2020_pg_dt on fec_fitem_sched_a_2019_2020 ffsa  (cost=0.57..4394087.21 rows=9706360 width=28) (actual time=0.125..6109.986 rows=7762743 loops=3)
              Index Cond: (pg_date < '2020-01-21'::date)

Planning time: 1.115 ms
Execution time: 44,425.786 ms

Planning time: 0.237 ms
Execution time: 44,477.213 ms
*/


explain analyze 
select pg_date, contb_receipt_dt, sub_id
from disclosure.fec_fitem_sched_a_2019_2020 ffsa 
where pg_date < '2020-01-21'::date
order by contb_receipt_amt desc, sub_id desc

/*
        ->  Parallel Index Scan using idx_sched_a_2019_2020_pg_dt on fec_fitem_sched_a_2019_2020 ffsa  (cost=0.57..4394087.21 rows=9706360 width=33) (actual time=0.166..6137.506 rows=7762743 loops=3)
              Index Cond: (pg_date < '2020-01-21'::date)
Planning time: 0.276 ms
Execution time: 58636.011 ms

Planning time: 0.247 ms
Execution time: 58722.853 ms

*/

### Added index
CREATE INDEX idx_sched_a_2019_2020_pg_dt_dt_sub_id_desc ON disclosure.fec_fitem_sched_a_2019_2020 USING btree (pg_date desc, contb_receipt_dt DESC, sub_id desc);

analyze disclosure.fec_fitem_sched_a_2019_2020

explain analyze 
select pg_date, contb_receipt_dt, sub_id
from disclosure.fec_fitem_sched_a_2019_2020 ffsa 
where pg_date < '2020-01-21'::date
order by contb_receipt_dt desc, sub_id desc
/*
        ->  Parallel Index Only Scan using idx_sched_a_2019_2020_pg_dt_dt_sub_id_desc on fec_fitem_sched_a_2019_2020 ffsa  (cost=0.57..3055228.34 rows=9593450 width=28) (actual time=0.341..1142.892 rows=7762743 loops=3)
              Index Cond: (pg_date < '2020-01-21'::date)
              Heap Fetches: 129602
Planning time: 1.136 ms
Execution time: 39176.675 ms

Planning time: 0.228 ms
Execution time: 38589.026 ms
*/

explain analyze 
select pg_date, contb_receipt_dt, sub_id
from disclosure.fec_fitem_sched_a_2019_2020 ffsa 
where pg_date < '2020-01-21'::date
order by contb_receipt_amt desc, sub_id desc
/*
        ->  Parallel Index Scan using idx_sched_a_2019_2020_pg_dt on fec_fitem_sched_a_2019_2020 ffsa  (cost=0.57..4226923.96 rows=9593450 width=33) (actual time=0.140..6060.188 rows=7762743 loops=3)
              Index Cond: (pg_date < '2020-01-21'::date)
Planning time: 0.266 ms
Execution time: 58146.774 ms

Planning time: 0.266 ms
Execution time: 57943.307 ms
*/

## added one more index
CREATE INDEX idx_sched_a_2019_2020_pg_dt_amt_sub_id_desc ON disclosure.fec_fitem_sched_a_2019_2020 USING btree (pg_date desc, contb_receipt_amt DESC, sub_id desc);

analyze disclosure.fec_fitem_sched_a_2019_2020

explain analyze 
select pg_date, contb_receipt_dt, sub_id
from disclosure.fec_fitem_sched_a_2019_2020 ffsa 
where pg_date < '2020-01-21'::date
order by contb_receipt_dt desc, sub_id desc
/*
        ->  Parallel Index Only Scan using idx_sched_a_2019_2020_pg_dt_dt_sub_id_desc on fec_fitem_sched_a_2019_2020 ffsa  (cost=0.57..3013612.37 rows=9453239 width=28) (actual time=0.111..1118.454 rows=7762743 loops=3)
              Index Cond: (pg_date < '2020-01-21'::date)
              Heap Fetches: 115949
Planning time: 0.238 ms
Execution time: 38805.732 ms

Planning time: 0.232 ms
Execution time: 38700.733 ms

*/

explain analyze 
select pg_date, contb_receipt_dt, sub_id
from disclosure.fec_fitem_sched_a_2019_2020 ffsa 
where pg_date < '2020-01-21'::date
order by contb_receipt_amt desc, sub_id desc
/*
        ->  Parallel Index Scan using idx_sched_a_2019_2020_pg_dt on fec_fitem_sched_a_2019_2020 ffsa  (cost=0.57..4137363.85 rows=9453239 width=33) (actual time=0.109..6019.433 rows=7762743 loops=3)
              Index Cond: (pg_date < '2020-01-21'::date)
Planning time: 1.177 ms
Execution time: 58267.554 ms

Planning time: 0.245 ms
Execution time: 59089.820 ms
*/

explain analyze 
select pg_date, contb_receipt_dt, sub_id
from disclosure.fec_fitem_sched_a_2019_2020 ffsa 
where pg_date < '2020-01-21'::date
order by contb_aggregate_ytd desc, sub_id

/*
Gather Merge  (cost=5602903.98..7808813.76 rows=18906478 width=33) (actual time=34452.940..54358.980 rows=23288228 loops=1)
  Workers Planned: 2
  Workers Launched: 2
  ->  Sort  (cost=5601903.96..5625537.05 rows=9453239 width=33) (actual time=34261.426..38398.865 rows=7762743 loops=3)
        Sort Key: contb_aggregate_ytd DESC, sub_id
        Sort Method: external merge  Disk: 335256kB
        ->  Parallel Index Scan using idx_sched_a_2019_2020_pg_dt on fec_fitem_sched_a_2019_2020 ffsa  (cost=0.57..4137363.85 rows=9453239 width=33) (actual time=0.099..6178.033 rows=7762743 loops=3)
              Index Cond: (pg_date < '2020-01-21'::date)
Planning time: 1.766 ms
Execution time: 55458.469 ms

Planning time: 0.225 ms
Execution time: 54784.946 ms
*/



explain analyze 
select pg_date, contb_receipt_dt, sub_id
from disclosure.fec_fitem_sched_a_2019_2020 ffsa 
where pg_date < '2020-12-21'::date
order by contb_receipt_dt desc, sub_id desc
/*
Gather Merge  (cost=15856237.15..25484853.35 rows=82525234 width=28) (actual time=233187.319..307071.833 rows=99087902 loops=1)
  Workers Planned: 2
  Workers Launched: 2
  ->  Sort  (cost=15855237.13..15958393.67 rows=41262617 width=28) (actual time=232842.028..246734.987 rows=33029301 loops=3)
        Sort Key: contb_receipt_dt DESC, sub_id DESC
        Sort Method: external merge  Disk: 1264848kB
        ->  Parallel Seq Scan on fec_fitem_sched_a_2019_2020 ffsa  (cost=0.00..8520342.71 rows=41262617 width=28) (actual time=0.006..84277.301 rows=33029301 loops=3)
              Filter: (pg_date < '2020-12-21'::date)
Planning time: 5.893 ms
Execution time: 310598.801 ms
*/
