### ISSUE TITLE
Consistent 502s hitting /schedule_a

### ISSUE THREAD

**Issue by helgridly** [fecgov/openFEC#4404]
The following request is consistently 502ing for me:

```https://api.open.fec.gov/v1/schedules/schedule_a/?sort=-contributor_aggregate_ytd&two_year_transaction_period=2016&api_key=MYAPIKEY```

If this is as simple as adding an index to `fec_fitem_sched_a.contb_aggregate_ytd` I can probably open a PR, but if it'll be anything like [adding an index for contb_receipt_amt](https://github.com/fecgov/openFEC/blob/develop/data/migrations/V0082__add_indexes_on_fec_fitem_sched_a_tables.sql) I may take that offer back in a hurry :)

**Comment by jason-upchurch** [comment]
We will look at investigating the index approach and get back to you!

**Comment by PaulClark2** [comment]
Hussein - we are in the process of deprecating sort by `contributor_aggregate_ytd`, https://github.com/fecgov/openFEC/pull/4423. You probably received an email about this. 

Sort options that may work for you to pull the data include: 
## Ascending
contribution_receipt_date
contribution_receipt_amount
## Descending
-contribution_receipt_date
-contribution_receipt_amount
