### ISSUE TITLE
Add output field in API to determine the PCCs that convert into PACs

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4419]
**What we're after:**
When a candidate converts their candidate committee to a PAC, the candidate's financial information is unlinked from their candidate profile page. We need to preserve the linkage for committees who have changed mid-way through a 2 year transaction period and automate the addition of text to the committee page to describe the committee conversion.

**Technical considerations:**
- ~Programmatically identify all candidates where this issue exists, add the mid-cycle conversion logic to the API~
- ~Make our data more granular to account for these kinds of changes across all candidates/committees~ This isn't feasible at this time
- Once we have identified the SQL query, we will need to add the logic to the API

Related issue:
https://github.com/fecgov/openfec/issues/4292. In the CMS, we implemented the easy solution where we hardcoded a list of candidates and their committees to display a message informing users about where the former candidate committee's money is. 
- #4561  (This ticket was split in two. The first part of the ticket was spun off into 4561)

**Completion criteria:**
- ~[ ] Figure out which endpoints the committee profile pages are using for committee information~
- [ ] Make this data available in an an endpoint. Ideally, expose this somewhere in an existing endpoint if it makes sense.
- [ ] Determine the quality of the data - check historical cycles and determine if we need a start date (2010?) before which we don't show this data.
- [ ] Put in a follow-up ticket to the CMS to use this information rather than the hard-coded info

**Starting point for logic**
Thanks @PaulClark2!

Test case is  C00697441	WIN THE ERA PAC

(In Oracle db):
```
with cand_cmte as
    (select cmte_id, max(receipt_dt) as last_cand_f1
    from disclosure.nml_form_1 
    where delete_ind is null 
    and filed_cmte_tp in ('H', 'S', 'P') 
    and filed_cmte_dsgn in ('P', 'A')
    group by cmte_id)
select * 
from disclosure.nml_form_1 f, cand_cmte cc
where f.cmte_id = cc.cmte_id
and F.RECEIPT_DT > cc.last_cand_f1 -- or possibly 'F.RECEIPT_DT >= cc.last_cand_f1'*
and F.DELETE_IND is null
and f.filed_cmte_tp not in ('H', 'S', 'P')
and f.filed_cmte_dsgn not in ('P', 'A')
order by f.receipt_dt desc;
```
*a committee could file an updated F1 for their candidate committee and an F1 to change their candidate committee to a PAC on the same day. We'd want to check with @fecjjeng on that logic change.

**Comment by fecjjeng** [comment]
@PaulClark2 
1. Yes, a committee could file an updated F1 for their candidate committee and an F1 to change their candidate committee to a PAC on the same day.  I had found two cases (C00239905, C00392282), both cases happened a while ago (< 2010), but it could happen again, so it would be safer to use F.RECEIPT_DT >= cc.last_cand_f1.  
2. For the converted cmte, does it matter if the filed_cmte_dsgn not in ('P', 'A')?  or as long as filed_cmte_tp not in ('H', 'S', 'P') would qualify?  The query will return 18 more committees without restricted filed_cmte_dsgn not in ('P', 'A')
3. Some committees have more amendment F1 after they changes the cmte_tp over several years.  The following will retrieve the one with the latest receipt_dt

with cand_cmte as
    (select cmte_id, max(receipt_dt) as last_cand_f1
    from disclosure.nml_form_1 
    where delete_ind is null 
    and filed_cmte_tp in ('H', 'S', 'P') 
    and filed_cmte_dsgn in ('P', 'A')
    group by cmte_id)
select distinct on (f.cmte_id) f.cmte_id, f.receipt_dt, f.*  
from disclosure.nml_form_1 f, cand_cmte cc
where f.cmte_id = cc.cmte_id
and F.RECEIPT_DT >= cc.last_cand_f1 -- or possibly 'F.RECEIPT_DT >= cc.last_cand_f1'*
and F.DELETE_IND is null
and f.filed_cmte_tp not in ('H', 'S', 'P')
--and f.filed_cmte_dsgn not in ('P', 'A')
order by f.cmte_id, f.receipt_dt desc

**Comment by PaulClark2** [comment]
@fecjjeng I don't think filed_cmte_dsgn not in ('P', 'A') matters as long as we are checking filed_cmte_tp not in ('H', 'S', 'P'). We can drop the filed_cmte_dsgn condition.

**Comment by lbeaufort** [comment]
Jerry recommended looking at `dim_committee` (sp?) which per @fecjjeng is not in postgres.

**Comment by djgarr** [comment]
I updated the ticket based off turning this initial ticket into two tickets (alongside #4561). Wasn't sure if I should remove some of the older content or not, so I used strike through to note the changes

**Comment by JonellaCulmer** [comment]
Closing in favor of https://github.com/fecgov/openFEC/issues/4458
