### ISSUE TITLE
accessing data

### ISSUE THREAD

**Issue by songkevinc** [fecgov/openFEC#4436]
Hi,

Thanks for making campaign data available to the public.

I'm well versed in python, but unfortunately, not so famililar with postgreSQL, node.js, elasticsearch and flyaway. I'd just like to be able to access the campaign data and make my own plots on a weekly basis. I thought about just scraping data weekly using selenium but thought maybe that's too cumbersome and ignoring the wonderful work of openFEC. Are there any good tutorials on how to just some data using the API?

**Comment by jason-upchurch** [comment]
Hello @songkevinc, thank you for your interest in using the FEC's API! The API documentation is here: https://api.open.fec.gov/developers/

There is also a Google group (not monitored by the FEC) here: https://groups.google.com/forum/#!forum/fec-data

Additionally, if you encounter any bugs or need more information on the FEC's api, there is a monitored box for general questions--such as issues like this: apiinfo@fec.gov

Thank you again for your interest in the FEC API!
--Jason

cc @PaulClark2

**Comment by songkevinc** [comment]
Ah, sorry. I actually ended up finding a python wrapper for openFEC (https://github.com/jeremyjbowers/pyopenfec). This works great for most things I'm trying to do with the data.
