### ISSUE TITLE
remove hard coding from API Key signup required fields

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4447]
### Update [12/21/2020]
It appears the "required fields" are now being passed through by api.data.gov, so we can definitely remove our hard coded asterisks. Previously we hard coded the required fields as they did not automatically render. Now that they do, we are getting double asterisks, so updating the labels to include "bug"

<img width="625" alt="Screen Shot 2020-12-21 at 1 45 37 PM" src="https://user-images.githubusercontent.com/49287206/102811178-f931aa80-4392-11eb-8e0f-076737bdf28b.png">

### Summary
Related issue #4363 and PR #4385 refined api key signup page. However, to address one comment about having "*" appear next to required fields the imported template didn't render, these elements were hard coded in `swagger-ui.html`. This is not ideal, however attempting to access them through `.required` did not produce the desired results. I also reached out to api.data.gov to ask for help on how we might do this more generally. n order to not hold up the work for stylistic issues, the style was enforced through hard coding. Let's try to remove the hard coding.

[edit: Updated 7/23/2020 with advice below from api.data.gov about how to generalize]
>The issue here is that the FEC's main.css stylesheet (https://fec-dev-api.app.cloud.gov/docs/static/dist/main.css) includes a >snippet that hides all "label abbr" tags which is how the default asterisks are present. You can see this in the attached >screenshot of how those are being forced to "display: none".

>I see you worked around this in a different way by appending new asterisks in a different way. That certainly works, or if >you'd like to use the default asterisks, I think you should be able to get those to display by adding this to your stylesheet:

>.api-umbrella-embed label abbr {
>  display: inline;
>}

>That just forces the "label abbr" tags back to their default display status inside our widget.

### Completion criteria
- [ ] a single asterisk appears next to any required fields

**Comment by jason-upchurch** [comment]
@patphongs I wanted to make you aware of this issue as it appears we definitely don't need the hard coding of required fields anymore. It's now more of a visual bug because the required fields appear to be automatically passed (they were not before).

**Comment by fec-jli** [comment]
We have refactored api ui page, Ref: [refine api key signup page](https://github.com/fecgov/openFEC/pull/4385)
