### ISSUE TITLE
API work: automatic candidate to PAC conversion

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/openFEC#4458]
## Summary
**What we're after:**
When a candidate converts their candidate committee to a PAC, the candidate's financial information is unlinked from their candidate profile page. We need to preserve the linkage for committees who have changed mid-way through a 2 year transaction period.

In previous sprints (#4419) the database solution for flagging candidate committees that converted to a PAC and the candidate linkage was implemented. 

To update the API we must determine the endpoint where the converted committee information will be added, the front-end team must use the endpoint to retrieve:
- Candidate ID
- Committee ID
- Former committee name
- Current committee name (probably already there, but make sure)
- Two year cycle when the conversion took place

### For Grooming: Need to
- [x] Identify the endpoints the candidate/committee profile pages are using
- Candidate profile page: `/candidate/ID/history/cycle` **where `election_full=True`** (`CandidateHistoryView`, `ofec_candidate_history_mv`)
- Committee profile page: `/committee/ID/history/cycle` and  `/committee/ID/history/` (`CommitteeHistoryView`, `ofec_committee_history_mv`)

Because the link has been broken between candidate and committee, I think we need to left join the new MV on both the candidate and committee history endpoints. 

### Completion criteria
- [ ] This data (candidate ID, committee ID, former committee name, current committee name and two year cycle when the conversation took place) is available in the API 

### Related Issues
- #4456 Collect business rules for candidate to PAC conversions
- #4457 Identify historic/current cycle conversion, edge cases, and problem situations
- #4419 Database work - programmatically identify candidate committees converted to PACs

### Past Work
- original user submitted issue [#9709](https://github.com/fecgov/FEC/issues/9709) 
- RAD's workflow when a candidate converts to a PAC: https://github.com/fecgov/fec-cms/issues/3806#issuecomment-639064274
- design ticket for candidate profile page language [#3806](https://github.com/fecgov/fec-cms/issues/3806) 
- implementation of manual approach [#4292](https://github.com/fecgov/openFEC/issues/4292)

**Comment by lbeaufort** [comment]
Example output from candidate profile page for converted candidate: 

```
INFO:data.api_caller: load_first_row_data: https://fec-dev-api.app.cloud.gov/v1/candidate/P00010793/history?per_page=1
INFO:data.api_caller: load_single_type: https://fec-dev-api.app.cloud.gov/v1/candidate/P00010793/history/2020?per_page=1&election_full=True
INFO:data.api_caller: load_nested_type: https://fec-dev-api.app.cloud.gov/v1/candidate/P00010793/committees/history/2020?per_page=100&election_full=True
INFO:data.api_caller: load_first_row_data: https://fec-dev-api.app.cloud.gov/v1/candidate/P00010793/totals?per_page=1&election_full=True&cycle=2020
INFO:data.api_caller: load_first_row_data: https://fec-dev-api.app.cloud.gov/v1/candidate/P00010793/totals?per_page=1&election_full=False&cycle=2020
INFO:data.api_caller: load_candidate_statement_of_candidacy: https://fec-dev-api.app.cloud.gov/v1/filings?candidate_id=P00010793&form_type=F2
INFO:data.api_caller: load_endpoint_results: https://fec-dev-api.app.cloud.gov/v1/efile/filings?per_page=100&election_full=False&cycle=2020&min_receipt_date=10%2F02%2F2020&committee_id=P00010793
INFO:data.api_caller: load_first_row_data: https://fec-dev-api.app.cloud.gov/v1/committee/C00699090/history/2020?per_page=1
[05/Oct/2020 09:51:52] "GET /data/candidate/P00010793/ HTTP/1.1" 200 40593
```

**Comment by fecjjeng** [comment]
The following columns will be added to the ofec_committee_history_mv:

  (case when pcc.cand_id is null then false else true end)::bool) as convert_to_pac_flg,
  pcc.first_cmte_nm as former_cmte_name, 
  pcc.cand_id as former_cand_id, 
  pcc.cand_name as former_cand_name,
  pcc.candidate_election_year as former_cand_election_year  
(ofec_committee_history_mv already has the current committee_name and cycle information, no need to added these two columns)

**Comment by fecjjeng** [comment]
Currently ofec_candidate_history_mv does not involve in committee information.  

After reviewing all the endpoints that candidate profile page is calling, 
/candidate​/{candidate_id}​/committees​/history​/{cycle}​/ 
seems to be a more suitable endpoint to add this information.  So there is no need to modify the ofec_candidate_history_mv.

**Comment by fecjjeng** [comment]
It is true that the link has been broken between candidate and committee.  With modified CommitteeHistoryView, it now return the converted committee.  A sample query output is as followed for P00009092:

SELECT anon_1.ofec_committee_history_mv_tmp_jj_idx, anon_1.ofec_committee_history_mv_tmp_jj_name, anon_1.ofec_committee_history_mv_tmp_jj_committee_id, anon_1.ofec_committee_history_mv_tmp_jj_cycles, anon_1.ofec_committee_history_mv_tmp_jj_treasurer_name, anon_1.ofec_committee_history_mv_tmp_jj_treasurer_text, anon_1.ofec_committee_history_mv_tmp_jj_committee_type, anon_1.ofec_committee_history_mv_tmp_jj_committee_type_full, anon_1.ofec_committee_history_mv_tmp_jj_filing_frequency, anon_1.ofec_committee_history_mv_tmp_jj_designation, anon_1.ofec_committee_history_mv_tmp_jj_designation_full, anon_1.ofec_committee_history_mv_tmp_jj_organization_type, anon_1.ofec_committee_history_mv_tmp_jj_organization_type_full, anon_1.ofec_committee_history_mv_tmp_jj_affiliated_committee_nam_1, anon_1.ofec_committee_history_mv_tmp_jj_party, anon_1.ofec_committee_history_mv_tmp_jj_party_full, anon_1.ofec_committee_history_mv_tmp_jj_state, anon_1.ofec_committee_history_mv_tmp_jj_street_1, anon_1.ofec_committee_history_mv_tmp_jj_street_2, anon_1.ofec_committee_history_mv_tmp_jj_city, anon_1.ofec_committee_history_mv_tmp_jj_state_full, anon_1.ofec_committee_history_mv_tmp_jj_zip, anon_1.ofec_committee_history_mv_tmp_jj_candidate_ids, anon_1.ofec_committee_history_mv_tmp_jj_cycle, anon_1.ofec_committee_history_mv_tmp_jj_cycles_has_financial, anon_1.ofec_committee_history_mv_tmp_jj_last_cycle_has_financial, anon_1.ofec_committee_history_mv_tmp_jj_cycles_has_activity, anon_1.ofec_committee_history_mv_tmp_jj_last_cycle_has_activity, anon_1.ofec_committee_history_mv_tmp_jj_is_active, anon_1.ofec_committee_history_mv_tmp_jj_former_cmte_name, anon_1.ofec_committee_history_mv_tmp_jj_former_cand_id, anon_1.ofec_committee_history_mv_tmp_jj_former_cand_name, anon_1.ofec_committee_history_mv_tmp_jj_former_cand_election_yea_2, anon_1.ofec_committee_history_mv_tmp_jj_convert_to_pac_flg 
FROM 
(
	(
		SELECT DISTINCT ON (ofec_committee_history_mv_tmp_jj.committee_id) ofec_committee_history_mv_tmp_jj.idx AS ofec_committee_history_mv_tmp_jj_idx, ofec_committee_history_mv_tmp_jj.name AS ofec_committee_history_mv_tmp_jj_name, ofec_committee_history_mv_tmp_jj.committee_id AS ofec_committee_history_mv_tmp_jj_committee_id, ofec_committee_history_mv_tmp_jj.cycles AS ofec_committee_history_mv_tmp_jj_cycles, ofec_committee_history_mv_tmp_jj.treasurer_name AS ofec_committee_history_mv_tmp_jj_treasurer_name, ofec_committee_history_mv_tmp_jj.treasurer_text AS ofec_committee_history_mv_tmp_jj_treasurer_text, ofec_committee_history_mv_tmp_jj.committee_type AS ofec_committee_history_mv_tmp_jj_committee_type, ofec_committee_history_mv_tmp_jj.committee_type_full AS ofec_committee_history_mv_tmp_jj_committee_type_full, ofec_committee_history_mv_tmp_jj.filing_frequency AS ofec_committee_history_mv_tmp_jj_filing_frequency, ofec_committee_history_mv_tmp_jj.designation AS ofec_committee_history_mv_tmp_jj_designation, ofec_committee_history_mv_tmp_jj.designation_full AS ofec_committee_history_mv_tmp_jj_designation_full, ofec_committee_history_mv_tmp_jj.organization_type AS ofec_committee_history_mv_tmp_jj_organization_type, ofec_committee_history_mv_tmp_jj.organization_type_full AS ofec_committee_history_mv_tmp_jj_organization_type_full, ofec_committee_history_mv_tmp_jj.affiliated_committee_name AS ofec_committee_history_mv_tmp_jj_affiliated_committee_nam_1, ofec_committee_history_mv_tmp_jj.party AS ofec_committee_history_mv_tmp_jj_party, ofec_committee_history_mv_tmp_jj.party_full AS ofec_committee_history_mv_tmp_jj_party_full, ofec_committee_history_mv_tmp_jj.state AS ofec_committee_history_mv_tmp_jj_state, ofec_committee_history_mv_tmp_jj.street_1 AS ofec_committee_history_mv_tmp_jj_street_1, ofec_committee_history_mv_tmp_jj.street_2 AS ofec_committee_history_mv_tmp_jj_street_2, ofec_committee_history_mv_tmp_jj.city AS ofec_committee_history_mv_tmp_jj_city, ofec_committee_history_mv_tmp_jj.state_full AS ofec_committee_history_mv_tmp_jj_state_full, ofec_committee_history_mv_tmp_jj.zip AS ofec_committee_history_mv_tmp_jj_zip, ofec_committee_history_mv_tmp_jj.candidate_ids AS ofec_committee_history_mv_tmp_jj_candidate_ids, ofec_committee_history_mv_tmp_jj.cycle AS ofec_committee_history_mv_tmp_jj_cycle, ofec_committee_history_mv_tmp_jj.cycles_has_financial AS ofec_committee_history_mv_tmp_jj_cycles_has_financial, ofec_committee_history_mv_tmp_jj.last_cycle_has_financial AS ofec_committee_history_mv_tmp_jj_last_cycle_has_financial, ofec_committee_history_mv_tmp_jj.cycles_has_activity AS ofec_committee_history_mv_tmp_jj_cycles_has_activity, ofec_committee_history_mv_tmp_jj.last_cycle_has_activity AS ofec_committee_history_mv_tmp_jj_last_cycle_has_activity, ofec_committee_history_mv_tmp_jj.is_active AS ofec_committee_history_mv_tmp_jj_is_active, ofec_committee_history_mv_tmp_jj.former_cmte_name AS ofec_committee_history_mv_tmp_jj_former_cmte_name, ofec_committee_history_mv_tmp_jj.former_cand_id AS ofec_committee_history_mv_tmp_jj_former_cand_id, ofec_committee_history_mv_tmp_jj.former_cand_name AS ofec_committee_history_mv_tmp_jj_former_cand_name, ofec_committee_history_mv_tmp_jj.former_cand_election_year AS ofec_committee_history_mv_tmp_jj_former_cand_election_yea_2, ofec_committee_history_mv_tmp_jj.convert_to_pac_flg AS ofec_committee_history_mv_tmp_jj_convert_to_pac_flg 
		FROM ofec_committee_history_mv_tmp_jj 
		JOIN ofec_cand_cmte_linkage_mv 
		ON ofec_cand_cmte_linkage_mv.cmte_id = ofec_committee_history_mv_tmp_jj.committee_id 
		AND ofec_cand_cmte_linkage_mv.fec_election_yr = ofec_committee_history_mv_tmp_jj.cycle 
		WHERE ofec_cand_cmte_linkage_mv.cand_id = 'P00009092' 
		AND ofec_cand_cmte_linkage_mv.election_yr_to_be_included = 2020 
		ORDER BY ofec_committee_history_mv_tmp_jj.committee_id, 
		ofec_committee_history_mv_tmp_jj.cycle DESC
	) 
	UNION 
	(
		SELECT DISTINCT ON (ofec_committee_history_mv_tmp_jj.committee_id) ofec_committee_history_mv_tmp_jj.idx AS ofec_committee_history_mv_tmp_jj_idx, ofec_committee_history_mv_tmp_jj.name AS ofec_committee_history_mv_tmp_jj_name, ofec_committee_history_mv_tmp_jj.committee_id AS ofec_committee_history_mv_tmp_jj_committee_id, ofec_committee_history_mv_tmp_jj.cycles AS ofec_committee_history_mv_tmp_jj_cycles, ofec_committee_history_mv_tmp_jj.treasurer_name AS ofec_committee_history_mv_tmp_jj_treasurer_name, ofec_committee_history_mv_tmp_jj.treasurer_text AS ofec_committee_history_mv_tmp_jj_treasurer_text, ofec_committee_history_mv_tmp_jj.committee_type AS ofec_committee_history_mv_tmp_jj_committee_type, ofec_committee_history_mv_tmp_jj.committee_type_full AS ofec_committee_history_mv_tmp_jj_committee_type_full, ofec_committee_history_mv_tmp_jj.filing_frequency AS ofec_committee_history_mv_tmp_jj_filing_frequency, ofec_committee_history_mv_tmp_jj.designation AS ofec_committee_history_mv_tmp_jj_designation, ofec_committee_history_mv_tmp_jj.designation_full AS ofec_committee_history_mv_tmp_jj_designation_full, ofec_committee_history_mv_tmp_jj.organization_type AS ofec_committee_history_mv_tmp_jj_organization_type, ofec_committee_history_mv_tmp_jj.organization_type_full AS ofec_committee_history_mv_tmp_jj_organization_type_full, ofec_committee_history_mv_tmp_jj.affiliated_committee_name AS ofec_committee_history_mv_tmp_jj_affiliated_committee_nam_1, ofec_committee_history_mv_tmp_jj.party AS ofec_committee_history_mv_tmp_jj_party, ofec_committee_history_mv_tmp_jj.party_full AS ofec_committee_history_mv_tmp_jj_party_full, ofec_committee_history_mv_tmp_jj.state AS ofec_committee_history_mv_tmp_jj_state, ofec_committee_history_mv_tmp_jj.street_1 AS ofec_committee_history_mv_tmp_jj_street_1, ofec_committee_history_mv_tmp_jj.street_2 AS ofec_committee_history_mv_tmp_jj_street_2, ofec_committee_history_mv_tmp_jj.city AS ofec_committee_history_mv_tmp_jj_city, ofec_committee_history_mv_tmp_jj.state_full AS ofec_committee_history_mv_tmp_jj_state_full, ofec_committee_history_mv_tmp_jj.zip AS ofec_committee_history_mv_tmp_jj_zip, ofec_committee_history_mv_tmp_jj.candidate_ids AS ofec_committee_history_mv_tmp_jj_candidate_ids, ofec_committee_history_mv_tmp_jj.cycle AS ofec_committee_history_mv_tmp_jj_cycle, ofec_committee_history_mv_tmp_jj.cycles_has_financial AS ofec_committee_history_mv_tmp_jj_cycles_has_financial, ofec_committee_history_mv_tmp_jj.last_cycle_has_financial AS ofec_committee_history_mv_tmp_jj_last_cycle_has_financial, ofec_committee_history_mv_tmp_jj.cycles_has_activity AS ofec_committee_history_mv_tmp_jj_cycles_has_activity, ofec_committee_history_mv_tmp_jj.last_cycle_has_activity AS ofec_committee_history_mv_tmp_jj_last_cycle_has_activity, ofec_committee_history_mv_tmp_jj.is_active AS ofec_committee_history_mv_tmp_jj_is_active, ofec_committee_history_mv_tmp_jj.former_cmte_name AS ofec_committee_history_mv_tmp_jj_former_cmte_name, ofec_committee_history_mv_tmp_jj.former_cand_id AS ofec_committee_history_mv_tmp_jj_former_cand_id, ofec_committee_history_mv_tmp_jj.former_cand_name AS ofec_committee_history_mv_tmp_jj_former_cand_name, ofec_committee_history_mv_tmp_jj.former_cand_election_year AS ofec_committee_history_mv_tmp_jj_former_cand_election_yea_2, ofec_committee_history_mv_tmp_jj.convert_to_pac_flg AS ofec_committee_history_mv_tmp_jj_convert_to_pac_flg 
		FROM ofec_committee_history_mv_tmp_jj 
		WHERE ofec_committee_history_mv_tmp_jj.former_cand_id = 'P00009092' 
		AND ofec_committee_history_mv_tmp_jj.former_cand_election_year = 2020 
		ORDER BY ofec_committee_history_mv_tmp_jj.committee_id, 
		ofec_committee_history_mv_tmp_jj.cycle DESC
	)
) AS anon_1 
ORDER BY anon_1.ofec_committee_history_mv_tmp_jj_committee_id, 
anon_1.ofec_committee_history_mv_tmp_jj_cycle DESC

**Comment by lbeaufort** [comment]
@fecjjeng thanks for your research on this! If I'm following, this works because we aren't filtering this join to `CandidateCommitteeLink` by `P` and `A`, but if we were, the converted information might not show up?

https://github.com/fecgov/openFEC/blob/5c7b4c237849dcf36724d9071d5d11985111fc75/webservices/resources/committees.py#L193-L205

Maybe this would be a good opportunity to check/add automated tests to make sure non-P and non-A committees linked still show up. Let me know if you'd like to discuss, or if you'd like help looking at tests.

Thanks again!

**Comment by fecjjeng** [comment]
if cycle:
            # use for
            # '/committee/<string:committee_id>/history/<int:cycle>/',
            # '/candidate/<candidate_id>/committees/history/<int:cycle>/',
            if kwargs.get('election_full') and candidate_id:
                query = query.filter(
                    models.CandidateCommitteeLink.election_yr_to_be_included == cycle,
                ).order_by(
                    models.CommitteeHistory.committee_id,
                    sa.desc(models.CommitteeHistory.cycle),
                ).distinct(
                    # in same election_yr_to_be_included, remove duplicate committee
                    models.CommitteeHistory.committee_id,
                )

**Comment by fecjjeng** [comment]
In this ticket, I had added a separate query to work on the converted committees based on the ofec_pcc_to_pac_mv then union to the original query to make this endpoint include the converted committee.  The converted committees will have the extra information of the former_xxxx.  I had also added a convert_to_pac_flg, the converted committee's convert_to_pac_flg=true.

**Comment by fecjjeng** [comment]
Encounter problem during materialized view refresh:
    graph.add_edges_from([
        ('totals_combined', 'ofec_pcc_to_pac'),
        ('cand_cmte_linkage', 'ofec_pcc_to_pac'),
        ('candidate_history', 'ofec_pcc_to_pac'),
    ])

    graph.add_edge('ofec_pcc_to_pac', 'committee_history'),

*****
    NOT working
            ('totals_combined', 'ofec_pcc_to_pac'),
            ('ofec_pcc_to_pac', 'committee_history'),

	NOT WORKING neither:
            ('totals_combined', 'committee_history'),

Error message:
networkx.exception.NetworkXUnfeasible: Graph contains a cycle.

**Comment by fecjjeng** [comment]
Modified ofec_pcc_to_pac_mv definition slightly to reduce MV inter dependency:
since we only need to if these committees file financial information or not, 
no need use whole ofec_totals_combined_vw.  Take the information from the base table of ofec_totals_combined_vw
using the same criteria.  Result had been compared to make sure it is the same.
