### ISSUE TITLE
Copy 11 tables under schema mur_arch from Oracle to PG/Aurora

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4465]
Currently, all archived MURs data(11 tables and 1 procedure) is stored in oracle db, under schema: **mur_arch**, we need copy those to AWS Aurora DB and setup data syntonization.
11 tables (under schema: mur_arch):
cite
murao
murcit
murcom
murflm
murmst
murmst_bad
murrel
mursub
subjct
subjct_from_file

Ref issue: [https://github.com/fecgov/openFEC/issues/4129](https://github.com/fecgov/openFEC/issues/4129)

- [x] Create schema and all the 11 tables in Aurora postgresql databases (make sure migration file is submitted)
- [x] Initial data load into Aurora tables ( DEV, STAGE, PROD )
- [x] Put a copy of mur_arch data on google shared drive ( legal resources/mur_arch )

**Comment by fec-jli** [comment]
check the 11 tables on dev. looks good. Thank you.

**Comment by hcaofec** [comment]
Initial data has been loaded into DEV.  Loading into Stage and Prod are still pending.
After discussing with @ChingKuan, mur_arch will not be included in GoldenGate because the archived data will not be changed.

**Comment by hcaofec** [comment]
Data has been loaded into STAGE.
