### ISSUE TITLE
follow up ITS status about Leadership sponsor candidate linkage table

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4466]
ITS status:
We are 90% done with Leadership PAC, following are the pending tasks.
1)Integration testing with EFO and confirm the spec and data.
2)Create an oracle sponsor linkage table in the disclosure schema.
3.EFO and ITS should have all their work related to Leadership PACs completed before 8/18, the beginning of Sprint 13.3.

ITS will create a new linkage table (similar to candidate committee linkage table) for leadership PACs, EFO modifying specs for form 1. When a committee selects leadership PAC, it will make them enter a candidate name using a validate candidate_id lookup. EFO has done initial work and RAD is doing UAT on the form 1 entry, to make sure that works as expected.

**Completion criteria:**

- [x] Confirm that the changes that they are making is what we need to move forward with the design and implementation. Wait for ITS to confirm changes for the Leadership PAC is finished. 

Ref Issues:
[https://github.com/fecgov/openfec/issues/3433](https://github.com/fecgov/openfec/issues/3433)
[https://github.com/fecgov/fec-cms/issues/2369](https://github.com/fecgov/fec-cms/issues/2369)
[https://github.com/fecgov/openFEC/issues/3765](https://github.com/fecgov/openFEC/issues/3765)

**Comment by PaulClark2** [comment]
The leadership PAC database work was deployed to production on 7/17. See RFC #1477.

**Comment by hcaofec** [comment]
Updates: database work was not deployed yet.  Here is the first draft of the table structure:
disclosure.leadership_pac_cand_cmte_link(
                                                        sub_id             NUMBER      NOT NULL
                                                      , cand_id            VARCHAR2(9) NOT NULL
                                                      , cand_election_yr   NUMBER      NOT NULL
                                                      , fec_election_yr    NUMBER      NOT NULL
                                                      , cmte_id            VARCHAR2(9)
                                                      , cmte_tp            VARCHAR2(1)
                                                      , cmte_dsgn          VARCHAR2(1)
                                                      , linkage_type       VARCHAR2(1)
                                                      , cmte_count_cand_yr NUMBER
                                                      , efile_paper_ind    VARCHAR2(1)
                                                      , created_by         NUMBER      DEFAULT 1
                                                      , created_date       DATE        DEFAULT SYSDATE
                                                      , updated_by         NUMBER      DEFAULT 1
                                                      , updated_date       DATE        DEFAULT SYSDATE
                                                   )

**Comment by fec-jli** [comment]
Contractor's email:
As discussed earlier today, there will be 2 sources which feeds data into the Leadership PAC table:
1.       RAD entering data for the paper filings.
2.       EFO entering data for electronic filings.
We will look into the historical data to be exported to the disclosure.leadership_pac_cand_cmte_link table and get back to you.

**Comment by hcaofec** [comment]
The CAND_CMTE_LINKAGE_ALTERNATE table has been deployed to production by ITS, and data are added by RAD and webforms. 

This ticket can be closed.
