### ISSUE TITLE
Test staging environment after 7/21 and clean up old environmental variables

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4468]
- [x] After release is cut on 7/21, test staging environment for this behavior: https://github.com/fecgov/openFEC/pull/4455
- [x] Clean up old env vars in stage
- [x] After deploy on 7/28, clean up old environmental variables

|old|new|
|-|-|
|`TRUSTED_PROXY_IPS`| `FEC_API_TRUSTED_PROXY_IPS`|
|`BLOCKED_IPS`| `FEC_API_BLOCKED_IPS `|
|`DOWNLOAD_WHITELIST_API_KEY_ID `| `FEC_API_DOWNLOAD_KEY_ID`|
|`TRAFFIC_WHITELIST_API_KEY_IDS `| `FEC_API_BYPASS_RESTRICTION_API_KEY_IDS`|
|`RESTRICT_DOWNLOADS `| `FEC_API_RESTRICT_DOWNLOADS `|
|`RESTRICT_TRAFFIC`|`FEC_API_RESTRICT_TRAFFIC`|

**Comment by fec-jli** [comment]
all tasks done. close.
