### ISSUE TITLE
Identify the new ES service upgrade version 

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4474]
**What we're after:** Identify the new ES service upgrade version 

**Action items:**
- [x] Send an email to cloud.gov team

**Completion criteria:**
- [ ] Document the version and any other relevant info necessary

**Comment by pkfec** [comment]
Here is the reply for cloud.gov when i enquired about the latest ES Service:

> Hi Priya,
> 
> Yes we will be offering a new version of Elasticsearch that is backed by AWS Elasticsearch.  Currently this in development testing and we hope to have the beta open by the end of our next Sprint cycle which is July 24th.  After the beta and compliance work it would then be in GA.
> 
> As of today we are deploying in testing the most recent version of AWS Elasticsearch which is 7.4 and plan to role that version out in beta and GA.
> 
> Thanks,
> Chris

**Comment by pkfec** [comment]
Cloud.gov will be releasing Elasticsearch service v7.4 beta by end of July.
