### ISSUE TITLE
Check logs Sprint 13.1 week 2

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/openFEC#4481]
Check logs Sprint 13.1 week 2

- [x] Log review needs to be completed for sprint 13.1 week 2 per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

-  [x]   Create check logs tickets for the next sprint

**Comment by jason-upchurch** [comment]
FEC-CMS: 6

package.json: 0

requirements.txt: 6
Medium: (5 in one) Pillow vulnerabilities: fecgov/fec-cms#3886;
Medium: Cross site scripting: fecgov/fec-cms#3942;

OPEN-FEC:
package.json: 0
requirements.txt: 0
data/flyway/build.gradle: 0

FEC-EREGS:
package.json: 0
requirements.txt: 0

FEC-PATTERN-LIBRARY:
package.json: 2
- 

Cloud.gov Dashboard: 9 deployer accounts, same as last week.
Offboarding: Nothing to report
