### ISSUE TITLE
Remove 'coalesce' from Schedule B sort

### ISSUE THREAD

**Issue by dzhang-fec** [fecgov/openFEC#4491]
Summary:
Problem: This SB sql took 17+min to 45+ mins. The end users reported the slow per Paul. This sql took resource and  caused the DB auto-scaling up

Suggestion: after code tuning it is 11sec. an
Please consider to use   `order by disclosure.fec_fitem_sched_b.disb_dt DESC NULLS FIRST`,  not `coalesce(disclosure.fec_fitem_sched_b.disb_dt, CAST('9999-12-31' AS DATE))`
Execution time: 70 times faster  (17+ mins to 11 sec)

Note:
1)From @fecjjeng and @hcaofec there was a story on why we had "`CAST('9999-12-31' AS DATE))`" there for logic in the logic. This suggestion is "not" to change the logic.  We are trying to tune the sql with more efficient way `NULL FIRST/LAST`. So, the return order is 100% same with before per our testings.
So, it may has risk to change the logic for now, e.g., just remove the `CAST('9999-12-31' AS DATE))`. The suggestion here will not change the logic for sure.

```
SELECT *
FROM disclosure.fec_fitem_sched_b LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_1 ON disclosure.fec_fitem_sched_b.cmte_id = ofec_committee_history_mv_1.committee_id AND disclosure.fec_fitem_sched_b.two_year_transaction_period = ofec_committee_history_mv_1.cycle LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_2 ON disclosure.fec_fitem_sched_b.clean_recipient_cmte_id = ofec_committee_history_mv_2.committee_id AND disclosure.fec_fitem_sched_b.two_year_transaction_period = ofec_committee_history_mv_2.cycle 
WHERE disclosure.fec_fitem_sched_b.two_year_transaction_period IN (2020) AND disclosure.fec_fitem_sched_b.disb_dt >= '2019-01-01'::date AND disclosure.fec_fitem_sched_b.disb_dt <= '2020-12-31'::date AND disclosure.fec_fitem_sched_b.recipient_name_text @@ to_tsquery('2020:* & campaign:* & services:*') 
ORDER BY coalesce(disclosure.fec_fitem_sched_b.disb_dt, CAST('9999-12-31' AS DATE)) DESC, disclosure.fec_fitem_sched_b.sub_id DESC 
 LIMIT 30
```

Analysis and suggestion

1)before change:  took 17+mins
       ... ORDER BY coalesce(disclosure.fec_fitem_sched_b.disb_dt, CAST('9999-12-31' AS DATE)) DESC, 

2)after change: took 11 sec
     `...BY disclosure.fec_fitem_sched_b.disb_dt DESC nulls first, disclosure.fec_fitem_sched_b.sub_id DESC `
```
SELECT *
FROM disclosure.fec_fitem_sched_b LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_1 ON disclosure.fec_fitem_sched_b.cmte_id = ofec_committee_history_mv_1.committee_id AND disclosure.fec_fitem_sched_b.two_year_transaction_period = ofec_committee_history_mv_1.cycle LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_2 ON disclosure.fec_fitem_sched_b.clean_recipient_cmte_id = ofec_committee_history_mv_2.committee_id AND disclosure.fec_fitem_sched_b.two_year_transaction_period = ofec_committee_history_mv_2.cycle 
WHERE disclosure.fec_fitem_sched_b.two_year_transaction_period IN (2020) AND disclosure.fec_fitem_sched_b.disb_dt >= '2019-01-01'::date AND disclosure.fec_fitem_sched_b.disb_dt <= '2020-12-31'::date AND disclosure.fec_fitem_sched_b.recipient_name_text @@ to_tsquery('2020:* & campaign:* & services:*') 
ORDER BY disclosure.fec_fitem_sched_b.disb_dt DESC nulls first, disclosure.fec_fitem_sched_b.sub_id DESC 
 LIMIT 30
```

Both are return 4 rows
 
![image](https://user-images.githubusercontent.com/62447258/88010912-00067980-cae4-11ea-8441-5880ddb7bf12.png)

Return recordset and order are same
the first 10 is null
![image](https://user-images.githubusercontent.com/62447258/87998242-5c0dd580-cac5-11ea-9d55-925bd7785f26.png)

Another SB sqls
`2020-07-21 03:42:43.944562+00,02:38:04.638485`
```
SELECT *
FROM disclosure.fec_fitem_sched_b LEFT OUTER JOIN ofec_committee_history_mv AS o
fec_committee_history_mv_1 ON disclosure.fec_fitem_sched_b.cmte_id = ofec_commit
tee_history_mv_1.committee_id AND disclosure.fec_fitem_sched_b.two_year_transact
ion_period = ofec_committee_history_mv_1.cycle LEFT OUTER JOIN ofec_committee_hi
story_mv AS ofec_committee_history_mv_2 ON disclosure.fec_fitem_sched_b.clean_re
cipient_cmte_id = ofec_committee_history_mv_2.committee_id AND disclosure.fec_fi
tem_sched_b.two_year_transaction_period = ofec_committee_history_mv_2.cycle
WHERE disclosure.fec_fitem_sched_b.two_year_transaction_period IN (2020) AND dis
closure.fec_fitem_sched_b.disb_dt >= '2019-01-01'::date AND disclosure.fec_fitem
_sched_b.disb_dt <= '2020-12-31'::date AND disclosure.fec_fitem_sched_b.recipien
t_name_text @@ to_tsquery('2020:* & campaign:* & services:*')
ORDER BY coalesce(disclosure.fec_fitem_sched_b.disb_dt, CAST('9999-12-31' AS DAT
E)) DESC, disclosure.fec_fitem_sched_b.sub_id DESC
 LIMIT 30"
```

**Technical considerations**
- [ ] Could we remove these indices? https://github.com/fecgov/openFEC/issues/2923

**Comment by dzhang-fec** [comment]
same sqls happens again and again
![image](https://user-images.githubusercontent.com/62447258/88299087-f5a8d300-cccf-11ea-8daf-ef2085fdd2f6.png)

**Comment by lbeaufort** [comment]
Here's a detailed wiki on the history behind these expression-based sorts: https://github.com/fecgov/openFEC/wiki/Enabling-an-expression-based-sort

**Comment by lbeaufort** [comment]
Next steps: 
- @dzhang-fec will research/add composite index (date, sub_id) for "default load" of 2020, and other coalesce indexes (See #2923) in `dev` so we can test
- @lbeaufort will test afterwards, track here: https://docs.google.com/spreadsheets/d/1J5QK4mw7HXbMnaDV_ClCGWEgbbI3VZZhXDqmjIFwBqI/edit#gid=0
- @lbeaufort will locust test

**Comment by dzhang-fec** [comment]
ched_A need this too2021-01-13 17:48:02.286669+00,00:05:00.56684,fec_api,"SELECT disclosure.fec_fitem_sched_a.cmte_id AS disclosure_fec_fitem_sched_a_cmte_id, disclosure.fec_fitem_sched_a.rpt_yr AS disclosure_fec_fitem_sched_a_rpt_yr, disclosure.fec_fitem_sched_a.rpt_tp AS disclosure_fec_fitem_sched_a_rpt_tp, disclosure.fec_fitem_sched_a.image_num AS disclosure_fec_fitem_sched_a_image_num, disclosure.fec_fitem_sched_a.line_num AS disclosure_fec_fitem_sched_a_line_num, disclosure.fec_fitem_sched_a.tran_id AS disclosure_fec_fitem_sched_a_tran_id, disclosure.fec_fitem_sched_a.file_num AS disclosure_fec_fitem_sched_a_file_num, disclosure.fec_fitem_sched_a.cmte_nm AS disclosure_fec_fitem_sched_a_cmte_nm, disclosure.fec_fitem_sched_a.entity_tp AS disclosure_fec_fitem_sched_a_entity_tp, disclosure.fec_fitem_sched_a.entity_tp_desc AS disclosure_fec_fitem_sched_a_entity_tp_desc, disclosure.fec_fitem_sched_a.contbr_id AS disclosure_fec_fitem_sched_a_contbr_id, disclosure.fec_fitem_sched_a.contbr_prefix AS disclosure_fec_fitem_sched_a_contbr_prefix, disclosure.fec_fitem_sched_a.contbr_nm AS disclosure_fec_fitem_sched_a_contbr_nm, disclosure.fec_fitem_sched_a.cmte_tp AS disclosure_fec_fitem_sched_a_cmte_tp, disclosure.fec_fitem_sched_a.org_tp AS disclosure_fec_fitem_sched_a_org_tp, disclosure.fec_fitem_sched_a.cmte_dsgn AS disclosure_fec_fitem_sched_a_cmte_dsgn, disclosure.fec_fitem_sched_a.contbr_nm_first AS disclosure_fec_fitem_sched_a_contbr_nm_first, disclosure.fec_fitem_sched_a.contbr_m_nm AS disclosure_fec_fitem_sched_a_contbr_m_nm, disclosure.fec_fitem_sched_a.contbr_nm_last AS disclosure_fec_fitem_sched_a_contbr_nm_last, disclosure.fec_fitem_sched_a.contbr_suffix AS disclosure_fec_fitem_sched_a_contbr_suffix, disclosure.fec_fitem_sched_a.contbr_st1 AS disclosure_fec_fitem_sched_a_contbr_st1, disclosure.fec_fitem_sched_a.contbr_st2 AS disclosure_fec_fitem_sched_a_contbr_st2, disclosure.fec_fitem_sched_a.contbr_city AS disclosure_fec_fitem_sched_a_contbr_city, disclosure.fec_fitem_sched_a.contbr_st AS disclosure_fec_fitem_sched_a_contbr_st, disclosure.fec_fitem_sched_a.contbr_zip AS disclosure_fec_fitem_sched_a_contbr_zip, disclosure.fec_fitem_sched_a.contbr_employer AS disclosure_fec_fitem_sched_a_contbr_employer, disclosure.fec_fitem_sched_a.contbr_occupation AS disclosure_fec_fitem_sched_a_contbr_occupation, disclosure.fec_fitem_sched_a.clean_contbr_id AS disclosure_fec_fitem_sched_a_clean_contbr_id, disclosure.fec_fitem_sched_a.receipt_tp AS disclosure_fec_fitem_sched_a_receipt_tp, disclosure.fec_fitem_sched_a.receipt_tp_desc AS disclosure_fec_fitem_sched_a_receipt_tp_desc, disclosure.fec_fitem_sched_a.receipt_desc AS disclosure_fec_fitem_sched_a_receipt_desc, disclosure.fec_fitem_sched_a.memo_cd AS disclosure_fec_fitem_sched_a_memo_cd, disclosure.fec_fitem_sched_a.memo_cd_desc AS disclosure_fec_fitem_sched_a_memo_cd_desc, disclosure.fec_fitem_sched_a.contb_receipt_dt AS disclosure_fec_fitem_sched_a_contb_receipt_dt, disclosure.fec_fitem_sched_a.contb_receipt_amt AS disclosure_fec_fitem_sched_a_contb_receipt_amt, disclosure.fec_fitem_sched_a.contb_aggregate_ytd AS disclosure_fec_fitem_sched_a_contb_aggregate_ytd, disclosure.fec_fitem_sched_a.cand_id AS disclosure_fec_fitem_sched_a_cand_id, disclosure.fec_fitem_sched_a.cand_nm AS disclosure_fec_fitem_sched_a_cand_nm, disclosure.fec_fitem_sched_a.cand_nm_first AS disclosure_fec_fitem_sched_a_cand_nm_first, disclosure.fec_fitem_sched_a.cand_nm_last AS disclosure_fec_fitem_sched_a_cand_nm_last, disclosure.fec_fitem_sched_a.cand_m_nm AS disclosure_fec_fitem_sched_a_cand_m_nm, disclosure.fec_fitem_sched_a.cand_prefix AS disclosure_fec_fitem_sched_a_cand_prefix, disclosure.fec_fitem_sch
    
FROM disclosure.fec_fitem_sched_a LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_1 ON disclosure.fec_fitem_sched_a.cmte_id = ofec_committee_history_mv_1.committee_id AND disclosure.fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_1.cycle LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_2 ON disclosure.fec_fitem_sched_a.clean_contbr_id = ofec_committee_history_mv_2.committee_id AND disclosure.fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_2.cycle
WHERE disclosure.fec_fitem_sched_a.is_individual = true AND disclosure.fec_fitem_sched_a.cmte_id IN ('C00703975') AND disclosure.fec_fitem_sched_a.two_year_transaction_period IN (2020) AND disclosure.fec_fitem_sched_a.contb_receipt_dt >= '2020-06-01'::date AND disclosure.fec_fitem_sched_a.contb_receipt_dt <= '2020-07-31'::date AND **(**coalesce**(disclosure.fec_fitem_sched_a.contb_receipt_dt, '9999-12-31'::date),** disclosure.fec_fitem_sched_a.sub_id) < ('2020-06-21'::date, 4072120201793236081) ORDER BY disclosure.fec_fitem_sched_a.contb_receipt_dt DESC, disclosure.fec_fitem_sched_a.sub_id DESC
 LIMIT 100"
