### ISSUE TITLE
Add TOS and AUP links to the openFEC swagger 

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4511]
**What we're after:** 
We need to include links to the Terms of Service and Acceptable Use Policy to the openFEC swagger. 

User story: As an API user, it's important that I understand if any limitations to using FEC data exist in order to use it effectively and understand potential blockers before I hit them. 

TOS: https://github.com/fecgov/FEC/blob/master/TERMS-OF-SERVICE.md
AUP: https://github.com/fecgov/FEC/blob/master/ACCEPTABLE-USE-POLICY.md

**Completion criteria:**
- [x] Updated language is drafted for the swagger page to include the TOS and AUP
- [x] Updated language is added to the swagger page

**Comment by JonellaCulmer** [comment]
@dorothyyeager @kathycarothers and I drafted the below language for the swagger page. Does this need to be reviewed by OGC @PaulClark2?

It should be formatted as it appears below. We want to introduce a header for the section called "Getting started with the openFEC API"

Other changes have been made to this text, so please use the below text to replace the 4th paragraph. It is now two paragraphs and a new header.

**Getting started with the openFEC API**
 If you would like to use the FEC's API programmatically, you can sign up for your own API key using our form. Alternatively, you can still try out our API without an API key by using the web interface and using DEMO_KEY. Note that when you use the openFEC API you are subject to the [Terms of Service](https://github.com/fecgov/FEC/blob/master/TERMS-OF-SERVICE.md) and [Acceptable Use policy](https://github.com/fecgov/FEC/blob/master/ACCEPTABLE-USE-POLICY.md).

Signing up for an API key will enable you to place up to 1,000 calls an hour. Each call is limited to 100 results per page. You can email questions, comments or a request to get a key for 120 calls per minute to APIinfo@fec.gov. You can also ask questions and discuss the data in the [FEC data Google Group](https://groups.google.com/forum/#!forum/fec-data). API changes will also be added to this group in advance of the change.

**Comment by PaulClark2** [comment]
@JonellaCulmer this does not need to go to OGC. 

Does it make sense to change `120 calls per minute` to `7,600 calls per hour (120 calls per minute)` to make it parallel with the first sentence? I'm perfectly okay with leaving the text as it is.

**Comment by JonellaCulmer** [comment]
@PaulClark2 I'll make that change. Thank you. 

Final language: 

**Getting started with the openFEC API**
 If you would like to use the FEC's API programmatically, you can sign up for your own API key using our form. Alternatively, you can still try out our API without an API key by using the web interface and using DEMO_KEY. Note that when you use the openFEC API you are subject to the [Terms of Service](https://github.com/fecgov/FEC/blob/master/TERMS-OF-SERVICE.md) and [Acceptable Use policy](https://github.com/fecgov/FEC/blob/master/ACCEPTABLE-USE-POLICY.md).

Signing up for an API key will enable you to place up to 1,000 calls an hour. Each call is limited to 100 results per page. You can email questions, comments or a request to get a key for 7,600 calls per hour (120 calls per minute) to APIinfo@fec.gov. You can also ask questions and discuss the data in the [FEC data Google Group](https://groups.google.com/forum/#!forum/fec-data). API changes will also be added to this group in advance of the change.

**Comment by JonellaCulmer** [comment]
https://github.com/fecgov/openFEC/blob/edceefff496e8dcb2a078c959aeb20f054298978/webservices/docs.py

**Comment by jason-upchurch** [comment]
<img width="857" alt="Screen Shot 2020-07-31 at 2 48 04 PM" src="https://user-images.githubusercontent.com/49287206/89067236-e1eb1580-d33c-11ea-8efe-d7b0ad10aca3.png">
@JonellaCulmer does the "final text" you link in https://github.com/fecgov/openFEC/issues/4511#issuecomment-665766183 _replace_ the text I included in screenshot above entirely? If not, do you mind indicating where it fits? Thanks!

**Comment by JonellaCulmer** [comment]
@jason-upchurch It does not replace everything. The new text will replace the fourth paragraph, "If you would like...advance of the change." The new header can just be bolded text on a separate line. Please see the below image. 

<img width="669" alt="Screen Shot 2020-07-31 at 3 00 38 PM" src="https://user-images.githubusercontent.com/31663028/89068134-a2252d80-d33e-11ea-99d6-50afba9efd90.png">
