### ISSUE TITLE
Check logs Sprint 13.4 week 2 (9/9/20)

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4517]
Check logs Sprint 13.4 week 2

- [ ] Log review needs to be completed for sprint 13.4 week 2 per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)
- [ ] Enter tickets for 13.5

**Comment by lbeaufort** [comment]
**FEC-CMS:**
- package.json: 1
New vulnerability: https://github.com/fecgov/fec-cms/issues/4026
- requirements.txt: 1
New vulnerability (2 vulnerabilities): https://github.com/fecgov/fec-cms/issues/4027

**OPEN-FEC:**
- package.json: 0
- requirements.txt: 2
  - Carryover vulnerability:
    - High: Directory Traversal (Due 10/02/2020)
      https://github.com/fecgov/fec-cms/issues/4015
  - Carryover vulnerability:
    - Medium: Denial of Service (DoS)  (Due 10/25/2020)
      https://github.com/fecgov/openFEC/issues/4588
- data/flyway/build.gradle: 0

**FEC-EREGS:**
- package.json: 0
- requirements.txt: 0

**FEC-PATTERN-LIBRARY:**
- package.json: 0

**Cloud.gov Dashboard:** 
9 deployer accounts, same as last week.

**Offboarding:**
Nothing to report
