### ISSUE TITLE
[Snyk: High Severity] Arbitrary Code Execution (Due: 09/04/2020)(Block?)

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4541]
[https://app.snyk.io/vuln/SNYK-PYTHON-PYYAML-590151](https://app.snyk.io/vuln/SNYK-PYTHON-PYYAML-590151)

Remediation:
There is no fixed version for pyyaml

**Comment by lbeaufort** [comment]
This is a duplicate of https://github.com/fecgov/openFEC/issues/4525, where I documented my research that we aren't vulnerable because we're not executing untrusted YAML. I've ignored the issue in Snyk and included my explanation there.
