### ISSUE TITLE
Remove /communication-costs/ endpoint

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4546]
### Summary
`/communication-costs/` was deprecated and replaced by `/communication_costs/` because the pagination was incorrect and the resultset pagination was  not as  specified.

### Technical Guidance
- The files changed to add the new `/communication_costs/` replacement endpoint are at: https://github.com/fecgov/openFEC/pull/4568/files
- we'll need to refactor for the removal with the idea being:
  - remove the code linked above for the new endpoint
  - replace the `paging_schema` for the "old" endpoint with OffsetPageSchema
  - rename the `/communication-costs/` in rest.py to `/communication_costs/`
  - in `test_costs.py` replace `CommunicationCostViewOffset` with CommunicationCostView and remove import

### Action items
- [x] verify that `/communication_costs/` (new endpoint) is working
- [x] verify that all related cms work is done
- [x] verify that all related openFEC work is done
- [x] verify that it has been 30 days since the last email/deprecation notice to api users
    - [x] ONLY AFTER THAT TIME: remove `/communication-costs/` (old endpoint)
    - [x] Remove deprecation notice from communication_costs endpoint

### Completion criteria
- [x] `/communication-costs/` endpoint is removed

**Comment by patphongs** [comment]
Moving this forward since we still need to make the change in the CMS

**Comment by jason-upchurch** [comment]
> Moving this forward since we still need to make the change in the CMS

@patphongs just in case it's not clear, this issue is not a blocker to the CMS issue which needs to happen _before_the removal. The CMS issue is a blocker to this issue.
