### ISSUE TITLE
Research possible performance improvements for user downloads

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4552]
**What we're after:**
Downloads can cause performance degradation, so we should look for opportunities to improve performance. One idea, per @dzhang-fec it looks we might not be using `COPY` to download data to `csv`, which may be an opportunity to improve download performance.  

**Techical considerations:**
- [x] Is this working the way we expect? Test locally. We are using `posgres_copy`'s `copy_to` command: https://github.com/diogob/postgres-copy. On our own local `cfdm_test` database,  `pg_stat_activity` table, we should see something like this: 
```
COPY (SELECT "users".* FROM "users" ) TO '/tmp/users.csv' WITH DELIMITER ',' CSV HEADER
```
...but there's no evidence of `COPY` in the database logs, so it's possible this isn't working the way we expect.

Current logic: 
https://github.com/fecgov/openFEC/blob/ca87dc2af9d8c6c98f9b6699805a3681d85532bc/webservices/tasks/download.py#L126-L139

**Completion criteria:**
- [x] Compile research to help us to better understand download mechanisms
- [ ] Create followup tickets to implement improvements. In followup ticket, must include locust testing as action item.

**Comment by dzhang-fec** [comment]
Thank you so much for the review and help @lbeaufort 
 COPY (SELECT "users".* FROM "users" ) TO stdout WITH DELIMITER ',' CSV HEADER" |gzip >/tmp/users.csv.gz

**Comment by dzhang-fec** [comment]
1)Our current Aurora log is set to tracing any DDL incl. this COPY.

**Comment by hcaofec** [comment]
Tests were done through dev website and "COPY (SELECT disclosure.fec_fitem_sched_a.cmte_id AS committee_id....." was captured in pg_stat_activity table.

Test link:
https://dev.fec.gov/data/receipts/?data_type=processed&committee_id=C00401224&two_year_transaction_period=2022&min_date=01%2F01%2F2021&max_date=12%2F31%2F2022&contributor_state=CA&min_amount=30

pg_stat_activity:
<img width="865" alt="Screen Shot 2021-08-09 at 1 14 31 PM" src="https://user-images.githubusercontent.com/24396726/128746614-2bd03bfc-a32e-4bd8-9115-cdf86ddf8d67.png">

**Comment by hcaofec** [comment]
"copy(select....)" statements were also found in production database log.
<img width="1116" alt="Screen Shot 2021-08-09 at 2 25 44 PM" src="https://user-images.githubusercontent.com/24396726/128757626-496941f9-db1f-4c55-b37e-19ff62c01378.png">

**Comment by hcaofec** [comment]
The above findings confirm that posgres_copy's copy_to command is working as we expected.
