### ISSUE TITLE
Missing data from bulk data files

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4553]
Reported to the webmanager inbox: 

> I am writing to inform you that the Bulk 2019-2020 committee to committee transaction data is not current. For most of the committees, the latest reported transaction in the bulk data is March 2020 -- even though disbursements up to June are available in their individual committee page. 

> For example, I'm looking at CMTE_ID number C00312777

> When I download the bulk data and check to see how much they spent, I get north of $200,000 with the latest transaction being December 2019. When I look at their individual profile on the FEC website, they have spent more than $900,000. 

> Do you know when the figures will be updated?

In a follow-up email I asked which files were used and this is how the user replied:
> Both itpas2.txt and itoth.txt

**Comment by fecjjeng** [comment]
The logic to generate the bulk download file itoth.txt file is mainly filtered by transaction type.  
For the itoth.txt, the transaction type included are:
transaction_tp IN ('13','20','29','15J','15Z','16C','16F','16G','16R','17R','17Z','18G','18J','18K','18U',
                           '19J','20C','20F','20G','20R','22H','22Z','23Y','24A','24C','24E','24F','24G','24H',
                           '24K','24N','24P','24R','24U','24Z','10J','11J','30F','30G','30J','30K','31F','31G',
                           '31J','31K','32F','32G','32J','32K','40Z','41Z','42Z','40','41','42' )

The entries included for C00312777 that are in this file has the 24K, 24Z, and 22Z.  The latest entries are from 2020/06/29.  This is from their latest report (2020, Q2).  The total transaction_amt for this committee_id in fec cycle 2020 is $446107

CMTE_ID   TRA  MAX(TRANSACTION_DT)      TRANSACTION_AMT
--------- --- -------------------- --------------------
C00312777 24K             20200629               439550
C00312777 24Z             20191206                 1292
C00312777 22Z             20200501                 5265

**Comment by fecjjeng** [comment]
For the web site, it include all disbursement regardless of the transaction code, which will bring the total to $2133994.25:

CMTE_ID   TRA  MAX(TRANSACTION_DT)      TRANSACTION_AMT
--------- --- -------------------- --------------------
C00312777 15              20200630           1179228.16
C00312777 22Z             20200501              5265.13
C00312777 24K             20200629               439550
C00312777 24Z             20191206              1293.71
C00312777                 20200629            508657.25

**Comment by fecjjeng** [comment]
For the web site, it include all disbursement regardless of the transaction code, which will bring the total to $2133994.25:

CMTE_ID TRA MAX(TRANSACTION_DT) TRANSACTION_AMT

C00312777 15   20200630 1179228.16
C00312777 22Z 20200501 5265.13
C00312777 24K 20200629 439550
C00312777 24Z 20191206 1293.71
C00312777        20200629 508657.25

**Comment by fecjjeng** [comment]
However, if restricted to Line_num=23, it will bring to a total number ($443608.84)  that is very close to the number in the itoth.txt file.

C00312777	22Z	20190424	265.13
C00312777	24K	20200629	437050
C00312777	24Z	20191206	1293.71
C00312777		20200515	5000

**Comment by fecjjeng** [comment]
The logic to generate the bulk download file itpas2 file is also mainly filtered by transaction type, it is a much smaller set of included transaction type.
For the itpas2, the transaction type included are:
transaction_tp IN ('24A','24C','24E','24F','24H','24K','24N','24P','24R','24Z')
It also checked if the other_id is H/S/P and cmte_dsgn is P/A.

**Comment by fecjjeng** [comment]
While web site provide all disbursement data, both itoth.txt and itpas2.txt are more specific data sets serve for their purpose, not the data is missing.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Do you mind confirming the above information regarding this requestor's question?

cc: @fecjjeng

**Comment by PaulClark2** [comment]
@JonellaCulmer The sum of the transactions included in the bulk data files rarely equal the amount disclosed on the report or the amount presented on our website. The bulk data files only contain categorized (coded) itemized transactions, expect for operating expenditures. The operating expenditures file (oppexp) contains uncategorized itemized expenditures. We generally do not categorize operating expenditures. Generally, receipts from a single source or disbursements to a single source in access of $200.00 must be itemized. There a few exceptions where a transaction of any amount much be itemized.

**Comment by PaulClark2** [comment]
INDIV, ITPAS2, ITOTH and OPPEXP are updated weekly on Sunday.
