### ISSUE TITLE
Update circle ci python image to be consistent with runtime version

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4560]
### Summary
Current runtime environment is 3.7.8 as specified by 3.7.x in runtime.txt. However, current circle ci image is 3.7.4 per .config.yml.

Let's make these consistent so that the tests run are with the same version as the runtime environment for our app.

### Completion criteria
- [ ] runtime versions are the same

**Comment by patphongs** [comment]
Closing in favor of: https://github.com/fecgov/openFEC/issues/4425
