### ISSUE TITLE
Finalize a SQL query that captures instances of PCC to PAC Conversions

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/openFEC#4561]
### Summary
When a candidate converts their candidate committee to a PAC, the candidate's financial information is unlinked from their candidate profile page. We need to preserve the linkage for committees who have changed mid-way through a 2 year transaction period.

The business rules that lead to the candidate's financial totals being unlinked from the candidate profile pages were documents in previous work:

- [document](https://docs.google.com/document/d/1eZs9jDOkYLiJsARp0SIcaLJA4TtEGHxWeP5OO3wJ_7U/edit?usp=sharing)
- [flow chart](https://docs.google.com/drawings/d/1_NrbiNVTPhyrQNdLwTCuKI3MER69iQq4rrZl4vKyIos/edit?usp=sharing)

**What we're after:**
A SQL query that captures candidate committee conversions from PCC to PAC that occur before the end of the two year period in which the candidate is running. Specifically, SQL that captures instances in which it will be informative for FEC.gov to add a clarifying messages to (1) the candidate profile profile page of the committee's former authorizing candidate and (2) the committee profile page of the newly converted PAC. Data needed to be captured in the query:

- Two election period in which the conversion takes place
- Committee ID of the PAC (formerly the candidate committee)
- PAC Name
- former name of the candidate committee prior to conversion
- Candidate ID of the authorizing candidate prior to conversion
- Name of the authorizing candidate prior to conversion

**Completion criteria:**
- [x] Document the SQL query
- [x] If needed, create a ticket for 13.3/13.4 to bring in any additional tables into `postgres` (migration file,  initial load and golden gate transfer work)

**Previous work:**
Collect business rules on candidate conversion to PAC ([cms # 3895](https://github.com/fecgov/fec-cms/issues/3895))
Compile examples of conversions ([cms # 3898](https://github.com/fecgov/fec-cms/issues/3898))

**Comment by bmathesonFEC** [comment]
Existing efforts to capture the logic in SQL:

Laura's initial effort, "casts net too wide": https://github.com/fecgov/fec-cms/issues/3895#issuecomment-663715727

```
select dim_cmte.cmte_id, min(dim_cmte.cmte_nm), max(dim_cmte.cmte_nm), link.cand_id, max(filed_cmte_tp), min(create_date), min(cand_election_yr)
--select dim_cmte.cmte_id, dim_cmte.cmte_nm, link.cand_id, cand_election_yr, filed_cmte_tp, filed_cmte_dsgn, create_date, filed_cmte_tp_desc, *
-- Any non-candidate committee that's linked to a candidate
from disclosure.dim_cmte_ie_inf dim_cmte
join disclosure.cand_cmte_linkage link using (cmte_id)
where filed_cmte_tp not in ('H', 'S', 'P', 'U', 'Y', 'Q', 'X') 
--and filed_cmte_dsgn not in ('J', 'X', 'P', 'A') 
and filed_cmte_dsgn in ('U','B','D')
and create_date < date(concat('12/31/',cast(cand_election_yr as varchar))) 
and link.linkage_type = 'U' -- what's this?
-- see if they ever had a possible PCC that raised money this cycle 
-- might include JFC's but that seems ok
and cand_id in (
    select link.cand_id
    from disclosure.dim_cmte_ie_inf dim_cmte
    join disclosure.cand_cmte_linkage link using (cmte_id)
    join ofec_totals_combined_vw totals 
    on totals.committee_id = dim_cmte.cmte_id and totals.cycle=cand_election_yr
    where filed_cmte_tp in ('H', 'S', 'P')
    -- exclude J's
    and create_date < date(concat('12/31/',cast(cand_election_yr as varchar)))
    and (totals.receipts > 0 or totals.disbursements > 0)
)
-- look up known examples
-- and (dim_cmte.cmte_id IN ('C00291955','C00693044', 'C00697441', 'C00634212', 'C00691790', 'C00697128', 'C00698894', 'C00727156', 'C00745752', 'C00503094')
-- or link.cand_id='H2PA18143')

GROUP BY dim_cmte.cmte_id, link.cand_id
```

**Comment by bmathesonFEC** [comment]
Jean's test on the candidate-committee-linkage table to identify conversion (https://github.com/fecgov/fec-cms/issues/3895#issuecomment-673899072)

> 
> As I mentioned in the discussion this afternoon, this is a simple test I did with the cand_cmte_linkage table that captures the change of cmte_tp within the same fec_election_yr for a cmte_id.  It can be modified to capture the change of cmte_dsgn as well.
> 
> create trigger tri_bu_cand_cmte_linkage before
> update
>     on
>     disclosure.cand_cmte_linkage for each row execute procedure disclosure.cand_cmte_linkage_upd();
> 
> CREATE OR REPLACE FUNCTION disclosure.cand_cmte_linkage_upd()
>  RETURNS trigger
>  LANGUAGE plpgsql
> AS $function$
> begin
> 	if (new.fec_election_yr = old.fec_election_yr) and (new.cmte_tp <> old.cmte_tp) then
> 
> 	insert into disclosure.cand_cmte_linkage_audit 
> 	(cmte_id, cand_id_old, cand_id_new, cmte_tp_old, cmte_tp_new, cmte_dsgn_old, cmte_dsgn_new, fec_election_yr)
> 	values
> 	(new.cmte_id, old.cand_id, new.cand_id, old.cmte_tp, new.cmte_tp, old.cmte_dsgn, new.cmte_dsgn, old.fec_election_yr);
> 
> 	end if;
> return old;
> END;
> $function$
> ;
> 
> ![image](https://user-images.githubusercontent.com/24943130/90217966-991d6d00-ddd0-11ea-8268-57011b005261.png)
>

**Comment by bmathesonFEC** [comment]
Jean's follow up comment w/ code using dim_cmte table (https://github.com/fecgov/fec-cms/issues/3895#issuecomment-673901762):

```

After taking a closer look at the dim_cmte_ie_inf table, it may be enough information from this table that the above trigger is not be necessary.  
Following is my first try to check the PCC to non-PCC change from dim_cmte_ie_inf table, join the ofec_cand_cmte_linkage_mv to get the cand_id.  it will need to be verified on some known cases to see if it capture the changes we desired.

WITH DIM_CMTE AS
(	
	-- postgresql syntax
	SELECT CMTE_ID, CMTE_NM, FILED_CMTE_TP, FILED_CMTE_DSGN, CREATE_DATE, TO_CHAR(CREATE_DATE, 'YYYY')::numeric +MOD(TO_CHAR(CREATE_DATE, 'YYYY')::numeric , 2) FEC_ELECTION_YR
	FROM DISCLOSURE.DIM_CMTE_IE_INF
	ORDER BY CMTE_ID, CREATE_DATE
)
, LATEST_ROW_IN_CYCLE AS 
(
	SELECT CMTE_ID, MAX(CREATE_DATE) LAST_CHANGE_DATE, FEC_ELECTION_YR 
	FROM DIM_CMTE 
	GROUP BY CMTE_ID, FEC_ELECTION_YR
)
, CHANGE_CAPTURE AS 
(
	SELECT DIM_CMTE.CMTE_ID, DIM_CMTE.CMTE_NM, DIM_CMTE.FILED_CMTE_TP, DIM_CMTE.FILED_CMTE_DSGN, DIM_CMTE.CREATE_DATE 
	, FIRST_VALUE(DIM_CMTE.CMTE_NM) OVER (PARTITION BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR order by CREATE_DATE) AS FIRST_CMTE_NM
	, LAST_VALUE(DIM_CMTE.CMTE_NM) OVER (PARTITION BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR order by CREATE_DATE) AS LATEST_CMTE_NM
	, FIRST_VALUE(DIM_CMTE.FILED_CMTE_TP) OVER (PARTITION BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR order by CREATE_DATE) AS FIRST_CMTE_TP
	, LAST_VALUE(DIM_CMTE.FILED_CMTE_TP) OVER (PARTITION BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR order by CREATE_DATE) AS LATEST_CMTE_TP
	, FIRST_VALUE(DIM_CMTE.FILED_CMTE_DSGN) OVER (PARTITION BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR order by CREATE_DATE) AS FIRST_CMTE_DSGN
	, LAST_VALUE(DIM_CMTE.FILED_CMTE_DSGN) OVER (PARTITION BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR order by CREATE_DATE) AS LATEST_CMTE_DSGN
	, DIM_CMTE.FEC_ELECTION_YR
	FROM DIM_CMTE 
	ORDER BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR, DIM_CMTE.CREATE_DATE
)
SELECT CHANGE_CAPTURE.CMTE_ID, CCL.CAND_ID, CHANGE_CAPTURE.FEC_ELECTION_YR, CHANGE_CAPTURE.FIRST_CMTE_NM, CHANGE_CAPTURE.LATEST_CMTE_NM, CHANGE_CAPTURE.FIRST_CMTE_TP, CHANGE_CAPTURE.LATEST_CMTE_TP,CHANGE_CAPTURE. FIRST_CMTE_DSGN, CHANGE_CAPTURE.LATEST_CMTE_DSGN
FROM CHANGE_CAPTURE
JOIN LATEST_ROW_IN_CYCLE 
ON CHANGE_CAPTURE.CMTE_ID = LATEST_ROW_IN_CYCLE.CMTE_ID 
AND CHANGE_CAPTURE.FEC_ELECTION_YR = LATEST_ROW_IN_CYCLE.FEC_ELECTION_YR 
AND CHANGE_CAPTURE.CREATE_DATE = LATEST_ROW_IN_CYCLE.LAST_CHANGE_DATE
join ofec_cand_cmte_linkage_mv ccl 
on ccl.cmte_id = change_capture.cmte_id and ccl.fec_election_yr = change_capture.fec_election_yr
WHERE
(
(CHANGE_CAPTURE.FIRST_CMTE_TP IN ('H','P','S') AND CHANGE_CAPTURE.LATEST_CMTE_TP NOT IN ('H','P','S'))
OR (CHANGE_CAPTURE.FIRST_CMTE_DSGN IN ('P','A') AND CHANGE_CAPTURE.LATEST_CMTE_DSGN NOT IN ('P','A'))
)
-- if want to filter out the JFC
-- and (CHANGE_CAPTURE.FIRST_CMTE_DSGN not IN ('J') AND CHANGE_CAPTURE.LATEST_CMTE_DSGN NOT IN ('J'))
ORDER BY CHANGE_CAPTURE.CMTE_ID, CHANGE_CAPTURE.FEC_ELECTION_YR

```

**Comment by fecjjeng** [comment]
Additional information for PCC to PAC conversion from Paul:

We have problems automatically updating committee type and designation based on a Form 1 amendment because our Form 1 is so badly designed. There is some lightweight logic that tries to determine the type but in most cases it cannot. The default behavior is to pull the current committee type forward so that committee type is not null.
Line 5 box A can be committee types “H,” “S” or “P.”
Line 5 box B can be committee types “H,” “S” or “P.”
Line 5 box C is committee type “U.”
Line 5 box D can be committee types “X” or “Y.”
Line 5 box E can be committee types “N” or “Q.”
Line 5 box F can be committee types “N,” “Q,” “O,” “V” or “W.”
Line 5 box G can be committee types “N,” “Q,” “H,” “S” or “P” (unlikely) and since we don’t have regs possibly “O,” “V” or “W.”
Line 5 box H can be committee types “N,” “Q,” “O,” “H,” “S” or “P” (unlikely) and since we don’t have regs possibly “O,” “V” or “W.”

We should still be able to put in an automatic identifier. It just means that the trigger for the identifier will be delayed until the committee type is changed. For example, F1 amendment that changes committee type is filed on Monday. Someone at FEC notices on Wednesday and enters a F1 change or F1Z to fix the committee type. The committee type change is "live" on Thursday. We wouldn't see the PCC-PAC message until Thursday morning.

**Comment by lbeaufort** [comment]
@djgarr and I took a look, here are our notes:

-- 1) counts: looks ok (340ish)

-- 2) wide enough? yes, catches these examples except where no money was raised
--source: https://docs.google.com/spreadsheets/d/1tFKYs3aKFvuncEcgg2Yvo27Smo1XLBhOODvfKspKy7c/edit#gid=0 filtered by “midcycle” and “midcycle 2012"
```
select *
from ofec_pcc_to_pac_mv_tmp_jj
where (COALESCE(receipts, 0) > 0 or COALESCE(disbursements, 0) > 0)
AND (FIRST_CMTE_DSGN not IN (‘J’) AND LATEST_CMTE_DSGN NOT IN (‘J’))
AND cmte_id in (‘C00745752’, ‘C00727008’, ‘C00727156’, ‘C00724005’, ‘C00712224’, ‘C
 00706564’, ‘C00705152’, ‘C00699090’, ‘C00698894’, ‘C00697441’, ‘C00697128’, ‘C00695338’, ‘C00695023’, ‘C00693044’, ‘C00661421’, '
 C00657965', ‘C00649822’, ‘C00647180’, ‘C00640748’, ‘C00636985’, ‘C00634212’, ‘C00632042’, ‘C00628123’, ‘C00622290’, ‘C00621623’,
 ‘C00619288’, ‘C00591206’, ‘C00584839’, ‘C00583146’, ‘C00581504’, ‘C00578641’, ‘C00572925’, ‘C00541573’, ‘C00529776’, ‘C00500678’,
  ‘C00500678’, ‘C00500173’, ‘C00495960’, ‘C00733790’)
```

-- 3) Too wide? possibly.
--> Need to exclude JFC’s
--> Need to make sure they raised money - ok to add `(COALESCE(receipts, 0) > 0 or COALESCE(disbursements, 0) > 0)`

--For Jean: Should we make this change on the MV or filter it later down the road (API or...?)

```
select *
from ofec_pcc_to_pac_mv_tmp_jj
where (COALESCE(receipts, 0) > 0 or COALESCE(disbursements, 0) > 0)
AND (FIRST_CMTE_DSGN not IN (‘J’) AND LATEST_CMTE_DSGN NOT IN (‘J’))
and cmte_id in (‘C00697441’, ‘C00691790’, ‘C00697128’, ‘C00698894’, ‘C00727156’, ‘C00745752’,‘C00291955’, ‘C00693044’, ‘C00634212’,‘C00503094’)
```

--159
```
select count(*)
from ofec_pcc_to_pac_mv_tmp_jj
where (COALESCE(receipts, 0) > 0 or COALESCE(disbursements, 0) > 0)
AND (FIRST_CMTE_DSGN not IN (‘J’) AND LATEST_CMTE_DSGN NOT IN (‘J’))
```

-- later: look at known high-profile candidates?
 C00398750 | H8CA20059 | NUNES, DEVIN G.               | 2020              | NEW PAC

-- data integrity: what about duplicates? how would we expect this to behave? 
-- do we want to do a distinct on cmte_id, cand_id, fec_election_yr
--- maybe not relevant once we remove JF and no-money
```
select cmte_id, cand_id, min(fec_election_yr), max(fec_election_yr), count(*)
from ofec_pcc_to_pac_mv_tmp_jj
group by cmte_id, cand_id
having count(*) > 1
```

```
+-----------+-----------+-------+-------+---------+
| cmte_id   | cand_id   | min   | max   | count   |
|-----------+-----------+-------+-------+---------|
| C00566653 | H4MD07066 | 2016  | 2016  | 2       |
| C00544585 | S4MA00184 | 2014  | 2014  | 2       |
| C00255976 | H0GA04023 | 2014  | 2018  | 2       |
| C00661421 | P00006585 | 2018  | 2020  | 2       |
| C00237198 | H0OH08029 | 2016  | 2018  | 2       |
| C00350421 | H0IL15053 | 2014  | 2020  | 2       |
| C00412312 | H6CA48039 | 2016  | 2018  | 2       |
| C00608174 | H6NY19243 | 2018  | 2020  | 2       |
| C00500173 | H4IN02051 | 2012  | 2014  | 2       |
| C00343863 | H0MI08042 | 2014  | 2016  | 2       |
| C00495960 | H2NV02239 | 2012  | 2012  | 2       |
| C00474825 | S0AZ00251 | 2012  | 2016  | 2       |
| C00225623 | H8NY27036 | 2010  | 2012  | 2       |
| C00632067 | H8KS04112 | 2018  | 2018  | 2       |
+-----------+-----------+-------+-------+---------+
```

**Comment by lbeaufort** [comment]
Since we won't be able to get to 100% accuracy with inconsistent data, we might want to the API to remove false positives. This way we'd be maintaining the 1% of false positives rather than 100% of the cases.

**Comment by fecjjeng** [comment]
This following 4 cand_id/cmte_id/fec_election_yr combination has duplicate.

Having a closer look at ofec_cand_cmte_linkage_mv revealed that these are these candidates has special elections at odd year.  

<img width="740" alt="Screen Shot 2020-08-25 at 1 17 02 AM" src="https://user-images.githubusercontent.com/24943130/91125908-d60b1e80-e670-11ea-9749-51504f9e9aab.png">

**Comment by fecjjeng** [comment]
@djgarr had identified 13 committees that are in a list provide by @bmathesonFEC but are not picked up by the MV here.

After reviewing these 13 committees, the following 11 committees are actually picked up by the query in this MV.  However, there are no financial activity reported from these committees.  Therefore when filter by 
(COALESCE(receipts, 0) > 0 or COALESCE(disbursements, 0) > 0).

'C00733790',
'C00724005',
'C00695023',
'C00695338',
'C00661421',
'C00632042',
'C00621623',
'C00619288',
'C00584839',
'C00578641',
'C00529776',

**Comment by fecjjeng** [comment]
The following two committees indeed has financial activity but are not picked up by the query in the MV:
'C00647180', 
'C00628123'

<img width="704" alt="Screen Shot 2020-08-25 at 8 59 46 PM" src="https://user-images.githubusercontent.com/24943130/91242650-f93bd980-e715-11ea-8a2b-d0993e2b1941.png">

**Comment by fecjjeng** [comment]
This is not a very common situation but I am trying to see if we can further fine-turn this query.  Reviewed other columns of dim_cmte_ie_inf, the cmte_pk followed the rule of <data_source>MMDDYYYYHH24MISS<sequencenumber> pattern.

<img width="870" alt="Screen Shot 2020-08-25 at 9 09 07 PM" src="https://user-images.githubusercontent.com/24943130/91243136-3eacd680-e717-11ea-8f99-524bd7c89b39.png">

**Comment by fecjjeng** [comment]
The updated MV (ofec_pcc_to_pac_mv_tmp_jj_3) now has picked up these two committees as PCC->PAC conversion

select * from ofec_pcc_to_pac_mv_tmp_jj_3 where cmte_id in ('C00647180', 'C00628123');
<img width="902" alt="Screen Shot 2020-08-25 at 9 25 29 PM" src="https://user-images.githubusercontent.com/24943130/91244129-8fbdca00-e719-11ea-9ab4-a866c2dd552e.png">

**Comment by djgarr** [comment]
@fecjjeng Thanks for working on this. Upon further review, those two committees should not be included on the lists. C00628123 looks to have been accidentally assigned to two committees at the onset and the PAC was given a new ID number. C00647180 is the ID for another PAC. The candidate committee associated with John Curtis is C00647339 and is still an active candidate committee

**Comment by fecjjeng** [comment]
@djgarr Thanks about the history research on those two committees.  As I noted above. the updated SQL is only to make sure the SQL get a consistent result when situation like this happen.  For the history of those committees, we may not be able to handle it programmatically.  We may need to handle it procedurally since a program would not know the story behind the scene.  After reviewed by @djgarr @bmathesonFEC of the list and try to grab as many conversion as we can programmatically and flush out the false positive, we can decide what would be the overall strategy to handle the overall flow.

**Comment by lbeaufort** [comment]
@djgarr @bmathesonFEC and @lbeaufort are working through this list to make sure the logic isn't catching too many "Extra" candidate/committee pairs.

https://docs.google.com/spreadsheets/d/1J1IVGaEmBsTZBSvP3-LdmvnTfUnfYB3GMml3dCabXEU/edit#gid=0

**Comment by lbeaufort** [comment]
MV notes so far: 

**Candidate profile page**

- Conversion list MV has 2-year “conversion slice” AKA fec_election_yr
- Election year is given to the front end
- Where the 2-year “conversion slice” falls within the election year’s range (H/S/P 2/6/4)
- Show the message

**Committee profile page**

- Conversion list MV has 2-year “conversion slice” AKA fec_election_yr
- two-year transaction period given to front-end
- Where the 2-year “conversion slice” falls equals two-year-transaction period
- Show the message

**Comment by fecjjeng** [comment]
Two tickets are created to "materialized" the database work needed to capture the work finalized in the ticket/
#4574 officially create disclosure.dim_cmte_ie_inf table and do initial load and hook to GoldenGate daily refresh 
#4595 add new MV to capture the SQL work finalized in this ticket and add it to the MV refresh task.

**Comment by fecjjeng** [comment]
I had cleaned up the candidate_election_year information in ofec_candidate_history_mv in several iteration, it is more reliable than cand_vaild_fec_yr for our purpose.
/*
ofec_pcc_to_pac_mv_tmp_jj_4 use ofec_candidate_history_mv
ofec_pcc_to_pac_mv_tmp_jj_3 use cand_valid_fec_yr
*/
ofec_pcc_to_pac_mv_tmp_jj_4 had picked up 5 less cmte_id/cand_id/fec_election_yr pair, however, all these 5 has no financial activity so it is fine.

select cand_id, cmte_id, fec_election_yr from ofec_pcc_to_pac_mv_tmp_jj_3 where (COALESCE(receipts, 0) > 0 or COALESCE(disbursements, 0) > 0)
except
select cand_id, cmte_id, fec_election_yr from ofec_pcc_to_pac_mv_tmp_jj_4 where (COALESCE(receipts, 0) > 0 or COALESCE(disbursements, 0) > 0);

-- these are some of the committees that David G and Brad had identified as post candidate election change.
-- these all had candidate_election_year null
select * from ofec_pcc_to_pac_mv_tmp_jj_4 
where cmte_id in ('C00026757','C00037606','C00090357','C00143438','C00178418','C00187419','C00194472','C00200865','C00202523')
order by cand_id, cmte_id, fec_election_yr, candidate_election_year 

select * from ofec_pcc_to_pac_mv_tmp_jj_4 
-- 338 rows
where candidate_election_year is not null
-- 236 rows
and (COALESCE(receipts, 0) > 0 or COALESCE(disbursements, 0) > 0)
-- 198 rows
and (FIRST_CMTE_DSGN not IN ('J') AND LATEST_CMTE_DSGN NOT IN ('J'))
-- 70 rows
and cmte_id in  ('C00697441', 'C00691790', 'C00697128', 'C00698894', 'C00727156', 'C00745752','C00291955', 'C00693044', 'C00634212','C00503094', 'C00372201')
-- Known conversion case, all 11 still got picked up
order by fec_election_yr, cand_id, cmte_id

filtered the latest version of MV (ofec_pcc_to_pac_mv_tmp_jj_4) by the following 3 conditions:
1. candidate_election_year is not null
-- the fec_election_yr that the conversion occurs does not belongs to a candiate_election_year
2. (COALESCE(receipts, 0) > 0 or COALESCE(disbursements, 0) > 0)
-- cmte does not have financial activity in the fec_election_yr that the conversion occurs
3. (FIRST_CMTE_DSGN not IN ('J') AND LATEST_CMTE_DSGN NOT IN ('J'))
-- cmte is not a Joint Fund committee
There are 70 rows identified.

The 11 committees known to have PCC to PAC conversion as Laura mentioned are still been picked up.

**Comment by fecjjeng** [comment]
@Brad @DG @laura I had updated the spreadsheet you have, added a third tab (updated_list).  That one has the 70 rows that shown as converted after filtered by
candidate_election_year is not null
-- the fec_election_yr that the conversion occurs does not belongs to a candiate_election_year
2. (COALESCE(receipts, 0) > 0 or COALESCE(disbursements, 0) > 0)
-- cmte does not have financial activity in the fec_election_yr that the conversion occurs
3. (FIRST_CMTE_DSGN not IN ('J') AND LATEST_CMTE_DSGN NOT IN ('J'))
-- cmte is not a Joint Fund committee

Plus the two rows (at the end of the list) that previous identified as "Y?" but with candidate_election_year as null in the updated MV.

Thank you for looking through it.

**Comment by bmathesonFEC** [comment]
I reviewed all of the candidate/committee combos identified by the new code. There are still some false positives showing up, but this list is very close! I also reviewed previous lists for false negatives, committees that should have 
carried forward but didn't. I didn't find any examples.

https://docs.google.com/spreadsheets/d/1J1IVGaEmBsTZBSvP3-LdmvnTfUnfYB3GMml3dCabXEU/edit#gid=1969132779

I provides notes on every committee/candidate that I don't think should be on the list:

1. Many of the remaining false positives occur because PCCs converted to a party committee on their Form 1 (box d) at some point. Possible, solution: these committees change their registration back to a PCC, maybe we can exclude if the committee designation changes back to P. (I realize that's not going to be as easy as it sounds to me).

2. Other false positives are the product of bad data (bad committee types / designations in dim_cmte). This makes me think that we need an exclusion list so we can override the code when it's identifying committees/candidates that are not on the list.

**Comment by fecjjeng** [comment]
@bmathesonFEC @djgarr @lbeaufort @PaulClark2 Thanks for the analysis of the output file.  I had review some of them and put down my comments.   I noticed there are quite a few of the committees that you mentioned converted to party instead of PAC so they should not be included in the list.  I have some questions regarding this point.
- So far I only found very few examples of these type of conversion, that is, latest_cmte_tp in ('X','Y'), and all of them does not have financial activity so it will not be included in the final version of the SQL.  My question is that no matter the PCC converted to PAC or Party, the financial activities associated with the committees will not be associated with the PCC anymore, if there is any.  Should these be also included in this list?
- Quite a few of the committees that had been indicated should not be in the list are due to imperfectness of the data.  I agreed with you that the an exclusion table is needed to override the result generate by the sql.  Just like we use disclosure.candidate_inactive table to filter out candidate that should not be included in the candidate list.  We can have a description column to record the reason, and requester column to indicate the requester, and a pg_date column to record the time a request had been executed (added the table).

**Comment by fecjjeng** [comment]
-- ***** Another situation, PCC converted into non-PCC but converted back.  No new rows created, but the previous row been flagged with MST_RCT_RCD_FLG = 'Y'.  
-- Order by create_date will miss this one. version 6 added MST_RCT_RCD_FLG in the order by when selection the lastest row of the fec_election_yr.  
-- Note: there is only one MST_RCT_RCD_FLG for a cmte_id over the years.  So this will not help in the situation that switching back to a row in earlier cycles.  -- example: C00545749/2016, C00254573/2016, C00410639/2018

**Comment by fecjjeng** [comment]
The exclude table will include the cmte_id, fec_election_yr, requester, reason to exclude and the pg_date.  This table is used to exclude the cmte_id/fec_election_yr that should not be considered mid-cycle exclusion in real world.  But existing data will pick them up as the mid-cycle exclusion.
I will enter the first round of entries according to Brad/Daivd's list for people to review.

**Comment by fecjjeng** [comment]
Proposed usage of the exclude table: 
API will look at the MV AND the exclude table to determine if the committee message should show up.  This way will be more flexible for immediate change.
I suggest to have people open a ticket to have DBA team to insert into the table.  This way we can keep a trace of the data flow.

**Comment by fecjjeng** [comment]
After talking to Brad, the PCC converted to Party will be excluded even money will dissociate from the candidate after convert to party since first, a PCC is allowed to convert into PAC but not other type of committees, second, the specific language that is used on the web site is for PCC to PAC conversion.   So far only few PCC to Party conversion had been recorded and all of them has no financial activity associate with them.

**Comment by fecjjeng** [comment]
First draft of the exclude list:
https://docs.google.com/spreadsheets/d/1J1IVGaEmBsTZBSvP3-LdmvnTfUnfYB3GMml3dCabXEU/edit#gid=253616182

**Comment by fecjjeng** [comment]
![Screen Shot 2020-09-15 at 1 52 29 AM](https://user-images.githubusercontent.com/24943130/93171173-962ada80-f6f6-11ea-9c11-85e95c021fb0.png)

**Comment by fecjjeng** [comment]
The initial list includes all records marked by @bmathesonFEC and @djgarr  as "NO" and can not be handled by the latest code of the MV. Except the following 3 for the reason described following (marked as yellow backgroud in the spreadsheet):
-- Mst_rct_rcd_flg had been switch to a previous record as PCC. However, it had been switched back to PAC record then cmte terminated.
C00279901	S8WI00026	FEINGOLD, RUSSELL D	2016	2012

-- Since this is a Senate committee, 2012 is part of 2016 race
C00341891	S6AZ00019	MCCAIN, JOHN S	2016	2012

-- Since this is a Senate committee, 2012 is part of 2016 race
C00639021	P00005900	DAVENPORT, KEITH	2020	2018

**Comment by fecjjeng** [comment]
There are two more converted one been picked up today.  Looks real, @bmathesonFEC and @djgarr?
C00693713	P00009183	GABBARD, TULSI	2020	2020
C00733261	S0KY00420	BOOKER, CHARLES	2020	2020

**Comment by fecjjeng** [comment]
In summary, 
We had finalized a SQL to generate a new MV that pick up all the conversion case we know, and filter out most of the false positive cases.
The cases that can not be handled by code due to inconsistent data will be entered into an exclusive table.  Records will look like the screenshot above.  The initial load of the table are according to the latest review by @bmathesonFEC and @djgarr.  Moving forward, ticket will be entered to request the entries to keep the history/reason.  DB team will enter upon request as soon as possible.
