### ISSUE TITLE
Create arch-mur name table and put murArchinve.xml into table

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4563]
What we're after:
We are working on write a new Python code to load archived MUR data to ES from Postgres database (under schema: mur_arch).  aAfter puting archived_mur_names.csv and murArchinve.xml into database,
all archived MUR data is in database.

- [ ] convert archived_mur_names.csv into table: mur_arch.archived_mur_names
source file:
[https://github.com/fecgov/openFEC/blob/develop/data/archived_mur_names.csv](https://github.com/fecgov/openFEC/blob/develop/data/archived_mur_names.csv)

- [ ] convert murArchinve.xml into table: mur_arch.murArchinve_xml

Ref issue: [https://github.com/fecgov/openFEC/issues/4490](https://github.com/fecgov/openFEC/issues/4490)

**Comment by hcaofec** [comment]
Tables are added to mur_arch.
mur_name_csv
mur_name
mur_arch_xml
all_murs
documents
