### ISSUE TITLE
Implement alternative to setTimeout for swagger-ui.html

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4564]
###
As part of hotfix https://github.com/fecgov/openFEC/pull/4557/files we implemented a `setTimeout` to ensure the api key signup form loaded with the page. 

@johnnyporkchops identified an alternative approach that does not presume any knowledge of how long a user's delay is

**Comment by johnnyporkchops** [comment]
The  purpose of this follow-up issue was to test one option that we overlooked when addressing the intermittent load issue  in https://github.com/fecgov/openFEC/pull/4557/files, which was writing the API Umbrella signup script to the body using the `document.write` statement in their embed code. I was hoping this would allow us to remove the `setTimout funcntion` we are using now.
Although this seems to reduce the occurrences of the form not loading over other techniques, it is still possible to recreate the issue locally, so no need to test on dev or move forward with this issue.

I will also submit an issue to the GH repo asking for input on this issue.

**Comment by johnnyporkchops** [comment]
This ticket was opened because there was one option we did not try when testing this :
Appending the API Umbrella signup script to the body instead of head using the `document.write` statements in API Umbrella's embed code.

**Comment by johnnyporkchops** [comment]
api.data.gov issue submitted: https://github.com/18F/api.data.gov/issues/554
