### ISSUE TITLE
Deploy the new ES service in production

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4582]
**What we're after:** 
Deploy the new ES service in production

Related work:
- https://github.com/fecgov/openFEC/issues/4505 Test Elasticsearch v7.4 beta service

**Action items:**
TBD

**Completion criteria:**
TBD

**Comment by fec-jli** [comment]
this is done. [https://github.com/fecgov/openFEC/issues/4663](https://github.com/fecgov/openFEC/issues/4663)
