### ISSUE TITLE
Create a leadership PAC sponsor postgres table and translate data

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4586]
**What we're after:**
Need to be able to have leadership PAC sponsor data in postgres in order to show it in the API and the website.

**Action items:**
- [ ] Create a table in postgres
- [ ] Initial data load
- [ ] Hook up to the daily goldengate refresh process

**Completion criteria:**
- [ ] New postgres table is created

**Comment by fec-jli** [comment]
new view on oracle: LEADERSHIP_PAC_CAND_CMTE_LINK
