### ISSUE TITLE
[Snyk: High] Directory Traversal (Due 10/02/2020)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4611]
@rfultz commented on [Wed Sep 02 2020](https://github.com/fecgov/fec-cms/issues/4015)

Directory Traversal
[https://app.snyk.io/vuln/SNYK-PYTHON-FLASKCORS-608972](https://app.snyk.io/vuln/SNYK-PYTHON-FLASKCORS-608972)

Remediation:
Upgrade Flask-Cors to version 3.0.9 or higher.

**Completion criteria:**
- [x] Verify that this is a problem and address the vulnerability appropriately

**Comment by patphongs** [comment]
This has been merged
