### ISSUE TITLE
Counts for all endpoints are incorrect when 'sort_hide_null=True' 

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4626]
### User story
As a user, I want the endpoints to return correct counts when I use `sort_hide_null=True`  because  I want accurate  results.

### Expected behavior
When we use  `sort_hide_null=True`, it's supposed to hide rows  that have  null values for whatever we are sorting on (e.g., `first_file_date`
(We want count to reflect the number of rows that are shown)

### Actual behavior
- correctly hides the row
- count reflects rows that hidden as well 

Examples  of incorrect behavior:

https://api.open.fec.gov/v1/candidates/?api_key=DEMO_KEY&sort_hide_null=true&sort_nulls_last=true&is_active_candidate=true&sort=-first_file_date 
is the same count as 
https://api.open.fec.gov/v1/candidates/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&is_active_candidate=true&sort=-first_file_date&per_page=100 ➡️ when I confirmed there are records with null `first_file_date` values. 

https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=true&sort_nulls_last=false&data_type=processed&committee_id=C00671339&line_number=F3-11AI&sort=-contribution_receipt_date&per_page=100&two_year_transaction_period=2020 
➡️ shows count of 3 and no results

This applies to ItemizedResource and ApiResource endpoints. This means the counts are wrong, and makes pagination really tough because it looks like there are more records than there are. I'm not sure this impacts front-end users. 
I put some tests in the `4626-tests` branch: https://github.com/fecgov/openFEC/pull/4627/commits/ff8ab0ac117ced0444187fd98f75c936f5c174b5

**Completion criteria**
- [ ] Counts update for `sort_hide_null=True` 
- [ ] Double-check counts update for `sort_nulls_only=True` 
- [ ] Need to add test cases to check count behavior

### Helpful additions:
This is an example of an API resource being ok (updating counts correctly):
https://api.open.fec.gov/v1/candidates/?api_key=DEMO_KEY&sort_nulls_only=true&sort_nulls_last=true&is_active_candidate=true&sort=-first_file_date&per_page=100

**Comment by JonellaCulmer** [comment]
Moving to

**Comment by jason-upchurch** [comment]
```sql
SELECT count(*) FROM ofec_candidate_detail_mv LEFT OUTER JOIN ofec_candidate_flag_mv AS ofec_candidate_flag_mv_1 ON ofec_candidate_flag_mv_1.candidate_id = ofec_candidate_detail_mv.candidate_id WHERE ofec_candidate_detail_mv.candidate_inactive = false AND ofec_candidate_detail_mv.first_file_date is not NULL;
=> 33048
```

**Comment by jason-upchurch** [comment]
A tracing of the logic for https://api.open.fec.gov/v1/candidates/?api_key=DEMO_KEY&sort_hide_null=true&sort_nulls_last=true&is_active_candidate=true&sort=-first_file_date:
