### ISSUE TITLE
API sign up key bug

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4635]
This was reported from a user:

> I visit https://api.open.fec.gov/developers/ , fill out the form titled "Sign up for an API key", and press "Signup". The button briefly changes to "Loading...", then flips back to "Submit". Nothing else happens and I receive no email. I've tried Chrome 85.0.4183.102 and Safari 13.1.2 (15609.3.5.1.3).

Replication:

I was not able to replicate this bug in Chrome and was able to sign up for a key successfully. We should investigate if we can replicate the bug.

- [ ] @jason-upchurch replicated problem from iPhone Safari
- [ ] @jason-upchurch replicated problem from Desktop Safari
- [ ] @jason-upchurch replicated problem from Desktop Firefox

**Technical Considerations**
There are a lot of downstream considerations for this page, e.g., https://github.com/fecgov/openFEC/issues/4565. The signup link worked previously and was browser independent. Perhaps as we work through the pain points and page redesign, the best course of action is to return to simply using the link, since the software worked. Then, when we have a more clear picture of what we are after we can revisit either embedding a form or creating a new one entirely.

**Completion criteria:**
- [x]  reach out to API.data.gov for assistance if it's not an "us" problem
- [x] timebox troubleshooting
- [ ] revert if need be, open issues, discuss approach with team.
- [x] Test across multiple browsers to verify issue and pinpoint any specific browser issues

**Comment by jason-upchurch** [comment]
Resolved. Notified google group as well.
