### ISSUE TITLE
Docker Hub and CircleCI [research]

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#4653]
**What we are after**
Research if this applies to our pipeline. 

Email from CircleCI

> Hi there, 
> 
> On November 1st, Docker Hub will begin limiting anonymous image pulls. We want to make sure you know how you might be impacted and what you can do to avoid interruptions to your workflow. 
> 
> Adding Docker authentication to your pipeline config is the easiest way to avoid any service disruptions. If you use the Docker executor or pull Docker images when using the machine executor on CircleCI, we encourage you to authenticate. Because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP. 
> 
> We are currently working on a partnership with Docker to minimize the impact of this change for our users and will share more details as we get them. 
> 
> For more information or to leave a question for us, please head over to Discuss or contact support. 
> 
> Thanks and happy building, 
> 
> - The CircleCI team

**Comment by jason-upchurch** [comment]
@jason-upchurch @johnnyporkchops @fec-jli discussed and it does not look like we will be above the [Docker rate limits](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/):
>    Free plan – anonymous users: 100 pulls per 6 hours 
    Free plan – authenticated users: 200 pulls per 6 hours
    Pro plan – unlimited
    Team plan – unlimited

* [circle ci documentation](https://support.circleci.com/hc/en-us/articles/360050623311-Docker-Hub-rate-limiting-FAQ)
* [circle ci instructions for authentication](https://circleci.com/docs/2.0/private-images/)

We will verify no issues on Nov 1 with new deploy in CircleCI (cc @patphongs @PaulClark2 )

**Comment by jason-upchurch** [comment]
verified using Docker Hub: `Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.`

> My builds use the Docker executor, does this affect me?
No, as mentioned previously CircleCI has partnered with Docker to ensure that our users can continue to access Docker Hub without rate limits.

**Comment by jason-upchurch** [comment]
@PaulClark2 this does not appear to be an issue for us. I also tested with deploys on openFEC, fec-eregs, and fec-cms. Based on the messaging, we are using Docker executor and are not subject to the rate limiting.
