### ISSUE TITLE
Add database caching for Biden schedule A

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4655]
Per @dzhang-fec we have some caching in place for Trump (C00580100) schedule A which has improved result time, but an API user pointed out the results for Biden (C00703975) are ~3x slower. Per @dzhang-fec we can add caching to schedule A for Biden (C00703975).

**Comment by dzhang-fec** [comment]
I have finished this caching.
--  Biden  713399 rows (sql run ~16 sec)
--  Trump 546398 rows (sql run ~8 sec) (edited) 
Yes, it has (or >95% are caching)  . The data histogram   and count has difference which can make sql execution time difference.

**Comment by dzhang-fec** [comment]
![image](https://user-images.githubusercontent.com/62447258/95480310-c2362600-0959-11eb-909f-a94eaafb710c.png)

**Comment by lbeaufort** [comment]
Caching is complete, thank you @dzhang-fec!
