### ISSUE TITLE
Upgrade Elasticsearch7.4 service in Dev space

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#4659]
Upgrade elasticsearch service from v5.6 to v7.4 in Dec environment.   

Related issue ES5.6 service -  https://github.com/fecgov/openFEC/issues/2921
Refer ES7.4 PR -  https://github.com/fecgov/openFEC/pull/4657

**Tech steps:**

- [x] Create a new ES7.4 High Availability service (es-medium-ha)
- [x] Create a new private s3 bucket service (fec-s3-snapshot) to save ES snapshot.(separated from public s3 bucket)
- [x] Config ES7.4 repository to bind private s3 and  test snapshots/restore 
- [x] Clean OCR text data on the **arch-mur253**(with 8 documents), which fixed the **Message: Request size exceeded 10485760 bytes** error while loading to ES7 service. 
- [x] Upload all legal docs (AOs, ADRs, AFs, MURs, Archived MURs, Statues, Regulations)
- [x] Test `/legal/search` and `/legal/docs/<doc_type>/<no>` two endpoints
- [x] Test eregs app
- [x] Test all schedule tasks
- [x] Test download function
- [x] Test all management commands.
- [x] Test Legal search page(CMS)
- [x] Conduct performance test (load test)

### Completion criteria
- Upgraded!

**Comment by fec-jli** [comment]
We follow the instruction and test on dev.
[https://github.com/fecgov/openFEC/pull/4657](https://github.com/fecgov/openFEC/pull/4657)

**Comment by pkfec** [comment]
PR https://github.com/fecgov/openFEC/pull/4657 merged. @fec-jli setup the new ES7 service (fec-api-elasticsearch) on dev# space.  Ran the zero downtime command and reloaded the legal docs  onto the new elasticsearch 7 service.
