### ISSUE TITLE
Upgrade Elasticsearch7.4 service in Stage space

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#4662]
Upgrade elasticsearch service from v5.6 to v7.4 in Stage environment.   

Related issue ES5.6 service -  https://github.com/fecgov/openFEC/issues/2921
Refer ES7.4 PR -  https://github.com/fecgov/openFEC/pull/4657

**Completion Criteria:**

- [x] Create a new ES7.4 High Availability service
- [x] Create a new private s3 bucket service (fec-s3-snapshot) to save ES snapshot.(separated from public s3 bucket)
- [x] Config ES7.4 repository and  test snapshots/restore 
- [x] Clean OCR text data on the **arch-mur253**(with 8 documents), which fixed the **Message: Request size exceeded 10485760 bytes** error while loading to ES7 service.
- [x] Upload all legal docs (AO, ADR, AF, MUR, Archived MURs, Statues, Regulations)
- [x] Test all schedule task code
- [x] Test  downloads
- [x] Test management commands.
- [x] Test Legal search (CMS)
- [x] Conduct performance test (load test)

**Comment by fec-jli** [comment]
follow the instruction and test on stage. 
[https://github.com/fecgov/openFEC/pull/4657](https://github.com/fecgov/openFEC/pull/4657)

**Comment by pkfec** [comment]
Complete the elasticsearch service setup on `Stage` space before the release branch(s) get cut on 12/15/2020

**Comment by fec-jli** [comment]
This is done.
