### ISSUE TITLE
Add filter_overlap to test_filters.py

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4674]
Follow-up to https://github.com/fecgov/openFEC/pull/4666#pullrequestreview-514803828

We have a new generic filter `filter_overlap`:
https://github.com/fecgov/openFEC/blob/0761f560fd044139053f0d6d3b9c2a1c1bc113d1/webservices/filters.py#L65-L79

while this is currently tested by the only endpoint using it...
https://github.com/fecgov/openFEC/blob/0761f560fd044139053f0d6d3b9c2a1c1bc113d1/tests/test_committees.py#L376-L393

it would be helpful to have a generic test for this new filter in test_filters.py.

**Comment by hcaofec** [comment]
Test case has been added in this PR: #[4680](url)

**Comment by hcaofec** [comment]
Close this ticket via #4612
