### ISSUE TITLE
Decide on path forward for leadership PACs sponsor name typeahead

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4675]
**What we're after:**
Need to be able to get search by leadership PACs sponsor name & id within the typeahead dropdown feature work.

### First task
- [x]  determine if we want full list of candidates or just the sponsored (will affect the implementation) cc @JonellaCulmer 
  - Addressed in this [comment](https://github.com/fecgov/openFEC/issues/4675#issuecomment-719520554). 

**Action items:**
- [ ] create PACs sponsor name_search_mv
- [ ] create or modify current PACs sponsor name typeahead endpoint

**Completion criteria:**
- [ ] PACs sponsor name_search_mv created
- [ ] create PACs sponsor name/search endpoint created
- [ ] endpoint auto test case added

![sponsor2](https://user-images.githubusercontent.com/24395751/97589257-af9c9300-19d3-11eb-8123-628b5042d108.png)

**Comment by JonellaCulmer** [comment]
@fec-jli The full list of candidates is preferable. I'd rather data users be able to search across all candidates to determine whether there are any leadership PACs associated with them and those who _know_ a candidate has a leadership PAC. Limiting the list to just those candidates who have leadership PACs may leave out data users who are exploring.

**Comment by fec-jli** [comment]
@JonellaCulmer Thank you for your response
I have a question: Do we want the new sponsor_candidate filter **typeahead** only return those sponsor candidates? that means that if not sponsor_candidate, won't display on dropdown list.
we just call one typeahead endpoint.

if use all_candidates typeahead, we will call two endpoints:
1)all-candidate typeahead
2)/committees/ endpoint

**Comment by JonellaCulmer** [comment]
Closing in favor of fec-cms#4061
