### ISSUE TITLE
2022 candidates missing from Candidates data table

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/openFEC#4689]
### Summary
There are two data tables on the site that appear to be listing fewer candidates for office than there are candidates that have registered for office:

[Campaign finance data > Browse data > Candidates ](https://www.fec.gov/data/candidates/?election_year=2022&office=H&is_active_candidate=true)
[Campaign finance data > Browse data > Candidates for house](https://www.fec.gov/data/candidates/house/?election_year=2022&election_full=True&is_active_candidate=true)
[Campaign finance data > Browse data > Candidates for senate](https://www.fec.gov/data/candidates/senate/?election_year=2020&cycle=2020&election_full=true&is_active_candidate=true)

The data tables -- filtered to display House candidates in 2022 -- show 31 candidates (at the time I am writing this). Alternatively, looking at Statement of Candidacy (Form 2) data as a starting point, we have received 138 electronically filed statements of candidacy for candidates registering for 2022. [List attached here](https://app.zenhub.com/files/40841283/df585320-4fe5-4e2a-9f55-bc463bee2123/download). Similarly, I get a proximate result (147) in FECP Disclosure when I run:

```
SELECT election_yr, cand_office,
    COUNT(*) AS numInstances
    FROM disclosure.dim_cand_inf
    WHERE election_yr = '2022'
         and cand_office = 'H'
GROUP BY election_yr, cand_office

```

The candidates in the attachment in the previous paragraph should appear as candidates for 2022 on [this page](https://www.fec.gov/data/candidates/?election_year=2022&office=H&is_active_candidate=true). For the sake of providing specific examples, here are several Candidates that have registered for 2022 House, but do not appear on candidates list today:

- WASHBURN, AMY IRENE (H0WI06194) - F2 received 7/2/2020
- SCALISE, STEVE (H0LA01087) - F2 received 11/12/2020
- PETERS, SCOTT (H2CA52089) - F2 received 11/9/2020
- CHENEY, ELIZABETH (H6WY00159) - F2 received 11/8/2020

I have not reviewed other offices or election cycles to confirm whether this is widespread.

**Completion criteria:**
- [ ] Determine why the list of candidates is not complete for both House and all candidates
- [ ] Determine if the list of candidates is not complete for Senate. If not complete, find out why.
- [ ] The House candidate list is complete in the API endpoint: https://api.open.fec.gov/v1/candidates/totals/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&election_year=2020&election_full=True&is_active_candidate=true&sort=-receipts&per_page=30&page=1&office=H
- [ ] The Senate candidate list is complete in the API endpoint: https://api.open.fec.gov/v1/candidates/totals/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&election_year=2020&cycle=2020&election_full=true&is_active_candidate=true&sort=-receipts&per_page=30&page=1&office=S
- [ ] The candidate list for all offices is complete in the API endpoint: https://api.open.fec.gov/v1/candidates/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&sort=-first_file_date&per_page=30&page=1

**Comment by hcaofec** [comment]
As @PaulClark2  indicated above, the source of candidates list is cand_valid table, which does not have data of fec_election_yr=2022.  This table will get refreshed after January 1, 2021.  

As of today,  website shows 37 House candidates for 2022 because these 37 rows have 2020/2022 (fec_election_yr/cand_election_yr) in cand_valid. 
https://www.fec.gov/data/candidates/house/?election_year=2022&election_full=True&is_active_candidate=true

Same reason goes for Senate candidates.  Since this is the design, there is no refactoring for now.  For future reference, a possible approach could be switching to dim_cand table for this list.

cc: @bmathesonFEC

**Comment by hcaofec** [comment]
Follow-up research ticket created here: #[4704](https://github.com/fecgov/openFEC/issues/4704)
