### ISSUE TITLE
former_committee_name for P00016063 incorrect

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4691]
The former committee name listed for this candidate displays their current committee name ("AFAEC PAC"), and not their former committee name ("Amash for America Exploratory Committee").

## API call
Screenshot of results also shown below. https://api.open.fec.gov/v1/candidate/P00016063/committees/history/2020?per_page=100&election_full=True&api_key=DEMO_KEY

![Screen Shot 2020-11-16 at 11 15 05 AM](https://user-images.githubusercontent.com/12799132/99278422-050ed780-27fd-11eb-9c73-725415535d1a.png)

## Form 1 filings
Past Form 1 filing: https://docquery.fec.gov/cgi-bin/forms/C00745752/1404770/ shows that the committee's former name was: "Amash for America Exploratory Committee".

Current form 1 filing: https://docquery.fec.gov/cgi-bin/forms/C00745752/1415260/ shows that the committee's current name is: "AFAEC PAC"

**Comment by hcaofec** [comment]
Need to update committee name in dim table.

**Comment by hcaofec** [comment]
data returned by API looks good now after the change made to database.

<img width="677" alt="Screen Shot 2021-01-08 at 11 03 46 AM" src="https://user-images.githubusercontent.com/24396726/104036274-35417980-51a1-11eb-8a29-2b11ac6f9221.png">
