### ISSUE TITLE
Replace http: links with https:, address other tech debt with docquery links

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4718]
When working on #4715, I came across a number of links in the code that are still `http`. We should use `https` where possible.

- [x] Look for `http`, replace with `https`
- [x] Comments here: https://github.com/fecgov/openFEC/pull/4716#issuecomment-746612416
- [x] Test functionality
- [x] Enter follow-up issues for fec-cms and fec-eregs

**Comment by rfultz** [comment]
For the record, instead of `http://` or `https://`, starting a URL with `//` will use whatever URL scheme is currently being used. Kinda old-school, though, before everything was ssl
