### ISSUE TITLE
Update system diagram

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4726]
**What we're after:** 
We accidentally broke functionality with an infrastructure change that was not documented in the system diagram. The database team has scripts to add bulk data files and database backups, those external services are not reflected. 

As a software developer, the best way I can be confident my changes won't break something else, I need to rely on up to date documentation. Contractors also rely on the diagram and the external dependencies.

**Action items:**
- [x] Investigate using a more user-friendly application to recreate this diagram (currently in docx.google)
- [x] New bucket for elasticsearch backups
- [x] Bulk downloads from FEC side connect to s3
- [x] Contractor uploads to https://www.fec.gov/files/bulk-downloads/index.html?prefix=bulk-downloads/electronic/ and
https://www.fec.gov/files//bulk-downloads/index.html?prefix=bulk-downloads/paper/
- [x] Database backups from FEC side connect to databases (CMS/Eregs) for backups
- [x] Make sure it's clear what goes in each s3 bucket, or at least all the apps that connect to them

https://github.com/fecgov/FEC/wiki/2.-FEC-system-diagram

https://docs.google.com/drawings/d/13LtMZMlOyZlBurFLQZL8s2IyCN66kgu59c6FnC3Igto/edit

**Completion Criteria:**
- [ ] ~Make a copy of current google doc (https://docs.google.com/drawings/d/13LtMZMlOyZlBurFLQZL8s2IyCN66kgu59c6FnC3Igto/edit) first before making any changes.~ I created a new diagram, so this was not needed
- [x] Update the system diagram with the S3 services as specified above
- [x] Verify that there are no other changes to be made
- [x] The wiki is updated

**Comment by patphongs** [comment]
@lbeaufort @pkfec @fec-jli I have completed the new fec.gov system diagram and it is ready for your review [here](https://app.diagrams.net/#G123mSF0rM5TV3HjFf-PjUGvGhEEgGOxVD) 🔒. Please let me know if you have any change suggestions. After you have verified, I would like to make this the new diagram going forward and update the FEC wiki.

**Comment by patphongs** [comment]
I have addressed comments about the diagram further with @lbeaufort @pkfec @PaulClark2.

**Comment by PaulClark2** [comment]
Thanks, @patphongs. I'm good with going ahead with publication.

**Comment by patphongs** [comment]
The diagram has been updated on our wiki: https://github.com/fecgov/FEC/wiki/2.-FEC-system-diagram
