### ISSUE TITLE
Research updates to election profile pages for reapportionment 

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#4727]
**What we are after**:
Update ZIP Codes used by election profile page for 2022 congressional districts. 

**Why we are after it**:
To provide up-to-date ZIP code-to-congressional district searches for our users. 

**Considerations**:
- add decennial indicator (2010 for current data; 2020 for new data)
- FIPS codes for states shouldn't change but confirm and update if necessary
- Find ZIP to CD crosswalk data 
- Update ofec_fips_states
- Update ofec_zips_districts

**Possible data sources**:
- State FIPS https://www.census.gov/library/reference/code-lists/ansi.html#par_textimage_3
- Census Congressional District Relationship Files https://www.census.gov/geographies/reference-files/2010/geo/relationship-files.html#par_textimage_1589730557 (Congressional Districts and ZIP Code Tabulation Areas). 
    - Will need to wait for 2020 files. We might need to look for additional sources.
- Sources we used for the original election profile search https://github.com/fecgov/openFEC/blob/develop/data/notes.md

**Related to**:
https://github.com/fecgov/fec-cms/issues/4290

Possibly helpful information from previous related task:
https://github.com/fecgov/fec-cms/issues/1942

**Completion criteria**:
- [ ] Document findings from research questions above including viable data sources inn addition to CENSUS, (see related ticket  https://github.com/fecgov/fec-cms/issues/4290)
- [ ]  Document other considerations for completing the API updates mentioned above
- [ ] Cross reference any findings in related FEC-CMS  ticket that may be helpful to that ticket: https://github.com/fecgov/fec-cms/issues/4290
- [ ] Create implementation ticket with completion criterion: "`https://api.open.fec.gov/v1/elections/search/...` returns 2022 CD when searching for 2022 elections."

**Comment by patphongs** [comment]
Bumping due to resource constraints and data unavailability
