### ISSUE TITLE
Update leadership sponsor linkage table for 2022 records

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4736]
In leadership sponsor linkage table ( **disclosure.cand_cmte_linkage_alternate** ), there are only 6 rows for 2022, and  650 rows for 2020.  
It seems to be the there should be rollover to 2022 for committees that are not terminated or admin terminated.

`select fec_election_yr, count(*) from disclosure.cand_cmte_linkage_alternate
group by fec_election_yr
order by fec_election_yr desc;`

Completion Criteria:
- [x] Contact the FEC contractor to update the 2022 records in Oracle table
- [x] Check disclosure.cand_cmte_linkage_alternate table 2022 data
- [x] Check ofec_committee_history_mv and ofec_committee_detail_mv

**Comment by PaulClark2** [comment]
I inserted 644 new rows into DISCLOSURE.CAND_CMTE_LINKAGE_ALTERNATE. Most of these are fec_election_yr  = 2022 rows. I also reviewed 43 committees that had electronically filed a Form 1 indicating the committee was a leadership PAC but our data had them coded as something else. When appropriate, I update From 1 data, committee data and leadership linkages. 

`select * from DISCLOSURE.CAND_CMTE_LINKAGE_ALTERNATE where substr(sub_id, 1,9) = 101102021;`
`select * from STAGING.FEC_STAGING_CAND_CMTE_LINKAGE where substr(sub_id, 1,9) = 101102021;`

As we review these data, we can make corrections to DISCLOSURE.CAND_CMTE_LINKAGE_ALTERNATE, STAGING.FEC_STAGING_CAND_CMTE_LINKAGE, Form 1 and the committee tables in FECP.

**Comment by hcaofec** [comment]
Six duplicates were in disclosure.cand_cmte_linkage_alternate and removed. 
2022 data in ofec_committee_history_mv and ofec_committee_detail_mv looks good.

Need to contact contractor to figure out the cause for duplicates and missing digit in cand_id.
