### ISSUE TITLE
Reports missing from /committee/<committee_id>/reports

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4742]
From an api user: 

> I am trying to retrieve financial information for some committees using the /committee/{committee_id}/reports/ endpoint. While it works great for most committees, the API sometimes returns no data.

> For instance, committee C00672311 does not map to any report if I use the API. But it does when I look at the FEC website (https://www.fec.gov/data/committee/C00672311/?tab=filings&cycle=2018).
> Query:
> https://api.open.fec.gov/v1/committee/C00672311/reports/?api_key=5JX2rcWDNrf0UEmIdVwE8Oab8cg9V27NdAb7pJVs&per_page=100&page=1

> Response:
> `{"api_version":"1.0","pagination":{"page":1,"count":0,"per_page":100,"pages":0},"results":[]}`

It looks like /committee/<committee_id>/reports is filtering by committee type, and since this committee changed types, the reports aren't appearing.

http://localhost:5000/v1/committee/C00672311/reports/?api_key=5JX2rcWDNrf0UEmIdVwE8Oab8cg9V27NdAb7pJVs&per_page=100&page=1
```
SELECT *
FROM ofec_reports_pac_party_mv 
LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_1 
ON ofec_reports_pac_party_mv.committee_id = ofec_committee_history_mv_1.committee_id 
AND ofec_reports_pac_party_mv.report_year + ofec_reports_pac_party_mv.report_year %% 2 = ofec_committee_history_mv_1.cycle 
WHERE ofec_reports_pac_party_mv.committee_id = 'C00672311'
```

**Comment by lbeaufort** [comment]
Workaround: 

> One alternative would be to use the /reports/<committee_type>/ endpoint.
> 
>  
> 
> Example: https://api.open.fec.gov/v1/reports/house-senate/?api_key=DEMO_KEY&committee_id=C00672311
> 
> Docs: https://api.open.fec.gov/developers/#/financial/get_reports__committee_type__
> 
>  
> 
> I believe you could combine this with /committee/{committee_id}/history/{cycle}/ endpoint to determine the committee type for a committee for a given 2-year period and pass that through to the /reports/<committee_type>/ endpoint.
> 
>  
> 
> Examples: https://api.open.fec.gov/v1/committee/C00672311/history/2020/?api_key=DEMO_KEY
> 
> https://api.open.fec.gov/v1/committee/C00672311/history/2022/?api_key=DEMO_KEY
> 
> Docs: https://api.open.fec.gov/developers/#/committee/get_committee__committee_id__history__cycle__
>

**Comment by hcaofec** [comment]
There are couple ways to return all financial reports filed by one committee regardless of this committee's type.  However,  different type of reports only share a few general columns.  Displaying all columns by one endpoint adds complexity and needs to be reviewed.
