### ISSUE TITLE
Consider increasing cache length for non-schedule data

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4745]
**What we're after:**
We should consider increasing cache length for non-schedule data (data that is refreshed once per day with MV's). One disadvantage is we'd need to bust the cache in the (rare) cases where we need to manually remove offensive or incorrect data and have it appear immediately. In these cases, we don't always refresh the MV's and sometimes wait for them to show up the next day.

https://github.com/fecgov/openFEC/blob/251a49efda44ea2c8a05f287c47b9e25f83dda9c/webservices/rest.py#L182-L212
**Action items:**
- [ ] Identify slowest-performing endpoints
- [ ] Make sure we won't cache too long in cases of data that needs to be removed quickly

**Completion criteria:**
- [ ] Increase cache-length for non-schedule data

**Comment by lbeaufort** [comment]
Another issue is that I think we might be running out of memory in the API umbrella cache mid-day, so taking up more space with non-schedule endpoints would decrease the amount of memory available for schedule A endpoints. 

- Consider talking to API umbrella about cache capability and ability to measure it (is the cache running out of memory? should we use it more for schedule data and less for others?)
- Consider researching current cache usage/capability
- Consider another caching option like cloud.gov CDN service

**Comment by JonellaCulmer** [comment]
Does this relate to https://github.com/fecgov/openfec/issues/4785?

**Comment by pkfec** [comment]
endpoints with most hits from API umbrella:

Path | Hits
-- | --
api.open.fec.gov/v1/schedules/ | 5592429
api.open.fec.gov/v1/committee/ | 1494983
api.open.fec.gov/v1/filings | 1207724
api.open.fec.gov/v1/candidate/ | 1199630
api.open.fec.gov/v1/names/ | 837336
api.open.fec.gov/v1/calendar-dates | 620884
api.open.fec.gov/v1/candidates | 521375
api.open.fec.gov/v1/efile/ | 453088
api.open.fec.gov/v1/candidates/ | 373056
api.open.fec.gov/v1/committees | 215723
api.open.fec.gov/v1/elections/ | 167720
api.open.fec.gov/v1/download/ | 128462
api.open.fec.gov/v1/legal/ | 99128
api.open.fec.gov/v1/elections | 59818
api.open.fec.gov/v1/audit-case | 43224
api.open.fec.gov/v1/calendar-dates/ | 42767
api.open.fec.gov/v1/electioneering/ | 38797
api.open.fec.gov/v1/presidential/ | 29875
api.open.fec.gov/v1/communication_costs/ | 29357
api.open.fec.gov/v1/election-dates | 26329
api.open.fec.gov/v1/totals/ | 19775
api.open.fec.gov/v1/state-election-office | 16750
api.open.fec.gov/v1/reports/ | 11641
api.open.fec.gov/v1/rad-analyst | 5337
api.open.fec.gov/v1/electioneering | 4256
api.open.fec.gov/v1/operations-log | 3980
api.open.fec.gov/v1/audit-category | 3193
api.open.fec.gov/v1/reporting-dates | 2846
api.open.fec.gov/v1/audit-primary-category | 2841
api.open.fec.gov/v1/communication_costs | 224
api.open.fec.gov/v1/auditcommitteess | 11

**Comment by pkfec** [comment]
candidate and committee totals are most visited/viewed endpoints.  After discussing with @lbeaufort and @fec-jli we all agreed to cache below endpoints during the peak hours. 

1. /committee/{committee_id}/totals/
2. /candidate​/{candidate_id}​/totals​/

**Comment by pkfec** [comment]
Tested caching committee totals endpoint on local env. 

Terminal log:
```
INFO:werkzeug:127.0.0.1 - - [07/Apr/2021 04:48:41] "GET /v1/committee/C00302695/totals?committee_id=C00302695&cycle=2020&per_page=1&sort_hide_null=True&api_key=NICAR16 HTTP/1.1" 200 -
$$$$ LONG_CACHE /v1/filings
$$$$ peak_hours_start_time UTC  13:00:00
$$$$ peak_hours_end_time UTC 23:30:00
$$$$ peak_hours_expiration_time GMT Wed, 07 Apr 2021 23:30:00 GMT
```

**Comment by pkfec** [comment]
1. /legal/ endpoint cache for 5mins:
 URL: http://localhost:8000/data/legal/advisory-opinions/2020-05/
 Logs:
```
INFO:werkzeug:127.0.0.1 - - [29/Apr/2021 10:32:56] "GET /v1/schedules/schedule_c/?api_key=NICAR16&sort_hide_null=false&sort_nulls_last=true&sort=-incurred_date&per_page=30&page=1 HTTP/1.1" 200 -
$$$$$$ legal /v1/legal/docs/advisory_opinions/2020-05
$$$$$$ In LEGAL Header: Cache-Control public, max-age=300
```


http://localhost:8000/data/legal/advisory-opinions/2020-05/
http://localhost:8000/data/loans/

**Comment by pkfec** [comment]
efile:
http://localhost:8000/data/receipts/?data_type=efiling

calendar:
http://localhost:8000/calendar/?calendar_category_id=36

legal:
http://localhost:8000/data/legal/advisory-opinions/2020-03/

committee/totals:
http://127.0.0.1:8000/data/committee/C00302695/

candidate totals:
http://localhost:8000/data/candidate/P80000722/

**Comment by pkfec** [comment]
Tested caching committee/candidate totals in`stage` env:

**cache committee totals endpoint:** `curl -svo /dev/null "https://api-stage.open.fec.gov/v1/committee/C00302695/totals/?per_page=20&page=1&sort_hide_null=false&sort_nulls_last=false&sort_null_only=false&sort=-cycle&api_key=DEMO_KEY"`

<img width="836" alt="Screen Shot 2021-05-03 at 1 21 53 PM" src="https://user-images.githubusercontent.com/11650355/116909678-8e329300-ac12-11eb-867b-1e983a4921ed.png">

**cache candidate totals endpoint:**`curl -svo /dev/null "https://api-stage.open.fec.gov/v1/candidate/H8NJ01077/totals?election_full=True&cycle=1998&api_key=DEMO_KEY"`

<img width="863" alt="Screen Shot 2021-05-03 at 1 28 57 PM" src="https://user-images.githubusercontent.com/11650355/116910372-8f17f480-ac13-11eb-965c-d4c0438436b8.png">

**Comment by pkfec** [comment]
The code changes to cache (api umbrella) candidate and committee `/totals` endpoint can be tracked in PR https://github.com/fecgov/openFEC/pull/4845
