### ISSUE TITLE
Check logs Sprint 13 innovation#2 - week 4 (2/17)

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#4749]
Log review needs to be completed for Sprint 13 innovation#2 week 4 per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

- [x] open tickets for Sprint 14.1

**Comment by lbeaufort** [comment]
**FEC-CMS:**

- package.json: 2 old, 3 new (combined)
     - High: (blocked) Arbitrary Code Execution (fecgov/fec-cms#4026)
     - High (new):  Command Injection (https://github.com/fecgov/fec-cms/issues/4390)
     - Medium: Access Restriction Bypass and Validation Bypass (combined) https://github.com/fecgov/fec-cms/issues/4379 (https://app.snyk.io/org/fecgov/project/2a97cddb-4b62-4d54-b18f-3b85d55a5e10/#issue-SNYK-JS-SANITIZEHTML-1070786 and https://app.snyk.io/org/fecgov/project/2a97cddb-4b62-4d54-b18f-3b85d55a5e10/#issue-SNYK-JS-SANITIZEHTML-1070780)
     - Medium (new): Regular Expression Denial of Service with lodash (https://github.com/fecgov/fec-cms/issues/4391)
     - Medium (new): Regular Expression Denial of Service with ua-parser (https://github.com/fecgov/fec-cms/issues/4392)


- requirements.txt: 2 existing

     - MEDIUM: Regular Expression Denial of Service (ReDoS) (https://app.snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994)  [https://github.com/fecgov/fec-cms/issues/4362](https://github.com/fecgov/fec-cms/issues/4362)
     - LOW: Directory Traversal (https://app.snyk.io/vuln/SNYK-PYTHON-DJANGO-1066259) [https://github.com/fecgov/fec-cms/issues/4363](https://github.com/fecgov/fec-cms/issues/4363)
     
**OPEN-FEC:**
- package.json: 2 new
     - High (new):  Command Injection (https://github.com/fecgov/openFEC/issues/4766)
https://github.com/fecgov/openFEC/issues/4766
     - Medium (new): Regular Expression Denial of Service (https://github.com/fecgov/openFEC/issues/4767)

**FEC-EREGS:**
- requirements.txt: 1
     - LOW: Directory Traversal: [https://github.com/fecgov/fec-eregs/issues/563](https://github.com/fecgov/fec-eregs/issues/563)

**FEC-PATTERN-LIBRARY:**
None

**Search logs:**
- [ ] Ticket for  Eileen Leamon

Cloud.gov Dashboard:
9 deployer accounts, same as last week.

Offboarding:
None
