### ISSUE TITLE
Image (pdf) links of older reports and statements not appearing

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4757]
**What we're after:**
Image (pdf) links of older reports and statements are not appearing. At this point we believe that this data exists somewhere and that this is an API bug.

Example: https://www.fec.gov/data/committee/C00302695/?cycle=1996&tab=filings#statements. However, the image of the Form 1 at 95039754175 is available on docquery https://docquery.fec.gov/cgi-bin/fecimg/?95039754175. 

**Action items:**
- [x] Determine the scope of just how broken this is and compile a list 

**Completion criteria:**
- [x] Older report PDF links are working

**Comment by pkfec** [comment]
Reports regularly filed section:
`pdf_url` is used to display the hyperlink for a each individual report

Statements of organization section:
`html_url` is used to display the hyperlink for a each statement

**Comment by pkfec** [comment]
For  https://www.fec.gov/data/committee/C00302695/?cycle=1996&tab=filings#statements the api call is:

https://api.open.fec.gov/v1/filings/?sort_null_only=false&page=1&sort_nulls_last=false&sort_hide_null=false&sort=-receipt_date&api_key=DEMO_KEY&cycle=1996&per_page=20&committee_id=C00302695

The hyperlinks under `Statements of organization sections` are generated using the _**html_url**_ attribute values. In DB when looked up for committee_id=C00302695 & cycle=1996, the html_url values are NULL. Hence the hyperlinks are not available on the website which displays the actual statement.

**Comment by hcaofec** [comment]
DB function report_pdf_url_or_null has been modified. The image link is available now on website. 
https://www.fec.gov/data/committee/C00302695/?cycle=1996&tab=filings#statements. 
image of the Form 1 at 95039754175

[PR #4830](urlhttps://github.com/fecgov/openFEC/pull/4830)
