### ISSUE TITLE
Add report-level information to debts endpoint

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#4758]
**What we are after**
Provide customers with information about the report a debt transaction was reported on.

**Why are we after it**
Provide context about the debt to our customers

**Completion criteria:**
- [x] Add coverage start date
- [x] Add coverage end date 
- [x] Add report year
- [x] Add report type
- [ ] Add corresponding filters
- [x] Create a follow-up ticket for front end to implement this for the debts datatable. Corresponding PR: https://github.com/fecgov/fec-cms/pull/4353

**Comment by tmpayton** [comment]
@patphongs Should I add a filter for all four of these variables? (`coverage_start_date`, `coverage_end_date`, `report_type` and `report_year`)

**Comment by patphongs** [comment]
> Should I add a filter for all four of these variables? (`coverage_start_date`, `coverage_end_date`, `report_type` and `report_year`)

@tmpayton If it doesn't hinder the performance in the API, then yes it would be good to have filters for all 4 of these variables. The reason being is that individual debt transactions (rows in the debt table) show increases or reductions of the debt by reporting period. Therefore, to help the user decipher these increases and decreases, it would help them to filter by these variables. This is further explained by @PaulClark2's comment in this old CMS [PR](https://github.com/fecgov/fec-cms/pull/4353#issuecomment-771895009).
