### ISSUE TITLE
Research the current CMS CDN (custom-domain, deprecated) setting in dev space

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4770]
**What we're after:** This is to see how caching works in the API app. We should document the process and the research we've done. 

**Action items:**
- [ ] Document the process and the research we've done

**Completion criteria:**
- [ ] Document how the existing CDN works on CMS and the existing settings

**Comment by pkfec** [comment]
| Space     | CDN service name(s) |
| ----------- | ----------- |
| Dev      | fec-dev-cdn-route       |
| Stage   | fec-stage-cdn-route        |
| Prod   | beta-fec-cdn-route , transition-fec-route, www.fec.gov       |

**Comment by johnnyporkchops** [comment]
Closing as this is no longer relevant
