### ISSUE TITLE
Advertise bulk schedule data dumps

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4772]
**What we're after:** Reach out to current schedule A users to let them know about the schedule data dumps

**Action items:**
- [x] Identify recent (past 6 months) schedule A users. Target moderate and heavy users. Look at the averages or top 50% for ballpark of who is a moderate or heavy user.
- [x] Consider adding bulk schedule data dump information to the API documentation

**Completion criteria:**
- [x] Users are informed of schedule data dumps.

**Comment by hcaofec** [comment]
Currently, schedule data dumps are uploaded to s3 bucket once a week.

**Comment by hcaofec** [comment]
Users are informed of schedule data dumps.

Thanks to @PaulClark2
