### ISSUE TITLE
Document and improve measurement process for database changes

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4773]
**What we're after:**
Document and improve measurement process for database changes, specifically application changes that impact database queries.

A reliable way to measure the performance impact of database changes is essential to make sure we are having the impact we intend. This measurement should be meaningful in a way that helps to justify new changes. 

**Action items:**
- [ ] During documentation, identify opportunities for improvement
- [ ] Document those opportunities in a google doc or create followup tickets as necessary

**Completion criteria:**
- [ ] Measurement process for database changes is documented.

**Comment by johnnyporkchops** [comment]
Closing at this time.
