### ISSUE TITLE
Research time it takes to have AO posted

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4798]
**What we're after:**
When an AO is posted, we need to research how long it takes for the AO to appear on our website in our legal resources section: https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions

### Technical considerations
1. The API will run a task to load AOs every 5 minutes
2. The API elasticsearch endpoint caches for 5 minutes
3. The CMS caches content for 10 minutes

Depending on when the task runs and when the caches expire, the total time for an AO to appear could be as much as 15 minutes. Coordinate with Jason B. and contractor so we can get best estimate of when something is published how long it might take.

**Considerations:**
- [ ] Add flag to slack once something is uploaded to elasticsearch?

**Completion criteria:**
- [x] Research, including methodology of testing, is documented and recommendations have been proposed

**Comment by johnnyporkchops** [comment]
If  we know based on the technical considerations above,   that `API task time is 5 min`, the `elastic search cache  is 5min` , `the  cms cache is 10 min`, then, as stated above:
> Depending on when the task runs and when the caches expire, the total time for an AO to appear could be as much as 15 minutes.

The answer to this research ticket is `"Up to 15 min"`

**Comment by johnnyporkchops** [comment]
To verify the task and cache times mentioned above , I am asking Srini to  un-publish  three  2023 AOs  today and to re publish tomorrow so I can follow the process in the logs and document findings.

**Comment by johnnyporkchops** [comment]
After following the process in the logs with a re-published AO, and looking at historical data we confirmed that the time-to-publish for an AO can be as much as 25 min. 
I  received a  spreadsheet (linked below) from Jason Bucelato in Public records  which shows **all legal doc publishing** times from 04/21 to 04/23. I  added formulas to calculate time-in-minutes, average and mean times. There were some enhancements to the process during that timespan which may have an effected on the time-to-publish over time. 
The average time was 10.75 minutes
The mean time was 8.00 minutes
https://docs.google.com/spreadsheets/d/1yvXEkn-4xGgk8ZN6q0RsxcqWgngsUw74/edit#gid=778483371

For the outstanding Considerations checklist item above:
Reached out to database team about adding status monitor alerts for AO's in legal-resources slack channel like we do for MURS 
Example: `….Recently published MUR case 7732 is in database and also in [fec.gov](http://fec.gov/)` . Will update when I hear back from them. cc @dzhang-fec.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Is there a path to improve these processing times?
