### ISSUE TITLE
Modify  is_active to allow active, terminated and administratively terminated

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#4800]
**What we are after**
We need to make a distinction between terminated and administratively terminated committees. On the committee profile page we need to be able committees: 'terminated,' 'administratively terminated' or 'active.'

May be able to close this ticket and https://github.com/fecgov/fec-cms/issues/4465 if https://github.com/fecgov/fec-cms/issues/4465 can be completed on its own

**Considerations**
- [ ] `is_active` in committee history is currently boolean
    - [ ] Is this a breaking change? Do we need to consider adding a new parameter? We could deprecate `is_active` later if no longer needed.
- [ ] We need three values
- [ ] committee filing frequency 
   - [ ] `T` = terminated
   - [ ] `A` = administratively terminated
   - [ ] `M` or `Q` = active

**Pairing**
David G. is interested in paring on this work.

**Steps / tasks**
- [ ] update database tables
- [ ] update endpoint

**Completion criteria**
- [ ]

**Comment by patphongs** [comment]
This should no longer be needed, we solved the need by using `filing_frequency` as an added check for administratively terminated committees. See PR https://github.com/fecgov/fec-cms/pull/4528
