### ISSUE TITLE
Add "administratively terminated" definition to glossary

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4801]
**What we're after:**
We plan to update our committee profile pages to distinguish between "terminated" and "administratively terminated" committees. We should update the glossary to include a definition for "administratively terminated committee." This will help users unfamiliar with the term administratively terminated do the research without requiring them to leave the page. 

**Regulations:**
Termination 11 CFR 102.3; Admin termination 11 CFR 102.4

**Resources with pre-approved language:**
- https://www.fec.gov/legal-resources/policy-other-guidance/administrative-terminations-and-debt-settlement-plans/
- https://www.fec.gov/help-candidates-and-committees/terminating-a-committee/

**Action items:**
- [x] Review letters and other published Wagtail pages for definitions language that has already been approved
- [x] Draft improved definition(s) for terminated committees and/or administratively terminated committees. We currently have a definition for "terminating committee". Does that need to change as well?
- [x] Circulate with OGC for review/permission (even if we're using language that's already been approved)
- [ ] Open PRs to make front-end change to the two glossary files (e-regs and cms)

**Completion criteria:**
- [ ] Definition(s) are approved and followup tickets are opened as appropriate

**Comment by kathycarothers** [comment]
The content team feels that the definition of terminated committee should not be changed. It is correct and has been approved by OGC.  I have drafted the definition of administratively terminated based on existing material @AmyKort @dorothyyeager @PaulClark2 @bmathesonFEC @JonellaCulmer and if okay I will circulate to OGC:

"Administrative termination is the action taken by the Commission to terminate the reporting obligations of political committees that appear to be inactive in accordance with 52 U.S.C. 30103(d)(2) and 11 CFR 102.4. Administrative termination does not relieve a committee of any legal responsibility for the payment of any outstanding debt or obligations."

**Comment by kathycarothers** [comment]
I have sent the term off to OGC for review.

**Comment by dorothyyeager** [comment]
All related PRs were merged, so closing.
