### ISSUE TITLE
Material view: modify is_active to allow active, terminated and administratively terminated

### ISSUE THREAD

**Issue by rfultz** [fecgov/openFEC#4809]
## Summary
Do we need this ticket—will a combination of `is_active` and `filing_frequency` satisfy #4465 ? (If so, we can also close #4800 )

Need to add/update material view for the is_active change from boolean to T, A, M, or Q, including changing its name

https://api.open.fec.gov/v1/committee/C00278424/history?per_page=1&api_key=DEMO_KEY

## Completion criteria
- Can move forward with #4800

**Comment by patphongs** [comment]
This should no longer be needed, we solved the need by using `filing_frequency` as an added check for administratively terminated committees. See PR https://github.com/fecgov/fec-cms/pull/4528
