### ISSUE TITLE
Investigate possible issue with info from partnership PACs' Form 1s showing up incorrectly

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/openFEC#4810]
A friend of mine who works for a law firm (former FEC employee) reached out because her law firm's PAC is showing up as having a connected organization of a "corporation without capital stock" but they are a nonconnected PAC and had that on their Form 1. I told her to contact RAD about possible data entry error, but just in case this might be a website issue, am logging here. She mentioned another law firm PAC that also has the same problem - the PAC is listed as membership organization but is really a partnership with a nonconnected PAC.

Here's her message to me (which she agreed I could share):

> My firm’s PAC (ID C00104901) is designated on the FEC website as a “Corporation w/o capital stock PAC-Qualified” but, as you know, since we are a partnership, we cannot have a separate segregated fund.  The PAC is a nonconnected PAC and our Statement of Organization accurately reflects our status as such.

**Comment by PaulClark2** [comment]
This seems like a data issue, but let's wait for the committee to contact RAD. 

```
select
form_tp, cmte_id, begin_image_num, filed_cmte_tp, filed_cmte_dsgn, org_tp, receipt_dt 
from disclosure.nml_form_1_1Z_view where cmte_id = 'C00104901' order by receipt_dt desc;;
```

**Comment by patphongs** [comment]
It looks like this is no longer an issue. The PAC is no longer filtering as an SSF: https://www.fec.gov/data/committees/?q=C00104901&committee_type=W&organization_type=W
