### ISSUE TITLE
Find administratively-terminated committees who show as active

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4811]
## Summary

Committee C00409011 in 2018 shows as `is_active = true` even though there is an administrative termination filing as seen below.

http://www.fec.gov/data/committee/C00409011/?cycle=2018&tab=filings

<img width="1275" alt="Screen Shot 2021-03-18 at 12 50 12 PM" src="https://user-images.githubusercontent.com/12799132/111665080-cf005500-87e8-11eb-8b6e-188c794f669d.png">

The API call for this committee for cycle 2018 shows that the committee `is_active = true` and the `filing_frequency = Q`. The assumption is if there is an administrative termination filing, the filing_frequency should be `A`.

### API call

https://api.open.fec.gov/v1/committee/C00409011/history/2018?per_page=1&api_key=DEMO_KEY

The `is_active` field uses filing_frequency to determine whether or not it is active. 

```
BEGIN
        RETURN CASE cmte_filing_freq
            WHEN 'Q' THEN TRUE
            WHEN 'M' THEN TRUE
            WHEN 'T' THEN FALSE
            WHEN 'A' THEN FALSE
            ELSE TRUE
        END;
```
 
## Completion criteria
- [ ] Get a list of committees that have a similar issue (see https://github.com/fecgov/openFEC/issues/4811#issuecomment-802238350 below)
- [ ] Create a follow-up ticket to address those issues

**Comment by PaulClark2** [comment]
@patphongs It looks like the filing frequency is incorrect in one of the tables in FECP. I'll correct it there. We can check tomorrow if this fixes this problem. 

Correct in FECP
`select form_tp, cmte_id, filing_freq, receipt_dt, begin_image_num, sub_id  from DISCLOSURE.NML_FORM_1_1Z_VIEW where cmte_id = 'C00409011' order by receipt_dt desc;`
`select cmte_id, fec_election_yr, cmte_filing_freq from DISCLOSURE.cmte_valid_fec_yr where cmte_id = 'C00409011' order by fec_election_yr desc;`

Incorrect in FECP
`select cmte_id, mst_rct_rec_flg, cmte_filing_freq from DISCLOSURE.DIM_CMTE_IE_INF where cmte_id = 'C00409011';`

**Comment by patphongs** [comment]
Let's see if we can find other examples of committees that were administratively terminated (sent an MS-F letter) during a two year period that do not have a filing frequency of `A` during that two year period.

**Comment by PaulClark2** [comment]
There are 1,047 committees with multiple administrative termination dates. 
```
SELECT cmte_id, COUNT(*)
FROM disclosure.nml_form_99_misc 
WHERE to_from_ind = 'F' 
AND delete_ind IS NULL 
GROUP BY cmte_id 
HAVING COUNT(*) > 1;
```
There are 4,106 committees with single administrative termination dates that have received an MS-F but do not have a filing frequency of "A." 
```
select f.cmte_id, (CASE MOD(f.rpt_yr,2) WHEN 0 THEN f.rpt_yr ELSE f.rpt_yr+1 END) AS mod_rpt_yr, cm.cmte_filing_freq, f.receipt_dt
FROM disclosure.nml_form_99_misc f, disclosure.cmte_valid_fec_yr cm 
WHERE f.cmte_id = cm.cmte_id
AND (CASE MOD(f.rpt_yr,2) WHEN 0 THEN f.rpt_yr ELSE f.rpt_yr+1 END) = cm.fec_election_yr
AND to_from_ind = 'F'  
AND f.delete_ind IS NULL 
AND cm.cmte_filing_freq <> 'A'
AND f.cmte_id 
IN 
    (SELECT cmte_id 
    FROM disclosure.nml_form_99_misc 
    WHERE to_from_ind = 'F' 
    AND delete_ind IS NULL 
    GROUP BY cmte_id 
    HAVING COUNT(*) = 1)
;
```
728 of the 4,106 committees that have received an MS-F but do not have a filing frequency of "A" have also received an MS-K (termination approval).
```
SELECT cmte_id, to_from_ind, receipt_dt, begin_image_num, sub_id 
FROM disclosure.nml_form_99_misc 
WHERE to_from_ind = 'K' 
AND delete_ind IS NULL 
AND cmte_id IN (
    select f.cmte_id
    FROM disclosure.nml_form_99_misc f, disclosure.cmte_valid_fec_yr cm 
    WHERE f.cmte_id = cm.cmte_id
    AND (CASE MOD(f.rpt_yr,2) WHEN 0 THEN f.rpt_yr ELSE f.rpt_yr+1 END) = cm.fec_election_yr
    AND to_from_ind = 'F'  
    AND f.delete_ind IS NULL 
    AND cm.cmte_filing_freq <> 'A'
    AND f.cmte_id 
    IN 
        (SELECT cmte_id 
        FROM disclosure.nml_form_99_misc 
        WHERE to_from_ind = 'F' 
        AND delete_ind IS NULL 
        GROUP BY cmte_id 
        HAVING COUNT(*) = 1)
               )
;
```

**Comment by PaulClark2** [comment]
These 490 records (there are committees with multiple rows) are cases where a committee's filing frequency was changed to "A" and then later changed to "M" or "Q."
```
WITH aterm AS 
    (SELECT cmte_id, TRUNC(receipt_dt) AS receipt_dt, new_ff, sub_id 
    FROM staging.ff_change 
    WHERE new_ff = 'A' 
    AND receipt_dt IS NOT NULL)
SELECT aterm.*, f.cmte_id, TRUNC(f.receipt_dt) AS receipt_dt, f.new_ff, f.sub_id  
FROM aterm, staging.ff_change f
WHERE f.cmte_id = aterm.cmte_id
AND TRUNC(f.receipt_dt) >= aterm.receipt_dt
AND f.new_ff IN ('Q', 'M');
```

**Comment by PaulClark2** [comment]
My suggestion is we correct these data issues on an ad hoc basis when they cause issues or when they are brought to our attention.
