### ISSUE TITLE
[Snyk: Low] Deserialization of Untrusted Data (07/06/21)

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#4818]
### Overview:
networkx is a Python package for creating and manipulating graphs and networks

Affected versions of this package are vulnerable to Deserialization of Untrusted Data. This package is vulnerable to arbitrary code execution via insecure YAML deserialization due to the use of a known vulnerable function load() in yaml, which is called in read_yaml() in networkx/readwrite/nx_yaml.py.

networkx/readwrite/nx_yaml.py is deprecated and scheduled to be removed in the next release of Networkx. Users should avoid using this function completely.

### Detailed paths:
Introduced through: project@0.0.0 › networkx@1.11

### Remediation:
There is no fixed version for networkx
Look for any updates here - https://app.snyk.io/vuln/SNYK-PYTHON-NETWORKX-1062709

### Completion criteria:
- [x] check if remediation is available for networkx and update the package
There is no direct remediation yet. but networkx releasethe latest version of networkx==2.5.1 0n 04/03/2021. [https://pypi.org/project/networkx/](https://pypi.org/project/networkx/)

- [x] document where we're using networkx / how we may be affected (If no remediation path, since it's a dev dependency, do we mark it as 'won't fix'?)
1)networkx v2.5.1 won't fix the Deserialization of Untrusted Data Vulnerability, but it is ready to next release upgrade which will fix the Vulnerability by networkx's announcement.
[https://github.com/networkx/networkx/issues/4728](https://github.com/networkx/networkx/issues/4728)
2)We upgrade networkx from 1.11 to 2.5.1 in this PR: [https://github.com/fecgov/openFEC/pull/4829](https://github.com/fecgov/openFEC/pull/4829)
3)The offending code appears to be in the nx_yaml module, we don't use nx_yaml, so this issue won't affect us. suggest to down-grade to [low] priority. 

- [ ] check if remediation is available for networkx(greater than v2.5.1) after 90 days and update the package. [https://pypi.org/project/networkx/](https://pypi.org/project/networkx/)

**Comment by fec-jli** [comment]
1)Currently, we are using networkx==1.11. the latest version of networkx==2.5.1, release 0n 04/03/2021. https://pypi.org/project/networkx/
2)but, after install networkx==2.5.1, we still get Deserialization of Untrusted Data Vulnerability warning.
<img width="500" alt="install_v2 25 1" src="https://user-images.githubusercontent.com/24395751/113895087-9d9af980-9796-11eb-90d3-3e36e3bd84b9.png">
<img width="500" alt="vulnerability" src="https://user-images.githubusercontent.com/24395751/113895109-a390da80-9796-11eb-885b-d4ecea009fbe.png">

3)create a tickey in networkx github, get reply: they will fix this issue in the next major release, not v2.5.1. https://github.com/networkx/networkx/issues/4728

4)`The offending code appears to be in the nx_yaml module`, we don't use nx_yaml, so this issue won't affect us.

5)We use networkx package in flow.py to build the sequence of refresh our materialized views. so we better to upgrade networkx to  the latest version.
