### ISSUE TITLE
Modify `report_pdf_url_or_null` function to generate images links for reports prior to 2000

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#4821]
### What we’re after

@PaulClark2 provided below logic to handle the image links on the website:

```
Images of reports and statements
The FEC has the following images of reports and statements.
PAC, party and presidential filings [Form 3X and Form 3P]
    1993-present: electronic copy
    1972-1992: microfilm
House committee filings [Form 3]
    May 1996-present: electronic copy
    1972-April 1996: microfilm
Senate filings [Form 3]
    May 2000-present: electronic copy
    1972-April 2000: microfilm
```
 `report_pdf_url_or_null` database function needs to be refactored to enable image links prior to 2000.

Examples:

Form 1 link:https://www.fec.gov/data/committee/C00302695/?cycle=1996&tab=filings#statements.
Form2 link https://www.fec.gov/data/candidate/H8NJ01077/?cycle=1998&election_full=true&tab=filings

### Action item(s)

- [ ]  Modify the  `report_pdf_url_or_null` database function to generate image links prior to 2000.

### Completion criteria

- [ ] Image of a report or statement are available on the website.

**Comment by hcaofec** [comment]
In first [PR #4826](https://github.com/fecgov/openFEC/pull/4826), "=" was added to the condition as 
`report_year >= 1996` 

Later we found that some images are not available even with report_year=1996.   For example:
https://docquery.fec.gov/pdf/463/96016023463/96016023463.pdf
https://docquery.fec.gov/pdf/814/96016044814/96016044814.pdf
https://docquery.fec.gov/pdf/819/96016044819/96016044819.pdf

Second PR is created to remove "=" from the function to make image links more accurate.  There is no direct relationship between receipt_date and report_year especially in old data.  Receipt_date can't be used in the function.

**Comment by hcaofec** [comment]
PR is merged.  So closing.
