### ISSUE TITLE
Schedule B efiling export downloading same row 100,000 times

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4825]
- Go to https://www.fec.gov/data/disbursements/?data_type=efiling&committee_id=C00702944
(1 result)
- click export 
- CMS sends request https://api.open.fec.gov/v1/download/schedules/schedule_b/efile/?sort_hide_null=false&sort_nulls_last=false&data_type=efiling&committee_id=C00702944&sort=-disbursement_date&api_key=<DOWNLOAD_KEY>
- File contains 100,000 rows with the same data in it

---

### What we’re after

(Summarize why this work needs to happen)

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [ ] 

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)
- [ ] 

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] 

### References/resources/technical considerations

(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)

**Comment by pkfec** [comment]
pr https://github.com/fecgov/openFEC/pull/4884 merged to `release/public-20210615` branch. Release went live on 06/15. Closing this issue

**Comment by fec-jli** [comment]
<img width="1192" alt="big_export_file" src="https://user-images.githubusercontent.com/24395751/122773462-60fb7c00-d276-11eb-9c53-0a1bf62cf767.png">
