### ISSUE TITLE
[Research] Changes to endpoints for /legal/ for AFs and document next steps

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4832]
### What we’re after
We have several improvements that need to be made to the AF pages. First we need to research and determine if these changes can be made. We need to document the feasibility and research and make recommendations on what can be accomplished now (and how) and what can't be done now (and why not).

### Related ticket(s)
- https://github.com/fecgov/fec-cms/issues/4446 Reach out to AF team to kickstart migration
- https://github.com/fecgov/fec-cms/issues/4552 [Research] Front-end solutions for AF pages and document next steps

### Action item(s)
- [x] Can we move the initial fine and challenge received date from the summary to the disposition? Is this technically possible? 
- [ ] Can we include the referral to Treasury line in the disposition accurately and consistently? Need to understand how it's in the API.
- [ ] Document any API changes necessary

### Completion criteria
- - [ ] Document research and findings about the feasibility of the aforementioned considerations, including:
  - Display initial fine and challenge inside disposition table
  - Display referral to treasury in the disposition table
- [x] Open followup implementation tickets, as appropriate

### References/resources/technical considerations
![AF Canonical Copy 3](https://user-images.githubusercontent.com/31663028/114943276-be58f400-9e13-11eb-8a83-51b52c6816b4.png)

**Comment by patphongs** [comment]
@JonellaCulmer This is what it looks like with the move of the disposition to it's own section. Does this look ok?

![Screen Shot 2021-05-04 at 4 39 02 PM](https://user-images.githubusercontent.com/12799132/117066853-45a0d580-acf7-11eb-8379-6036fa9ed024.png)

**Comment by patphongs** [comment]
@pkfec I was able to do the first action item of moving the "initial fine and challenge received date" to the disposition section on the front end, you shouldn't need to do anything on the backend for this. https://github.com/fecgov/fec-cms/pull/4598

**Comment by patphongs** [comment]
@JonellaCulmer I just realized that you wanted the "Initial finding and proposed fine" and "Challenge received date" moved to within the disposition section. I did this on the front end. How does this look?

![Screen Shot 2021-05-05 at 8 49 54 AM](https://user-images.githubusercontent.com/12799132/117143688-19309c00-ad7f-11eb-949c-c6ac9b15b993.png)

**Comment by pkfec** [comment]
@patphongs `/legal/`  API endpoint is giving all the necessary AF data back. No changes required on the API for AF data. 
Here is data for AF case_no#26 for your reference: https://api.open.fec.gov/v1/legal/search/?case_no=26&type=AF&api_key=DEMO_KEY

I am not sure if AF's have citations. I will look further and let you know.

**Comment by patphongs** [comment]
@pkfec I asked @JonellaCulmer about the legal citations and she said that no legal citations are needed for Admin Fines, it was inadvertently left in the mock up.

**Comment by patphongs** [comment]
@pkfec The endpoint that we're using on the front end is this: https://api.open.fec.gov/v1/legal/docs/admin_fines/26?api_key=DEMO_KEY. I don't think I see the "Civil penalty due date" data in that endpoint yet.

**Comment by pkfec** [comment]
I am not seeing `Civil penalty due date` column in the DB as well. 

> @pkfec I asked @JonellaCulmer about the legal citations and she said that no legal citations are needed for Admin Fines, it was inadvertently left in the mock up.

Ok, sounds good.

**Comment by patphongs** [comment]
@pkfec If it's possible, can you research if we can add the legal citations from the database into the API? If so, please create a new ticket.

**Comment by patphongs** [comment]
Update: Civil penalty due date and payment status will need to be added to the database from an external source, waiting to determination level of effort and time it will take to move that data over to our DB and API.

**Comment by pkfec** [comment]
Meeting  contractors today (05/06/2021) to discuss the LOE to get the `Civil penalty due date` and `payment status` to our postgres db.

**Comment by patphongs** [comment]
Moving to PI 14 innovation so that we can track work that is needed from the legacy application to bring over the necessary fields to our database.

**Comment by patphongs** [comment]
Closing in favor of follow-up work here: https://github.com/fecgov/openFEC/issues/4866
