### ISSUE TITLE
[Snyk: HIGH ] Deserialization of Untrusted Data (05/28/21)

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/openFEC#4836]
Vulnerability in: 
**openFEC - requirements.txt**

### Overview

networkx is a Python package for creating and manipulating graphs and networks

Affected versions of this package are vulnerable to Deserialization of Untrusted Data. This package is vulnerable to arbitrary code execution via insecure YAML deserialization due to the use of a known vulnerable function load() in yaml, which is called in read_yaml() in networkx/readwrite/nx_yaml.py.

networkx/readwrite/nx_yaml.py is deprecated and scheduled to be removed in the next release of Networkx. Users should avoid using this function completely.

**Introduced through**: networkx@2.5.1

**Remediation:** No remediation path available.
https://app.snyk.io/org/fecgov/project/a95ea997-b012-4b3b-a026-2fdbe6ac0398#issue-SNYK-PYTHON-NETWORKX-1062709

### Related ticket(s)
Upgraded to networkx@2.5.1:
https://github.com/fecgov/openFEC/issues/4818

**Comment by rfultz** [comment]
Networkx [says](https://github.com/networkx/networkx/issues/4728) that this [has been addressed](https://github.com/networkx/networkx/pull/4548), but it's still being flagged

**Comment by pkfec** [comment]
No remediation available at the moment. New version of networkx package might be released soon. 
Follow these issues for more updates:
https://github.com/bridgecrewio/checkov/issues/1051
https://github.com/networkx/networkx/pull/4541

**Comment by pkfec** [comment]
networkx v2.6 will be out around May 31st. See for more comments: https://github.com/networkx/networkx/pull/4541#issuecomment-843015203

**Comment by pkfec** [comment]
**networkx v2.6 beta version** is released on May 31st and available for testing: https://pypi.org/project/networkx/2.6rc1/#history.

**Comment by pkfec** [comment]
Still waiting for the official release version of networkx 2.6 here - https://pypi.org/project/networkx/#history

**Comment by pkfec** [comment]
networkx beta version#2 was released on June23rd here - https://pypi.org/project/networkx/2.6rc2/. 
Still waiting for the official version of networkx package.

**Comment by pkfec** [comment]
Still waiting for the stable release version of networkx pkg here:https://pypi.org/project/networkx/#history

**Comment by pkfec** [comment]
networkx **v2.6.2** available now. I will upgrade networkx on openFEC  and see if that resolves the vulnerability.
https://pypi.org/project/networkx/2.6.2/

**Comment by pkfec** [comment]
Upgrade networks to v2.6.2 in PR https://github.com/fecgov/openFEC/pull/4922
