### ISSUE TITLE
Remove sort expression for Schedule H4

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#4841]
### What we’re after

sort_expression has been removed for schedule B. Should the sort_expression for schedule H4 be removed? 

https://github.com/fecgov/openFEC/blob/develop/webservices/common/models/itemized.py#L897

### Related ticket(s)

[PR for schedule B #4509](https://github.com/fecgov/openFEC/pull/4509)

### Completion criteria

- [ ] Remove sort expression

**Comment by fec-jli** [comment]
This is done in [https://github.com/fecgov/openFEC/pull/5398](https://github.com/fecgov/openFEC/pull/5398)
