### ISSUE TITLE
Do not add coalesce to pagination statement when sort_by_column is not null is in the where clause

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#4842]
### What we’re after

In the where clause of schedule A query below, when there is 'disclosure.fec_fitem_sched_a.contb_receipt_dt IS NOT NULL', there is no need to have coalesce in this pagination statement:  

`AND (coalesce(disclosure.fec_fitem_sched_a.contb_receipt_dt, $3::date), disclosure.fec_fitem_sched_a.sub_id) < $4::date, $5)` 

Remove coalesce under this condition could benefit performance .

![image](https://user-images.githubusercontent.com/24396726/116600066-e1e16b80-a8f6-11eb-8800-e3c6d8738847.png)

![image](https://user-images.githubusercontent.com/24396726/116601455-87e1a580-a8f8-11eb-960f-802b5563ab02.png)

### Related ticket(s)

- More performance testing results can be found in this ticket: [#4763 ](url)
- when sort_hide_null=true, 'is not null' condition is added to the query
    https://github.com/fecgov/openFEC/blob/develop/webservices/sorting.py#L121
- 'coalesce' is added in utils.py
    https://github.com/fecgov/openFEC/blob/develop/webservices/utils.py#L145

**Comment by dzhang-fec** [comment]
Thanks for this ticket. @hcaofec
