### ISSUE TITLE
Simplify read-only connection logic

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4843]
### What we’re after

Simplify read-only connection logic for more maintainable/readable code and small performance improvement. 

The existing "choose a random replica" and "route schedule A traffic to one replica" logic is no longer needed as we have one connection string for the AWS aurora reader endpoints. The logic adds complexity and a little bit of latency, so it's a win-win to simplify the logic.

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [x] https://github.com/fecgov/openFEC/issues/4835
- [x] WIP PR: https://github.com/fecgov/openFEC/pull/4838

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] Application works as expected, with simplified logic for connecting to the replica.
- [ ] Remove SQLA_FOLLOWER from deva and prod

**Comment by lbeaufort** [comment]
**Env var cleanup**
- [ ] After PR is merged to `dev`, remove `SQLA_FOLLOWERS` env var from `dev`
- [ ] After release branch is cut on 5/5, remove `SQLA_FOLLOWERS` env var from `stage`
- [ ] Add `SQLA_FOLLOWER` env var to `prod`
- [ ] After release is deployed to production on 5/11, remove `SQLA_FOLLOWERS` env var from `prod`

**Comment by cnlucas** [comment]
I am going to remove the schedule A logic as it is no longer needed while keeping the rest of the replica logic in case we need it in the future. I am going to keep the variable named SQLA_FOLLOWERS and will be removing the new SQLA_FOLLOWER variable from our envs.
