### ISSUE TITLE
AF: Add regulations and citations to /legal/docs/ api endpoint

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#4850]
### What we’re after

Add AF regulations and citations to the `/legal/docs/` API endpoint. 
https://api.open.fec.gov/v1/legal/docs/admin_fines/23?api_key=DEMO_KEY

### Related ticket(s)
https://github.com/fecgov/openFEC/issues/4832

### Completion criteria
- [ ] AF regulations and citations should show on the AF `/legal/docs/admin_fines/<admin_fines_no>` endpoint
- [ ] Re-index for admin fines

**Comment by fec-jli** [comment]
Ref: [Add admin fines additional parameters](https://github.com/fecgov/openFEC/pull/4899)

**Comment by AmyKort** [comment]
This may not be a priority for people using the search because AF cases refer to the two regulatory citations that govern the program. Thus, searching by regulatory citation isn't likely to be as useful a filter.
