### ISSUE TITLE
AOs: Fix timestamp issue, change UTC to ET

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4863]
**What we're after:**
We experience significant delays with AOs showing up in the AO search on .gov. This will be a huge blocker to shutting down SAOS. We need to engage with our contractor and have them change their system from UTC to ET.

Talk to contractor about this ticket alongside [timeframe tracking ticket](https://github.com/fecgov/openFEC/issues/4798), also in 21.4

**Completion criteria:**
- [ ] Contractor changes timezone in their system from UTC to ET

**Comment by JonellaCulmer** [comment]
Include DB team in meetings with contractor to discuss.

**Comment by hcaofec** [comment]
There is no UTC in database after meeting with contractor.  The refresh interval for AOs has been updated in this [PR #5241](https://github.com/fecgov/openFEC/pull/5241) to reduce the delay.

So this ticket is closed.
