### ISSUE TITLE
Check if there's null treasurer_name for any committee

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4867]
### What we’re after

Run a query to see if there's any null treasurers for any committees. Example endpoint where we have `treasurer_name`: https://api.open.fec.gov/v1/committees/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&per_page=30&page=1

### Completion criteria

- [x] Findings about treasurer name in the data
- [x] Snapshot of filers without treasurer information

**Comment by PaulClark2** [comment]
Certain types of filers are not required to provide treasurer information. These are: 

- Current activity
    - Communication cost (filer type C): 621 unique filers over time
    - Electioneering communication (filer type E): 321 unique filers over time
    - Independent expenditures reported by persons other than a political committee (filer type I): 1,995 unique filers over time
- Historical activity
    - Nonfederal account of a national party organization (filer type Z): 203 unique filers over time
    - Office accounts (multiple committee types, committee IDs begin C1): 198 unique filers over time

During 2019-2020 we had 5 committees with missing treasurer information. During the same period, we had 840 filers that are not required to provide treasurer information.

Filers that are not required to provide treasurer information:
- Communication cost (filer type C): 2020 - 95filers
- Electioneering communication (filer type E): 2020 - 94 filers
- Independent expenditures reported by persons other than a political committee (filer type I): 2020 - 651 filers
   
Committees that are required to provide treasurer information:
- Delegate (committee type D): 2020 - 1 committee; 0 missing treasurer information
- House (committee type H): 2020 - 5,026 committees; 3 missing treasurer information
- PAC (committee types N and Q): 2020 - 6,771 committees; 0 missing treasurer information 
- Super PAC (committee type O): 2020 - 2,320 committees; 0 missing treasurer information
- Presidential (committee type P): 2020 - 1,228 committees; 0 missing treasurer information
- Senate (committee type S): 2020 - 1,049 committees; 1 missing treasurer information
- Single candidate independent expenditure (committee type U): 2020 - 151 committees; 0 missing treasurer information
- Hybrid PAC (committee types V and W): 2020 - 522 committees;  0 missing treasurer information
- Party (committee types X and Y): 2020 - 618 committees; 1 missing treasurer information

**Comment by PaulClark2** [comment]
Two-year period	|	# committees missing treasurer information
----	|	----
1980	|	294
1982	|	177
1984	|	78
1986	|	44
1988	|	74
1990	|	70
1992	|	63
1994	|	58
1996	|	42
1998	|	22
2000	|	18
2002	|	9
2004	|	9
2006	|	3
2008	|	4
2010	|	4
2012	|	10
2014	|	8
2016	|	10
2018	|	7
2020	|	5
2022	|	3

**Comment by PaulClark2** [comment]
We'll need to develop a way to gracefully handle missing treasurer information.
