### ISSUE TITLE
Add leadership PAC sponsor names to API /committees/ endpoint

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4870]
### What we’re after

Currently, the API gives a list of `sponsor_candidate_ids` as part of the /committees/ endpoint. In order to easily look up the name of the Leadership PAC sponsors, we should also incorporate the candidate names with that list.

Example API call: https://api.open.fec.gov/v1/committees/?api_key=DEMO_KEY

### Related ticket(s)

- [ ] https://github.com/fecgov/fec-cms/issues/4660 (This change will help to add the names to the committees datatable panel.)

### Completion criteria

- [x] Candidate sponsor name is added with the candidate ids

**Comment by hcaofec** [comment]
View script:
```sql
CREATE OR REPLACE VIEW public.ofec_pac_sponsor_name_vw_hc
 AS
 SELECT ofec_committee_detail_mv.committee_id,
    array_agg((ofec_candidate_detail_mv_1.candidate_id::text || ':'::text) || ofec_candidate_detail_mv_1.name::text) AS sponsor_list
   FROM ofec_committee_detail_mv
     LEFT JOIN ofec_candidate_detail_mv ofec_candidate_detail_mv_1 ON ofec_candidate_detail_mv_1.candidate_id::text = ANY (ofec_committee_detail_mv.sponsor_candidate_ids)
  WHERE ofec_committee_detail_mv.sponsor_candidate_ids IS NOT NULL
  GROUP BY ofec_committee_detail_mv.committee_id;
```
