### ISSUE TITLE
Verify what API changes need to be made to /totals/pac-party/ to support PAC/party datatable

### ISSUE THREAD

**Issue by rfultz** [fecgov/openFEC#4871]
**What we're after**
Based on the designs for the PAC/Party totals datatable, we should verify what API changes need to be made to /totals/pac-party/ ([example](https://api.open.fec.gov/v1/totals/pac-party/?sort_nulls_last=false&sort=-committee_id&sort_null_only=false&per_page=20&sort_hide_null=false&api_key=DEMO_KEY&cycle=2022&page=1)) in order to support the designed functionality.

Existing designs can be found in the epic ticket, will be updated in https://github.com/fecgov/fec-cms/issues/4674

**Easier**

- Add committee type filter (NOT existing field -that’s more like category)
- Add min/max receipts filters
- Add min/max disbursements filters
- Add min/max COH filters
- Add min/max debt filters
- First file date output field

**Harder**

- Leadership pac sponsor output and filter (for the two year period)
- Most recent treasurer output and filter (for the 2-year period)
- State output and filter(for the two year period)
- Filing frequency output and filter “”

### Completion criteria
- [x] Update the ticket #4872 for the easy API changes
- [x] Update the ticket https://github.com/fecgov/openFEC/issues/4878 for the harder API changes

### References/resources/technical considerations
Check the example query at the top of this ticket

**Comment by lbeaufort** [comment]
**All output fields needed**
Datatable
- [ ] Committee name
- [ ] Committee Type
- [ ] Total receipts
- [ ] Total disbursements
- [ ] Ending cash on hand
Flyout panel (already including ones above)
- [ ] Designation
- [ ] Most recent treasurer
- [ ] State
- [ ] Filing frequency
- [ ] First file date
- [ ] Total individual contributions
- [ ] Debts owed by committee
- [ ] Coverage end date

**All filters**
- [ ] Committee ID
- [ ] 2-year period
- [ ] Committee type
- [ ] Most recent treasurer
- [ ] Leadership PAC sponsor
- [ ] State
- [ ] Filing frequency
- [ ] Total receipts
- [ ] Total Disbursements
- [ ] Ending Cash on hand
- [ ] Ending debts owed by committee
