### ISSUE TITLE
Test the data for the /totals/pac-party/ (/totals/{committee_type}/) endpoint

### ISSUE THREAD

**Issue by rfultz** [fecgov/openFEC#4873]
### What we’re after

If we're going to build a feature using an endpoint that hasn't been on fec.gov before, we should take some time to look for major data issues before the feature goes live. The totals on /totals/pac-party/ should match the totals on the committee profile page, which come from /committee/<committee_id>/totals/. We could spot-check the data or write a script similar to https://github.com/lbeaufort/scripts/blob/master/compare_candidate_totals.py. 

**Optionally** we could also research why we pulled PACs from the raising by the numbers page - what data issues existed?

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [x] Check to make sure the totals in /totals/pac-party/  match the totals on /committee/<committee_id>/totals/
- [x] Enter any follow-up issues

### References/resources/technical considerations

Candidate totals checking script: https://github.com/lbeaufort/scripts/blob/master/compare_candidate_totals.py.

**Comment by lbeaufort** [comment]
Thank you to @hcaofec for pointing out that these two endpoints have the same underlying materialized view and very similar logic. I took some of the top raising PACs and spot-checked the totals (google doc here: https://docs.google.com/spreadsheets/d/1wJGI579Og-yYuZZTTWmIOnEMHAgAapPnh12XolyCDNo/edit#gid=0) but I think the data looks good to use. We should re-check after we make changes.
