### ISSUE TITLE
Handle unusual data scenarios for PAC and Party overview calculations

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4876]
### What we’re after
Test-driven development. Tests that account for weird math possibilities. e.g.,
- Over 100% (math errors)
- Less than 1% 
- Negative numbers
- Divide by 0
- Null values

(not an exhaustive list—there are likely others)

Research edge cases and weird scenarios and share with Jonella

### Completion criteria

Automated tests exist that test how calculations handle weird data situations

**Comment by PaulClark2** [comment]
I'm sure we'll run into other scenarios, but I'll address these. 

- Over 100% (math errors): We shouldn't display percentages greater than100. We'll need pattern for pattern for "could not calculate." 
- Less than 1%: I think Jonella has a pattern for this. 
- Negative percentages: We shouldn't display negative percentages. We'll need pattern for pattern for "could not calculate." 
- Divide by 0: We'll need pattern for pattern for "could not calculate." 
- Null values: We'll need pattern for pattern for "could not calculate." 

We need to think about how best to display operating expenditure information for certain committees. Maybe it's just disclaimer language. 
- SSFs
    - SSFs generally don't report costs covered by their connected organization
- nonconnected PACs post _Emily's List v FEC_ (No. 08-5422 (D.C. Cir. Sept. 18, 2009)
    - Nonconnected PACs with federal and nonfederal accounts can pay operating expenditures with nonfederal funds that are not reportable to the FEC.

**Comment by lbeaufort** [comment]
I'm sure we'll run into other scenarios, but I'll address these. 
Per our discussion:
- Over 100% (math errors, refunds): **Display >100%** and include explanation in methodology
- Less than 1%:  Jonella has a pattern for this. 
- 0% will display differently.
- Negative percentages: **We will display negative percentages.** The methodology should explain why some percentages could be negative.
- Divide by 0: We'll need pattern for "could not calculate."  The methodology should include "divide by zero" as a potential reason why we couldn't calculate.
- Null values: We'll need pattern for "could not calculate." The methodology should include null values as a potential reason why we couldn't calculate.

**Comment by lbeaufort** [comment]
Included logic in PR: https://github.com/fecgov/openFEC/pull/4894

**Comment by JonellaCulmer** [comment]
@lbeaufort Will we be able to show the exact percentage in all cases, except the last two where we will says "could not calculate" or another equivalent?

To ask another way, do we have to say >100% or can we say 115%?

**Comment by lbeaufort** [comment]
Example of negative denominator: C00178053, 2012
Example of negative numerator: C00332890, 2014
