### ISSUE TITLE
Identify potential cost savings in AWS

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4887]
### What we’re after

Since we moved to Aurora about a year ago, we should use the Cost Explorer and research additional ways to reduce AWS Aurora costs

### Action item(s)

- [ ] Research other options for AWS cost savings

### Completion criteria

- [ ] Document options for decision makers
- [ ] Create tickets for any actionable findings / decisions

### References/resources/technical considerations

(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)

**Comment by lbeaufort** [comment]
Discussions are underway to move the website database from govCloud to FEC's other FedRAMPed commercial account, which should result in significant savings. This would be a fairly involved migration and the DBA team has a lot of competing priorities, so it might not be able to happen right away. 

Past migration (AWS RDS to Amazon Aurora) detailed notes: https://github.com/fecgov/openFEC/issues/4297#issuecomment-620378893

**Comment by PaulClark2** [comment]
Moving this ticket to 15.6. The work described in this ticket is most likely larger than the scope of the website project. The DBA team is working on a plan to migrate our Aurora database. Once this plan is developed the DBA team will coordinate with the website team on the details.

**Comment by cnlucas** [comment]
Moving forward with moving to commercial and tracking that seperately
