### ISSUE TITLE
/legal/docs/admin_fines/ endpoint: Add full name of report_type

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4927]
### Summary

**What we're after:**
_To make it easier to understand the report_type field, the full name of the report type (report_type_full) should be added to the /legal/docs/admin_fines/ endpoint._

Example of report_type field
![Screen Shot 2021-08-04 at 10 25 24 AM](https://user-images.githubusercontent.com/12799132/128198524-f9fe1d06-7c07-48c9-919c-64d507f7d7cc.png)

Example endpoint call:
https://api.open.fec.gov/v1/legal/search/?api_key=DEMO_KEY&case_no=3941&type=admin_fines

### Completion criteria

- [ ] report_type_full is added to the /legal/docs/admin_fines/ endpoint
- [ ] Follow-up ticket to implement this on the front end Admin Fines canonical page

**Comment by johnnyporkchops** [comment]
Issue moved to [fecgov/fec-cms #4912](https://github.com/fecgov/fec-cms/issues/4912) via [**ZenHub**](https://www.zenhub.com/)
