### ISSUE TITLE
Identify and update API endpoints to display filing frequency (status?) and original Form 1 filing dates

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4928]
**What we're after:**
We would like to add additional clarity to committee profiles pages and display:
- Filing frequency
- "Registration date" (TBD on what we actually want to call original form 1 committee filings) Currently available on filings datatable if that helps with the direction of this work.

This work should likely exclude form 5, 7, and 9 filers, at least on the front-end. Need to accommodate for that. Good pairing opportunity with design and possibly content.

### Completion criteria
- [ ] Applicable API endpoints are updated as appropriate to display filing frequency and registration date

**Comment by lbeaufort** [comment]
`filing_frequency` and `first_file_date` are in the committee totals endpoint, which used by the front end for the committee profile page.

https://api-stage.open.fec.gov/v1/committee/C00715375/totals?committee_id=C00715375&cycle=2022&per_page=1&sort_hide_null=True&api_key=DEMO_KEY

**Comment by PaulClark2** [comment]
@lbeaufort we are looking for the first Form 1 receipt date. It was my understanding that `first_file_date` was the date of the first financial form. Can you confirm this?

**Comment by lbeaufort** [comment]
@PaulClark2 thanks for confirming - the `first_file_date` is the first date the committee has in `disclosure.f_rpt_or_form_sub`. I'm not familiar with this table - do you know if it has F1 data?

**Comment by lbeaufort** [comment]
Noting here that this is also the "first filing date" used in the committees data table and `/committees/` endpoint. https://www.fec.gov/data/committees/

**Comment by PaulClark2** [comment]
@lbeaufort is does have F1s. `select * from DISCLOSURE.F_RPT_OR_FORM_SUB where form_tp = 'F1';`

I'm not sure what we do with cases like this. The first F1 date is after the first financial form. I don't know how common this is. 

`select form_tp, min(receipt_dt) from DISCLOSURE.F_RPT_OR_FORM_SUB where form_tp in ('F1', 'F3X') and cand_cmte_id = 'C00010603' group by form_tp;`

FORM_TP |MIN(RECEIPT_DT)
----|----
F1 | 19760729
F3X | 19750310

**Comment by lbeaufort** [comment]
@PaulClark2 the API is using min() so in this case it uses 19750310: https://www.fec.gov/data/committees/?q=C00010603

```
SELECT f_rpt_or_form_sub.cand_cmte_id AS cmte_id,
        min(f_rpt_or_form_sub.receipt_dt) AS first_file_date,
        max(f_rpt_or_form_sub.receipt_dt) AS last_file_date,
        max(f_rpt_or_form_sub.receipt_dt) FILTER (WHERE ((f_rpt_or_form_sub.form_tp)::text = 'F1'::text)) AS last_f1_date
        FROM disclosure.f_rpt_or_form_sub
        GROUP BY f_rpt_or_form_sub.cand_cmte_id
```

**Comment by lbeaufort** [comment]
Leadership has asked that we specifically use F1 as registration date, not first file date. Like we have `last_f1_date` we can add `first_f1_date`:

```sql
min(f_rpt_or_form_sub.receipt_dt) FILTER (WHERE ((f_rpt_or_form_sub.form_tp)::text = 'F1'::text)) AS first_f1_date
```
