### ISSUE TITLE
Check logs sprint 15.6 - week 1 (8/18/21)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4931]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Related #4924

**Comment by rfultz** [comment]
**FEC-CMS:**
package.json: 1
- Low: request - Insecure encryption (due 11/18/21) (https://github.com/fecgov/fec-cms/issues/4839)

requirements.txt: 1
- (existing) Medium: urllib - Regular Expression Denial of Service (https://github.com/fecgov/fec-cms/issues/4803)

**OPEN-FEC:**
package.json: None
requirements.txt: None
flyway: None

**FEC-EREGS:**
package.json: None

requirements_dev.txt: 1
- **High**: django-debug-toolbar - SQL Injection - https://github.com/fecgov/fec-eregs/issues/615

requirements.txt: 1
- existing: https://github.com/fecgov/fec-eregs/issues/613

requirements-parsing.txt: 3 critical, 14 high, 15 medium, 3 low

FEC-PATTERN-LIBRARY:
package.json: None

Search logs:
No log results for "user change"

Cloud.gov Dashboard:
9 deployer accounts, same as last week.

Off-boarding:
One request, closed
