### ISSUE TITLE
Check logs sprint 15.6 - week 2 (8/25/21)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4932]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Related #4931

- [x] Make new tickets for  week 1 , 2 , 3 and 4 of ~15.7 sprint~ PI 15 innovation sprint.

**Comment by pkfec** [comment]
**FEC-CMS:**
package.json: 1

Low: request - Insecure encryption (due 11/18/21) ([Snyk: Low] Request - Insecure Encryption (due 11/18/21, 16.3) fec-cms#4839)

requirements.txt: 1

Medium: urllib - Regular Expression Denial of Service ([Snyk: Medium ] Regular Expression Denial of Service (due 10/20/2021 ) fec-cms#4803)

**OPEN-FEC:**
package.json: None
requirements.txt: None
flyway: None

**FEC-EREGS:**
package.json: None

requirements_dev.txt: 1

High: django-debug-toolbar - SQL Injection - [SNYK: HIGH] - django-debug-toolbar - SQL Injection (due 9/18/21) fec-eregs#615

requirements-parsing.txt: 3 critical, 14 high, 15 medium, 3 low

**FEC-PATTERN-LIBRARY:**
package.json: None

**Search logs:**
No log results for "user change"

**Cloud.gov Dashboard:**
9 deployer accounts, same as last week.

**Off-boarding:**
None
