### ISSUE TITLE
Legal Search Outages on 8/19

### ISSUE THREAD

**Issue by djgarr** [fecgov/openFEC#4938]
### What we’re after

Two outages on PROD-/legal/search/ reported on 8/19/21 between 3:10a-7:39a and 9:10a-9:24a. When trying to access the AO section of Legal Resources, received a 504 error.

### Completion criteria

- [ ] Investigate outage

**Comment by pkfec** [comment]
Reached out to cloud.gov team regarding the 4 hours ES outage in our Production environment.

**Comment by pkfec** [comment]
cloud.gov team confirmed that the ES cluster went down (red status on cloudwatch graphs on 08/19/2021 from 03:09:16 AM  till  07:24:16 AM). There is no way to know from cloud.gov/AWS console to see why the ES cluster went red this morning!
