### ISSUE TITLE
Check logs sprint 16.1 - week 1 (09/29/21)

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#4952]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Related #4940

**Comment by fec-jli** [comment]
FEC-CMS:
package.json: 1 Low
Low: site Scripting (XSS) in datatables.net(due 12/28/21) ([Snyk: Low] site Scripting (XSS) in datatables.net (due 12/28/21) fec-cms#????)

requirements.txt: 1
Medium: urllib -  [[Snyk: Medium ] Regular Expression Denial of Service (due 10/20/2021 )](https://github.com/fecgov/fec-cms/issues/4803)

OPEN-FEC:
package.json: None
requirements.txt: None
flyway: None

FEC-EREGS:
package.json: None
requirements.txt: 1 High
High: django - [[SNYK: HIGH] HTTP Header Injection (due 10/19/21)](https://github.com/fecgov/fec-eregs/issues/626)
requirements_dev.txt: None
requirements-parsing.txt: 3 critical, 15 high, 15 medium, 3 low

FEC-PATTERN-LIBRARY:
package.json: None

Search logs:
No log results for "User change"

Cloud.gov Dashboard:
9 deployer accounts, same as last week.

Off-boarding:
None

**Comment by fec-jli** [comment]
It is done and close.
