### ISSUE TITLE
Update Flask to 2.0.1 (or latest 2.x)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4958]
### What we’re after

Update Flask to 2.0.1 (or latest 2.x). See https://github.com/pallets/flask/releases

Hopefully after we upgrade Flask to lates  version, we can unpin Jinja2 3.0.3 and Flask will pickup lates Jinja2.
https://github.com/fecgov/openFEC/pull/5091

### Related ticket(s)

- https://github.com/fecgov/openFEC/issues/4950

### Action item(s)

- [ ]  Adrdess any Pytest errors related to other package dependencies.

### Completion criteria

- [ ] Flask is updated to Flask to 2.0.1 (or latest 2.x)

### References/resources/technical considerations

[Changes for 2.0](https://flask.palletsprojects.com/en/2.0.x/changes/#version-2-0-0)

**Comment by rfultz** [comment]
[Changes for 2.0](https://flask.palletsprojects.com/en/2.0.x/changes/#version-2-0-0)
