### ISSUE TITLE
Reload all AOs cannot finish on dev space

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4971]
Currently, we schedule three tasks to reload/refresh AOs:
Task 1: Every 5 minutes during 6am-7pm(EST)everyday--when there is modified AO, reload all AOs from recently modified starting AO number to the latest AO.
Task 2: Daily at 9pm(EST) except Sunday: when there is modified AO in the past 24 hour, reload all AOs.
Task 3: Every Sunday at 9pm(EST)--reload All AOs.

Issues we have now:
1)Usually,It will take 20-30 minutes to reload all AOs, depends on space.
Sometime it is fail to reload all AOs on dev space.
2)When one AO get modify, AO citations go back and forward, it is difficult to find the earliest AO number be referenced. We have to reload all AOs.

### Action item(s)

- [x] Research to find a good way to get the the earliest AO number be referenced when AO is modified (database side or python code side)
- [x] re-design and implement the reload AO logic

### Completion criteria
- [x] When AO is modified, all AOs referenced by this can be reload to ES correctly and efficiently.
- [x] Send AO detail info and reload message to Slack

**Comment by JonellaCulmer** [comment]
We upgraded the worker memory to 1G in openFEC #5047

**Comment by fec-jli** [comment]
upgrade memory to 1 G on dev space. fix the issue. closed
