### ISSUE TITLE
Make document formatting consistent in documents column

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4982]
**What we're after:**
While reviewing the AF datatable and canonical page report type work, I wanted to compare to the filings datatable and my eye twitched with the inconsistency of labeling for documents. Some are capitalized, sentence case, or random capitalization. 

All documents should be consistently formatted and in title case. Pair with content team for title case for document labels.

**Completion criteria:**
- [ ] All filing document labels are title case

![Screen Shot 2021-10-23 at 5.33.17 PM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/9747f1a4-347e-4a44-916a-889dab4fbd64)

**Comment by hcaofec** [comment]
https://github.com/fecgov/openFEC/blob/develop/webservices/utils.py#L377

**Comment by hcaofec** [comment]
https://github.com/fecgov/openFEC/blob/develop/webservices/decoders.py#L18

**Comment by fec-jli** [comment]
note by Jonella:
https://docs.google.com/document/d/1QntwhFYqFYa6MG3q_hmJxm991ocAz2QNd5WbCvo0Vd8/edit
