### ISSUE TITLE
Upgrade Aurora postgresql 10 to Aurora postgresql 13 on `dev` space

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4993]
### What we’re after

Moving to Aurora Postgres 13 will improve performance, and is a helpful step to make moving to the commercial account in AWS easier.

The DBA team has created an Aurora Postgres 13 instance for the website team to test.  We are mostly interested to find out:

- Performance between  WEB/APP servers reside in Cloud.Gov and RDS in AWS commercial
- API code works with Aurora Postgres13  (Hopefully minimal to no changes to Python code or libraries)
- Talk to @lbeaufort or @rjayasekera for connection string information

Data should be in-sync with GovCloud dev-aurora
Please let us know of any issues.  Thanks

### Action item(s)

- [x] Upgrade Mac OS to Monterey
    - Per [homebrew docs](https://formulae.brew.sh/formula/postgresql@13#default), make sure you're running Mac OS Big Sur or Monterey
    - Upgrade from Catalina --> Bigsur
    - Upgrade from Bigsur --> Monterey, restart Mac
    - Upgrade Xcode to latest version and restart Mac (take hours)

- [x] Upgrade local database to Postgres 13
    - `brew uninstall postgresql@10`
    - `brew install postgresql@13`
    - Export/update postgres13 PATH in bash_profile
    - `brew services stop postgresql@10`
    - `brew services start postgresql@13`

- [x] Setup local api env and test it
    - Create new Python 3.7.12 virtualenv’s on openFEC
    - `dropdb cfdm_unit_test`
    - `createdb cfdm_unit_test`
    - `dropdb cfdm_test`
    - `createdb cfdm_test`
    - `invoke create_sample_db` (will run migration)
    - `export SQLA_CONN=postgresql://:@/cfdm_test`
    - `pip install -r requirements.txt`
    - `pip install -r requirements-dev.txt`
    - `npm install -g swagger-tools`
    - `npm install`
    - `npm run build`
    - `pytest`
    - `./manage.py runserver` and test local api
    
- [x] Test read/write connection to new AWS database from local API
    - [x] Test migration. Could run a zero-impact migration file and delete from flyway history
    
- [x] Switch to Aurora Postgres 13 on dev space
   - [x] Follow wiki update SQLA_CONN,SQLA_FOLLOWER,SQLA_FOLLOWERS environment variables to Aurora Postgres 13: [https://github.com/fecgov/openFEC/wiki/Switch-out-cf-environment- variables](https://github.com/fecgov/openFEC/wiki/Switch-out-cf-environment-variables)
   - [x] Update Circleci environment variables
   FEC_BASTION_DEV_TUNNEL:
   ssh -L 5555:<new db-url> -Nf ec2-user@<Bastion Host IP> || true
   - [x] Rebuild deploy on circleci and make sure deployment successfully

- [x] Test read/write connection strings in cloud.gov dev space
    - [x] Test migration, manually run refresh_MV command: 
    `cf run-task api 'python manage.py refresh_materialized' --name refresh-<date>`
    - [x] run a zero-impact migration file and delete from flyway history
    - [x] Make sure celery/MV refresh tasks work, such as: Daily refresh_materialized_views, refresh_most_recent_legal_doc, reload_all_aos_daily_except_sunday, reload_all_aos_every_sunda.
    

### Completion criteria

- [x] API runs successfully while connected to a database running Aurora Postgres 13

**Comment by cnlucas** [comment]
I had issues upgrading from PG10 to PG13. I tried the `brew postgresql-upgrade-database` and just uninstalling the old versions which seems to work for most people, but I kept seeing 13 start successfully, but then there's a 512 bad status error. I had to force uninstall every PG version and delete the old PG directories in usr/local/var. I then re-installed 13 and that worked for me.
