### ISSUE TITLE
Research: Modify API to return list of JFC participant committees

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4997]
### What we’re after
In order to provide a full list of committees that participate in a JFC on committee profile pages (About this committee tab) we need to make some changes to the API. 

The endpoint needs to be able to return a list instead of a single result. 

This is the endpoint that would require the changes: `/committee/{committe_id}/history/{cycle}/`

**Related ticket(s):**
- https://github.com/fecgov/fec-cms/issues/4874
- https://github.com/fecgov/fec-cms/issues/4980

**Action items:**
- Check committee history MV
- How is this stored in the database

**Completion criteria:**
- [x] Research and document changes to the API that would need to be made that would allow us to display a list of committees instead of a single result

### References
Slack conversation here: https://fecgov.slack.com/archives/C3W9XBBJL/p1638463737199800
API call: https://api.open.fec.gov/v1/committee/C00750166/history/2022/?page=1&sort_hide_null=false&sort=-cycle&per_page=20&api_key=DEMO_KEY&sort_null_only=false&election_full=true&sort_nulls_last=false

### About this committee - Committee profile page
![Committee - About](https://user-images.githubusercontent.com/31663028/143883820-66a0e92d-6c05-4df6-857f-ffd95351cfb3.png)

**Comment by lbeaufort** [comment]
@JonellaCulmer FYI there's some additional information in this ticket: https://github.com/fecgov/openFEC/issues/4861. These could probably be combined.

**Comment by pkfec** [comment]
@PaulClark2 needed time to analyze current JFP data on the backend systems. After Paul's back from vacation reach out him and have a technical discussion with front & back end teams

**Comment by johnnyporkchops** [comment]
@PaulClark2 wrote:
`I don't think we currently do a good job of capturing all this information in the database. I'll need to check with Ryan Lanz to ensure that our Pass I procedures capture all participants and how we handle Form 1 amendments with (or without) participants listed. We also need to confirm that electronic filers are always providing a full list of participants when they file amendments. We probably need to do a fairly deep dive into the data before we make this feature available to the public. `

`I like the idea, but I think we might need to implement some changes to ensure accurate and consistent data.
I don't want to hold things up. It might be helpful if Helen or someone else can start looking into this`
cc: @hcaofec

**Comment by hcaofec** [comment]
In form_1, filed_cmte_dsgn,  jntfndrsg_cmte_flg are used to make JFC.
JFC is stored in form_1s table and referred to parent table using link_id.

**Comment by hcaofec** [comment]
We can move forward to add this feature to Committee Profile page.  JFC participant committees can be found in fec_form_1s_vw.  It can be found from these two columns: join_cmte_id and joint_cmte_nm. Column most_recent_filing_flag indicates the latest version.

@PaulClark2  Please feel free to add your thoughts.

**Comment by hcaofec** [comment]
Follow up ticket has been created. [#5120](https://github.com/fecgov/openFEC/issues/5120)
