### ISSUE TITLE
Update Flyway

### ISSUE THREAD

**Issue by rfultz** [fecgov/openFEC#5011]
### What we’re after

Our Flyway version is a few behind. While we aren't affected by the [Log4Shell](https://flywaydb.org/blog/flyway-log4j-vulnerability) vulnerability, we should still get ourselves closer to current.

### Related ticket(s)

None?

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)
- [ ] 

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] 

### References/resources/technical considerations

(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)

**Comment by fec-jli** [comment]
Thanks @rfultz create this ticket.
This maybe combine with this issue?
[https://github.com/fecgov/openFEC/issues/5006](https://github.com/fecgov/openFEC/issues/5006)

**Comment by fec-jli** [comment]
Please see this issue:
[https://github.com/fecgov/openFEC/issues/5006](https://github.com/fecgov/openFEC/issues/5006)
