### ISSUE TITLE
Treemap and all elections totals table: Discuss new endpoints for /by_state and /by_state/by_district

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#5026]
**What we're after:**
We need to create new endpoints to support the work for the House and Senate treemap and all elections totals tables (see screenshots below). To do this, we will riff off the /totals/by_office/by_state endpoint. We would want to be able to grab all the states for senate elections, and use by_state/by_district to get states for House elections.

Proposed  endpoints will be:
- /candidates/totals/by_office/by_state
- /candidates/totals/by_office/by_state/by_district

**Action items:**
- Pass the two-year period as a filter grouped by state and district
- We have total receipts, total disbursements. 
- Add cash on hand and debts to this endpoint
- Should be no database work, fewer moving parts
- Needs to be sortable

**Completion criteria:**
- [ ] Have a meeting to discuss best way to create endpoint.
- [ ] Create a ticket to implement new  endpoints

**Related tickets**
https://github.com/fecgov/openFEC/issues/5027

**This is the "treemap: feature mockup:**
https://github.com/fecgov/fec-epics/issues/213
<img width="680" alt="Screen Shot 2022-03-10 at 7 40 35 PM" src="https://user-images.githubusercontent.com/5572856/157779574-c9a9afc0-fbec-4f5c-acb1-a0247c5bcd8f.png">

<hr>

**This is the All elections totals table  mockup:**
https://github.com/fecgov/fec-epics/issues/216
<img width="802" alt="Screen Shot 2022-03-10 at 7 46 52 PM" src="https://user-images.githubusercontent.com/5572856/157780125-06b3fde9-b318-44b0-9949-56a34a7610c5.png">

**Comment by fec-jli** [comment]
Another new endpoint: 
/candidates/totals/{aggregate_by}

if aggregate_by =by_office:(==>/candidates/totals/by_office)
(group_by:election_year,office)


if aggregate_by =by_party: (==>/candidates/totals/by_office/by_party)
(group_by:election_year,office,party)

if aggregate_by=by_state: (==>/candidates/totals/by_state)
(group_by:election_year,office,state)

if aggregate_by=by_district:(==>/candidates/totals/by_state/by_district)
(group_by:election_year,office,state,district)
