### ISSUE TITLE
Modify API to show select totals of schedule A

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#5028]
**What we're after:**
Show totals of individual contributions, transfers from other committees and other committee contributions for all House and all Senate across time feature. 

Considerations:
- Which endpoint(s) will we use or will this be a new endpoint(s)? 
- Is it /candidates/totals/by_office/
- Can we use min_election_year and max_election_year instead of including each election year into the query?

Line numbers:
- Itemized individual contributions (for the clickthrough): Line 11a(i)
- Transfers from other committees: Line 12
- Other committee contributions: Line 11c

**Filter option additions:**
- min_election_year
- max_election_year
- election_full=false
- Make sure that we don't break this endpoint /candidates/totals/by_office/by_party/. It should continue to have running totals for an election year. Raising by the numbers raising summary feature uses this: https://www.fec.gov/data/raising-bythenumbers/

**Completion criteria:**
- [ ] API now provides House and Senate totals across all elections by two-year period and grouped by individual contributions, transfers from other committees, and other committee contributions

**Comment by patphongs** [comment]
@fec-jli You were asking earlier about the candidate election as a boolean flag for this. I think you'll need the `is_active_candidate=true` boolean when passing any `election_year` parameters. Especially for `min_election_year` and `max_election_year`.

**Comment by fec-jli** [comment]
The PR [https://github.com/fecgov/openFEC/pull/5050](https://github.com/fecgov/openFEC/pull/5050) finished part 1 of this ticket.
