### ISSUE TITLE
Research modifying the API to provide top-level IEs

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#5029]
**What we're after:**
We'd like to display top-level IEs on the new House and Senate pages. What API work needs to happen in order for this feature to be displayed. 

**Action items:**
- Which IEs should be included in these figures? 24- and 48-hour reports and/or regularly scheduled reports? 3x filers only? Form 5 filers?
- Research and document best path forward
- Have a conversation on the business use case. Pair with @djgarr 

**Completion criteria:**
- [x] Research and next steps are identified and documented
- [x] Followup ticket to implement is opened

**Mockup:**
![Screen Shot 2022-01-27 at 2 09 45 PM](https://user-images.githubusercontent.com/31663028/151427433-c1e4ba3f-7737-4aed-89de-a14defcb3dc0.png)

**Comment by cnlucas** [comment]
Closing in favor or #5039
