### ISSUE TITLE
Accommodate for district changes in API

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#5031]
**What we're after:**
We are currently receiving data for the newly created districts but the API is not currently looking for them. We need to modify the API to provide these new districts so they appear on the election search page. 

Some districts have also been removed. We need to determine how to accommodate for those changes as well. 

**Added districts:**
- Texas 37 and 38 (+2)
- Colorado 08 (+1)
- Florida 28 (+1)
- Montana 02 (+1)
- North Carolina 14 (+1)
- Oregon 06 (+1)

**Lost districts:**
- California 52 (-1)
- New York 26 (-1)
- Illinois 17 (-1)
- Pennsylvania 17 (-1)
- Ohio 15 (-1)
- Michigan 13 (-1)
- West Virginia 2 (-1)

**Call:**
https://api.open.fec.gov/v1/elections/search/?api_key=DEMO_KEY&per_page=100&cycle=2022

**Action items:**
- [x] Discussion on  business case with Paul
- [x] Determine whether supporting table changes are necessary 
- [x] Check the front-end election search listing to make sure the functionality is in sync with what the API gives us

**Completion criteria:**
- [x] Pair with Paul on best practice for ensuring lost districts would appear for previous cycles
- [x] API provides accurate list of districts following census changes in election search

**Comment by PaulClark2** [comment]
You should be able to confirm the list from data on the Census Bureau's website. 

https://www.census.gov/library/visualizations/2021/dec/2020-apportionment-map.html
https://www.census.gov/data/tables/2020/dec/2020-apportionment-data.html
https://www2.census.gov/programs-surveys/decennial/2020/data/apportionment/apportionment-2020-table01.xlsx

**Comment by hcaofec** [comment]
After backend table is updated, api and website reflects the change now.

https://api.open.fec.gov/v1/elections/search/?office=house&sort_hide_null=false&sort_null_only=false&per_page=40&sort_nulls_last=false&cycle=2022&api_key=DEMO_KEY&page=1&sort=sort_order&sort=district&state=NC
![image](https://user-images.githubusercontent.com/24396726/159500768-0848e512-d7e9-4c89-af7c-e4ab0b2781fb.png)

**Comment by hcaofec** [comment]
https://www.fec.gov/data/elections/?cycle=2022&state=TX


![image](https://user-images.githubusercontent.com/24396726/159501126-1c0a6bb8-ff9d-4250-a449-1fe9eeffe7fe.png)
