### ISSUE TITLE
Create an endpoint to aggregate total independent expenditures by cycle

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5039]
### What we’re after
We would like to have an endpoint calculate the total amount of IE's spent in support or opposition of all candidates in a candidate_office(entity_type) by cycle. Currently, our endpoints support aggregation by candidate, but not aggregation without breaking down by candidate.  We should create a new /schedules/schedule_e/totals/by_cycle/ which will need to be able to be filtered by support or oppose and candidate_office. 

We want the endpoint to include both Form 3X and Form 5 regularly scheduled reports (& not include 24/48 notices) and be able to support this front end work:
![image](https://user-images.githubusercontent.com/66386084/152265999-5388015e-11b4-4e1e-b18f-e109c335c266.png)

### Related ticket(s)

- [4061](https://github.com/fecgov/openFEC/issues/4061)
- [5029](https://github.com/fecgov/openFEC/issues/5029)

### Action item(s)

- [ ] /schedules/schedule_e/totals/by_cycle/  endpoint is created, with support and oppose totals, filters by office sought, election year
- [ ] testing 
- [ ] front-end ticket this API work is blocking is created

### References/resources/technical considerations
Consistent with Paul's point in [4061](https://github.com/fecgov/openFEC/issues/4061) we should calculate "other spending" totals on the back-end for consistency and performance improvement.

**Comment by patphongs** [comment]
This work is difficult and we need to re-evaluate this part of the feature.
