### ISSUE TITLE
Add auto test case into AggregateByOfficeByPartyView

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#5062]
### What we’re after
In this PR: [https://github.com/fecgov/openFEC/pull/5056](https://github.com/fecgov/openFEC/pull/5056)
we add election_full filter, we need add auto test case for this filter.

### Related PR(s)
[https://github.com/fecgov/openFEC/pull/5056](https://github.com/fecgov/openFEC/pull/5056)

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)
- [ ] Add auto test case for `election_full` filter
- [ ] Update or add necessary test case.  

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] Make sure all filters are covered by auto test case

**Comment by cnlucas** [comment]
This filter doesn't seem to be working correctly. After conferring with @fec-jli, we should instead remove the totals/by_office and totals/by_party endpoints as our current totals endpoint should be able to support those aggregates after this work https://github.com/fecgov/openFEC/pull/5090
