### ISSUE TITLE
[SNYK: Medium] com.fasterxml.jackson.core:jackson-databind Denial of Service (DoS)(Due 04/20/2022)

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#5064]
### Overview

[com.fasterxml.jackson.core:jackson-databind](https://github.com/FasterXML/jackson-databind) is a library which contains the general-purpose data-binding functionality and tree-model for Jackson Data Processor.

Affected versions of this package are vulnerable to Denial of Service (DoS) when using JDK serialization to serialize and deserialize JsonNode values. It is possible for the attacker to send a 4-byte length payload, with a value of Integer.MAX_VALUE , that will eventually cause large buffer allocation and out of heap memory.

https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698

### Detailed path
Introduced through: unknown:unknown@0.0.0 › org.flywaydb:flyway-commandline@8.4.3 › com.microsoft.azure:msal4j@1.10.1 › com.fasterxml.jackson.core:jackson-databind@2.12.1

### Completion criteria
- [ ]  upgrade com.fasterxml.jackson.core:jackson-databind@2.13.1, @2.12.6

**Comment by fec-jli** [comment]
We upgraded flyway to 8.5.2 and fixed this issue in 
PR: [https://github.com/fecgov/openFEC/pull/5073](https://github.com/fecgov/openFEC/pull/5073)
