### ISSUE TITLE
Check logs Sprint 17.4 week 2 (03/09/2022)

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#5067]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Ref: [Check logs sprint 17.4 week 1](https://github.com/fecgov/openFEC/issues/5066)

- [ ]  Make new tickets for sprint 17.5 weeks1 & 2

**Comment by hcaofec** [comment]
**FEC-CMS:**
package.json: 0

requirements.txt: 4 Medium, 3 Low
[Snyk:Medium]: django Denial of Service (DoS) will solve in https://github.com/fecgov/fec-cms/issues/5030
[Snyk:Medium]: [django Cross-site Scripting (XSS)] will solve in https://github.com/fecgov/fec-cms/issues/5030
[Snyk:Medium]: [pillow Improper Input Validation] will solve in https://github.com/fecgov/fec-cms/issues/5071
[Snyk:Medium new]: [gitpython Regular Expression Denial of Service (ReDoS)] will solve in https://github.com/fecgov/fec-cms/issues/5081

[Snyk:Low]: [django Directory Traversal]will solve in https://github.com/fecgov/fec-cms/issues/5030
[Snyk:Low]: [django Information Exposure]will solve in https://github.com/fecgov/fec-cms/issues/5030
[Snyk:Low]: [wagtail Information Exposure] will solve in https://github.com/fecgov/fec-cms/issues/5043

**OPEN-FEC:**
package.json: 1 Medium
[SNYK: Medium]: [@braintree/sanitize-url Cross-site Scripting (XSS)].  https://github.com/fecgov/openFEC/issues/5075  

requirements.txt: 1 High, 2 Medium
[SNYK: High ] [ujson Out-of-Bounds Write] (https://github.com/fecgov/openFEC/issues/5058)
[Snyk: Medium]: [Celery Stored Command Injection] (https://github.com/fecgov/openFEC/issues/5017)
[Snyk: Medium]: [gitpython Regular Expression Denial of Service (ReDoS)] (https://github.com/fecgov/openFEC/issues/5065)

**FEC-EREGS:**
package.json: 0
requirements.txt: 0
requirements-parsing.txt: 1 High
[SNYK: High]: [networkx Deserialization of Untrusted Data]. (https://github.com/fecgov/fec-eregs/issues/674)

**FEC-PATTERN-LIBRARY:**
package.json: None

Search logs:
No log results for "User change"

Cloud.gov Dashboard:
9 deployer accounts, same as last week.

Off-boarding:
None for this week
