### ISSUE TITLE
Define MUR_category values

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5106]
### What we’re after

We want to mirror the document type MUR search with what we already have for the AO document type filter. Category is being passed from a fetch on the front end to the API. Example call: https://fec-dev-api.app.cloud.gov/v1/legal/search?api_key=DEMO_KEY&type=advisory_opinions&ao_category=C&q=spending&search=spending 
CMS URL: https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=C&q=spending&search=spending 
MUR document types (same as `category` in the API)
![image](https://user-images.githubusercontent.com/66386084/164072735-cc160912-aa0c-4b25-9d1b-d5e512e0812a.png)

To start this process, we need to research and define the category values. 

### Completion criteria
- [x] MUR database checked, confirm and list all the document types we have for MURs. 
- [ ] Update openFEC #5118 ticket to prototype a document type filter in elacticsearch

**Comment by fec-jli** [comment]
[mur_doc_category_list.csv](https://github.com/fecgov/openFEC/files/8710053/mur_doc_category_list.csv)

**Comment by fec-jli** [comment]
(Srini's query:)
`select distinct c.doc_order_id, c.category
from fecmur.document d
join fecmur.case v on (d.case_id = v.case_id)
join fecmur.doc_order c on (d.doc_order_id = c.doc_order_id)
where v.case_type='MUR'
order by doc_order_id;`



<img width="400" alt="case_doc_category_list" src="https://user-images.githubusercontent.com/24395751/174933756-3ba35e82-6426-431e-a6a8-81cdc9c51632.png">

**Comment by fec-jli** [comment]
There are 333 rows with doc_order_id = null
`select count(*) from fecmur.document
where doc_order_id is null `

**Comment by pkfec** [comment]
PR https://github.com/fecgov/openFEC/pull/5179 merged. Closing this issue
