### ISSUE TITLE
Research elasticsearch DSL

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5107]
**What we’re after:**
In order to start work on the legal web search app, we need to do research on the elasticsearch DSL

**Action item(s):**
- [x]  Research is conducted and documented as necessary
- [x] Sync(s) held to get the back-end team on the same page about elasticsearch DSL 

**Future work:**
- [x] Prototype elasticsearch DSL to filter by citations (openFEC #5111)

**Comment by fec-jli** [comment]
test `legal/search` endpoint:
[test urls](https://docs.google.com/spreadsheets/d/1l3YKu-oBzOwBHH986YdyiYaSJTFdJBNxitZkt_Ew4zA/edit#gid=0)
