### ISSUE TITLE
Prototype using Elasticsearch DSL to filter by election cycle

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5108]
### What we’re after

In order to create the legal web search app, we need to prototype using Elasticsearch DSL to filter by election cycle.  We need to understand our current code using Elasticsearch DSL and work through some of their documentation.

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [ ] #5107 

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)
- [ ] Research using Elasticsearch DSL to filter by election cycle 
- [ ] Create prototype
- [ ] Create ticket to sync with other devs on creation, actions moving forward

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] Prototype is created
- [ ] Sync ticket is created

**Comment by patphongs** [comment]
This feature was not very low on the list of desired features. So I am closing this issue.
