### ISSUE TITLE
Add MUR Document Type filter

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5119]
### What we’re after

We want to mirror the document type MUR search with what we already have for the AO document type filter. For the legal/search endpoint we want to filter keyword search by document type (passing type = murs and mur_category.)

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [ ] #5106 
- [ ] #5118

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)
- [ ] 

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] legal/search endpoint supports filtering by document type
- [ ] ticket for front-end work is created

### References/resources/technical considerations

(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)

**Comment by fec-jli** [comment]
see ticket: [https://github.com/fecgov/openFEC/issues/5118](https://github.com/fecgov/openFEC/issues/5118)
