### ISSUE TITLE
Add filter functionality by disposition

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#5155]
### What we’re after
(Summarize why this work needs to happen)

### Related ticket(s)
(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [ ] 

### Action item(s)
(These are the smaller tasks that should happen in order to complete this work)
- [ ] 

### Completion criteria
(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] 

### References/resources/technical considerations
(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)

**Comment by fec-jli** [comment]
Ref PR: [Update results display for archive MURs](https://github.com/fecgov/fec-cms/pull/5440)
