### ISSUE TITLE
Research: 'sort_nulls_last' is not working properly in schedules/schedule_a/ or schedules/schedule_b/

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#5158]
### Summary
api user report a bug about pagination issue in schedules/schedule_a/
user said: "the pagination objects starting in year 2004 are much, much larger than the page I reach when last_indexes = null. For example, 2004 reached a null index at page 2646 (out of 16893); 2006 reached a null last index at page 4651 (out of 67531). Similar results occur when I re-attempt my data collection process for these election cycles. "

Example api call:
https://api.open.fec.gov/v1/schedules/schedule_a/?two_year_transaction_period=2006&sort_hide_null=false&sort_null_only=true&api_key=DEMO_KEY&sort=-contribution_receipt_date&per_page=100&last_index=1010320060000288692

### Refer ticket
#5198 

### Action item(s)
none

front-end sample urls:
https://www.fec.gov/data/receipts/?data_type=processed&two_year_transaction_period=2006
api call:
https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&data_type=processed&two_year_transaction_period=2006&sort=-contribution_receipt_date&per_page=30

https://api.open.fec.gov/v1/schedules/schedule_a/?two_year_transaction_period=1980&api_key=DEMO_KEY&per_page=12&sort=-contribution_receipt_date&sort_null_only=false&sort_hide_null=false

http://127.0.0.1:5000/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&data_type=processed&two_year_transaction_period=1980&sort=-contribution_receipt_date&per_page=12&last_index=3061920110000375492&sort_null_only=true

**Comment by hcaofec** [comment]
For this particular api call,  1010320060000288692 is the last record.  Among schedule A records from 2005 to 2006,  1010320060000288692 will be returned if "select min(sub_id)".  In a descending order, that is the last row.  So  the below api returns no result. 
https://api.open.fec.gov/v1/schedules/schedule_a/?two_year_transaction_period=2006&sort_hide_null=false&sort_null_only=true&api_key=DEMO_KEY&sort=-contribution_receipt_date&per_page=100&last_index=1010320060000288692

**Comment by hcaofec** [comment]
"sort_nulls_last" has been disabled in SA and SB endpoint.  By default, null value sorts as if larger than non-null value in PG.  The behavior described in this ticket is not a bug.  

This ticket is closed without action.
