### ISSUE TITLE
Enable string keyword text filter for committees

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5160]
### Summary

**What we're after:**
_As a researcher, I want to be able to filter the following endpoints by keyword or committee ID so that I can return a dataset that is specific to the committee name keyword I'm looking for._

We want to try enabling this text filter in filing endpoint before moving this to other endpoints. 
- `/filings/` and `/efile/filings/`, we want to search by keyword or committee ID for `filer_name`

In addition, we want to research performance in the follow-up work for these filters that also do not have the capability to search by string keyword text or committee ID for these endpoint fields:

- `/schedules/schedule_a/` and `/schedules/schedule_a/efile/`, we want to search by keyword or committee ID for `recipient_name`
- `/schedules/schedule_b/` and `/schedules/schedule_b/efile/`, we want to search by keyword or committee ID for `spender_name`
- `/schedules/schedule_e/` and `/schedules/schedule_e/efile/`, we want to search by keyword or committee ID for `spender_name`
- `/filings/` and `/efile/filings/`, we want to search by keyword or committee ID for `filer_name`
- `/reports/presidential/` and `/efile/reports/presidential/`, we want to search by keyword or committee ID for `filer_name`
- `/reports/house-senate/` and `/efile/reports/house-senate/`, we want to search by keyword or committee ID for `filer_name`
- `/reports/pac-party/` and `/efile/reports/pac-party/`, we want to search by keyword or committee ID for `filer_name`

### Completion criteria

- [x] Filings endpoint listed above has the capability search by string keyword or committee ID
- [x] Tickets created for follow-up work for the other endpoints (performance research is completed)

**Comment by JonellaCulmer** [comment]
@fec-jli Can this be closed?

**Comment by fec-jli** [comment]
https://docs.google.com/spreadsheets/d/1AkQjXA2XMQfxlRyinSY0uynhf2ZRMh7l_BTWdJgHzXY/edit#gid=0
