### ISSUE TITLE
Research logic for displaying states for senate elections in all totals data table 

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5162]
### What we’re after
We need to address errors appearing on the all Senate totals table, currently disabled under a feature flag on the new Senate overview pages. Some states without elections in that cycle are appearing, but show no money. States without elections during a given election year should not appear.

Senate overview page: https://www.fec.gov/data/elections/senate/

**Local cms url**:  http://localhost:8000/data/elections/senate/

**API endpoint:** https://api.open.fec.gov/v1/candidates/totals/aggregates/?sort_hide_null=false&sort_nulls_last=false&page=1&per_page=20&election_full=true&sort=-election_year&api_key=DEMO_KEY&sort_null_only=false

Examples:
Election year 2022
- New Jersey
- Texas
- New Mexico
- Virginia
- Minnesota
- Massachusetts
- Michigan
- Mississippi
- District of Columbia [should never be included on Senate pages]

### Completion criteria

- [x] States without elections during a given election year should not appear

Screenshot of issue: 
<img width="886" alt="Screen Shot 2022-06-01 at 5 02 53 PM" src="https://user-images.githubusercontent.com/31663028/174081789-eacc226d-5e03-4884-8389-6cf4725fa7d3.png">

**Comment by djgarr** [comment]
@PaulClark2 do you mind taking a look at this ticket?

**Comment by PaulClark2** [comment]
@djgarr we have this information in a database table `dim_race_inf`

> select election_yr, state, state_desc, election_type_id, senate_class 
> from disclosure.dim_race_inf where office = 'S' and election_yr between 2022 and 2030
> order by election_yr asc, state_desc;

I'm not exactly sure which page prompted this issue being created, but I found that our list of states for 2022 Senate elections on this page, https://www.fec.gov/data/candidates/senate/?election_year=2022&cycle=2022&election_full=true&state=DC&state=MA&state=MI&state=MN&state=MS&state=NJ&state=NM&state=TX&state=VA&is_active_candidate=true, is incorrect. The selected states do not have Senate elections in 2022.

**Comment by djgarr** [comment]
@JonellaCulmer @patphongs Just wanted to let you know about Paul's comment above

**Comment by PaulClark2** [comment]
@JonellaCulmer thank you. That helps. As noted above, we seem to be displaying states that do not have 2022 Senate elections on the Candidates for Senate page, too.

**Comment by djgarr** [comment]
@PaulClark2 Was hoping you could provide a little more clarification on this ticket and next steps? Thanks
