### ISSUE TITLE
Fix districts that don’t exist in `/candidates/totals/aggregates/`

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5164]
### What we’re after

We want to show data for house districts that are running in that election year. We should validate the total number of districts are 441 and not show any invalid districts. We should only show districts if they were valid throughout history.

We need to figure out how to show active districts for any given election year. Can we add a `is_active_district` flag?

If a committee submitted a form 1 amendment, we have it in our database. Money is attached to the new district from the committee. If a candidate submitted that they raised money in a district that doesn’t exist, it will show up in the data. 

### Completion criteria

- [ ] Fix: Validate districts are 441, and remove all districts that are invalid
- [ ]  Create a CMS ticket to add language to explain how there may be more than 441 districts at a given time, determine the best location for this information.

**Comment by hcaofec** [comment]
The districts displayed by this endpoint are pulled from ofec_candidate_history_mv, and traced back to Form 2 which is submitted by candidates.  
@patphongs
