### ISSUE TITLE
Bug: Candidate contributions excluded when using unique individuals filter

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#5197]
### What we’re after

Bug for 11D and 17D transactions if you use the "From unique individuals only" filter on the All Receipts data table. Here's an example using Mike Bloomberg's presidential data. The same issue happens for congressional candidates. The correct answer is 2,122 transactions.

Bloomberg candidate contributions: 2,122 transactions
https://www.fec.gov/data/receipts/?data_type=processed&committee_id=C00728154&two_year_transaction_period=2020&line_number=F3P-17D

Bloomberg candidate contributions add "From unique individuals only" filter:  0 transactions
https://www.fec.gov/data/receipts/?data_type=processed&committee_id=C00728154&two_year_transaction_period=2020&is_individual=true&line_number=F3P-17D

### Completion criteria

- [ ] Candidate contributions (Line 11D, Form 3X and Line 17D, Form 3P) should be included in the result set when the unique individuals filter is selected currently using the filter drops candidate contributions.

**Comment by hcaofec** [comment]
@PaulClark2  Is this a permanent change to is_individual function by including all Line 11D from Form 3X and all Line 17D from Form 3P,  not just for Bloomberg?  Thanks.

**Comment by hcaofec** [comment]
After looking into the data, we think that Candidate contributions shouldn't be included with individual contributions.  There is no change needed to current is_individual function. So this ticket is closed.
