### ISSUE TITLE
Fix api bug cannot exclude two more parameters

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#5198]
### What we’re after
In order to filter by exclusion parameter on api, we need pass parameter like `-value`.
currently our api only support exclude one parameter. We should fix it to allow api exclude one or more parameters.
examples:
return 154 rows:
https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&contributor_name=sohn+richard&two_year_transaction_period=2022&min_date=01%2F01%2F2021&max_date=12%2F31%2F2022&sort=-contribution_receipt_date&per_page=30&is_individual=true

return 47 rows:
https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&contributor_name=sohn+richard&two_year_transaction_period=2022&min_date=01%2F01%2F2021&max_date=12%2F31%2F2022&sort=-contribution_receipt_date&per_page=30&is_individual=true&committee_id=-C00694323

### Action item(s)
- [ ] Find the root cause why two more parameters excluding not work.
- [ ] Fix it
- [ ] Add autotest

### Completion criteria
- [ ] api can exclude one or more parameters.

**Comment by hcaofec** [comment]
Whenever there is committee_id as filter, "union all" is used for schedule A endpoint.  When two and more committee IDs are passed with '-', the logic does not return the correct results.  Here is the logic:
```
select * 
from ( select * from schedule_a where committee_id not in (id1)
           union all
           select * from schedule_a where committee_id not in (id2) 
         );
```
