### ISSUE TITLE
Check logs PI 18 Innovation week 3

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#5202]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Ref: [Check logs PI Innovation week 2](https://github.com/fecgov/openFEC/issues/5201)
- [ ] Make new tickets for Sprint 19.1 weeks 1 & 2

**Comment by cnlucas** [comment]
**FEC-CMS:**
package.json: 0

requirements.txt: 1 High, 1 Medium
1. [SNYK: Medium]: [[pyjwt- Use of a Broken or Risky Cryptographic Algorithm](https://app.snyk.io/org/fecgov/project/ff0dca01-794e-4c1c-bf1f-0c0f8932fadd/#issue-SNYK-PYTHON-PYJWT-2840625)] [#5247](https://github.com/fecgov/fec-cms/issues/5247)
2. [SNYK: High]:[[django Reflected File Download (RFD)](https://app.snyk.io/org/fecgov/project/ff0dca01-794e-4c1c-bf1f-0c0f8932fadd/#issue-SNYK-PYTHON-DJANGO-2968205)] [#5362](https://github.com/fecgov/fec-cms/issues/5362)


**OPEN-FEC:**
package.json: None

requirements.txt: 0

flyway: 1 High, 2 Medium--No remediation path yet https://github.com/fecgov/openFEC/issues/5182
1.  [org.postgresql:postgresql SQL Injection](https://app.snyk.io/org/fecgov/project/e6c155e9-f0ac-4a49-98fa-83c24f5b74b3#issue-SNYK-JAVA-ORGPOSTGRESQL-2970521) ---No Remediation Path yet

1. org.bouncycastle:bcprov-jdk15on Cryptographic Issues
3. io.netty:netty-handler Improper Certificate Validation

**FEC-EREGS:**
package.json: 0

requirements.txt: 
1. [SNYK: High]:[[django Reflected File Download (RFD)](https://app.snyk.io/org/fecgov/project/ff0dca01-794e-4c1c-bf1f-0c0f8932fadd/#issue-SNYK-PYTHON-DJANGO-2968205)] [#703](https://github.com/fecgov/fec-eregs/issues/703)

**FEC-PATTERN-LIBRARY:**
package.json: 0

Search logs:
No new users

Cloud.gov Dashboard:
8 application deployer accounts 

Off-boarding:
None for this week
