### ISSUE TITLE
Research pre-commit git hook vs upgrade Flake8 

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5217]
### What we’re after

We are getting pytest errors when upgrading to the newest flake8. We need to update our code or find out why the upgrade is breaking our tests. 

~UPDATE: Flake8 is pinned,  now we need to figure out how to upgrade~. 

### Related ticket(s):

1. https://github.com/fecgov/fec-cms/pull/5388
2. https://github.com/fecgov/openFEC/pull/5227

https://github.com/tholo/pytest-flake8/issues/87

### Action item(s)

- [x] unpin flake8 in requirements.txt file 
- [x] remove pytest-flake8 (anti-pattern) and add pre-commit
- [x] tests run successfully
- [ ] do the same thing in CMS and/or build ticket

### Completion criteria

- [x] pytest runs without errors

**Comment by cnlucas** [comment]
https://github.com/tholo/pytest-flake8/issues/87

**Comment by pkfec** [comment]
More on pre-commit git hook: https://github.com/pre-commit/pre-commit-hooks

**Comment by pkfec** [comment]
1. Install `pre-commit` inside python virtualenv, run: `pip install pre-commit`
2. run : `pre-commit run --all-files`
