### ISSUE TITLE
[SNYK: HIGH] org.postgresql:postgresql SQL Injection (Due 2022-09-17)

### ISSUE THREAD

**Issue by rfultz** [fecgov/openFEC#5218]
### What we’re after

SNYK flagged a vulnerability, [org.postgresql:postgresql SQL Injection](https://app.snyk.io/org/fecgov/project/e6c155e9-f0ac-4a49-98fa-83c24f5b74b3#issue-SNYK-JAVA-ORGPOSTGRESQL-2970521)

Introduced through `org.flywaydb:flyway-commandline@9.0.2`
Fixed in `org.postgresql:postgresql@42.2.26`, `@42.4.1`

**Detailed paths and remediation**
Introduced through: unknown:unknown@0.0.0 › org.flywaydb:flyway-commandline@9.0.2 › org.postgresql:postgresql@42.3.3
Fix: Upgrade to org.flywaydb:flyway-commandline@9.1.4 

**Overview**
org.postgresql:postgresql is a Java JDBC 4.2 (JRE 8+) driver for PostgreSQL database.

Affected versions of this package are vulnerable to SQL Injection via the java.sql.ResultRow.refreshRow() function in jdbc/PgResultSet.java, due to insufficient escaping column names. An attacker with control of the underlying database can name a column with a string containing a semicolon or other statement terminator, then convince a user to run a query against the table with the compromised column, and then have the application run ResultSet.refreshRow(), to execute code.

**NOTE:**

An application that only connects to its own database with a fixed schema with no DDL permissions is not affected by this vulnerability.

Additionally, applications that do not invoke ResultSet.refreshRow() are not affected.

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)
- [ ] 

### Completion criteria

- [ ] SNYK no longer flags this as a vulnerability, or
- [ ] We've determined that this isn't an issue and we've documented that

### References/resources/technical considerations

-

**Comment by JonellaCulmer** [comment]
Closing this because the work has been merged.
