### ISSUE TITLE
Change "notification" to "report" for 24/48 hour report

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#5222]
### What we’re after

On this page,  we would like to change "notification" to "report" for all 24/48 hour reports

https://www.fec.gov/data/committee/C00530766/?tab=filings#notices

api:  
[https://api.open.fec.gov/v1/filings/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls[…]_type=-7&request_type=-8&request_type=-9&election_full=false](https://api.open.fec.gov/v1/filings/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&sort=-receipt_date&per_page=100&page=1&cycle=2022&committee_id=C00530766&form_type=F5&form_type=F24&form_type=F6&form_type=F9&form_type=F10&form_type=F11&form_type=RFAI&report_type=-Q1&report_type=-Q2&report_type=-Q3&report_type=-YE&request_type=-1&request_type=-3&request_type=-5&request_type=-6&request_type=-7&request_type=-8&request_type=-9&election_full=false).

### Action item(s)

- [x]  Add this logic in model file
- [ ]  Create follow-up CMS ticket to check if there is any work on CMS side

### Completion criteria

- [x] api returns correct document name for 24 hour and 48 hour reports

**Comment by PaulClark2** [comment]
I guess the labels should be in all caps to match what's on the website.
