### ISSUE TITLE
 Check logs sprint 19.2 week 1

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5225]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Ref: [Check logs sprint 19.1 week 2](https://github.com/fecgov/openFEC/issues/5215)

**Comment by cnlucas** [comment]
**FEC-CMS:**
package.json: None
requirements.txt: None
- 1 existing:
   - [[Snyk:Medium] pyjwt- Use of a Broken or Risky Cryptographic Algorithm (due by 07/24/2022)](https://github.com/fecgov/fec-cms/issues/5247)

**OPENFEC:**
package.json: None
requirements.txt: None
flyway: 
- 1 existing: 
   - [SNYK: Medium] io.netty:netty-handler Improper Certificate Validation (Due 2022-10-17)](~https://github.com/fecgov/fec-cms/issues/5377~ closed in favor of https://github.com/fecgov/openFEC/issues/5182)
   https://app.snyk.io/org/fecgov/project/e6c155e9-f0ac-4a49-98fa-83c24f5b74b3#issue-SNYK-JAVA-IONETTY-1042268

**FEC-PATTERN-LIBRARY:**
package.json: None

**FEC-EREGS:**
package.json: None
requirements.txt: 
None
requirements-parsing.txt:
None

**Search logs:**
No log results for "User change"

**Cloud.gov Dashboard:**
Cloud.gov login down

**Off-boarding:**
None in Github or Cloud.gov this week
