### ISSUE TITLE
 Check logs sprint 19.2 week 2

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5226]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Ref: [Check logs sprint 19.2 week 1](https://github.com/fecgov/openFEC/issues/5225)

- [ ] Make new tickets for Sprint 19.3 weeks 1 & 2

**Comment by cnlucas** [comment]
**FEC-CMS:**
package.json: None
requirements.txt: None
- 1 existing:
   - [[Snyk:Medium] pyjwt- Use of a Broken or Risky Cryptographic Algorithm (due by 07/24/2022)](https://github.com/fecgov/fec-cms/issues/5247)

**OPENFEC:**
package.json: None
requirements.txt: None
flyway: None

**FEC-PATTERN-LIBRARY:**
package.json: None

**FEC-EREGS:**
package.json: None
requirements.txt: 
None
requirements-parsing.txt:
None

**Search logs:**
no new users

**Cloud.gov Dashboard:**
Ok 8 accounts

**Off-boarding:**
None in Github or Cloud.gov this week
