### ISSUE TITLE
Check logs 19.4 week 1

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#5242]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Ref: [Check logs sprint 19.3 week 2](https://github.com/fecgov/openFEC/issues/5237)

**Comment by cnlucas** [comment]
**FEC-CMS:**
package.json: None
requirements.txt: Snyk Medium: [django Denial of Service (DoS)](https://github.com/fecgov/fec-cms/issues/5433)

**OPENFEC:**
package.json: None
requirements.txt: None
flyway: 2 Snyk Medium: [com.fasterxml.jackson.core:jackson-databind Denial of Service (DoS) ](https://github.com/fecgov/openFEC/issues/5253)

**FEC-PATTERN-LIBRARY:**
package.json: None

**FEC-EREGS:**
package.json: None
requirements.txt: Snyk Medium: [django Denial of Service (DoS)](https://github.com/fecgov/fec-eregs/issues/718)


**Search logs:**
no new users

**Cloud.gov Dashboard:**
Ok 8 accounts

**Off-boarding:**
None in Github or Cloud.gov this week
