### ISSUE TITLE
Check logs 19.6 week 2

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#5265]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Ref: [Check logs sprint 19.6 week 1](https://github.com/fecgov/openFEC/issues/5264)

- [ ] Make new tickets for Sprint 19 innovation weeks 1 & 2

**Comment by cnlucas** [comment]
**FEC-CMS:**
package.json: Snyk Medium: [minimatch Regular Expression Denial of Service (ReDoS) #5447](https://github.com/fecgov/fec-cms/issues/5447)
requirements.txt: Snyk Medium: [django Denial of Service (DoS)  #5433](https://github.com/fecgov/fec-cms/issues/5433)

**OPENFEC:**
package.json: None
requirements.txt: None
flyway: None

**FEC-EREGS:**
package.json: None
requirements.txt: None

**FEC-PATTERN-LIBRARY:**
package.json: None


**Search logs:**
Ok

**Cloud.gov Dashboard:**
Ok 8 accounts

**Off-boarding:**
None in Github or Cloud.gov this week
