### ISSUE TITLE
Candidate_disbursements typo

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5297]
### What we’re after

There are several instance of candidate_disbursements spelled "canidate_disbursements" in the migration files. We should rename these rows. 

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [ ] 

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)
- [ ] 

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] All instances of "canidate" are removed

### References/resources/technical considerations

(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)

**Comment by hcaofec** [comment]
The typo appears in ofec_entity_chart_mv, and  later this materialized view was no longer needed and delete in migration V108.  So close this ticket without further action.
