### ISSUE TITLE
Check logs 20.6 Week 1 

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#5337]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Ref: [Check logs sprint 20.5 week 2]
https://github.com/fecgov/openFEC/issues/5332

- [x] Check [booting workers](  https://logs.fr.cloud.gov/goto/67b5912713e2588c523b63597baa54e8
), caches, [memory usage](https://logs.fr.cloud.gov/goto/03634cc2122630e2a86cad813ddefe52)

**Comment by hcaofec** [comment]
**FEC-CMS:**
package.json: Snyk Medium: https://github.com/fecgov/fec-cms/issues/5593
requirements.txt: Snyk high: https://github.com/fecgov/fec-cms/issues/5603

**OPENFEC:**
package.json: None
requirements.txt: None
flyway: None

**FEC-EREGS:**
package.json: None
requirements.txt: Snyk high: https://github.com/fecgov/fec-eregs/issues/747

**FEC-PATTERN-LIBRARY:**
package.json: None

**Search logs:**
User change: Slack access for Alyssa Ondrus

Cloud.gov Dashboard:
Ok 6 accounts

Off-boarding:
Ok

Health check:
memory usage: ok
booting workers: ok
