### ISSUE TITLE
[Snyk:High] werkzeug Denial of Service (DoS) (due by 03/22/23)

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#5349]
Introduced through  werkzeug@2.0.0, flask@2.1.2 and others
Fixed in werkzeug@2.2.3

Detailed paths and remediation:
Introduced through: project@0.0.0 › werkzeug@2.0.0
Fix: Upgrade werkzeug to version 2.2.3 
Introduced through: project@0.0.0 › flask@2.1.2 › werkzeug@2.0.0
Fix: Pin werkzeug to version 2.2.3 
Introduced through: project@0.0.0 › flask-apispec@0.7.0 › flask@2.1.2 › werkzeug@2.0.0
Fix: Pin werkzeug to version 2.2.3 
Introduced through: project@0.0.0 › flask-cors@3.0.10 › flask@2.1.2 › werkzeug@2.0.0
Fix: Pin werkzeug to version 2.2.3 
Introduced through: project@0.0.0 › flask-restful@0.3.9 › flask@2.1.2 › werkzeug@2.0.0
Fix: Pin werkzeug to version 2.2.3 
Introduced through: project@0.0.0 › flask-sqlalchemy@2.4.1 › flask@2.1.2 › werkzeug@2.0.0
Fix: Pin werkzeug to version 2.2.3 

Security information:
Factors contributing to the scoring:
Snyk: [CVSS 7.5](https://security.snyk.io/vuln/SNYK-PYTHON-WERKZEUG-3319936) - High Severity
NVD: Not available. NVD has not yet published its analysis.

Overview:
Affected versions of this package are vulnerable to Denial of Service (DoS) when parsing multipart form data. An attacker can trigger the opening of multipart files containing a large number of file parts, which are processed using request.data, request.form, request.files, or request.get_data(parse_form_data=False), consuming CPU, memory, or file handles resources. The amount of CPU time required can block worker processes from handling other requests. The amount of RAM required can trigger an out-of-memory and crash the process.

**Comment by pkfec** [comment]
PR #5359 merged. Closing this issue.
