### ISSUE TITLE
[Snyk:Low] werkzeug Access Restriction Bypass (due by 05/22/23)

### ISSUE THREAD

**Issue by hcaofec** [fecgov/openFEC#5350]
Introduced through werkzeug@2.0.0, flask@2.1.2 and others
Fixed in werkzeug@2.2.3

Detailed paths and remediation:
Introduced through: project@0.0.0 › werkzeug@2.0.0
Fix: Upgrade werkzeug to version 2.2.3 
Introduced through: project@0.0.0 › flask@2.1.2 › werkzeug@2.0.0
Fix: Pin werkzeug to version 2.2.3 
Introduced through: project@0.0.0 › flask-apispec@0.7.0 › flask@2.1.2 › werkzeug@2.0.0
Fix: Pin werkzeug to version 2.2.3 
Introduced through: project@0.0.0 › flask-cors@3.0.10 › flask@2.1.2 › werkzeug@2.0.0
Fix: Pin werkzeug to version 2.2.3 
Introduced through: project@0.0.0 › flask-restful@0.3.9 › flask@2.1.2 › werkzeug@2.0.0
Fix: Pin werkzeug to version 2.2.3 
Introduced through: project@0.0.0 › flask-sqlalchemy@2.4.1 › flask@2.1.2 › werkzeug@2.0.0
Fix: Pin werkzeug to version 2.2.3 

Security information:
Factors contributing to the scoring:
Snyk: [CVSS 2.6](https://security.snyk.io/vuln/SNYK-PYTHON-WERKZEUG-3319935) - Low Severity
NVD: Not available. NVD has not yet published its analysis.

Overview:
Affected versions of this package are vulnerable to Access Restriction Bypass that allows a malicious application on an adjacent subdomain to present "nameless" cookies that look like =value instead of key=value and have them accepted by the affected browser. For example, a cookie like =__Host-test=bad would be parsed as __Host-test=bad and the key treated as valid while the value is ignored.

**Comment by pkfec** [comment]
PR #5349 merged. Closing this issue
