### ISSUE TITLE
Conduct H4 data mapping to improve variable names

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5360]
**What we’re after:**
We should map out the H4 data --connecting the form labels to our current prototype endpoint labels. We should figure out any current work that needs to happen to that endpoint and add it to the refinement ticket here:
https://github.com/fecgov/openFEC/issues/5361

Waiting on contractors to finish adding missing data for purpose of disbursement.

**Completion criteria:**
- [ ] Variable names determined and form parameters are mapped to API

**Comment by JonellaCulmer** [comment]
Preliminary documentation: https://docs.google.com/document/d/1_0SqudoNoAXBdauhDkhalW3LIYbyqPo_HU6aY8VOg4Y/edit

**Comment by cnlucas** [comment]
Updates have been made to the document above and the ticket.
