### ISSUE TITLE
Presidential Map Back-End work

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5362]
### What we’re after

We need to update our presidential map endpoint to support 2024 data.  We should have the map online on 4/17 if the Q1 04/15 data has fully processed.

### Related ticket(s)

- [ ] https://github.com/fecgov/openFEC/issues/4175

### Action item(s)

- [ ] Perform necessary updates to view and endpoint to add 2024 data to [presidential map](https://www.fec.gov/data/candidates/president/presidential-map/)
- [ ] locust test before and after the addition, confer with product managers about [the 2008-2012 addition ](https://github.com/fecgov/openFEC/issues/5363)
- [ ] QA and ensure presidential candidates who meet the $100,000 individual contribution threshold are there on the map. (Need Paul for this)

**Comment by pkfec** [comment]
Links to Presidential map: 
 
 Stage: https://fec-stage-proxy.app.cloud.gov/data/candidates/president/presidential-map/
 Feature: https://fec-feature-cms.app.cloud.gov/data/candidates/president/presidential-map/
Production: https://www.fec.gov/data/candidates/president/presidential-map/

**Comment by pkfec** [comment]
Still waiting to receive and process presidential candidates Q1 data. Expected date is April 15th.

**Comment by pkfec** [comment]
Database changes for 2024 presidential map can be tracked in PR https://github.com/fecgov/openFEC/pull/5374

1. 2024 presidential map went live on April 18 2023. 
2. 2024 presidential candidates with 100K in contributions are now showing up on the [presidential map](https://www.fec.gov/data/candidates/president/presidential-map/)
3. As of April 18, 2023 there are only 4 candidates running for 2024 presidency. Not a big dataset to conduct locust test
4. Plan is to run locust tests when 2008, 2012 data is available to go live
