### ISSUE TITLE
Test 2008-2012 Presidential Map data

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5363]
### What we’re after

After locust testing the 2024 additions to the presidential map and conferring with the product managers, we need to decide if we are going to add the 2008-2012 data to the presidential map. We should also determine the policy for how long we are showing the data going forward. 

If we decide that we are going to add the 2008-2012 data, we should add it and conduct further testing and create the ticket for the front-end work. 

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [x] https://github.com/fecgov/openFEC/issues/5362

### Action item(s)
- [x] Conduct performance testing
- [x] Confirm performance is acceptable with 2008-2024 cycles data
- [x] Create front-end ticket to include 2008, 2012 under election years dropdown

### Completion criteria
- [x] 2008 & 2012 data has been added to the presidential table(s), then
- [x] Decision on whether performance is acceptable. If so,
- [x] Front-end ticket has been created

**Comment by patphongs** [comment]
Moving this to 21.3 while we get the 2024 presidential map data ready.

**Comment by pkfec** [comment]
After discussing with @jdiaofec and @ChingKuan , @fecjjeng mentioned that Presidential tables for 2008 through 2012 have quite different structure compare to the more recent cycles. It will take some effort to bring them together. And the procedures to create the download files will take some effort to be updated too. 

It looks like DB team need more time to align things so I am going to comment and unassign myself and move this ticket  to 21.5 sprint

**Comment by pkfec** [comment]
@PaulClark2 mentioned to get the historic data ready on the website by end of 2023. @fecjjeng mentioned to discuss the LOE to accomplish this task with the DB team. Waiting to her from DB team for further updates.

**Comment by cnlucas** [comment]
I have done the load testing that I can.

 We need to do some updating of our locust tests. So far, the DB teams changes haven't caused any issues with the API performance. This doesn't really confirm if the FE components can handle loading this data. I am currently working with FE to determine if we should make this ticket.
