### ISSUE TITLE
Create filter for coverage dates in API

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#5368]
**What we're after:**
Create a filter for coverage date in the API. 

Jonella: Is this filter needed for sorting? Or do display on the datable? Filter for coverage date or dates?

Related ticket:
- openFEC #4758

Completion criteria:**
- [x] coverage date filter added to API

**Comment by tmpayton** [comment]
Closing this ticket because the coverage date filter was implemented with this [PR](https://github.com/fecgov/openFEC/pull/5410)
