### ISSUE TITLE
Check logs 21.1 Week2

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#5372]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Ref: [Check logs PI 21.1 week 1]
(https://github.com/fecgov/openFEC/issues/5371)

- [x]  Check [booting workers](https://logs.fr.cloud.gov/goto/67b5912713e2588c523b63597baa54e8)
- [x] Check [memory usage](https://logs.fr.cloud.gov/goto/72391fa43d1cf607fbf1c6b30e71251f)
(**Note**: Copy above links in a browser to view the metrics)
- [x] Make new tickets for  21.2 week1 and week2

**Comment by hcaofec** [comment]
**FEC-CMS:**
package.json: 1 , Snyk High https://github.com/fecgov/fec-cms/issues/5635
requirements.txt: None

**OPENFEC:**
package.json: None
flyway: 1,  Snyk high https://github.com/fecgov/openFEC/issues/5382
requirements.txt: 1, Snyk Low https://github.com/fecgov/openFEC/issues/5381

FEC-EREGS:
package.json: None
requirements.txt: None

FEC-PATTERN-LIBRARY:
package.json: None

Search logs:
User change: None

Cloud.gov Dashboard: 6 deployer accounts

Off-boarding: 1

Health check:
memory usage: ok
booting workers: ok
