### ISSUE TITLE
Database work for presidential map

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#5373]
**What we're after:**
Jerry has added 2024 presidential tables and updated Informatica workflow to populate our internal databases (FECP). 
This ticket is for tasks required to add presidential 2024 tables and updated related views to include 2024 presidential tables in Postgresql databases.

New tables needed:
disclosure.pres_ca_cm_sched_a_join_24d
disclosure.pres_nml_ca_cm_link_24d
disclosure.pres_ca_cm_sched_state_24d
disclosure.pres_ca_cm_sched_link_sum_24d
disclosure.pres_nml_sched_a_24d
disclosure.pres_nml_sched_b_24d
disclosure.pres_f3p_totals_ca_cm_link_24d
disclosure.pres_nml_f3p_totals_24d
disclosure.pres_nml_form_3p_24d

Existing views need to be updated:
public.ofec_presidential_coverage_date_vw
public.ofec_presidential_by_candidate_vw
public.ofec_presidential_by_state_vw
public.ofec_presidential_financial_summary_vw
public.ofec_presidential_by_size_vw

**Completion criteria:**
- [x] Add presidential 2024 base tables
- [x] Updated related views to include 2024 presidential tables
- [x] Created DMS tasks to pull presidential 2024 data from FECP database to Aurora postgres database on demand.

**Comment by hcaofec** [comment]
PR has been merged.
