### ISSUE TITLE
Test and upload all legal data ES management commands on stage and prod space

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#5377]
### What we’re after
After refactoring ES managements commands, we need test on stage and prod spaces

### Related ticket(s)
[Refactor Elasticsearch management commands](https://github.com/fecgov/openFEC/pull/5367)

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)
- [x] after cutting release branch, test all ES management commands on stage space
- [ ] after release, test  all ES management commands on prod space

### Completion criteria
- [ ] All legal management tasks work well.

**Comment by rfultz** [comment]
Already deployed to Prod
