### ISSUE TITLE
Swagger URL seems broken

### ISSUE THREAD

**Issue by EightArmCode** [fecgov/openFEC#5395]
Is it intentional that the [link to swagger](https://api.open.fec.gov/swagger/) look like this?
<img width="1184" alt="Screenshot 2023-04-10 at 15 24 00" src="https://user-images.githubusercontent.com/7226801/230909658-7697b1c4-c88d-4686-bf31-64688950e595.png">

Seems swagger is still live [here](https://api.open.fec.gov/developers), but the actual links to swagger just look like an unstyled json dump.
<img width="1412" alt="Screenshot 2023-04-10 at 15 26 01" src="https://user-images.githubusercontent.com/7226801/230909804-2c36e6ea-b0a7-45da-a021-f254e07fab45.png">

**Comment by fec-jli** [comment]
This is browser JSONViewer issue, change to use Firefox or click "Highlight anyway!" in Chrome.

<img width="334" alt="Screenshot 2023-12-11 at 6 42 42 PM" src="https://github.com/fecgov/openFEC/assets/24395751/c17bfc02-9630-4a32-a380-5fa5c762cf2a">
