### ISSUE TITLE
Malformed response from: `committee/{committee_id}/candidates/history/{cycle}` endpoint

### ISSUE THREAD

**Issue by EightArmCode** [fecgov/openFEC#5408]
Hello

I thought you might like to know that the endpoint `committee/{committee_id}/candidates/history/{cycle}` seems to return a malformed response. It is possible that I'm not using the right values in the path, but I would still expect it to return a valid response shape. Currently, I'm only getting

```
{
  "size": 0,
  "timeout": 0
}
``` 

It seems to work fine in Swagger, which suggests there might be more than one issue... Let me know if you need more info. Just posting this as a courtesy. I'm not blocked by this.

**Comment by fec-jli** [comment]
Thank you for reporting the issue. Could you please share the URL or the steps you followed to obtain the result? This information will be very helpful. Thanks.

**Comment by EightArmCode** [comment]
Sure I don't mind, but now I'm getting a 500. 🤔 I'll see if I can reproduce that again.

**Comment by EightArmCode** [comment]
Ah, thanks for asking! I was using Nextjs API syntax to call Open FEC API. The variables were not interpolated in the URL of the endpoint. Your question helped me find a bug in my own program. Now when I send an invalid value for `cycle` I get a correctly formed empty response.
