### ISSUE TITLE
Upgrade API app to use cflinuxfs4 stack

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#5443]
### What we’re after

From cloud.gov:

> Hello! This notification is to make you aware that you are still running `cflinuxfs3` applications in your [cloud.gov](https://cloud.gov/) organization. Your applications will soon stop working unless you take action to migrate your applications to the cflinuxfs4, stack! 

> Please follow the directions below to migrate your applications to the cflinuxfs4, stack. 

> **What should you do now for existing apps?** 
> For existing applications which were created under cflinuxfs3 you will need to update the stack declaration to cflinuxfs4, there are two common ways of doing this detailed below. 
The options below only have to be run once for each application on cflinuxfs3 , once the stack is set for an application, it is persistent until changed with any of these two steps. 
> - Push the app manually and specify the stack with the cf cli: cf push MY-APP -s cflinuxfs4 
> - Use the stack-auditor cf cli plugin to change the stack without having to push the application. Documentation for using this plugin is at [https://docs.cloudfoundry.org/adminguide/stack-auditor.html#change-stacks](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.cloudfoundry.org%2Fadminguide%2Fstack-auditor.html%23change-stacks&data=05%7C01%7CPKasireddy%40fec.gov%7Cf2fe4c51c3c14decf1f508db51995e4f%7Cee91fa706c9d45e0bb084a355de91010%7C0%7C0%7C638193491373538770%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MnfWx3s5u8aQKV9cndIx3G3wSGSfcaoiyjiG%2Fon11Qw%3D&reserved=0), the basic workflow is: - Install the plugin - Use the cf cli to target the org and space for your existing application - Run cf change-stack APP-NAME cflinuxfs4 to change the app to the cflinuxfs4 stack - Each application will take about a minute or so to run the cf change-stack... command depending on the size of the droplet. 
> -  Additional information Please refer to the deprecation notice at [https://cloud.gov/2023/04/27/cflinuxfs3-deprecation-update/](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.gov%2F2023%2F04%2F27%2Fcflinuxfs3-deprecation-update%2F&data=05%7C01%7CPKasireddy%40fec.gov%7Cf2fe4c51c3c14decf1f508db51995e4f%7Cee91fa706c9d45e0bb084a355de91010%7C0%7C0%7C638193491373538770%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8uBYRHofCFRt%2Fjm7QlxkyqBDb8wrpTe%2FbmgHnI%2BnF%2Bk%3D&reserved=0) which will give you additional information.

### Action item(s)
On cloud.gov space:
- [ ] Run `cf push MY-APP -s cflinuxfs4`manually on cloud.gov space
**or** 
- [ ] Run `cf change-stack APP-NAME cflinuxfs4`
- [ ] Run `cf restage APP-NAME` **or** Run the latest app build on circleci
- [x] Update the  `stack` declaration to cflinuxfs4 in [manifest](https://github.com/fecgov/openFEC/tree/develop/manifests)* files
- [ ]  Deploy and test the changes on `dev` space 
- [ ] Implement the changes on stage, feature and prod manifest files

### Completion criteria

- [ ] Run `cf app api` and verify `api` app is  upgraded to **cflinuxfs4** stack in  `dev/feature/stage` and `prod` environments

**Comment by JonellaCulmer** [comment]
test note
