### ISSUE TITLE
Research the removal of extra columns from debts export

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#5513]
**What we're after:**
Following a review by RAD, we need to remove unnecessary columns Y-AM from the debts datatable export. This is not a quick fix and requires research to address. 

**Notes:**
The debts tables are using `/schedules/schedule_d/`, so the export/downloads would be `/download/schedules/schedule_d/`

**Action items:**
- [ ] See if front-end can remove columns
- [ ] Consider other exports that may have extra columns that may need to be removed
- [ ] Add other tickets as needed to handle next steps

**Completion criteria:**
- [ ] Document research and next steps to remove columns Y-AM from the debts datatable export

**Comment by cnlucas** [comment]
I am recommending removing the columns from our debts output. They are all <1% non-null 
![image](https://github.com/fecgov/openFEC/assets/66386084/3f04cd74-9a2f-4c62-a59d-9c5b3e659a0c)


I have a PR ready for review by DB and PM's for the work.
