### ISSUE TITLE
Rotate S3 service access keys in Dev, Stage, Feature and Prod environments 

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#5620]
### What we’re after

 We have to rotate keys by un-binding and re-binding S3 buckets to each bound application.

> Dear cloud.gov customer,

> We are writing to notify you of an incident involving brokered service credentials on the cloud.gov platform. We do not believe there was any impact to confidentiality, integrity, or availability of your data as a result of this incident, but we are sharing this information with you so your teams can assess the risk and take action as needed.

> What happened?

> On Friday October 16, a cloud.gov engineer found that the cloud.gov S3 broker, which manages the S3 buckets that customers broker using the platform, was printing AWS secret access keys in clear text to its logs. Specifically, whenever a customer created a “binding” between the bucket and one of their applications, the newly created key was written to the broker log and indexed by our log management system.

> How has cloud.gov responded?

> We have modified the S3 broker to stop printing these credentials and we have removed all log lines containing the keys from our active log indices. However, the log lines will remain in our long-term log archives due to our retention obligations.

> What is the scope of the issue?

> The relevant code and configuration was introduced more than six years ago. Because of the time span, it is likely that all current and past brokered S3 buckets are affected.

> Next steps

> Because of the factors listed above, although there was no public compromise of your credentials, we recommend rotating your access keys at this time.

> You can rotate your keys by un-binding and re-binding your S3 buckets to each bound application. In a terminal, using the cf command line tool:

 
               
                       # list all spaces in your organization
                       cf spaces
 
                       # target a space
                       cf target -s SPACE-NAME
 
                       # list all s3 services in the space and the applications bound to them.
                       cf services | grep s3
 
                       # for each application bound to the service, un-bind it from the service, re-bind it, and restage it.
                       cf unbind-service YOUR-APPLICATION YOUR-SERVICE
                       cf bind-service YOUR-APPLICATION YOUR-SERVICE
                       cf restage YOUR-APPLICATION
               
        
> Note that re-staging your application may cause downtime.

> You will also need to delete and recreate any service keys for your S3 services:

 
               
                       # delete and recreate service keys for each service
                       cf delete-service-key SERVICE SERVICE_KEY
                       cf create-service-key SERVICE SERVICE_KEY
               
        
> Is my data at risk?

> Cloud.gov does not believe your data is at risk. The logging system is designed to segregate logs from customer tenant access, and we have no indications of unauthorized access. We are continually monitoring our system and will reach out to your team directly if we detect any suspicious activity.

> Why did this happen?

> Cloud.gov will hold an incident postmortem in the coming weeks to discuss the root cause of this incident and how similar incidents will be prevented in the future. We will share our findings and corrective actions at that time.

> Please feel free to reach out to our support team at [support@cloud.gov](mailto:support@cloud.gov) if you have questions or concerns.

> Sincerely,
James Hochadel
Platform Engineer, cloud.gov

### Action item(s)

- [x]  list all spaces in your organization: `cf spaces`
- [x] target a space: `cf target -s SPACE-NAME`
- [x] list all s3 services in the space and the applications bound to them: `cf services | grep s3`
- [x] for each application bound to the service, un-bind it from the service, re-bind it, and restage it:
      -  cf unbind-service YOUR-APPLICATION YOUR-SERVICE
      -  cf bind-service YOUR-APPLICATION YOUR-SERVICE
      - cf restage YOUR-APPLICATION  (causes downtime)
        **OR** 
      -  rerun the latest develop/master build on circleci
- [x] delete and recreate any service keys for your S3 services:
      -  cf delete-service-key SERVICE SERVICE_KEY
       - cf create-service-key SERVICE SERVICE_KEY 

 
 ### Completion criteria: 
-  [x] Rotate S3 service access keys in Dev, Stage, Feature and Prod environments

**Comment by pkfec** [comment]
- cf services | grep s3
## fec-s3-snapshot
- cf unbind-service celery-beat fec-s3-snapshot
- cf unbind-service celery-worker fec-s3-snapshot
- cf unbind-service api fec-s3-snapshot

**Comment by fec-jli** [comment]
We have 6 S3 services on Prod:
1)content-s3.   basic-public               cms                                                                    
2)fec-s3-api     basic-public               api, celery-worker, celery-beat                   
3)fec-s3-cms-backup    basic   
4)fec-s3-snapshot          basic           api, celery-worker, celery-beat       
5)fec-s3-web-logs-export-20171128      basic    
6)s3-hybrid-website      basic-public

**Comment by pkfec** [comment]
> There are six S3 services on Prod: (10/19/2023)
> 
> S3 Service Name	S3 Service Type	api Name
> **content-s3**	basic-public	cms
> **fec-s3-api**	basic-public	api, celery-worker, celery-beat
> fec-s3-cms-backup	basic	
> **fec-s3-snapshot**	basic	api, celery-worker, celery-beat
> fec-s3-web-logs-export-20171128	basic	
> s3-hybrid-website	basic-public

@fec-jli `s3-hybrid-website` and `fec-s3-web-logs-export-20171128` services were created in 2017 and none of the apps or bound to them. We can delete them

**Comment by fec-jli** [comment]
We have rotated S3 service access keys on dev, stage, feature and prod spaces successfully.
(content-s3, fec-s3-api and fec-s3-snapshot)
