### ISSUE TITLE
Migrate from Deploy to Run in CircleCi

### ISSUE THREAD

**Issue by tmpayton** [fecgov/openFEC#5678]
### What we’re after

Eventually, CircleCi will deprecate the deploy step. We need to switch to Run instead. [This](https://circleci.com/docs/migrate-from-deploy-to-run/) article shows us how to switch over.  

### Completion criteria
- [ ] "Run" is used instead of "deploy" in CircleCI repos (openFEC, FEC-CMS, eRegs, FEC-Proxy, FEC-Proxy-Redirect, fec-pattern-library)

**Comment by cnlucas** [comment]
This work was completed in 5711
