### ISSUE TITLE
Check logs Sprint 24.1 Week1

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#5700]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Ref: [Check logs PI 23 innovation sprint week 3](https://github.com/fecgov/openFEC/issues/5685)

- [x]  Check [booting workers](https://logs.fr.cloud.gov/goto/67b5912713e2588c523b63597baa54e8)
- [x] Check [memory usage](https://logs.fr.cloud.gov/goto/72391fa43d1cf607fbf1c6b30e71251f)

(Note: Copy above links in a browser to view the metrics)

**Comment by cnlucas** [comment]
FEC-CMS: 6
package.json: None
requirements.txt: 6
3 [Snyk High - pillow Uncontrolled Resource Consumption](https://github.com/fecgov/fec-cms/issues/5930)
1 [Snyk High - gitpython Untrusted Search Path](https://github.com/fecgov/fec-cms/issues/6082)
1 [Snyk Medium - jinga2](https://github.com/fecgov/fec-cms/issues/6083)
1 [Snyk Low - wagtail](https://github.com/fecgov/fec-cms/issues/5972)



OPENFEC: 1
package.json: 0
requirements.txt: 1
1 [Snyk High - gitpython Untrusted Search Path](https://github.com/fecgov/openFEC/issues/5694)
requirements-dev.txt: 0
FLYWAY: [org.apache.derby:derby LDAP Injection ](https://github.com/fecgov/openFEC/issues/5708)


FEC-EREGS: 0
package.json: 0
requirements.txt: 0


FEC-PATTERN-LIBRARY: None
package.json: 0

Search logs: None

Cloud.gov Dashboard: 6 deployer accounts

Off-boarding: None

App Health check: ok
