### ISSUE TITLE
Check logs Sprint 24.1 Week2

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#5701]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Ref: [Check logs Sprint 24.1 Week1](https://github.com/fecgov/openFEC/issues/5700)

- [x]  Check [booting workers](https://logs.fr.cloud.gov/goto/67b5912713e2588c523b63597baa54e8)
- [x] Check [memory usage](https://logs.fr.cloud.gov/goto/72391fa43d1cf607fbf1c6b30e71251f)
- [x] Make new tickets for sprint 24.2 weeks  1 and 2

(Note: Copy above links in a browser to view the metrics)

**Comment by cnlucas** [comment]
FEC-CMS: 6
package.json: None
requirements.txt: 1
1 [Snyk Medium - jinga2](https://github.com/fecgov/fec-cms/issues/6083)

OPENFEC: 0
package.json: 0
requirements.txt: 0

requirements-dev.txt: 0
FLYWAY: 0


FEC-EREGS: 0
package.json: 0
requirements.txt: 0


FEC-PATTERN-LIBRARY: None
package.json: 0

[Search logs](https://logs.fr.cloud.gov/goto/cc416e749b334928539d498e76015bb2):  3 changes, ok

Cloud.gov Dashboard: 6 deployer accounts

Off-boarding: None

App Health check: ok
