### ISSUE TITLE
Database provides an estimate on the complete dataset of national party account data

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5702]
### What we’re after
Better understand the universe of national party account data as it currently stands. This work would be to provide an estimate of the size and scope of this data by querying the database.

**Breakout session doc:**
https://docs.google.com/document/d/1Gycb7yaKOEa_OT5afLYfF5tqSFLqzky-V9LRxpP5p-g/edit

### Action item(s)
- [x] Query the database here: receipt_tp, disb_tp @hcaofec confirming where this is in the database
- [x] Determine whether there are any performance issues that may require indexing this data

### Completion criteria
- [x] Document available data fields and size in this ticket

**Comment by fecjjeng** [comment]
National Party Accounts data consist data reported in sched_b, line 21B and 29; and data reported in sched_a, line 17.
There are 12 National Party committees that have National Party Accounts data for the following 3 categories.
-Headquarters building fund
-Recounts/legal fees
-Presidential nominating conventions
These 12 National Party committees' total schedule data (including SA, SB, SC, etc) is about 4.3% out of all schedule data (1,145,592,110 rows).  Amongst these data,  there are 82955 rows of SA/line17 and 1670075 rows of SB/line 21B/29.  Currently, the line_num column is indexed in both fec_fitem_sched_a_xxxx tables and fec_fitem_sched_b_xxxx tables.  receipt_tp (sched_a) and disb_tp (sched_b) columns are not indexed in fec_fitem_sched_a_xxxx tables and fec_fitem_sched_b_xxxx tables.  Considering the small percentage of National Party Accounts data, it is a reasonable approach to create materialized views for this purpose.  The data duplication is acceptable.  Adding indexes on receipt_tp and disb_tp columns to the MV to further distinguish the three different Accounts (Headquarters, Recounts, Conventions) is more efficient and cost effective.   More manipulation to fit the TBD data presentation will also be easier on the much smaller data sets.

**Comment by JonellaCulmer** [comment]
This is done, so closing.
