### ISSUE TITLE
Research 500 errors when paginating on schedule A

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5720]
### What we’re after

We received a user email with a list of queries that were giving 500 errors. After doing some initial research, there was no obvious reason that these queries weren't returning successfully. We should do more research and see if we can fix this issue. 

Look at the user e-mail for more context. 
* https://api.open.fec.gov/v1/schedules/schedule_a/?sort=contribution_receipt_date&min_amount=1000&two_year_transaction_period=2024&min_date=2023-01-19&max_date=2023-01-19&last_contribution_receipt_date=2023-01-19&last_index=4042720231744864529&per_page=100&api_key=DEMO_KEY
PAGE 2 4022120231732455931 OK
PAGE 3 4040520231738512306 OK 
PAGE 4 4042220231743647880 OK 
STARTS 4042720231744846112 ERROR
PAGE 5 4042720231744864529 ERROR
* https://api.open.fec.gov/v1/schedules/schedule_a/?sort=contribution_receipt_date&min_amount=1000&two_year_transaction_period=2022&min_date=2022-10-20&max_date=2022-10-20&last_contribution_receipt_date=2022-10-20&last_index=4121320221635175467&per_page=100&api_key=DEMO_KEY
* https://api.open.fec.gov/v1/schedules/schedule_a/?sort=contribution_receipt_date&min_amount=1000&two_year_transaction_period=2022&min_date=2022-02-03&max_date=2022-02-03&last_contribution_receipt_date=2022-02-03&last_index=4040520221465315780&per_page=100&api_key=DEMO_KEY
* https://api.open.fec.gov/v1/schedules/schedule_a/?sort=-contribution_receipt_date&min_amount=1000&two_year_transaction_period=2022&min_date=2021-10-27&max_date=2021-10-27&last_contribution_receipt_date=2021-10-27&last_index=4020720221405294106&per_page=100&api_key=DEMO_KEY
* https://api.open.fec.gov/v1/schedules/schedule_a/?sort=contribution_receipt_date&min_amount=1000&two_year_transaction_period=2022&min_date=2021-10-20&max_date=2021-10-20&last_contribution_receipt_date=2021-10-20&last_index=4012520221389410863&per_page=100&api_key=DEMO_KEY
 

### Action item(s)

- [x] Check the api umbrella for these 500 errors
- [x] Try paginating through the queries above. 

### Completion criteria

- [x] The cause of the 500 errors has been identified.
- [x] Create any follow up tickets needed

**Comment by tmpayton** [comment]
I determined that the cause of the internal service error was a data type issue with `conduit_committee_zip` field, I created [this](https://github.com/fecgov/openFEC/issues/5722) ticket to implement a fix.
