### ISSUE TITLE
National Party Accounts DB work

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5733]
### What we’re after

Now that the [data design studio](https://github.com/fecgov/fec-cms/issues/6111) for the National Party Accounts data is finished, we should do the db work. 

Here's the previous db team research https://github.com/fecgov/openFEC/issues/5702

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)

 https://github.com/fecgov/openFEC/issues/5702

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)

- [x] MV's created for Schedule A and B National Party Data

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)

- [x] DB supports final designs for national party data

### References/resources/technical considerations

(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)

**Comment by JonellaCulmer** [comment]
@hcaofec Here are the final designs for the national party account data feature work. Let me know if you need anything else. 

### National party account datatable - schedule a
![Image](https://github.com/fecgov/openFEC/assets/31663028/8711453a-ddb5-4b62-972c-f2bee2da7015)

### National party account datatable - schedule b
![Image](https://github.com/fecgov/openFEC/assets/31663028/0bd85f06-6148-4504-ab1a-4d1dbddd0571)

### National party committee profile page - financial summary
![Image](https://github.com/fecgov/openFEC/assets/31663028/d0e0566d-d8d6-4617-8ba3-317748c5e682)

### National party committee profile page - raising tab
![Image](https://github.com/fecgov/openFEC/assets/31663028/17d9268d-c7fd-4388-a304-f99306a46d19)

### National party committee profile page - spending tab
![Image](https://github.com/fecgov/openFEC/assets/31663028/ee14cde7-2b1c-470e-9cd9-56f00db9c5b6)
