### ISSUE TITLE
Research removing restrictions for `/schedule_a/?contributor_state`

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5735]
### What we’re after

Research and load test removing restrictions for `contributor_state` filter on the `/schedule_a/` endpoint. We should limit to only 10 states in a single query. 

We currently have a restriction on `/schedule_a/?contributor_state` where a single `two_year_transaction_period` or one of the following filters: `committee_id`, `contributor_id`, `contributor_name`, `contributor_city`, `contributor_zip`, `contributor_employer`, `contributor_occupation`, `image_number`" need to be part of your query to search by contributor state. As a result, the state field is buried in the "more source details" accordion on the front end filters and hard to find for users as exhibited in this [ticket](https://github.com/fecgov/fec-cms/issues/5857). 

Example API call: https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&contributor_state=AK&sort=-contribution_receipt_date&per_page=30&is_individual=true

### Related ticket(s)

- [ ] https://github.com/fecgov/fec-cms/issues/5857

### Action item(s)

- [ ] Load test contributor state for `/schedule_a/` without current restrictions (adding the 10 state restriction)

### Completion criteria

- [ ] TBD

**Comment by cnlucas** [comment]
This will not be performant. Closing as we should not remove these restrictions.
