### ISSUE TITLE
Investigate statute keyword search issue - example text not searchable

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#5747]
**What we're after:**
The Statutes example search, found on the [statutes page](https://www.fec.gov/data/legal/statutes/) and [statutes search feature](https://www.fec.gov/data/legal/search/statutes/), is not working. The search yields "no results." The section symbol (§) and U.S.C. don't currently function as expected. Need to determine whether these were ever searchable and fix or identify new example text so as not to confuse statute search users. 

### Related issue(s):
https://github.com/fecgov/FEC/issues/13147

**Action items:**
- [ ] Investigate issue and identify fix
- [ ] Locate any additional places on the website that use this same functionality
- [ ] If needed, draft new Example text for the statutes page and statutes search page and other locations, if others exist

### Completion criteria
- [ ] Example text is now a legitimate searchable example for the statute search

**Comment by JonellaCulmer** [comment]
@pkfec The new example language for the statutes search will be "Examples: contribution; 52; 30123". As you mentioned before this will need to changed in two places: On the [statutes search](https://www.fec.gov/data/legal/search/statutes/?search=) and [statutes page](https://www.fec.gov/data/legal/statutes/).

We will also update the language in the information box at the top of the search. 

The last sentence will need to change FROM: "You can search statutes using keywords and/or statutory citations (full or partial)." 
TO: "You can search statutes using keywords from section titles and/or statutory citations."

**Comment by pkfec** [comment]
The current example terms "spending," "52 U.S.C. §30123," none of which yield results. The keyword search function exclusively searches for titles (e.g., 26 or 52) and sections (e.g., 9001 or 30109) or the document name description (e.g.,short title )

After discussing with @JonellaCulmer @patphongs @johnnyporkchops decision has be made to update the sample search terms  to provide either the titles (such as 26 or 52) or sections (such as 9001 or 30109 as shown in) in [statutes page](https://www.fec.gov/data/legal/statutes/) and [statutes search feature](https://www.fec.gov/data/legal/search/statutes/)

**Comment by pkfec** [comment]
Work is completed and merged in this PR https://github.com/fecgov/fec-cms/pull/6171
