### ISSUE TITLE
Research Throttling Schedule A and/or Pagination Requests 

### ISSUE THREAD

**Issue by tmpayton** [fecgov/openFEC#5760]
### What we’re after

We should research throttling Schedule A and/or pagination requests when the database reader is running on 4-5 instances. 

### Action item(s)

- [x] Research throttling schedule A and pagination
- [ ] Need to determine a way to throttle requests when users are hitting schedule A or using the parameter `last_index `
- [ ] Check the number of instances running in the cluster 

### Completion criteria

- [x] Research and next steps are documented 

### References/resources/technical considerations

https://docs.aws.amazon.com/cli/latest/reference/rds/describe-db-cluster-endpoints.html

**Comment by cnlucas** [comment]
This ticket is to add pg_sleep to slow down expensive queries when we are running at or near our max instances. Unfortunately, this method of throttling would increase overall resource consumption (the sleeping sessions would occupy DB resources while idle) and without setting up a separate queue for these types of queries it would prolong the expensive connections without freeing up connections for the less expensive queries. 
We need to do more research on our current pool size to see how frequently we are dipping into overflow (ongoing) and research further creating a separate queue before this could be implemented
