### ISSUE TITLE
Create elevated key template language

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5766]
### What we’re after

We should create an e-mail template for the back-end team to use when elevating our users' keys. We should consider including links to the bulk download page, links to the google group, links to our acceptable use policy  and encourage them to use non-peak hours if they can.

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)

- [x] Create and distribute the disclaimer language
- [x] Create a follow-up ticket to add the language to github and include the link to the github location in our swagger docs and bulk downloads page

**Comment by PaulClark2** [comment]
First draft: 

Thank you for using the Federal Election Commission’s (FEC) API. I have upgraded your key to 7,200 calls per hour (120 calls per minute). While using our API, please do not overload openFEC or prevent other users, including but not limited to FEC.gov, from accessing openFEC.

For more details about using the FEC’s API and FEC data, see FEC’s [sale and use policy](https://www.fec.gov/updates/sale-or-use-contributor-information/), FEC’s [privacy and security policy](https://www.fec.gov/about/privacy-and-security-policy/), openFEC API’s [acceptable use policy](https://github.com/fecgov/FEC/blob/master/ACCEPTABLE-USE-POLICY.md) and openFEC API’s [terms of service](https://github.com/fecgov/FEC/blob/master/TERMS-OF-SERVICE.md) (collectively, the "Agreement").

**Comment by PaulClark2** [comment]
Draft 2

Thank you for using the Federal Election Commission’s (FEC) API. I have upgraded your key to 7,200 calls per hour (120 calls per minute). While using our API, please do not overload openFEC or prevent other users, including but not limited to FEC.gov, from accessing openFEC.

For more details about using the FEC’s API and FEC data, see FEC’s [sale or use policy](https://www.fec.gov/updates/sale-or-use-contributor-information/), FEC’s [privacy and security policy](https://www.fec.gov/about/privacy-and-security-policy/), openFEC API’s [acceptable use policy](https://github.com/fecgov/FEC/blob/master/ACCEPTABLE-USE-POLICY.md) and openFEC API’s [terms of service](https://github.com/fecgov/FEC/blob/master/TERMS-OF-SERVICE.md) (collectively, the "Agreement").

**Comment by PaulClark2** [comment]
Draft 3

Thank you for using the Federal Election Commission’s (FEC) API. Your key has been upgraded to 7,200 calls per hour (120 calls per minute). While using openFEC API, please do not overload it or prevent other users, including but not limited to FEC.gov, from accessing it.

The FEC also provides bulk data files that might satisfy your data needs. You can review those files from the [Browse data page](https://www.fec.gov/data/browse-data/?tab=bulk-data).
For more details about using the FEC’s API and FEC data, see the [sale or use policy](https://www.fec.gov/updates/sale-or-use-contributor-information/), [privacy and security policy](https://www.fec.gov/about/privacy-and-security-policy/), [acceptable use policy](https://github.com/fecgov/FEC/blob/master/ACCEPTABLE-USE-POLICY.md) and [terms of service](https://github.com/fecgov/FEC/blob/master/TERMS-OF-SERVICE.md).

If you have questions about the API, please contact the FEC at [APIinfo@fec.gov](mailto:APIinfo@fec.gov). In addition, there is a community led [group](https://groups.google.com/forum/#!forum/fec-data) that discusses FEC data. FEC staff do not monitor this community led group.

**Comment by PaulClark2** [comment]
🔒 [final version](https://docs.google.com/document/d/1guGUMkyDbj0zBww7KJXuqo1AViUByHTZftYFpYX_35Y/edit) 🔒 

Thank you for using the Federal Election Commission’s (FEC) API. Your key has been upgraded to 7,200 calls per hour (120 calls per minute). While using openFEC API, please do not overload it or prevent other users, including but not limited to FEC.gov, from accessing it.

The FEC also provides bulk data files that might satisfy your data needs. You can review those files from the [Browse data page](https://www.fec.gov/data/browse-data/?tab=bulk-data).

For more details about using the FEC’s API and FEC data, see the [sale or use policy](https://www.fec.gov/updates/sale-or-use-contributor-information/), [privacy and security policy](https://www.fec.gov/about/privacy-and-security-policy/), [acceptable use policy](https://github.com/fecgov/FEC/blob/master/ACCEPTABLE-USE-POLICY.md) and [terms of service](https://github.com/fecgov/FEC/blob/master/TERMS-OF-SERVICE.md).

If you have questions about the API, please contact the FEC at [APIinfo@fec.gov](mailto:APIinfo@fec.gov). In addition, there is a community led [group](https://groups.google.com/forum/#!forum/fec-data) that discusses FEC data. FEC staff do not monitor this community led group.
