### ISSUE TITLE
Create a manual task to make new public api keys

### ISSUE THREAD

**Issue by tmpayton** [fecgov/openFEC#5802]
### What we’re after

We should create a manual task to create new public API keys and update our environment variables. 

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)

- [ ] https://github.com/fecgov/fec-accounts/issues/502

### Action item(s)

- [ ] Create a task to create new public api keys
- [ ] Create a task to update environment variables

**Comment by pkfec** [comment]
Work completed in https://github.com/fecgov/openFEC/pull/5826
