### ISSUE TITLE
 [Snyk:Low]  Flask-cors (Due: 07/23/2024) 

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5806]
### What we’re after

flask-cors Log Injection
Detailed paths

    Introduced through: project@0.0.0 › flask-cors@3.0.10
    Fix: No remediation path available. 

Security information
Factors contributing to the scoring:

    Snyk: [CVSS 3.1](https://security.snyk.io/vuln/SNYK-PYTHON-FLASKCORS-6670412) - Low Severity
    NVD: Not available. NVD has not yet published its analysis.

Why are the scores different? Learn how Snyk evaluates vulnerability scores
Overview

[Flask-Cors](https://www.pypi.org/project/Flask-Cors) is an A Flask extension adding a decorator for CORS support

Affected versions of this package are vulnerable to Log Injection when the log level is set to debug. A user can inject or modify messages by abusing CRLF sequences in the request path of a GET request.### Completion criteria

## Tech step
- [ ] Upgrade flask-cors

## Completion Criteria 
- [ ] We are no longer getting a snyk error

**Comment by tmpayton** [comment]
This snyk venerability will be remediated with [this](https://github.com/fecgov/openFEC/pull/5899/files) PR.
