### ISSUE TITLE
Add spender_committee_designation_full to national party account disbursements endpoint

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#5848]
### What we’re after
Need to add `spender_committee_designation_full` to the national party account disbursements endpoint. 

### Related issues
- [ ] fec-cms #6179 
- [ ] fec-cms #6180 
- [ ] #5786 

### Completion criteria
- [x] Endpoint updated with `spender_committee_designation_full`

**Comment by pkfec** [comment]
Work completed in pr https://github.com/fecgov/openFEC/pull/5865. Closing this issue
