### ISSUE TITLE
National party account data remove line number constraint from MV

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5850]
### What we’re after

Since line numbers can have outliers in schedule A and schedule B national party data, we should the constraint so that all data is included in the table. The only constraints should be the National party committee IDs and the National party transaction codes. Refreshing the MV will take a little bit of time due to the size of the data.

National party aggregate numbers are pulling from these materialized view. So it's not necessary to modify it.

### Related ticket(s)

- [ ] #5733 
- [ ] #5804 

### Completion criteria

- [ ] Remove line number contraint from MV
- [ ] Refresh MV

**Comment by patphongs** [comment]
@bmathesonFEC Please confirm if there are outliers to the schedule A line numbers. If so, it will be removed. cc @hcaofec

**Comment by bmathesonFEC** [comment]
I'm not finding any coded transactions on lines other than line 17; however, I think we should remove the line number constraints from both receipts and disbursements to ensure that any future wrong-line transactions are included on the data table.
