### ISSUE TITLE
[Snyk: Med] Resource Exhaustion (Due 7/29/24)

### ISSUE THREAD

**Issue by tmpayton** [fecgov/openFEC#5853]
Resource Exhaustion
Affecting [idna](https://security.snyk.io/package/pip/idna) package, versions [3.7)

How to fix?
Upgrade idna to version 3.7 or higher.

Overview
Affected versions of this package are vulnerable to Resource Exhaustion via the idna.encode function. An attacker can consume significant resources and potentially cause a denial-of-service by supplying specially crafted arguments to this function.

Note: This is triggered by arbitrarily large inputs that would not occur in normal usage but may be passed to the library assuming there is no preliminary input validation by the higher-level application.

##Completion Criteria

- [ ] Upgrade idna to version 3.7 or higher

**Comment by pkfec** [comment]
snyk cli no longer flag this as vulnerable. closing this issue
