### ISSUE TITLE
Research - Switch the elasticsearch analyzer to standard

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#5872]
### What we’re after

We want to test switching from using the Elasticsearch English analyzer to the Standard analyzer. This analyzer performs exact string matching without altering terms by stemming and ignoring common words. 

The analyzer will be switched for all documents EXCEPT archived MURs (since it will be resource intensive, we want to exclude this from the test for now).

We will then evaluate if the change is working for our needs. 

### Current setup
Currently, our API uses the [English analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/analysis-analyzers.html#analysis-analyzers) at both the index and field levels. This analyzer provides features such as stemming, stopword removal (like "to", "not", etc.), and keyword and lowercase normalization. However, this conflicts with what is desired by the legal users.

### Related ticket(s)

-  https://github.com/fecgov/openFEC/issues/5832
- Notes https://gist.github.com/markdboyd/904d39803ea340bad9e7c81a5414acc6#reserved-words

### Action item(s)

- [ ]  Update analyzer to standard while creating an index [global settings]( https://github.com/fecgov/openFEC/blob/develop/webservices/legal_docs/es_management.py#L406) and also under mapping settings for (individual fields)
- [ ] Reindex and upload documents to elasticsearch service on Dev space

### Completion criteria

- [ ] Document search should return results that match the exact string and include common words but exclude stem words from the search results
- [ ] Create a separate user testing ticket to test with legal users and our team

**Comment by tmpayton** [comment]
Link to PR https://github.com/fecgov/openFEC/pull/5887. Modify PR to include AO index.
