### ISSUE TITLE
[Snyk: Med] Improper Handling of Insufficient Permissions or Privileges (Due 09/16/24)

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#5877]
### Overview
[urllib3](https://pypi.org/project/urllib3/) is a HTTP library with thread-safe connection pooling, file post, and more.

Affected versions of this package are vulnerable to Improper Removal of Sensitive Information Before Storage or Transfer due to the improper handling of the Proxy-Authorization header during cross-origin redirects when ProxyManager is not in use. When the conditions below are met, including non-recommended configurations, the contents of this header can be sent in an automatic HTTP redirect.

https://security.snyk.io/vuln/SNYK-PYTHON-URLLIB3-7267250

### Workarounds
Using the Proxy-Authorization header with urllib3's ProxyManager.

Disabling HTTP redirects using redirects=False when sending requests.

Not using the Proxy-Authorization header.

### Introduced through: 
Introduced through: project@0.0.0 › elasticsearch@7.6.0 › urllib3@2.0.7
Introduced through: project@0.0.0 › requests@2.31.0 › urllib3@2.0.7
Introduced through: project@0.0.0 › elasticsearch-dsl@7.3.0 › elasticsearch@7.6.0 › urllib3@2.0.7

### Remediation:
upgrade  urllib3@1.26.19 

### Completion criteria:
- [ ] upgrade urllib3 to version 1.26.19 or latest and verify snyk cli no longer flags requests as vulnerable package

**Comment by tmpayton** [comment]
Closing this ticket, because snyk no longer flags this as an issue and we are currently using urllib3 version 2.2.2. 
![image](https://github.com/user-attachments/assets/0f8e3b3f-6d54-44bb-a4be-a7cf5c5a8a24)
