### ISSUE TITLE
MURs, AFs, ADRs - Remove name and  number from keyword search

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5949]
### What we’re after

Refine the MUR, AF, and ADR document keyword search by removing the number and name from the search. This change is intended to enhance search accuracy, ensuring that keyword searches focus solely on the content within `document.text` and `document.description`. 

This will NOT be done for statutes, as we need number and name for that search.

### Related issues
- [x] #5948 

### Completion criteria

- [x] MUR, AF, and ADR number and name are successfully removed from the document keyword search functionality.

**Comment by pkfec** [comment]
Work completed in pr https://github.com/fecgov/openFEC/pull/5959. Closing this issue

**Comment by pkfec** [comment]
work completed in pr https://github.com/fecgov/openFEC/pull/5963. Closing this issue
