### ISSUE TITLE
AO_category filter bug

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5958]
### What we’re after

https://api.open.fec.gov/v1/legal/search/?q=coordinated&api_key=DEMO_KEY&ao_category=F&ao_is_pending=True

There shouldn't be any pending AO's with final opinions, but a pending AO without a final opinion is showing up even when the ao_category=F filter is added

This is also true for ao_category=W. 

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)

- [ ] When ao_category filter is added only AO's with a final opinion should show

**Comment by pkfec** [comment]
Reached out to Jason about the discrepancy with AO 2024-07 description that i noticed on the website. On both the website and in our backend resource (Postgres database), the description text for the final opinion appears to be different from the other AOs. Specifically, for AO 2024-07, the description text is listed as "2024-11." It should be "2024-07" instead. Jason corrected that description text to 2024-07 later.
**Before:**
<img width="985" alt="Screenshot 2024-09-03 at 6 04 26 PM" src="https://github.com/user-attachments/assets/734bfa19-ecb7-42ac-8662-4d24dff799a6">

<img width="1066" alt="Screenshot 2024-09-03 at 11 32 15 AM" src="https://github.com/user-attachments/assets/42d70545-5429-4575-85e8-74355b76bfbb">

**Comment by pkfec** [comment]
No pending AO's showing on the [API](https://api.open.fec.gov/v1/legal/search/?q=coordinated&api_key=DEMO_KEY&ao_category=F&ao_is_pending=True) as of today. Closing this issue as there is no correction needed
