### ISSUE TITLE
Build subject categories filter for current MURs and ADRs

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5965]
### What we’re after

Create a subject categories filter for current MURs and ADRs by using the existing `/legal/search/` endpoint. We'll pass one parameter,`case_subject=string`. This will do a keyword match for subjects and filter the list of cases accordingly.  

Front-end can send the parameter through without the `:`.

Subjects include:

1. Allocation
2. Committees
3. Committees: Candidate
4. Committees: Multi-candidate
5. Committees: Non-party
6. Committees: PAC
7. Committees: Party 
8. Committees: Political
9. Committees: Presidential
10. Contributions
11. Contributions: Corporations
12. Contributions: Excessive
13. Contributions: Exemptions
14. Contributions: In the name of another
15. Contributions: Labor unions
16. Contributions: Limitations
17. Contributions: National bank
18. Contributions: Prohibited
19. Disclaimer
20. Disbursements
21. Electioneering
22. Expenditures
23. Expenditures: Coordinated
24. Expenditures: Exemptions
25. Expenditures: Limits
26. Expenditures: Prohibitions
27. Express advocacy
28. Foreign nationals
29. Fraudulent misrepresentations
30. Issue advocacy
31. Knowing & willful
32. Loans
33. Non-federal
34. Other
35. Personal use
36. Presidential
37. Reporting
38. Soft money
39. Solicitation

### Action item(s)

- [ ] We should cross check the subjects based on the database fields for [subject](https://fecgov.slack.com/files/U3R9P66LC/F07LYTM42GG/subject.csv) and [related subject](https://fecgov.slack.com/files/U3R9P66LC/F07LA1BJRFD/relatedsubject.csv)
- [ ] Add filter parameter for `case_subjects` for only ADRs and MURs. Filter will use exact string match.

### Completion criteria

- [ ] `case_subject` is now a filterable query parameter

**Comment by cnlucas** [comment]
Archived MUR will not be included see https://fecgov.slack.com/archives/C3W9XBBJL/p1726690196063319?thread_ts=1726689628.467149&cid=C3W9XBBJL
