### ISSUE TITLE
Add AO number sort capability

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5967]
### What we’re after

Add capability to sort by AO number ascending and descending to `/legal/search?type=advisory_opinions` by passing the sort parameters `sort=ao_no` and `sort=-ao_no`.

### Completion criteria
- [x] Can sort by AO number

**Comment by pkfec** [comment]
sort by ao_no is available in /legal/search/ endpoint:

ascending order: https://api.open.fec.gov/v1/legal/search/?type=advisory_opinions&sort=ao_no&api_key=DEMO_KEY
descending order: https://api.open.fec.gov/v1/legal/search/?type=advisory_opinions&sort=-ao_no&api_key=DEMO_KEY
