### ISSUE TITLE
Research issue with ADR citations not appearing consistently

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5985]
### What we’re after

ADR citations removed since it wasn't populating consistently. There are few cases where citations data is available for example ADR 954, 981, 123 etc. We need to research why all ADRs do not have citations populated.

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)

- [ ] Speak to ADR team/Jennie Boyt about what citations they expect for ADRs  

### Completion criteria

- [ ] Determine if citations are needed at all for ADRs
- [ ] if citations are needed, create a follow up ticket to fix issues with ADR citations

**Comment by cnlucas** [comment]
We want citations in dispositions. Implementation ticket [here](https://github.com/fecgov/openFEC/issues/6006)
