### ISSUE TITLE
Search penalty amount by respondent (MURs, ADRs and Admin fines)

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5986]
### What we’re after

We should add penalty amount by respondent

Penalties are frequently non-monetary so this should be considered (null is different then zero) 

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)

- [ ]

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)

- [ ] Penalty amount by respondent is available for Murs, ADRs and Admin fines 

### Designs
![Image](https://github.com/user-attachments/assets/fe533434-51d0-4d37-872e-c96b1cb6c865)

**Comment by cnlucas** [comment]
Fixed by #6023
