### ISSUE TITLE
Add respondents filter capability for archived MURs

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#6019]
### What we’re after

Archived MURs contain a list of respondents, and we need to ensure these are included in the `case_respondents` filter to allow for filtering by respondent names across the entire MUR dataset.

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)

- [ ] Decide if we need one or two filters 

### Completion criteria

- [ ] Archived MURs are now included in the case_respondents filter

**Comment by cnlucas** [comment]
Fixed by PR #6023
