### ISSUE TITLE
Remove unpublished final MUR disposition categories

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#6041]
### What we’re after

We want to remove some final disposition categories from the list as they are not needed. 

List that is required:
- Conciliation: Pre Probable Cause
- Conciliation: Probable Cause
- Dismiss and Remind
- Dismissed
- Dismissed-Low Rated
- Dismissed-Other
- Dismissed-Stale
- Dismiss pursuant to prosecutorial discretion
- Dismiss pursuant to prosecutorial discretion, and caution
- Enforcement - Disposition - Dismissed “Dismiss” - Dismiss and Caution
- No PCTB
- No RTB
- PCTB Finding
- Probable Cause/NFA
- RTB Finding
- RTB/NFA
- Take no action
- Take No Further Action

List to remove:
- Approved by Commission
- Approved In Part Recs.
- Approved Recs.
- Case Activated
- Case Activation
- Dismissed – Agreement Rejected
- Failed to Approve Recs.
- First General Counsel Report
- Formal Discovery Authorized
- Investigative Activity
- Mailed to Respondent
- Merged
- Offer from Respondent Received
- Other
- PC Brief
- PC Conciliation Approved
- Pre-PCC Commenced
- Received 
- Received from Audit Division
- Received from Commission
- Received from OGC
- Received from RAD
- Request for Extension of Time Approved
- Request for Extension of Time Approved/Denied
- Request for Extension of Time Received
- Response Received
- Settlement Agreement
- Suit Authorization
- To Respondent
- Transferred to ADR

### Related ticket(s)

- [x] https://github.com/fecgov/fec-cms/issues/6538

### Action item(s)

- [x] Update the data to only have the required list of dispositions. The `dispositions` list is a list of objects. We need to remove the entire object that contains the disposition category we want removed. 
- [x] Re-index with elasticsearch after this change is made
- [x] fecgov/fec-cms#6546

### Completion criteria

- [x] MUR disposition category is updated

**Comment by pkfec** [comment]
MUR disposition categories are now down to 18. API work is completed in pr https://github.com/fecgov/openFEC/pull/6047
